### ISSUE TITLE
Report has 2 different approvers but there is nothing to approve

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#51146]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.51-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @jliexpensify 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1729202845455229

## Action Performed:

1. SmartScan receipt
2. See that the Unexpected Error issue is still happening
3. Remove receipt from Report

## Expected Result:
Report is approved by approver 1 and should have system message that waiting for approver 2 to approve
## Actual Result:
Header says waiting for approver 2 to approve the report, but system message doesn't mentions about waiting for approver 2

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>
![Snip - (3) New Expensify - Google Chrome (2)](https://github.com/user-attachments/assets/1dd4182d-3825-48df-82db-e5ea2075a7f7)
![image (2)](https://github.com/user-attachments/assets/eeef84dc-e952-41b7-b467-64555972baa4)

  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by truph01** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Header says waiting for approver 2 to approve the report, but system message doesn't mentions about waiting for approver 2

### What is the root cause of that problem?
- In case of ```FORWARDED``` message type, we only display ```approved ${amount}```:

https://github.com/Expensify/App/blob/13f41cbb09510cdf6b9e039ed121397676efc04e/src/libs/ReportUtils.ts#L4680
### What changes do you think we should make in order to solve the problem?
- We should display something like:  ```approved and forwarded this report```. To do it, we need to udpate:

https://github.com/Expensify/App/blob/13f41cbb09510cdf6b9e039ed121397676efc04e/src/languages/en.ts#L924

```
        forwardedAmount: ({amount}: ForwardedAmountParams) => `approved and forwarded this report`,
```

### What alternative solutions did you explore? (Optional)

**Comment by garrettmknight** [comment]
Discussing in slack thread on this one. Not a bug, but we may decide to update copy or design.

**Comment by MitchExpensify** [comment]
This was deemed not to be a bug [here](https://expensify.slack.com/archives/C049HHMV9SM/p1729527885177589?thread_ts=1729202845.455229&cid=C049HHMV9SM) but I think I agree with @jliexpensify that the experience could be improved with a "XXX approved and forwarded to YYY" 
<img width="541" alt="image" src="https://github.com/user-attachments/assets/3635a5c6-0c3f-42d5-96c6-b2c6d3a06b61">

Are you passionate enough about that to push for the change @jliexpensify ?

**Comment by jliexpensify** [comment]
Huh, yeah I don't know why this GH got created 🤷‍♂️ 

@Expensify/design [the conversation stalled after my suggestion in-thread](https://expensify.slack.com/archives/C049HHMV9SM/p1729544445125909?thread_ts=1729202845.455229&cid=C049HHMV9SM) but is this something that can be changed?

**Comment by dubielzyk-expensify** [comment]
I think even just a clarifying string like you suggested in Slack would be good. cc @trjExpensify

**Comment by dannymcclain** [comment]
Agree—added my thoughts to the thread.

**Comment by MitchExpensify** [comment]
Seeing what next steps we agree on here: https://expensify.slack.com/archives/C049HHMV9SM/p1730160336700109?thread_ts=1729202845.455229&cid=C049HHMV9SM
