### ISSUE TITLE
Expense - In dependent tags dropdown, normal tags are displayed

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#51163]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** V9. 0.51-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Y
**Issue reported by:** Applause Internal Team

## Action Performed:
Pre-condition: As admin, have a workspace with tags enabled & created 

1. Go to https://staging.new.expensify.com/home
2. As employee login mweb, create an expense with tag selected
3. As admin, upload dependent tags in old dot attached below
4. As employee, open the employee workspace chat
5. Open the expense already created and note the error "state no longer valid".
6. Tap state
7. Note the normal tag used previously is displayed under dependent tag dropdown list.

## Expected Result:
In dependent tags dropdown, normal tags must not be displayed and "state no longer valid" error also must not be displayed.

## Actual Result:
In dependent tags dropdown, normal tags are displayed and "state no longer valid" error is displayed.

## Workaround:
Unknown

## Platforms:

- [x] Android: Standalone
- [x] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/a81e8df4-06c7-43a4-aeda-809cc95f4802

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by IuliiaHerets** [comment]
@sakluger  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by ChavdaSachin** [comment]
Option is greyed out, so it looks good enough to me.

**Comment by FitseTLT** [comment]
BE issue, it should not set the previously set tag to the newly added dependent tag.

**Comment by sakluger** [comment]
@IuliiaHerets fyi - I would consider all tags as "normal tags". In the future, if you need to differentiate between different types of tags, can you be more specific? Please use the terms "single-level tags", "independent multi-level tags", and "dependent multi-level tags".

**Comment by sakluger** [comment]
I think it's correct that we're showing the old tag still. Here's the screen I'm talking about that I think is correct:

<img width="292" alt="image" src="https://github.com/user-attachments/assets/7da91354-f61a-4af9-bfb5-dc794303124f">

I do agree though that the error message is incorrect. We should show `Tag out of workspace` instead of `State no longer valid`.

**Comment by sakluger** [comment]
Turns out there is no bug here - “Not a valid state” is referring to the “state” tag level.
