### ISSUE TITLE
Expense - Expense fields are editable after the workspace is deleted

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#51164]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.51-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5102033
**Email or phone of affected tester (no customers):** applausetester+kh081006@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Create a workspace.
3. Submit an expense.
4. Delete the workspace.
5. Go to the transaction thread.
6. Edit any fields.

## Expected Result:
The expense fields should be disabled and not be editable after the workspace is deleted.

## Actual Result:
The expense fields are not disabled and are editable after the workspace is deleted.

## Workaround:
Unknown

## Platforms:

- [x] Android: Standalone
- [x] Android: HybridApp
- [x] Android: mWeb Chrome
- [x] iOS: Standalone
- [x] iOS: HybridApp
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/4d35a9fa-1fa3-4c9d-a10e-528a5c25888c

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by IuliiaHerets** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by IuliiaHerets** [comment]
@muttmuure  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by ChavdaSachin** [comment]
https://github.com/Expensify/App/issues/50352#issuecomment-2398009718
This was my Proposal for exactly similar issue, and I suggested a complete solution where we might be able to completely solve this GH and any similar future issues we might face.

**Comment by FitseTLT** [comment]
This might be expected as open expense requests are not archived when the workspace is archived. Tagging @trjExpensify for context.

**Comment by trjExpensify** [comment]
The workspace being deleted doesn't mean you can't edit the details of the expenses on the expense report if it's in a state you could edit them prior to deletion. What you shouldn't be able to do is 1) add new expenses to it or 2) submit, approve or pay it. Those restrictions/action buttons are being worked on in another issue though.

**Comment by aldo-expensify** [comment]
> The workspace being deleted doesn't mean you can't edit the details of the expenses on the expense report if it's in a state you could edit them prior to deletion. What you shouldn't be able to do is 1) add new expenses to it or 2) submit, approve or pay it. Those restrictions/action buttons are being worked on in another issue though.

What is the purpose of allowing editing the expense in an archived workspace? There is a new related issue here: https://github.com/Expensify/App/issues/52896 where the backend doesn't update correctly an expense that belongs to an archived room.

I'm just asking because it may be easier to prevent this in the frontend. Is it a real user case that someone may want to edit an expense in an archived workspace?

**Comment by trjExpensify** [comment]
>What is the purpose of allowing editing the expense in an archived workspace?

Backwards compatibility with OldDot at this juncture, mainly. Expense reports don't change state when a policy is deleted (i.e gets moved to "closed"). We don't prevent editing expense details on the expense reports outside of the usual report state restrictions, nor prevent commenting on them, nor most actions really. We do prevent onward actions on the policy like approve/pay, and give you the ability to move the expense report to another workspace to continue those. The latter of which we're hoping to bring to NewDot soon as well.

**Comment by aldo-expensify** [comment]
I see, thanks! then the expected behaviour in https://github.com/Expensify/App/issues/52896 is correct in expecting the backend to do the modification correctly 🙇
