### ISSUE TITLE
Search - Search does not returns group when entering group members

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#51175]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.51-2
**Reproducible in staging?:** Y
**Reproducible in production?:** N/A - new feature, doesn't exist in prod
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5107189&group_by=cases:section_id&group_order=asc&group_id=229066
**Email or phone of affected tester (no customers):** gocemate+a2595@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Create group chat and invite two users (for example [bob@domain.com,](mailto:bob@domain.com,) and [alice@domain.com](mailto:alice@domain.com))
2. Go to chat search and enter member's emails ( bob@domain.com and alice@domain.com)

## Expected Result:
The search should displays the group

## Actual Result:
Search does not returns group when entering group members

## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/c4891981-f200-446f-9746-92c3b025b5a2

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mjasikowski** [comment]
checking

**Comment by mjasikowski** [comment]
caused by https://github.com/Expensify/App/pull/48652 according to git bisect

**Comment by mjasikowski** [comment]
Revert in progress

**Comment by mjasikowski** [comment]
FYI this happens when group member names are separated by whitespace only. It works fine if you enter the names separated by comma and a space (like they are in the group chat title), but nevertheless - this is a bug.

**Comment by hannojg** [comment]
Huh the PR has been reverted and is said to be deployed to staging. If i try to reproduce this on staging it seems like I can't retrieve a group by searching for its members there either:


https://github.com/user-attachments/assets/7f5045d0-72de-4200-8792-61c6dd9e9d46



if i am not mistaken a few weeks ago the functionality to search for groups/reports by their participants had been removed here:

- https://github.com/Expensify/App/pull/47229

![Screenshot 2024-10-23 at 15 01 47](https://github.com/user-attachments/assets/91b2623b-ebe2-4749-b5f5-c2a332ac57be)
