### ISSUE TITLE
Login - Login with new gmail account, user directed to concierge chat

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#51179]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** V9. 0.51-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/home
2. Login with a new gmail account
3. Finish onboarding by selecting "something else"
4. Enter first name and complete the flow

## Expected Result:
Login with new gmail account, user must be directed to LHN.

## Actual Result:
Login with new gmail account, user directed to concierge page.

## Workaround:
Unknown

## Platforms:

- [x] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/776d6d76-4d97-45f8-b52e-632f5866d8ec

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by IuliiaHerets** [comment]
@RachCHopkins  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by RachCHopkins** [comment]
This is not a bug. As part of Guided Setup we end with Concierge. If they don't do the other steps, then they start with Concierge:

<img width="1050" alt="image" src="https://github.com/user-attachments/assets/790b1141-a4c2-44bf-8826-1eb7d048502e">

And then they can message for advice on what to do.
