### ISSUE TITLE
LHN is filtering based on the system messages

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#51188]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.51-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @JmillsExpensify 
**Slack conversation:** https://expensify.slack.com/archives/C05LX9D6E07/p1729502981173039

## Action Performed:
1. Set the preference to "Most recent"
2. Look at the LHN
## Expected Result:
Messages should get sorted with real user actionable messages
## Actual Result:
Messaged sorted with system messages  which are non actinable
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>
![CleanShot 2024-10-21 at 11 26 47](https://github.com/user-attachments/assets/13f39d42-5538-48c3-96e3-64132d84ea62)

  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by JmillsExpensify** [comment]
We're going to handle this one internally.

**Comment by muttmuure** [comment]
@deetergp are you taking this one as part of #quality?

**Comment by JmillsExpensify** [comment]
I posted in #whatsnext on this one. Shipping the pre-design this week.

**Comment by JmillsExpensify** [comment]
In fact, I'm going to close this issue in favor of an issue in E/E for design doc tracking.
