### ISSUE TITLE
[HOLD for payment 2024-11-13] [$250] iOS - Search - Search page cannot be dismissed by swiping to the right

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#51191]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.51-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+kh081006@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Launch hybrid app (or standalone ND app)
2. Tap on the search icon on the top right
3. Swipe to the right to dismiss the search page (iOS swiping style)

## Expected Result:
The search page can be dismissed by swiping to the right (the old Find page can be dismissed by swiping to the left)

## Actual Result:
The search page cannot be dismissed by swiping to the right

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [x] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/b990bd6b-f5fc-43f4-9b9f-be90272ea096

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021851376677882025777</li>
        <li>Upwork Job ID: 1851376677882025777</li>
        <li>Last Price Increase: 2024-10-29</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @anmurali</details>

**Comment by lanitochka17** [comment]
@anmurali  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by SzymczakJ** [comment]
Yes, I've set modal type to `CENTRED_UNSWIPABLE` on purpose because SelectionList behaved really strange(go on and test it yourself) on `CENTRED` modal. I didn't realise that it will break the swipe right pattern on iOS though.
Unfortunately I don't have a straightforward solution for this, I guess we will have to fix SelectionList behaviour on `CENTRED_UNSWIPABLE` modals.
I could take a look at it, after finishing this PR https://github.com/Expensify/App/pull/51237, so it can take me like 1-2 days.

**Comment by anmurali** [comment]
I'll let @ishpaul777 review proposals

**Comment by QichenZhu** [comment]
Please check out the [comment](https://github.com/Expensify/App/issues/51191#issuecomment-2441875581) by @SzymczakJ from Software Mansion.

**Comment by SzymczakJ** [comment]
Fix ready for your review @ishpaul777 😄

**Comment by MitchExpensify** [comment]
offer sent @ishpaul777 !

**Comment by MitchExpensify** [comment]
Paid / contract ended, thanks @ishpaul777
