### ISSUE TITLE
Search - Unable to delete expense when there is message in the combined report

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#51194]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.51-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** applausetester+kh081006@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to FAB > Submit expense > Manual.
3. Submit an expense to a user that has no unsettled expense.
4. Go to Search.
5. Click on the expense.
6. Send a message.
7. Close the report RHP.
8. Select the expense via checkbox.
9. Click on the dropdown > Delete.
10. Delete the expense.
11. Click on the expense.
12. Repeat Step 1 to 10 but do not add a message to the combined report (exclude Step 5 to 7).

## Expected Result:
The expense will be deleted.

## Actual Result:
The expense cannot be deleted on Search page when there is message in the combined report.

This issue is not reproducible when the combined report has no message (Step 12).

This issue is not the same as https://github.com/Expensify/App/issues/43415
because in this issue, the expense is not deleted at all.

## Workaround:
Unknown

## Platforms:

- [x] Android: Standalone
- [x] Android: HybridApp
- [x] Android: mWeb Chrome
- [x] iOS: Standalone
- [x] iOS: HybridApp
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/45c11c0c-3a5e-4e64-a165-e2fec4b6bef5

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by IuliiaHerets** [comment]
We think that this bug might be related to #wave-control

**Comment by IuliiaHerets** [comment]
@adelekennedy  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by huult** [comment]
We received an error response from the backend when calling `DeleteMoneyRequestOnSearch`.
```diff
  {
      "jsonCode": 500,
      "message": "500 Unhandled Exception",
      "onyxData": [],
      "requestID": "8d6a860d4af6e2e2-HKG"
  }
```

Could @adelekennedy please obtain the backend error log for me? I would like to determine whether this issue can be fixed from the frontend. Thank you!

**Comment by adelekennedy** [comment]
I'm really struggling to reproduce this one as it's edge case enough that I think this would be a little difficult to reproduce and so many other search issues are being prioritized I am going to close this for now
