### ISSUE TITLE
[$250] Set HybridApp Testflight environment to staging

### ISSUE THREAD

**Issue by puneetlath** [Expensify/App#51193]
Right now, when you use the HybridApp Testflight app, it is treated as a production app. This means our debugging tools are not available to use. Ideally, we should make it so that the HybridApp testflight is treated as a staging app. Just like the NewExpensify staging app is. That way we'll have access to the debug mode and various debugging tools. 

cc @AndrewGable @staszekscp  
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021848496225680121076</li>
        <li>Upwork Job ID: 1848496225680121076</li>
        <li>Last Price Increase: 2024-10-21</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

**Comment by AndrewGable** [comment]
Code in question is here: https://github.com/Expensify/App/blob/main/src/libs/Environment/getEnvironment/index.native.ts#L32-L36

**Comment by situchan** [comment]
Happy to review this as C+ since [this bug](https://github.com/Expensify/App/issues/50843) I've been reviewing is related this one.

**Comment by VictoriaExpensify** [comment]
Thanks @situchan - assigned.

**Comment by situchan** [comment]
Asked confirmation [here](https://github.com/Expensify/App/issues/50843#issuecomment-2428357985)

**Comment by situchan** [comment]
yes dupe

**Comment by staszekscp** [comment]
Hey! 👋 I've left an update [here](https://github.com/Expensify/App/issues/50843#issuecomment-2428711462), since this is a duplicated issue!

**Comment by puneetlath** [comment]
Ah cool, I'll close this one.
