### ISSUE TITLE
Web - Whisper - User receives 'not here' error when accessing shared whisper link

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#51195]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.51
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Copied a link to a whisper in a chat
2. Sent it to another user who does not have access to that whisper but does have access to the chat
3. Had that user click the link

## Expected Result:
The user should be taken to the whisper as if they just opened it, and no comment should be linked

## Actual Result:
The user sees a page stating, "hmm it's not here."

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/80919e05-2fea-4e50-b433-02fa656f07e3

![Bug6629048_1728446110556!Step_2](https://github.com/user-attachments/assets/9d8a2f7d-fcc1-4b14-b4ef-45e472cb6dcd)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Christinadobrzyn** [comment]
The OP isn't filled out completely but first, I don't think we want people to be able to copy a whisper to another chat thread - asking - https://expensify.slack.com/archives/C06ML6X0W9L/p1729566739640599

**Comment by FitseTLT** [comment]
> The OP isn't filled out completely but first, I don't think we want people to be able to copy a whisper to another chat thread - asking - https://expensify.slack.com/archives/C06ML6X0W9L/p1729566739640599

I agree with you.

**Comment by Christinadobrzyn** [comment]
Yeah let's close this- a whisper shouldn't be shared.
