### ISSUE TITLE
Web - Workspace Chat - Edited/Deleted Messages Stay After Workspace Deletion

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#51199]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.51
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Navigate to staging.new.expensify..com
2. Create workspace
3. Go to #announce room
4. Switch to offline mode
5. Send 3 messages to the room
6. Delete the first message and edit the second message
7. From other device delete the workspace
8. Come back online

## Expected Result:
Messages added in offline mode should disappear when other user delete the workspace

## Actual Result:
After deleting the workspace and reconnecting, error messages appear for each message that was added/edited offline. The messages and red dot remain visible even if the page is refreshed
By pressing the close button on each error message, the user can delete them

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/2aa2e34f-4adf-4a0c-9b7f-80beca48bc3d

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@trjExpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by trjExpensify** [comment]
@lanitochka17 can you tell me where this expected result is coming from? A link to the test rail or something. Thanks! 

>Messages added in offline mode should disappear when other user delete the workspace

**Comment by trjExpensify** [comment]
CC: @m-natarajan

**Comment by lanitochka17** [comment]
@trjExpensify This issue was found when executing EDGE test case:
Issue to retest: https://github.com/Expensify/App/issues/32529
Internal issue (ignore): https://github.com/Expensify/Expensify/issues/365980

**Comment by trjExpensify** [comment]
Cool, so the test is: 

> 1. Create a workspace if you don't have one
> 2. Go to the #admins or #announce chat of the workspace
> 3. Go offline
> 4. Send 3 messages
> 5. Edit the first message and delete the 2nd message
> 6. From another device on the same account, delete that workspace
> 7. Back to the main device, go back online
> 8. **Verify each message has an error message and a reduced opacity**
> 9. Close the error message one by one
> 10. **Verify the messages are removed one by one once you're dismissing the errors**

That matches the actual results: 

>**Actual Results**
>After deleting the workspace and reconnecting, error messages appear for each message that was added/edited offline. The messages and red dot remain visible even if the page is refreshed
>By pressing the close button on each error message, the user can delete them

Closing!
