### ISSUE TITLE
[$250]  Android - Hybrid app - Login - Unable to select email after going back and starting over

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#51190]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.51.2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Open the hybrid app
2. Select the Continue with Email option
3. Enter an email and proceed to the magic code / join step
4. Tap the back icon
5. Select the Continue with Email option again
6. Long/double tap the previously entered email to select it and get the context menu

## Expected Result:
User is able to select the previously entered entered email

## Actual Result:
Nothings happens when long/double tapping the email

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [x] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/07092221-bd54-4b47-85e0-d27e95d9f85a

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021848750623798530077</li>
        <li>Upwork Job ID: 1848750623798530077</li>
        <li>Last Price Increase: 2024-10-22</li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
@lschurr  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lschurr** [comment]
Hi @lakchote! Are you able to pick this one up since we need an internal engineer to work on it?

**Comment by lakchote** [comment]
@lschurr yes I'm picking this one up.

**Comment by lakchote** [comment]
Encountering issues so far to have a valid HybridApp environment running ([Slack](https://expensify.slack.com/archives/C03TQ48KC/p1730305529148279?thread_ts=1730303354.728069&cid=C03TQ48KC)).

**Comment by lakchote** [comment]
Fixed the issues, but I'm unable to reproduce the testing conditions e.g the context menu doesn't appear at all like in the video when I'm running the Android simulator.

Asked in #engineering-chat if someone with an Android can test in on the latest HybridApp build to see if the issue still exists.

Also reached out in DM with @Julesssss to see if he can reproduce, since he's more familiar with Android.

**Comment by Julesssss** [comment]
Can reproduce

https://github.com/user-attachments/assets/15a27849-37cb-413f-9eeb-d0f9e282ed33

**Comment by lakchote** [comment]
Unfortunately I'm not able to have a working HybridApp environment anymore.

I've spent some time debugging, and testing potential solutions, without success (see [this](https://expensify.slack.com/archives/C01GTK53T8Q/p1730380671761429?thread_ts=1730121870.217109&cid=C01GTK53T8Q) discussion).

I have to switch to other issues in the meantime to not spend too much time on it.

**Comment by lakchote** [comment]
I've been able to have a working environment again ([link](https://expensify.slack.com/archives/C01GTK53T8Q/p1730384679069029?thread_ts=1730121870.217109&cid=C01GTK53T8Q)). Will report tomorrow on my advancements.

**Comment by lakchote** [comment]
I’m still having trouble with my dev environment, problems I didn't have before. 

Specifically, I need to ensure that Metro is running correctly to enable live code changes without having to rebuild the entire app each time. Rebuilding the app takes approximately 15 minutes, which significantly slows down my workflow while trying to fix the bug.

Asked for help in #expensify-open-source [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1730732187612759). 

cc @Julesssss since you might be able to help.

**Comment by lakchote** [comment]
Still working on it.

**Comment by lschurr** [comment]
Not overdue - @lakchote just commented here: https://github.com/Expensify/App/issues/51190#issuecomment-2455004671

**Comment by lakchote** [comment]
I've tried to modify [AuthenticationInputFormViewHolder.kt](https://github.com/Expensify/Mobile-Expensify/blob/main/Android/src/yapl/android/navigation/views/authentication/forms/AuthenticationInputFormViewHolder.kt#L107) and [authentication_input_form_fragment.xml](https://github.com/Expensify/Mobile-Expensify/blob/main/Android/res/layout/authentication_input_form_fragment.xml#L35) to make the context menu appear, without success.

Here's what I tried in `AuthenticationInputFormViewHolder.kt` for `editText`:

- setTextIsSelectable(true)
- isLongClickable = true
- isFocusableInTouchMode = true
- added explicit long click listener with `setOnLongClickListener`
- tried showContextMenu()

Likewise in `authentication_input_form_fragment.xml` I've tried:

- android:textIsSelectable="true"
- android:longClickable="true"
- android:focusableInTouchMode="true"

Is there anything that rings a bell to you when you look at the code in `AuthenticationInputFormViewHolder.kt`?

**Comment by Julesssss** [comment]
Hey @lakchote. I think those are good starting points and valid flags to try applying. 

The InputView will have these flags and they can either be set by XML or in code. My guess would be that these flags are set by default or with your XML changes, but then something causes them to be changed during login. To override the XML in code it would look something like this: `inputName.setTextIsSelectable()` or similarly named for the other View flags. 

Let me know if that doesn't make sense.

**Comment by lakchote** [comment]
Thanks for your answer. Having taken a quick look at the different setters for the properties above, there's nowhere where we set them up and override the default settings, in appearance. Will have to look deeper but I won't be able to in the next few days as I'll be focusing on a #stability [issue](https://github.com/Expensify/Expensify/issues/430306#top).

**Comment by lakchote** [comment]
@Julesssss any chance you can take a look into this? 🙏

**Comment by Julesssss** [comment]
Sorry, no I have a few critical convert issues currently, then need to open source HybridApp.

**Comment by lakchote** [comment]
I've taken a look today again, but still didn't manage to find a solution. I'm still stuck.

**Comment by lakchote** [comment]
Since the context menu doesn't show after transitioning to the next form and going back, I'm investigating into `this._invokeViewMethod('transitionToForm', args);`.

**Comment by twisterdotcom** [comment]
Relabelling as Lauren is OOO now.

**Comment by lakchote** [comment]
I found the fix to the issue. [PR](https://github.com/Expensify/Mobile-Expensify/pull/13292) is in review.

Found out the issue also impacted the `Continue with phone number` option.
