### ISSUE TITLE
iOS - Hybrid app - App crashes when switching between OD and ND several times

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#51206]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.51.3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://github.com/Expensify/App/pull/51155
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Open the hybrid app and log in
2. Select Try new Expensify or Switch to Expensify Classic deepening on where user lands after login
3. Repeat step 2 several times

## Expected Result:
The app does not crash

## Actual Result:
The app crashes after switching 5-8 times

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [x] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/9f89e9c3-d70f-4bcd-bcc3-c128d41ddc64

[log.txt](https://github.com/user-attachments/files/17467582/log.txt)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@stephanieelliott  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by stephanieelliott** [comment]
> The app crashes after switching 5-8 times

This feels very edge case, I don't think we need to prioritize fix for this
