### ISSUE TITLE
Android - Onboarding -Onboarding modal is missing

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#51205]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** .9.0.51
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://github.com/Expensify/App/pull/50979
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Open the Hybrid app.
2. Log in with new gmail account
3. Close the app
4. Enable the option "Try new Expensify"
5. Reopen the app and log in if needed
6. Tap on the "Try new Expensify" option.

## Expected Result:
The Onboarding modal is displayed

## Actual Result:
A Welcome message is displayed but the Onboarding modal is missing

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [x] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/b51b8294-6513-4476-ab7b-568557be8449

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@abekkala  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by CyberAndrii** [comment]
I think it's the expected behavior that the onboarding modal is not shown for OldDot accounts. This will require a BE fix if we want to change this.

https://github.com/Expensify/App/blob/d3db2a15e16d2b503ec5514d95eb845b44197d7b/src/libs/onboardingSelectors.ts#L11-L18

**Comment by abekkala** [comment]
@vitHoracek based on [this Slack conversation ](https://expensify.slack.com/archives/C036QM0SLJK/p1726479540380709?thread_ts=1726074674.036609&cid=C036QM0SLJK)

I _think_ this reported issue is not actually an issue, correct? it would be expected that an onboarding modal is not shown in this scenario?

**Comment by mountiny** [comment]
Correct i believe this is expected. We show the welcome banner for user who migrated in this case

**Comment by abekkala** [comment]
hmm, thought I closed this on Monday - 🤷🏼‍♀️ 
based on the expectation - this is not an issue
