### ISSUE TITLE
ntegrations-Integration menu is displayed instead of message to switch to OD

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#51214]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
Issue was found when validating https://github.com/Expensify/App/pull/49972
**Version Number:**  v.9.0.51 
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:** 

## Action Performed:
Pre requisites:
* QuickBooks Desktop installed
* In OD, QuickBooks Desktop successfully connected
Steps:
1. In ND, open workspace settings > Categories
2. Verify "The categories below are imported from Quickbooks Desktop settings." message shows
3. Press Quickbooks Desktop settings
## Expected Result:
The "Go to Expensify Classic to manage your settings." message is displayed without any integration menu (Import, Export, Advanced...) or error message.
## Actual Result:
The integration menu (Import, Export, Advanced...) is displayed.

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/8e4e1999-7584-48c2-ba80-53b3838efdf9

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mkzie2** [comment]
Quickbooks Desktop is supported now so the testing steps above are invalid. We can close this out.

**Comment by joekaufmanexpensify** [comment]
Great. TY!
