### ISSUE TITLE
Allow QA to test the Fullstory integration in staging

### ISSUE THREAD

**Issue by anmurali** [Expensify/App#51211]
Problem: Our FullStory integration is quickly becoming a critical part of New Expensify. If it breaks than we are left blind without the ability to debug issues for users and determine the usability of New Expensify.

Solution: Add a FullStory test case for Applause to test on each staging build to verify that we haven’t added any regressions to the integration. We need to be able to record sessions for specific accounts on staging, but keep the integration turned off for staging to not hit our session limit.

- [x] Identify a specific domain like @fstest.expensify.com that we can use specifically for this purpose
- [x] When this email user is detected in staging, start the Fullstory session. Do not record any other staging sessions for any other domains
- [x] Write down regression tests that utilize this domain for making sure the Fullstory session works as designed
- [ ] Train Applause on testing this

<details><summary>Issue Owner</summary>Current Issue Owner: @anmurali</details>

**Comment by anmurali** [comment]
cc @danieldoglas @AndrewGable

**Comment by anmurali** [comment]
@danieldoglas I was wondering if this is all simple as adding a user email check to the same place where we make sure to only start a FS session if the environment is production?

**Comment by anmurali** [comment]
Discussed a solution [here](https://expensify.slack.com/archives/C07HPDRELLD/p1730160879806929)
@danieldoglas can I assign this to you?

**Comment by danieldoglas** [comment]
awaiting the decision about the email.

**Comment by danieldoglas** [comment]
There's no payment on this one.

**Comment by danieldoglas** [comment]
WIP

**Comment by anmurali** [comment]
**Regression test proposal**

1. Sign up on www.expensify.com and select `Organize my own expenses` or `Manage expenses for a small team (1-9 employees)` with an email like fullstory+<anythinghere>@applause.expensifail.com
2. Select anything from `What do you want to do today` or `Do you use any accounting software?` as the case may be
3. Login to app.fullstory.com 
4. Go to Home - Just watch sessions
5. Under "User Filters" -- In the `Any user` dropdown, select email and enter the email used for sign up
6. Scroll down and verify that a session is found under `Session Playlist`
7. In `Session Playlist` click on the email, scroll down and verify that user properties are populated
<img width="449" alt="image" src="https://github.com/user-attachments/assets/2f4e5a7a-9e36-4765-b4ce-3355f903362a">

Repeat the above steps by signing up on new.expensify.com, hybrid app (iOS and Android)

Repeat the above steps by signing in with a previously signed up fullstory+<anythinghere>@applause.expensifail.com on all platforms (www.expensify.com, new.expensify.com, Hybrid iOS and Android). For sign in, verify the additional step below as well: 
8. Verify by watching the most recent session in the `Session Playlist` by clicking on the green play button, that the actions on sign in are in fact recorded.

**Comment by anmurali** [comment]
This is all setup!
