### ISSUE TITLE
[$250] Safari/Web - Emoji - Double highlight is shown when navigating with keyboard arrow key

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#51229]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.51-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** dave0123seife@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Navigate to any chat
2. Open emoji picker
3. Navigate through the emoji list using the keyboard arrow keys

## Expected Result:
Single highlight is shown when navigating with keyboard arrow key

## Actual Result:
Double highlight is shown when navigating with keyboard arrow key

## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/1cbaed9c-dade-4fb4-a407-bc6f600cf925

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021848902911414439965</li>
        <li>Upwork Job ID: 1848902911414439965</li>
        <li>Last Price Increase: 2024-10-23</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @ikevin127</details>

**Comment by IuliiaHerets** [comment]
@kadiealexander  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by kadiealexander** [comment]
Posted [here](https://expensify.slack.com/archives/C05LX9D6E07/p1729648542741469) to get confirmation whether this is a real bug.

**Comment by kadiealexander** [comment]
Closing as a non-issue.
