### ISSUE TITLE
[HOLD for payment 2024-11-13] [Create Expense A/B] Tweak Onboarding Copy for Combined Track/Submit 

### ISSUE THREAD

**Issue by grgia** [Expensify/App#51223]
See https://github.com/Expensify/App/issues/47598#issuecomment-2422948290

Track an expense task

> **Title** Track an expense
> **Description** Track an expense in any currency, whether you have a receipt or not.
> 
> Here’s how to track an expense:
> 
> 1. Click the green + button.
> 2. Choose Create expense.
> 3. Enter an amount or scan a receipt.
> 4. Click "Just track it (don't submit it)".
> 5. Click Track.
> 
> And you’re done! Yep, it’s that easy.

Submit an expense task

> **Title**: Submit an expense
> **Description**: Submit an expense by entering an amount or scanning a receipt.
> 
> Here’s how to submit an expense:
> 
> 1. Click the green + button.
> 2. Choose Create expense.
> 3. Enter an amount or scan a receipt.
> 4. Add your reimburser to the request.
> 5. Click Submit.
> 
> And you're done! Now wait for that sweet “Cha-ching!” when it’s complete.

**Comment by grgia** [comment]
Asking questions here https://expensify.slack.com/archives/C07HPDRELLD/p1729566040888919

Confirming `Are these tweaks only for the beta users?`

**Comment by grgia** [comment]
cc @fabioh8010

**Comment by fabioh8010** [comment]
Hi, I'm Fábio from Callstack - expert agency - and I would like to work on this issue.

**Comment by grgia** [comment]
There might be some BE required for this one, I'm going to have to look into [this doc](https://docs.google.com/document/d/10bhCv6XtzzqEZQ9tzxFwAz4lowgjOhsFqz13BMq6Iu4/edit?tab=t.0) to make a plan so we can coordinate @fabioh8010

**Comment by fabioh8010** [comment]
@grgia The onboarding copy for Track and Submit are [here](https://github.com/Expensify/App/blob/main/src/CONST.ts#L4774-L4789) and [here](https://github.com/Expensify/App/blob/main/src/CONST.ts#L96-L111). I think we only need to adjust on E/App, no?

**Comment by anmurali** [comment]
Ah could we reuse those tasks and just manipulate the copy when we render it for the test audience? Is that what you mean @fabioh8010 ?

**Comment by fabioh8010** [comment]
Yeah we could have different task objects in CONST.ts for the combined track/submit flow, and if the user has the `combinedTrackSubmit` we would use them instead of the current ones. I think it can work.

**Comment by fabioh8010** [comment]
I will proceed with this solution for now and test if it works as expected.

**Comment by anmurali** [comment]
@fabioh8010 any updates on this?

**Comment by grgia** [comment]
That works too- how's it going with this?

**Comment by fabioh8010** [comment]
@grgia @anmurali Created a Draft PR [here](https://github.com/Expensify/App/pull/51600). The idea is to tweak the track/submit messages in the FE if the user has the `combinedTrackSubmit` beta enabled.

I created versions of the combined flow for the onboarding copy and we're using it [here](https://github.com/fabioh8010/expensify-app/blob/feature/51223/src/libs/actions/Report.ts#L3337). This `completeOnboarding` function will create those messages optimistically and send them to the API [here](https://github.com/fabioh8010/expensify-app/blob/feature/51223/src/libs/actions/Report.ts#L3752).

From my tests the combined flow messages sent to the API are the same returned in the BE response, so it should work without having to make changes in BE.

**Comment by anmurali** [comment]
Sounds great!

**Comment by grgia** [comment]
Thank you @fabioh8010! I can help QA on an ADHOC build once it's ready

**Comment by fabioh8010** [comment]
I've opened the PR to review!

**Comment by mallenexpensify** [comment]
d'oh. 

Contributor+: @Ollyws due $250 via NewDot

Seeing this happened twice, at least, for ya, post in #contributor-plus if you ave any ideas on how we can create automation to _do something_ to ensure these don't get missed in the future.

**Comment by garrettmknight** [comment]
$250 approved for @Ollyws
