### ISSUE TITLE
[CRITICAL] Make all chats visible in New Supportal with all Add_Comment actions redacted

### ISSUE THREAD

**Issue by VictoriaExpensify** [Expensify/App#51221]
**Background**
Concierge Responders use New Supportal to provide customer support and troubleshooting; our Sales team also uses it to give demos and onboard customers. Because of that, it's important these teams can see the information needed to support customers.

**Problem**
We [redacted New Expensify chats from view in Supportal](https://github.com/Expensify/Expensify/issues/380658) earlier in the year in order to protect our customers privacy. In doing so, some of the information needed to successfully troubleshoot and demo to customers has also been revoked.

**Solution**
As discussed [here](https://expensify.slack.com/archives/C07NZ8B1VTQ/p1729200214389649), we want to update New Expensify chat visibility in Supportal to allow the following:

- Make all will make all chat previews visible in the LHN, regardless of type
- When a chat is clicked into, the message content will be redacted but relevant information, such as expenses and actions taken (e.g something being approved or exported) will be visible
- The #admins channels will be visible in their entirety as they contain an audit-trail for the Workspace which is required for troubleshooting

**Comment by VictoriaExpensify** [comment]
This should be a New Feature, not a Bug

**Comment by marcaaron** [comment]
Is [this issue](https://github.com/Expensify/App/issues/51449) still necessary if we stop redacting the chats themselves and start redacting the messages instead? 🤔

**Comment by VictoriaExpensify** [comment]
I think so @marcaaron , because the chats still need to be visible in the LHN for us to redact the messages. At the moment, they are not. Having redacted messages isn't going to be helpful if we can't see the chats in the first place. Here's an example:

Supportal:
![image](https://github.com/user-attachments/assets/8b324c70-d606-4990-b28f-35235cb5f18f)


Actual account:
![image](https://github.com/user-attachments/assets/7328c1d5-0465-4d6b-bde3-50150b56d542)

**Comment by marcaaron** [comment]
Yes, looks good. Let's update the Issue description with the new details? I can get started on this tomorrow.

**Comment by marcaaron** [comment]
Made some progress on this one today. We are returning these messages via various different paths... it could take some time to track down all of it. e.g. the search APIs also return some reports with chats. some of it resides in Auth and some of it in Web AFAICT.

**Comment by marcaaron** [comment]
Almost wrapped on this one. Seems like `ReconnectApp` and pusher updates are not accessible by supportal so no need to worry about these flows.

**Comment by marcaaron** [comment]
Put this into review today.

**Comment by mallenexpensify** [comment]
@marcaaron where are we at here? Asking cuz the below is held on this
- https://github.com/Expensify/App/issues/51449

**Comment by VictoriaExpensify** [comment]
We're all wrapped up here! Wrap up post is [here](https://expensify.slack.com/archives/C07NZ8B1VTQ/p1733792853610319)
