### ISSUE TITLE
Scheduled Email - Actionable hyper link behaves inconsistently with respond at hyper link

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#51236]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.51-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5083888
**Email or phone of affected tester (no customers):** nathanmulugetatesting+1846@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Navigate to OldDot login page
2. Click on the option to "organize my own expenses"
3. Enter a new account (name the account in a way that it's easy to filter and locate when receiving emails, e.g: [tester+trackbudget@gmail.com](mailto:tester+trackbudget@gmail.com))
4. Once navigated to NewDot - Select "Track and Budget Expenses" on the onboarding modal
5. Finish the onboarding modal
6. Logout and wait until you receive an email (Usually lasts about 24h - 48h)
7. Once you receive the email open it
8. Make sure you're not signed into new dot on another tab (You can clear cache and cookies for new dot)
9. Go back to the email and click on the bottom hyper link (Respond at... hyper link)

## Expected Result:
Both hyper links should automatically sign in user

## Actual Result:
The actionable hyper link just takes deeplinks user to a specific page whereas the bottom respond at hyper link automatically signs in user and takes user to the specific page

## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
 

https://github.com/user-attachments/assets/76b2f3d8-3461-4c09-962d-dccb85872631

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by IuliiaHerets** [comment]
@puneetlath  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by puneetlath** [comment]
I don't think it's expected that the reply footer automatically signs you in.
