### ISSUE TITLE
Expense - Category list loads infinitely when submitting to non-existing workspace chat

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#51238]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.52-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N/A - new feature, doesn't exist in prod
**Issue was found when executing this PR:** https://github.com/Expensify/App/pull/49412
**Email or phone of affected tester (no customers):** applausetester+zm39@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to OD.
2. Create a new Collect workspace.
3. Go to ND.
4. Go to FAB > Submit expense > Manual.
5. Enter amount > Next.
6. Select the Collect workspace chat created on OD.
7. Click Show more.
8. Click Category.

## Expected Result:
Category list will load without issue.

## Actual Result:
Category list loads infinitely.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/8ebf5e8f-c635-4dd6-9220-3571ddcdee62

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mjasikowski** [comment]
reverting

**Comment by mjasikowski** [comment]
awesome, thanks @ishpaul777

**Comment by m-natarajan** [comment]
Not reproducible 

https://github.com/user-attachments/assets/c518e7be-1d59-4ae6-ac94-5e2c08bb2833
