### ISSUE TITLE
Expense - Error shown when deleting WS with IOU

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#51240]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.52-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5114024
**Email or phone of affected tester (no customers):** testpayment935+505@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Navigate to http://www.staging.new.expensify.com/
2. Create new workspace
3. Submit expense on that workspace
4. Delete the workspace

## Expected Result:
Archived WS should be exist without error occurring.

## Actual Result:
"Auth OpenReport returned an error" shown and the WS will be deleted and navigated back to concierge
## Workaround:
Unknown

## Platforms:

- [x] Android: Standalone
- [x] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/2e581213-415a-49a3-9293-36c6afff39c0

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by IuliiaHerets** [comment]
@twisterdotcom  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by twisterdotcom** [comment]
Can't recreate:

https://github.com/user-attachments/assets/59279d6a-ab52-478b-9ee3-51d6dcac6437
