### ISSUE TITLE
[HOLD for payment 2024-11-01] [HOLD for payment 2024-10-30] Account Settings - I don't receive the magic code to verify the account in wallet section

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#51258]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.52-2
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5110296&group_by=cases:section_id&group_order=asc&group_id=229064
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Log in with a new Gmail account.
3. Complete onboarding.
4. Go to Account Settings and click on the Wallet section.
5. Scroll down and click on the "Enable Wallet" option.

## Expected Result:
The magic code to validate the account should be mailed on your first attempt.

## Actual Result:
The magic code isn't received unless the option “Didn't receive a magic code?” is clicked.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/eed094e0-6d00-4554-af1c-dc2d7a917878

 
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @trjExpensify</details>

**Comment by trjExpensify** [comment]
Testing now and chatting in the slack thread: https://expensify.slack.com/archives/C01GTK53T8Q/p1729607715820819

**Comment by hungvu193** [comment]
Taking a look 👀

**Comment by luacmartins** [comment]
PR merged and being CPed

**Comment by yuwenmemon** [comment]
Removing DeployBlockerCash label as this has been Cp'ed

**Comment by luacmartins** [comment]
Done!

**Comment by trjExpensify** [comment]
Payment summary as follows: 

- $250 to @aimane-chnaif for the C+ review. 

Offer sent!

**Comment by trjExpensify** [comment]
Paid, closing!
