### ISSUE TITLE
Scanned receipts not merging with workspace feed card transactions

### ISSUE THREAD

**Issue by garrettmknight** [Expensify/App#51250]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** N/A
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @puneetlath 
**Slack conversation:**  https://expensify.slack.com/archives/C06ML6X0W9L/p1729532744886309

## Action Performed:

1. swipe expensify card
2. the expensify card transaction from the workspace card comes in
3. scan the receipt

## Expected Result:
SmartScan successfully merges the scanned receipt with the card expense.

## Actual Result:
SmartScan isn't merging the scanned receipt with the card expense.

## Workaround:
None

## Platforms:
All

## Screenshots/Videos

![image](https://github.com/user-attachments/assets/5f8a8510-bbad-434d-89b9-20624a85eedc)

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by nkuoch** [comment]
<img width="711" alt="image" src="https://github.com/user-attachments/assets/6a888cf4-d8d4-4915-9297-f22e910fe6f1">

**Comment by nkuoch** [comment]
[This](https://github.com/Expensify/App/issues/51250#issuecomment-2432535298) should not happen again once https://github.com/Expensify/Auth/pull/12882 gets deployed

**Comment by nkuoch** [comment]
Adding [debug logs](https://github.com/Expensify/Web-Expensify/pull/44142) to understand Vit's case where merge is not working because ccTransaction is somehow seen as not editable during the process, even though it's seen as editable on display.

<img width="1097" alt="image" src="https://github.com/user-attachments/assets/7d29088e-fc06-4f25-903e-a062c9475366">

**Comment by nkuoch** [comment]
Waiting for the PR to be deployed so we can debug vit's case

**Comment by nkuoch** [comment]
[This](https://github.com/Expensify/Web-Expensify/pull/44175) might have fixed it. Let's test again today @mountiny

**Comment by mountiny** [comment]
We have tested on wednesday and further fixes are required, seems like an issue with cache not being updated correctly

**Comment by nkuoch** [comment]
Should get fixed once https://github.com/Expensify/Web-Expensify/pull/44176 gets deployed

**Comment by anmurali** [comment]
Rotating to get another BZ assigned while OOO

**Comment by mountiny** [comment]
Update: The core merging logic is fixed, we still need to make sure the report actions are correctly cleaned up after the merge

**Comment by nkuoch** [comment]
Will investigate in the logs tomorrow why this report action didn't get deleted:

```
nkuoch@db1.lax:~$ sudo readdb.sh -tsv "SELECT * FROM reportActions WHERE reportActionID=2496071261297319370"
created	reportID	accountID	action	message	reportActionID
2024-11-13 15:12:24.702	6000297946021321	10160771	IOU	{"IOUReportID":6000297946021321,"IOUTransactionID":"6293875063134994363","amount":0,"comment":"Testing merge","currency":"USD","isNewDot":true,"lastModified":"2024-11-13 15:12:24.702","participantAccountIDs":[10160771,0],"type":"track"}	2496071261297319370
```

**Comment by mountiny** [comment]
I can test one right now

**Comment by mountiny** [comment]
Well my receipt does not include a tip 😢

**Comment by mountiny** [comment]
Tested with another coffee without a tip this time and it worked and everything was correctly cleared up
<img width="1130" alt="image" src="https://github.com/user-attachments/assets/72b03f77-42e9-4baa-ad5d-16141ddfb95b">

Great job @nkuoch, spectacular 🎉
