### ISSUE TITLE
[WAITING ON SLACK] Markdown - Code Block - Code block uses one backtick instead of three

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#51259]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.52-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5083289&group_by=cases:section_id&group_order=asc&group_id=292106
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Open the desktop app
2. Login in
3. Open a chat or start a new one
4. Type a message with a code block ```code````
5. Type a message like this `code`

## Expected Result:
When the user types a code with three backticks ```code ```it is displayed as code

## Actual Result:
When the user types a code with one backticks `code` it is displayed as code

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/749bf5cb-2b75-44f5-9f67-1b6ee5cbc950

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@jliexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by jliexpensify** [comment]
Thanks @FitseTLT - I'll confirm internally if this is an actual bug.

**Comment by jliexpensify** [comment]
This is not a bug @lanitochka17:

>Not a bug, codeblock needs to start with triple backticks and the actual code needs to be in the next line
