### ISSUE TITLE
Tags - State field is not auto populated

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#51256]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9. 0. 52-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
Pre-condition: As admin in old dot, upload dependent tags
1. Go to https://staging.new.expensify.com/home
2. As employee, login
3. Open workspace chat
4. Tap plus icon -- submit expense
5. Enter an amount and tap next
6. Note the state field

## Expected Result:
State field must be auto populated

## Actual Result:
State field is not auto populated

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Standalone
- [x] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/5faa1212-cc79-456b-a443-2ea2b2594a19

[Dependent - Multi Level tags NEW (1).csv](https://github.com/user-attachments/files/17479912/Dependent.-.Multi.Level.tags.NEW.1.csv)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by dangrous** [comment]
Interesting, I see it on staging (and not on production) but not able to reproduce locally. Will investigate further.

**Comment by dangrous** [comment]
Found a potential cause here - https://github.com/Expensify/App/pull/49412 - but still not able to reproduce, so it's proving hard to figure out.

**Comment by lanitochka17** [comment]
@ishpaul777 uploaded dependent tags:

[Dependent - Multi Level tags NEW (1).csv](https://github.com/user-attachments/files/17479908/Dependent.-.Multi.Level.tags.NEW.1.csv)

**Comment by m-natarajan** [comment]
Not reproducible 

https://github.com/user-attachments/assets/6f778a2e-dc6f-45c4-b392-0e8b8800b866
