### ISSUE TITLE
Search - The feature Delete does nothing on expenses with a task in it

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#51260]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.52-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** aatweq+22222223@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Loggin
2. Go to a 1:1 chat with another user account
3. Click on 'Create' the + button inside the chat
4. Click on 'Submit expense'
5. Click on 'Manual'
6. Complete the data and submit a expense
7. Hover over the expense and click on 'Reply on thread'
8. Write something in the chat and send it
9. Click on 'Search' between Inbox and Settings
10. Click on check button on the expense
11. Click on button '1 selected (down arrow)' on the top right corner
12. Click on 'Delete' button and again click on 'Delete'

## Expected Result:
After the user clicks the delete button, the receipt should be deleted. Or an error message should appear saying something like, “It is not possible to delete a receipt with a task in it.”

## Actual Result:
After the user click on delete button nothing happen

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/982b21bc-6948-4a69-a859-a96786af33e6

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by MitchExpensify** [comment]
I was unable to reproduce following these steps, the expense deleted correctly on v9.0.52-5
