### ISSUE TITLE
 Web - Search - The DM of user does appear on the search result

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#51261]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.52-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):**Spica+123456@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Open the website https://staging.new.expensify.com/
2. Create new group with user example [bob@domain.com,](mailto:bob@domain.com,)
and [alice@domain.com.](mailto:alice@domain.com.)
3. Send a message to the user in group
4. Goto other conversation
5. Start searching
6. Try entering the user email [alice@domain.com](mailto:alice@domain.com)
or the name 'alice'
7. Goto the group
8. Try entering 'bob alice' to searching

## Expected Result:
1. When the user searches for keywork is [alice@domain.com](mailto:alice@domain.com)
or the name 'alice' the result should appear the message with alice
2. When the user searches for keywork is 'bob alice' the result is none

## Actual Result:
1. When the user searches for keywork is [alice@domain.com](mailto:alice@domain.com)
or the name 'alice' the result just appear the last message with bob
2. When the user searches for keywork is 'bob alice' the result should appear the group

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/0317864c-946a-47bb-89b2-419eebf3e64e

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@abekkala  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by abekkala** [comment]
this type of search would be expected

> 'bob alice' the result is none

But comma separating provides results - when search for 2 people the comma is needed.
