### ISSUE TITLE
Search - Expenses created on a control WS are not showing up on Search page

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#51270]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.52-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://github.com/Expensify/App/pull/49412
**Email or phone of affected tester (no customers):** nathanmulugetatesting+1897@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Navigate to staging.expensify.com/inbox
2. Create a new Gmail account
3. Create a control workspace
4. Click on concierge to navigate to newDot
5. Click on FAB > Submit expense > Enter an amount > Select the control workspace created in OD and finish the creation flow
6. Go to search page
7. For comparison create a new workspace and submit an expense on the newly created workspace and go to search page

## Expected Result:
The expense created on the Control workspace gets shown on the search page and on step 5 when clicking on FAB the new workspace button does not appear since the user already created a workspace.

## Actual Result:
The expense created on the control workspace doesn't get shown on the search page, when clicking FAB the user is shown create a new workspace button even if user already created a control workspace on OD.

## Workaround:
Unknown
## Platforms:

- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/7af40ca1-ce78-4546-840e-0bb0d167322e

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by IuliiaHerets** [comment]
We think that this bug might be related to #wave-control

**Comment by luacmartins** [comment]
This is expected. Only expenses on migrated policies, i.e. with `policyExpenseChatEnabled` set to true should show up.
