### ISSUE TITLE
[HOLD for payment 2024-11-01] [HOLD for payment 2024-10-30] Validate account - Magic code email is received twice when validating from bank account setup

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#51277]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.52-2
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Email or phone of affected tester (no customers):** yonghongkok2+ksopdspd11@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Log in with a new Gmail account (unvalidated).
3. Complete the onboarding.
4. Create a new workspace.
5. Go to workspace settings > More features.
6. Enable Workflows.
7. Go to Workflows.
8. Click Connect bank account.
9. Click "verify your account here" link.
10. Check email.

## Expected Result:
One magic code email will be received.

## Actual Result:
One magic code email will be received.

## Workaround:
Unknown

## Platforms:

- [x] Android: Standalone
- [x] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/24c9e842-5c11-4399-959e-38349de971a3

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @francoisl</details>

**Comment by francoisl** [comment]
I can repro, there are 2 API calls to `RequestContactMethodValidateCode` when you click "or verify your account here".

<img width="1512" alt="image" src="https://github.com/user-attachments/assets/60b2cdc6-3f6e-4ccf-baee-f07c3a5c5939">


This might possibly be coming from https://github.com/Expensify/App/pull/49445, discussion about a fix ongoing in https://expensify.slack.com/archives/C01GTK53T8Q/p1729607715820819.

**Comment by francoisl** [comment]
This will be fixed by https://github.com/Expensify/App/pull/51267

**Comment by kavimuru** [comment]
It's a pass

https://github.com/user-attachments/assets/7f8e9865-41f4-4d72-818c-cfae43b6d5a7

**Comment by yuwenmemon** [comment]
https://expensify.slack.com/archives/C07J32337/p1729726700727579

**Comment by RachCHopkins** [comment]
@francoisl Do I need to pay anyone here?

**Comment by francoisl** [comment]
I don't believe so, the PR fixed multiple issues, and [this one](https://github.com/Expensify/App/issues/51258#issuecomment-2452333530) already has a payment summary for the C+ that reviewed.
