### ISSUE TITLE
Expense - Error when submitting distance expense to non-existing workspace chat

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#51286]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.52-2
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+kh1610015@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to OD
2. Create a new Control workspace
3. Go to ND
4. Go to FAB > Submit expense > Distance
5. Enter waypoints > Next
6. Select the Control workspace chat created on OD
7. On confirmation page, click Rate
8. Note that Rate list is empty
9. Submit the distance expense
10. Go to transaction thread

## Expected Result:
In Step 8, Rate list should not be empty
In Step 10, the distance expense will be submitted without issue

## Actual Result:
In Step 8, Rate list is empty
In Step 10, error happens when submitting distance expense to non-existing workspace chat

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [x] iOS: Standalone
- [ ] iOS: HybridApp
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/0adbcc4f-c74e-44fb-a044-0bf4ae481e98

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@blimpich  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by blimpich** [comment]
Probably related to https://github.com/Expensify/App/pull/49412, checking locally if reverting it fixes this.

**Comment by blimpich** [comment]
Reverting does seem to fix the issue, discussing possible solutions other than reverting in Slack

**Comment by blimpich** [comment]
Decided to revert, working on that now.

**Comment by blimpich** [comment]
Steps still needed:
- [ ] merge [revert PR](https://github.com/Expensify/App/pull/51289#pullrequestreview-2386101575) to main
- [ ] confirm [CP request](https://expensify.slack.com/archives/C07J32337/p1729625287927659) goes through and code is CP'ed to staging
- [ ] ask QA to re-test this deploy blocker
- [ ] remove deploy blocker / close issue

**Comment by blimpich** [comment]
Will be afk for 1.5 hours, will continue steps above once I'm back

**Comment by blimpich** [comment]
[Not reproducible](https://expensify.slack.com/archives/C9YU7BX5M/p1729639636311899?thread_ts=1729632202.975429&cid=C9YU7BX5M), closing.
