### ISSUE TITLE
[HOLD for payment 2024-11-14] [$250] Android -Distance - Distance tab is gray and not highlighted in green when swiping to Distance

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#51297]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.52-2
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+kh1610015@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Launch ND or hybrid app.
2. Open FAB > Submit expense
3. Go to Manual
4. Swipe to Scan, then swipe to Distance

## Expected Result:
Distance tab will be highlighted in green when swiping to Distance tab (production behavior)

## Actual Result:
Distance tab is gray and not highlighted in green when swiping to Distance tab
The tab is only green when it is tapped on
This issue also happens in Scan tab when it is swiped from Distance to Scan

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Standalone
- [x] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/9d158542-d61b-4a29-af0b-2b8795ade7d6

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021848826866073504646</li>
        <li>Upwork Job ID: 1848826866073504646</li>
        <li>Last Price Increase: 2024-10-29</li>
<li>Automatic offers: </li>
<ul>
<li>rayane-djouah | Reviewer | 104667585</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @mallenexpensify</details>

**Comment by yuwenmemon** [comment]
Demoting this as it's pretty minor.

**Comment by mallenexpensify** [comment]
Removed Help Wanted for a min... @rayane-djouah , what do you think of the proposals above?

**Comment by mallenexpensify** [comment]
I'm back from OOO on Nov 14th, not assigning another BZ because the PR is on staging so payment will likely be the day or two after I'm back. If one is needed please add or post in #contributor-plus to ask for one to be added, thx.

**Comment by mallenexpensify** [comment]
Contributor: @twilight2294 owed $250 via Upwork
Contributor+: @rayane-djouah paid $250 via Upwork 

Test case created, thx @rayane-djouah 
- https://github.com/Expensify/Expensify/issues/445521

@twilight2294 can you please accept the job and reply here once you have? 
https://www.upwork.com/jobs/~021848826866073504646

**Comment by mallenexpensify** [comment]
Thanks @twilight2294 , you've been paid, payment post above has been updated.
