### ISSUE TITLE
[HOLD for payment 2024-11-07] [$250] Web/Safari - Workspace - Upgrade message in the #admins room moves slightly when hovered

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#51308]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.52-5
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Navigate to https://staging.new.expensify.com/
2. Log in with a new Gmail account
3. Create a workspace
4. Navigate to Workspace settings - More features
5. Enable "Report fields" and upgrade the WS to Control when asked
6. Navigate to the #admins room
7. Hover over the upgrade message
8. Navigate to the Concierge chat
9. Hover over the "Welcome to Expensify" message

## Expected Result:
Message shouldn't move.

## Actual Result:
Upgrade message in the #admins room moves slightly when hovered. It also affects Concierge "Welcome to Expensify" message.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/fd4e221c-fa4f-4825-ba84-fab072d1abc3

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021849066967845098466</li>
        <li>Upwork Job ID: 1849066967845098466</li>
        <li>Last Price Increase: 2024-10-23</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @thesahindia</details>

**Comment by IuliiaHerets** [comment]
@bfitzexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by IuliiaHerets** [comment]
We think that this bug might be related to #wave-control

**Comment by rlinoz** [comment]
Nice, let's make sure to test all possible markdown syntax we support

**Comment by bernhardoj** [comment]
PR is ready

cc: @thesahindia

**Comment by bfitzexpensify** [comment]
Payment summary:

@bernhardoj requires $250 payment through NewDot Manual Requests

@thesahindia - please complete the BZ checklist and I'll finalise your C+ payment summary

**Comment by bernhardoj** [comment]
Requested in ND.

**Comment by JmillsExpensify** [comment]
$250 approved for @bernhardoj

**Comment by bfitzexpensify** [comment]
Updated payment summary for @thesahindia:

@thesahindia - requires $250 payment through NewDot Manual Requests

**Comment by garrettmknight** [comment]
$250 approved for @thesahindia
