### ISSUE TITLE
[HOLD for payment 2024-11-18] [$250] Workspace - WS chat is created for invalid phone number

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#51316]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.52-5
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** gibethlehem@gmail.com
**Issue reported by:**Applause Internal Team

## Action Performed:
1. Login to an account
2. create a WS
3. Invite a user with invalid Phone number(Invalid Phone: +1 631-791-8378)
Notice error is shown and can't invite user.
4. Go to inbox

## Expected Result:
WS chat with invalid Phone number is not created

## Actual Result:
WS chat with invalid Phone number is created

## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/5a47eb49-3cfb-4446-8a6d-69da70913a7e

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021849978282313703906</li>
        <li>Upwork Job ID: 1849978282313703906</li>
        <li>Last Price Increase: 2024-10-26</li>
<li>Automatic offers: </li>
<ul>
<li>akinwale | Reviewer | 104685790</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @stephanieelliott</details>

**Comment by IuliiaHerets** [comment]
@stephanieelliott  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
WS chat is still available for failed to add workspace members.

### What is the root cause of that problem?
When we invite a member, we optimistically create a report for the invited member. However, we don't clear the report when fails, we only set the `isLoadingInitialReportActions` metadata to false.
https://github.com/Expensify/App/blob/f251dbcdfdafc492d9a9908cbf40e4630b7b6d9d/src/libs/actions/Policy/Policy.ts#L1007-L1013

### What changes do you think we should make in order to solve the problem?

We can clear the optimistic report when fails (and it's metadata).
```
workspaceMembersChats.onyxFailureData.push({
    onyxMethod: Onyx.METHOD.SET,
    key: `${ONYXKEYS.COLLECTION.REPORT_METADATA}${optimisticReport.reportID}`,
    value: null,
});

workspaceMembersChats.onyxFailureData.push({
    onyxMethod: Onyx.METHOD.SET,
    key: `${ONYXKEYS.COLLECTION.REPORT}${optimisticReport.reportID}`,
    value: null,
});
```

OR

We can show an error instead of clearing it like this:
https://github.com/Expensify/App/blob/f251dbcdfdafc492d9a9908cbf40e4630b7b6d9d/src/libs/actions/IOU.ts#L804-L809

```
workspaceMembersChats.onyxFailureData.push({
    onyxMethod: Onyx.METHOD.MERGE,
    key: `${ONYXKEYS.COLLECTION.REPORT}${optimisticReport.reportID}`,
    value: {
        errorFields: {
            createChat: ErrorUtils.getMicroSecondOnyxErrorWithTranslationKey('report.genericCreateReportFailureMessage'),
        },
    },
});
```

This way, the user will see an error on the chat and can manually remove it.
<img width="1197" alt="image" src="https://github.com/user-attachments/assets/6348be26-46d9-4f00-8553-faf6b35a23ed">

**Comment by stephanieelliott** [comment]
Hey @akinwale we have a proposal here, can you please review?

**Comment by akinwale** [comment]
> Hey @akinwale we have a proposal here, can you please review?

Sure, I'll review today.

**Comment by akinwale** [comment]
We can move forward with @bernhardoj's [proposal](https://github.com/Expensify/App/issues/51316#issuecomment-2431657472) here.

@bernhardoj Let's go with the option that is already an established pattern in other parts of the app.

🎀👀🎀 C+ reviewed.

**Comment by marcochavezf** [comment]
Sounds good, thanks @akinwale for the review! Assigning @bernhardoj 🚀

**Comment by bernhardoj** [comment]
> Let's go with the option that is already an established pattern in other parts of the app.

@akinwale sorry, which one you mean? 😅 The clear report one or show an error?

**Comment by akinwale** [comment]
> > Let's go with the option that is already an established pattern in other parts of the app.
> 
> @akinwale sorry, which one you mean? 😅 The clear report one or show an error?

Display an error.

**Comment by bernhardoj** [comment]
Ok, thanks!

PR is ready

cc: @akinwale

**Comment by stephanieelliott** [comment]
Hey @akinwale the PR is waiting for your review, can you take a look?

**Comment by akinwale** [comment]
@stephanieelliott I am eligible to be paid through ND on this one so I'll decline the [automatic offer].(https://www.upwork.com/nx/wm/offer/104685790)

**Comment by stephanieelliott** [comment]
Summarizing payment on this issue: 

 - Contributor: @akinwale $250 - please request via ND 
 - Contributor+: @bernhardoj $250 - please request via ND

**Comment by bernhardoj** [comment]
Requested in ND.

**Comment by JmillsExpensify** [comment]
$250 approved for @akinwale

**Comment by JmillsExpensify** [comment]
$250 approved for @bernhardoj
