### ISSUE TITLE
 [AU] Search - User is logged out after signing in through public room and clicking on Search

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#51319]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.52-5
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5120736&group_by=cases:section_id&group_id=229066&group_order=asc
**Issue reported by:** Applause Internal Team

## Action Performed:
Precondition: User should be logged off in browser.

1. Navigate to https://staging.new.expensify.com/r/2091104345528462
2. Click on the "Sign in" button
3. Sign in with a new Gmail account
4. Click on the "Search" button at the top right of the screen

## Expected Result:
Search modal should open.

## Actual Result:
User is logged out after signing in with a new account through a public room and clicking on "Search".

## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/7e954a7f-661a-4afe-8387-acaf5a829fe6

/details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by IuliiaHerets** [comment]
@garrettmknight  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by garrettmknight** [comment]
This doesn't fit any of our projects at the moment so I'm going to close.
