### ISSUE TITLE
 [AU] Task - Unable to edit subtask description "Auth EditTask returned an error"

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#51322]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.52-5
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5120695&group_by=cases:section_id&group_id=291936&group_order=asc
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Navigate to https://staging.new.expensify.com/
2. Log in with a new Gmail account
3. Navigate to FAB - Start chat
4. Open a 1:1 DM with any account
5. Navigate to + button - Assign task
6. Create a task with any title and assign it to the other user
7. Click on the task to navigate to the task thread
8. Navigate to + button - Assign task
9. Create a task with any title and assign it to the other user
10. Click on the subtask to navigate to the subtask thread
11. Click on "Description" and change it to any text

## Expected Result:
I should be able to edit the description.
## Actual Result:
Unable to edit subtask description "Auth EditTask returned an error" message appears.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/91302953-7f39-4519-95a5-d912112c4007

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by IuliiaHerets** [comment]
@joekaufmanexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by joekaufmanexpensify** [comment]
A task within a task feels like an edge case, and we are [closing almost all task bugs right now](https://expensify.slack.com/archives/C05LX9D6E07/p1729633232719639?thread_ts=1729620879.897129&cid=C05LX9D6E07) for focus. So closing for now!
