### ISSUE TITLE
[HOLD for payment 2024-11-07] Add report fields to QBO/Xero

### ISSUE THREAD

**Issue by lakchote** [Expensify/App#51320]
Implement the [detailed section of the design doc](https://docs.google.com/document/d/1us_o_1-qoALSMjbOtuU1ZfkdFX9oSiMRf0RYuFtwx1U/edit?tab=t.0#bookmark=id.bhtvetftadls) related to adding report fields to QBO/Xero.

<details><summary>Issue Owner</summary>Current Issue Owner: @adelekennedy</details>

**Comment by lakchote** [comment]
Regression tests can be found in the doc [Add report fields to QBO/Xero - Manual Test Steps](https://docs.google.com/document/d/1Bl__Vll944onIxVPcn3_0asIDLV5Mu8kM72BZCUrV0s/edit?tab=t.0).

**Comment by adelekennedy** [comment]
getting a check on this

**Comment by lakchote** [comment]
> * Add report fields to QBO/Xero #51321

@allgandalf no special compensation should be given out. Test steps were straightforward and not complex to follow. 
Changes were relatively small. A big part of the new code changes were kind of the same since it followed the same logic.
As such there was no complexity or review overhead.

**Comment by lakchote** [comment]
> Please assign me here for payment, also @lakchote what's the payment here given the testing was vast and PR was long and from a project
>

@allgandalf no special compensation should be given out. Test steps were straightforward and not complex to follow. Changes were relatively small. A big part of the new code changes were kind of the same since it followed the same logic. As such there was no complexity or review overhead.

**Comment by adelekennedy** [comment]
Payouts due:

- [ ] Contributor: $250 @allgandalf [Upwork](https://www.upwork.com/ab/applicants/1854996988214531156/job-details)

@allgandalf will you apply [here](https://www.upwork.com/jobs/~021854996988214531156)?
