### ISSUE TITLE
[HOLD for payment 2024-12-30] [$250] [Performance] Implement a debug setting that simulates a poor connection by going online/offline a bunch

### ISSUE THREAD

**Issue by muttmuure** [Expensify/App#51331]
___

## What performance issue do we need to solve?
When on a poor connection, authentication calls can sometimes fail. This is sometimes de-authing users from the app (logging them out) when it shouldn't be, because we have infinite sessions.

## What is the impact of this on end-users?
Users need to re-authenticate when this happens, and this is annoying. 

## List any benchmarks that show the severity of the issue
It has been reported numerous times in the #quality Slack channel. 

## Proposed solution (if any)
Implement a debug setting that simulates a poor connection, then see how much of the app breaks and try to fix those spots.

This could be done by setting up some code that will call `NetworkActions.setNetWorkStatus(networkStatus);` with a random value of `CONST.NETWORK.NETWORK_STATUS` at random intervals like every 2-5 seconds.

https://expensify.slack.com/archives/C05LX9D6E07/p1728935338695029?thread_ts=1728600237.229689&cid=C05LX9D6E07

## List any benchmarks after implementing the changes to show impacts of the proposed solution (if any)
It might be time to add some benchmarking for how often the network connection is changing. How about logging every hour how many times the network connection state changed?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

**Version Number:**
**Reproducible in staging?:**
**Reproducible in production?:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:**

[View all open jobs on Upwork](https://www.upwork.com/ab/jobs/search/?q=Expensify%20React%20Native&sort=recency&user_location_match=2)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021864308224556700727</li>
        <li>Upwork Job ID: 1864308224556700727</li>
        <li>Last Price Increase: 2024-12-04</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @hoangzinh</details>

**Comment by tgolen** [comment]
@muttmuure for this one, can we just send it to contributors to have this done? I don't think it needs anything from anyone internal.

**Comment by muttmuure** [comment]
Sure!

**Comment by VickyStash** [comment]
Hi, I'm Viktoryia from Callstack - expert contributor group - and I would like to work on this issue.

**Comment by VickyStash** [comment]
I've opened a [PR](https://github.com/Expensify/App/pull/53698) , which adds the `Simulate poor internet connection toggle`. It changes connection from online to offline randomly every 2-5 seconds using `NetworkActions.setShouldForceOffline` method (`NetworkActions.setNetWorkStatus` didn't have the expected effect on the app).
Please, let me know what you think! @hoangzinh @tgolen 

Also, I have a question regarding this part:
> How about logging every hour how many times the network connection state changed?

@muttmuure  Where do we want to log this value?

**Comment by VickyStash** [comment]
> I think you can just log that information with Log.info() and it should be fine.
1. Should it be counted when poor connection simulation is turned on or real-life cases only?
2. Should it be counted within one session only or persist between several sessions within an hour (I mean if user close/re-open the app)?

**Comment by tgolen** [comment]
It would be nice to log it whether or not the setting is turned on. In fact, let's add the state of the setting in the log itself. I think it would also be nice to span sessions if that's not too much extra work. I'm not worried about losing it if they sign out though.

**Comment by VickyStash** [comment]
@tgolen I've added the log in this commit : https://github.com/Expensify/App/pull/53698/commits/5e52653975b8eeb83dfa441ea46498858c6f7f7f, let me know what you think. It is triggered by the connection change on its own and reports the connection changes within the 1+ hour.

**Comment by tgolen** [comment]
I don't feel too strongly about that. If I were thinking about this with a fresh perspective I guess it wouldn't be three on/off settings, but one setting with several options:

- Always offline
- Poor connection
- Failing requests

**Comment by VickyStash** [comment]
> I don't feel too strongly about that. If I were thinking about this with a fresh perspective I guess it wouldn't be three on/off settings, but one setting with several options:
> 
> * Always offline
> * Poor connection
> * Failing requests

@tgolen But you can't use all options at once, right? You can use only one out of three options per time?

**Comment by VickyStash** [comment]
@hoangzinh Okay, I'll update the PR within the next couple of hours 👌

**Comment by VickyStash** [comment]
**Updates:**
- Moved logic of simulating a poor connection into `src/libs/NetworkConnection.ts` so the code is aligned with force offline functionality
- Use [NetworkConnection.setOfflineStatus](https://github.com/Expensify/App/blob/37105a1b4c60ba6416b3ae3415c2265a53c55257/src/libs/NetworkConnection.ts#L53-L63) instead of `forceOffline`
- Made it possible to turn on only one network test toggle per time:

https://github.com/user-attachments/assets/63d07b17-cbd7-4cbe-84f6-ccb13884c5de

**TODOs:**
I haven't had enough time to re-test it fully, so plan to do it tomorrow.

**Questions:**
We can try to update the UI to something like:
![image](https://github.com/user-attachments/assets/afa63cc6-cdf8-4336-a56f-4ed044d84a0a)
But it will require some side updates.
@tgolen wdyt?

**Comment by sonialiap** [comment]
Payment summary:
- @hoangzinh $250 through NewDot

**Comment by garrettmknight** [comment]
$250 approved for @hoangzinh
