### ISSUE TITLE
[HOLD] SearchForReports query doesn't sort results

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#51343]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.52-5
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @JmillsExpensify 
**Slack conversation:** https://expensify.slack.com/archives/C05LX9D6E07/p1729007631513779

## Action Performed:
1. Go to staging.new.expensify.com
2. Click Search on LHN
3. Click chat > Search icon
4. Enter workspace name in search field
## Expected Result:
Search result sorted as expected (1.Order everything by the last message timestamp (descending)
  2.When searching, self DM is put at the top  3.All archived reports should remain at the bottom)
## Actual Result:
The workspace chat is not displayed

## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
![CleanShot 2024-10-15 at 17 51 57](https://github.com/user-attachments/assets/f4006ff0-fa4e-4da7-907b-b4787ba860d8)

https://github.com/user-attachments/assets/83c5fb3e-4e2f-4f05-80c2-05202610c2bb

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by alexpensify** [comment]
@JmillsExpensify should this be an `Internal` or `External` GH? Thanks!

**Comment by flodnv** [comment]
Internal.

**Comment by flodnv** [comment]
I am a bit confused by the expected result @JmillsExpensify 

1. Order everything by the last message timestamp (descending)
2. When searching, self DM is put at the top
3. All archived reports should remain at the bottom

Is this saying that this should be the order of things, assuming they are present in the results? Like:
1. Workspace chat
2. self dm
3. archived reports

? How does last message timestamp affect this? Like what if the last message in the self dm was 1 hour ago, and the last message in the workspace chat was 2 hours ago?

**Comment by alexpensify** [comment]
It's not overdue; we are waiting for feedback here.

**Comment by JmillsExpensify** [comment]
This should be on hold. It needs to go through the design process internally first. I'll also take it over.

**Comment by JmillsExpensify** [comment]
P.S. @luacmartins is going to take the lead on this one!

**Comment by luacmartins** [comment]
Posted [whatsnext proposal](https://expensify.slack.com/archives/CC7NECV4L/p1730410672386209). Gonna ship a pre-design by EOD tomorrow.

**Comment by luacmartins** [comment]
Tracking issue [here](https://github.com/Expensify/Expensify/issues/442313)

**Comment by luacmartins** [comment]
I'll work on the HL doc this week

**Comment by luacmartins** [comment]
Still on hold

**Comment by luacmartins** [comment]
Still on hold

**Comment by luacmartins** [comment]
Still on hold

**Comment by luacmartins** [comment]
I'm actually gonna close this issue in favor of https://github.com/Expensify/Expensify/issues/442313
