### ISSUE TITLE
[$250] Self DM - Self DM is not bolded in LHN after it is marked as unread

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#51362]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.53-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** javascript:
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Log in with a new account
3. Go to self DM
4. Send a few messages
5. Right click on the self DM in LHN
6. Click Mark as unread

## Expected Result:
Self DM will be bolded in LHN after it is marked as unread

## Actual Result:
Self DM is not bolded in LHN after it is marked as unread

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/2ab7faa2-1f6e-4584-a211-96902e97ade5

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021849224049457734741</li>
        <li>Upwork Job ID: 1849224049457734741</li>
        <li>Last Price Increase: 2024-10-23</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @mkhutornyi</details>

**Comment by blimpich** [comment]
I have a meeting right now but will look into this right after the meeting

**Comment by blimpich** [comment]
Caused by this: https://github.com/Expensify/App/pull/51212. Tested reverting it locally.

**Comment by blimpich** [comment]
Demoting

**Comment by blimpich** [comment]
Gonna mark this as external since I don't know what PR caused it. @NJ-2020 as part of your proposal can you state what PR caused this regression in the first place?

**Comment by bernhardoj** [comment]
We have the same issue before [here](https://github.com/Expensify/App/issues/39712) too
