### ISSUE TITLE
[$250]  "New Message Indicator Active but Message Not Visible in Chat Despite Whisper Notification in LHN"

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#51363]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.52-5
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @puneetlath 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1729699406894099

## Action Performed:
1. Assign a user as a Admin for a group chat
2. Observe LHN and report
## Expected Result:
Whisper message displayed in group chat and LHN 
## Actual Result:
No whisper message in group chat, New message pill displayed in group chat and whisper message in LHN
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

![image (2)](https://github.com/user-attachments/assets/bae19f3e-a823-478c-8e0c-f68bd3b147d9)
![image (1)](https://github.com/user-attachments/assets/e073fbbc-4d2b-4b0c-942b-f2016ce9bc27)
  

https://github.com/user-attachments/assets/986b6497-c8ce-4bc3-be54-80d540a9ffcc

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021849497090026766357</li>
        <li>Upwork Job ID: 1849497090026766357</li>
        <li>Last Price Increase: 2024-10-31</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @eh2077</details>

**Comment by Anaslancer** [comment]
Hi @m-natarajan Can you please provide more about the Actual and Expected Results. It would be better to upload a video. Thanks!

**Comment by eh2077** [comment]
Not overdue, still waiting for proposals!

**Comment by lschurr** [comment]
@eh2077 is this reproducible? Do we need more clear steps like @Anaslancer mentioned here? https://github.com/Expensify/App/issues/51363#issuecomment-2442158923

**Comment by eh2077** [comment]
@lschurr I can't reproduce the bug. There's no new message indicator or notification in LHN. See recording

https://github.com/user-attachments/assets/89fa02f2-606f-481a-998d-5c1ba5f8222a

**Comment by lschurr** [comment]
Alright, thanks! Let's close.
