### ISSUE TITLE
Modal that shows European countries list is not being shown

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#51385]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.53-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Issue was found when executing this PR:** 
**Email or phone of affected tester (no customers):** https://github.com/Expensify/App/pull/51173
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Create a workspace
3. Change the workspace currency to EUR, GBP, CAD or AUD
4. Go to more features and enable workflows
5. Go to workflows and click on connect bank account

## Expected Result:
New component with European countries list gets shown.

## Actual Result:
No new component with European countries list gets shown but the usual "Update currency to USD" modal gets shown

## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/aa14fa77-9da7-4659-a00c-22981da0ccd0

  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by IuliiaHerets** [comment]
@CortneyOfstad  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by MrMuzyk** [comment]
Hey, I'm the creator of the PR. We're building a flow for global reimbursements that will support adding bank account for workspaces with different currency than USD - https://github.com/Expensify/App/issues/50896. At the moment this whole feature is accessible in development mode only. I can try to find out if there is something we can do to make this flow accessible by QAs right now if there is such need. I'm not 100% that there is such need at the moment as we're building it piece by piece and it won't be fully operational until phase 4. There will be a moment when we will want to make it accessible by everyone and at this point it will be of course tested as a whole.

**Comment by MrMuzyk** [comment]
I can make it visible in debug mode and also create a switch for it in the troubleshoot section. I believe it's not a big effort and would allow you QAs to check this.

**Comment by CortneyOfstad** [comment]
Thanks for @MrMuzyk! I agree that this is not needed right now, so going to close!
