### ISSUE TITLE
Expensify Card - Shipping details message on workspace chat doesn't appear dynamically

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#51387]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.53-0
**Reproducible in staging?:** Y
**Reproducible in production?:**  Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:**
**Found when validation PR:** https://github.com/Expensify/App/pull/50660
**Email or phone of affected tester (no customers):** nathanmulugetatesting+1943@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
Pre-conditions:
- Workspace is connected with a bank account
- Workspace has a member invited
- Workspace has enabled Expensify card
1. Sign in with the invited member on a different chrome profile
2. Sign in with the admin on a different chrome profile
3. [Employee] Open workspace chat
4. [Admin] Issue a physical card for the member
5. [Employee] Observe if any messages are received on employee's side
6. [Employee] Open another report and open the workspace chat

## Expected Result:
The shipping details message appears inside the workspace chat dynamically right after the admin issues the physical card

## Actual Result:
The shipping details message appears only when the employee opens another report and re opens the workspace chat

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/6e3a9a9e-d2c1-46b2-ba03-a82b00c4fa3f

  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment]
We think this issue might be related to the #collect project.

**Comment by VictoriaExpensify** [comment]
Hmm I'm just not sure this is actually a real problem. I don't think employees are sitting in the workspace chat waiting to see this message. And if they click into it after the individual limit has been set, they will see the message. 

Think we will close this out as a very low priority
