### ISSUE TITLE
[$250] [HOLD for payment 2024-11-07] [3rd Party Feeds]  FE: Build out report action about the assigned card

### ISSUE THREAD

**Issue by robertjchen** [Expensify/App#51401]
## Problem

Ref https://github.com/Expensify/Expensify/issues/434245

For Third Party Card Feeds v1, we have a new reportAction type `CARDASSIGNED ` and the handling for that in NewDot needs to be implemented.

BE: https://github.com/Expensify/Expensify/issues/438621

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021853821158813750356</li>
        <li>Upwork Job ID: 1853821158813750356</li>
        <li>Last Price Increase: 2024-11-05</li>
    </ul>
</details>

**Comment by VickyStash** [comment]
Hi, I'm Viktoryia from Callstack - expert contributor group - and I would like to work on this issue.

**Comment by robertjchen** [comment]
Assigned, thanks!

**Comment by VickyStash** [comment]
The [PR](https://github.com/Expensify/App/pull/51406) has been opened for the review!

**Comment by mountiny** [comment]
Adding joe to help with payment

**Comment by joekaufmanexpensify** [comment]
Payment due later this week

**Comment by joekaufmanexpensify** [comment]
Only payment here is $250 to @allgandalf for C+ review via upwork

**Comment by joekaufmanexpensify** [comment]
@allgandalf offer sent!

**Comment by joekaufmanexpensify** [comment]
Actioning tomorrow!

**Comment by joekaufmanexpensify** [comment]
@allgandalf could you please accept the offer here so I can pay you?

**Comment by joekaufmanexpensify** [comment]
@allgandalf $250 sent and contract ended!

**Comment by joekaufmanexpensify** [comment]
All set, thanks everyone!
