### ISSUE TITLE
Add `expo-background-fetch` to execute background task

### ISSUE THREAD

**Issue by szymonrybczak** [Expensify/App#51404]
# Name of library: `expo-background-fetch`

## Details
- Link to package: https://www.npmjs.com/package/expo-background-fetch
- Problem solved by using this package: It allows to run specified tasks in the background.
- Number of stars in GH: 33.7k (it's inside Expo monorepo). 
- Number of monthly downloads: 25276
- Number of releases in the last year: 5 (without nightlies and canaries), it's inside Expo SDK, so it's maintain by Expo team
- Level of activity in the repo: for this particular package it seems like it's in maintenance level
- Alternatives: 
	- https://github.com/transistorsoft/react-native-background-fetch
		- no support for New Architecture with latest versions of React Native,
		- API may be outdated due to long-term development, containing legacy code and patterns
		- longer history of use. 
	- https://github.com/jamesisaac/react-native-background-task
	    - not maintained 
- Are security concerns brought up and addressed in the library's repo? ✅
- How many dependencies does this lib use that will be brought into our code? `expo-task-manager` and `expo-constants`.
- What will the effect be on the bundle size of our code?
	- [`expo-background-fetch`](https://bundlephobia.com/package/expo-background-fetch@12.0.1)
	- [`expo-task-manager`](https://bundlephobia.com/package/expo-task-manager@11.8.2)
	- [`expo-constants`](https://bundlephobia.com/package/expo-constants@16.0.2)
In summary <10kB.

**Comment by szymonrybczak** [comment]
For more context the library is needed to solve the problem described [here](https://github.com/Expensify/App/issues/50140).

**Comment by thienlnam** [comment]
Thread where this convo has been happening is https://expensify.slack.com/archives/C05LX9D6E07/p1727884875529299

Seems like this is possibly being split into a few different P/S items - can you re-open if you still need this library with another P/S once that conversation is done?

**Comment by mountiny** [comment]
Reopening as the time has come

**Comment by thienlnam** [comment]
This is going to be built instead, progress for that here: https://github.com/Expensify/App/issues/52700
