### ISSUE TITLE
Track - Preview shows "Receipt scan in progress" after submitting manual expense with receipt

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#51418]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.53-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+kh1610015@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to self DM
3. Track a manual expense without receipt
4. Click Categorize it from the whisper
5. Select a workspace and category
6. Add a receipt on the confirmation page
7. Click Submit

## Expected Result:
Since the submitted expense is a manual expense with receipt, the expense preview will not show "Receipt scan in progress"

## Actual Result:
The expense preview in the workspace chat shows "Receipt scan in progress" after submitting a manual expense with receipt

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [x] iOS: Standalone
- [ ] iOS: HybridApp
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/52acb3c4-1ae6-47d7-8598-5522adc57863

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by slafortune** [comment]
This would be expected if you unloaded the receipt after creating the expense.  If you uploaded the receipt then entered the details then it would not scan.
