### ISSUE TITLE
Expensify Card - RHP resets to previous steps and shows "Get physical card" after a refresh

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#51430]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.53-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** nathanmulugetatesting+1945@gmail.com
**Issue reported by:** Applause - Internal Team

**Issue found when executing Pr** https://github.com/Expensify/App/pull/50660
## Action Performed:
Pre-conditions:
- Workspace is connected with a bank account
- Workspace has a member invited
- Workspace has enabled Expensify card
- Admin has issued a physical card for employee
- Employee is done adding shipping details to receive the card
1. Sign in with the invited member's account
2. Go to wallet > Open issued physical card RHP
3. Refresh the page
4. After the refresh close the RHP and Click on the Employee's card to open the RHP again

## Expected Result:
Activate card button shows up

## Actual Result:
RHP shows previous step with the button "Get physical card" even if all the info's are added previously

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/1c6de3a7-d9f7-40f1-97f7-8c207c1fa7ab

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@CortneyOfstad  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave-collect - Release 2

**Comment by CortneyOfstad** [comment]
So I checked the video it shows **Enter Shipping Details** indicating that the details were not already provided despite what is listed in the **Actual Result** above:

<img width="938" alt="Screenshot 2024-10-24 at 1 49 39 PM" src="https://github.com/user-attachments/assets/8861cac1-ec78-4a87-9f35-eb9be7f22d39">

After entering the details, the next button to appear is the **Activate Card** button, so this working as intended.
