### ISSUE TITLE
Tapping admin link in concierge page, directed to production app

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#51463]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** V9. 0.54-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to https://staging.new.expensify.com/home
2. Login with a new gmail account
3. Tap fab - create a new workspace
4. Submit an expense
5. Go to LHN
6. Open the concierge chat
7. Tap #admin link

## Expected Result:
Tapping admin link in concierge page, user must be directed to workspace admin room.

## Actual Result:
Tapping admin link in concierge page, directed to production app instead of workspace admin room.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/a502aab8-a88e-4fb9-b26c-e4ede6a1fb38

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment]
Production 

https://github.com/user-attachments/assets/71f0c536-7527-4406-a4c2-0f1524dba128

**Comment by zanyrenney** [comment]
how you getting on with investigating this one @youssef-lr ?

**Comment by youssef-lr** [comment]
This isn't a bug. When this hits production it will redirect properly to the admin room.
