### ISSUE TITLE
Composer - Nothing happens when tapping Enter after selecting emoji from suggestion list

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#51460]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.54-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** 
**Email or phone of affected tester (no customers):** applausetester+kh2010001@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
Precondition:
- Device keyboard is Samsung keyboard.

1. Go to staging.new.expensify.com
2. Open DM.
3. Type :sm
4. Select an emoji from the list.
5. Tap keyboard Enter.

## Expected Result:
A new line will be created.

## Actual Result:
Nothing happens when tapping Enter after selecting an emoji from the suggestion list.
This issue also happens with mention suggestion list.
This issue is only reproducible with Samsung keyboard.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/954d3a55-f20b-4883-9114-46382e82a6e6

  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by JmillsExpensify** [comment]
Going to close this out for focus.
