### ISSUE TITLE
Chat - Conversation is not scroll to the bottom when edit message/save button is cut-off

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#51472]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.54-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** gocemate+a2649@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to any conversation
2. Send a lot of messages until the top messages are not visible
3. Send new message
4. Hover over the message> Click on 3-dot menu> Edit

## Expected Result:
Conversation should scroll to the bottom of the page when edit a message

## Actual Result:
Conversation does scroll to the bottom of the page when edit a message
Save button is cut-off

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/42bd78af-2710-422c-a477-54d2a74b1abe

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by shahinyan11** [comment]
Similar to this [issue](https://github.com/Expensify/App/issues/51431). Most likely they have the same root cause and fixing one will fix another too
