### ISSUE TITLE
[HOLD for payment] Attendee Tracking feature C+ reviews

### ISSUE THREAD

**Issue by Julesssss** [Expensify/App#51484]
Please pay out @ZhenjaHorbach for their work as contributor+ on these Attendee tracking feature PRs.

- https://github.com/Expensify/App/pull/48008
- https://github.com/Expensify/App/pull/48870
- https://github.com/Expensify/App/pull/49008

The first two PRs contained a huge number of changes that could have been easily broken into smaller PRs. We also delayed the payment by quite a few months, so I suggest we increase the payment from $750 to $1000.

**Comment by MitchExpensify** [comment]
So just to be sure, $1000 for all 3 PRs? @Julesssss

**Comment by MitchExpensify** [comment]
Offer sent for payment here https://www.upwork.com/jobs/~021851043127029144459

**Comment by MitchExpensify** [comment]
Paid and contract ended @ZhenjaHorbach !

Thanks
