### ISSUE TITLE
[HOLD for payment 2024-11-11] Implement the route for Workspace Downgrades

### ISSUE THREAD

**Issue by carlosmiceli** [Expensify/App#51486]
Part of [Add Workspace Plan Downgrades to NewDot](https://github.com/Expensify/Expensify/issues/399936) 

[Doc section](https://docs.google.com/document/d/1GDPmbvV47VVxucr-tHYjH80VylcJptP0RfGMVy3zanY/edit?tab=t.0#bookmark=id.iwjdboyqgfbu)

Description: Implement screens, paths, types and mappings outlined in the doc section.

<details><summary>Issue Owner</summary>Current Issue Owner: @isabelastisser</details>

**Comment by carlosmiceli** [comment]
@garrettmknight is there something I should/could do about [this](https://github.com/Expensify/App/issues/51486#issuecomment-2438277128) warning by Melvin? Or should that be done by someone else?

**Comment by garrettmknight** [comment]
@carlosmiceli BZ on the issue should have added to a project. Sorted you out in the meantime.

**Comment by carlosmiceli** [comment]
Thanks sir! Should I just put all the rest on #migrate as well?

**Comment by garrettmknight** [comment]
Yep!
