### ISSUE TITLE
Collect Approvers -The option to delete the expense is displayed in the conversation details

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#51490]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.53-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5122302
**Issue reported by:** Applause - Internal Team

## Action Performed:
Preconditions:
- The user uses two new accounts using gmail, 1 workspace administrator and 1 employee.
- The user has added the employee to the Workspace Chat.
- As an admin, activate the Scheduled Submit option is set to "Manually"
1. Go to staging.new.expensify.com
2. Log in with the employee account
3. Go to WS chat and upload a spend of >$100 to WS
4. Tap on the "Submit" button
5. Navigate to the Expense details
6. Tap on the "Submit" button
7. Tap on the header on the expense
8. Tap on the option to "Delete the expense

## Expected Result:
The option to delete the expense is not displayed in the conversation details

## Actual Result:
The option to delete expenses appears and can be interacted with

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/d8712d3c-0df5-4e30-8577-284416ccfa16

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@stephanieelliott  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by FitseTLT** [comment]
This might be expected.

**Comment by bernhardoj** [comment]
The submitter can delete the expense as long as it's not approved yet. It was changed in https://github.com/Expensify/App/issues/45779

**Comment by stephanieelliott** [comment]
Ah thanks guys, yes seems like this is expected behavior
