### ISSUE TITLE
[HOLD for payment 2024-11-14] [$250] Remove the redundant `+ New workspace` button from the `Workspaces` page when no workspaces exist

### ISSUE THREAD

**Issue by jamesdeanexpensify** [Expensify/App#51500]
**Slack thread**
https://expensify.slack.com/archives/C07HPDRELLD/p1729808604309359

**Problem**
When no workspaces exist and you go to the **Workspaces** screen, we offer two buttons that do the same thing (`New workspace`). Not only is this redundant, it unnecessarily takes up screen real estate on mobile and distracts the user with two CTAs (though they're the same, one CTA is still best practice).

**Solution**
When no workspaces exist and you go to the **Workspaces** screen, remove the top `+ New workspace` button so only the bottom/card New workspace button shows.

**Where I'm talking about**
![image (95)](https://github.com/user-attachments/assets/adcaa9d8-daba-4f55-8142-d9ac141e6c75)
![image (96)](https://github.com/user-attachments/assets/91b24882-00be-4eaa-8b35-cd5257e6c879)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021850943776036588977</li>
        <li>Upwork Job ID: 1850943776036588977</li>
        <li>Last Price Increase: 2024-10-28</li>
<li>Automatic offers: </li>
<ul>
<li>Krishna2323 | Contributor | 104649051</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @mallenexpensify</details>

**Comment by zfurtak** [comment]
Hello, I'm Zuza from Software Mansion agency and I could take care of the issue 😊

**Comment by mallenexpensify** [comment]
I'm back from OOO on Nov 14th, not assigning another BZ because the PR is on staging so payment will likely be the day or two after I'm back. If one is needed please add or post in #contributor-plus to ask for one to be added, thx.

**Comment by mallenexpensify** [comment]
I'm back from OOO on Nov 14th, not assigning another BZ, if one is needed please add or post in #contributor-plus to ask for one to be added, thx.

**Comment by mallenexpensify** [comment]
Contributor: @Krishna2323 paid $250 via Upwork.  
Contributor+: @thesahindia due $250 via NewDot  

Doesn't look like we need a regression test here.  Thanks y'all!

**Comment by garrettmknight** [comment]
$250 approved for @thesahindia
