### ISSUE TITLE
Update tasks in onboarding flows to link to the end point 

### ISSUE THREAD

**Issue by danielrvidal** [Expensify/App#51508]
Problem: When users go through onboarding tasks, they struggle to follow the instructions to the end, which leads to confusion and delays in completing the necessary actions.

Solution: Provide users links in all onboarding tasks that direct them to somewhere more than a couple of clicks away. 

Note:  we do this already in the manage my team's onboarding tasks, but we should provide consistency in other use cases to provide a link as well. 

<details><summary>Issue Owner</summary>Current Issue Owner: @danielrvidal</details>

**Comment by nikihatesgh** [comment]
Sign up and select manage my team intent - you’ll see a “take me there” link in each task. 

Sign up and choose every other intent. You’ll see the tasks don’t have such a destination link. Add them as appropriate.

**Comment by nikihatesgh** [comment]
Sign up and select manage my team intent - you’ll see a “take me there” link in each task.

1. Create a workspace - no take me there option
2. Meet your setup specialist - Chat with the specialist in your #admin room
3. Set up categories - [Take me to workspace category settings](https://new.expensify.com//settings/workspaces/9FE3C62A71DE825C/categories).
4. Set up tags - [Take me to more features](https://new.expensify.com//settings/workspaces/9FE3C62A71DE825C/more-features)
5. Add expense approvals - [Take me to enable more features](https://new.expensify.com//settings/workspaces/9FE3C62A71DE825C/more-features).
6. Invite your team - [Take me to workspace members](https://new.expensify.com//settings/workspaces/9FE3C62A71DE825C/members). That’s it, happy expensing! :)

**Comment by nikihatesgh** [comment]
as a side note, the formatting is different between these tasks in the SAME flow (as in, moving from task 1 to 2 to 3) 
![Screenshot 2024-10-28 at 5 04 12 PM](https://github.com/user-attachments/assets/536642a6-0c17-4dc1-8cea-ad8af068e3af)

**Comment by danielrvidal** [comment]
Yea, I thnk Tags were added later so that would be good to standardize on.

**Comment by nikihatesgh** [comment]
Was holding to see if this p/s would change from the convo [here](https://expensify.slack.com/archives/C07HPDRELLD/p1730224202113149) but after discussing 1:1 with Daniel I am going to move forward as planned with adding the tooltips for each other intent

**Comment by nikihatesgh** [comment]
https://docs.google.com/spreadsheets/d/1-C23RbCPKRvIcqQohVWHHTwBpShGY5DrcpRaMUdTAYE/edit?gid=0#gid=0

**Comment by nikihatesgh** [comment]
[convo started in #convert ](https://expensify.slack.com/archives/C07HPDRELLD/p1730938183592589)

**Comment by nikihatesgh** [comment]
[discussion here,](https://expensify.slack.com/archives/C07HPDRELLD/p1731371749906199) but I think since we are removing the task for PBA in this flow then we have no other updates to the tasks. The 1 action I am going to push for though is to remove the video in favor of the self guided tour task which we now have

**Comment by nikihatesgh** [comment]
It looks like we are trending to remove PBAs from the onboarding flow which is the only item which needed the link added. I think we discussed leaving this open as that conversation (from Flavia's CVP review [here](https://expensify.slack.com/archives/C07HPDRELLD/p1730224202113149)) is still up in the air.

**Comment by danielrvidal** [comment]
I'll take this one back over while Niki is OOO and try to close it out this week.

**Comment by danielrvidal** [comment]
Latest update here: https://expensify.slack.com/archives/C07HPDRELLD/p1732046380186049?thread_ts=1730938270.380039&cid=C07HPDRELLD

**Comment by danielrvidal** [comment]
Here is the outcome. I'm going to close this one as the other issue covers it. 

https://github.com/Expensify/App/issues/52977
