### ISSUE TITLE
[HOLD for payment 2024-11-26] [$250] New Feature: "When to export" selector for auto-sync for NetSuite

### ISSUE THREAD

**Issue by yuwenmemon** [Expensify/App#51512]
Hello! We need to build the following selector in the NetSuite configuration options:
![364604714-6baa9d6b-fe87-43fd-bd28-d0844b9dc381](https://github.com/user-attachments/assets/5efd17bf-c3ee-4cf5-bac5-d2d7d72c1dbb)

The "When to export" selector in the above mock-up is what we're adding.

The two options should have the following values (copied from the same feature in OldDot)
```JSX
const accountingMethodOptions = [
    {
        value: 'ACCRUAL',
        text: 'Accrual',
        description: 'Out of pocket expenses will export when final approved',
    },
    {
        value: 'CASH',
        text: 'Cash',
        description: 'Out of pocket expenses will export when paid',
    },
];
```

Please use the constants defined in Expensify Common though: https://github.com/Expensify/expensify-common/pull/817

The selection should be saved under the property `accountingMethod` in the NetSuite `options.config` object.

If there is no `accountingMethod` property set in the NetSuite config, the selector should default to `CASH`

Linked Expensify Issue: https://github.com/Expensify/Expensify/issues/422402

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021852432563378960977</li>
        <li>Upwork Job ID: 1852432563378960977</li>
        <li>Last Price Increase: 2024-11-01</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @mallenexpensify</details>

**Comment by yuwenmemon** [comment]
Removing `NewFeature` label since this does not fall under a project.

**Comment by yuwenmemon** [comment]
@mallenexpensify Can we set up a job in Upwork for this?

@twilight2294 Thanks for your proposal! When can we expect a PR?

**Comment by mallenexpensify** [comment]
^ Job created.  
Wasn't sure which project to add it too, went with #convert, based on 
> All-things new customer adoption at or better than Classic for Collect workspaces between 1-10 submitters

**Comment by yuwenmemon** [comment]
Yeah the API will be named `UpdateNetSuiteAccountingMethod` and the accounting method should be supplied in the `accountingMethod` param

**Comment by yuwenmemon** [comment]
> can you update the auto-sync toggle BE to set accountingMethod to CASH please?

I'm sorry what do you mean by this? The toggle should default to CASH if a value is not explicitly set. Otherwise the client is sending `ACCRUAL`/`CASH` in the `accountingMethod` param when calling the API.

**Comment by yuwenmemon** [comment]
> also when someone disabled the auto-sync toggle, we should clear the value of accountingMethod too right?

No, let's actually just keep the `accountingMethod` whatever it was. That way if they turn it back on the setting is not reset.

**Comment by mallenexpensify** [comment]
@rojiphil can you help here while @aimane-chnaif is out sick? If not, can you post in #contributor-plus to find a volunteer? Thx

**Comment by rojiphil** [comment]
> @rojiphil can you help here

I am happy to contribute here @mallenexpensify.

**Comment by rojiphil** [comment]
> All new connections will be created with the `accountingMethod` already set to `ACCRUAL` so the default value should just follow what is set in the connection object. if there is no `accountingMethod`, then go with `CASH` as the default.

Ah ok. Thanks @yuwenmemon for clarifying. 
Also, is the understanding correct that enabling or disabling the `auto sync` should not impact the configured accounting method i.e the method would remain the same?

**Comment by yuwenmemon** [comment]
Yes correct.

**Comment by mallenexpensify** [comment]
@rojiphil @twilight2294 can you please accept the job and reply here once you have? 
https://www.upwork.com/jobs/~021852432563378960977

**Comment by mallenexpensify** [comment]
Contributor: @twilight2294 paid $250 via Upwork
Contributor+: @rojiphil owed $250 via Upwork

**Comment by rojiphil** [comment]
> can you please accept the job and reply here once you have?

@mallenexpensify Accepted the offer. Thanks.

**Comment by mallenexpensify** [comment]
@rojiphil paid, payment post updated above. 

> [@rojiphil] Please propose [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the new feature will work correctly on production in further releases.

@rojiphil , do we want a test case for this new feature?  If not, why not?   Thx

**Comment by rojiphil** [comment]
> do we want a test case for this new feature? If not, why not? Thx

@mallenexpensify Thanks for the payment. Regarding new features, I think it would be good if the QA process implicitly involved mandatorily including the test case directly from the PR in their database. Maybe a checklist is also needed for QA. 
The reasoning is that, for C+, the existing BZ checklist is designed for bugs/blockers and not for new features, while adding test cases for new features is a mandatory step for QA. What do you think?

**Comment by rojiphil** [comment]
Meanwhile, here is the test case to this issue for addition:
 
Precondition: Netsuite Accounting must be setup in a workspace
1. Navigate to `Workspace` —> `Accounting`
2. Click on `Advanced`
3. Enable `Auto-sync` toggle if disabled
4. Verify that a new field `When to export` is displayed
5. Select the field `When to export`
6. Verify that two options `Cash` and `Accrual` are displayed.
7. Select an unselected option.
8. Verify that we are navigated back to `Autosync` page and the new selected option is displayed.
9. Also verify the hint text i.e. if we select CASH as option then the hint text below auto-sync option should be: `Out-of-pocket expenses will export when paid` and if we select ACCURAL as option then the hind text should be: `Out-of-pocket expenses will export when final approved`

**Comment by mallenexpensify** [comment]
Test Case, thx @rojiphil 
- https://github.com/Expensify/Expensify/issues/449285

> QA process implicitly involved mandatorily including the test case directly from the PR in their database

@rojiphil can you elaborate on this?  Are you saying that, for every new feature, QA should _do something_ for all of the PRs to create new test cases without the assigned internal engineer, C+ or contributor _doing anything_?   I do find it interesting how most test cases for bugs are just the test steps from the OP of the PR.

**Comment by rojiphil** [comment]
> can you elaborate on this? Are you saying that, for every new feature, QA should _do something_ for all of the PRs to create new test cases without the assigned internal engineer, C+ or contributor _doing anything_? I do find it interesting how most test cases for bugs are just the test steps from the OP of the PR.

@mallenexpensify Yeah. That’s correct. As I understand, the QA should have a database of all test cases. As such, any new feature/improvement should be added to the test case database. And I believe it is the QA team’s responsibility to write and maintain this. Not frequently though but once in a while, all these test cases can be run to ensure that the software functions as expected. Regression test cases, to me, are a subset of test cases from the database of all test cases that are required to be tested by QA to check for feature regressions. Regression tests can be run whenever code is changed for a certain feature to ensure that all is well within the feature.

**Comment by mallenexpensify** [comment]
Thx @rojiphil.  For New Features, it's the responsibility of the people creating or working on the feature to propose the updated test steps then QA will add them, if needed.  If the new feature comes from a design doc, an author of the doc might choose to write all test steps at once so that they're cohesive.  For small features, it's likely default to have C+ create the test steps unless it's been clearly stated not to, or that someone else will add them.   This is to ensure they get added.  We'd rather have multiple GHs for adding new test steps and have QA close dupes or unneeded ones vs missing a test case.

**Comment by mallenexpensify** [comment]
@aimane-chnaif can you please accept the job below? Please reply here and tag me once you have. 
https://www.upwork.com/jobs/~021988047151437580139

**Comment by mallenexpensify** [comment]
### Payment Summary
Contributor+: @aimane-chnaif paid $125 via NewDot
