### ISSUE TITLE
Expense - Using non existing account, pay elsewhere must not displays red dot error

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#51521]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9. 0.54-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/home
2. Tap fab -- start chat with non existing user
3. Create an expense via submit expense option
4. Note no error displayed on opening expense
5. Tap plus icon --Pay expense
6. Enter an amount and tap next
7. Tap pay elsewhere
8. Open the expense
9. Note red dot error displayed and directs to hmm not here page.

## Expected Result:
Using non existing account, user can pay elsewhere must not displays red dot error and on opening expense must not direct to hmm not here page

## Actual Result:
Using non existing account, user can submit expense but on pay elsewhere displays red dot error and on opening expense directs to hmm not here page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/aea01977-f149-453b-934b-76e19e8a3481

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@RachCHopkins  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by RachCHopkins** [comment]
Site down, will triage tomorrow.

**Comment by RachCHopkins** [comment]
Yes, can replicate. Note there is a step missing in the instructions:

1. Go to https://staging.new.expensify.com/home
2. Tap fab -- start chat with non existing user
3. Create an expense via submit expense option
4. Note no error displayed on opening expense
_5. Go back to the chat_
6. Tap plus icon --Pay expense
7. Enter an amount and tap next
8. Tap pay elsewhere
9. Open the expense
10. Note red dot error displayed and directs to hmm not here page.

**Comment by RachCHopkins** [comment]
I have concerns here: Why would a person send someone an expense to pay, and then pay it themselves? Is this deliberate? I might check this before adding the External label.

**Comment by RachCHopkins** [comment]
Noting that the expense is not shown as Paid at all - I'm adding more expenses. 

Payee end:

![image](https://github.com/user-attachments/assets/60d6f5db-2685-4dee-a169-6188efa67cf9)

Payer end:

![image](https://github.com/user-attachments/assets/f66e7a49-dfe4-4295-a8d1-ce3b0acfdcb7)

**Comment by RachCHopkins** [comment]
IOU functionality, not a priority at this stage. Closing.
