### ISSUE TITLE
Hybrid iOS - App gets unresponsive after logging as WS member and dismissing explanation modal

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#51527]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.54.1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5134614
**Issue reported by:** Applause - Internal Team

## Action Performed:
precondition:
- user A created an account in OD web, verified it and enabled Try New Expensify option by running a snippet
- user B created a workspace in ND and invited user A
1. Open the hybrid app and log in as user A
2. Tap the Get started button on the modal or outside of the modal to dismiss it
3. Open any report from LHN, search, FAB or account settings

## Expected Result:
User is able to open any report, search, account settings and FAB

## Actual Result:
The app becomes unresponsive, unable to open any chat, search, account settings and FAB until the app is reopened

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [x] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/364fab69-5a95-460b-8d5c-ac43ad42b056

https://github.com/user-attachments/assets/a9f6bb65-5f6d-416a-8077-7b3348b0e65e

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Beamanator** [comment]
The linked testrail test looks unrelated 🤔  also the precondition kinda makes me think this is NAB if it requires running a js snippet?

Would also be helpful to know exactly what the snippet was that should be run

**Comment by NikkiWines** [comment]
I'll raise this in QA to get more detailed steps.

**Comment by NikkiWines** [comment]
I'm not able to reproduce this on v9.0.54-2, can we get this retested please?

**Comment by NikkiWines** [comment]
Ok, also able to reproduce. Separately, while using newDot via Hybrid App, I'm unable to exit out a report using the `<` navigation button, regardless of whether or not I follow the above steps for this issue.

**Comment by NikkiWines** [comment]
Reverting https://github.com/Expensify/App/pull/51332 seems to have resolved this! 


https://github.com/user-attachments/assets/a8746e9e-c451-4b24-ace4-a69b97bbed23

**Comment by hannojg** [comment]
Actually none of the code from the accused PR is executed in the described flow. I assume this to have the same root cause as this ticket:

- https://github.com/Expensify/App/issues/51584
