### ISSUE TITLE
Search - Chats: docx/zip/txt/html files are present on Links tab

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#51529]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.54-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/cases/view/3284915
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition: there are chats with sent links and files (txt, zip, html, docx)
1. Go to Search > Chats
2. Go to Links tab
3. Go to Attachment tab

## Expected Result:
On step 2: Sent messages with links are displayed
On step 3: Sent files are displayed

## Actual Result:
On step 2: Sent messages with links are displayed. Sent files (with formats txt/zip/docx/html) are also present on a tab.
On step 3: Sent files are displayed (also files with formats txt/zip/docx/html)

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/e1b4ecc3-1f41-442a-948d-65ed0f0dc7b2

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@adelekennedy  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave-control

**Comment by Shahidullah-Muffakir** [comment]
This appears to be a backend filtering issue in the **Search** endpoint
1. jsonQuery in the case of **attachment**; 
`{"type":"chat","status":"attachments","sortBy":"date","sortOrder":"desc","filters":null,"inputQuery":"type:chat status:attachments sortBy:date sortOrder:desc","hash":34196984,"offset":0}
`
2. jsonQuery in the case of **links**; 
 `{"type":"chat","status":"links","sortBy":"date","sortOrder":"desc","filters":null,"inputQuery":"type:chat status:links sortBy:date sortOrder:desc","hash":2089317297,"offset":0}`

We are sending the correct **status** in each payload, but the **Links** response includes all chat types.

**Comment by flaviadefaria** [comment]
@adelekennedy I think this is more of a retain bug since migrated customers won't have any chats once they migrate and the links are more of an edge case.

**Comment by adelekennedy** [comment]
I'm going to close this for now - I think this is something we will want to address in the future but it being a BE bug and a semi-edge case makes me think we should deprioritize
