### ISSUE TITLE
[HOLD for payment 2024-11-18] [$250] QAB - Without entering any amount, tapping submit expense/ pay elsewhere shows diff. behavior

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#51520]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9. 0.54-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/home
2. Go to 1:1 with an user
3. Submit an expense
4. Navigate to LHN
5. Tap fab - submit expense via quick action button
6. Tap submit expense without entering any amount
7. Note no sound is heard
8. Go to 1:1 with an user
9. Tap plus icon - pay elsewhere
10. Enter an amount and tap next
11. Tap pay elsewhere
12. Navigate to LHN
13. Tap fab - Pay expense via quick action button
14. Tap play elsewhere without entering any amount
15. Note an sound is heard

## Expected Result:
Via qab, without entering any amount, tapping submit expense/ pay elsewhere must show same behavior

## Actual Result:
Via qab, without entering any amount, tapping submit expense, user can't hear any sound but fir pay elsewhere, sound is heard

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/8560e9c2-8243-45aa-ad7d-6f4c305f9acb

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021850782070242079103</li>
        <li>Upwork Job ID: 1850782070242079103</li>
        <li>Last Price Increase: 2024-10-28</li>
<li>Automatic offers: </li>
<ul>
<li>Krishna2323 | Contributor | 104658616</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @muttmuure</details>

**Comment by lanitochka17** [comment]
@lschurr  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by hungvu193** [comment]
@Krishna2323 's [proposal here ](https://github.com/Expensify/App/issues/51520#issuecomment-2439718525) looks good to me! 

🎀 👀 🎀  C+ reviewed

**Comment by hungvu193** [comment]
@Krishna2323 Do you have any ETA for the PR? 👀

**Comment by twisterdotcom** [comment]
Relabelling as Lauren is OOO now.

**Comment by garrettmknight** [comment]
@muttmuure can you get me an updated payment summary?

**Comment by muttmuure** [comment]
@hungvu193 - $250 for C+ 
@Krishna2323 $250 for C

**Comment by garrettmknight** [comment]
$250 approved for @hungvu193
