### ISSUE TITLE
[HOLD for payment 2024-12-20] [$250] Search - Hmm it's not here opens when try to View invoices created in OD

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#51528]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.54-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/cases/view/3284914
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition: workspace with enabled invoices. Admin is logged in ND and OD
1. In OD: Submit a invoice to anyone with at least 2 expenses
2. In ND: Navigate to the Search page
3. Click on Invoices
2. Click on the Outstanding filter
3. Click on the “View” button next to the report that has the 2 expenses grouped

## Expected Result:
The report view is displayed and the 2 expenses are visible

## Actual Result:
'Hmm.. it's not here' tab is opened

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/72e1c95e-a4d6-4a89-a20f-618b7834ded1

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021851097781495138249</li>
        <li>Upwork Job ID: 1851097781495138249</li>
        <li>Last Price Increase: 2024-11-12</li>
<li>Automatic offers: </li>
<ul>
<li>dukenv0307 | Reviewer | 104892930</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @VictoriaExpensify</details>

**Comment by lanitochka17** [comment]
@VictoriaExpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-bills

**Comment by VictoriaExpensify** [comment]
I _think_ since this is a backward compatible issue, I would put this as a Migrate bug. But we should definitely get this fixed

**Comment by rezkiy37** [comment]
Hi, I am Michael (Mykhailo) from Callstack, an expert agency and I can work on this issue.

**Comment by rezkiy37** [comment]
I am OOO till Tuesday and will continue to work on this issue later.

**Comment by VictoriaExpensify** [comment]
Not OD

**Comment by rezkiy37** [comment]
I am back and working on the issue.

**Comment by rezkiy37** [comment]
I can confirm the bug is replicable. Working on it.

<details><summary>Details</summary>
<p>

<img width="1728" alt="Screenshot 2024-11-05 at 15 55 28" src="https://github.com/user-attachments/assets/0e917b06-8e92-4b36-8e80-f39d21586c87">

</p>
</details>

**Comment by rezkiy37** [comment]
Working on the issue.

**Comment by rezkiy37** [comment]
I've started a discussion in [Slack](https://callstack-hq.slack.com/archives/CSL3XBCCR/p1730896857770339).

**Comment by rezkiy37** [comment]
Working on the issue.

**Comment by rezkiy37** [comment]
I am chating in [Slack](https://callstack-hq.slack.com/archives/CSL3XBCCR/p1731582840107749?thread_ts=1730896857.770339&cid=CSL3XBCCR).

**Comment by rezkiy37** [comment]
No updates. We are waiting on the backend.

**Comment by flaviadefaria** [comment]
@rezkiy37 is there someone working on the backend? Or do we need to assign an internal engineer to work on this?

**Comment by rezkiy37** [comment]
> @rezkiy37 is there someone working on the backend? Or do we need to assign an internal engineer to work on this?

Yep, there is. 
cc @cristipaval

**Comment by VictoriaExpensify** [comment]
Any updates on this @cristipaval ?

**Comment by cristipaval** [comment]
[The backend PR](https://github.com/Expensify/Auth/pull/13419) is ready for review.

**Comment by cristipaval** [comment]
@rezkiy37, the backend PR has been deployed

**Comment by rezkiy37** [comment]
Hey @cristipaval!
I can confirm that the backend allows the app to render reports now. Thank you!

However, I just tested it and found that there is a crucial difference between normal invoice rooms and invoices with multiple expenses. They are not defined as invoice rooms or invoice reports but they are policy expense reports.  

<details><summary>Screenshots</summary>
<p>

### Invoice room
<img width="1920" alt="Screenshot 2024-12-05 at 14 58 18" src="https://github.com/user-attachments/assets/c73aac6d-ea45-478b-8899-d729595391a2">

### Invoice report actions 
<img width="1920" alt="Screenshot 2024-12-05 at 15 04 34" src="https://github.com/user-attachments/assets/fc68fba5-6f68-4604-8979-b4e0c20c7278">

### Invoice report
<img width="1920" alt="Screenshot 2024-12-05 at 15 16 31" src="https://github.com/user-attachments/assets/88560b7a-ce4b-4b37-a3b1-f5e613cb1827">

</p>
</details> 

Does it make sense?

**Comment by cristipaval** [comment]
Hey @rezkiy37!

The invoice report should be rendered similarly to an expense report, not to an invoice room or expense chat. So you should get the `report.type = invoice`

**Comment by cristipaval** [comment]
I added more clarification [here](https://expensify.slack.com/archives/CSL3XBCCR/p1733409751174069?thread_ts=1730896857.770339&cid=CSL3XBCCR). Let me know if you still need changes in the backend

**Comment by VictoriaExpensify** [comment]
Created request to add regression test to testrail https://github.com/Expensify/Expensify/issues/455488

**Comment by VictoriaExpensify** [comment]
Payment summary:
C: @rezkiy37 - Contractor
C+: @dukenv0307 paid $250 via Upwork
