### ISSUE TITLE
[HOLD for payment 2024-12-05] [$125] Taxes - BNP input is not auto focused in add rate page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#51543]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.54-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5134453
**Email or phone of affected tester (no customers):** applausetester+kh1610015@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Launch New Expensify app
2. Go to workspace settings > Taxes
3. Tap Add rate
4. Tap Value

## Expected Result:
BNP input will be auto focused

## Actual Result:
BNP input is not auto focused

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [x] iOS: Standalone
- [x] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/93729d32-8f90-4ec5-b749-ef77e5adb942

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021850971328621900159</li>
        <li>Upwork Job ID: 1850971328621900159</li>
        <li>Last Price Increase: 2024-11-11</li>
<li>Automatic offers: </li>
<ul>
<li>Krishna2323 | Contributor | 104920003</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @garrettmknight</details>

**Comment by lanitochka17** [comment]
Production:

https://github.com/user-attachments/assets/6e3c4070-cece-4826-be59-894fe2b7cecb

**Comment by Beamanator** [comment]
@Krishna2323 

> I don't think this is caused by any recent PR.

But then wouldn't that mean that the issue should be reproducible in prod?

**Comment by Beamanator** [comment]
I'm going to call this NAB - also I don't know if we need it to look "focused" - pressing numbers works fine

**Comment by QichenZhu** [comment]
The root cause is likely from upstream, as this happens only after enabling Bridgeless mode, but adding a delay as @Krishna2323 suggested might be the quickest option for now.

**Comment by thienlnam** [comment]
Hmm, actually we shouldn't be adding setTimeouts here - I'm not sure how that other approach made it into the codebase. That doesn't address the root cause of the issue

**Comment by thienlnam** [comment]
We can update this form so it's consistent with the rest, but it's still a workaround. Ideally we'd solve this upstream for all of these cases and remove them, however not something we need to do in this issue

**Comment by garrettmknight** [comment]
@thienlnam mind giving this one a look?

**Comment by garrettmknight** [comment]
@Ollyws please fill out the checklist

**Comment by garrettmknight** [comment]
@Krishna2323 paid you out!

**Comment by garrettmknight** [comment]
@Ollyws bump on the checklist

**Comment by garrettmknight** [comment]
**Payment Summary:**
- Contributor: @Krishna2323 $125 paid via Upwork
- Reviewer: @Ollyws $125 paid via NewDot


@Ollyws go ahead and request.

**Comment by garrettmknight** [comment]
$125 approved for @Ollyws
