### ISSUE TITLE
[HOLD for payment 2024-11-11] [Workspace Feeds] Default feedname should be %bank% cards

### ISSUE THREAD

**Issue by grgia** [Expensify/App#51558]
https://expensify.slack.com/archives/C06ML6X0W9L/p1729884555181589

Mock
![image](https://github.com/user-attachments/assets/a4379580-ae20-443a-b068-8dee9c4e27d5)
App
![image](https://github.com/user-attachments/assets/3b20daf6-3e92-4e2e-8431-994e3e84b07e)

<details><summary>Issue Owner</summary>Current Issue Owner: @bfitzexpensify</details>

**Comment by mountiny** [comment]
$125 for checklist and help for @allgandalf on the second pr

**Comment by bfitzexpensify** [comment]
Offer sent @allgandalf

**Comment by bfitzexpensify** [comment]
Thanks! Let's close this out.
