### ISSUE TITLE
Task - An error occurs when trying to create a task with a description

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#51560]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.54-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5137753
**Email or phone of affected tester (no customers):** sustinov@applausemail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Open https://staging.new.expensify.com/
2. Log in with a new HT account
3. Go to your personal DM
4. Create a task with a description (contains only numbers)

## Expected Result:
The user should be able to create a task with description

## Actual Result:
An error occurs when trying to create a task with a description

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/44d2560f-5b5e-4389-9429-943b2fbe6f77

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by zfurtak** [comment]
Hello, I'm Zuza from Software Mansion agency and I could take care of this issue 😊

**Comment by jliexpensify** [comment]
Thanks @NJ-2020! I have assigned you @zfurtak - just as a heads up, we aren't really prioritising `Task` bugs atm ([asking for the priority here](https://expensify.slack.com/archives/C01SKUP7QR0/p1730148716506979?thread_ts=1729721728.427419&cid=C01SKUP7QR0))

**Comment by jliexpensify** [comment]
Alright sorry @zfurtak - we're going to close this one!
