### ISSUE TITLE
[$250] [Custom feeds] Feed details explanations are missing

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#51563]
Reported [here](https://expensify.slack.com/archives/C06ML6X0W9L/p1729884432477149) - find more details in the slack thread

BUG: Feed details pages for Visa/Mastercard/Amex are all missing the explainers that link to where to find the fields
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021857093201326774795</li>
        <li>Upwork Job ID: 1857093201326774795</li>
        <li>Last Price Increase: 2024-11-14</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @allgandalf</details>

**Comment by mountiny** [comment]
No payments needed

**Comment by VickyStash** [comment]
Hi, I'm Viktoryia from Callstack - expert contributor group - and I would like to work on this issue.

**Comment by VickyStash** [comment]
The [PR](https://github.com/Expensify/App/pull/51575) has been opened for the review.

**Comment by joekaufmanexpensify** [comment]
Only payment is $250 to @allgandalf for C+ via Upwork

**Comment by joekaufmanexpensify** [comment]
@allgandalf offer sent for $250!

**Comment by joekaufmanexpensify** [comment]
Ah, I see. So you're being paid in bulk?

**Comment by mountiny** [comment]
@joekaufmanexpensify Yes I have talked with @allgandalf @DylanDylann @dukenv0307 so we are going to collect all the issues and manage the payment in the end as that will be easier than handling this on individual issues. We also agreed that the base price will be $125 since there is plenty of these and they are often small and we can change to $250 on case by case basis

Once the checklist is complete, we can close

**Comment by joekaufmanexpensify** [comment]
Makes sense! Will look out for the checklist then and close after

**Comment by joekaufmanexpensify** [comment]
I actually don't think we need the checklist here. This wasn't introduced anywhere, it just got missed during implementation. Further, I already have this case covered in the manual test script, so it will be codified into a regression test when I pass those off to Applause. We should be all set here. TY!
