### ISSUE TITLE
[HOLD for payment 2024-11-11] [Custom feeds]  The freeform fields have incorrect limit

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#51564]
Reported [here](https://expensify.slack.com/archives/C06ML6X0W9L/p1729884486849509) - find more details in the slack thread.

BUG: When adding a commercial feed, freeform fields do not have the field length limit discussed in the design document. They should all be capped at 100 characters.

**Comment by VickyStash** [comment]
Hi, I'm Viktoryia from Callstack - expert contributor group - and I would like to work on this issue.

**Comment by VickyStash** [comment]
The [PR](https://github.com/Expensify/App/pull/51569) has been opened for the review!

**Comment by mountiny** [comment]
@allgandalf could you please complete the checklist? thanks!

**Comment by sakluger** [comment]
I sent an offer via Upwork. Now we're just waiting for the checklist to be completed and for the offer to be accepted.

**Comment by mountiny** [comment]
@allgandalf we can handle the test in https://github.com/Expensify/App/issues/51899

**Comment by sakluger** [comment]
Thank you! I paid the contract, we're all done here.
