### ISSUE TITLE
Enable links to in-app routes from chat messages

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#5157]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!

cc @marcaaron 
___

## Problem

While working on https://github.com/Expensify/Expensify/issues/176355, we have found out there is currently no way how to add a link to chat message, which would navigate to some other view of the App (without reloading or opening new window).

We want to add a link to Concierge message, which would open the RHN with Guide calls for easier setup. 

Potentially in future, there could be more usecases, where we will need this option (ie someone sharing a link like `new.expensify.com/workspace/foo` with someone else).

## Solution

As per [this Slack thread](https://expensify.slack.com/archives/C03TQ48KC/p1631144535423100?thread_ts=1631106791.394900&cid=C03TQ48KC), we have decided to create a new component for [AnchorForCommentsOnly](https://github.com/Expensify/App/blob/main/src/components/AnchorForCommentsOnly/index.js) which would be something along the lines of `InternalAnchorForCommentsOnly`.

Here, we will treat any anchor, whose `href` attribute starts with `/` as internal link and prevent default usage of `<a>` tag (which forces the page to reload) and use in-app system of navigation: `Navigation.navigate()`.

1. Check if the href starts with `/`.
    - If no, process the link as we do now.
2. If yes, check if the route matches any in app `ROUTES`
3. If yes again, make sure to create Pressable Text with same styling as a link which will use `Navigation.navigate()` on press.

**Comment by mountiny** [comment]
@marcaaron I have added `Planning` label here for now as we can still think of some improvements. Please free to chime in if you want to specify something a bit more.

I think it should be `Internal` if we want to have it done faster. Also not sure if External contributor could test this as there are not concierge messages starting with `/` and they cannot create such a message from chat.

**Comment by marcaaron** [comment]
I like the solution - seems pretty straight forward to me. Only I'm not sure we should call this `InternalAnchorForCommentsOnly` or if we really need a new component. We can just check the `href` here then return the alternate style of link with a navigate method.

**Comment by mountiny** [comment]
@marcaaron I totally agree with you, we can just check for it without creating a new component and then potentially refactor if it gets more complex over time.

**Comment by botify** [comment]
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/1218935234) to staging by @marcaaron in version: 1.0.95-3 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|failure ❌ 
🕸 web 🕸|success ✅

**Comment by botify** [comment]
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/1222459337) to production by @roryabraham in version: 1.0.96-0 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅
