### ISSUE TITLE
Android - hybrid app - Tapping copy to clipboard of user suggestion, app closes and reopens

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#51578]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9. 0.54-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Launch hybrid app
2. Open 1:1 chat with an user
3. Tap plus icon -- assign task
4. Enter task name and description as @
5. Tap save
6. Open the task created
7. Tap description
8. Enter near @, an existing user id-
@[jaihanumanblog@gmail.com](mailto:jaihanumanblog@gmail.com)
and save
9. Now long press on the email id displayed in the system message
10. Select copy to clipboard

## Expected Result:
Tapping copy to clipboard of user suggestion, app must not close

## Actual Result:
Tapping copy to clipboard of user suggestion, app closes and reopens

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [x] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/9c8047de-0f83-4f31-9e26-3cdb76a4305f

[log.txt](https://github.com/user-attachments/files/17544670/log.txt)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@slafortune  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by slafortune** [comment]
I was not able to recreate this - but also it seems very unlikely that anyone will be taking these steps to create a task.
