### ISSUE TITLE
[no payment] [Custom feeds] Incorrect default feed name

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#51570]
Reporte [here](https://expensify.slack.com/archives/C06ML6X0W9L/p1729884647586059)- check for more details

BUG: Card feed name field is blank on feed settings page when the feed name is the default. We should show the default feed name in the field. Shown in :thread:.

**Comment by mountiny** [comment]
no payments will be needed

**Comment by koko57** [comment]
I would like to help with this issue 🙂

**Comment by RachCHopkins** [comment]
The upwork job link above links back to this issue, the first [payment summary](https://github.com/Expensify/App/issues/51570#issuecomment-2458441466) says @allgandalf is paid via NewDot, but our records don't reflect that. Can I just confirm here @mountiny that I need to:

1. Add a job to Upwork
2. Send an offer to @allgandalf 
3. Pay them via that offer

**Comment by mountiny** [comment]
@allgandalf could you please add the checklist for this one? 

I think this one would be for $125. We agreed to use this amount for the feeds clean up

**Comment by mountiny** [comment]
> in sometime

famous last words

**Comment by RachCHopkins** [comment]
Regression test created, I think we are good to close this!
