### ISSUE TITLE
Android - Search - Keyboard doesn´t open automatically, when reopening expense after edited.

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#51580]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.54-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5135648&group_by=cases:section_id&group_order=asc&group_id=296775
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Open the Expensify app.
2. Tap on "Search"
3. Open any expense.
4. Verify the keyboard is automatically displayed.
5. Edit any field on the expense.
6. Tap on the arrow on the top left corner.
7. Reopen the expense.
8. Verify the keyboard is still displayed automatically.

## Expected Result:
The keyboard should be automatically displayed everytime the user opens the expense.

## Actual Result:
The keyboard is not displayed automatically anymore, when reopening an expense after editing any field on it, in "Search" section.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/18232cba-0c19-4ed0-a9d0-6d0b5a88a0d9

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by FitseTLT** [comment]
Intentional, we only auto focus for empty chats in mobile.
