### ISSUE TITLE
[$250] Held expense - System message shows full amount is paid when only pending amount is paid

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#51596]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.54-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5103344
**Email or phone of affected tester (no customers):** applausetester+wdws45@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. [User A] Open DM with User B
3. [User A] Submit two expenses of different amount to User B
4. [User B] Open one of the expenses submitted by User A and hold the expense
5. [User B] Go back to the expense report
6. [User B] Click Pay elsewhere
7. [User B] Select the pending amount
8. [User B] Note that the system message for the paid report shows "full amount" is paid instead of "pending amount"

## Expected Result:
The system message for the paid report will show that "pending amount" is paid instead of "full amount"

## Actual Result:
The system message for the paid report shows that "full amount" is paid instead of "pending amount"

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [x] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [x] iOS: HybridApp
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/9c57e5b0-ba5e-4299-be57-38871b05ebec

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021851473940776586673</li>
        <li>Upwork Job ID: 1851473940776586673</li>
        <li>Last Price Increase: 2024-10-30</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @Beamanator</details>

**Comment by lanitochka17** [comment]
@RachCHopkins  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by RachCHopkins** [comment]
Correct: the full figure is shown as the Paid amount, but it should be the amount minus the hold:

![image](https://github.com/user-attachments/assets/9f257d44-5864-46d5-9abf-98aa7fbe8d71)

**Comment by FitseTLT** [comment]
@RachCHopkins This is a BE problem. We are setting the correct value from the FE, but the BE then updates it to the wrong value. You can easily observe it in the OP video.

**Comment by Beamanator** [comment]
Oh baby yeah this def looks internal, I'll have a look soon

**Comment by Beamanator** [comment]
Haven't actually started on this, @robertjchen just curious are you still working on Held expense tasks or not so much now'days since that stuff has been live for a bit?

**Comment by RachCHopkins** [comment]
@Beamanator shall I relabel this Internal or are we still awaiting confirmation?

**Comment by Beamanator** [comment]
I think it's safe to make `Internal` 👍

**Comment by RachCHopkins** [comment]
Thanks @Beamanator - I have adjusted that! FYI I can't seem to change the star on the issue owner so it will be overdue until you comment again!

**Comment by RachCHopkins** [comment]
Oh good, it's working today.

**Comment by robertjchen** [comment]
> Haven't actually started on this, @robertjchen just curious are you still working on Held expense tasks or not so much now'days since that stuff has been live for a bit?

Not much anymore since I'm about to go OOO for a bit. It definitely sounds like backend- let me know if you have any q's in the meantime 🙏

**Comment by Beamanator** [comment]
Hmm I ran through test steps in dev...

> 1. Go to staging.new.expensify.com
> 2. [User A] Open DM with User B
> 3. [User A] Submit two expenses of different amount to User B
> 4. [User B] Open one of the expenses submitted by User A and hold the expense
> 5. [User B] Go back to the expense report
> 6. [User B] Click Pay elsewhere

But at this step ^, I didn't see the "Pay" button anymore for User B - @RachCHopkins can you confirm if you see the "Pay" button for user B at this step?

**Comment by RachCHopkins** [comment]
@Beamanator I do not - is that a new bug? I was able to replicate this last month, and now the Pay button has vanished.

**Comment by RachCHopkins** [comment]
https://github.com/Expensify/App/issues/53166 - yes it is a new bug

**Comment by Beamanator** [comment]
aahhhh ok so let's put this one on hold for that one probably?

**Comment by RachCHopkins** [comment]
Ok, that PR has been merged @Beamanator

**Comment by RachCHopkins** [comment]
Ok, now I don't see Hold @Beamanator . Should Hold be a thing in a DM? It works fine in the workspace chat. Was the real issue that there should not have been Hold in DM?

**Comment by Beamanator** [comment]
@robertjchen do you know know if users should be able to "Hold" expenses in DMs?

**Comment by Beamanator** [comment]
Asked in slack - https://expensify.slack.com/archives/C06ML6X0W9L/p1734428916634449

**Comment by Beamanator** [comment]
Groovy, looks like we agreed in slack that Hold feels like a workspace feature, not P2P 👍

**Comment by RachCHopkins** [comment]
Cool, so are we actually left with anything to fix here @Beamanator ?

**Comment by Beamanator** [comment]
Not that I know of, or did I forget about some other piece in this issue @rushatgabhane ?

**Comment by Beamanator** [comment]
looks like we should close this out!
