### ISSUE TITLE
[HOLD for payment 2024-12-07] [$125] Update the intent video for `Get paid back from my employer`

### ISSUE THREAD

**Issue by anmurali** [Expensify/App#51603]
Update the intent video shown by Concierge when someone selects `Get paid back from my employer`. Right now it shows a manual request and we want it to show a receipt being scanned.

[GIF version](https://www.dropbox.com/scl/fi/08bv1tmjeml48qr9b94yw/11_2_Onboarding_Q4_v3.gif?rlkey=5c3yhsy76v1lasiysbmpvuanu&st=usj37u19&dl=0) [MP4 version](https://www.dropbox.com/scl/fi/xddzcpx35qkju8cagokma/11_2_Onboarding-Q4-v3.mp4?rlkey=y1r5uf5iquw7s4okhowz8ii84&unfurl=slack_gen&dl=0)

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021850986914069355403</li>
        <li>Upwork Job ID: 1850986914069355403</li>
        <li>Last Price Increase: 2024-11-11</li>
<li>Automatic offers: </li>
<ul>
<li>Krishna2323 | Contributor | 104920383</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @abdulrahuman5196</details>

**Comment by anmurali** [comment]
For https://github.com/Expensify/Expensify/issues/432811 [Internal only design issue]

**Comment by nikihatesgh** [comment]
The video has been added here: https://github.com/Expensify/Web-Static/blob/main/videos/guided-setup-get-paid-back-v3.mp4

**Comment by anmurali** [comment]
@Krishna2323 - can you update the video in product now?

**Comment by NikkiWines** [comment]
Thee url will be `${CLOUDFRONT_URL}/videos/guided-setup-get-paid-back-v3.mp4`

**Comment by NikkiWines** [comment]
updated URL is live!

**Comment by abdulrahuman5196** [comment]
Hi, Will check today.

**Comment by nikihatesgh** [comment]
@abdulrahuman5196 is there any update here?

**Comment by abdulrahuman5196** [comment]
Checking now

**Comment by abdulrahuman5196** [comment]
@Krishna2323 's proposal here https://github.com/Expensify/App/issues/51603#issuecomment-2442515857 looks good and works well. Since this is a straightforward change, going with the first proposal.

🎀 👀 🎀
C+ Reviewed

**Comment by francoisl** [comment]
I thought we already had a PR in progress for this? I may have confused with something else though. Anyway, pretty straightforward change, let's get this done 🚀

**Comment by RachCHopkins** [comment]
Payment Summary:

- Contributor: @Krishna2323 to be paid $125 via Upwork
- Contributor+: @abdulrahuman5196 to be paid $125 via NewDot Manual Request

Upwork job [here](https://www.upwork.com/jobs/~021850986914069355403)

**Comment by RachCHopkins** [comment]
Contributor has been paid, the contract has been completed, and the Upwork post has been closed.

**Comment by JmillsExpensify** [comment]
$125 approved for @abdulrahuman5196
