### ISSUE TITLE
Get mock ups for update to Accounting page in Workspace setup. 

### ISSUE THREAD

**Issue by danielrvidal** [Expensify/App#51623]
Coming from [this update](https://github.com/Expensify/App/issues/51487), can you please provide a mock up for this solution:

We're adding another option on the Accounting page to help users get their accounting setup if they don't see their account package. I think if you do the first one on web/mobile, we can take it from there.

We're going to update the page below with the following language. The button should be all the way to the right, like the accounting package. 
- If they have an onboarding specialist assigned display the following and link to the #admins room with the setup specialist.
>[?] Need another accounting package?                          [Talk to your onboarding specialist]
- If not, if they have an account manager assigned display the following and link to the DM with their account manager.
> [?] Need another accounting package?                          [Talk to your account manager]
- Else, display the following and link to their Concierge DM.
> [?] Need another accounting package?                          [Talk to concierge]

![image](https://github.com/user-attachments/assets/cd378487-9014-4167-9b39-e43dab97be52)

**Comment by dannymcclain** [comment]
Mock ups are [here in Figma](https://www.figma.com/design/Gnj3JxgnhKYvtcaTIm2E1i/Self-guided-tour-(Onboarding)?node-id=220-14101&node-type=canvas&t=lwcY169z9EnOpBFk-11).

Preview:

![image](https://github.com/user-attachments/assets/745826db-489f-46ea-b90a-c2c0939acb37)

![image](https://github.com/user-attachments/assets/ffd650ac-dbeb-4ef0-b42b-98b4546a6f5f)

![image](https://github.com/user-attachments/assets/41097ab6-a7da-4b97-89f9-c47819ea9cec)

**Comment by dannymcclain** [comment]
Since the linked issue is getting proposals and these mocks are done, I'm going to go ahead and close this one out. Feel free to reopen if you need to!
