### ISSUE TITLE
Profile - Validation error only appears after the invalid phone number is saved

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#51649]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.55-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+wspkwskwpos@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to Profile > Phone number
3. Enter valid local phone number (or numbers that don't result in error)
4. Save it

## Expected Result:
If the number is invalid, user should not be able to save it and validation error will appear upon saving it

## Actual Result:
When the number is invalid, user is able to save it and validation error only appears after saving it

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/47d55356-829c-48cb-9eff-bbb09ede2a9e

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by pecanoro** [comment]
@lanitochka17 Why do we think `+15005550006` is not a valid formatted phone number? It seems to be a valid one

**Comment by pecanoro** [comment]
I am closing this one since the number has the right format
