### ISSUE TITLE
[HOLD for payment 2024-12-19] [$250] Accounting - Unnecessary tooltip showing the same icon on export page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#51656]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.55-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+nl732@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition:
- A workspace with QBO or any accounting integration connected
- An expense created and paid
1. Go to transaction thread of the paid expense
2. Click on header > Export
3. Hover over the icon

## Expected Result:
No tooltip should be shown

## Actual Result:
Tooltip is shown showing the exact same icon that is already visible

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/5a38fb8c-3d34-4893-8d72-6f87cf6ae6f4

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021851328333556408802</li>
        <li>Upwork Job ID: 1851328333556408802</li>
        <li>Last Price Increase: 2024-11-12</li>
<li>Automatic offers: </li>
<ul>
<li>Krishna2323 | Contributor | 104866520</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @bfitzexpensify</details>

**Comment by lanitochka17** [comment]
@bfitzexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by bfitzexpensify** [comment]
Payment summary:

@Krishna2323 paid $250 via Upwork for contributor work ✅ 
@parasharrajat to be paid $250 via ND request for C+ work

**Comment by JmillsExpensify** [comment]
$250 approved for @parasharrajat
