### ISSUE TITLE
[HOLD for payment 2024-11-22] [$250] Search - Not here page appears when selecting a non-existing user and then going online

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#51651]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.55-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5140184
**Email or phone of affected tester (no customers):** applausetester+bm176@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Go offline
3. Click on the search icon at the top right
4. Search for a non-existing user
5. Click on the search result
6. Go online

## Expected Result:
Not here page should not appear, and the chat with the non-existing user should remain visible

## Actual Result:
Not here page appears when going online, which contradicts the behavior when performing these steps while online

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/4bb0258a-6873-4dd3-a50b-88a64167e885

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021851703015510861438</li>
        <li>Upwork Job ID: 1851703015510861438</li>
        <li>Last Price Increase: 2024-10-30</li>
<li>Automatic offers: </li>
<ul>
<li>dukenv0307 | Contributor | 104740405</li>
<li>NJ-2020 | Contributor | 104800732</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @isabelastisser</details>

**Comment by lanitochka17** [comment]
@isabelastisser  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave-control

**Comment by isabelastisser** [comment]
### Heads up, I will be OOO from Oct 31 until Nov 4, so please re-apply the Bug label and assign a new member if needed. Thanks!

**Comment by isabelastisser** [comment]
Payment made in Upwork to @NJ-2020.

@dukenv0307, please accept the offer in Upwork and I will process the payment. Thanks!

**Comment by isabelastisser** [comment]
[Payment summary.](https://github.com/Expensify/App/issues/51651#issuecomment-2494533041)

**Comment by JmillsExpensify** [comment]
$250 approved for @dukenv0307
