### ISSUE TITLE
[$125] Expensify Card - Unable to proceed with empty Address line 2 field when adding missing details

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#51654]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.55-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:** applausetester+khcategory17@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition:
- User has assigned themselves a physical card
- User personal details have not been added
1. Go to staging.new.expensify.com
2. Go to workspace chat
3. Click Add missing details
4. Proceed to address step
5. Enter address while leaving Address line 2 field empty
6. Click Next

## Expected Result:
User should be able to proceed when Address line 2 field is empty (production behavior)

## Actual Result:
User is unable to proceed when Address line 2 field is empty

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/9461b7b3-51cb-4997-81df-36a74374caa9

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021851264059586500401</li>
        <li>Upwork Job ID: 1851264059586500401</li>
        <li>Last Price Increase: 2024-10-29</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave-collect - Release 2

**Comment by hungvu193** [comment]
cc @burczu it look like it came from our PR

**Comment by burczu** [comment]
Ok, I confirm this is regression from https://github.com/Expensify/App/pull/51231 and as @NJ-2020 pointed out, this line should just not be changed:

```javascript
const errors = ValidationUtils.getFieldRequiredErrors(values, STEP_FIELDS); 
```

Please assign me and I'll prepare a fix.

**Comment by hungvu193** [comment]
Thank you @burczu

**Comment by Beamanator** [comment]
Thanks @burczu 🙏 

Assigning `Bug` b/c I believe we should pay @NJ-2020 at least something for helping us find the fix quick 🙏

**Comment by burczu** [comment]
The PR with the fix is ready: https://github.com/Expensify/App/pull/51662

**Comment by hungvu193** [comment]
That was quick 🚀. I'm on it

**Comment by Beamanator** [comment]
Confirmed fixed on staging! Marking NAB - but won't close till we pay out @NJ-2020 👍

**Comment by garrettmknight** [comment]
@NJ-2020 has been paid, closing.
