### ISSUE TITLE
[HOLD for payment 2024-11-14] [Custom feeds] Clean up for the wallet and workspace member page

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#51660]
1. On the member details page, the company cards icons are too small
![image](https://github.com/user-attachments/assets/e9a9e1b4-dd71-4d30-9e7e-2433357c5666)

____

2. On the wallet page, we are not showing the correct visa/ mastercard icons:

![image](https://github.com/user-attachments/assets/9f75c80a-b80f-4e77-ae8a-4e9fbde099aa)

____

<details><summary>Issue Owner</summary>Current Issue Owner: @stephanieelliott</details>

**Comment by VickyStash** [comment]
Hi, I'm Viktoryia from Callstack - expert contributor group - and I would like to work on this issue.

**Comment by VickyStash** [comment]
The [PR](https://github.com/Expensify/App/pull/51671) has been opened for the review

**Comment by stephanieelliott** [comment]
Summarizing payment on this issue: 

 - Contributor: @VickyStash - no payment due (expert contrib)
 - Contributor+: @dukenv0307 - $250 via Upwork -- offer extended, please accept!  https://upwork.com/nx/wm/offer/104964789
 
 Upwork job is here: https://www.upwork.com/jobs/~021858766650246025249

**Comment by stephanieelliott** [comment]
Sounds good! Offer was withdrawn and UW job canceled.
