### ISSUE TITLE
Deeplink -"You don't have access to this chat" link navigate to wrong report

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#51665]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.55-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:**  N/A
**Email or phone of affected tester (no customersm):** testpayment935+522@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Navigate to http://www.staging.new.expensify.com/
2. Submit 1 or 2 distance expense correctly
3. Submit the the next distance expense with wrong waypoints while being offline (to get an error IOU)
4. Copy the link of the IOU of step 3
5. Back online
6. Click on the close icon of the error and navigate back to chat report
7. While LHN on chat report, copy the link from step 4 in the URL
8. Click on "You don't have access to this chat" link

## Expected Result:
"You don't have access to this chat" link should navigate back to chat report as it is the last navigated chat

## Actual Result:
"You don't have access to this chat" link should navigate to combined report or report conversation

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/ec6f5952-7c4d-4dcf-a78d-32d9c5877dc4

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@joekaufmanexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by joekaufmanexpensify** [comment]
I am not exactly following the bug based on the description above, as both the expected and actual behavior are written as if they are the expected behavior. 

However, it seems like we think there is some navigation issue related to someone copying the URL from a report we fail to successfully create, and later pasting it into their browser and trying to navigate to it again. I don't think that is a super realistic action for a user to take, so going to close this for now. 

Please let me know if there is some additional context for this one, and happy to review further!
