### ISSUE TITLE
mWeb/Chrome - Search - Empty space created below search list and chat can be opened by tapping on it

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#51687]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.55-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5141647&group_by=cases:section_id&group_order=asc&group_id=296775
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Open the staging.new.expensify.com website
2. Open any chat
3. Tap on the search icon on the top right corner
4. Scroll down fast through the list
5. Verify no empty space is created below the list

## Expected Result:
When the user scrolls through the search list, no empty space should be created below the results

An empty space is created below the search list when fast scrolling through it, and tapping on that empty space, opens a chat or report from the list

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/46111856-a6ac-4f12-9e5c-07cec27b6a47

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@lschurr  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by SzymczakJ** [comment]
I've looked into this but couldn't reproduce it on current main branch
