### ISSUE TITLE
Scheduled email tests - "Create a workspace" is crossed out and seems not in place

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#51685]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.55-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Unable to check
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:**  N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5107636
**Issue reported by:** Applause - Internal Team

## Action Performed:
Preconditions: create an account in OldDot choosing the option "Manage expenses for a small team".
1. Open the 7th email for this account with the subject "Recapping your first week in Expensify".
2. Check the content. the next steps are to get you up and running

## Expected Result:
The correct steps provided in the section "...the next steps are to get you up and running"

## Actual Result:
"Create a workspace" is on the 4th place among the steps after "Set up categories", and is crossed out

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

<img width="1132" alt="48_AM" src="https://github.com/user-attachments/assets/3779ef88-d4fa-45ca-943c-0aa52aae9649">

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@muttmuure  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by muttmuure** [comment]
I think it is crossed out because it's a completed task.
