### ISSUE TITLE
Desktop Prod deploys sometimes fail due to "problems locating the `'lipo'` tool"

### ISSUE THREAD

**Issue by Beamanator** [Expensify/App#51688]
**Slack conversation:** https://expensify.slack.com/archives/C07J32337/p1730199872560049

Seems our Desktop prod deploys are failing sometimes with `Failed to locate 'lipo', requesting installation of command line developer tools.`

Example: https://github.com/Expensify/App/actions/runs/11570554014/job/32206608033, noted in slack [here](https://expensify.slack.com/archives/C07J32337/p1730199872560049)

@AndrewGable volunteered to help fix 🙏  Thanks! Good luck!

**Comment by RachCHopkins** [comment]
Handing this to you @AndrewGable - I definitely can't repro this, so I'm assuming you can!

**Comment by AndrewGable** [comment]
Yup all good!

**Comment by AndrewGable** [comment]
Not a whole lot of search results out there, this issue is the first result 😆 

![Google Chrome 2024-10-31 at 12 38 22](https://github.com/user-attachments/assets/3be8572c-3ef4-47d9-81ce-87917274547a)

**Comment by AndrewGable** [comment]
Can only find one instance of this and worked on retry, so I think we are OK to close and look into this deeper if it happens more often.

**Comment by AndrewGable** [comment]
Ok so two things I notice:

1. We are using `macos-14-large` to build desktop vs `macos-13-xlarge` on iOS
2. We do not set the XCode version on desktop (so we use XCode 15.4) and on iOS we set it to XCode 15.2

**Comment by AndrewGable** [comment]
Haven't seen this one in  a little bit, will keep monitoring.

**Comment by AndrewGable** [comment]
Haven't seen this in a few, closing for now
