### ISSUE TITLE
[$350] Writing Detailed Design for Multi Tags project

### ISSUE THREAD

**Issue by yuwenmemon** [Expensify/App#51694]
This is the bulk amount for the writing of the detailed design for the project [Multi-tag configuration / Dependent tags in NewDot ](https://github.com/Expensify/Expensify/issues/418655). To be paid to @allgandalf 

Amount: $350

Link to Doc: https://docs.google.com/document/d/1_p8qZXVKG-s32i9GKqVjCLEcEREBUEgYcxk3KYHXMVg/edit?usp=sharing

cc @garrettmknight 
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021854430349143675049</li>
        <li>Upwork Job ID: 1854430349143675049</li>
        <li>Last Price Increase: 2024-11-07</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @ahmedGaber93</details>

**Comment by yuwenmemon** [comment]
@allgandalf can you do payment on NewDot?

**Comment by yuwenmemon** [comment]
Aiight, triggered a job in Upwork.

**Comment by JmillsExpensify** [comment]
Offer sent!

**Comment by JmillsExpensify** [comment]
All paid out!
