### ISSUE TITLE
[HOLD for payment 2024-12-05] [HOLD for payment 2024-11-28] Update the Switch to Expensify Classic survey to drive better feedback

### ISSUE THREAD

**Issue by danielrvidal** [Expensify/App#51703]
**Problem:** We are currently prompting people who Switch to Classic with a modal asking for a reason.  But we do it inconsistently (on web but not mobile), and there are too many results to look at, and the results are kind of useless because they include known complaints from users we don’t actually think should be using New Expensify, and that we aren’t going to prioritize.

**Solution:** 

**Case 1: People that are redirected into NewDot.** 

- This user group has the NVP `tryNewDot.classicRedirect.dismissed` set to `false`
- We show them the existing survey when they click `Switch to Expensify Classic` in Settings.
- We add a new page to the start of the flow to offer a call to speak to a product manager. Clicking `Book a call` will open [this Calendly link](https://calendly.com/d/cqsm-2gm-fxr/expensify-product-team) in a new browser tab, and closes the RHP modal when clicked.
- Make the free form response page in the survey not mandatory anymore

Copy: 
```
**Would you like to speak to a product manager?** 

By switching to Expensify Classic, you will miss out on:
* Chatting directly on expenses and reports
* Ability to do everything on mobile
* Travel and expense at the speed of chat

We'd be excited to get on a call with you to understand why. You can book one with one of our senior product managers to discuss your needs.

[No thanks]
[Book a call]
```
![image](https://github.com/user-attachments/assets/caf72ed5-ea7b-4c0d-91cf-eace5f512255)

- [Internal - NW] Keep creating GHs for the research team. Engineering don't need to worry about this. 

**Case 2: People not redirected into NewDot** 
- This user group has no `tryNewDot` NVP OR `tryNewDot.classicRedirect.dismissed===true`
- We **do not** show them the survey when they click `Switch to Expensify Classic` in Settings.
- Instead, we show them a new page to educate them on how to go directly to Expensify Classic next time.

Copy: 

```
Quick tip... 
You can go straight to Expensify Classic by visiting expensify.com. Bookmark it for an easy shortcut!
[Take me to Expensify Classic]
```

![image](https://github.com/user-attachments/assets/88b52263-3e06-4dd6-b10a-b1f933a8a85f)

- [Internal - DV/TRJ] Track the button click on that page separately in FullStory, so we can see how many keep hitting this flow going forward and continue to try and curb it if it remains high. I've purposely labelled this button slightly differently to Case 1 to make it easy for us to do that.

<details><summary>Issue Owner</summary>Current Issue Owner: @trjExpensify</details>

**Comment by anmurali** [comment]
This is going to be implemented on web and hybrid app, correct? cc @AndrewGable

**Comment by AndrewGable** [comment]
Yes it should be implemented on all platforms 👍

**Comment by danielrvidal** [comment]
Asking for the next steps, let's try to make quick progress on this one!

**Comment by trjExpensify** [comment]
Updated the solution OP to reflect where we landed. My next steps:

- Get the Calendly link to include 
- Confirm if any of this actually needs backend (I don't think it does). 
- Get someone to start on it.

**Comment by trjExpensify** [comment]
I've been chatting to Hans and confirmed we don't need any backend here. He's going to take on the implementation for us, starting today (tomorrow his time).

Working on getting the calendly link, and I'll add it to the OP.

**Comment by trjExpensify** [comment]
Added the [Calendly link](https://calendly.com/d/cqsm-2gm-fxr/expensify-product-team) to the OP, @hungvu193.

**Comment by hungvu193** [comment]
Thanks Tom, I'll prepare a PR today!

**Comment by hungvu193** [comment]
I created a PR here: https://github.com/Expensify/App/pull/52526

Also waiting for confirmed translations here:
https://expensify.slack.com/archives/C01GTK53T8Q/p1731572881369449

**Comment by hungvu193** [comment]
Created a draft PR for the tests here:
https://github.com/Expensify/App/pull/52754

**Comment by trjExpensify** [comment]
👋 @shubham1206agra can we get the checklist please?

**Comment by trjExpensify** [comment]
I've created a regression test request based off the tests I wrote for it in the PR [here](https://github.com/Expensify/Expensify/issues/448565).

**Comment by trjExpensify** [comment]
Payment summary [here](https://github.com/Expensify/App/issues/51703#issuecomment-2505592854) is correct. @hungvu193 you can go ahead and request, @shubham1206agra I've sent an offer which I'll pay after the checklist is added.

**Comment by trjExpensify** [comment]
Looks good. Feel free to accept the offer.

**Comment by trjExpensify** [comment]
Paid, closing!

**Comment by garrettmknight** [comment]
$250 approved for @hungvu193
