### ISSUE TITLE
Desktop- Split - Unable to select members for split expense in the group DM

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#51729]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.55-6
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5142441&group_by=cases:section_id&group_id=306203&group_order=asc
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Navigate to a group conversation with at least 2 users
2. Select Split expense
3. Select the Scan tab if it is not already active
4. Upload a digital receipt
5. Click on the radio button and select two members

## Expected Result:
The user can select not all participants from the group DM for the split expense by clicking the radio buttons next to members' names/email addresses

## Actual Result:
Unable to select members for split expense in the group DM. All group DM participants are selected by default

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/cb6d3d04-6039-424c-9c58-50f46b098d72

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@bfitzexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
@bfitzexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by bfitzexpensify** [comment]
This is p2p focused, which isn't a priority right now. Let's close this out for the moment.
