### ISSUE TITLE
[Payment 2024-11-13] [Company cards] Update how we fetch company cards

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#51726]
coming from [here](https://expensify.slack.com/archives/C06ML6X0W9L/p1730278350313989?thread_ts=1729596921.819569&cid=C06ML6X0W9L)
- Filter out Expensify Card from settings.companyCards
- Update [CardSelectionStep](https://github.com/Expensify/App/blob/main/src/pages/workspace/companyCards/assignCard/CardSelectionStep.tsx) and cards assigning flow to use oAuthAccountDetails[<bank>].accountList as card options for OAuth Direct feeds.

<details><summary>Issue Owner</summary>Current Issue Owner: @strepanier03</details>

**Comment by VickyStash** [comment]
Hi, I'm Viktoryia from Callstack - expert contributor group - and I would like to work on this issue.

**Comment by VickyStash** [comment]
I'm going to be **OOO** Oct 31 - Nov 3 🌴 
So, the PR with the updates will be ready on Monday only.

**Comment by VickyStash** [comment]
It looks like @narefyev91 handled this one 👍

**Comment by mountiny** [comment]
Can you add the BZ checklist here please @narefyev91 @DylanDylann

**Comment by DylanDylann** [comment]
### Regression Test Proposal

1. Have any feed added
2. Go to Feed
3. Clicking on Assign card
4. Choose user
5. Verify that you can see cards

**Comment by DylanDylann** [comment]
@strepanier03 I believe that the checklist isn't required on this issue. We can process the payment now

**Comment by strepanier03** [comment]
@DylanDylann - Sent you an [offer](https://www.upwork.com/nx/wm/offer/104890864). I'll check again in the morning, sorry for the late send, it's been a long day.

**Comment by strepanier03** [comment]
I paid and closed the contract for @DylanDylann, thanks everyone!
