### ISSUE TITLE
[HOLD for payment 2024-11-18] [$250] iOS Company cards - View your subscription link opens Subscription page then back to Workspace

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#51733]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.55-6
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+kh2210008@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Launch ND or hybrid app
2. Create a new workspace
3. Go to More features
4. Enable Company cards
5. Tap Upgrade
6. On upgrade success screen, tap View your subscription

## Expected Result:
App will open subscription page

## Actual Result:
App opens subscription page and then opens workspace editor page quickly.
This issue only happens when upgrading workspace to Control from Company cards feature

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [x] iOS: Standalone
- [x] iOS: HybridApp
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/1668819b-9687-4149-94cd-c38a4fee653d

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021853715612324216469</li>
        <li>Upwork Job ID: 1853715612324216469</li>
        <li>Last Price Increase: 2024-11-05</li>
<li>Automatic offers: </li>
<ul>
<li>DylanDylann | Contributor | 104748690</li>
<li>Nodebrute | Contributor | 104757262</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @stephanieelliott</details>

**Comment by lanitochka17** [comment]
@stephanieelliott  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by DylanDylann** [comment]
@Nodebrute's [proposal](https://github.com/Expensify/App/issues/51733#issuecomment-2447125077) looks good to me

🎀 👀 🎀 C+ Reviewed

cc @mountiny

**Comment by DylanDylann** [comment]
If you get assigned, could you raise a PR soon?

**Comment by NikkiWines** [comment]
Yep, @Nodebrute's proposal looks good 👍

**Comment by stephanieelliott** [comment]
Summarizing payment on this issue: 

 - Contributor: @Nodebrute $250 via Upwork - PAID
 - Contributor+: @DylanDylann $250 via Upwork - PAID
 
 Upwork job is here: https://www.upwork.com/jobs/~021853715612324216469
