### ISSUE TITLE
[HOLD for payment 2024-11-29] [HOLD for payment 2024-11-21] Align Firebase performance metrics with core in-app workflows

### ISSUE THREAD

**Issue by adhorodyski** [Expensify/App#51742]
Coming from this Slack thread: https://expensify.slack.com/archives/C05LX9D6E07/p1730214849510819

**Problem**
Our performance metrics do not represent exactly what we care about when tracking App's performance across the user base. They either have unclear naming, or code markers that are put in the wrong places, making measurements incorrect and giving us falsy results.

**Solution**
Let's align the definitions and fix code markers' placement to make sure we collect whole user interactions when people eg. open chats from different scenarios, send message or open up search. Detailed changes in the first comment.

<details><summary>Issue Owner</summary>Current Issue Owner: @adhorodyski</details>

**Comment by adhorodyski** [comment]
`homepage_initial_render` does not serve as a meaningful measure of performance with a misleading event name and not appropriate code markers (should be in different components + AuthScreens is not fully laying out). I advocate for removing this event.
- Starts when [rendering AuthScreens for the first time (in render)](https://github.com/callstack-internal/Expensify-App/blob/7445ef2dc2ea4b038aea070348184189f678f767/src/libs/Navigation/AppNavigator/AuthScreens.tsx#L250) <- not taking unmounts into account, possibly false information
- Ends [in the middle of a useEffect in the same high level component](https://github.com/callstack-internal/Expensify-App/blob/7445ef2dc2ea4b038aea070348184189f678f767/src/libs/Navigation/AppNavigator/AuthScreens.tsx#L309)

---

`switch_report` can be deprecated in favour of specific `open_report*` events that take into account different scenarios and have a more correct naming.

---

`chat_render` does not effectively measure what it's name describes (component fully laying out). I advocate for removing this event and focus on events that better mark full user interactions.
- Starts when [rendering ReportScreen for the first time (in render)](https://github.com/callstack-internal/Expensify-App/blob/7445ef2dc2ea4b038aea070348184189f678f767/src/pages/home/ReportScreen.tsx#L233) <- not taking unmounts into account, possibly false information
- Ends when we [start executing one of the useEffects](https://github.com/callstack-internal/Expensify-App/blob/7445ef2dc2ea4b038aea070348184189f678f767/src/pages/home/ReportScreen.tsx#L469) in the same component, producing false information

---

`sidebar_loaded` does not measure anything meaningful in the performance context. I advocate for removing it (at least from tracking) as it's based on the falsy end event (LHN is not interactive when we hide the splash screen). Additionally, the `sidebar` naming is misleading.
- Starts when [we start the lifecycle of BaseSidebarScreen](https://github.com/callstack-internal/Expensify-App/blob/7445ef2dc2ea4b038aea070348184189f678f767/src/pages/home/sidebar/SidebarScreen/BaseSidebarScreen.tsx#L36) <- not sure if correct
- Ends when [we hide the Splash screen](https://github.com/callstack-internal/Expensify-App/blob/7445ef2dc2ea4b038aea070348184189f678f767/src/Expensify.tsx#L141) <- definitely a wrong place

---

`search_render` is no longer being used. Either docs need to be updated to account for the new `search_router_render`, or naming can be improved to `open_search` to be more descriptive.

---

`report_initial_render` does not measure anything meaningful, we have `open_report*` events for this use case. The start marker it put in the wrong place causing false results. I advocate for removing this event.
- Starts when [we render first LHN items](https://github.com/callstack-internal/Expensify-App/blob/7445ef2dc2ea4b038aea070348184189f678f767/src/libs/actions/App.ts#L182) <- wrong event placement
- Ends when we [finish laying out the report](https://github.com/callstack-internal/Expensify-App/blob/7445ef2dc2ea4b038aea070348184189f678f767/src/pages/home/report/ReportActionsView.tsx#L433)

---

`message_sent` is currently not being sent to Firebase. I advocate for adding a Firebase call for it so we can start tracking how long it takes for people to send messages.

---

`open_report` is currently not being sent to Firebase. Let's add a Firebase call for it so we can start tracking how long it takes for people to fully navigate to chats from LHN.

---

`SEARCH_FILTER_OPTIONS` needs to be updated in docs (Finder is now deprecated

---

`SEARCH_BUILD_TREE`, `SEARCH_MAKE_TREE` and `SEARCH_CONVERT_SEARCH_VALUES` all need to be documented

**Comment by adhorodyski** [comment]
Adam from Callstack, I'd like to work on this issue.

**Comment by adhorodyski** [comment]
@kirillzyusko I noticed we're relying on the `chat_render` event [here](https://github.com/Expensify/App/blob/5f9d44a4c58107928927a9039efdaf93b5a35958/src/libs/E2E/tests/chatOpeningTest.e2e.ts#L49) but it's not being trigger anywhere. Can this be also removed from our E2E suite? I think we can realign this afterwards based on the newly set "correct" events.

**Comment by adhorodyski** [comment]
For now I'll intentionally remove deprecated events in the PR, **breaking E2E in the process so that we have a clear diff for what I have to fix** before we merge anything.

**Comment by adhorodyski** [comment]
Created a draft PR as it's in progress: https://github.com/Expensify/App/pull/51815

**Comment by adhorodyski** [comment]
Updated the PR, now I need to work on bringing e2e tests back to life.

**Comment by kirillzyusko** [comment]
e2e tests are fully back now and works pretty stable 😎

**Comment by adhorodyski** [comment]
@kirillzyusko oh you mean on this branch? 🤞

**Comment by adhorodyski** [comment]
This is opened for a review now.

**Comment by adhorodyski** [comment]
cc @mountiny I created this small PR in the meantime that brings the `sidebar_loaded` event to Firebase/Grafana so we at least know some results for this substantial (for some) period of starting the app.

**Comment by adhorodyski** [comment]
I'm currently reworking the StartupTimer native module to work with multiple traces based on a map (the same way we do it with JS). This will enable a true TTI measurement.

**Comment by mountiny** [comment]
@adhorodyski anything else for this PR?

**Comment by adhorodyski** [comment]
I don't think so, let's close this issue - core workflows are covered.
I'm still wrapping my head around the best way of reporting the TTI for all systems. We don't want to hardcode this for Firebase only, I'll propose something else to be more generic and also enable pushing to Grafana at the same time (collecting between threads is problematic).

**Comment by mountiny** [comment]
Thanks, yes I think that sounds like a good path
