### ISSUE TITLE
Handover to https://new.expensify.com/r/concierge is not seamless

### ISSUE THREAD

**Issue by muttmuure** [Expensify/App#51759]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @muttmuure 
**Slack conversation** (hyperlinked to channel name): https://expensify.slack.com/archives/C07NMDKEFMH/p1730316136748629?thread_ts=1730247644.696569&cid=C07NMDKEFMH

## Action Performed:
Break down in numbered steps

Log into Expensify Classic
Navigate to https://new.expensify.com/r/concierge

## Expected Result:
Describe what you think should've happened

Your chat with Concierge is loaded fully in a short time

## Actual Result:
Describe what actually happened

The chat loads for a long time, and only the latest message is shown

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

None

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @RachCHopkins</details>

**Comment by youssef-lr** [comment]
Auth is merged. I'll have the App PR ready by the time Auth deploys.

**Comment by youssef-lr** [comment]
No payment is needed here, this has been worked on internally.

**Comment by RachCHopkins** [comment]
@Ollyws I see you are paid via NewDot Manual Request, so no offer needed. But @youssef-lr do you know if this has a standard $250 pricetag?

**Comment by youssef-lr** [comment]
This was a pretty simple PR so I think the payout is $125 here.

**Comment by RachCHopkins** [comment]
Payment Summary:

- Contributor+: @Ollyws to be paid $125 via NewDot manual request

No Upwork job

**Comment by garrettmknight** [comment]
$250 approved for @Ollyws
