### ISSUE TITLE
Add upgrade and downgrade #admins messaging

### ISSUE THREAD

**Issue by carlosmiceli** [Expensify/App#51764]
Part of [Add Workspace Plan Downgrades to NewDot](https://github.com/Expensify/Expensify/issues/399936) 

Steps to complete:
- Downgrade #admins messaging ([doc section](https://docs.google.com/document/d/1GDPmbvV47VVxucr-tHYjH80VylcJptP0RfGMVy3zanY/edit?tab=t.0#bookmark=id.w6ts64qntqhe))
- Upgrade #admins messaging and workspace owner whisper ([doc section](https://docs.google.com/document/d/1GDPmbvV47VVxucr-tHYjH80VylcJptP0RfGMVy3zanY/edit?tab=t.0#bookmark=id.4f2n9pqp7m))

**Comment by carlosmiceli** [comment]
@DylanDylann let me know if you'd need more details in the doc to accomplish this, but should be straightforward since most of the work on this is BE.

**Comment by carlosmiceli** [comment]
@DylanDylann all good here? Need help with anything?

**Comment by DylanDylann** [comment]
@carlosmiceli It is straightforward, but I believe that this issue could only be implemented after the BE done

**Comment by carlosmiceli** [comment]
Will be able to come back to the Downgrades project this week hopefully.

**Comment by jliexpensify** [comment]
@carlosmiceli mind adding this to a project? Thanks!

**Comment by carlosmiceli** [comment]
Sure thing!

**Comment by carlosmiceli** [comment]
@DylanDylann just merged final BE PR :)

**Comment by carlosmiceli** [comment]
What's the status here @DylanDylann ?

**Comment by DylanDylann** [comment]
I hold this PR because we need to merge this PR https://github.com/Expensify/App/pull/53343 first, then we can easier to implement this one

**Comment by carlosmiceli** [comment]
@DylanDylann Seems like we can unify this issue with [this](https://github.com/Expensify/App/issues/51515) issue (hookup api), right? And we can close this one?

**Comment by DylanDylann** [comment]
Yes
