### ISSUE TITLE
 Task - Hidden displayed in inbox when task assigned to any other user

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#51765]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.55-8
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** 
**Email or phone of affected tester (no customers):** applausetester+ck31030@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Launch Hybrid app or ND app
2. Go to any 1:1 chat
3. Tap + icon >> Assign task
4. Enter task title
5. Select assignee as any other external user which you have access to
6. Go back to LHN

## Expected Result:
Username to whom the task assigned should be displayed in LHN

## Actual Result:
Hidden displayed in inbox when task assigned to any other user

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Standalone
- [x] Android: HybridApp
- [ ] Android: mWeb Chrome
- [x] iOS: Standalone
- [x] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/3c434e31-0093-4992-8ff4-6495157d2991

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by zanyrenney** [comment]
https://expensify.slack.com/archives/C01SKUP7QR0/p1730157216276209?thread_ts=1729721728.427419&cid=C01SKUP7QR0

As per: 

> we're deprioritizing the task feature and would like for the QA to stop testing task-related issues and creating new GH issues from bugs they find.  Can you easily hide or skip the Task folder in TestRail until further updated? Let me know if you want a GH to make it official

Closing this.
