### ISSUE TITLE
[HOLD for payment 2024-12-07] Create missing upgrade and RHP components 

### ISSUE THREAD

**Issue by carlosmiceli** [Expensify/App#51768]
Part of [Add Workspace Plan Downgrades to NewDot](https://github.com/Expensify/Expensify/issues/399936) 

Doc section: https://docs.google.com/document/d/1GDPmbvV47VVxucr-tHYjH80VylcJptP0RfGMVy3zanY/edit?tab=t.0#bookmark=id.8wdgvm83nqu6

Steps to complete:
- Locked Plan Type RHP for Subscriptions
- Upgrade Confirmation RHP 
- Upgrade Success RHP

<details><summary>Issue Owner</summary>Current Issue Owner: @bfitzexpensify</details>

**Comment by carlosmiceli** [comment]
@jayeshmangwani Thought I'd create an issue that would gather the final FE aspects of the project, maybe split the PRs a bit in a way that makes sense :)

Let me know if there are any questions!

**Comment by carlosmiceli** [comment]
@jayeshmangwani all good here? Need help with anything?

**Comment by jayeshmangwani** [comment]
All good! I'll raise the PR over the weekend. Nothing needed for now, but I'll reach out if anything comes up

**Comment by jayeshmangwani** [comment]
Hey @DylanDylann, are you planning to add the Plan Type row in your PR? If you haven’t started on it yet, I can handle it in this issue. While working on the Upgrade Confirmation and Upgrade Success RHP UI, I went ahead and added the route page for Plan Type. Let me know if you’d like me to include it in my PR!
<img width="948" alt="Screenshot 2024-11-04 at 01 38 56" src="https://github.com/user-attachments/assets/a3445451-6cc8-4403-b19e-fe2926290a47">

**Comment by jayeshmangwani** [comment]
@carlosmiceli Update on this issue: I've created two components:

1. Upgrade Confirmation RHP
2. Upgrade Success RHP (reusing the existing [UpgradeConfirmation](https://github.com/Expensify/App/blob/main/src/pages/workspace/upgrade/UpgradeConfirmation.tsx) component)

The Locked Plan Type RHP is currently in progress.but I’ll wait on merge this issue https://github.com/Expensify/App/issues/51494 first, as it includes the Plan Type page, and they’re very similar.

https://github.com/user-attachments/assets/17e8428c-1b50-4e66-829f-ca9f24d2bbbd


https://github.com/user-attachments/assets/031e29a4-8e1a-45b1-a891-be60e4794a5e

**Comment by DylanDylann** [comment]
@jayeshmangwani Oke, please do it to unblock your PR

**Comment by DylanDylann** [comment]
@jayeshmangwani Any updated here?

**Comment by jayeshmangwani** [comment]
@DylanDylann No updates from my side. Could you raise a PR for this issue?

**Comment by DylanDylann** [comment]
@jayeshmangwani Could you include the upgrade component to [this PR](https://github.com/Expensify/App/pull/52117)?

**Comment by jayeshmangwani** [comment]
Hi @carlosmiceli  @garrettmknight , I have a question regarding the workspace upgrade header title and footer button:

In the doc, the header states `Upgrade your workspace` and the footer button says `Upgrade Workspace`. However, we already have an existing `Upgrade Workspace` page that simply uses `Upgrade` (screenshot attached below).

Should we use the copies from the design document for the header and footer, or stick with the existing page's text and use that same page with the new upgrade component and benefits bullet points added?

<details>
<summary>Existing Upgrade:</summary>
<img width="376" alt="Screenshot 2024-11-15 at 20 30 16" src="https://github.com/user-attachments/assets/8cf22b50-3886-4f80-8720-ef7be7e0e745">

</details>
<details>
<summary>Design doc:</summary>

<img width="235" alt="Screenshot 2024-11-15 at 20 36 02" src="https://github.com/user-attachments/assets/70bb8a62-41ab-4ee5-8c31-8d8c55000624">

</details>

**Comment by carlosmiceli** [comment]
@jayeshmangwani good questions, I think Garrett will give you the best answer :)

**Comment by garrettmknight** [comment]
@jayeshmangwani let's use the existing 'Upgrade' button instead of the 'Upgrade Workspace' proposed in the doc.

**Comment by jayeshmangwani** [comment]
Great, we'll use the existing Upgrade, Thanks!

**Comment by carlosmiceli** [comment]
Final BE PR has been merged :)

**Comment by bfitzexpensify** [comment]
@jayeshmangwani can you please propose regression steps here and the I'll post the payment summary?

**Comment by jayeshmangwani** [comment]
@bfitzexpensify I’m not sure if this issue is ready for payment, as it’s part of the ongoing "Workspace Plan Downgrade" project. The [PR](https://github.com/Expensify/App/pull/53343) is still in progress, and additional PRs will also be part of this project.

**Comment by bfitzexpensify** [comment]
Gotcha. @carlosmiceli, how are we handling payment for this project?

**Comment by carlosmiceli** [comment]
Mmm, I'm not sure, we'll have to ask @garrettmknight 😅

**Comment by garrettmknight** [comment]
@jayeshmangwani once we launch the project we can comb through different issues and PRs and pay out all at once to keep things simple.
