### ISSUE TITLE
Collect Approvers - The employee can't change an empty report type to invoice

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#51772]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.55
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/runs/view/26765&group_by=cases:section_id&group_order=asc&group_id=296773
**Issue reported by:** Applause - Internal Team

## Action Performed:
Setup - OldDot
1.Create a new Gmail account in OldDot (must be new)
2.Create a collect workspace
3.Set the workspace policy to USD
4.Open the JS console and run the following script in the collect policy settings page
if (Url.getCurrentPageName()!="policy" ){ alert('Only run this snippet from a policy editor!'); } else { var p = Policy.getCurrent(); p.policy.isPolicyExpenseChatEnabled = "true"; p.save().done(function(){$.jGrowl('Workspace chat creation enabled!')}); }
Stay logged in with the workspace admin (owner) in OldDot.

Steps
OldDot setup - Can be done in browser for easy access
2.Invite another account and set it as admin - This account will be called Admin2 in the following TCs
3.Invite another account and set it as employee - This account will be called Employee1 in the following TCs
4.Invite another account and set it as admin - This account will be called Admin Approver in the following TCs
5.Under approval mode - Set admin Approver as the "Submit and Approve" approver

Login to OldDot with the employee account
1.Navigate to workspaces and set the collect policy to default if not already set
2.Navigate to reports
3.Create at least 3 reports with no expenses on them
4.Navigate to one of the empty reports and change the report type to "Invoice"

## Expected Result:
The employee can change the empty report to an invoice in OD

## Actual Result:
The employee can't change the empty report to an invoice in OD. Only the workspace owner can change the report type to an invoice if it has expenses

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/cb971328-93a8-4e2b-afa2-3c5594124a65

<img width="1440" alt="25_AM" src="https://github.com/user-attachments/assets/039191be-37ee-4fce-b76f-cff9b199095d">

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@VictoriaExpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by VictoriaExpensify** [comment]
Hmm since this is an OD bug, I don't think we'll be prioritising a fix for this. If an issue is reported by customers, we may look into it. For now, I'm closing
