### ISSUE TITLE
Hide Search filters for features that aren't enabled (and can't be searched)

### ISSUE THREAD

**Issue by JmillsExpensify** [Expensify/App#51771]
**Problem**: While we only show the card filter if a member has cards actually assigned to them, we don't do the same for category, tags, and tax. This inconsistency overcomplicates the product and leads to a confusing search experience, since we're allowing members to search for things that can't be searched.

**Solution**: Let's only show filters if members actually have those features enabled on the workspace. Again, we already do this for `Card`, so simply make things consistent and do the same for `Category`, `Tag` and `Tax rate`.   

![CleanShot 2024-10-30 at 15 08 28@2x](https://github.com/user-attachments/assets/8189e8af-b1fe-488e-9bd9-af952111d25d)

**Comment by luacmartins** [comment]
@Kicu @SzymczakJ @289Adam289 would either of you wanna work on this issue?

**Comment by Shahidullah-Muffakir** [comment]
It looks like this issue is the same as [Issue #50564](https://github.com/Expensify/App/issues/50564). @luacmartins suggested those changes in [this comment](https://github.com/Expensify/App/issues/50564#issuecomment-2407994747). I've also shared : [My Proposal](https://github.com/Expensify/App/issues/50564#issuecomment-2406319975). Now waiting for @fedirjh to choose the best solution.

**Comment by JmillsExpensify** [comment]
Oh ok. So @luacmartins should we go ahead and close this one out?

**Comment by Kicu** [comment]
I read parts of the discussion on the other issue and they seem long and overly complex.

This is how we don't display Card advanced filter: https://github.com/Expensify/App/blob/ab40264dff9a6c21372617c8744b1013c22dd2d2/src/pages/Search/AdvancedSearchFilters.tsx#L318

There is a function that iterates over static filters array and computes the display data. We can run a simple `if` check to see whether we want this filter or not.
Feels to me (without digging too deep into this) that we could apply quite similar logic to all the other filters that you mentioned @JmillsExpensify

I don't want to randomly barge in into the conversation on the other issue, but I'm sure one of us in SWM could take this and provide some not-too-complex solution. This specific filters code was something that @289Adam289 worked on.

**Comment by luacmartins** [comment]
@Kicu I agree. I commented on the [issue](https://github.com/Expensify/App/issues/50564#issuecomment-2452204971). I'm gonna close this one in favor of https://github.com/Expensify/App/issues/50564. Can you please leave a comment so I can assign it to you?

**Comment by luacmartins** [comment]
Closing since @Kicu is assigned to https://github.com/Expensify/App/issues/50564
