### ISSUE TITLE
Submitting a expense to reports@expensify.com shows an error message

### ISSUE THREAD

**Issue by isagoico** [Expensify/App#51773]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Issue reported by:** @quinthar 
**Slack conversation** (hyperlinked to channel name): [#expensify-bugs](https://expensify.slack.com/archives/C049HHMV9SM/p1730326430459449)

## Action Performed:
1. Submit a expense to reports@expensify.com

## Expected Result:
IG: Not completely sure about the expected result for this one, I think we either: 
- Block the user from being able to submit expenses to report@expensify.com
- Show a friendlier message on why the expense was not created

## Actual Result:
An error message is displayed and the expense is not created after dismissing the error. 

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [x] iOS: Standalone
- [x] iOS: HybridApp
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

![image](https://github.com/user-attachments/assets/10df5f84-e383-4ad2-b06e-7e11f18ab068)

https://github.com/user-attachments/assets/756c4bc7-112b-4dcf-9cbf-cc5d9aaff5e5

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by FitseTLT** [comment]
This is not a bug if it can't create a report with it, it will return an error. Same behavior for similar contacts; you can try it with `test@expensify.com`, for instance.
