### ISSUE TITLE
 Workspace - Item (member, category, tag etc) in focus has two shades when selected by keyboard

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#51788]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.56-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+kh2310001@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace settings > Members
3. Invite a member
4. Navigate the member list via keyboard

## Expected Result:
The member in focus will have one shade

## Actual Result:
The member in focus has two shades when selected by keyboard
The same highlight issue also happens in Categories, Tags, Distance Rates, and Taxes page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/f95043a5-99bb-448e-ab62-bb36ddb372ee

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by jjcoffee** [comment]
@nkdengineer Are you able to take a look?

**Comment by nkdengineer** [comment]
@jjcoffee I think we can revert the PR anh I will create another tomorrow.

**Comment by flodnv** [comment]
Looks like you're handling this @mjasikowski, so I'm assigning you, thanks!

**Comment by Beamanator** [comment]
Reverted in https://github.com/Expensify/App/pull/51795 & that was checked off by applause, so seems to be fixed!

**Comment by mjasikowski** [comment]
Fix was submitted in https://github.com/Expensify/App/pull/51937
