### ISSUE TITLE
[$250] Don't auto-pin the selfDM. 

### ISSUE THREAD

**Issue by JmillsExpensify** [Expensify/App#51781]
Background: The selfDM was created as a place to store expenses that a member isn't quite ready to share with someone else, or that they are purely tracking for personal use. Recently we updated the selfDM so that it's marked as read on when a user signs up. 

Problem: In viewing FullStory sessions, we've commonly seen that employees mistake selfDM as a place to share expenses directly with their employer, leading to confusion and creating extra steps they must navigate to ultimately submit their expenses. 

Solution: To resolve confusion and ultimately focus members on our most important use case, **let's stop auto-pinning the selfDM** in a member's LHN. Instead, let's exclusively pin the workspace chat, whenever one exists. 
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021851947919649807243</li>
        <li>Upwork Job ID: 1851947919649807243</li>
        <li>Last Price Increase: 2024-10-31</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @marcaaron</details>

**Comment by FitseTLT** [comment]
This is a BE issue.

**Comment by marcaaron** [comment]
I'll take a look at this one today.

**Comment by marcaaron** [comment]
>let's stop auto-pinning the selfDM in a member's LHN. Instead, let's exclusively pin the workspace chat, whenever one exists

To clarify, we want something like this:

- If user has a non-personal policy / workspace then do not auto-pin the self DM and pin the workspace chat
- Otherwise, continue to auto-pin the self DM

?

**Comment by marcaaron** [comment]
First PR for this is merged and deployed. It will be a two parter.
