### ISSUE TITLE
Web - Search - Group expense box is not highlighted evenly when selected by keyboard

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#51784]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.56-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** applausetester+kh2310001@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Submit two expenses to any user
3. Go to Search
4. Go to Outstanding
5. Navigate to the group expenses in Step 2 using keyboard
6. Click on the empty area to remove the blue border

## Expected Result:
The group expense box will be highlighted evenly

## Actual Result:
The top and bottom of the group expense box have different shade than the middle of the box

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

<img width="1440" alt="99!highlight" src="https://github.com/user-attachments/assets/f76807f9-8783-43ec-a285-b95814c530d8">

https://github.com/user-attachments/assets/b1075f94-6178-4c98-8e77-2f6d226a75ca

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by jjcoffee** [comment]
@nkdengineer Can you take a look?

**Comment by iwiznia** [comment]
I don't think this is a blocker, but it seems the change created a bunch of other issues and is being reverted already.

**Comment by Beamanator** [comment]
Reverted in https://github.com/Expensify/App/pull/51795 & that was checked off by applause, so seems to be fixed!

**Comment by mjasikowski** [comment]
Fix was submitted in https://github.com/Expensify/App/pull/51937

**Comment by iwiznia** [comment]
The PR above was deployed
