### ISSUE TITLE
[HOLD for payment 2024-11-13] [HOLD for payment 2024-11-11] Room – Unable to save room description with numbers only

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#51789]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.56-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+jp_11311024@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log
3. Create a workspace
4. Create a room without description
5. Open room chat
6. Click on header, open description
7. Enter few numbers into description and save

## Expected Result:
Description is saved

## Actual Result:
Description is empty

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/9a6cf043-6c88-4b89-a187-2c8d6b505534

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by lanitochka17** [comment]
Production:

https://github.com/user-attachments/assets/a711e12c-4fac-4ebe-b514-3f62c6e459b5

**Comment by MuaazArshad** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Unable to save room description with numbers only.
### What is the root cause of that problem?
We are passing only strings for the room description; if we receive a number, it cannot be processed as a string.
here
https://github.com/Expensify/App/blob/6c33bba59c3305d59c96b265183473bc7ffed2e0/src/libs/ReportUtils.ts#L4265-L4271
### What changes do you think we should make in order to solve the problem?

We should cast numbers to string before processing like this
```
try {
        const reportDescription = report?.description;
        const objectDescription = JSON.parse(reportDescription) as {html: string};
        const newObjectDescription = {html:String(objectDescription)};
        return newObjectDescription.html ?? '';
    } catch (error) {
        return report?.description ?? '';
    }
```

### What alternative solutions did you explore? (Optional)

**Comment by Christinadobrzyn** [comment]
@Gonals I can reproduce this, can this go external?

**Comment by Beamanator** [comment]
@NJ-2020 -thanks for finding what looks like the regression, i pinged the PR authors in slack 🙏

**Comment by truph01** [comment]
Working on it ...

**Comment by truph01** [comment]
@abdulrahuman5196 [PR](https://github.com/Expensify/App/pull/51943) is ready

**Comment by Beamanator** [comment]
PR looks great, I'll merge & CP very soon 👍

**Comment by Beamanator** [comment]
Note to @Christinadobrzyn : It looks like we're using @NJ-2020 's solution from [here](https://github.com/Expensify/App/issues/51789#issuecomment-2449917122), so I believe they deserve some compensation even though they didn't complete the PR

**Comment by Beamanator** [comment]
PR is being CP'd

**Comment by abdulrahuman5196** [comment]
Unassigning myself since i didn't work on this PR.

**Comment by Christinadobrzyn** [comment]
Payouts due:

- [ ] Contributor: $250 @truph01 (Upwork offer - https://www.upwork.com/nx/wm/offer/104890091)
- [ ] Contributor: 25% partial payment based on [this](https://github.com/Expensify/App/issues/51789#issuecomment-2454235805) $62.50 @NJ-2020 - can you send me your Upwork profile so I can send you an offer? 

Do we need a regression for this?

**Comment by truph01** [comment]
@Christinadobrzyn I create a follow-up PR, so no payment is needed for me

**Comment by Christinadobrzyn** [comment]
Thanks @NJ-2020! Can you please accept the Upwork [offer](https://www.upwork.com/nx/wm/offer/104893577) so I can pay you? Thanks!

**Comment by Christinadobrzyn** [comment]
Awesome! Thanks @NJ-2020 - I sent the payment through Upwork. 

It does seem like a regression test would be good for this and since there was no C+ review, I'm discussing the best options to create one with QA. https://expensify.slack.com/archives/C9YU7BX5M/p1731570034074179

**Comment by Christinadobrzyn** [comment]
[Sounds like QA](https://expensify.slack.com/archives/C9YU7BX5M/p1731592834679419?thread_ts=1731570034.074179&cid=C9YU7BX5M) already has a test for this and they are going to treat this as an edge case so no need to create a regression test. So we're good to close!
