### ISSUE TITLE
[HOLD for payment 2024-11-13] Setup Firebase Web for HybridApp

### ISSUE THREAD

**Issue by rinej** [Expensify/App#51787]
Currently we are collecting the performance traces from the web to the newDot firebase dashboard([dashboard](https://console.firebase.google.com/u/0/project/expensify-chat/overview))
We want to change it to collect traces to oldDot firebase dashboard ([dashboard](https://console.firebase.google.com/u/0/project/expensify-mobile-app/overview))

Discussion:
https://callstack-hq.slack.com/archives/C05LX9D6E07/p1729858514881169?thread_ts=1728892308.074619&cid=C05LX9D6E07

<details><summary>Issue Owner</summary>Current Issue Owner: @muttmuure</details>

**Comment by dannymcclain** [comment]
Feels like I probably don't need to be here? LMK!

**Comment by mountiny** [comment]
PR merged! yeah no design changes required here

**Comment by mountiny** [comment]
No need for checklist for this one, updating the firebase setup, no payments either
