### ISSUE TITLE
Room - Sending reply in thread message for specific room system message error is shown

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#51796]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.56-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/home
2. Open a room chat
3. Tap header -- description
4. Enter ~🙂🙂🙂~ and save
5. Tap share - copy url
6. Navigate to description and paste the url below the description which is entered previously and save it
7. Navigate to conversation
8. Long press the system message and open reply in thread
9. Send a message

## Expected Result:
Sending reply in thread message for specific room system message error must not be shown

## Actual Result:
Sending reply in thread message for specific room system message error is shown

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/556ae969-9586-4373-b8fe-eda6e18d3183

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@MitchExpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by MitchExpensify** [comment]
This is not a core flow, closing
