### ISSUE TITLE
Bank account - Almost done screen shown briefly when coming from choose an account page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#51799]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.56-0
**Reproducible in staging?:** Y
**Reproducible in production?:**Unable to check
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** nathanmulugetatesting+1985@gmail.com
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/49536
## Action Performed:
1. Navigate to staging.new.expensify.com
2. Create a workspace and enable expensify card
3. Go to Expensify Card and click on issue card
4. Add a bank account via plaid
5. On choose account page choose saving and click next but watch closely before the next page appears

## Expected Result:
Almost done screen does not get shown in between "Choose an account" page and "Personal Info" page

## Actual Result:
Almost done screen get shown briefly in between "Choose an account" page and "Personal Info" page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/57373860-299c-41b5-97c3-3e2e75d217f0

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021852305752972180049</li>
        <li>Upwork Job ID: 1852305752972180049</li>
        <li>Last Price Increase: 2024-11-01</li>
<li>Automatic offers: </li>
<ul>
<li>DylanDylann | Contributor | 104984187</li>
</ul></li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave-collect - Release 2

**Comment by grgia** [comment]
Demoted. Reached out to @koko57 in the slack thread

**Comment by D-01576** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Bank account - Almost done screen shown briefly when coming from choose an account page

### What is the root cause of that problem?
`ConfirmationStep` component inadvertently includes the "Almost done" screen in its path before reaching the intended "Personal Info" page.

### What changes do you think we should make in order to solve the problem?
To resolve this, modify the navigation path within the `ConfirmationStep` component to skip the "Almost done" screen and navigate directly to the "Personal Info" page. 

In the `ConfirmationStep` component, change ([line 52](https://github.com/Expensify/App/blob/main/src/pages/workspace/expensifyCard/issueNew/ConfirmationStep.tsx#L52)):
```typescript
    useEffect(() => {
        if (!isSuccessful) {
            return;
        }
        Navigation.navigate(backTo ?? ROUTES.WORKSPACE_EXPENSIFY_CARD.getRoute(policyID ?? '-1'));
        Card.clearIssueNewCardFlow();
    }, [backTo, policyID, isSuccessful]);
```
to :

```typescript
Navigation.navigate(ROUTES.WORKSPACE_PERSONAL_INFO.getRoute(policyID ?? '-1'));
```

### What alternative solutions did you explore? (Optional)

**Comment by koko57** [comment]
@grgia I can work on this one 🙂

**Comment by koko57** [comment]
I will be working on this issue and the one that has the same root cause https://github.com/Expensify/App/issues/50422, but first I need to finish some Workspace Feed issues

**Comment by koko57** [comment]
I'm finishing my Workspace Feed tasks - I will focus on this issue from Monday.

**Comment by mountiny** [comment]
@grgia if you want, happy to take over, I have worked with @koko57 on these flows for last couple of weeks. but do not want to force-takeover 😄 so up to you

**Comment by grgia** [comment]
all yours @mountiny (now you owe me one fun issue in the future)

**Comment by koko57** [comment]
Mostly finished WFeed issues, now I'm able to fully focus on this one.

**Comment by koko57** [comment]
@mountiny today I will help with the new Workspace Feed bugs, they are higher priority? Maybe we can move this one to weekly?

**Comment by DylanDylann** [comment]
Note for the PR phase, we need to recheck these issues again:
- https://github.com/Expensify/App/issues/50422
- https://github.com/Expensify/App/issues/51479

**Comment by DylanDylann** [comment]
@eVoloshchak Could I take over this issue? Because this is a deploy blocker from the previous issue that I worked with @koko57

**Comment by koko57** [comment]
Still working on it. I've already removed some unnecessary code, for now it looks fine, looking for some edge cases.

**Comment by koko57** [comment]
EDIT: I need to rethink my solution. This component has too much complexity, I will try to simplify it a bit but I can't go with the solution I thought of first

**Comment by DylanDylann** [comment]
Feel free to post a proposal first, then we can discuss it thoroughly together

**Comment by koko57** [comment]
I tested some other ideas, I really wanted to simplify this logic, but TBH it's really hard.
I tried to reproduce the issue once again on staging but I cannot get the exact behavior consistently. 

https://github.com/user-attachments/assets/5f8d3ca7-9b16-4276-a2b0-ca5e05c2c2b6

So in my opinion, it doesn't make sense to burn more time on this - but let's retest it first. The only issue I've found - is that when we have the supported currency for the nonUSDBankAccountStep for the workflows we display the non-USD flow and for the Expensify Card we get the modal to change the currency - is it expected?

cc @mountiny

**Comment by mountiny** [comment]
> is that when we have the supported currency for the nonUSDBankAccountStep for the workflows we display the non-USD flow and for the Expensify Card we get the modal to change the currency - is it expected?

For Expensify Card, you need to have USD settlement bank account so I think yes

**Comment by izarutskaya** [comment]
Issue not reproducible anymore 

https://github.com/user-attachments/assets/fd280f3a-1708-4ede-9949-bf508979102b

**Comment by mountiny** [comment]
Thanks! Lets close then and hopefully we dont have to handle this one again
