### ISSUE TITLE
GBR - No GBR on settings avatar, profile and contact method

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#51792]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.56-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:**N/A
**Email or phone of affected tester (no customers):** nathanmulugetatesting+1981@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Sign up with a new Gmail account
3. Observe settings avatar, profile and contact method

## Expected Result:
A GBR is present

## Actual Result:
No GBR is visible

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/5fc3fbf7-d325-4624-b015-e028da76ba04

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by stitesExpensify** [comment]
Agreed @JmillsExpensify @techievivek can we just close this?

**Comment by Beamanator** [comment]
Calling this NAB b/c yes this looks expected

**Comment by techievivek** [comment]
Yes, this is expected. @lanitochka17 can we please get that tests updated? We no longer need to show GBR on initial signup.
