### ISSUE TITLE
[HOLD 49931] Expensify Card - Empty state screen not visible and issue card button and settings shown

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#51801]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.56-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+nl745@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/49536
## Action Performed:
1. Navigate to staging.new.expensify.com
2. Create a workspace and enable Expensify Card
3. Click on Issue card and add a bank account
4. Click on the bank account and wait for it to be verified
5. Go to another workspace and go through the same steps from 1-4

## Expected Result:
While the verification is ongoing an empty state screen should be shown on step 4 and on step 5 the issue card button and settings should not be visible

## Actual Result:
While the verification is ongoing an empty state screen is not shown on step 4 and on step 5 the issue card button and settings are visible

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/cee1c2c6-e422-408f-b4dc-3f5d8c167bd5

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @bfitzexpensify</details>

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave-collect - Release 2

**Comment by DylanDylann** [comment]
This will be fixed after https://github.com/Expensify/App/pull/51712 is merged

**Comment by neil-marcellini** [comment]
Thanks for pointing that out @DylanDylann! Sounds like this is a general issue across the whole app due to the way that Network requests are processed. Therefore I'll remove the blocker label and put this issue on HOLD for that one.

**Comment by aldo-expensify** [comment]
I'm making the backend PR ready for review: https://github.com/Expensify/Auth/pull/13168

**Comment by bfitzexpensify** [comment]
Cool, we'll be able to circle around to this soon then

**Comment by DylanDylann** [comment]
@bfitzexpensify  This bug has already been fixed

https://github.com/user-attachments/assets/fd7c8cc7-fea2-4d95-93a1-4482cf47c542

**Comment by bfitzexpensify** [comment]
Nice, let's close this out.
