### ISSUE TITLE
[HOLD for payment 2024-11-21] Re-direct to Classic when creating expenses for non-migrated users

### ISSUE THREAD

**Issue by puneetlath** [Expensify/App#51804]
There are scenarios where users who have not yet had their group workspaces NewDot-enabled in NewDot. In those scenarios, things can get confusing if they try to create expenses. 

To address this, let's block them from Creating, Tracking, Submitting expenses from NewDot if they are: 
- on at least one group policy 
- none of the group policies they are a member of have isPolicyExpenseChatEnabled=true

We should do this by showing a modal when they tap/click any of these options, which re-directs them back to OldDot. 

<img width="383" alt="Screenshot 2024-10-31 at 11 34 11 AM" src="https://github.com/user-attachments/assets/795f3ad8-9f47-4d70-9dc6-c12b0b4a29e7">

<details><summary>Issue Owner</summary>Current Issue Owner: @puneetlath</details>

**Comment by puneetlath** [comment]
@dubielzyk-expensify can you help with some mocks of what that re-direct to Classic modal should look like?

**Comment by dubielzyk-expensify** [comment]
Yes sir. Think we need some @jamesdeanexpensify magic to make the copy more crisp (he's back on Monday I believe).

## Mocks
![image](https://github.com/user-attachments/assets/c5d2d6f9-5976-4ed7-a156-012189912f76)
![image](https://github.com/user-attachments/assets/d406b2fc-7916-4641-95c8-c31740aaf62a)

**Comment by flaviadefaria** [comment]
Based on the latest discussions, I think this bow belongs to #retain, so I am assigning it there.

**Comment by jamesdeanexpensify** [comment]
@puneetlath @dubielzyk-expensify too much?

> ** 🚧 Under construction 🚧 **
> This part of New Expensify is still under construction. In the meantime, we've got just what you need over in Expensify Classic.

**Comment by dubielzyk-expensify** [comment]
It's quite cute. But this feature is still available right, but it's just because the workspace has a complicated setup that we don't allow it? So maybe it feels a bit underselling?

**Comment by jamesdeanexpensify** [comment]
Updated it slightly. Anything else specific you wanna tweak? Happy to brainstorm.

**Comment by dubielzyk-expensify** [comment]
I like it. Keen to hear what @puneetlath thinks though

**Comment by puneetlath** [comment]
Sounds great to me! FYI @ishpaul777

**Comment by dannymcclain** [comment]
P.S. @jamesdeanexpensify I am surprised to see emoji being used in the copy. IS THAT FAIR GAME NOW?!

_{ Rewrites all copy everywhere to use gratuitous amounts of emoji }_ 😁 😂

**Comment by jamesdeanexpensify** [comment]
It felt like it fit this one! haha

**Comment by dubielzyk-expensify** [comment]
Danny's got it right. I actually think we shouldn't have the emojis. Keen to hear what @Expensify/design thinks. Feels like it cheapens things to me. I should've mentioned this initially. If people disagree, we can move on though.

**Comment by jamesdeanexpensify** [comment]
I'm fine removing the emojis. I don't think we've done that much elsewhere anyways. I don't know what got into me! haha

**Comment by dubielzyk-expensify** [comment]
Hahah. Sometimes we need to push the boundaries to see what we really feel. Do the headline still work without it?

**Comment by jamesdeanexpensify** [comment]
Maybe something like "Almost there!" ?

**Comment by dubielzyk-expensify** [comment]
Hmm. What about "Not ready yet" or something. Almost there sounds like a last step before you finish something or that the user has control.

**Comment by jamesdeanexpensify** [comment]
True! But I don't like the negative connotation of starting with "Not". I considered it. Maybe "Work in progress..." or something like that?

**Comment by dubielzyk-expensify** [comment]
I like it

**Comment by shawnborton** [comment]
Hahah came here to say the same thing... I think I also prefer the non-emoji version, they kind of compete with our illustration system a bit. If we want to add some construction pizazz, we could always use something from our library but I like keeping it simple for this one.

**Comment by puneetlath** [comment]
I like "Work in progress" or "Coming soon".

**Comment by jamesdeanexpensify** [comment]
Oh I'm down with "Coming soon"!

**Comment by dubielzyk-expensify** [comment]
Sounds good to me. Alright we're ready to proceed with the rest of the implementation @ishpaul777

**Comment by MariaHCD** [comment]
Looks like we have another flow in-product where we need to redirect to Classic: https://github.com/Expensify/App/issues/52457

Would @ishpaul777 want to take that over as well? Or shall we treat it as a separate follow up?

**Comment by puneetlath** [comment]
@suneox can you complete the checklist here?

**Comment by puneetlath** [comment]
@ishpaul777 offer here: https://www.upwork.com/nx/wm/offer/105064871
@suneox offer here: https://www.upwork.com/nx/wm/offer/105064898

Can y'all ping me here when you've accepted? 

Regression test GH: https://github.com/Expensify/Expensify/issues/447666

**Comment by puneetlath** [comment]
@ishpaul777 has been paid.

**Comment by suneox** [comment]
I've accepted the offer. Thank you

**Comment by puneetlath** [comment]
Everyone has been paid now. Thanks everyone!
