### ISSUE TITLE
mWeb - BA - On tapping "next" in manually enter bank account page, user directed to continue setup

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#51823]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.56-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/home
2. Tap profile icon -- workspaces-- workspace
3. Tap more features - enable workflow
4. Tap workflow in workspace settings
5. Tap connect bank account
6. Complete the flow using region bank - selecting account ending 1111
7. Note user directed to continue set up page instead of "manually add bank account page"
8. Navigate to settings and tap connect bank - continue set up
9. On tapping next on manually enter bank account page, user directed to continue set up page again
10. When we revisit the page by tapping next, user directed to personal information page

## Expected Result:
On tapping "next" in manually enter bank account page, user must not be directed to continue set up page

## Actual Result:
On tapping "next" in manually enter bank account page, user directed to continue set up page again instead personal information page.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/7e4c3ae1-ba4c-45ab-8a6a-287c285d95f0

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
Production:

https://github.com/user-attachments/assets/ddf69774-1784-405c-b86a-10961e68b03a

**Comment by dangrous** [comment]
Traced it to https://github.com/Expensify/App/pull/51315 - looking to see if we can maybe fix without reverting

**Comment by dangrous** [comment]
it's specifically [this useEffect](https://github.com/Expensify/App/pull/51315/files#diff-1f7e5f0ea4429c43c2e243a5d1c069e9959e4032c661fdca7af20113b1c6e8bcR208-R211) - I'm not sure what that was added for so I hesitate just to remove

**Comment by dangrous** [comment]
So it's not the blink, i think the description could be clearer.

Basically, when you are on the "Manually add your bank account" pane (usually gotten to by clicking "continue setup" or by clicking "back" from the Personal info pane), when you click next you should be brought to the Personal info pane, NOT the Continue Setup pane. This is the behavior that's wrong here.

**Comment by dangrous** [comment]
It might also be a bug that existed before but was unearthed by this PR - the `personal-information` pane doesn't actually exist in the [list of steps](https://github.com/Expensify/App/blob/4bf4988e5e9dbb9d10a8194143364858d1b1f70d/src/pages/ReimbursementAccount/ReimbursementAccountPage.tsx#L70-L89), so I think the logic doesn't know where to go from the new page...

**Comment by DylanDylann** [comment]
I am checking

**Comment by mountiny** [comment]
The offending Pr is reverted, we can close now and make sure its addressed with the PR going again
