### ISSUE TITLE
Group Conversation - Couldn't trigger Error when invalid name used for the title

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#51837]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.56-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5173586
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Navigate to http://www.staging.new.expensify.com/
2. Create a group
3. Go to force offline mode
4. Try to edit group name with an invalid name (example: adoadoadoajdoajdoadoajdoajadoadoadoajdoajdoadoajdoajadoadoadoajdoajdoadoajdoajadoadoadoajdoajdoadoaỏ)

## Expected Result:
The group name saved and become grayed out in the Settings to get error message for the invalid name

## Actual Result:
Couldn't triggered Error when invalid name used for the title due to "Exceeds the maximum length of 100 characters" error displayed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/34629a5f-4664-4020-82f3-59d08eff9041

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@RachCHopkins  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by FitseTLT** [comment]
This is not a bug.

**Comment by RachCHopkins** [comment]
I agree, this is not a bug as stated here. @lanitochka17 the QA tester is welcome to restate the issue in a way that points out what the problem is, but this problem statement and video don't appear to show any bugs.
