### ISSUE TITLE
iOS - Use "rich" notifications with avatar and room for new experience HybridApp users

### ISSUE THREAD

**Issue by JmillsExpensify** [Expensify/App#51846]
For iOS users with tryNewDot enabled and that use HybridApp, we're not delivering "rich" notifications that include the user's avatar and a clarification of what room the conversation is happening in. Here's two examples, one is a DM and another convo is a "test" discussion happening in a room/workspace chat. 

![IMG_A1EC932509E8-1](https://github.com/user-attachments/assets/6df28ffd-f3de-4021-8356-a7e16e75e697)

In contract, whenever:

 - A user is on HybridApp
 - And has tryNewDot enabled

Then we should be sending notifications that look like this. 
![IMG_7285](https://github.com/user-attachments/assets/7047396f-4c2e-4652-91d8-80ed019d6b11)

**Comment by Julesssss** [comment]
This will be a good task for our SWM team.

**Comment by arosiclair** [comment]
We implemented this for NewDot iOS in #32765 and Android in #37604 so we just need to port over those changes to the HybridApp. It sounds like that might have already been done for Android.

**Comment by Julesssss** [comment]
Yeah this is working for Android, I'll update the description 👍

**Comment by Julesssss** [comment]
iOS notifications are tough to test. Our best bet would be to ask an engineer who has already worked on HybridApp notifications, but the initial SWM HybridApp guys are all working on much more critical tasks at the moment.

**Comment by Julesssss** [comment]
We need an internal engineer for this. 

I am working on a P/S for making noticiation DevX easier -- I think it makes sense to hold this issue until the tooling is better and use it as motivation for that project.

**Comment by Julesssss** [comment]
Reducing priority as I don't think this needs a daily update. But DevX improvements for notifications are incoming, and I think align quite closely with #quality -- more details to follow shortly!

**Comment by arosiclair** [comment]
Starting some work on this today. For iOS we're going to need to

1. Enable `mutable_content` flag for HybridApp push notifications like we did for NewDot [here](https://github.com/Expensify/Web-Expensify/pull/40158)
2. Follow the [Airship guide](https://docs.airship.com/platform/mobile/setup/sdk/ios/?groupid=ios-swift#notification-service-extension) for adding the NSE to our Xcode project
    - The bundle ID will be `com.expensify.expensifylite.NotificationServiceExtension`
4. Copy over the NewDot implementation we have for it [here](https://github.com/Expensify/App/blob/52a039f96c7ea0e1031df29b919395bc94ef59f5/ios/NotificationServiceExtension/NotificationService.swift)
5. Register the new bundleID and enable comms notification capability in the Apple developer console like we did [here](https://github.com/Expensify/Expensify/issues/350975)

**Comment by arosiclair** [comment]
I made another issue to make Apple developer console changes for this [here](https://github.com/Expensify/Expensify/issues/446301). Gonna need a deployer to make the changes.

**Comment by arosiclair** [comment]
This is nearly done just need to do final tests and I'll post [the PR](https://github.com/Expensify/Mobile-Expensify/pull/13293) for review.

**Comment by arosiclair** [comment]
Out for review!

**Comment by arosiclair** [comment]
This is all done!
