### ISSUE TITLE
[HOLD App#52252] [$250] [Workspace Feeds] Company Cards - Unable to remove card feed that's under review

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#51858]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.56-2
**Reproducible in staging?:** Y
**Reproducible in production?:** No, unable to check
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/51569
## Action Performed:
1. Open the app
2. Log in with a new expensifail account
3. Create a workspace
4. Navigate to Workspace settings - More features
5. Enable "Company cards"
6. Navigate to Workspace settings - Company cards
7. Navigate to Add company cards - American Express - American Express Corporate Cards - Next
8. Input any name and tap on the "Next" button
9. Tap on the "Submit" button
10. Tap on the "Settings" button
11. Tap on the "Remove card feed" button
12. Tap on the "Delete" button

## Expected Result:
I should be able to delete the feed

## Actual Result:
Unable to remove card feed that's under review. "Import company cards" page can be seen briefly but the "review" page loads again

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [x] iOS: Standalone
- [x] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/35c3a695-b946-40a1-9565-b7be9e43a166

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021852426699884185074</li>
        <li>Upwork Job ID: 1852426699884185074</li>
        <li>Last Price Increase: 2024-11-01</li>
<li>Automatic offers: </li>
<ul>
<li>allgandalf | Contributor | 104730679</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @mountiny</details>

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave-collect - Release 2

**Comment by marcochavezf** [comment]
This is happening in production, so not a blocker

https://github.com/user-attachments/assets/b4df5312-ce91-40a2-99d3-2c3f5694ae7a

**Comment by mountiny** [comment]
@marcochavezf happy to take this one over as I have been working on the workspace feeds feature

**Comment by mountiny** [comment]
I think we can go with the contributors here

**Comment by mountiny** [comment]
Working on this one in a similar issue. https://github.com/Expensify/App/issues/52252

**Comment by mountiny** [comment]
PR is up https://github.com/Expensify/Auth/pull/13111

**Comment by mountiny** [comment]
There is a follow up merged so we can test again shortly

**Comment by mountiny** [comment]
I believe @joekaufmanexpensify tested removing the pending card so this worked well
