### ISSUE TITLE
[HOLD for payment 2024-12-07] [LHN Mismatch] Add SetCollection to Onyx

### ISSUE THREAD

**Issue by puneetlath** [Expensify/App#51864]
We are going to be changing the behavior of OpenApp/ReconnectApp when it does a full reconnect to replace the full reports list that the client has stored instead of merging with it. In order to do that, we need to be able to send a list of report objects to the client and have Onyx.set be called for each of those reports. And have any reports that weren't included get cleared. In order to support this, let's add `SetCollection` to Onyx. 

<details><summary>Issue Owner</summary>Current Issue Owner: @puneetlath</details>

**Comment by zirgulis** [comment]
I am Povilas Zirgulis from Callstack - expert contributor group. I’d like to work on this job

**Comment by zirgulis** [comment]
@puneetlath should the API for `setCollection` be something like this?
```
Onyx.setCollection(ONYXKEYS.COLLECTION.REPORT, [
     { [`${ONYXKEYS.COLLECTION.REPORT}1`]: report1 },
     { [`${ONYXKEYS.COLLECTION.REPORT}2`]: report2 }
 ]);
```

**Comment by puneetlath** [comment]
I think the API for it should look basically exactly like `mergeCollection`. Which I believe would mean it looks like this: 

```
Onyx.setCollection(ONYXKEYS.COLLECTION.REPORT, {
    [`${ONYXKEYS.COLLECTION.REPORT}${report1.reportID}`]: report1,
    [`${ONYXKEYS.COLLECTION.REPORT}${report2.reportID}`]: report2,
    [`${ONYXKEYS.COLLECTION.REPORT}${report3.reportID}`]: report3,
});
```

**Comment by puneetlath** [comment]
How's this going @zirgulis?

**Comment by zirgulis** [comment]
@puneetlath PR open https://github.com/Expensify/react-native-onyx/pull/594

**Comment by puneetlath** [comment]
Great!

**Comment by puneetlath** [comment]
Alright, I've merged the Onyx PR. @zirgulis can you raise a PR to update the react-native-onyx version in App?

**Comment by zirgulis** [comment]
New PR to fix the onyx.update when using with setCollection + quality of life improvements

**Comment by allroundexperts** [comment]
Hi @puneetlath!

I reviewed 2 PRs here. Can I please have a payment summary?

Also, do we need a regression test here? The function itself is covered by unit tests.

**Comment by puneetlath** [comment]
I can't really think of a way to regression test it. Can you?

**Comment by puneetlath** [comment]
Payment summary: 
- C+ - $500 - @allroundexperts - to be paid via NewDot

Thanks everyone!

**Comment by JmillsExpensify** [comment]
$500 approved for @allroundexperts
