### ISSUE TITLE
Workspace - Spend category names and "Uncategorized" aren't translated to Spanish

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#51866]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.56-3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Y
**Found when validation PR:** https://github.com/Expensify/App/pull/50698
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
Precondition: Language is set to Spanish. Have a workspace with categories enabled and one connected to Sage Inacct.

1. Open the app
2. Log in with any account with a workspace
3. Navigate to Configuración - Espacios de trabajo - *any workspace with categories enabled* - Categorias - Configuración
4. Navigate to Configuración - Espacios de trabajo - *any workspace connected to Sage Inacct* - Categorias - Configuración

## Expected Result:
Spend category names should be translated.

## Actual Result:
Spend category names and "Uncategorized" aren't translated to Spanish.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [x] iOS: Standalone
- [x] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/2c4feefc-d4d7-43d0-8b5c-360230a0613e

https://github.com/user-attachments/assets/ed87f64f-adbd-4e97-b5f4-d49ef5f79dc8

![Bug6652372_1730471228682!Workspace_connected_to_Sage](https://github.com/user-attachments/assets/59cb0ca2-2aaa-4390-b607-ce9a6230ff07)

![Bug6652372_1730471228697!Workspace](https://github.com/user-attachments/assets/4ede7f20-c666-42f6-b293-c58487b33be9)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by puneetlath** [comment]
It's not expected that these be translated. They are set by the customer.
