### ISSUE TITLE
[HOLD for payment 2024-11-18] [Workspace feeds] Company Cards - Bank name persists between different banks in the Other card feed

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#51860]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.56-2
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/51569
## Action Performed:
1. Open the app
2. Log in with an expensify account that's an admin of a workspace with "Company Cards" enabled
3. Navigate to Workspace settings - Company cards
4. Navigate to Add company cards - Other - Mastercard Commercial Cards - Next
5. Enter any text for the "Name of bank"
6. Tap on the "Next" button
7. Navigate back to the screen where "Mastercard Commercial Cards" and "Visa Commercial Cards" are visible
8. Tap on "Visa Commercial Cards" - Next - Next

## Expected Result:
Bank name should be cleared when choosing a different bank

## Actual Result:
Bank name persists between different banks in the "Other" card feed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [x] iOS: Standalone
- [x] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/95657f08-25c7-4616-9413-7f8570b65f13

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @JmillsExpensify</details>

**Comment by Beamanator** [comment]
Thanks for the proposals so far, can anyone confirm which PR caused this regression?

**Comment by Julesssss** [comment]
Downgrading from blocker -- users can simply delete the name manually for now.

**Comment by narefyev91** [comment]
Hi, I'm Nicolay from Callstack - expert contributor group - and I would like to work on this issue.

**Comment by mountiny** [comment]
Should we add a regression test for this? @JmillsExpensify if not, we can close this as payments will be handled in lumpsum

**Comment by mountiny** [comment]
@JmillsExpensify there is one proposed from @allgandalf so I think we can go ahead with that one

**Comment by JmillsExpensify** [comment]
Ah haha sorry I missed it in the scroll. I'll add.

**Comment by JmillsExpensify** [comment]
Awesome thanks!
