### ISSUE TITLE
[HOLD] [$250] Android Hybrid - Login - Cursor displayed at the beggining of Email when trying to re login

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#51878]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.56-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Open the Expensify app
2. Log out of the account
3. Tap on "Continue with Email"
4. Verify that the cursor in Email input, is displayed at the end of the last used Email

## Expected Result:
When trying to re log in, the cursor in Email input should be displayed at the end of the last used Email

## Actual Result:
After logging out and trying to re login, the cursor in Email input is displayed at the beggining of the last used Email

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [x] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/09572b28-f84a-40a3-8ef4-d5383e1d815f

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021857152364358853345</li>
        <li>Upwork Job ID: 1857152364358853345</li>
        <li>Last Price Increase: 2024-11-14</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @mollfpr</details>

**Comment by lanitochka17** [comment]
@abekkala  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by QichenZhu** [comment]
Not quite sure if it’s related, but I worked on a similar issue https://github.com/Expensify/App/issues/50055.

**Comment by abekkala** [comment]
Looks like there is discusson in #50055 on next steps

**Comment by abekkala** [comment]
@QichenZhu would the fix for https://github.com/Expensify/App/issues/50055 resolve this issue?

**Comment by QichenZhu** [comment]
> would the fix for https://github.com/Expensify/App/issues/50055 resolve this issue?

@abekkala Sorry, I can't answer this question as I don't have access to the HybridApp repo.

**Comment by abekkala** [comment]
@mollfpr I think we should hold this one on https://github.com/Expensify/App/issues/50055

**Comment by mollfpr** [comment]
The #50055 will close soon and the [PR](https://github.com/Expensify/App/pull/52734) for the RN patch is ready for review. We can test again after the PR merged.

**Comment by mollfpr** [comment]
The RN patch is merged and hit production. @abekkala We can ask QA to test it again.

**Comment by abekkala** [comment]
@lanitochka17 can this be retested please?

**Comment by lanitochka17** [comment]
Issue still reproducible  Cursor is still displayed at the beginning of the Email when trying to log in again.
 

https://github.com/user-attachments/assets/c0a14524-9e83-4382-bffa-d5e94fb105e4

**Comment by muttmuure** [comment]
This seems low value. I think we should close it.
