### ISSUE TITLE
[HOLD for payment 2024-11-18] [$125] Expensify Card - Back button on issue card page returns to Bank account verified page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#51883]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.56-3
**Reproducible in staging?:** Y
**Reproducible in production?:** N/A Unable to check
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+kh081006@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace settings > Expensify Card
3. Click Issue new card
4. Add a bank account
5. Dismiss the RHP
6. Click Issue new account
7. Select the added bank account
8. On Bank account verified page, click Got it
9. On Issue card page, click RHP back button

## Expected Result:
The RHP will be dismissed

## Actual Result:
App returns to Bank account verified page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [x] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [x] iOS: HybridApp
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/9b4080e6-1e88-4c74-825a-01b83e605de1

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @OfstadC</details>
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021853850206557900537</li>
        <li>Upwork Job ID: 1853850206557900537</li>
        <li>Last Price Increase: 2024-11-05</li>
<li>Automatic offers: </li>
<ul>
<li>Nodebrute | Contributor | 104755066</li>
<li>rayane-djouah | Contributor | 104792968</li>
</ul></li>
    </ul>
</details>

**Comment by thienlnam** [comment]
Possibly no longer an issue https://expensify.slack.com/archives/C01GTK53T8Q/p1730482621189069

**Comment by situchan** [comment]
@daledah's [proposal](https://github.com/Expensify/App/issues/51883#issuecomment-2452871028) looks good.
There's one more verifying step after https://github.com/Expensify/App/pull/51407 so the repro step should be updated a bit.
🎀👀🎀 C+ reviewed

**Comment by situchan** [comment]
@Nodebrute sorry I didn't realize that there was a proposal before making External. I reviewed only @daledah's proposal.
And yes, your proposal also looks good. Since you're the first, you can be assigned.
cc: @thienlnam

**Comment by OfstadC** [comment]
Asking to have this retested [here](https://expensify.slack.com/archives/C9YU7BX5M/p1730758220361779) Based on this - https://expensify.slack.com/archives/C01GTK53T8Q/p1730487824713359?thread_ts=1730482621.189069&cid=C01GTK53T8Q

**Comment by situchan** [comment]
Agree with @Nodebrute.

> We can also use goBack() before navigating to `WORKSPACE_EXPENSIFY_CARD_ISSUE_NEW`

The same approach was used in https://github.com/Expensify/App/pull/44712

**Comment by situchan** [comment]
@daledah yes, I already checked it. You wanna find and fix all instances throughout the app then?

**Comment by kavimuru** [comment]
Bug is still reproducible 

https://github.com/user-attachments/assets/4a6778b9-dcf5-4055-80fd-246f900a76a3

**Comment by thienlnam** [comment]
Adjusting bounty as this is a simple bug

**Comment by thienlnam** [comment]
I don't think the navigation direction makes a big difference here

**Comment by situchan** [comment]
@Anusha if still same after pod install, reset cache
```
npm start -- --reset-cache
```

**Comment by situchan** [comment]
@s77rt please take over as C+

**Comment by s77rt** [comment]
Will get someone else to review the PR as I cannot reproduce the bug due to bank issues.

**Comment by s77rt** [comment]
cc @rayane-djouah

**Comment by OfstadC** [comment]
@rayane-djouah Please complete the BZ checklist before the payment date. Thank you! 😃

**Comment by OfstadC** [comment]
Test - https://github.com/Expensify/Expensify/issues/445651

## Payment Summary

- @rayane-djouah [paid $125](https://www.upwork.com/nx/wm/workroom/38920042/overview) via Upwork 
- @Nodebrute [paid $125](https://www.upwork.com/nx/wm/workroom/38900943/overview) via Upwork
