### ISSUE TITLE
[HOLD for payment 2024-12-07] [Search v1] Add bulk actions on Search

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#51911]
With [this PR](https://github.com/Expensify/App/issues/51898), we're introducing new inline actions on the Search page. The next step is to add bulk actions so users can batch process reports.

<details><summary>Issue Owner</summary>Current Issue Owner: @lschurr / @VictoriaExpensify</details>

**Comment by luacmartins** [comment]
Draft PR is ready, but we need to hold on the inline PRs.

**Comment by dubielzyk-expensify** [comment]
Any PR you want me to have a look at?

**Comment by luacmartins** [comment]
@dubielzyk-expensify eventually [this PR](https://github.com/Expensify/App/pull/51913), but that's still on hold for other PRs

**Comment by dubielzyk-expensify** [comment]
Alright. Let me know and I'll give it a review when it's ready 👍

**Comment by twisterdotcom** [comment]
Relabelling as Lauren is OOO now.

**Comment by trjExpensify** [comment]
I know we're super close to being done here, but I'm popping it in #migrate anyway to track to completion, as making the action buttons available on the search page is central to support our plans to better support batch processing on the Search page.

**Comment by lschurr** [comment]
Removing you Vics :)

**Comment by lschurr** [comment]
Payment summary is correct - please request in ND @Pujan92 :)

**Comment by garrettmknight** [comment]
$250 approved for @Pujan92
