### ISSUE TITLE
[HOLD for payment 2024-11-22] [Workspace feeds] Card art on card details page looks a  bit smaller than the mockups

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#51910]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:** needs reproduction
**Reproducible in production?:** needs reproduction
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @joekaufmanexpensify 
**Slack conversation** (hyperlinked to channel name): [quality](https://applause-ts.slack.com/archives/C05LX9D6E07/p1730402951932829)

## Action Performed:
Prerequisite:
Members and company cards added in workspace , 8+ export options for card

1. Go to staging.new.expensify.com
2. Choose the workspace from settings
3. Click company cards >Card Details

## Expected Result:
Card art on the card details should match the mocks
## Actual Result:
Card art on card details page looks a good bit smaller than the mockups, and compared to analogous pages for Expensify Card.
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>
![image - 2024-10-31T152943 856](https://github.com/user-attachments/assets/8ed3e674-fddd-47dc-b4c2-3fe297242e22)
![image - 2024-10-31T152932 168](https://github.com/user-attachments/assets/32220c5a-aac5-41dd-89e9-f7f32d8c18d9)

  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mountiny** [comment]
Handling this as part of the project I have worked on

**Comment by waterim** [comment]
Hello, Im Artem from Callstack and would like to help with this issue!

**Comment by mountiny** [comment]
assigned, thanks

**Comment by waterim** [comment]
@mountiny Here is an issue with exported SVGs we have
It has sizes defined in svg itself for icons(for selections list, list of cards etc.)
and all of the cards have size: viewBox="0 0 40 40"
While expensify card has viewBox="0 0 235 148"

And I cant just change the size with ignoring aspect ratio because svg is not optimized for this scale and looks like this:
<img width="384" alt="image" src="https://github.com/user-attachments/assets/6a5aa5eb-60dd-4da2-972b-2d57eaab823e">

I think we need to devide icons company cards and full big card images with another aspect ratio

Some designer is needed here for exporting all correct card images

**Comment by waterim** [comment]
I need: Amex, BOA, CapitalOne, Chase, Citibank, WellsFargo, BrexCompany, Stripe, Other

**Comment by mountiny** [comment]
👋 any chance you could help with the request above? @dannymcclain thanks!

**Comment by dannymcclain** [comment]
Absolutely. I'll upload the updated card SVGs here once I get a chance to make them! We can't be showing squish squashed cards in the app 😂

**Comment by mountiny** [comment]
@dannymcclain friendly bump

**Comment by dannymcclain** [comment]
Getting to this today!

**Comment by dannymcclain** [comment]
Alright let's try these:

[Card Images - Large.zip](https://github.com/user-attachments/files/17681746/Card.Images.-.Large.zip)

**Comment by mountiny** [comment]
time for checklist, no regression test required, we will add them with @joekaufmanexpensify at the end of the project

**Comment by mountiny** [comment]
@allgandalf let us know when you fill out the checklist
