### ISSUE TITLE
[HOLD for payment 2024-11-14] [HOLD for payment 2024-11-13] [WAIT FOR PAYMENT - 14th November] Room - App crashes after submitting expense to user or creating a new room

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#51959]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.57-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Email or phone of affected tester (no customers):** applausetester+kh22100010ad@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to FAB > Submit expense.
3. Enter amount > Next.
4. Select a user that has no previous chat.
5. Submit the expense.

1. Go to staging.new.expensify.com
2. Go to FAB > Start chat.
3. Go to Room.
4. Create a new room.

## Expected Result:
App will not crash.

## Actual Result:
App crashes after submitting expense to user or creating a new room.
It also crashes by just opening new chat.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/b1b7c9fb-d6bd-4460-987a-9ce41389650f

[0411_1.txt](https://github.com/user-attachments/files/17620576/0411_1.txt)

https://github.com/user-attachments/assets/bbfda954-5522-40b6-ac9d-f805c18a3305

  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @slafortune</details>

**Comment by Julesssss** [comment]
@flodnv did the CP resolve the issue? I don't see any comments on the checklist or PR post-CP confirming the issue was resolved. 

If not I will ask QA to retest.

**Comment by Julesssss** [comment]
Verified fixed: https://github.com/Expensify/App/pull/51973#issuecomment-2456925746

**Comment by Julesssss** [comment]
I believe the only remaining task here is payment for @rojiphil's C+ review

**Comment by flodnv** [comment]
@slafortune can you please process payment for @rojiphil's review https://github.com/Expensify/App/issues/51959#issuecomment-2456942709 and then close this issue?

**Comment by flodnv** [comment]
Ah, no, not necessarily. We can wait.

**Comment by rojiphil** [comment]
> I believe the only remaining task here is payment for @rojiphil's C+ review

Oh! I do not need the payment for the work here, as we can consider it part of this [PR](https://github.com/Expensify/App/pull/51573) where I was the C+ reviewer.
@slafortune We can close this out.
