### ISSUE TITLE
New Library Request: expo-navigation-bar

### ISSUE THREAD

**Issue by kirillzyusko** [Expensify/App#51957]
In order to properly evaluate if a new library can be added to `package.json`, please fill out this request form. It will be automatically assigned someone from our review team that will go through and vet the library.

*In order to add any new production dependency, it must be approved by the App Deployer team. They will evaluate the library and decide if it's something we want to move forward with or if other alternatives should be explored.*

Note: This is only for production dependencies. While we don't want people to add packages to dev-dependencies willy-nilly, we recognize that there isn't as great of a need there to secure them.

# Name of library:

## Details
- Link to package: https://www.npmjs.com/package/expo-navigation-bar
- Problem solved by using this package: https://github.com/Expensify/App/issues/51673
- Number of stars in GH: 34k
- Number of monthly downloads: ~160k
- Number of releases in the last year: ~12-13
- Level of activity in the repo: High
- Alternatives: https://www.npmjs.com/package/react-native-navigation-bar-color
- Are security concerns brought up and addressed in the library's repo? N
- How many dependencies does this lib use that will be brought into our code? `@react-native/normalize-colors` + `debug` but we already use them, so `0`
- What will the effect be on the bundle size of our code? ~25kb (`src` + `android` folders)

**Comment by jasperhuangg** [comment]
> Are all the answers in the main description filled out properly and make sense?
Yes

> Who maintains the library and how well is it maintained?
Expo, seems to be very well maintained.

> How viable are the alternatives?
There is another library, [react-native-navigation-bar-color](https://www.npmjs.com/package/react-native-navigation-bar-color), but its popularity seems to be dying down. The package may not support Fabric/bridgeless mode, etc., so it's not ideal for us to use.

> Should we build it ourselves instead?
Probably not, Expo is a pretty reputable company that releases some very performant and well-maintained. It seems easier for us to just leverage this library.

**Comment by jasperhuangg** [comment]
https://expensify.slack.com/archives/C03TQ48KC/p1730933053958029

**Comment by jasperhuangg** [comment]
Latest update [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1731420578341999?thread_ts=1731092817.909359&cid=C01GTK53T8Q)

**Comment by jasperhuangg** [comment]
We're not moving forward with this library request since we have longer-term solutions that we're working on that will fix this issue.
