### ISSUE TITLE
[$250] [HOLD for payment 2024-11-22] [Search v2.5] If Search in suggests a workspace chat, we should add the reportID filter instead of in. Same goes for invoice and trip rooms

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#51964]
Coming from [this thread](https://expensify.slack.com/archives/C06ML6X0W9L/p1728287678155109?thread_ts=1727907702.678009&cid=C06ML6X0W9L), we should make `expenses` the default type when suggesting contextual report searches if the report is a workspace chat or invoice room

1. Head to the workspace chat
2. Click the router, opt for `Search in`
3. Add the merchant/description from a historical expense

**Expected result**
Standard search for a workspace chat would be the `expense` type

**Actual result**
I land on the Search results page with `type:chats` selected

cc @SzymczakJ 

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021857432600242148425</li>
        <li>Upwork Job ID: 1857432600242148425</li>
        <li>Last Price Increase: 2024-11-15</li>
    </ul>
</details>

**Comment by 289Adam289** [comment]
Hi I am Adam from SWM and I'd like to work on this issue

**Comment by 289Adam289** [comment]
From my understanding, using: `type:expense reportID:<workspace chat>` and `type:invoice reportID:<invoice room>` should get all expenses/invoices from a specific room, but I'm not receiving any results. Is this supported on the backend, or should a different query be created?

**Comment by luacmartins** [comment]
I think the reason you don't see any results is because those reportIDs belong to a `chat` report and the expenses are actually reported on `expense` or `invoice` type reports, which is a child of the chat report. So I think a more accurate filter would be `type:expense policyID:<workspaceID> from:<workspace chat participant email>` since that'd filter all expenses sent by a user to the workspace, which should live in the workspace chat. Similarly, for invoice `type:invoice policyID:<invoice room policyID> from:<invoice room participant email>`. 

cc @JmillsExpensify to confirm since you suggested this change

**Comment by johncschuster** [comment]
Adding `External` to create the Upwork job

**Comment by johncschuster** [comment]
# Payment Summary:

Contributor: @289Adam289 does not require payment

Contributor+: @rayane-djouah paid $250 via Upwork

Upwork job [here](https://www.upwork.com/jobs/~021857432600242148425)! Please apply

**Comment by johncschuster** [comment]
Just dropping a note for Melv. This will be eligible for payment in two days 👍

**Comment by johncschuster** [comment]
@rayane-djouah can you please accept the [invite](https://www.upwork.com/nx/wm/offer/105023305) to the job?

**Comment by johncschuster** [comment]
Paid! Thanks for your contributions! 🎉
