### ISSUE TITLE
[$250] Onboarding -Not here page is displayed after navigating back from Workspace settings

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#51963]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.57-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Email or phone of affected tester (no customers):** htad26+fgfgfjhgf@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Sign in to the app with a new Gmail account
2. Choose "Manage my team's expense" from the onboarding tasks > Finish the flow
3. After finishing the onboarding flow navigate to the concierge chat
4. Click on "Set up categories" from the tasks
5. Click on the "Take me to workspace category settings." link
6. Once you are navigated to "categories" settings, click back from the workspace settings
7. Then click on the inbox tab to navigate to LHN

## Expected Result:
The onboarding task page in concierge opens

## Actual Result:
"Hmm... it's not here" pages opens

## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/949ae4d8-3ac7-4e2d-9e78-c4767bc1d7d5

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021853505694132276985</li>
        <li>Upwork Job ID: 1853505694132276985</li>
        <li>Last Price Increase: 2024-11-04</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @akinwale</details>

**Comment by marcochavezf** [comment]
For some reason the reportIDs for the tasks created in the onboarding list doesn't exist

<img width="425" alt="Screenshot 2024-11-04 at 12 08 13 p m" src="https://github.com/user-attachments/assets/6b672c36-2b01-4ea1-a7de-a7bed3263cb2">

I'm still investigating

**Comment by marcochavezf** [comment]
We're getting the error "400 Unique Constraints Violation"

<img width="568" alt="Screenshot 2024-11-04 at 12 11 46 p m" src="https://github.com/user-attachments/assets/f01259b4-eaf6-4902-9c90-6b71aeba2487">

**Comment by marcochavezf** [comment]
The difference between the staging/local and prod versions is that we're sending `"completedTaskReportActionID":"-1"` in the payload in the former. The payload is malformed, so it's a FE error. Assigning `External` label to get more 👀

**Comment by marcochavezf** [comment]
Ok, this is the offending PR https://github.com/Expensify/App/pull/51722, completedTaskReportActionID are not sent to the BE when completedTaskReportActionID is undefined, otherwise cause the unique constraints violation error

**Comment by marcochavezf** [comment]
Revert https://github.com/Expensify/App/pull/51983

**Comment by DylanDylann** [comment]
I think we should fix this bug on BE to adopt new value

**Comment by DylanDylann** [comment]
But if we revert https://github.com/Expensify/App/pull/51983 we will re-introduce the original issue. If this regression is more serious, I agree to revert

**Comment by marcochavezf** [comment]
Hmm, that's true. Both bugs are serious because they are part of the onboarding process, and any new user will experience them. I will try to fix them in the BE, but probably the BE fix won't make it before the next App release. 

If I had to choose between the two bugs, I would lean forward to fixing this one because the current cohort will experience it vs someone looking to split and chat with friends

**Comment by marcochavezf** [comment]
What I found is that optimistic reportActionIDs should be 0 or any positive number. If it's 0, BE will create a new random reportActionID. For this issue, technically we shouldn't set the completedTaskReportActionID because it will mark the tasks as completed by default. For https://github.com/Expensify/App/issues/51395, I think we'd need a backend fix

**Comment by marcochavezf** [comment]
Created [PR](https://github.com/Expensify/Auth/pull/13026) to fix https://github.com/Expensify/App/issues/51395 in the BE. So we can continue with the revert https://github.com/Expensify/App/pull/51983

**Comment by marcochavezf** [comment]
[CP](https://github.com/Expensify/App/actions/runs/11672307633)

**Comment by Anaslancer** [comment]
@marcochavezf I just found the problem and fixed it on frontend side.
Let me post my proposal?

**Comment by marcochavezf** [comment]
Oh I already reverted the offending PR @Anaslancer

**Comment by marcochavezf** [comment]
Tested the revert in staging and the bug is gone. Removing the deploy blocker label
