### ISSUE TITLE
Onboarding - Error occurs when marking a task as complete

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#51969]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.57-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** htad26+fgfgfjhgf@gmail.com
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/51722
## Action Performed:
1. Sign in with new account
2. On the onboarding flow, select "Chat and split expenses with friends" > Enter a name and finish the flow
3. In the concierge chat, click on any of the tasks
4. Click on "Mark as complete"

## Expected Result:
The task is marked as complete

## Actual Result:
"You don't have permission to take the requested action." error occurs

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/491bb71c-1328-4248-ae44-a10ba8db72cc

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by danieldoglas** [comment]
hmm @deetergp looks like the permissions are not correctly set for the new tasks being created? I think it's related to https://github.com/Expensify/Auth/pull/12835

**Comment by danieldoglas** [comment]
cc @francoisl too

**Comment by trjExpensify** [comment]
Scott is out until tomorrow btw.

**Comment by danieldoglas** [comment]
This is a backend issue, so I don't think we need to block the app on it. do you agree, @trjExpensify @francoisl ?

**Comment by francoisl** [comment]
Yes agreed.

**Comment by danieldoglas** [comment]
I think this one is finished. @francoisl did all the work on the backend. Assigning him and closing the issue.
