### ISSUE TITLE
Start chat - Keyboard-selected item background and hover background are the same

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#51975]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.57-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+kh22100010ad@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to FAB > Start chat
3. Navigate through the list via keyboard
4. Hover over another member

## Expected Result:
The selected item background and hover background will be different (production behavior)

## Actual Result:
The selected item background and hover background are the same

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/ff5cbb2e-d6fd-45c7-9e0f-2f6e1776820c

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by nkdengineer** [comment]
It's the new expected behavior.

**Comment by dangrous** [comment]
yep, this is expected from https://github.com/Expensify/App/issues/50779 - cc @Expensify/design

I'm going to close but if anyone disagrees let me know

**Comment by shawnborton** [comment]
Yup, indeed that is intentional. Don't know where the blue outlines went though but I think that's a separate thing maybe?

**Comment by dangrous** [comment]
yeah I think the blue outlines have been coming and going periodically... I believe it's being handled elsewhere? @nkdengineer do you happen to know?
