### ISSUE TITLE
Workspace - Endless loading spinner when importing member csv file

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#51978]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.57-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5176182&group_by=cases:section_id&group_id=229065&group_order=asc
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Account A: Log in with a new Gmail account
2. Account A: Create a workspace
3. Account A: Navigate to the workspace members page
4. Account A: Invite 3 Gmail addresses without an Expensify account
5. Account A: Navigate to "..." - Download CSV
6. Account A: Save the CSV file
7. Account B: Log in with a new Gmail account
8. Account B: Create a workspace
9. Account B: Navigate to the workspace members page
10. Account B: Navigate to "..." - Import spreadsheet
11. Account B: Open the CSV file saved at step 6
12. Account B: Click on the "Import" button

## Expected Result:
I should be able to add members with the csv file.

## Actual Result:
Endless loading spinner when importing member csv file. I can also repro it with the same account on a different workspace. "Hidden" members are appearing in the member list after dismissing the RHP.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/c4591997-b80e-42dd-a798-a6858bf8d0d2

[Bug6654538_1730741268855!Members-2024-11-04_17_12_01.606.csv](https://github.com/user-attachments/files/17622080/Bug6654538_1730741268855.Members-2024-11-04_17_12_01.606.csv)
  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by anmurali** [comment]
Rotating for a BZ member while I am OOO
