### ISSUE TITLE
Onboarding - Concierge and self-DM chats disappear from LHN after returning from accounting

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#51974]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.57.0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Issue was found when executing this PR:** https://github.com/Expensify/App/pull/51070
**Email or phone of affected tester (no customers):**
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Enter a new email and tap "Join"
3. Select "Manage my team's expense" on onboarding > any number of employees
4. Select any integration option
5. Navigate to the concierge chat
6. Open the task "Connect to <integration name>"
7. Tap the link "Take me to Accounting"
8. Return to the LHN using the back icon

## Expected Result:
The Concierge and self-DM chats are displayed in the LHN

## Actual Result:
Th Concierge and self-DM chats disappear from LHN after returning from accounting

## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/7be9f101-b870-466e-8361-6ddfc32f71fb

  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by IuliiaHerets** [comment]
Issue not repro with stg server off  

https://github.com/user-attachments/assets/04ee6489-cc39-44df-84dd-ae6d33d0edee

**Comment by neil-marcellini** [comment]
I just tested on iOS mWeb and it's not reproducible. That's the environment that proved it wasn't reproducible on prod. Therefore I don't think this is a blocker. Please re-test on mWeb Android and we can close if it's not reproducible there.

**Comment by JmillsExpensify** [comment]
Asked QA to re-test in Slack.

**Comment by isagoico** [comment]
Issue is not reproducible anymore 🎉

https://github.com/user-attachments/assets/20fce468-e713-49d0-8d78-1805d75cc7d0

**Comment by JmillsExpensify** [comment]
Thanks! Closing
