### ISSUE TITLE
[HOLD for payment 2024-11-26] [$250] Reduce number of `react-compiler/react-compiler` and `react-hooks/exhaustive-deps` eslint comments

### ISSUE THREAD

**Issue by blazejkustra** [Expensify/App#51972]
Currently we disable `react-compiler/react-compiler` in 214 files (332 occurances), which means we don't strictly follow React rules.

This is a problem because of two reasons:
- All these components are not compiled
- With React concurrent mode turned on this could lead to unexpected bugs (especially once we upgrade to React v19)

Solution? Find a way to adjust the code in a way it doesn't break React rules.
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021854187628255719202</li>
        <li>Upwork Job ID: 1854187628255719202</li>
        <li>Last Price Increase: 2024-11-06</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @alexpensify</details>

**Comment by alexpensify** [comment]
Update: Waiting for this one to go to production

**Comment by alexpensify** [comment]
Payouts due: 2024-11-26

- [ ] Contributor: $250 @blazejkustra 
- [ ] Reviewer: $250 @dominictb - I sent a request via Upwork here: https://www.upwork.com/jobs/~021854187628255719202 - Please accept 

Upwork job is [here](https://www.upwork.com/jobs/~021854187628255719202).

**Comment by alexpensify** [comment]
I'm OOO this week, but I'm checking in on a few tasks. I passed by to check if there was an Upwork update. Since this one has not been approved yet, my next check in will be on Friday (PST) morning.

**Comment by alexpensify** [comment]
No update - waiting for @dominictb to accept. I'll check again on Monday.

**Comment by alexpensify** [comment]
Thanks! All set here, @dominictb has been paid via Upwork. 

https://github.com/Expensify/App/issues/51972#issuecomment-2501796003
