### ISSUE TITLE
Unable to delete a feed

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#52003]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:** need reproduction
**Reproducible in production?:** need reproduction
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @joekaufmanexpensify 
**Slack conversation** (hyperlinked to channel name): [quality](https://applause-ts.slack.com/archives/C05LX9D6E07/p1730755586339529)

## Action Performed:
1. Set up a feed with supportal tool 
2. Delete the feed

## Expected Result:
Able to delete the feed
## Actual Result:
Unable to delete the feed. It happens with pending feeds as well
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>
![image (108)](https://github.com/user-attachments/assets/219a98cb-aea2-489e-b4c2-853ead76cb51)

https://github.com/user-attachments/assets/b1f5cb15-5a00-4449-becc-5b16f8951db0

 
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by m-natarajan** [comment]
BZ team member, Callstack will work on this issue, please wait for them to comment before moving the issue forward.

**Comment by mountiny** [comment]
PR is up and ready to get merged

**Comment by mountiny** [comment]
Yes, we identified another issue with the existing implementation, working on the fix

**Comment by joekaufmanexpensify** [comment]
Sounds good!
