### ISSUE TITLE
Onboarding - User lands on LHN instead of Concierge when "Manage team's expenses" is selected

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#52018]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.57-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** applausetester+kh22100010ad@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Launch ND or hybrid app.
2. Sign up as a new Gmail user.
3. Select "Manage my team's expenses" during onboarding.
4. Complete the flow.
5. Note that user is not redirected to Concierge after onboarding.
6. Log out.
7. Sign up as a new Gmail user.
8. Select any other purpose except "Manage my team's expenses" during onboarding.
9. Complete the flow.
10. Notet that user is redirected to Concierge after onboarding when any other purpose other than "Manage my team's expenses" is selected during onboarding.

## Expected Result:
In Step 5, user should be redirected to Concierge after completing onboarding when "Manage my team's expenses" is selected.

## Actual Result:
In Step 5, user is redirected to LHN after completing onboarding when "Manage my team's expenses" is selected.

When different purpose is selected, user is brought to Concierge after completing onboarding.

## Workaround:
Unknown

## Platforms:

- [x] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [x] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/cf286076-d979-410c-9fd3-2ab871f1c2fd

 
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by MitchExpensify** [comment]
@strepanier03 Where are you checking? I have the opposite issue here https://github.com/Expensify/App/issues/52420

**Comment by MitchExpensify** [comment]
So you can close this and we'll focus on the issue I'm assigned to
