### ISSUE TITLE
[HOLD for payment 2024-12-07] [$250] [Chore] Bump `react-native-reanimated` to 3.16.3

### ISSUE THREAD

**Issue by blazejkustra** [Expensify/App#52024]
This issue aims to update `react-native-reaniamted` to the newest version because of two reasons:
1. [Workletization of `react-native-live-markdown`](https://github.com/Expensify/react-native-live-markdown/pull/439), requires that we have latest version installed + it blocks [[Autocomplete] Highlight autocomplete key and selected value](https://github.com/Expensify/App/issues/50949)
2. Starting from this versions, there is a new API for shared values that is compatible with react-compiler. More info [here](https://github.com/reactwg/react-compiler/discussions/14#discussioncomment-10123774)

<details><summary>Issue Owner</summary>Current Issue Owner: @OfstadC</details>
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021853942849461570206</li>
        <li>Upwork Job ID: 1853942849461570206</li>
        <li>Last Price Increase: 2024-11-05</li>
<li>Automatic offers: </li>
<ul>
<li>allgandalf | Contributor | 105098848</li>
</ul></li>
    </ul>
</details>

**Comment by luacmartins** [comment]
Assigning myself since this change affects Search - https://github.com/Expensify/App/issues/50949

**Comment by blazejkustra** [comment]
Update: I created a draft [PR](https://github.com/software-mansion-labs/expensify-app-fork/pull/131) with the update, however I hit a wall because there are crashes after the upgrade, I let the reanimated team know and they are working on it ([here](https://github.com/software-mansion/react-native-reanimated/issues/6613) is an upstream issue).

Also FYI I'm OOO 7-11 November, so I'll go back to this after the break.

**Comment by luacmartins** [comment]
Thanks for the update @blazejkustra! Enjoy your time off.

**Comment by blazejkustra** [comment]
Update: [PR](https://github.com/Expensify/App/pull/52048) that bumps the version is ready and awaits C+ review.

> however I hit a wall because there are crashes after the upgrade, I let the reanimated team know and they are working on it (https://github.com/software-mansion/react-native-reanimated/issues/6613 is an upstream issue).

We decided not to wait for the upstream fixes as this could take more time than initially anticipated, and new version is crucial as it affects Search - https://github.com/Expensify/App/issues/50949. 

Once the above PR is merged let's not close this issue so we can migrate to new shared values API as part of this issue, wdyt @luacmartins?

**Comment by luacmartins** [comment]
Sounds good!

**Comment by luacmartins** [comment]
done

**Comment by luacmartins** [comment]
No regression tests.

**Comment by luacmartins** [comment]
Hmm this issue is still not done. We're still working on https://github.com/Expensify/App/pull/52825

**Comment by blazejkustra** [comment]
Update: [Reanimated bump](https://github.com/Expensify/App/pull/52825) is ready for review 🚀

@eVoloshchak Could you please review today? It is blocking a high priority [issue](https://github.com/Expensify/App/issues/50949)

**Comment by luacmartins** [comment]
Thanks! @eVoloshchak let's prioritize reviewing this one

**Comment by OfstadC** [comment]
>Hmm this issue is still not done. We're still working on https://github.com/Expensify/App/pull/52825


Ah okay 😅 - I'll ignore the payment piece for now

**Comment by OfstadC** [comment]
I just noticed we didn't add this to a project 😅 - I think this falls under #stability? since it doesn't really fit the other buckets. So i'll add it there, but if i'm wrong, please let me know!

**Comment by OfstadC** [comment]
Paying today since tomorrow is a Saturday 😄 

## Payment Summary 

- @eVoloshchak due $250 via manual NewDot Manual Request
- @blazejkustra does not require payment 
- @allgandalf [paid](https://www.upwork.com/nx/wm/workroom/39101724/overview) $250 via Upwork

**Comment by JmillsExpensify** [comment]
$250 approved for @eVoloshchak
