### ISSUE TITLE
[$250] Android - Search - Unable to add number at the beggining of expense´s amount while editing

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#52026]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.57-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5180262&group_by=cases:section_id&group_order=asc&group_id=296775
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Open the Expensify app.
2. Tap on "Search"
3. Open any expense.
4. Tap on "Amount"
5. Verify that the cursor is displayed at the end of the amount and that the user is able to add a number at the beggining of it.

## Expected Result:
When landing on the amount edition tab, the user should be able to edit it by adding a number at the beggining, and the cursor should be displayed at the end of the amount.

## Actual Result:
When landing on the amount edition´s tab, the cursor is displayed at the beggining of the amount and the user isn´t able to add any number until moving the cursor to the end and returning to the beggining again.

## Workaround:
Unknown

## Platforms:

- [x] Android: Standalone
- [x] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/52afca0d-4416-43e9-82e7-32ca1bf00ca8
 
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021856072640497865812</li>
        <li>Upwork Job ID: 1856072640497865812</li>
        <li>Last Price Increase: 2024-11-11</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @rushatgabhane</details>

**Comment by QichenZhu** [comment]
This might be related to https://github.com/Expensify/App/issues/50055 and there's an [upstream PR](https://github.com/facebook/react-native/pull/46948) to fix it. We're waiting for the upstream release.

**Comment by greg-schroeder** [comment]
@rushatgabhane can you help confirm if https://github.com/Expensify/App/issues/52026#issuecomment-2458589903 is accurate?

**Comment by greg-schroeder** [comment]
Adding to #expense given the linked bug is there, but not adding to `Followed Up` yet until the above is confirmed

**Comment by greg-schroeder** [comment]
Held

**Comment by QichenZhu** [comment]
**Update:** https://github.com/Expensify/App/issues/50055 will soon be closed in favor of https://github.com/Expensify/App/issues/52029.

**Comment by greg-schroeder** [comment]
Posted in #qa

**Comment by izarutskaya** [comment]
Issue is not reproducible anymore.

https://github.com/user-attachments/assets/9e103d29-a818-4ff8-a266-4b195876021b

**Comment by greg-schroeder** [comment]
Closing as not reproducible, please reopen/comment if you disagree
