### ISSUE TITLE
Comprehensive unit tests and docs  for LHN item presence

### ISSUE THREAD

**Issue by OlimpiaZurek** [Expensify/App#52031]
**Problem**
LHN items have a historical record of rendering inconsistencies & regressions that lead us to a recurring question of “Why is this in my LHN?”.
There are multiple factors determining which reports should be displayed including report’s type, participants, status, specific conditions such as being pinned, having violations, or being archived which makes it easy to accidentally break this pipeline.

**Solution**
Implement a comprehensive unit test suite & docs around `shouldReportBeInOptionList` that focuses on clearly defined scenarios for report visibility. This will help us increase confidence and make sure on the CI level that no regressions in this area make it to the production environment which is not something we can guarantee ourselves right now. Here are some sample scenarios we can assert:

 Should show the report
- is expense report with outstanding violations and the report is not reimbursed
- is currently viewing
- has valid draft comment in the report
- Is a self DM report
- is marked it as pinned
- is in focus mode and the report is unread
- is in default mode and the report is archived

slack thread: https://callstack-hq.slack.com/archives/C05LX9D6E07/p1727967763482779

**Comment by RachCHopkins** [comment]
Expensify slack thread for convenience: https://expensify.slack.com/archives/C05LX9D6E07/p1727967763482779

**Comment by mountiny** [comment]
We are chugging along on these

**Comment by mountiny** [comment]
in progress

**Comment by mountiny** [comment]
This was for tracking and the last issue open is this one https://github.com/Expensify/App/issues/52034 and the PR for it was just merged so I think we can close this one and consider it concluded https://github.com/Expensify/App/pull/53745
