### ISSUE TITLE
[HOLD for payment 2024-11-20] Update readme to include LHN Rules

### ISSUE THREAD

**Issue by OlimpiaZurek** [Expensify/App#52035]
Tracking issue: https://github.com/Expensify/App/issues/52031

Add a section to the README that explains the rules for what shows or hides in the LHN.

<details><summary>Issue Owner</summary>Current Issue Owner: @JmillsExpensify</details>

**Comment by mountiny** [comment]
This was just adding a README for some tests, no c+ review, no regression
