### ISSUE TITLE
[HOLD for payment 2024-11-20] Implement attribute limitation for performance traces

### ISSUE THREAD

**Issue by rinej** [Expensify/App#52039]
Firebase Performance Monitoring has a limitation on the number of custom metadata attributes we can use for traces; it only allows up to five attributes. To work within this constraint, we need to implement a method to selectively limit which attributes are saved in Firebase, ensuring we stay within the allowed threshold.

Additionally, we need a solution that enables us to save all attributes for use in other tools, e.g. Grafana, where no such limitation exists.

**Comment by mountiny** [comment]
Not a bug, performance monitoring improvement, no payment, closing
