### ISSUE TITLE
[HOLD for payment 2024-11-26] Set up environment for LHN tests

### ISSUE THREAD

**Issue by OlimpiaZurek** [Expensify/App#52036]
Tracking issue: https://github.com/Expensify/App/issues/52031

Prepare the mock data and environment needed to run LHN tests, including any dependencies, e.g. Onyx,  user settings etc.

<details><summary>Issue Owner</summary>Current Issue Owner: @OlimpiaZurek</details>

**Comment by OlimpiaZurek** [comment]
Yes, so you can assign me to this one as well

**Comment by zanyrenney** [comment]
is something required of me here @mountiny ?

**Comment by mountiny** [comment]
No, we should be able to handle this one without payments

**Comment by mountiny** [comment]
thanks!

**Comment by mountiny** [comment]
@OlimpiaZurek working on this

**Comment by mountiny** [comment]
Setting up the tests, new feature and nobody to pay, no regression test required. I am going to close this
