### ISSUE TITLE
Switch from using `cardList` on the payments page to `fundList`

### ISSUE THREAD

**Issue by stitesExpensify** [Expensify/App#5205]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to Settings -> Payments
2. See that you have imported cards, not billing cards

## Expected Result:
1. You should see billing cards

## Actual Result:
1. We are showing imported cards, not billing cards

## Workaround:
None

## Platform:
All

**Version Number:** 1.0.96
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:**
**Issue reported by:** Cole
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1631304328179600

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by botify** [comment]
:hand: This PR was not deployed to staging yet because QA is ongoing. It will be automatically deployed to staging after the next production release.

**Comment by botify** [comment]
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/1230722409) to staging by @Beamanator in version: 1.0.97-1 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅

**Comment by botify** [comment]
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/1239072912) to production by @francoisl in version: 1.0.98-1 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅
