### ISSUE TITLE
HybridApp crashing in dev due to react-native-reanimated

### ISSUE THREAD

**Issue by Julesssss** [Expensify/App#52053]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

### Problem

HybridApp builds are broken currently on `main`, which will soon be deployed to staging. We believe [this PR](https://github.com/Expensify/App/pull/48772) broke the builds.

### Solution

We need to bump `react-native-reanimated` on App and then the HybridApp module.

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by war-in** [comment]
Hi 👋 I'm Marcin from Software Mansion and I'd like to work on this

**Comment by Julesssss** [comment]
PRs: 
- https://github.com/Expensify/App/pull/52051
- https://github.com/Expensify/Mobile-Expensify/pull/13272
