### ISSUE TITLE
iOS - Hybrid app-IOU emails-Subject of the email is "IOU" instead of "User A requests amount"

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#52068]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.57-0
**Reproducible in staging?:** N
**Reproducible in production?:** N
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5178822
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Open staging New Expensify Hybrid app.
2. As User A - Open any 1:1 chat and submit an expense.
3. As User B - Check the email.

## Expected Result:
User B received an email with the subject "[User A] requests [amount]"

## Actual Result:
User B received an email with the subject "IOU", which is confusing for the regular user, who may not know the abbreviation meaning

## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [x] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
![Bug6654954_1730771530288!IMG_3324](https://github.com/user-attachments/assets/82bd51ae-34ae-4502-a724-99e0d796657a)
  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by MitchExpensify** [comment]
Reproduced, is IOU the new expected behavior @trjExpensify ?

**Comment by trjExpensify** [comment]
> If this was caught on HybridApp, is this reproducible on New Expensify Standalone?: Y

This means it's not exclusive to HybridApp, so it's just a general bug. Let's remove Hybrid from the title. 

All that said, we're in the process of fixing the report submission emails - so I don't think we really need to do anything here. CC: @jasperhuangg

**Comment by MitchExpensify** [comment]
Do you agree we can close this, @jasperhuangg ?
