### ISSUE TITLE
[HOLD for payment 2024-11-14] [HOLD for payment 2024-11-13] Subscription Page - Add Payment Card doesn't accept Amex Cards 

### ISSUE THREAD

**Issue by trjExpensify** [Expensify/App#52079]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.55-10
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:** https://expensify.slack.com/archives/C07HPDRELLD/p1730831531905479
**Issue reported by:** @zsgreenwald 
**Slack conversation** (hyperlinked to channel name):

## Action Performed:
1. Go to Subscription
2. Click `Add payment card`
3. Enter a 15 digit Amex card number 
4. Blur the field 
5. Observe the frontend validation fail. 

## Expected Result:
Amex cards should be acceptable payment method. 

## Actual Result:
We're failing the validation [here](https://github.com/Expensify/App/blob/ef6203db7a2236a55c3f84061a803ca44437dd75/src/libs/ValidationUtils.ts#L17-L34)

## Workaround:
Use OldDot. 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @trjExpensify</details>

**Comment by luacmartins** [comment]
This was all internal. We can close the issue.
