### ISSUE TITLE
Web/Safari - History - Images are not displayed after navigating to the conversation while offline

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#52076]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.57
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5171771&group_by=cases:section_id&group_order=asc&group_id=306202
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. If you don't have a conversation with images - Navigate to a conversation and send an few images
2. Navigate to another conversation
3. Disable the internet connection
4. Navigate back to the conversation with the image
5. Verify the images are displayed in the conversation history

## Expected Result:
Images that have been previously loaded should display in the conversation history after navigating to the conversation while offline

## Actual Result:
Images that have been previously loaded are not displayed in the conversation history after navigating to the conversation while offline

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/5f98e75e-cf23-4863-9e69-440ec3fcadb8

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by CyberAndrii** [comment]
Tester likely has browser cache disabled, in which case I think this is the expected behavior

**Comment by johncschuster** [comment]
@lanitochka17 can you confirm if the browser cache is disabled when you are testing in offline mode?

**Comment by johncschuster** [comment]
@lanitochka17 bump!

**Comment by lanitochka17** [comment]
@johncschuster The browser cache is disabled

![Screenshot 2024-11-18 at 12 36 01 PM](https://github.com/user-attachments/assets/e71b0fd7-a89d-4f46-899e-c0b6f91fd4a6)

**Comment by johncschuster** [comment]
Thanks! It sounds like this behavior is expected then. I would suggest two tests, one with the browser cache enabled, and one with the browser cache disabled.

When the browser cache is `enabled`, I would expect the images to be visible when taking `step 4` in your repro steps above, but when the browser cache is `disabled`, I would expect the images to not be visible when taking `step 4` in your repro steps.

**Comment by CyberAndrii** [comment]
@lanitochka17 I think you meant to say that the cache is **_enabled_** as the "Disable Caches" checkbox is not checked in the screenshot.

Anyway, it seems that Safari always disables the cache when running in "Private Browsing Mode", even if "Disable Caches" is unchecked. I would suggest updating the test steps to say not to use private mode in Safari.

**Comment by johncschuster** [comment]
@lanitochka17 bump!

**Comment by johncschuster** [comment]
Asked in Slack to get cleared repro steps

**Comment by lanitochka17** [comment]
When the cache is disabled, it is reproducible.
 
![Screenshot 2024-11-22 at 9 55 38 AM](https://github.com/user-attachments/assets/fd0c5cdd-61cc-465d-a6c3-3a12d277a88b)

Now it's not reproducible with cache enabled

https://github.com/user-attachments/assets/51edeeca-8801-4bf3-a680-f6bbbd8ec5e1

**Comment by johncschuster** [comment]
Got it. Thanks! Ok so, this sound like expected behavior.
