### ISSUE TITLE
[$125] Dev: An error log appear when going to company Feed that have some assigned cards 

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#52070]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:** need reproduction
**Reproducible in production?:** need reproduction
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @DylanDylann 
**Slack conversation** (hyperlinked to channel name): [quality](https://applause-ts.slack.com/archives/C05LX9D6E07/p1730779015867719)

## Action Performed:
1. Assign a company card to employee
2. Open the company feed
## Expected Result:
No errors observed
## Actual Result:
An error log appears
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>
![Screenshot 2024-11-05 at 10 54 35](https://github.com/user-attachments/assets/9d11c113-28cf-4d0d-a6de-237df63d1355)
![Screenshot 2024-11-05 at 10 53 18](https://github.com/user-attachments/assets/e4f211bc-2176-4de6-977e-2fbf92283780)

  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021853888643970312147</li>
        <li>Upwork Job ID: 1853888643970312147</li>
        <li>Last Price Increase: 2024-11-05</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @alitoshmatov</details>

**Comment by mountiny** [comment]
@DylanDylann could you please retest as you originally reported this. Thanks!

**Comment by DylanDylann** [comment]
I just realized that this bug only happens if we use mock data (with some wrong information). From the client side, this bug has never happened. I also checked all above proposals and they are invalid

@mountiny Let's close this one

**Comment by mountiny** [comment]
Closing this per the above comment as not a real user scenario
