### ISSUE TITLE
[HOLD for payment 2024-11-14] [$250] Android - Chat - App crashes when trying to split expense

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#52099]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.58-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Y
**Issue was found when executing this PR:** https://github.com/Expensify/App/pull/51849
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Open the Expensify app with Gmail account.
2. Open any group chat.
3. Tap on the "+" icon and select "Split Expense"
4. Verify you are able to complete with any amount.

## Expected Result:
User should be able to complete the split expense flow properly in any group chat.

## Actual Result:
App crashes when opening a group chat and starting the split expense flow.

## Workaround:
Unknown

## Platforms:

- [x] Android: Standalone
- [x] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
[0611.txt](https://github.com/user-attachments/files/17645702/0611.txt)

https://github.com/user-attachments/assets/85421976-d7dc-4874-af17-c5ec9433cfbc

 
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021854131328155845207</li>
        <li>Upwork Job ID: 1854131328155845207</li>
        <li>Last Price Increase: 2024-11-06</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @twisterdotcom</details>

**Comment by IuliiaHerets** [comment]
This issue is repro only with Gmail account

**Comment by mountiny** [comment]
Looking for the offending pr for $50

**Comment by kavimuru** [comment]
Fixed 

https://github.com/user-attachments/assets/8e2c64f8-d753-49ee-9e83-d13309dcbe53

**Comment by mountiny** [comment]
Ah good point, thanks for raising. We discussed this at the same time  in Slack where C+ helped to identify it too and seems like I created the revert PR https://github.com/Expensify/App/pull/52112 before your comment (looking at the timestamps) so while I appreciate your help I think I would not issue a reward at this case since we managed to find the offending PR before your comment
