### ISSUE TITLE
[Performance] Re-rendering whole form on every key stroke

### ISSUE THREAD

**Issue by aldo-expensify** [Expensify/App#5209]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## What performance issue do we need to solve?

`BaseExpensiTextInput`'s `setValue` method calls `Str.result(this.props.onChangeText, value);` ([here](https://github.com/Expensify/App/blob/main/src/components/ExpensiTextInput/BaseExpensiTextInput.js#L69)) on every change on the input (every key we press).

This causes that the component storing the values of the forms gets re-rendered on every key stroke, including descendants. This can be expensive in forms with many inputs, like the "Company Step" when adding a new withdrawal account.

https://user-images.githubusercontent.com/87341702/132925532-06564fd1-b27d-4d84-b233-3a86e119ea2e.mov

## What is the impact of this on end-users?
There is a perceptible delay when typing in a text input in the "Company Step" form.
 
## List any benchmarks that show the severity of the issue
For now, just typing fast in a field should show easily a delay

## Proposed solution (if any)
Keep a local state for the value in the `BaseExpensiTextInput` and debounce the update of the value in the state of the component containing all values of the form. This should make the form component re-render much less, only re-rendering the `BaseExpensiTextInput` component, improving performance.

## List any benchmarks after implementing the changes to show impacts of the proposed solution (if any)
There should be less perceptible delay when typing?

## Platform:
Where is this issue occurring?

- [x] Web
- [x] iOS
- [x] Android
- [x] Desktop App
- [x] Mobile Web

**Version Number:**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:**

[View all open jobs on Upwork](https://www.upwork.com/ab/jobs/search/?q=Expensify%20React%20Native&sort=recency&user_location_match=2)

**Comment by ammar-yasir** [comment]
This is a real issue and should be fixed immediately for the sake of performance.

**Comment by aldo-expensify** [comment]
Not overdue, this is low priority.

**Comment by aldo-expensify** [comment]
Not overdue, not a priority.

**Comment by aldo-expensify** [comment]
Not overdue, not a priority. With the new design doc and the usage of uncontrolled inputs, this shouldn't be an issue.
