### ISSUE TITLE
[HOLD for payment 2024-12-03] [hold] Web - Concierge - Take a 2-minute tour task not autocomplete after finishing tour

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#52098]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.58.0
**Reproducible in staging?:** Y
**Reproducible in production?:** N/A - new feature, doesn't exist in prod
**Issue was found when executing this PR:** https://github.com/Expensify/App/pull/51153
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/ and log in with a new account
2. On the onboarding modal select any option other than 'Something else"
3. Complete the onboarding flow
4. Navigate to the Concierge chat
5. Select the Take a 2-minute tour task
6. Click on the link and finish the tour

## Expected Result:
The task is marked complete automatically upon finishing the tour like other Concierge tasks

## Actual Result:
The "Take a 2-minute tour" task is not marked complete automatically

## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/a25c96b3-1f0b-47c7-9a02-aa39928ecc07

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @OfstadC</details>

**Comment by c3024** [comment]
#51153 is related to this.

**Comment by lakchote** [comment]
I do agree that it's not a blocker and that it should be handled on the backend for the reasons mentioned above by @c3024.

Waiting for your input @mountiny too

**Comment by mountiny** [comment]
@c3024 @rushatgabhane should be assigned and we should mark this optimistically as completed and call the SelfTourViewed command and update the BE to mark the task as complete too

**Comment by lakchote** [comment]
Didn't have time to focus on it internally as I'm focusing on a #stability [issue](https://github.com/Expensify/Auth/pull/13089). 

@c3024 you can still raise a frontend PR to set this optimistically in the meantime (see @mountiny's [comment](https://github.com/Expensify/App/issues/52098#issuecomment-2460283737) above).

**Comment by lakchote** [comment]
If you could do it today that'd be great @rushatgabhane

**Comment by c3024** [comment]
Raised a [PR](https://github.com/Expensify/App/pull/52617).

**Comment by OfstadC** [comment]
@rushatgabhane @c3024 Please complete thee BZ checklist by EOD so we can issue payment tomorrow

**Comment by OfstadC** [comment]
@c3024 Offer sent [here](https://www.upwork.com/nx/wm/offer/105180777)

**Comment by OfstadC** [comment]
Ooop didn't mean to close this. Still need @c3024 to accept Upwork Offer

**Comment by OfstadC** [comment]
@c3024 Could you please accept the offer so we can close this GH out? 😃 Thanks so much!

**Comment by c3024** [comment]
@OfstadC , sorry for the delayed response. This is part of a project and payment is handled [here](https://github.com/Expensify/App/issues/52098). No payment in this issue. Thanks!

**Comment by OfstadC** [comment]
Ah okay! Thanks for letting me know. I will not issue payment here then 😃
