### ISSUE TITLE
Debug - "Clicking on View button leads to not here page when opening invalid URL

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#52104]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.58-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Can't check as no Debug Mode on prod
**Issue was found when executing this PR:** https://github.com/Expensify/App/pull/51425
**Email or phone of affected tester (no customers):** applausetester+shsb22sc2@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
Prerequisite
Enable Debug Mode in troubleshooting
1. Open a report that doesn't exist from the URL (e.g. r/123456)
2. The view above the bottom navigation bar will show up a message saying "There's a report with errors"
3. Click on "View" button

## Expected Result:
Clicking on "View" button opens the RHP with the debug report page

## Actual Result:
Clicking on "View" tab leads to not here page

## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/1d7c406d-5d46-4d10-80f4-a34f443b48b2

 
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by pac-guerreiro** [comment]
@IuliiaHerets thanks for reporting this! This is a known issue that will be resolved when this [PR](https://github.com/Expensify/App/pull/51675) gets merged 😄

CC @puneetlath @DylanDylann

**Comment by puneetlath** [comment]
Makes sense. Gonna close this.
