### ISSUE TITLE
Implement Android edge-to-edge mode

### ISSUE THREAD

**Issue by Julesssss** [Expensify/App#52116]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

P/S was shared [here](https://expensify.slack.com/archives/C05LX9D6E07/p1730885163855239) by @kirillzyusko 

### Problem:

The android navigation bars (bottom and top) can have a different color than the background color of the app. This happens when the app theme switches (due to change in system appearance), or when the splashscreen hides.

### Solution

Trying to fix the existing code with asynchronous updates is hard, as it's almost impossible to perfectly time the update from JS to the UI thread. A 100% reliable approach would be to enable `edge-to-edge` mode on Android. It'll brings several advantages, such as:
- such mode fully matches iOS behavior in terms of insets handling -> by default content will be drawn under system bars and if we want we can apply padding/fill the area with background color and do whatever we want. Since we'll have the same mode on both platforms it helps us to reduce code fragmentation, make code consistent and truly crossplatform.
- since insets handling will not work on Android anymore, it gives us a flexibility in terms of keyboard handling. By default Android handles keyboard appearance out of the box, but such keyboard handling is quite limited, it doesn't have smooth animations etc. When we get a control of keyboard management we can utilize cross-platform behavior.
- `edge-to-edge` mode is enabled by default on Android 15 (there is still a way to disable it if the app is not ready to edge-to-edge` mode), but in future Android versions this approach may be totally disabled: https://developer.android.com/about/versions/15/behavior-changes-15#edge-to-edge.
- Expo (starting from SDK 52) will turn on edge-to-edge mode by default: https://expo.dev/changelog/2024/10-24-sdk-52-beta#highlights;
- After Expo SDK 52 RN team will see how adoptation is going on and if they will see, that ecosystem and community is ready for this step they will enable `edge-to-edge` by default as well: https://github.com/react-native-community/discussions-and-proposals/discussions/827.

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kirillzyusko** [comment]
Kiryl from Margelo expert agency is here 👋 

As discussed [here](https://margelo.slack.com/archives/C05LX9D6E07/p1730885163855239) I'd like to take care of that 🙌

**Comment by zoontek** [comment]
👋 I can do it. I'm the author of [react-native-edge-to-edge](https://github.com/zoontek/react-native-edge-to-edge), knows the subject perfectly.

**Comment by kirillzyusko** [comment]
@MelvinBot not overdue, I'm planning to start working on it today 👀
