### ISSUE TITLE
Copilot-No error message after entering the wrong code multiple times

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#52118]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.58
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Issue was found when executing this PR:** https://github.com/Expensify/App/pull/51588
**Issue reported by:** Applause Internal Team

## Action Performed:
Add copilot
1. Go to settings > security
2. Add copilot
3. Enter wrong code multiple times
4. Verify you see error like "too many attempts"

Update copilot role
1. Go to settings > security
2. Click a copilot > update role
3. Enter wrong code multiple times
4. Verify you see error like "too many attempts"

## Expected Result:
An error like "too many attempts" is displayed after entering the wrong code multiple times.

## Actual Result:
The "too many attempts" error message is not displayed after entering the wrong code multiple times.

## Workaround:
Unknown

## Platforms:

- [x] Android: Standalone
- [x] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/d0d6816c-518f-4cf1-9508-4d9d97ea2ca2

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by bfitzexpensify** [comment]
cc @rushatgabhane @Ollyws @dangrous - looks like this came from https://github.com/Expensify/App/pull/51588. Can you please review?

**Comment by dangrous** [comment]
I am checking with the team on some backend behavior here, stay tuned!

**Comment by dangrous** [comment]
okay so short version, the "too many attempts" will only be encountered on successful calls - we don't throttle for incorrect codes, etc.

**Comment by dangrous** [comment]
I think that means we can close this?
