### ISSUE TITLE
Search - App crashes after deleting track expense in Search

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#52129]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.58-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+kh2610010@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to self DM
3. Track a manual expense
4. Go to Search
5. Select the track expense via checkbox
6. Click on the dropdown > Delete expense
7. Delete the expense

## Expected Result:
App will not crash

## Actual Result:
App crashes after deleting track expense in Search

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Standalone
- [x] Android: HybridApp
- [x] Android: mWeb Chrome
- [x] iOS: Standalone
- [x] iOS: HybridApp
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/0d106e5d-98ca-46ec-8467-570caad5ee98

[logs (2).txt](https://github.com/user-attachments/files/17650764/logs.2.txt)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by nkdengineer** [comment]
It's a BE bug


Backend returns in `DeleteMoneyRequestOnSearch` API a report with a value is `6`


<img width="1512" alt="Screenshot 2024-11-07 at 00 31 59" src="https://github.com/user-attachments/assets/2e5b6fc3-c5e5-4f22-8d2e-8865764a314f">


Then the app crashes here
https://github.com/Expensify/App/blob/99802996a734b01bae3437d201f8e79e27223cf7/src/libs/ReportUtils.ts#L2721

**Comment by mjasikowski** [comment]
I'll take this

**Comment by mjasikowski** [comment]
@lanitochka17 can you please re-test this? I tried to reproduce in dev, staging and production on web and desktop and I failed to do so on multiple accounts. Maybe it has magically fixed itself.

**Comment by lanitochka17** [comment]
Issue is not reproducible on the latest build 9.0.62-3

https://github.com/user-attachments/assets/83798093-0e6a-4529-ae0c-3dc3f8341687

**Comment by mjasikowski** [comment]
Thanks, so let's close this as fixed.
