### ISSUE TITLE
[$250] Add a button in workspace settings that brings the user to their workspace chat for that workspace

### ISSUE THREAD

**Issue by jamesdeanexpensify** [Expensify/App#52136]
**Slack convo**
https://expensify.slack.com/archives/C06ML6X0W9L/p1730747317025379

**Problem**
There have been many instances of users clicking into their workspace settings looking for where or how to submit their expenses ([example](https://expensify.slack.com/archives/C07HPDRELLD/p1730759073701999), [example](https://expensify.slack.com/archives/C07NMDKEFMH/p1730380892061729), [example](https://expensify.slack.com/archives/C07NMDKEFMH/p1730237878973379?thread_ts=1730234218.103439&cid=C07NMDKEFMH)). They ultimately get confused and are unable to submit anything. This is not a great product experience.

**Solution**
Add a [very clear and obvious button](https://expensify.slack.com/archives/C07NMDKEFMH/p1730452087961259?thread_ts=1730380892.061729&cid=C07NMDKEFMH) in workspace settings that takes the user directly to their workspace chat to submit expenses. It should look like this: 

![image](https://github.com/user-attachments/assets/e9e66038-3de7-488f-85fa-22c906c5225b)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021854243925904217172</li>
        <li>Upwork Job ID: 1854243925904217172</li>
        <li>Last Price Increase: 2024-11-06</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @s77rt</details>

**Comment by nkdengineer** [comment]
@jamesdeanexpensify I think it's dupe of https://github.com/Expensify/App/issues/52136

**Comment by jamesdeanexpensify** [comment]
@nkdengineer your link takes me to this issue - did you mean to link a different one?

**Comment by nkdengineer** [comment]
@jamesdeanexpensify  Oh sorry the other issues [here](https://github.com/Expensify/App/issues/51851#issuecomment-2460401711)

**Comment by jamesdeanexpensify** [comment]
Oh wow, I had no idea. Will close this one out!

**Comment by s77rt** [comment]
Interesting that I got assigned in both 😁
