### ISSUE TITLE
[HOLD for payment 2024-11-21] QBD - Admin is not selected as default Preferred exporter after connecting to QBD

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#52134]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.58-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5184323
**Email or phone of affected tester (no customers):** applausetester+dqbd7@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition: Have a workspace connected to QBD
1. Navigate to Workspace > Accounting
2. Click on Export
3. Click Preferred exporter

## Expected Result:
Admin is selected as default Preferred exporter after connecting to QBD

## Actual Result:
Admin(owner) is not selected as default Preferred exporter after connecting to QBD

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/1084f55d-46de-4aa8-a17e-68c5c4d687c7

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021854584654634877527</li>
        <li>Upwork Job ID: 1854584654634877527</li>
        <li>Last Price Increase: 2024-11-07</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @garrettmknight</details>

**Comment by lakchote** [comment]
@hoangzinh I don't think there is a problem at all. And I do agree that if there ever was, we should instead fix it in the backend and not the frontend.

QBD integration backend logic hasn't changed regarding the preferred exporter and it works fine on OldDot.

cc @francoisl for your input.

**Comment by lakchote** [comment]
Not overdue, see my comment above.

**Comment by lakchote** [comment]
@hoangzinh thanks for testing it out in OldDot. I had trouble connecting to QBD this morning (Web connector screen stuck).

Let's do @ZhenjaHorbach's solution then? 

It wouldn't be eligible for payment though, as @ZhenjaHorbach you were the one in charge of handling the feature in https://github.com/Expensify/App/pull/50297 and it could be considered as a regression from OldDot.
