### ISSUE TITLE
mWeb - Compose Box - Deleting emoji causes the next text input to be bigger

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#52143]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.56-7
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** bobdrakeforstuff+04112024@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Open a conversation
3. Type ":he" (or other text to trigger emoji suggestion)
4. Tap on an emoji
5. Tap backspace twice so that the emoji is deleted
6. Enter a text

## Expected Result:
The text is displayed in normal size

## Actual Result:
The text is displayed with bigger size than usual

## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

![Bug6654174_1730717417423!Big_text](https://github.com/user-attachments/assets/13d24425-4200-460d-a002-3de278b50612)

https://github.com/user-attachments/assets/613295a8-cbe6-4f97-ac88-2be847bb695d

  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by jacobkim9881** [comment]
Not reproducible

**Comment by RachCHopkins** [comment]
Not reproducible for me either! Closing.
