### ISSUE TITLE
mWeb/Safari - New contact - The new contact method verify page auto refresh

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#52145]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.56-7
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** spica8922@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Open URL https://staging.new.expensify.com/
2. Click on the settings > Profile > Contact Method
3. Tap on new contact method.
4. Enter the email.
5. Tap Add.
6. Open email when receiving new code and copy it.
7. Switch to verify page.
## Expected Result:
The new contact method verify page should appear to the user can paste code and verify.

## Actual Result:
The new contact method verify page auto refresh and the user must re-enter email. Beside, sometime it auto refesh in the enter the email page.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/50ddbcb2-ad94-4829-8858-03dd6ef7cd65

 
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by alexpensify** [comment]
Heads up, I will be offline until Tuesday, November 12, 2024, and will not actively watch over this GitHub during that period.

If this GitHub requires an urgent update, please ask for help in the #expensify-open-source Slack Room. If it can wait, I'll continue the review process when I return online. Thanks!

**Comment by alexpensify** [comment]
I'm back and moving this one to daily. I'll test soon.

**Comment by alexpensify** [comment]
Still on my radar

**Comment by alexpensify** [comment]
Still on my test list

**Comment by alexpensify** [comment]
I didn't get to test this one before going OOO. This week, I'll try to log in to confirm the next steps.

**Comment by alexpensify** [comment]
No update

**Comment by alexpensify** [comment]
Closing - I've been unable to replicate 

![2024-12-02_20-35-27](https://github.com/user-attachments/assets/23d24bda-99e6-4994-9a51-9ef3c889f94f)
