### ISSUE TITLE
Expensify Card institution icon looks bland compared to others

### ISSUE THREAD

**Issue by puneetlath** [Expensify/App#5215]
## Action Performed:
Break down in numbered steps
1. Go to Settings > Payments in an account that has an Expensify Card and is importing other cards
2. Look at the list of Payment methods

## Expected Result:
The Expensify "institution" icon should look on par with other institutions like Chase and Bank of America. Given that we aren't showing an icon of a card for other banks, but rather the icon shown is the institution's logo, I would think we should use the Expensify logo since that is the institution issuing the card. Here's what it would look like if we did: 

![image](https://user-images.githubusercontent.com/1371996/133004531-7e0fa197-ab69-4b96-ba12-1c0db77f3ebf.png)

## Actual Result:
The icon next to the Expensify Card looks bland and not like an actual institution. 

![image](https://user-images.githubusercontent.com/1371996/133003955-602a62db-9919-4487-89b0-7ead05d460c9.png)

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** v1.0.97-0

@Expensify/design curious what you think.

**Comment by michelle-thompson** [comment]
Yeah, I agree that this would be a positive change!

**Comment by puneetlath** [comment]
Cool, I'll do that then.

**Comment by botify** [comment]
:hand: This PR was not deployed to staging yet because QA is ongoing. It will be automatically deployed to staging after the next production release.
