### ISSUE TITLE
Offline comments in a thread room result in missing post and 'Access Denied' error upon reconnection

### ISSUE THREAD

**Issue by brunovjk** [Expensify/App#52179]
**Original GH:** https://github.com/Expensify/App/issues/47708

## Action Performed:
1. Create a room that User A, User B, and User C are in.
2. Post a comment as User A.
3. Have User B go offline.
4. Have User C create a thread on User A’s comment.
5. While offline, have User B also create a thread on User A’s comment.
6. Both User B and User C send messages in the thread.
7. Bring User B back online.

## Expected Result:
User B's and User C’s comments post in User A’s thread without any issues, and the Left-Hand Navigation updates accordingly.

## Actual Result:
- User C's comment posts successfully, and the LHN updates as expected.
- For User A, there are no errors or duplicate reports, and only User C’s comment appears. User B’s comment is missing.
- When User B comes back online, their offline message is displayed in a disabled state with the error: _"You don't have access to this chat room."_

One response from the `AddComment` request after User B reconnects:
```
{
    "code": 666,
    "jsonCode": 666,
    "type": "Expensify\\Libs\\Error\\ExpError",
    "UUID": "E490CD6D-46BF-4EE2-8B4F-51672557284A",
    "message": "You don't have access to this chat room.",
    "title": "Room not accessible",
    "data": {
        "onyxData": [
            {
                "onyxMethod": "merge",
                "key": "reportActions_4167634506996915",
                "value": {
                    "8205893435296449884": {
                        "errors": {
                            "1729771507600209": "You don't have access to this chat room."
                        }
                    }
                }
            }
        ]
    },
    "htmlMessage": "",
    "onyxData": [
        {
            "onyxMethod": "merge",
            "key": "reportActions_4167634506996915",
            "value": {
                "8205893435296449884": {
                    "errors": {
                        "1729771507600209": "You don't have access to this chat room."
                    }
                }
            }
        }
    ],
    "requestID": "8d79d54f68183565-CNF"
}
```

## Screenshots/Videos

![image](https://github.com/user-attachments/assets/73606330-d68c-4f31-bc71-e7a110ed73db)

cc: @AndrewGable

<details><summary>Issue Owner</summary>Current Issue Owner: @marcochavezf</details>

**Comment by marcochavezf** [comment]
No update, I will look at this one this week

**Comment by johncschuster** [comment]
@marcochavezf how's this one going?

**Comment by mallenexpensify** [comment]
@marcochavezf when you need a review, can you add the `Bug` label to assign a C+?  (if applicable)

**Comment by marcochavezf** [comment]
> how's this one going?

No update on this one yet, I've been prioritizing a #retain issue. Hopefully tomorrow I can prioritize it again

**Comment by marcochavezf** [comment]
> when you need a review, can you add the Bug label to assign a C+? (if applicable)

Sure

**Comment by brunovjk** [comment]
I can't reproduce today (28 Nov):
<details>
<summary>new.expensify.com</summary>



https://github.com/user-attachments/assets/b7ea0fd5-cb25-4d26-8963-6da5cf841e72


</details>

<details>
<summary>dev - v9.0.67-9</summary>



https://github.com/user-attachments/assets/55c7d75a-c23f-414b-853b-587895441c3b


</details>

**Comment by marcochavezf** [comment]
Oh cool, it was potentially fixed as a side effect of another fix. I'm going to close it out for now, but feel free to re-open it
