### ISSUE TITLE
[HOLD for payment 2024-11-21] QAB - Scan QAB is not displayed for offline created workspace

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#52186]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.59-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N/A - new feature, doesn't exist in prod
**Issue was found when executing this PR:** https://github.com/Expensify/App/pull/51836
**Email or phone of affected tester (no customers):** expensify416+da2@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Sign up with a new account
2. Apply offline network
3. Create a workspace
4. Click on FAB
5. Apply online network

## Expected Result:
On step 4, a Scan receipt QAB should be displayed pointing to the newly created workspace

## Actual Result:
There is no Scan receipt QAB

## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/64a331f3-2413-4c57-a287-3311ece8a870

  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @OfstadC</details>

**Comment by mountiny** [comment]
As per the op, this is a new feature and its not broken to the user so demoting - not a blocker

**Comment by mountiny** [comment]
@ishpaul777 @dukenv0307 @puneetlath can you have a look please?

**Comment by puneetlath** [comment]
@ishpaul777 I'm guessing this is because we don't yet have the workspace chat reportID, right? Because we don't create it optimistically and so we have to wait for the back-end to return it? If so, I feel like it's not really a bug and the behavior is fine as-is.

**Comment by puneetlath** [comment]
Oh cool, I like that. That makes sense to me.

**Comment by mountiny** [comment]
@ishpaul777 yeah that sounds good, if its your first group policy, set it as active. Can you put up a PR for it please as a follow up

**Comment by OfstadC** [comment]
We'll need the checklist to be completed before I can issue payment tomorrow. Thanks!

**Comment by OfstadC** [comment]
@dukenv0307 could you please complete the BZ checklist so we can issue payment here? Thank you!

**Comment by OfstadC** [comment]
Or - actually I think @ishpaul777 would be responsible for the BZ checklist 😅 Sorry about that!

**Comment by OfstadC** [comment]
[Regression Test Issue](https://github.com/Expensify/Expensify/issues/447051)

**Comment by OfstadC** [comment]
Thanks @ishpaul777 - I'll hold payment here until @puneetlath weighs in. I believe they are out today -- so if you prefer, I can raise a Slack discussion to decide on payment sooner if you'd like? 

I can confirm [Payment Summary ](https://github.com/Expensify/App/issues/52186#issuecomment-2490436345)for @dukenv0307 is accurate.

**Comment by puneetlath** [comment]
I don't think it's a regression. It wasn't part of the scope for the original, so I think we should pay everyone out on this one.

**Comment by OfstadC** [comment]
@ishpaul777 [Offer sent ](https://www.upwork.com/nx/wm/offer/105027480)

**Comment by JmillsExpensify** [comment]
$250 approved for @dukenv0307

**Comment by OfstadC** [comment]
Updated Payment Summary - All set here 😃 

Thanks everyone!
