### ISSUE TITLE
[HOLD for payment 2024-11-20] [$250] Search - Unable to select expenses by tapping and holding

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#52202]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.59-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5193391
**Issue reported by:** Applause Internal Team

## Action Performed:
Preconditions: User with existing expenses
1. Log in with user from preconditions
2. Tap on Search in the bottom
3. Tap and hold an expense

## Expected Result:
Select option should be displayed in the bottom.

## Actual Result:
Nothing happens when tapping and holding an expense, user is unable to select expenses in search.

## Workaround:
Unknown

## Platforms:

- [x] Android: Standalone
- [x] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/8fad6815-49b5-4704-a816-bb7fb12b4cbf

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021854876478688351316</li>
        <li>Upwork Job ID: 1854876478688351316</li>
        <li>Last Price Increase: 2024-11-23</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @adelekennedy</details>

**Comment by Julesssss** [comment]
Hey @tylerkaraszewski, I have made this external to get more eyes on this deploy blocker.

**Comment by FitseTLT** [comment]
Looking into this 👀

**Comment by FitseTLT** [comment]
Will prepare a fix shortly

**Comment by FitseTLT** [comment]
[PR](https://github.com/Expensify/App/pull/52278) fixing the regression is raised.

**Comment by Julesssss** [comment]
@Krishna2323 I think a 'regression located bounty' is reasonable here. I commented on [the payment issue](https://github.com/Expensify/App/issues/50851#issuecomment-2470941336). Let me know if you disagree with this being reasonable.

**Comment by c3024** [comment]
@Julesssss , I reviewed this PR though I was not the C+ of the original PR because of urgency based on the Slack [thread](https://expensify.slack.com/archives/C02NK2DQWUX/p1731283549709539) by @mountiny .

I think this issue is right place to handle the payment for this. Can this be opened now for handling payment for me after the regression period is complete?

**Comment by mountiny** [comment]
Yep I think that is reasonable, thanks for help urgently addressing this PR review https://github.com/Expensify/App/pull/52278

**Comment by adelekennedy** [comment]
thank you @mountiny 

PR deployed to prod [yesterday](https://github.com/Expensify/App/pull/52278#issuecomment-2468773348) - payment due on the 18th 

Payouts due:

- [ ] $250 @c3024

**Comment by Julesssss** [comment]
> @Julesssss, I respectfully disagree. I've identified the offending PR and also provided a solution, so I believe the payout should be $125, as I haven't opened a PR myself.

Okay I agree. These regression fix cases are a bit blurry because solutions can be similar, but I am happy to suggest $125 [here](https://github.com/Expensify/App/issues/50851#issuecomment-2473100239).

**Comment by c3024** [comment]
@adelekennedy 

I think [this](https://github.com/Expensify/App/issues/52202#issuecomment-2471262291) is the only payment due here given that other payments were handled elsewhere.

**Comment by adelekennedy** [comment]
@c3024 will you apply to the job? https://www.upwork.com/jobs/~021854876478688351316

**Comment by c3024** [comment]
@adelekennedy , applied. Thanks!

**Comment by adelekennedy** [comment]
Sent!

**Comment by c3024** [comment]
Accepted!
