### ISSUE TITLE
mWeb - Workspace - After enabling all features, unable to enable tax option

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#52203]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.49-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/home
2. Tap fab - new workspace
3. Tap more features
4. Enable all features and try to enable "taxes" at last

## Expected Result:
After enabling all features, must be able to enable tax option

## Actual Result:
After enabling all features, unable to enable tax option

## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/07d740cd-04ef-49f1-81f9-c51be205a17d

 </details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by rlinoz** [comment]
```
	"Expensify\\Policy\\CustomUnit::setAttributes(): Argument #1 ($attributes) must be of type array, string given, called in /git/releases/expensify.com/4d4af21/lib/Policy/CustomUnit.php on line 93"
```

**Comment by rlinoz** [comment]
I think this is related to per diem

**Comment by rlinoz** [comment]
Which is behind a beta, so I think we don't need to block on this one.

**Comment by rlinoz** [comment]
@Gonals based on the error above, I think this line https://github.com/Expensify/Auth/blob/ab20754697d76a3840c4653a1890e158c423a229/auth/command/TogglePolicyPerDiem.cpp#L54 might have to be an empty object instead?

**Comment by rlinoz** [comment]
This is not reproducible anymore, so I am going to close it.
