### ISSUE TITLE
Chat-The "edited" text disappears when go online

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#52215]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 4.0.59-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Launch app
2. Open a chat
3. Go offline
4. Send a message
5. Long press the message sent and edit the message by adding additional text & save it
6. Note edited text is displayed next to message
7. Go online

## Expected Result:
The "edited" text must not disappear when go online

## Actual Result:
The "edited" text disappears when go online

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [x] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/1d46c723-5dfd-4b36-9a14-45ed66f12a56

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mkzie2** [comment]
Expected: https://github.com/Expensify/App/pull/51422#issuecomment-2445056866.

**Comment by garrettmknight** [comment]
Agreed, closing.
