### ISSUE TITLE
 Unable to submit distance expense to workspace when it is created from actionable whisper

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#52249]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.59-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Y
**Email or phone of affected tester (no customers):** applausetester+kh271000024@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to self DM.
3. Track a manual expense.
4. Click Categorize it from the actionable whisper.
5. Click New workspace (if there is existing workspace).
6. Select a category, enter merchant and submit it.
7. Go to workspace chat.
8. Submit a distance expense.

## Expected Result:
The distance expense is submitted successfully.

## Actual Result:
It shows error when submitting distance expense to a workspace that is created from the actionable whisper.
Error:
Unexpected error submitting this expense. Please try again later.
The selected rate has been deleted

## Workaround:
Unknown

## Platforms:

- [x] Android: Standalone
- [x] Android: HybridApp
- [x] Android: mWeb Chrome
- [x] iOS: Standalone
- [x] iOS: HybridApp
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
  
https://github.com/user-attachments/assets/c8bfc6b8-88b4-4590-88aa-436ed0a1abb2

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by FitseTLT** [comment]
This is a BE issue we are already dealing with it [here](https://github.com/Expensify/App/pull/52061#issuecomment-2460460437) Tagging @luacmartins

**Comment by kadiealexander** [comment]
@luacmartins should we close this as a dupe?

**Comment by luacmartins** [comment]
yea, we can close as a dupe.

**Comment by FitseTLT** [comment]
@luacmartins I am sorry but on a second thought I see that this is a different API `CATEGORIZE_TRACKED_EXPENSE` not o `ConvertTrackedExpenseToRequest` so don't forget to handle that and also `SHARE_TRACKED_EXPENSE` API.
