### ISSUE TITLE
[$125] Track- Description disappears when returning online after editing distance&description offline

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#52244]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.59-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Y
**Email or phone of affected tester (no customers):** applausetester+kh2710000@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to self DM.
3. Track a distance expense without description.
4. Go to transaction thread.
5. Go offline.
6. Click distance.
7. Edit the distance and save it.
8. Click Description.
9. Enter description and save it.
10. Go online.

## Expected Result:
Description will not disappear when returning online after editing distance first, then description in offline mode.

## Actual Result:
Description disappears when returning online after editing distance first, then description in offline mode.

## Workaround:
Unknown

## Platforms:

- [x] Android: Standalone
- [x] Android: HybridApp
- [x] Android: mWeb Chrome
- [x] iOS: Standalone
- [x] iOS: HybridApp
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/d75e9449-03dd-4dbc-bda6-2285a4fee6ca
  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021854955416970949942</li>
        <li>Upwork Job ID: 1854955416970949942</li>
        <li>Last Price Increase: 2024-11-08</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @akinwale</details>

**Comment by adelekennedy** [comment]
I think this is worth the polish but is a bit of an edge case with the amount of offline activity - reducing the price

**Comment by ikevin127** [comment]
Not reproducible on latest dev / staging (v9.0.59-0), here's a video with the exact steps from issue's description:

https://github.com/user-attachments/assets/236c852e-8e36-433d-a795-b153e355eceb

Networking calls:

First call `UpdateMoneyRequestDistance` Response:

```json
        {
            "key": "transactions_6598055347393571074",
            "onyxMethod": "merge",
            "value": {
                "amount": 853,
                "bank": "",
                "billable": false,
                "cardID": 0,
                "cardName": "Cash Expense",
                "cardNumber": "",
                "category": "",
                "comment": {
                    "comment": "", <- Expected as we're only changing Distance
```

Second call `UpdateMoneyRequestDescription` Response:

```json
        {
            "key": "transactions_6598055347393571074",
            "onyxMethod": "merge",
            "value": {
                "amount": 853,
                "bank": "",
                "billable": false,
                "cardID": 0,
                "cardName": "Cash Expense",
                "cardNumber": "",
                "category": "",
                "comment": {
                    "comment": "text", <- Expected as we're only changing Description
```

**Comment by ikevin127** [comment]
Wasn't able to reproduce, more details in https://github.com/Expensify/App/issues/52244#issuecomment-2465885017.

**Comment by adelekennedy** [comment]
closing!
