### ISSUE TITLE
Per diem - Error when submitting distance expense when Per diem is enabled

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#52245]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.59-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N/A - new feature, doesn't exist in prod
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Y
**Email or phone of affected tester (no customers):** applausetester+kh271000023@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Create a new workspace.
3. Go to workspace settings > More features.
4. Enable Per diem.
5. Upgrade the workspace to control.
6. Go to workspace chat.
7. Submit a distance expense.

## Expected Result:
The distance expense is submitted successfully.

## Actual Result:
Error when submitting distance expense when Per diem is enabled.

## Workaround:
Unknown

## Platforms:

- [x] Android: Standalone
- [x] Android: HybridApp
- [x] Android: mWeb Chrome
- [x] iOS: Standalone
- [x] iOS: HybridApp
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/38410da6-ed1a-4376-b430-295104217cf8

 
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by MariaHCD** [comment]
Looking at the logs for CreateDistanceRequest for applausetester+kh271000023@applause.expensifail.com

https://www.expensify.com/_devportal/tools/logSearch/#query=request_id:(%228df4e13a9a52e2f2-HKG%22)+AND+timestamp:[2024-11-08T09:29:03.899Z+TO+2024-11-08T11:29:03.899Z]&index=logs_expensify-031109

Looks like the request succeeded.

**Comment by MariaHCD** [comment]
```
8df4d97abbb1e2f2-HKG	staging-www1.rno	2024-11-08 10:23:46 561	applausetester+kh271000023@applause.expensifail.com	[OOPS!] API threw TypeError - 250906d6a267ef9efe4431bb6ef9f000 ~~ exceptionMessage: 'Expensify\Policy\CustomUnit::setAttributes(): Argument #1 ($attributes) must be of type array, string given, called in /git/releases/expensify.com/4d4af21/lib/Policy/CustomUnit.php on line 93' exceptionFile: '/git/releases/expensify.com/4d4af21/lib/Policy/CustomUnit.php' exceptionLine: '191' exceptionCode: '0'
```

https://www.expensify.com/_devportal/tools/logSearch/#query=request_id:(%228df4d97abbb1e2f2-HKG%22)+AND+timestamp:[2024-11-08T09:23:46.561Z+TO+2024-11-08T11:23:46.561Z]&index=logs_expensify-031109

**Comment by MariaHCD** [comment]
I also tested the flow on staging and got the error:

![Screenshot 2024-11-08 at 3 09 02 PM](https://github.com/user-attachments/assets/2ba018e9-ac65-437b-84a8-5a626b819760)

```
Expensify\\Policy\\CustomUnit::setAttributes(): Argument #1 ($attributes) must be of type array, string given, called in /git/releases/expensify.com/4d4af21/lib/Policy/CustomUnit.php on line 93
```

I believe this will be fixed once https://github.com/Expensify/Web-Expensify/pull/44307 is deployed.

**Comment by MariaHCD** [comment]
We could CP https://github.com/Expensify/Web-Expensify/pull/44307 but I think it's fine to wait until the next web deploy on Monday in light of DBSF

**Comment by Julesssss** [comment]
> Reproducible in production?: N/A - new feature, doesn't exist in prod

Removing the blocker label. It's a new feature that isn't a main flow and we have a fix awaiting deployment. 

I'm unsubscribing, please tag me if necessary here.

**Comment by MariaHCD** [comment]
https://github.com/Expensify/Web-Expensify/pull/44307 was deployed to staging.

@IuliiaHerets could you retest this on staging? Thanks!

**Comment by IuliiaHerets** [comment]
@MariaHCD Tester can't reproduce this issue in the latest build (9.0.60-0)

https://github.com/user-attachments/assets/cbeac005-e71b-474c-a7eb-59ad18c8e435

**Comment by MariaHCD** [comment]
Great, thanks for confirming! https://github.com/Expensify/Web-Expensify/pull/44307 should have fixed this. Closing!
