### ISSUE TITLE
[Payment 2024-11-18] [$250] Expense - Disabled category when selected is not highlighted

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#52259]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.59-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Y
**Email or phone of affected tester (no customers):** applausetester+kh271000026@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace chat.
3. Submit an expense with category.
4. Go to workspace settings > Categories.
5. Disable all the categories.
6. Go to workspace chat.
7. Go to the transaction thread (from Step 3).
8. Click Category.

## Expected Result:
The disabled category when selected should be highlighted (production behavior).

## Actual Result:
The disabled category when selected is not highlighted.

## Workaround:
Unknown

## Platforms:

- [x] Android: Standalone
- [x] Android: HybridApp
- [x] Android: mWeb Chrome
- [x] iOS: Standalone
- [x] iOS: HybridApp
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
https://github.com/user-attachments/assets/d219c77b-6a61-4b15-a0c0-bf1fb3174920
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021854920252783122362</li>
        <li>Upwork Job ID: 1854920252783122362</li>
        <li>Last Price Increase: 2024-11-08</li>
<li>Automatic offers: </li>
<ul>
<li>rayane-djouah | Contributor | 104839950</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @strepanier03</details>

**Comment by MuaazArshad** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Expense - Disabled category when selected is not highlighted
### What is the root cause of that problem?
We are getting undefined for the disabled category as we are checking for disabled first. 
https://github.com/Expensify/App/blob/346bb370add9c7225bec8b5b499a1aab93476dec/src/styles/utils/index.ts#L1122-L1136
### What changes do you think we should make in order to solve the problem?
We should check for selected before checking for disabled like this
```
if (isSelected) {
        backgroundColor = selectedBG;
    } else if (isFocused) {
        backgroundColor = focusedBG;
    } else if (isDisabled) {
        backgroundColor = undefined;
    }
```
or like this
```
if (isSelected) {
        backgroundColor = selectedBG;
    }  else if (isDisabled) {
        backgroundColor = undefined;
    } else if (isFocused) {
        backgroundColor = focusedBG;
    }
```


### What alternative solutions did you explore? (Optional)

**Comment by MuaazArshad** [comment]
This PR handled the case for disabled background color https://github.com/Expensify/App/pull/51988

**Comment by luacmartins** [comment]
@MuaazArshad please make sure that your proposal doesn't break [this case](https://github.com/Expensify/App/issues/51984)

**Comment by MuaazArshad** [comment]
My proposal's alternative doesn't break the given case.

**Comment by luacmartins** [comment]
@MuaazArshad are you available to work on the PR now?

**Comment by MuaazArshad** [comment]
Yes

**Comment by MuaazArshad** [comment]
PR is ready for review

**Comment by strepanier03** [comment]
@rayane-djouah - Thanks for the checklist! I've paid and closed the contract for you in Upwork. 

@MuaazArshad - I have sent you an offer, I'll check again later today to see if I can pay it.

**Comment by MuaazArshad** [comment]
Thank you. I have accepted the offer.

**Comment by strepanier03** [comment]
Thanks @MuaazArshad - I've paid and closed your contract. 👋
