### ISSUE TITLE
[Workspace Feeds] RemoveFeed command fails

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#52252]
### Problem
Coming from [here](https://expensify.slack.com/archives/C06ML6X0W9L/p1731054379043849?thread_ts=1729596921.819569&cid=C06ML6X0W9L)

When removing the company card feed, the RemoveFeed command fails with `404 Bank feed does not exist`

### Solution

Investigate why this is happening

**Comment by mountiny** [comment]
Here are some logs https://www.expensify.com/_devportal/tools/logSearch/#sort=asc&size=10000&query=request_id%3A%228df583fe0b723bc4-WAW%22%20AND%20timestamp%3A%5B2024-11-08T00%3A00%20TO%202024-11-09T23%3A59%5D

**Comment by mountiny** [comment]
This is failing because the feed is pending so there is no CompanyID NVP for the feed. Gonna have to update that.

then the next thing is that the RemoveFeed command is not removing the feed from the comapnyCards settings in domain_member and it should

**Comment by mountiny** [comment]
Working on this one

**Comment by mountiny** [comment]
PR in review

**Comment by mountiny** [comment]
Merged

**Comment by mountiny** [comment]
Created one more follow up

**Comment by joekaufmanexpensify** [comment]
Noting that I tested [here](https://expensify.slack.com/archives/C06ML6X0W9L/p1732116549221049?thread_ts=1732108983.281759&cid=C06ML6X0W9L) and it works well when there's only one feed. Still [not 100% right](https://expensify.slack.com/archives/C06ML6X0W9L/p1732116549221049?thread_ts=1732108983.281759&cid=C06ML6X0W9L) when there are multiple feeds though. 

LMK when this is ready to retest!

**Comment by mountiny** [comment]
@joekaufmanexpensify That is a frontend-only issue; the feed is removed, but we are not navigating/ showing another one upon deletion. It is handled here https://github.com/Expensify/App/pull/52893

Given the backend changes for this are done, I think we can close this issue

**Comment by joekaufmanexpensify** [comment]
Sweet, sounds good. TY!
