### ISSUE TITLE
[HOLD for payment 2024-12-07] [$250] Clean-up in the `Categorize it` flow

### ISSUE THREAD

**Issue by trjExpensify** [Expensify/App#52253]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.59-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @trjExpensify 
**Slack conversation** https://expensify.slack.com/archives/C07HPDRELLD/p1731032656572279?thread_ts=1731032605.304139&cid=C07HPDRELLD

## Action Performed:

**Case: Is not a member of `collect` or `control` workspaces**
1. Sign-up for a new account 
2. Choose "Track my personal spend" > complete onboarding
3. Go to the selfDM > `+` icon > Track expense
4. Create a manual expense 
5. Click `Categorize it` 

**Case: Is a member of `collect` or `control` workspaces**
1. Sign-up for a new account 
2. Choose "Manage my team's expenses" > complete onboarding
3. Go to the selfDM > `+` icon > Track expense
4. Create a manual expense 
5. Click `Categorize it` 

## Expected Result:
_This is considered a feature request as it's improvements to the flow._ 

1. When you click `Categorize it`, if your "default workspace" (`activePolicyID`) is type `collect` or `control`, skip the selector and show the categories list of the default workspace. 

<img width="508" alt="image" src="https://github.com/user-attachments/assets/143742c4-d84f-44c6-a61a-37913953c8b4">

2. If you have no workspaces (or your default workspace is a personal policy), show an upgrade interstitial. When `Upgrade` is clicked, create a `collect` workspace. When `Got it, thanks` is clicked, move on to show the list of categories on the workspace created. 

<img width="860" alt="image" src="https://github.com/user-attachments/assets/999d33a0-c5f7-4b0e-aaa0-d835ca946738">

## Actual Result:
1. When the user has workspaces, we show a selector to enter a name, email or phone number or create a new workspace. It's incredibly easy to go wrong here and create a second workspace, as evident in the thread. 

<img width="944" alt="image" src="https://github.com/user-attachments/assets/7dc3f6b9-232a-486d-a236-fa03d3b7124b">

2. When the user has no workspaces, we seem to be showing an empty state for the submit expense flow which doesn't make sense or match the action you just took to "categorize it" not "submit it to someone"

<img width="1511" alt="image" src="https://github.com/user-attachments/assets/9c8508f7-023e-4cb5-8d02-94353726758a">

## Workaround:
N/A 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Standalone
- [x] Android: HybridApp
- [x] Android: mWeb Chrome
- [x] iOS: Standalone
- [x] iOS: HybridApp
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
In-line above. 

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021856320183270003796</li>
        <li>Upwork Job ID: 1856320183270003796</li>
        <li>Last Price Increase: 2024-11-12</li>
<li>Automatic offers: </li>
<ul>
<li>nkdengineer | Contributor | 104948536</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @trjExpensify</details>

**Comment by trjExpensify** [comment]
@jamesdeanexpensify can you just sense check the copy, and then I'll send it external. Figgy [here](https://www.figma.com/design/ReBRDcqMXgtvPgWBBCmBxs/Wave-9%3A-Track-Expense?node-id=697-4592) if you want it.

**Comment by jamesdeanexpensify** [comment]
Do you upgrade to a workspace, or do you upgrade to a plan? Because I'm thinking of saying something like "You've upgraded to a workspace on the Collect plan!" or "You've upgraded to the Collect plan!" because it sounds a bit clearer to me.

**Comment by trjExpensify** [comment]
>Do you upgrade to a workspace

Yeah, I mean you don't have a workspace before this. That's where I was going with that, and also to hopefully teach them about the "workspace" terminology in that sense.

**Comment by jamesdeanexpensify** [comment]
Cool - only a couple comments in Figma!

**Comment by trjExpensify** [comment]
Alright, moving this on.

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

When the user has workspaces, we show a selector to enter a name, email or phone number or create a new workspace. It's incredibly easy to go wrong here and create a second workspace, as evident in the thread.


### What is the root cause of that problem?

This is a new feature request
### What changes do you think we should make in order to solve the problem?
1. For the upgrade page, we can create a new page like `IOURequestStepUpgradePage`. We can re-use `UpgradeConfirmation`, `UpgradeIntro` as we do in `WorkspaceUpgradePage`. 

- `UpgradeIntro`: we will create a new policy or draft policy when we click on the upgrade button

- `UpgradeConfirmation`: This will be shown when we create a policy/draft successfully and when clicking on got it button navigate to the select category step

- We need to add a new translation for the category upgrade feature and custom `UpgradeIntro` and `UpgradeConfirmation` to dynamic the price, and the description

https://github.com/Expensify/App/blob/cd3f30f73a18c29532d6886b4bb3744fd700ab9d/src/pages/workspace/upgrade/WorkspaceUpgradePage.tsx#L122

https://github.com/Expensify/App/blob/cd3f30f73a18c29532d6886b4bb3744fd700ab9d/src/pages/workspace/upgrade/WorkspaceUpgradePage.tsx#L128

2. When we click on `Categorize it`, 

- if the default workspace is `control` or `collect`, set the participant of the transaction as this workspace like we do [here](https://github.com/Expensify/App/blob/cd3f30f73a18c29532d6886b4bb3744fd700ab9d/src/libs/ReportUtils.ts#L8155-L8164) and navigate to the category step. 

- If `filteredPolicies` is an empty object, navigate to the `IOURequestStepUpgradePage` that we created above

- If we have multiple workspaces, navigate to the selector page.

https://github.com/Expensify/App/blob/cd3f30f73a18c29532d6886b4bb3744fd700ab9d/src/libs/ReportUtils.ts#L8204
### What alternative solutions did you explore? (Optional)

**Comment by trjExpensify** [comment]
>If we have multiple workspaces, navigate to the selector page.

Just a note that we don't want to do this part from your proposal. We want to show the categories list of the user's "default workspace" (activePolicyID) in both cases of having either one or multiple existing workspaces.

**Comment by nkdengineer** [comment]
@trjExpensify But what is the expected if `activePolicyID` is a personal workspace? In this case the user has many workspace, the default workspace still can be updated to personal in OD.

**Comment by trjExpensify** [comment]
>@trjExpensify But what is the expected if activePolicyID is a personal workspace? 

The expectation is that we treat that like having no workspace, and show the upgrade flow to create one.

**Comment by nkdengineer** [comment]
> The expectation is that we treat that like having no workspace, and show the upgrade flow to create one.

@trjExpensify This is also expected when we have many `collect` or `control` workspace and the default workspace is the personal workspace, right?

**Comment by trjExpensify** [comment]
Yep. To be clear, I think it's a hole in the design when you have multiple workspaces and an activePolicyID set to the personal workspace, but I've had pushback on the workspace picker bullet. So to start for now, we're going to have to treat that one like having "no workspace" instead and promote creating one in that case. Overall then:

- If your default workspace is of a “group” type (`collect` or `control`), show the categories list for that workspace.
- If your default workspace is the personal workspace: 
    - If you have no group workspaces, promote creating one. 
    - If you have one group workspace, show the categories list for that workspace.
    - If you have multiple group workspaces, promote creating one.

**Comment by trjExpensify** [comment]
Alrighty, @Ollyws.. can we get regression tests for this so we can move on to looking at payments?

**Comment by trjExpensify** [comment]
Thanks, going to suggest a little re-write to make these flow better. What do you think of those? 

**Case: your default workspace is the personal workspace**
1. Sign-up for a new account
2. Choose "Track my personal spend" > complete onboarding
3. Go to the selfDM > + icon > Track expense
4. Create a manual expense
5. Click Categorize it
6. Verify that a category upgrade page appears.
7. On the upgrade page, click on Learn more link
8. Verify that a help page is opened in a new tab
9. Click Upgrade > Confirm
10. Verify that we show a list of categories to select from. 

**Case: your default workspace is of a “group” type** ("Collect" or "Control")
1. Go to the selfDM > track a new expense 
2. Click Categorize it 
3. Verify that we show the categories list for that workspace.
4. Close the RHP

**Case: Disabled categories on the workspace**
1. Go to the workspace settings of the workspace
2. Go to More features > Categories
3. Disable the Categories feature
5. Go back to the selfDM
6. Click Categorize it again 
7. Verify an empty page appears as all categories are disabled 
8. Click Edit categories 
9. Verify that the category feature is enabled and the categories page appears 

**Case: personal workspace default, multiple group workspaces exist**
1. Create another workspace, so the account is now a member of two group workspaces. 
2. Go to Settings > Domains (to switch over to expensify.com easily). 
3. On OldDot, click your avatar. 
4. Change your default workspace to the personal workspace
5. Switch back to new.expensify.com 
6. Go to the selfDM > track another expense
7. Click Categorize it 
8. Verify the categories upgrade modal appears.

**Comment by trjExpensify** [comment]
@Ollyws thoughts on the above?

**Comment by trjExpensify** [comment]
Okay cool, regression test issue created! 

Payment summary as follows: 

- $250 to @Ollyws for the C+ review
- $250 to @nkdengineer for the PR

@Ollyws go ahead and request, @nkdengineer I've settled up in Upwork. Closing!

**Comment by garrettmknight** [comment]
$250 approved for @Ollyws
