### ISSUE TITLE
[HybridApp] Update the force upgrade modal to distinguish between prod and staging environments. 

### ISSUE THREAD

**Issue by trjExpensify** [Expensify/App#52276]
Coming from [here](https://expensify.slack.com/archives/C07HPDRELLD/p1730980657961059?thread_ts=1730921918.324469&cid=C07HPDRELLD). 
[Parent issue](https://github.com/Expensify/Expensify/issues/368878)

### Problem 
When we deprecate the NewDot standalone app, it causes us to not be able to test whether bugs are /app or /mobile, which prevents us from confirming if the issue can be external or internal. 

### Why is this important? 
To protect internal engineering resources and maximise the use of our external contributors. This is also a blocker to deprecating the app, which increasingly causing more confusion amongst users.  

### Solution 
- Update the force upgrade modal to distinguish between staging and production environments.
- Force upgrade production only, pointing the "Upgrade" CTA to the "Expensify" HybridApp listing in the app store. 

In doing so, we can continue shipping NewDot standalone builds to staging environments (i.e Testflight) and maintain our ability to test for HybridApp only bugs. 

<details><summary>Issue Owner</summary>Current Issue Owner: @trjExpensify</details>

**Comment by trjExpensify** [comment]
Asking about next steps [here](https://expensify.slack.com/archives/C07HPDRELLD/p1731510963057979?thread_ts=1730921918.324469&cid=C07HPDRELLD). CC: @staszekscp

**Comment by staszekscp** [comment]
Just to confirm the scope of the task 😄 The desired behaviour is to:

1. Present the `Force upgrade` modal to production users on NewDot, with a CTA to download HybridApp
2. Distinguish production and staging on HybridApp (since we don't do it at the moment)

**Comment by trjExpensify** [comment]
I don't think (2) is required for this issue. We need to force upgrade production users of the NewDot app, and keep shipping new builds to staging such that we can continue testing bugs to determine if they're HybridApp only or not.

**Comment by trjExpensify** [comment]
Cool, I think we just merged that PR didn't we? https://github.com/Expensify/App/pull/52283

**Comment by staszekscp** [comment]
Ok then! We'll jump into this on Monday!

**Comment by Julesssss** [comment]
Hey @staszekscp, is there anyone specifically that I can assign this issue to?

**Comment by war-in** [comment]
Hi @Julesssss 👋 I'm going to work on this :)

**Comment by Julesssss** [comment]
Great, let me know if I can help with anything.

**Comment by Julesssss** [comment]
@trjExpensify we should think about testing. It's going to be tricky so maybe we just have to manually verify on the PR that bumps the minimum once these changes are deployed and we are ready to kill standalone?

**Comment by AndrewGable** [comment]
I think we should add a beta to test this, so we can confirm on known test domains and then enable it for all domains.

**Comment by AndrewGable** [comment]
Added in https://github.com/Expensify/Web-Expensify/pull/44480, the beta name will be `hybridForcedMigration`

**Comment by Julesssss** [comment]
PR merged, awaiting deployment for testing

**Comment by trjExpensify** [comment]
@Julesssss can we close this?

**Comment by trjExpensify** [comment]
We're still waiting to confirm this, Melv.

**Comment by trjExpensify** [comment]
Still held up on confirming this.

**Comment by Julesssss** [comment]
- InternalQA staging passed yesterday: https://github.com/Expensify/Web-Expensify/pull/44699#issuecomment-2539486808
- InternalQA prod is being tested this morning

**Comment by trjExpensify** [comment]
Thanks!

**Comment by trjExpensify** [comment]
@Julesssss how do you feel about closing this now?

**Comment by Julesssss** [comment]
Thanks, yeah as shown [here](https://github.com/Expensify/Web-Expensify/pull/44856#issuecomment-2557041040) the force upgrade flow is working nicely. We have a separate error with how referer is being reported.
