### ISSUE TITLE
Expensify Card - No error message when incorrect code is entered when deactivating card

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#52338]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.60-0
**Reproducible in staging?:** Y
**Reproducible in production?:**N, New feature
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+zm27@applause.expensifail.com
**Issue reported by:** Applause - Internal Team
**Slack conversation** (hyperlinked to channel name):

**Issue found when executing PR** https://github.com/Expensify/App/pull/51147
## Action Performed:
Precondition:
- User has a virtual card
1. Go to staging.new.expensify.com
2. Go to Wallet
3. Click on the virtual card
4. Click Report virtual card fraud
5. Click Deactivate card
6. Enter incorrect magic code

## Expected Result:
There will be error for incorrect magic code

## Actual Result:
There is no error for incorrect magic code.
App shows not here page briefly and then empty card details page loads

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/5414b64d-54a6-44fc-8098-8bb6f11a6d5c

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
New feature, not repro on Production
https://github.com/user-attachments/assets/88502225-de49-4096-b5a9-c9a7f797e337

**Comment by francoisl** [comment]
This will require backend changes, reassigning and demoting.

**Comment by francoisl** [comment]
I think the last piece was https://github.com/Expensify/Auth/pull/12739 and we can close this now, right @youssef-lr?

**Comment by youssef-lr** [comment]
Yup!
