### ISSUE TITLE
[$250] Update system message copy - policy approver

### ISSUE THREAD

**Issue by jamesdeanexpensify** [Expensify/App#52335]
## Summary
Related to [this convo](https://expensify.slack.com/archives/C07NZ8B1VTQ/p1730946283669399), two changes here:

<img width="656" alt="image" src="https://github.com/user-attachments/assets/72d15c53-c298-4fdd-b06c-eb37a2bdd372">

1. Change `Policy Approver` to (lower-case) `workspace approver`
2. Remove the quotes around the two emails
 
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021856060154754593261</li>
        <li>Upwork Job ID: 1856060154754593261</li>
        <li>Last Price Increase: 2024-11-11</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @jayeshmangwani</details>

**Comment by jamesdeanexpensify** [comment]
@muttmuure do you think we should also update the wording of `policy approver` in this issue? I can't seem to find it in the product, but I know we've been essentially trying to banish the use of the term `policy` in favor of `workspace`. Would that work here? Is `workspace approver` an Expensify term?

**Comment by FitseTLT** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Update system message copy - policy approver

### What is the root cause of that problem?
The system message coming from the BE has problems
### What changes do you think we should make in order to solve the problem?

We can add a specific condition for `CONST.REPORT.ACTIONS.TYPE.POLICY_CHANGE_LOG.UPDATE_FIELD
` report action type here
https://github.com/Expensify/App/blob/533aed65143e5bb47b9692952995be81368eed7b/src/pages/home/report/ReportActionItem.tsx#L687
and return the message we want translated by getting the changed values from `originalMessage`
`updated the policy approver from {originalMessage.oldValue} to {originalMessage.newValue}` and add the same condition for copy to clipboard, getREportName (to create a thread with it) and LHN
### What alternative solutions did you explore? (Optional)

**Comment by jamesdeanexpensify** [comment]
Sorry all - had to switch this to `Internal`

**Comment by jayeshmangwani** [comment]
Issue [switched to internal](https://github.com/Expensify/App/issues/52335#issuecomment-2468932513). @jamesdeanexpensify , what’s the next step here ?

**Comment by maddylewis** [comment]
@jamesdeanexpensify - sure! just be sure to run through these prompts before adding the label :) 

https://stackoverflowteams.com/c/expensify/questions/20462

**Comment by jamesdeanexpensify** [comment]
- **What is the expected outcome? What specific criteria will indicate that this issue has been successfully resolved?**
- This is a very minor copy update, the expected result is in the OP up top!

- **Why are we doing this / what value do we get out of this proposed change? Describe the purpose and benefits of addressing this issue. Will it improve user experience, resolve a pain point, enhance performance, or fulfill a critical business need?**
- I would say this enhances user experience with more consistent copy that reflects Expensify style.

- **What problem are we solving? Clarify the issue by describing the specific problem and its impact. What undesirable outcomes are users experiencing? How does this problem affect product functionality, user experience, or team workflows?**
- Problem: The Expensify style isn't being followed in this system message copy, which makes it inconsistent with other copy across the product and leads to a less polished user experience.

- **Priority and Impact - How critical is this issue in the larger scope of the project? Does it block other tasks or have a high impact on the product or customer experience? Link any relevant Slack threads that illustrate the priority and impact of the issue.**
- It's not critical. I would call it polish.

- **Reproduction Steps - Include detailed reproduction steps that illustrate how this is an issue.**
- I think these would be: 
  - 1. Create a workspace
  - 2. Invite two other members to it
  - 3. Make one of them an approver on the workspace
  - 4. Then switch the approver to the other member
  - 5. You should see the system message in the #admins room of the workspace 

- **Estimation of how long the ticket might take to complete - Provide an estimate on how much effort this should take to complete - are you asking an engineer to write the detailed section of a design doc? Or, is this a smaller amount of effort (e.g., fixing a minor bug)? If you're unsure, note in the comment: I'm not sure, so I will default to engineering to confirm.**
- I'll default to engineering to confirm.

- **Who has experience or domain knowledge that might help us complete it? Mention any team members with relevant expertise, context, or familiarity with this area of the codebase or functionality. This can save time by ensuring the right people are involved early.**
- @JmillsExpensify this is a tiny tweak, but since you're working on system messages I'll tag you for viz

- **Related Issues - Are there any related issues or blockers tied to this issue?** 
- I don't think so

- **Can it be worked on by contributors or not? Indicate whether this issue is suitable for external contributors (e.g., open source) or requires internal team access or specialized knowledge. If you're not sure if it can be worked on by a contributor, you can ask in #bug-zero.**
- No, this is a system message so it's BE work. 

- **Context for Any Existing Workarounds - Are there any current workarounds that users or team members are using?**
- N/A

**Comment by muttmuure** [comment]
Sorry I missed my ping two weeks ago. Workspace Approver sounds fine to me! 

Also, is this issue solely about updating this one line here: https://github.com/Expensify/Web-Expensify/blob/efc6355260f9ba007973c794c25bc01088f5cc9b/lib/Report/Action/PolicyChangeLog/UpdateField.php#L22

?

**Comment by jamesdeanexpensify** [comment]
Two changes! One is that and the other is removing the quotes (see OP comment). I lumped them together since they appeared in the same system message. (Minor note: it should be `workspace approver` and not `Workspace Approver` please!)

**Comment by srikarparsi** [comment]
Hey! I'm trying to reproduce this message but not seeing it when I run through these [test steps](https://github.com/Expensify/App/issues/52335#issuecomment-2486839073). Is there anything I'm missing @jamesdeanexpensify

https://github.com/user-attachments/assets/da82824f-f2fe-4734-b725-f35ff4829b59

**Comment by srikarparsi** [comment]
Just for later notice, I think the place to change is [here](https://github.com/Expensify/Auth/blob/84150919f814d332519b73fd020deab890f751e5/auth/lib/ReportAction.h#L228) since we moved over some changelogs from Web E to Auth but I'll make sure by testing.

**Comment by jamesdeanexpensify** [comment]
Can you try switching the approver for everyone's expenses to another new user? I played around with switching back and forth between different approvers and eventually generated the message.

**Comment by srikarparsi** [comment]
Tried adding a new member and then updating `everyone's` approver to that new user. Could this be a larger bug where the system message is not being generated? Maybe cc @cristipaval since I saw you worked on this related [PR](https://github.com/Expensify/Auth/pull/9980)


https://github.com/user-attachments/assets/fffabab6-8452-40ac-8b07-f60c37ab9a2d

**Comment by jamesdeanexpensify** [comment]
So strange - I kinda had to play around with switching between different approvers before it triggered, so maybe it's actually a bug. I'm not sure.

**Comment by twisterdotcom** [comment]
I am removing hot pick from any issues with an internal engineer assigned so other engineers can know it's available.

**Comment by srikarparsi** [comment]
I'll try to make some time to look into this Wednesday.

**Comment by jayeshmangwani** [comment]
@srikarparsi Any updates for us on [this](https://github.com/Expensify/App/issues/52335#issuecomment-2530658756)?

**Comment by srikarparsi** [comment]
Hey, not yet. I still haven't been able to reproduce since last time but I'll play around with it and try to leave an update tomorrow.

**Comment by jamesdeanexpensify** [comment]
@srikarparsi maybe we can just close this one out and I'll let you know if I see it again?

**Comment by srikarparsi** [comment]
Cool, yup sounds good. Do let me know
