### ISSUE TITLE
[$250] Expense Preview - The number of expenses in the expense preview is not visible

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#52340]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
 
**Version Number:** 9.0.60-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Email or phone of affected tester (no customers):** applausetester+bm215@applause.expensifail.com
**Issue reported by:**Applause Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Create new workspace
3. Go to the workspace chat
4. Submit two expenses and see the expense preview.

## Expected Result:
The number of expenses should not become hidden

## Actual Result:
The number of expenses becomes hidden when creating a second expense. it reappears after going to another chat and coming back again.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/33ac9784-94ae-4c81-931a-ff660e85455f
  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021857044981491277126</li>
        <li>Upwork Job ID: 1857044981491277126</li>
        <li>Last Price Increase: 2024-11-21</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @akinwale</details>

**Comment by sonialiap** [comment]
@akinwale what do you think of the above proposal?

**Comment by akinwale** [comment]
We can move forward with @NJ-2020's [proposal](https://github.com/Expensify/App/issues/52340#issuecomment-2469881867) here.

🎀👀🎀 C+ reviewed.

**Comment by luacmartins** [comment]
Hmm can we actually retest this? I just update some flows in the backend to return `linkedReportID` as a string. Let's confirm that we can still reproduce the issue first. If we can, I think we should fix this in the backend to send `linkedReportID` as a string.
