### ISSUE TITLE
Expense preview - Preview gets duplicated on submit 2 duplicate expenses if any already exist

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#52343]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.60-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/52060
## Action Performed:
1. Log in to New Expensify
2. Navigate to workspace chat
3. Submit an expense
4. Submit another different expense
5. Submit third expense, the same as in step 4.

## Expected Result:
One expense preview should be displayed

## Actual Result:
Duplicate expense preview appears after submitting duplicate expenses

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/f2830c62-855d-404e-904c-ca99d2c285f4

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
Production:

https://github.com/user-attachments/assets/fa39fe0f-969e-4a42-922f-4e4fbf7bb07d

**Comment by francoisl** [comment]
I think this is a backend bug, I can still repro if I check out NewDot's production version locally, and can no longer repro if I check out Web-E's production branch.

**Comment by francoisl** [comment]
This is caused by https://github.com/Expensify/Web-Expensify/pull/44299, cc @yuwenmemon. Removing the DeloyBockerCacsh label.

**Comment by yuwenmemon** [comment]
Hmmmm... This only seems to happen when you are the workspace's admin in addition to the submitter..

**Comment by yuwenmemon** [comment]
Ah, we're not removing the optimistic report action, and updating the old one that actually exists...

**Comment by yuwenmemon** [comment]
I have a fix but will create a revert the offending PR in the meantime so we can move forward with the deploy if we need to before the next Auth deploy cc @mountiny

**Comment by mountiny** [comment]
Asked for a retest here https://expensify.slack.com/archives/C9YU7BX5M/p1731434051476589

**Comment by kavimuru** [comment]
Not able to reproduce

https://github.com/user-attachments/assets/2be9f039-5bf9-450c-bfd4-84880457c855

**Comment by brunovjk** [comment]
**Is this the same bug**: Two previews are created after creating 2 or more expenses

<details>
<summary>v9.0.66-8</summary>



https://github.com/user-attachments/assets/31f2ddf2-c7d6-48d5-af3b-e1f6021a2523

</details>

cc: @yuwenmemon @mountiny 

Thank you for your help!

**Comment by mountiny** [comment]
@brunovjk yes that seems like a bug

**Comment by mountiny** [comment]
Can you report in Slack if its not reported yet?

**Comment by brunovjk** [comment]
Reported it [here](https://expensify.slack.com/archives/C049HHMV9SM/p1732793407316609) :D

**Comment by brunovjk** [comment]
@mountiny I'm a bit confused, the bug has already been reported [here](https://expensify.slack.com/archives/C05LX9D6E07/p1732781783173839), right? Thanks.

**Comment by mountiny** [comment]
Yes, I saw it reported there just after this message from you
