### ISSUE TITLE
 Expense - Unable to download expense from expense report

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#52346]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.60-0 
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** applausetester+kh27100061@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to DM.
3. Submit an expense.
4. Go to expense report.
5. Click on the report header.
6. Click Download.

## Expected Result:
The expense can be downloaded.

## Actual Result:
The expense cannot be downloaded. It shows Download failed.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
  
https://github.com/user-attachments/assets/b12dd5a6-5fdf-46ef-b372-2163ec6243ef

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Shahidullah-Muffakir** [comment]
Seems like a BE issue in **ExportReportToCSV** endpoint. 
It is working if user download the same expense from the Search page using **ExportSearchToCSV** endpoint.

**Comment by johncschuster** [comment]
Thanks for calling that out! I'll get this in a project and see if we can get a BE on this.

**Comment by johncschuster** [comment]
I couldn't action this today.

**Comment by MarioExpensify** [comment]
I'm on it.

**Comment by MarioExpensify** [comment]
![image](https://github.com/user-attachments/assets/658f872f-43bd-473d-bfb6-407534c5a07d)

I'll request a retest for this as every attempt I made I could download the report.

**Comment by kavimuru** [comment]
Not reproducible. 

https://github.com/user-attachments/assets/fadccd22-834f-4b9a-8f58-d7efc5c2d1f5

**Comment by MarioExpensify** [comment]
Let's hold onto this for a while, perhaps retest next week and check if everything is still good. It seems this may have been a one off.

**Comment by kavimuru** [comment]
Not able to reproduce. 

https://github.com/user-attachments/assets/9985b65f-3baa-4a47-a70c-515d6490b18d
