### ISSUE TITLE
[HOLD for payment 2024-12-03] [Search v1.2] - Pay button displayed next to expense after unapproving

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#52364]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.60.0
**Reproducible in staging?:** Y
**Reproducible in production?:** N/A - new feature, doesn't exist in prod
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/ and log in with an account (WS admin) that have some unapproved expenses
2. Navigate to Search
3. Click on the Approve button
4. Open the expense
5. Click on the header and unapprove the report
6. Dismiss the RHP to return to Search

## Expected Result:
The Approve button is displayed next to the expense

## Actual Result:
The Pay button is displayed until the page is refreshed

## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/7d30f16d-64de-4549-81f0-864e003e2456

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @luacmartins</details>

**Comment by techievivek** [comment]
@luacmartins seems related to the search functionality, can you please take care of it?

**Comment by luacmartins** [comment]
I'll demote this to NAB since the fix would be in Auth

**Comment by luacmartins** [comment]
hmm I see that the Onyx update for `UnapproveExpenseReport` is the following:

![Screenshot 2024-11-13 at 1 56 12 PM](https://github.com/user-attachments/assets/b2a86422-6bfa-4216-b8b5-ecfb968251b3)

According to [this SO](https://stackoverflowteams.com/c/expensify/questions/9), stateNum 1 and statusNum 3 isn't a valid combo. I'll take a look there

**Comment by luacmartins** [comment]
Before I investigate Auth, it seems like the data in `snapshot_` is not being updated, since it's still at stateNum 2 and statusNum 3 after unapproving. Even if the Auth response is incorrect, we should be updating it to 1 and 3 like shown above. So I'll investigate that first

**Comment by luacmartins** [comment]
Interesting, so after unapproving a report we merge the following changes to the Search data, the first which correctly updates the report state/status to 1, but then there's another merge that reverts that back to 2/3

```
[info] [Onyx] merge called for key: snapshot_243428839 changes: {"data":{"report_4218805946655093":{"chatReportID":"4713946710220241","chatType":"","currency":"USD","isWaitingOnBankAccount":false,"managerID":1175,"nonReimbursableTotal":0,"ownerAccountID":1175,"policyID":"B8110BD941FBBECF","private_isArchived":"","reportID":"4218805946655093","reportName":"Expense Report #4218805946655093","stateNum":1,"statusNum":1,"total":-100,"type":"expense","unheldTotal":-100}}} properties: data hasChanged: true - "" 
Log.ts:66 [info] [Onyx] merge called for key: snapshot_243428839 changes: {"data":{"report_4218805946655093":{"chatReportID":"4713946710220241","chatType":"","currency":"USD","isWaitingOnBankAccount":false,"managerID":1175,"nonReimbursableTotal":0,"ownerAccountID":1175,"policyID":"B8110BD941FBBECF","private_isArchived":"","reportID":"4218805946655093","reportName":"Expense Report #4218805946655093","stateNum":2,"statusNum":3,"total":-100,"type":"expense","unheldTotal":-100},"personalDetailsList":{"1175":{"accountID":1175,"avatar":"https://d2k5nsl2zxldvw.cloudfront.net/images/avatars/default-avatar_24.png","displayName":"test","firstName":"test","lastName":"","login":"act@act.com","phoneNumber":"","pronouns":"","status":null,"timezone":{"automatic":true,"selected":"America/Edmonton"},"validated":false}},"report_4713946710220241":{}}} properties: data hasChanged: true - "" 
Log.ts:66 [info] [Onyx] merge called for key: snapshot_243428839 changes: {"data":{"report_4218805946655093":{},"personalDetailsList":{"1175":{"accountID":1175,"avatar":"https://d2k5nsl2zxldvw.cloudfront.net/images/avatars/default-avatar_24.png","displayName":"test","firstName":"test","lastName":"","login":"act@act.com","phoneNumber":"","pronouns":"","status":null,"timezone":{"automatic":true,"selected":"America/Edmonton"},"validated":false}}}} properties: data hasChanged: false - "" 
```

**Comment by luacmartins** [comment]
Pinging @Beamanator for some clarification on how `UnapproveExpenseReport` is sending those updates and why we call `GetMissingOnyxMessages` since I couldnt find where Auth/Web-E sends that data

**Comment by Beamanator** [comment]
Hmm so Auth-wise:
1. I'm sure that `Report::createAction` does its own onyx-update-sending, you just have to follow the chain down a few levels.
2. For auth.report.updateLastReadTime It looks like that just calls `setReportNameValuePair` which has its own onyx-update-queueing
3. Then for `ReportAction::createOrUpdateReportPreview` it calls the above two functions, OR `queueReportPreviewMessageUpdates` which does its own queueing
