### ISSUE TITLE
Search - "Save search" is shown when no category is displayed

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#52361]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.60-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Issue was found when executing this PR:** https://github.com/Expensify/App/pull/52102
**Email or phone of affected tester (no customers):** applausetester+ds@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Log in with a new account.
3. Create a new workspace.
4. Go to workspace settings
5. Go to search > filters > Select a category and save search
6. Delete the workspace
7. Go to search > filters
8. Notice that "Save search" is shown even if no category is displayed and no item is selected.

## Expected Result:
"Save search" is not shown when there is no item selected.

## Actual Result:
"Save search" is shown even if there is no category displayed and no item is selected.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/1c4ce59a-7ee7-424e-8dc4-f26b532ee576
 
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Kicu** [comment]
I will try to fix this. However I think there is no obvious solution to this edge case, because the saved search exists and it has certain data saved with it.
On one hand if there are no categories in the system then the picker should not be displayed. On the other hand if a category was saved with this "saved search" then we should display it.

I don't know what is the cleanest solution. What do you think about this @luacmartins ?

**Comment by MonilBhavsar** [comment]
I think if there are no categories, we can still display a category picker, but may be disable it, so user can know that they can filter through categories.
Makes sense to display saved search.

**Comment by MonilBhavsar** [comment]
I think we can demote it from blocker since it's an edge case

**Comment by MonilBhavsar** [comment]
@Kicu I'll assign this issue to you, if you don't mind

**Comment by luacmartins** [comment]
TBH I think we should just close this. The filter is always available to the user via the typed query so they could technically still search for something like `category:blah`. The point of hiding the filter in the UI is to de-clutter and give users options that make sense, but I don't think we need to clean up previously saved searches. That behavior is not exclusive to showing/hiding the filter, it would also happen if they saved a search with a category that no longer exists -- for that, the user can update the search themselves if they want to.

**Comment by luacmartins** [comment]
Gonna close this for now.
