### ISSUE TITLE
[HOLD for payment 2024-12-03] [Search v1.2] - Paid invoice shows "View" button instead of "Paid" label

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#52366]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.60-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N/A - new feature, doesn't exist in prod
**Email or phone of affected tester (no customers):** applausetester+kh011101@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. [User A] Send an invoice to User B.
3. [User B] Go to invoice chat.
4. [User B] Pay the invoice.
5. [User A] Go to Search.
6. [User A] Go to Invoices.

## Expected Result:
There will be a "Paid" label for the paid invoice (production behavior).

## Actual Result:
It shows "View" button for the paid invoice instead of "Paid" label.

## Workaround:
Unknown
## Platforms:

- [x] Android: Standalone
- [x] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/0933dafb-1af8-452c-a9e2-f729fdddbf32

  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @luacmartins</details>

**Comment by luacmartins** [comment]
Looking into this

**Comment by Anaslancer** [comment]
I think we need to remove ` || (isTransaction && !data[key].isFromOneTransactionReport)` at the first condition of [`getAction`](https://github.com/Expensify/App/blob/7b31a728168e833a43248f8e6e59f80ee7d5dbd2/src/libs/SearchUIUtils.ts#L251-L300) function. And looks good the other logic. Please check [my solution](https://github.com/Expensify/App/issues/52369#issuecomment-2470973069).

**Comment by johncschuster** [comment]
@luacmartins as far as I can tell, this doesn't require payment. Please let me know if I've overlooked anyone!

**Comment by luacmartins** [comment]
Yea, this is not done yet. I'll remove those labels/update the OP

**Comment by luacmartins** [comment]
This is done
