### ISSUE TITLE
Changing approvers in NewDot on Submit/Approve changes workspace settings to Advanced Approval

### ISSUE THREAD

**Issue by garrettmknight** [Expensify/App#52363]
**Original GH:** https://github.com/Expensify/App/issues/51349#issuecomment-2459424486
**Slack discussion:** https://expensify.slack.com/archives/C06ML6X0W9L/p1731060374967819

## Action Performed:

1. Create a workspace in NewDot
2. Invite another user, User B
3. Enable Workflows and Approvals
4. Change the default approver from the admin to User B

## Expected Result:
The approval mode remains `BASIC`

## Actual Result:
The approval mode changes to `ADVANCED`

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

</details>

**Comment by tgolen** [comment]
[PR](https://github.com/Expensify/Auth/pull/13108) is up and ready for review

**Comment by mjasikowski** [comment]
Removing the `Hot Pick` label, as it's already taken!

**Comment by tgolen** [comment]
# Daily Update
- Scott gave the [Auth PR](https://github.com/Expensify/Auth/pull/13108) a review

### Next Steps
- @deetergp continue reviewing and then merge the PR

#### ETA
- Today, Nov 14

**Comment by tgolen** [comment]
# Daily Update
- Scott gave the Auth PR another review
- I've updated the PR with the requested changes

### Next Steps
- @deetergp continue reviewing and then merge the PR

#### ETA
- Today, Nov 15

**Comment by tgolen** [comment]
This was deployed and can be closed.
