### ISSUE TITLE
[Search v2.5] Tax rate field is displayed after disabling Taxes

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#52378]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v.9.0.60
**Reproducible in staging?:** Y
**Reproducible in production?:** N/A - new feature, doesn't exist in prod
**Issue was found when executing this PR:** https://github.com/Expensify/App/pull/52102
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Log in with a new account
3. Create a new workspace
4. Go to workspace settings > More features
5. Enable Taxes
6. Go to Search > Filters.
7. Verify that there is tax filter displayed if user has taxes
8. Go back to workspace settings > More features
9. Disable Taxes
10. Go to Search > Filters.

## Expected Result:
There is no tax filter displayed if the user has no taxes.

## Actual Result:
There is tax filter displayed when the user has no taxes.
The filter disappears when the user clears the cache (Troubleshoot > Clear cache and restart).

## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/f1e2d88d-7f00-4249-be17-856e96f945d7

 
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @sumo-slonik</details>

**Comment by sumo-slonik** [comment]
Hey! I'm Kuba Nowakowski from Software Mansion, an expert agency, and I'd like to work on this issue!
I talked to @Kicu

**Comment by Kicu** [comment]
CC @luacmartins this looks pretty simple, probably need a more advanced if check around taxes.
I suggested that Jakub here can handle it ☝️

**Comment by luacmartins** [comment]
Gonna demote since it doesn't break any functionality

**Comment by luacmartins** [comment]
@sumo-slonik all yours

**Comment by RachCHopkins** [comment]
@luacmartins do I need to add the Help Wanted label to post on Upwork, or are @sumo-slonik and @Kicu handling it totally separate to Upwork?

**Comment by Kicu** [comment]
@RachCHopkins we work for an expert agency and no Upwork post is needed for us :)

**Comment by carlosmiceli** [comment]
Assigning myself too since I got assigned the contributor's PR for review.

**Comment by mjasikowski** [comment]
@sumo-slonik any updates here?

**Comment by Kicu** [comment]
It seems to me we a PR was created and successfully was merged 3 weeks ago?
https://github.com/Expensify/App/pull/52462

Perhaps something failed in automation?

**Comment by luacmartins** [comment]
Correct, [this PR](https://github.com/Expensify/App/pull/52462) was merged 3 weeks ago

**Comment by luacmartins** [comment]
There is no C+ here and the authors/reviewers are either internal or from SWM, so no Upwork payment is due. Closing
