### ISSUE TITLE
[HOLD for payment 2024-12-03] [Search v1.2] - LHN preview shows 0.00 and no pay button when paying partially from Search

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#52375]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.60-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N/A - new feature, doesn't exist in prod
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Y
**Email or phone of affected tester (no customers):** applausetester+kh011102@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Create a new workspace.
3. Submit two expenses.
4. Hold one of the expenses.
5. Go to Search.
6. Go to Outstanding.
7. Click Pay next to the expense.
8. Click on the dropdown button in RHP.
9. Select Pay elsewhere.
10. Close the RHP.
11. Click Pay button next to the expense.
12. Go back to Inbox.
13. Go to the main workspace chat.

## Expected Result:
The expense will show the correct amount in expense preview and LHN, with pay button.

## Actual Result:
The expense shows 0.00 in LHN and there is no pay button on the expense preview.
Sometimes the expense preview also shows 0.00.

After refreshing the page, LHN shows correct amount and pay button is shown on the expense preview.

## Workaround:
Unknown

## Platforms:

- [x] Android: Standalone
- [x] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/a890e023-cc05-4dcd-b235-180136c8e20a

  </details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @MitchExpensify</details>

**Comment by MarioExpensify** [comment]
Checking

**Comment by MarioExpensify** [comment]
I believe this may be related to [this PR](https://github.com/Expensify/App/pull/51445) where the Search actions were introduced.

**Comment by MarioExpensify** [comment]
@luacmartins this seem to be a missing update from the backend, do you think we can dismiss as a blocker for the app?

**Comment by MarioExpensify** [comment]
Talked with @luacmartins, he'll be taking over. Thank you!

**Comment by luacmartins** [comment]
Done!
