### ISSUE TITLE
[HOLD for payment 2024-12-17] Add `Posted:` for filtering card transactions by statement dates

### ISSUE THREAD

**Issue by JmillsExpensify** [Expensify/App#52376]
We missed adding this filter in the Search v2 design doc, so let's add it now. Like other date filters, it'll accept YYYY-MM-DD and will apply exclusively to the Expensify Card. 

<details><summary>Issue Owner</summary>Current Issue Owner: @JmillsExpensify</details>

**Comment by dannymcclain** [comment]
@JmillsExpensify will `datePosted:` accept both `before` and `after` values like our regular date filter?

**Comment by JmillsExpensify** [comment]
Hmm, good question. We should probably take that approach for consistency.

**Comment by luacmartins** [comment]
@JmillsExpensify should this filter name also follow the other date-based filter and be just `posted:` instead of `datePosted:`? We are using `submitted`, `approved`, etc for the other ones

**Comment by JmillsExpensify** [comment]
Ah, great call. I like that, updated the OP.

**Comment by JmillsExpensify** [comment]
Also see this comment from a [related issue](https://github.com/Expensify/App/issues/52262#issuecomment-2492520320). We're getting to the point that we have a ton of filters that do different things, so it's a good time to section out the options into thematic sections.

**Comment by dannymcclain** [comment]
Any updates of note here?

**Comment by luacmartins** [comment]
PR in staging

**Comment by dannymcclain** [comment]
@luacmartins I don't see `Posted` in that list of filters—am I just missing something?

![CleanShot 2024-12-10 at 13 46 30@2x](https://github.com/user-attachments/assets/81dce85d-108d-4211-9b78-2fcef9bf9467)

**Comment by dannymcclain** [comment]
Ah gotcha—I was just going by what I was seeing in the videos in the PR. Sounds like it's taken care of though! Thanks!

**Comment by luacmartins** [comment]
Payment was handled via https://github.com/Expensify/App/issues/52262. Closing.
