### ISSUE TITLE
[HOLD for payment 2024-12-03] [Search v1.2] - Pay button can be clicked many times without error when bank account is not set up

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#52371]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.60-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N/A - new feature, doesn't exist in prod
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Y
**Email or phone of affected tester (no customers):** applausetester+kh011102@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Create a new workspace.
3. Submit an expense.
4. Go to Search.
5. Click Pay.
6. Click on the dropdown.
7. Select Pay with Expensify (select the same option even when the button shows Pay with Expensify).
8. Close the RHP.
9. Click Pay button.

## Expected Result:
There should be a message informing that the payment cannot be carried out because bank account is not set up.

## Actual Result:
The pay button can be clicked several times and there is no error message at all.

## Workaround:
Unknown

## Platforms:

- [x] Android: Standalone
- [x] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/68c2020e-780e-414b-8dd0-e76af71ca812

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @luacmartins</details>

**Comment by rlinoz** [comment]
Probably related to this PR https://github.com/Expensify/App/pull/51445

But I am not sure we have a pattern for showing errors in Search, checking here https://expensify.slack.com/archives/C01GTK53T8Q/p1731409542501669

**Comment by rlinoz** [comment]
We are adding RBR in another PR https://github.com/Expensify/App/pull/52333 and this is still under construction, so we don't need to block on this and can close it.

**Comment by luacmartins** [comment]
I'll reopen this issue and assign it to me so I can work on fixing it

**Comment by luacmartins** [comment]
@rlinoz @greg-schroeder we fixed the issue via a revert. I'll unassign you but keep the issue open to make sure I address it in the v2 of my PR

**Comment by luacmartins** [comment]
This is done
