### ISSUE TITLE
Invoices Category visible for invoice recipient in the Search LHN

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#52379]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.60-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Issue was found when executing this PR:** https://github.com/Expensify/App/pull/52148
**Email or phone of affected tester (no customers):** applausetester+omuserb4@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
Precondition: User signed into account A on the main tab and into account B, which is not a member of any workspace with invoices and has never released files, in the incognito tab

1. [Account A] open https://staging.new.expensify.com/

2. [Account A] Create a workspace and enable invoices
3. [Account B] Navigate to search tab and observe categories
4. [Account A] Send invoice to account B
5. [Account B] Repeat step 3

## Expected Result:
According the step 10 in the PR, "Veriy that invoices category is not visible in the Search LHN"
(Invoices categories should not be displayed in the search tab for invoice recipient in the Search LHN)

## Actual Result:
Invoices Category visible for invoice recipient in the Search LHN

## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/b9412e07-97a1-430c-bf87-dc195af7cf7f

 
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by luacmartins** [comment]
This is expected. The invoice receiver should be able to filter by invoices since they have invoices in their account. Closing
