### ISSUE TITLE
Android - Chat - The code block in room description is shown with ellipsis

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#52385]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.60-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Launch app
2. Open a chat
3. Tap fab -- start ch ta - room
4. Create a room with this description - #01283873🤑😇😋😇😋😘😋😘
@[hshdhd@gmail.com](mailto:hshdhd@gmail.com)

# 028337

~`|•••¶•÷~
`😇😇😇🫸🫷🫰🪸🛞😇||`

5. Tap header and note description

## Expected Result:
The code block in room description must not be shown with ellipsis.

## Actual Result:
The code block in room description is shown with ellipsis.

## Workaround:
Unknown

## Platforms:

- [x] Android: Standalone
- [x] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/9f4c58d5-9832-4769-b5b0-edab86b364da

 </details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by muttmuure** [comment]
I don't think anyone cares about this right now
