### ISSUE TITLE
Critical: Report preview report actions are not displayed in created timestamp of the reports

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#52391]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.60-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @heyjennahay 
**Slack conversation** (hyperlinked to channel name): [ts_external_expensify_migrate](https://expensify.slack.com/archives/C07NMDKEFMH/p1731363881032019)

## Action Performed:
Prerequisite:  User have unsubmitted expense in workspace

1. Submit a new expense to a workspace 
2. Get paid by the approver
3. Open the workspace chat and observe

## Expected Result:
The paid expenses are displayed above the unsubmitted ones in the chat
## Actual Result:
The unsubmitted expenses are displayed above the paid ones in the chat
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details>

![image (15)](https://github.com/user-attachments/assets/8fa0b699-00cc-4a3d-983f-bb1aa0823213)

![image (16)](https://github.com/user-attachments/assets/8fcc468b-20f4-48f6-a7c5-e21a94d781da)

![Snip - (138) New Expensify - Google Chrome](https://github.com/user-attachments/assets/ff9e672b-5960-4a84-bad7-c13ba5a3d5d0)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by puneetlath** [comment]
The PR was merged. We'll run the migration to test this again once it's live.
