### ISSUE TITLE
[HOLD for payment 2024-12-03] [Search v1.2] - Approve button is not disabled in Search when "Prevent self-approvals" is enabled

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#52404]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.60-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N/A - new feature, doesn't exist in prod
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Y
**Email or phone of affected tester (no customers):** applausetester+0080989@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
Precondition:
- Workflows are enabled.
- Delayed submissions are disabled.
- Add approvals are enabled, and admin is the approver.
- Rules are enabled.
- "Prevent self-approvals" in Rules is enabled.

1. Go to staging.new.expensify.com
2. Go to workspace chat.
3. Submit an expense.
4. Note that Approve button is disabled.
5. Go to Search.
6. Click Approve button next to the expense.

## Expected Result:
Approve button for the expense should be disabled when "Prevent self-approvals" in Rules enabled.

## Actual Result:
Approve button for the expense is not disabled when "Prevent self-approvals" in Rules enabled.
User can click Approve button repeatedly.

## Workaround:
Unknown

## Platforms:

- [x] Android: Standalone
- [x] Android: HybridApp
- [x] Android: mWeb Chrome
- [x] iOS: Standalone
- [x] iOS: HybridApp
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/bc0d0fe4-8317-4b9b-91ed-ffb454530986
  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @stephanieelliott</details>

**Comment by francoisl** [comment]
@srikarparsi are you able to look into this?

**Comment by srikarparsi** [comment]
Sorry, I didn't see this earlier, looking into it now.

**Comment by srikarparsi** [comment]
Able to reproduce on staging:
<img width="1511" alt="image" src="https://github.com/user-attachments/assets/87061a02-20cb-45a9-9ee0-c4455ac60e20">

Not able to reproduce on production, so is a blocker:
<img width="1512" alt="image" src="https://github.com/user-attachments/assets/227c8fcf-821c-440b-af89-7feb10b9042f">

**Comment by srikarparsi** [comment]
Looks like this [PR](https://github.com/Expensify/App/pull/51445) which adds the action buttons @luacmartins, probably an edge case that we just need to account for, looking into it

**Comment by srikarparsi** [comment]
Asked a question [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1731442058464039?thread_ts=1731423953.254799&cid=C01GTK53T8Q) about expected behavior

**Comment by luacmartins** [comment]
This is done
