### ISSUE TITLE
Regression test request for #27913

### ISSUE THREAD

**Issue by zanyrenney** [Expensify/App#52402]
### Precondition:

- None

### Test:

1. Go into any chat report.
2. Type the suggested message below, it's been prepared for testing purposes:
```

`thissadasdasdsadsadasdadsadasdasdasdasdasdasdasdasdasdasdsadsadggggggggggggggggg` multilingual 
`https://www.google.com/search?q=google&oq=goog&gs_lcrp=EgZjaHJvbWUqEAgAEAAYgwEY4wIYsQMYgAQyEAgAEAAYgwEY4wIYsQMYgAQyEwgBEC4YgwEYxwEYsQMY0QMYgAQyDQgCEAAYgwEYsQMYgAQyBggDEEUYOzIGCAQQRRg8MgYIBRBFGDwyBggGEEUYPDIGCAcQBRhA0gEHNzM1ajBqN6gCALACAA&sourceid=chrome&ie=UTF-8`
```
3. Confirm that the message displays and wraps around properly for both IOS and Android native.

cc @isagoico

**Comment by isagoico** [comment]
Created the following TC to cover this scenario in the regression run: 
- [Markdown - Code Block in mobile](https://expensify.testrail.io/index.php?/cases/view/3605909)

Closing the issue, please reopen if needed.
