### ISSUE TITLE
[HOLD for payment 2024-12-03] [Search v1.2] - Pay button appears for report that will be auto-paid and it reappears after clicked

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#52418]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.60-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N/A - new feature, doesn't exist in prod
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Y
**Email or phone of affected tester (no customers):** applausetester+00809892@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
Precondition:
- Admin and employee are in the same workspace.
- Workspace has bank account.
- Employee has personal bank account.
- Add approvals feature is enabled and admin is the approver.

1. Go to staging.new.expensify.com
2. [Employee] Go to workspace chat and submit an expense more than $100.
3. [Admin] Go to Search.
4. [Admin] Click Approve next to the expense, than click Pay.
5. [Admin] Click Pay with Expensify on the expense report RHP.
6. [Employee] Go to workspace chat and submit an expense less than $100 (so that it auto pays later).
7. [Admin] Go to Search.
8. [Admin] Click Approve next to the expense.
9. [Admin] Click Pay.

## Expected Result:
Pay button should not appear for report that will be auto paid (if less than $100).

## Actual Result:
Pay button appears for report that will be auto paid (if less than $100). The button reappears after clicking Pay.

## Workaround:
Unknown

## Platforms:

- [x] Android: Standalone
- [x] Android: HybridApp
- [x] Android: mWeb Chrome
- [x] iOS: Standalone
- [x] iOS: HybridApp
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/1e4c2a7f-50de-44ac-bf88-434b356bf7de

 
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @luacmartins</details>

**Comment by luacmartins** [comment]
I'm not sure if this is an issue. I think admins should have the ability to pay reports even if they have auto pay enabled.

**Comment by luacmartins** [comment]
Ah I see that the video shows a different things than what the OP described. In that case the expense has already been paid, so we shouldn't show the button again. I'll investigate

**Comment by luacmartins** [comment]
This is done
