### ISSUE TITLE
[HOLD for payment 2024-12-03] [Search v1.2] - Approve button disappears after deleting expense in report that has comments

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#52411]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.60-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N, New feature
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:**Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+00809892@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition:
- Add approvals feature is enabled in Workflows
- Admin is the approver
1. Go to staging.new.expensify.com
2. Go to workspace chat
3. Submit two expenses to the workspace chat
4. Go to Search > Outstanding
5. Note that the report has Approve button
6. Go back to expense report in Inbox
7. Send a message in the expense report
8. Delete one of the expenses
9. Go to Search > Outstanding
10. Click on the expense
11. Note that the expense report RHP has Approve button, but it is missing Approve button in Search

## Expected Result:
Approve button will appear for the expense in Outstanding tab after the other expense is deleted

## Actual Result:
Approve button does not appear for the expense in Outstanding tab after the other expense is deleted
Approve button disappears after deleting expense in report that has comments

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Standalone
- [x] Android: HybridApp
- [x] Android: mWeb Chrome
- [x] iOS: Standalone
- [x] iOS: HybridApp
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/37000f25-7099-4f83-977b-bd10b13e0093

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @luacmartins</details>

**Comment by luacmartins** [comment]
I'll take it over as part of Search

**Comment by luacmartins** [comment]
Yea, I agree that it's a backend fix. Gonna remove the blocker since it doesn't break the funcitonality.
