### ISSUE TITLE
Web - Pay someone - Error message still displayed after removing incorrect code

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#52454]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.61.0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Issue was found when executing this PR:** https://github.com/Expensify/App/pull/50835
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/ and log in with a new account
2. Select Something else on the onboarding modal
3. Click on FAB > Start chat and enter an email of another user
4. In 1:1 chat click on + > Pay someone
5. Enter the amount and proceed to the next step
6. Select Pay with Expensify
7. Enter incorrect code
8. Delete the entered code

## Expected Result:
The underscore turns green and the error message disappears

## Actual Result:
The underscore is still red and the error message is still displayed. The error is still displayed after retuning to the previous screen and selecting Pay with expensify again

## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/e4478c36-d41a-4bdb-96e1-6cfb3bec01e5

 
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lakchote** [comment]
It's not a blocker as it doesn't prevent the user from entering a correct code.

**Comment by lakchote** [comment]
The offending PR is https://github.com/Expensify/App/pull/50835

cc @arosiclair

**Comment by arosiclair** [comment]
Fixed in **v9.0.61-1**:

https://github.com/user-attachments/assets/7b5f0fc5-d964-4e6a-829e-eecb567232b7
