### ISSUE TITLE
Web - Pay someone - Console errors displayed after validating account

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#52455]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.61.0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Issue was repro when executing this PR:** 9.0.61.0
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/and log in with a new account
2. Select Something else on the onboarding modal
3. Click on FAB > Start chat and enter an email of another user
4. In 1:1 chat click on + > Pay someone
5. Enter the amount and proceed to the next step
6. Select Pay with Expensify
7. Enter a correct code

## Expected Result:
There are no console errors

## Actual Result:
There are consoles errors after validating account

## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/21e9450f-4a51-4164-b58c-e2bca8152d8f
  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by arosiclair** [comment]
Let's not block on this since it's not really a regression. I'll take over and make sure this gets cleaned up.

**Comment by arosiclair** [comment]
Not reproducible with the latest changes **v9.0.61-1**:

![Screenshot 2024-11-13 at 4 44 14 PM](https://github.com/user-attachments/assets/c94ff735-04d4-4423-b281-beeb8b826398)
