### ISSUE TITLE
OD Modal is not displayed with the same WS created in OD

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#52460]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.61-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N/A - new feature, doesn't exist in prod
**Issue was found when executing this PR:** https://github.com/Expensify/App/pull/51979
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to https://staging.expensify.com/
2. Create a new account in OD.
3. Click on Business from Concierge Chat.
4. Go to settings, and click on Workspace.
5. Tap on the WS Name, click “Plans” and change the WS to Control.
6. Sign in to staging.new.expensify.com with the same account as OD in ND.
7. Open FAB.
8. Click "Create Expense" or "Submit Expense" and submit a manual expense to WS.

## Expected Result:
Modal should be displayed to redirect to the OD.

## Actual Result:
When I click on " Create Expense, " no modal is displayed to redirect to the OD; it allows to submit the expenses without any problem.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/fa9faf60-7847-4b28-b193-66948d0880c2

 
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by IuliiaHerets** [comment]
I marked the issue as deploy as according to [PR](https://github.com/Expensify/App/pull/51979) redirect to OD modal should be displayed

**Comment by mountiny** [comment]
cc @ishpaul777 @puneetlath @suneox can you check this out?

This is a new feature and quite narrow edge case, I think we can demote but feel free to disagree with me

**Comment by puneetlath** [comment]
This doesn't seem like a bug to me. The workspace is policy expense chat enabled because it was first created as a Collect workspace. Feel free to reopen if I've misunderstood.
