### ISSUE TITLE
mWeb - Preferences - Toggle button does not work until refresh the page

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#52464]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.61-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5208354&group_by=cases:section_id&group_order=asc&group_id=229070
**Email or phone of affected tester (no customers):** gocemate+a2804@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to Settings> Preferences> Enable the notification toggle
2. The toggle button does not works appropriately
3. Navigate back to Settings> Preferences
4. Check the toggle status

## Expected Result:
The toggle button should work appropriately in real time

## Actual Result:
Toggle button does not work until refresh the page

## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
https://github.com/user-attachments/assets/f274dbd1-b6f2-4da9-9257-bf0e97f9d139
 
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kadiealexander** [comment]
Android <> ios bug swap with JLi!

**Comment by jliexpensify** [comment]
Nope, no issues on v62. Works perfectly!

Pixel 7, Chrome.
