### ISSUE TITLE
[$250] Login - For particular account, magic code not received

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#52468]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 5.0.61-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in with this expensifail account : [applausetester+chandraguptamaurya@applause.expensifail.com](mailto:applausetester+chandraguptamaurya@applause.expensifail.com)

3. Tap continue

## Expected Result:
Magic code must be received

## Actual Result:
Magic code is not received for this particular account

## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/215bd574-3543-46de-8c43-1c5963706fe5
 
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021856743486758881212</li>
        <li>Upwork Job ID: 1856743486758881212</li>
        <li>Last Price Increase: 2024-11-20</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @abdulrahuman5196</details>

**Comment by isabelastisser** [comment]
Not overdue. @abdulrahuman5196, can you please follow up on the question above? Thanks!

**Comment by abdulrahuman5196** [comment]
hi @isabelastisser , Just checked, Not sure how we can test this issue from frontend, I think we should check in backend logs for this issue.

**Comment by isabelastisser** [comment]
thanks for the context! Changing this to internal.

**Comment by muttmuure** [comment]
Have we checked the logs for this to see if the code is being sent in a job?

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by isabelastisser** [comment]
Not reproducible as of 3 days ago. @mvtglobally will test it again this week, and we can close it if it's still not reproducible.

**Comment by isabelastisser** [comment]
We can no longer reproduce the issue. Closing!
