### ISSUE TITLE
[$250] Search-Currency on Submit Button Reverts to Default breifly Before Expense Submission

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#52474]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.61-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** applausetester+tw345553533@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Sign in with a new account or an account without expenses.
2. Go to "Search" > click "Create Expense" > change currency > add amount.
3. Add user > click the "Submit" button.

## Expected Result:
Currency on the submit button should remain as selected after changing the currency and submitting the expense.

## Actual Result:
Currency briefly reverts to the default on the submit button before the expense is submitted.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/b7a68f9b-d315-46a9-804b-e6b20879d0e4

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021861166191086746017</li>
        <li>Upwork Job ID: 1861166191086746017</li>
        <li>Last Price Increase: 2024-12-02</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @shubham1206agra</details>

**Comment by FitseTLT** [comment]
might be [dupe](https://github.com/Expensify/App/issues/52196)

**Comment by johncschuster** [comment]
Thanks for the heads up, @FitseTLT! I'll take a look at that one tomorrow!

**Comment by johncschuster** [comment]
@IuliiaHerets I'm confused by this bug report. When I review the video, it looks like the expense was created and the user selecting a new currency (away _from_ `ETB` and to `USD`). Then, the submit button appropriately reflected the symbol for `USD`.

Am I misunderstanding what you're reporting? If so, can you please elaborate?

**Comment by johncschuster** [comment]
@IuliiaHerets Got it. Thanks for clarifying that. Can you please clarify the OP so that's made more clear?

**Comment by IuliiaHerets** [comment]
@johncschuster Tester use Mac 13.6

**Comment by IuliiaHerets** [comment]
@shubham1206agra Tester cannot reproduce the issue anymore, build - v9.0.67-1 

https://github.com/user-attachments/assets/e7649301-725e-484a-9d55-330865ac692d
