### ISSUE TITLE
[$250] Android - Chat- Group name not saved if changed offline and not here tab when opening header

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#52484]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.61-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Y
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Open the Expensify app.
2. Turn off internet connection.
3. Tap on FAB and select "Start Chat"
4. Add a few users and start a group chat.
5. Tap on group´s header.
6. Tap on the group´s name and change it.
7. Return to chat.
8. Turn on internet connection.
9. Verify that the new name is still displayed on header.
10. Tap on header.
11. Verify all the information is properly displayed.

## Expected Result:
After creating group offline, the user should be able to change it´s name and the new one should be saved after recovering internet connection.

## Actual Result:
After creating a new group offline and changing the name, the new name is not saved when recovering internet connection, and also, tapping on header, leads to "Hmm, it´s not here" tab.

## Workaround:
Unknown

## Platforms:

- [x] Android: Standalone
- [x] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/de3083f5-4718-4b8b-906f-99c9d5f0f4a9
  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021856723825193050849</li>
        <li>Upwork Job ID: 1856723825193050849</li>
        <li>Last Price Increase: 2024-11-13</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @ZhenjaHorbach</details>

**Comment by Julesssss** [comment]
Users can still use the chat in this case; they are just unable to rename existing chats if they are offline IMMEDIATELY after creating them. We can update existing group chat headers while offline without any issues. 

So I am demoting.

**Comment by Julesssss** [comment]
I can't see any obvious candidates for this regression on the[ checklist](https://github.com/Expensify/App/issues/52440) 😕

**Comment by Shahidullah-Muffakir** [comment]
> I can't see any obvious candidates for this regression on the[ checklist](https://github.com/Expensify/App/issues/52440) 😕

It is happening in prod also.

**Comment by twisterdotcom** [comment]
Let's close and get on with our days.
