### ISSUE TITLE
[$250]  Android - Offline created chat disappear when come back online

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#52498]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.61-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5211763&group_by=cases:section_id&group_order=asc&group_id=296775
**Email or phone of affected tester (no customers):** gocemate+a2807@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Open New dot hybrid app
2. Go offline
3. Go to FAB> Start chat> Enter gmail user with no previous conversation> Finish the flow
4. Verify you see the chat in LHN
5. Go online

## Expected Result:
Newly created chat in offline should remain when user come back online

## Actual Result:
Offline created chat disappear when come back online

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Standalone
- [x] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/b453c5e5-860a-40fa-bc4a-40215bb416cd

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021858389248839438677</li>
        <li>Upwork Job ID: 1858389248839438677</li>
        <li>Last Price Increase: 2024-11-25</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @eVoloshchak</details>

**Comment by eVoloshchak** [comment]
Not overdue, this is awaiting proposals

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)
