### ISSUE TITLE
[HOLD for payment 2024-12-05] [$250] Update headers in certain flows to match their screens

### ISSUE THREAD

**Issue by jamesdeanexpensify** [Expensify/App#52502]
## Background
Coming from [this Slack convo](https://expensify.slack.com/archives/C07HPDRELLD/p1731295478449439), we'd like to update the header copy in certain product flows to more closely match what's happening in the associated screen.

## Which flows to update
- [ ] **Track expense**
- [ ] **Submit expense**
- [ ] **Create expense**
- [ ] **Split expense**
- [ ] **Pay (user)**

## Where to find the specific details
https://docs.google.com/document/d/1IAnUtW4JzLApeMDuO1-GPD8Y11vPQl9AsFiTOiWp2bM/edit?tab=t.0
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021860038796835570004</li>
        <li>Upwork Job ID: 1860038796835570004</li>
        <li>Last Price Increase: 2024-11-22</li>
<li>Automatic offers: </li>
<ul>
<li>c3024 | Reviewer | 105201449</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @kadiealexander</details>

**Comment by jamesdeanexpensify** [comment]
Updates start [here](https://expensify.slack.com/archives/C07HPDRELLD/p1732228888238429?thread_ts=1731295478.449439&cid=C07HPDRELLD).

**Comment by c3024** [comment]
Raised a PR #53004.

🎀 👀 🎀 for internal engineer for PR final review.

**Comment by kadiealexander** [comment]
- [ ] Contributor: @c3024 paid $250 via Upwork ([Offer link](https://www.upwork.com/nx/wm/offer/105201449))
- [ ] Contributor+: @dukenv0307 owed $250 via NewDot

**Comment by kadiealexander** [comment]
@dukenv0307 please complete the checklist!

**Comment by JmillsExpensify** [comment]
$250 approved for @dukenv0307
