### ISSUE TITLE
Spacing between "you've started a free trial" subject and body seems too wide

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#52516]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.62-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @jamesdeanexpensify 
**Slack conversation** (hyperlinked to channel name): [Expensify-convert](https://expensify.slack.com/archives/C07HPDRELLD/p1731537265197409)

## Action Performed:
1. Create an account
2. Subscribe for free trial
## Expected Result:
There should be single spacing between the "You've started a free trial!"

## Actual Result:
 The spacing between the "You've started a free trial!" subject and body seems a bit too wide:
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details>

![2024-11-13_14-31-46](https://github.com/user-attachments/assets/a820ff2c-f7b8-4186-b0a6-5f46436b33f2)

![Snip - (1) New Expensify - Google Chrome (4)](https://github.com/user-attachments/assets/a84d184c-4b5f-4ee2-a1e6-262216606af7)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by alexpensify** [comment]
I've reviewed the Slack convo-- this one is a Hot Pick (Internal)!

**Comment by techievivek** [comment]
This will be a quick fix.

**Comment by danielrvidal** [comment]
I think this can be closed, right? Please reopen if needed.

**Comment by techievivek** [comment]
Aaah, yes, the PR is already QAed and the bug is fixed.
