### ISSUE TITLE
OpenReport API return `iouReportID` as `null` for policy expense chat after we cancel payment

### ISSUE THREAD

**Issue by nkdengineer** [Expensify/App#52527]
**Original GH:** https://github.com/Expensify/App/issues/49801

## Action Performed:
Break down in numbered steps
Precondition: Create a workspace, add an employee to it, upgrade to control plan, enable workflow, turn on the "Make or track payments" option

1. EMPLOYEE: Submit a manual expense to the workspace
2. ADMIN: Pay the expense with the "pay elsewhere" option
3. ADMIN: Cancel the expense as the workspace admin
4. ADMIN: As the workspace admin, go back to the policy expense report in the LHN

## Expected Result:

OpenReport API returns the correct `iouReportID` for policy expense chat after we cancel payment. 

## Actual Result:

OpenReport API returns `iouReportID` as `null` for policy expense chat after we cancel payment. That prevents us from submitting new expenses in the canceled expense report
## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

https://github.com/user-attachments/assets/16abb637-1be1-4c97-9a9b-0e12678eacb6

</details>

**Comment by nkdengineer** [comment]
cc @tgolen

**Comment by tgolen** [comment]
Thanks @nkdengineer. I'll look into this one @blimpich unless you feel strongly :D

**Comment by tgolen** [comment]
@nkdengineer I'm trying to make sure I reproduce this properly. Can you watch this video and see if this is the correct `OpenReport` request I should be looking at?

From the reproduction steps in the issue it says to "go back to the policy expense report" I'm not quite sure if this is the right one or not.

https://github.com/user-attachments/assets/3013b1d0-36a6-4115-b207-74359b009c15

**Comment by nkdengineer** [comment]
@tgolen I already have a video in the description of the OP.

**Comment by tgolen** [comment]
Ah, I see. OK, thanks.

**Comment by tgolen** [comment]
OK, [I've been chatting in Slack internally](https://expensify.slack.com/archives/C03TQ48KC/p1731608137925029) with @aldo-expensify and I think we found the problem on the backend that is causing this. We haven't settled on a solution yet.

We determined that this started happening after [this PR](https://github.com/Expensify/Auth/pull/12717) from @mountiny and we need to figure out why.

**Comment by tgolen** [comment]
# Daily Update:
- The result of the thread was that we tracked it down to the `autoReporting` setting of a policy is switched to `false` when upgrading a workspace from collect to control. This is a bug and the setting should remain as `true`. I verified that when the setting is `true`, then the bug here is fixed.

### Next Steps
- @Beamanator will be fixing this as part of https://github.com/Expensify/Expensify/issues/411558 and this issue can be closed for now.
