### ISSUE TITLE
Expense - App turns to blank page with console error after deleting expense

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#52531]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.62-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Email or phone of affected tester (no customers):** applausetester+23233@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace chat.
3. Submit an expense to the workspace chat.
4. Click on the expense preview.
5. Click on the report header.
6. Click Delete expense.
7. Delete the expense.

## Expected Result:
App returns to workspace chat after deleting the expense.

## Actual Result:
App turns to blank page with console error after deleting expense.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
[1411.txt](https://github.com/user-attachments/files/17746229/1411.txt)

https://github.com/user-attachments/assets/51dd5962-04d8-4876-b540-9b5f6d0ab6f3
 
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by francoisl** [comment]
Yeah, tested on v9.0.62-4 and it's no longer reproducible.
