### ISSUE TITLE
Search -"To" filter is auto-populated in the search query for invoice room

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#52532]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.62-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Email or phone of affected tester (no customers):** applausetester+290310@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to FAB > Send invoices.
3. Send an invoice to anyone.
4. Go to invoice room.
5. Click on the search icon on the top right.
6. Click Search in.

## Expected Result:
There will be no "To" filter in the search query.

## Actual Result:
There is "To" filter in the search query.

This issue only happens in invoice room. In workspace chat, there is no "To" filter in the search query.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/a2ea77b5-d2d2-4fce-b115-ae10e2efa3fb
 
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Kicu** [comment]
I believe related to this issue and comment? https://github.com/Expensify/App/issues/51964#issuecomment-2460176150
@289Adam289 was working on this and also agrees that we expect this behavior

**Comment by luacmartins** [comment]
This is the expected behavior. Closing.
