### ISSUE TITLE
[Awaiting checklist] [$250] Web - Concierge - Onboarding tasks in Concierge chat is duplicated when switch chat

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#52543]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.62-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5222784&group_by=cases:section_id&group_order=asc&group_id=229043
**Email or phone of affected tester (no customers):** gocemate+a2824@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Create a new gmail user
2. Verify that the "What do you want to do today?" modal appears
3. Select the purpose "Chat and split expenses with friends"
4. Click on "Continue"
5. Verify that the "What’s your name?" modal appears
6. Enter any names
7. Click on "Continue"
8. Close the video modal
9. Open the Concierge chat
10. Verify that the app has generated a welcome message and onboarding tasks in Concierge chat
11. Open the Concierge chat again

## Expected Result:
A welcome message and onboarding tasks in Concierge chat should be present

## Actual Result:
A welcome message and onboarding tasks in Concierge chat is duplicated when switch chat

## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/9feee508-5b83-418f-9ef6-fe617df7c517

  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021857103016023822782</li>
        <li>Upwork Job ID: 1857103016023822782</li>
        <li>Last Price Increase: 2024-11-14</li>
<li>Automatic offers: </li>
<ul>
<li>allgandalf | Contributor | 104901467</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @allgandalf</details>

**Comment by twisterdotcom** [comment]
Agree, I recreated this. It's very odd to see it twice. We only complete `CompleteGuidedSetup` once, so I don't understand why navigating back to chat shows it twice.

https://github.com/user-attachments/assets/d9cb79d9-125b-4bb6-8026-7790a73b4cae

I think this one should be `Hourly` and block the deploy.

**Comment by twisterdotcom** [comment]
Posted in Slack: https://expensify.slack.com/archives/C01GTK53T8Q/p1731589469103229?thread_ts=1731582255.236159&cid=C01GTK53T8Q

Not sure how best to continue helping here. @Gonals lmk if you have any ideas, otherwise we can get some `External` eyes and pay out for it.

**Comment by Gonals** [comment]
@blazejkustra, thanks! Keep me posted!

**Comment by blazejkustra** [comment]
Sure! I might have a fix today, I'll update in max 2h

**Comment by Gonals** [comment]
Neat. This is a deploy blocker (and today is Thursday), so we pretty much need a fix today. Let me know if you can't prioritize this and I'll find someone/do it myself

**Comment by Gonals** [comment]
(or we can revert the PR that caused it if we can't figure out a fix today)

**Comment by Gonals** [comment]
cc @francoisl

**Comment by blazejkustra** [comment]
I think I have a fix, will post a PR and do more testing in a moment! cc @Gonals 

https://github.com/user-attachments/assets/b124c69b-5f4c-4d1d-97ed-4276efe760d3

**Comment by blazejkustra** [comment]
@Gonals PR is ready for review https://github.com/Expensify/App/pull/52585

The problem was that we generated onboarding messages twice, first for onboarding flow and then first time a report was opened. Now we check `NVP_ONBOARDING` so that messages are never duplicated.

**Comment by twisterdotcom** [comment]
We can just pay out for this when the time comes.

**Comment by twisterdotcom** [comment]
Payment Summary:

- @blazejkustra **does not** require payment (Contractor)
- @allgandalf paid $250 [here](https://www.upwork.com/nx/wm/offer/104901467) (Contributor)

**Comment by twisterdotcom** [comment]
No, we don't.
