### ISSUE TITLE
Concierge - Start a chat task is marked as comleted when select Chat and split expenses option

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#52544]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.62-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5222784&group_by=cases:section_id&group_order=asc&group_id=229043
**Email or phone of affected tester (no customers):** gocemate+a2827@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Create a new gmail user
2. Verify that the "What do you want to do today?" modal appears
3. Select the purpose "Chat and split expenses with friends"
4. Click on "Continue"
5. Verify that the "What’s your name?" modal appears
6. Enter any names
7. Click on "Continue"
8. Close the video modal
9. Open the Concierge chat

## Expected Result:
Start a chat option should not be mark as completed

## Actual Result:
Start a chat task in Concierge chat is mark as completed even new chat has not be created yet

## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/873cfebc-502a-40d0-9fda-63c5807a31a2
  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by deetergp** [comment]
This is expected behavior. Closing.
