### ISSUE TITLE
[HOLD for payment 2024-12-09] [$250] QBO - "Reconciliation account" disappears after selecting it

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#52548]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.62-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Issue was found when executing this PR:** https://github.com/Expensify/App/pull/51359
**Email or phone of affected tester (no customers):** 
**Issue reported by:** Applause Internal Team

## Action Performed:
Preconditions:

- Use a new Gmail account.
- Expensify Card is enabled.
- Bank account is added in Expensify Card page.
- Workspace is connected to QBO.

1. Open the app
2. Navigate to Workspace settings - Accounting - Card reconciliation
3. Enable "Continuous Reconciliation"
4. Click on your added bank account

## Expected Result:
"Reconciliation account" should still be visible.

## Actual Result:
"Reconciliation account" disappears after selecting it.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/853c67b3-22a6-413e-9901-2a8e51ecb8b4
  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021860984129964489529</li>
        <li>Upwork Job ID: 1860984129964489529</li>
        <li>Last Price Increase: 2024-11-25</li>
<li>Automatic offers: </li>
<ul>
<li>DylanDylann | Reviewer | 105055923</li>
<li>daledah | Contributor | 105055925</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @trjExpensify</details>

**Comment by trjExpensify** [comment]
Another one for your eyes @mountiny @MariaHCD @madmax330 @nkuoch @allgandalf @DylanDylann

**Comment by trjExpensify** [comment]
Gotcha, continuousReconciliation is only a feature of the Expensify Card.

**Comment by DylanDylann** [comment]
@trjExpensify I already worked on Card reconciliation account setting Page [before](https://github.com/Expensify/App/pull/44968) (when implementing the Expensify Card). Let me take this issue

**Comment by DylanDylann** [comment]
I agreed with @daledah about [Bug 1](https://github.com/Expensify/App/issues/52548#issuecomment-2478352713), in case the user go to accounting page right after login successful we also need to display the bank account list

About the main bug on OP, @daledah @etCoderDysto could anyone help to explain why the API failed?

**Comment by DylanDylann** [comment]
@mountiny @MariaHCD Tag you here because it relates to Expensify Card. In this issue, we have 2 problems:
1.  In case the user go to Card reconciliation page right after login successful we also need to display the bank account list. To do that, `private_expensifyCardSettings_` is needed to been available when user going to Card reconciliation Page. Currently, It is only available after we call API OpenPolicyExpensifyCardsPage (going to Expensify Card Page)

2. To setup settlementBankAccountID we have two ways:
- In ExpensifyCard, we use ConfigureExpensifyCardsForPolicy API and It works well 




<img width="355" alt="Screenshot 2024-11-18 at 12 01 58" src="https://github.com/user-attachments/assets/d11934f6-edcb-4133-ac60-d7be561f5f8a">
<img width="353" alt="Screenshot 2024-11-18 at 12 02 05" src="https://github.com/user-attachments/assets/b7aa0243-c542-494a-9c38-7956fece90ee">

- In Card reconciliation page, we use UpdateCardSettlementAccount API and It is failed

<img width="424" alt="Screenshot 2024-11-18 at 12 01 34" src="https://github.com/user-attachments/assets/4598cbbb-011d-4e15-8dde-e0a75b0d54ff">
<img width="428" alt="Screenshot 2024-11-18 at 12 01 41" src="https://github.com/user-attachments/assets/440949bf-2cd2-46a8-8ee0-b6a1d5cf50ca">

**Comment by trjExpensify** [comment]
> @trjExpensify I already worked on Card reconciliation account setting Page [before](https://github.com/Expensify/App/pull/44968) (when implementing the Expensify Card). Let me take this issue

Assigned you to help progress!

**Comment by mountiny** [comment]
Maria is out assigning. I am also working partial day @nkuoch in case you could take a look earlier

**Comment by mountiny** [comment]
@DylanDylann What bank accounts did you use to try it? 

Did you provision the policy first and then you tried switching the bank account? You will have to use a different bank account for that and there is only one testing bank account you have access to right? So did you try switching to different bank account?

**Comment by DylanDylann** [comment]
Ahh thanks for pointing out that

**Comment by DylanDylann** [comment]
@mountiny You mean that if we haven't set up a settlement bank account, we shouldn't have access to `Select Reconciliation account page`.

**Comment by mountiny** [comment]
@DylanDylann Yeah, I think if you do not have bank account set up, there is nothing to choose there. But also you cannot have expensify cards without settlement bank account

**Comment by DylanDylann** [comment]
@mountiny  I think we should disable and lock the toggle if users haven't setup the settle bank account like this. Wdyt?

<img width="1212" alt="Screenshot 2024-11-22 at 16 25 02" src="https://github.com/user-attachments/assets/735fb644-f738-45bf-b65d-528272c36973">

**Comment by mountiny** [comment]
Discussing internally cc @trjExpensify @JmillsExpensify 

Maybe we should lock it or even hide the Expensify card reconciliation option if you do not have exepnsify cards. Or show some graphics CTA for the user in RHP to inform them about ECard option

**Comment by trjExpensify** [comment]
>hide the Expensify card reconciliation option if you do not have exepnsify cards.

I thought that was the logic? 😕

**Comment by JmillsExpensify** [comment]
Same, I thought we hid this when it didn't apply.

**Comment by mountiny** [comment]
@DylanDylann there is the answer, lets hide the button and add lock the toggle in case of a deeplink to that RHP page if cards are not provisioned that is no workspaceAccountID + areExpensifyCardEnabled

**Comment by DylanDylann** [comment]
@mountiny Should we open this issue for external contributors? If yes, @daledah's [proposal](https://github.com/Expensify/App/issues/52548#issuecomment-2478352713) looks fine

**Comment by trjExpensify** [comment]
Waiting for the PR to go to prod, melv.

**Comment by trjExpensify** [comment]
👋 let's get the checklist in here, please. Thanks!

**Comment by DylanDylann** [comment]
@trjExpensify It means selecting bank acocunt here

<img width="1512" alt="Screenshot 2024-12-10 at 16 56 34" src="https://github.com/user-attachments/assets/47899462-4984-40f5-b501-488f44aa1f4e">

**Comment by trjExpensify** [comment]
Gotcha, can we make sure the test makes sense for someone to follow? It sounds like you need to add a VBBA first for this test, right? Here's a suggested edit: 

1. Create a workspace 
2. Go to More features > Enable `Workflows`, `Accounting` & `Expensify Card`
3. Go to Workflows > Make or track payments > add a VBBA 
5. Go to Accounting > Connect to QBO successfully 
6. **Verify** that "Card reconciliation" is not an option displayed (only `Import`, `Export`, `Advanced`). 
7. Copy this URL and paste it in the browser: <insert URL> (CC: @DylanDylann what's the URL?)
10. **Verify** that you land on a `Not found page`
11. Go to Expensify Card > Click `Issue New Card` > Select the linked bank account
12. Go to Accounting
13. **Verify** that the `Card reconciliation` option is displayed now.

**Comment by DylanDylann** [comment]
@trjExpensify Thanks for your reminder. I already updated the test steps

**Comment by trjExpensify** [comment]
Nice, thanks! 

Payment summary as follows: 

- $250 to @DylanDylann for the C+ review
- $250 to @daledah for the fix

Paid, closing!
