### ISSUE TITLE
[$250] Web - Guided Setup - No email received for a new account added in a group chat

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#52540]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.62-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Issue was found when executing this PR:** https://github.com/Expensify/App/pull/46052
**Email or phone of affected tester (no customers):** nathanmulugetatesting+2078@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Create a group chat
3. Invite a non existent account into the group
4. As the invitee open email and wait for an invitation

## Expected Result:
Invitation email is received

## Actual Result:
No invitation email is received

## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/435e487f-7e00-4433-a541-762bff2c5eeb

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021857184283440567369</li>
        <li>Upwork Job ID: 1857184283440567369</li>
        <li>Last Price Increase: 2024-11-14</li>
    </ul>
</details>

**Comment by sakluger** [comment]
I'm going to add this to the `#convert` project because it has to do with inviting new users to NewDot.

**Comment by mountiny** [comment]
cc @blazejkustra @deetergp https://github.com/Expensify/App/pull/46052

**Comment by blazejkustra** [comment]
Thanks @mountiny for bumping 😄 

I think it is likely a backend issue, and it was known before merging ([here](https://github.com/Expensify/App/pull/46052#issuecomment-2477063168) more context). @deetergp are you going to investigate this?

**Comment by sakluger** [comment]
Switching to internal. If this does end up being front end, let me know and we can switch back to external.

**Comment by deetergp** [comment]
I'll look into it @sakluger but I'm going to bump it down to a weekly. The invited users still get unread message notifications after 10 mins when there's other activity in the chat.

**Comment by deetergp** [comment]
I haven't been able to get to this one and probably won't be able to till Monday.

**Comment by deetergp** [comment]
Same status as last week—too many other higher priorities.

**Comment by deetergp** [comment]
We had a discussion [here](https://expensify.slack.com/archives/C07HPDRELLD/p1733793711746069) and it sounds like we are okay with how it works currently. So I am going to close this, but feel free to reopen if you disagree.
