### ISSUE TITLE
[HOLD for payment 2024-11-22] [$50] Workspace- App crashes when submitting an expense in OD after creating a new Workspace

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#52542]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.62-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Email or phone of affected tester (no customers):** applausetester+shsb22cq11@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
Prerequisite
Make sure you are signed in the same account in both ND and OD
You already have an existing workspace and an existing expense submitted
1. Navigate to OD
2. Create a new collect workspace
3. Navigate to expenses tab > Create a new manual expense > Finish the flow
4. Navigate to the tab where you are signed in ND

## Expected Result:
App does not crash and the expense is submitted successfully

## Actual Result:
App crashes

## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
[1411_1.txt](https://github.com/user-attachments/files/17747306/1411_1.txt)

https://github.com/user-attachments/assets/f05cdfe3-52b8-47a3-a84b-f816941d016a

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021857012145307783614</li>
        <li>Upwork Job ID: 1857012145307783614</li>
        <li>Last Price Increase: 2024-11-14</li>
<li>Automatic offers: </li>
<ul>
<li>nkdengineer | Contributor | 104896419</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @greg-schroeder</details>

**Comment by mountiny** [comment]
$50 For identifying the offending pr

**Comment by nkdengineer** [comment]
@mountiny It comes from [here](https://github.com/Expensify/App/pull/52478).

**Comment by nkdengineer** [comment]
The report can be `undefined`. I can raise a quick fix for this.

https://github.com/Expensify/App/blob/75dd17a60ce33e6c222baf3f17f0f05d307222fa/src/libs/ReportUtils.ts#L6354

**Comment by mountiny** [comment]
@nkdengineer Sounds good, thanks!

**Comment by mountiny** [comment]
Plot twist, @allgandalf already has PR to fix this up https://expensify.enterprise.slack.com/archives/C01GTK53T8Q/p1731582509875719?thread_ts=1731581014.860089&channel=C01GTK53T8Q&message_ts=1731582509.875719

**Comment by mountiny** [comment]
Assigning @iwiznia was he did lots of work on the linked pr

**Comment by nkdengineer** [comment]
@mountiny Will I receive $50 for offending PR?

**Comment by mountiny** [comment]
> Will I receive $50 for offending PR?

I think this is a thin line because the fix was already at work before you identified the PR, and in these cases, we usually do not compensate. I hope that is fine with you

**Comment by nkdengineer** [comment]
Thanks, no problem.
