### ISSUE TITLE
[HOLD for payment 2024-12-05] [Company cards]  The card name after assignment is not showing correctly

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#52558]
Coming from [here](https://expensify.slack.com/archives/C06ML6X0W9L/p1731525096418759).

When admin assigns a card on the workspace the card name is not showing correctly on the card details page and we are not returning it correctly.

Also lets remove the unused card images https://github.com/Expensify/App/pull/52389#issuecomment-2474819756

<details><summary>Issue Owner</summary>Current Issue Owner: @adelekennedy</details>

**Comment by koko57** [comment]
I can work on that!

**Comment by mountiny** [comment]
Backend pr raised

**Comment by mountiny** [comment]
@koko57 this should be ready to test in staging. Essentially we are saving the name now for the admin's nvp, so the admins should be able to see the card names correctly after the assignment. The assignee on the other hand does not have this name, but we discussed this in slack.

@allgandalf would you be able to retest in staging?

**Comment by koko57** [comment]
@mountiny so is there any change required on the FE?

**Comment by koko57** [comment]
the changes I've made for this PR make a fallback to the "[UserName]'s card". I've also noticed that for Expensify Card we have "[UserName]'s Card" with the "Card" uppercased. I checked this in the docs, the lowercased version is the proper one, sorry it's my fault. It'll be kind of a breaking change when I change it for the Exfy Card? 

For the default name in the card details page - I can display the fallback name but for the Edit card name page I would do some hard logic to have it displayed as the input's default value

**Comment by mountiny** [comment]
Discussed in DM, we can change the name to `card`

**Comment by mountiny** [comment]
@koko57 are you going to update the card name as part of this issue?

**Comment by koko57** [comment]
yes, I can do that

**Comment by joekaufmanexpensify** [comment]
>the changes I've made for this PR make a fallback to the "[UserName]'s card". I've also noticed that for Expensify Card we have "[UserName]'s Card" with the "Card" uppercased. I checked this in the docs, the lowercased version is the proper one, sorry it's my fault. It'll be kind of a breaking change when I change it for the Exfy Card?

Agree with Vit, let's change the c in card to lowercase. LMK if any other questions!

**Comment by koko57** [comment]
opening for the review (no screenshots for android though, the app is built but stuck on the SplashScreen) https://github.com/Expensify/App/pull/52735

maybe @allgandalf or @DylanDylann can review it?

**Comment by mountiny** [comment]
Merged

**Comment by mountiny** [comment]
We will handle the payments for these in bulk after the project is done, no regression tests specifically forthis change is required, we will add tests with Joe in general
