### ISSUE TITLE
[HOLD for payment 2024-11-26] [Comapny cards] Do not show the Expensify cards option if the policy is not provisioned for it

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#52552]
Coming from [here](https://expensify.slack.com/archives/C06ML6X0W9L/p1731525179027439)

We are showing the expensify card as an option when creating card from the workspace member profile even if the policy is not provisioned for expensify cards.

<details><summary>Issue Owner</summary>Current Issue Owner: @jliexpensify</details>

**Comment by DylanDylann** [comment]
@mountiny I can help on this issue

**Comment by koko57** [comment]
actually, I think @allgandalf should have priority as was working with me in this thread 😃 But I see that a reviewer was auto-assigned

**Comment by jliexpensify** [comment]
Thank you @allgandalf!
