### ISSUE TITLE
RBR doesn't display immediately when a receipt with a modified amount is submitted

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#52557]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.62-2
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Issue was found when executing this PR:** https://github.com/Expensify/App/pull/52478
**Email or phone of affected tester (no customers):** applausetester+bm231@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
Preconditions:
- Workspace is created.
- Delay submission is set to Manual.
1. Go to https://staging.new.expensify.com/

2. Navigate to the workspace chat.
3. Scan a receipt and wait until scanning completes.
4. Open the preview and modify the amount.
5. Return to the main chat and click the Submit button.

## Expected Result:
The RBR should appear immediately.

## Actual Result:
The RBR does not appear, even when navigating to another chat and returning. It only reappears after opening the expense and then returning back.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/71c897e5-9336-4d86-ba33-26e68018446f

 
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by dangrous** [comment]
oh no does that mean we're going to have to revert a revert of a revert

**Comment by iwiznia** [comment]
Looking into this

**Comment by iwiznia** [comment]
Context https://expensify.slack.com/archives/C03TQ48KC/p1731601123347109?thread_ts=1731598521.545959&cid=C03TQ48KC

**Comment by francoisl** [comment]
So now the RBR appears immediately after you upload the receipt, while it's still scanning. Is that expected?

<img width="1512" alt="image" src="https://github.com/user-attachments/assets/5c095526-98fe-448e-812c-4271c80a1997">

**Comment by kavimuru** [comment]
Not reproducible 

https://github.com/user-attachments/assets/e8a2e7c5-82a3-4466-9c60-2d073f466124

**Comment by iwiznia** [comment]
Nice the fix worked then
