### ISSUE TITLE
[HOLD for payment 2024-11-29] [Company Cards] Update the Amex cards format

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#52551]
Coming from [here](https://expensify.slack.com/archives/C06ML6X0W9L/p1731525071415359)

Lets update the Amex cards format to show as 4 digits, 6 digits, 5 digits because they are 15 digits number. This ensure they will look nice in the product.

<details><summary>Issue Owner</summary>Current Issue Owner: @zanyrenney</details>

**Comment by VickyStash** [comment]
Hi, I'm Viktoryia from Callstack - expert contributor group - and I would like to work on this issue.

**Comment by DylanDylann** [comment]
@mountiny I can help on this issue

**Comment by VickyStash** [comment]
**Updates:** 
- Implemented updates and opened the [Draft PR](https://github.com/Expensify/App/pull/52578).

**TODOs:**
- Add screenshots for mobile platforms
- Add unit tests for [maskCardNumber](https://github.com/Expensify/App/pull/52578/files#diff-19159f02504c955e4ad7285cc48ac7bfcc0e1cfbec74b371af5cb877311cc9b8R141) function.

I think the PR will be ready for the review tomorrow in the first part of the day.

**Comment by VickyStash** [comment]
The [PR](https://github.com/Expensify/App/pull/52578) is ready for the review!

**Comment by mountiny** [comment]
Seems like we are going to update the card formats again and show only the last 4 pans across the App so I dont think we need regression tests for this change yet, we will handle that in the follow up
