### ISSUE TITLE
[$250] QBO - RBR on expensify card without any indication or errors inside

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#52555]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.62-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Issue was found then executing this PR:** https://github.com/Expensify/App/pull/50864
**Email or phone of affected tester (no customers):** nathanmulugetatesting+2090@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Create a new workspace
3. Connect bank account and enable Expensify Card
4. Go to Expensify Card page
5. Click New Issue card button
6. Connect bank account
7. Enable accounting and connect to QBO online
8. Click on Card reconciliation
9. Enable continuous reconciliation
10. Select bank account

## Expected Result:
No RBR on Expensify card and if there is an RBR there should be an error message

## Actual Result:
RBR without any error message shown on Expensify card LHN

## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/729f0150-2697-4ef3-a73e-4d2383c789bc
  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021858452638935929929</li>
        <li>Upwork Job ID: 1858452638935929929</li>
        <li>Last Price Increase: 2024-11-25</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @rushatgabhane</details>

**Comment by VictoriaExpensify** [comment]
It looks like this is being[ fixed elsewhere](https://github.com/Expensify/App/issues/52548#issuecomment-2476214544). Closing
