### ISSUE TITLE
[HOLD for payment 2024-11-29] [$250] [Workspace feeds - Direct] Search page `Card` filter should show card name

### ISSUE THREAD

**Issue by JmillsExpensify** [Expensify/App#52554]
At the moment if you try to search for direct workspace cards, we show the card feed name, like so. 

![CleanShot 2024-11-14 at 13 11 52@2x (1)](https://github.com/user-attachments/assets/537e4831-b96e-4c97-b183-16945cdfe9d2)

Instead, we should be showing the card name in the `Card` filter list for search. 
![CleanShot 2024-11-14 at 13 37 37@2x](https://github.com/user-attachments/assets/4c7cdddc-1f73-4c96-8d41-61899ff93521)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021857041070045717217</li>
        <li>Upwork Job ID: 1857041070045717217</li>
        <li>Last Price Increase: 2024-11-14</li>
<li>Automatic offers: </li>
<ul>
<li>allgandalf | Contributor | 104897589</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @JmillsExpensify</details>

**Comment by narefyev91** [comment]
Hi, I'm Nicolay from Callstack - expert contributor group - and I would like to work on this issue.

**Comment by mountiny** [comment]
@allgandalf can you please complete a checklist and suggest a test?

**Comment by JmillsExpensify** [comment]
Upwork contract paid out and regression test created. We should be good here.
