### ISSUE TITLE
[HOLD for payment 2024-11-29] [$250] Add a loader to the cards page while waiting for cards collection and feed settings 

### ISSUE THREAD

**Issue by JmillsExpensify** [Expensify/App#52559]
One pattern we use extensively in other pages is a little spinner to help the user understand that we don't quite yet have all the data, and then one we do, the spinner disappears and the content shows. Here's how that looks for the categories page in the workspace editor. 

![CleanShot 2024-11-14 at 14 28 44](https://github.com/user-attachments/assets/73f6c944-c232-4b2e-be88-c954b4d7a11d)

All in all, we need to:

 - **If the user is online**: Show a spinner while we wait for a 200 response from cards collection and feed settings
 - **If the user is offline**: Don't show the spinner and show whatever data we have. 
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021857059797769493830</li>
        <li>Upwork Job ID: 1857059797769493830</li>
        <li>Last Price Increase: 2024-11-14</li>
<li>Automatic offers: </li>
<ul>
<li>allgandalf | Contributor | 104898980</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @JmillsExpensify</details>

**Comment by narefyev91** [comment]
Hi, I'm Nicolay from Callstack - expert contributor group - and I would like to work on this issue.

**Comment by JmillsExpensify** [comment]
Removing `Help Wanted` since we only need C+ help on this issue.
