### ISSUE TITLE
Expense - RBR appears on the expense preview when there is no violation

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#52562]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.62-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Y
**Email or phone of affected tester (no customers):** applausetester+kh0311009@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to FAB > Submit expense.
3. Enter amount > Next.
4. Select any user with no unsettled expense.
5. On confirmation page, add a receipt.
6. Submit the expense with receipt.
## Expected Result:
Describe what you think should've happened

## Actual Result:
RBR will not appear on the expense preview in the main chat if there is no violation (production behavior).

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

- [x] Android: Standalone
- [x] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/6c85f31c-89a4-4430-be12-053f3cdb8939

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kavimuru** [comment]
Not reproducible

https://github.com/user-attachments/assets/6725a079-dd69-416d-af38-f461938a8ef8

**Comment by iwiznia** [comment]
Nice, the fix worked then
