### ISSUE TITLE
Expense - The app crashes when deleting an error about creating a distance expense

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#52560]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.62-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5222476
**Email or phone of affected tester (no customers):** sustinov@applausemail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Open New Expensify app
2. Log in with a new HT account
3. Create a WS
4. Go to the WS room
5. Disconnect the internet
6. Click + Menu > Submit expense
7. Select Distance option
8. Enter a vague start location, random characters should also work
9. Enter a vague finish location, random characters should also work
10. Finish the submit creation flow
11. Turn on the internet
12. Remove the distance expense creation error

## Expected Result:
If the error about creating a distance expense is cleared, the application should crash.

## Actual Result:
The app crashes when deleting an error about creating a distance expense

## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/a50a11aa-e287-4f70-8124-563bc6135aff
 
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mountiny** [comment]
@allgandalf, can you please link this issue to your PR and include tests for this so QA can confirm once CPed?

**Comment by puneetlath** [comment]
Yep, asked.

**Comment by puneetlath** [comment]
Great, thanks!
