### ISSUE TITLE
[$250] Attachment - Image attachement is blinking when switching from a public image

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#52567]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.62-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** https://expensify.testrail.io/index.php?/tests/view/5223867&group_by=cases:section_id&group_id=292107&group_order=asc
**Issue reported by:** Applause - Internal Team

## Action Performed:
- Open iCloud notes
- Paste this link to an empty note: An inline image and some text ![off](https://images.unsplash.com/photo-1709983723739-d72ea88434dd?q=80&w=2940&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D
)
1. Navigate to https://staging.new.expensify.com/
2. Log in with a Gmail account
3. Navigate to a 1:1 DM
4. Navigate to + - Add attachment - Take Photo or Video
5. Take a photo and send it to the chat
6. Open iCloud notes
7. Copy the contents of the note
8. Paste it into the composer and send it
9. Open the public image
10. Switch to the first image
11. Return to the chat
12. Repeat steps 9 and 10

## Expected Result:
Image shouldn't blink

## Actual Result:
Image attachement is blinking when switching from a public image

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/3a862bad-0c7d-415d-bcde-97ae1d270a45

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021857526397411268805</li>
        <li>Upwork Job ID: 1857526397411268805</li>
        <li>Last Price Increase: 2024-11-29</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @rayane-djouah</details>

**Comment by twisterdotcom** [comment]
Relabelling as Lauren is OOO now.

**Comment by JmillsExpensify** [comment]
Not critical so moving this to weekly

**Comment by JmillsExpensify** [comment]
Actually going to close this as not a priority.
