### ISSUE TITLE
[HOLD for payment 2024-12-20] [HOLD for payment 2024-12-19] [$250] Updating report action button in the case of held expenses

### ISSUE THREAD

**Issue by JmillsExpensify** [Expensify/App#52569]
Based on this [internal Slack discussion](https://expensify.slack.com/archives/C06ML6X0W9L/p1731266836594429), we've decided that the approve button should be grey when all expenses on a report are held. This `new feature` makes sense for a couple of reasons:

 - We already use this grey button pattern for `Submit` when a workspace has automatic scheduled submit settings
 - When all expenses on a report a held, then the report is not GBRed for the admin, and as a result there is no required action on their part. 
 - Conversely, when a report has a mix of held and non-held expenses, we do show GBR for the admin because they can (and probably should) action on the expenses that can be actioned on. 

As a result, let's do the following:

1. In the report thread, let's make the `Approve` or `Pay` buttons grey when all expenses on that report are held. Here's an example. 
![image](https://github.com/user-attachments/assets/def1483e-0ed3-47c3-b243-0861e4d93041)

2. On the `Search` page, let's do the exact same thing, should a user end up seeing/finding this reports there instead. 
![image](https://github.com/user-attachments/assets/47e62989-2722-4251-853b-c78cf88f6d4a)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021857475710560245957</li>
        <li>Upwork Job ID: 1857475710560245957</li>
        <li>Last Price Increase: 2024-11-15</li>
<li>Automatic offers: </li>
<ul>
<li>NJ-2020 | Contributor | 105028413</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @JmillsExpensify</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @JmillsExpensify</details>

**Comment by luacmartins** [comment]
I think this can be external

**Comment by dubielzyk-expensify** [comment]
Feels right to me. Just minor update to making sure the search icon is still there and the system message is correct:
![image](https://github.com/user-attachments/assets/5fcc45e4-029b-4357-b646-7eeb324fa35f)

**Comment by mananjadhav** [comment]
Will review this by tomorrow.

**Comment by JmillsExpensify** [comment]
Thanks, it'd be good to get this one going as it's effecting production customers.

**Comment by quinthar** [comment]
Yep, this is a good one!

**Comment by mananjadhav** [comment]
@NJ-2020's [proposal](https://github.com/Expensify/App/issues/52569#issuecomment-2477990920) looks good to me. 

🎀 👀 🎀  C+ reviewed.

**Comment by bernhardoj** [comment]
@mananjadhav I think we want to make it gray if all expenses are on hold.

**Comment by mananjadhav** [comment]
Okay I missed that part. In that case @bernhardoj's [proposal](https://github.com/Expensify/App/issues/52569#issuecomment-2478083567) is more correct as it points out about all held expenses. Sorry about that.

🎀 👀 🎀  C+ reviewed.

**Comment by luacmartins** [comment]
I think @JmillsExpensify might update his comment soon. We settled on a grey button if `any` transaction on a report is held.

**Comment by mananjadhav** [comment]
Ohh 😶‍🌫️  Well once @JmillsExpensify updates the comment we can choose one of the proposals.

**Comment by JmillsExpensify** [comment]
Comment updated. Ready for proposal selection.

**Comment by mananjadhav** [comment]
A bit confused with these two statements @JmillsExpensify. Can you please clarify what's the difference?

![image](https://github.com/user-attachments/assets/ec1690e9-c302-46ee-8234-affa8ee3ac12)

**Comment by JmillsExpensify** [comment]
Apologies. I removed that first sentence for clarity.

**Comment by JmillsExpensify** [comment]
Any questions on the updated comment?

**Comment by mananjadhav** [comment]
> @NJ-2020's [proposal](https://github.com/Expensify/App/issues/52569#issuecomment-2477990920) looks good to me.
> 
> 🎀 👀 🎀 C+ reviewed.

@luacmartins With the updated comment [here](https://github.com/Expensify/App/issues/52569#issuecomment-2488559242), we should use previous selected proposal.

**Comment by mananjadhav** [comment]
@NJ-2020 can you please share the ETA on the PR?

**Comment by mananjadhav** [comment]
I raised the PR with the fix for regression.

**Comment by JmillsExpensify** [comment]
Payment summary:

 - $250 @mananjadhav via New Expensify
 - $250 @NJ-2020 via Upwork

**Comment by JmillsExpensify** [comment]
Contributor has been paid, so all that remains is the BZ checklist.

**Comment by mananjadhav** [comment]
Apologies, I was out sick, still getting back.

I think this would be more of a feature request than a bug. We're also reverting this in a separate issue so I think we don't need a regression test here.

**Comment by JmillsExpensify** [comment]
@mananjadhav so you're saying that the correct payment summary is $125 each?

**Comment by mananjadhav** [comment]
Yes @JmillsExpensify. The payout should be $125 each.

**Comment by JmillsExpensify** [comment]
Updated above and processed the update via Upwork as well.

**Comment by JmillsExpensify** [comment]
Thanks so much for the quick response!

**Comment by JmillsExpensify** [comment]
@mananjadhav I'm going to close this for your part, though don't forget the BZ checklist before requesting payment.

**Comment by mananjadhav** [comment]
> I think this would be more of a feature request than a bug. We're also reverting this in a separate issue so I think we don't need a regression test here.

@JmillsExpensify Considering this is more towards a feature request and also being reverted, do we need a BZ checklist here?

**Comment by garrettmknight** [comment]
$250 approved for @mananjadhav
