### ISSUE TITLE
[HOLD for #52428] mweb -Expense - Via QAB, entering amount& tapping submit expense displays only currency

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#52565]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9. 0.62-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/home
2. Open a Workspace chat
3. Create an expense
4. Go to LHN
5. Tap fab and select submit expense via QAB
6. Enter amount
7. Tap submit expense
8. Note after tapping submit expense, user can see both currency and amount
9. Open a 1:1 chat with any user
10. Create an expense
11. Go to LHN
12. Tap fab and select submit expense via QAB
13. Enter amount
14. Tap submit expense
15. Note after tapping submit expense, user can see only currency

## Expected Result:
Via QAB, entering amount& tapping submit expense must displays both currency and amount.

## Actual Result:
Via QAB, entering amount& tapping submit expense displays only currency

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/7bd2e411-d470-48b8-91f8-9b2eb31bc47e

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by FitseTLT** [comment]
This can also be fixed in https://github.com/Expensify/App/pull/52428

**Comment by kadiealexander** [comment]
Thanks @FitseTLT! Popping on hold until https://github.com/Expensify/App/pull/52428 is deployed.

**Comment by izarutskaya** [comment]
Not reproducible now.
Build 9.0.64-0

https://github.com/user-attachments/assets/4dd221a8-899c-4b75-b9b2-9914138b7ceb
