### ISSUE TITLE
Android - Expense - Third Expense shows unexpected error on visiting from outstanding tab

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#52576]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.62-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Y
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Launch app
2. Tap fab - start chat - select a user
3. In 1:1 page, create 2 expenses
4. Go to LHN
5. Tap fab - submit expense via QAB select and create 3 expense
6. Open the expense report and note no error
7. Go to LHN - search at bottom
8. Tap outstanding
9. Tap on the expense report created

## Expected Result:
Third expense created via QAB, on visiting from outstanding tab must not show unexpected error.

## Actual Result:
Third expense created via QAB, on visiting from outstanding tab shows unexpected error.

## Workaround:
Unknown

## Platforms:

- [x] Android: Standalone
- [x] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/517a914f-d182-489f-b30f-bd648158b81f

 
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by stephanieelliott** [comment]
Not able to repro this on the latest version, seems fixed in staging: 

https://github.com/user-attachments/assets/35b49f20-e27c-4515-a784-1510fab8be7f
