### ISSUE TITLE
[HOLD for payment 2024-12-03] Update copy on custom feed details page

### ISSUE THREAD

**Issue by joekaufmanexpensify** [Expensify/App#52581]
Coming from [here](https://expensify.slack.com/archives/C06ML6X0W9L/p1731589442563349), we want to update the copy on these two pages because it is currently confusing. 

### Visa changes

- Update copy in first paragraph to: `We have global integrations with Visa, though eligibility varies by bank and card program.`
- Add a space in 2 between `to` and `enable` as it's missing one right now. 
<img width="376" alt="image" src="https://github.com/user-attachments/assets/f673bd53-30da-48f0-9d8f-833b0c74a468">

### Mastercard change

- Update copy in first paragraph to: `We have global integrations with Mastercard, though eligibility varies by bank and card program.`

<img width="374" alt="image" src="https://github.com/user-attachments/assets/11ecb818-5257-4db0-8781-df4aacfe6f93">

<details><summary>Issue Owner</summary>Current Issue Owner: @abekkala</details>

**Comment by joekaufmanexpensify** [comment]
Someone from callstack will likely pick this up, flagging in Slack!

**Comment by mountiny** [comment]
Spanish translations:

We have global integrations with Visa, though eligibility varies by bank and card program. > Contamos con integraciones globales con Visa, aunque la elegibilidad varía según el banco y el programa de la tarjeta.

We have global integrations with Mastercard, though eligibility varies by bank and card program. > Contamos con integraciones globales con Mastercard, aunque la elegibilidad varía según el banco y el programa de la tarjeta.

**Comment by mountiny** [comment]
will look

**Comment by mountiny** [comment]
no c+ needed here

**Comment by DylanDylann** [comment]
@mountiny Could I help to speed up the PR?

**Comment by mountiny** [comment]
@DylanDylann all good on this one

**Comment by mountiny** [comment]
this was just a copy change and nobody to pay here so I think we can close
