### ISSUE TITLE
[No Payment] mWeb - WS - In #admin room the message about the upgrader disappears

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#52582]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.62-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5223810
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Log in the app
2. Go to Settings and create a new WS
3. In the new WS go to More Features and enable Accounting
4. Tap on Netsuite/Sage
5. Tap upgrade button
6. Navigate to WS screen and Tap 3 dots
7. Go to #admins room

## Expected Result:
User is navigated to the #admins room, the upgrade system messages have posted, including a message from Expensify mentioning the upgrader.

## Actual Result:
The upgrader is mentioned in a separate whisper message, that is only displayed briefly. In the system message the upgrader is not mentioned.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
  
https://github.com/user-attachments/assets/bd868c03-7ccb-47a5-aa30-01d70d99e7b6

https://github.com/user-attachments/assets/c8edf4a2-a6bb-49a8-b872-8126e14e73c3

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021857185698447287009</li>
        <li>Upwork Job ID: 1857185698447287009</li>
        <li>Last Price Increase: 2024-11-14</li>
    </ul>
</details>

**Comment by sakluger** [comment]
Pulling out a few screenshots from the reproduction video so it's easier to see what's going on here. Here's the `#admins` room chat showing the upgrade system message:

<img width="502" alt="image" src="https://github.com/user-attachments/assets/806c62c2-f8eb-47b3-8e33-3e6ceb75aba3">

And here's the same admins room seconds later, after the system message disappeared:

<img width="492" alt="image" src="https://github.com/user-attachments/assets/00a42540-4e6b-4a1d-8a14-c3ef112b245f">

**Comment by sakluger** [comment]
@Ollyws can you please confirm if this needs to be handled in BE? If so, I can change to `internal`.

**Comment by sakluger** [comment]
We have a ton of `POLICYCHANGELOG` system messages and as far as I know, they're all created and stored API-side and the workspace changes require access to backend code. I'm going to mark internal for now, but if it turns out that @daledah's front-end solution will work, we can switch it back.

**Comment by yuwenmemon** [comment]
Ooh weird. Yeah I can take a look at this...

**Comment by sakluger** [comment]
@yuwenmemon let me know if you think we need to change to weekly.

**Comment by sakluger** [comment]
Looks like this is fully backend - I'll remove @Ollyws since it doesn't seem like we need a C+ review.

**Comment by sakluger** [comment]
PR was deployed to prod last week. We're all done here!
