### ISSUE TITLE
[HOLD for payment 2024-12-25] [Performance] useOnyx doesn't return new data if the selector changes but the data in the store is the same

### ISSUE THREAD

**Issue by pac-guerreiro** [Expensify/App#52597]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## What performance issue do we need to solve?
Inefficient React component rendering when onyx collection data is updated, although we're only accessing unmodified entries of the onyx collection.

Example case: https://github.com/Expensify/App/pull/49919#pullrequestreview-2346813622

## What is the impact of this on end-users?
App performance can degrade with the inefficient rendering

## List any benchmarks that show the severity of the issue
N/A

## Proposed solution (if any)
Mimic dependency array from some React hooks, like `useEffect`, to force `useOnyx` to fetch data if any dependency changes.

Something like `useOnyx(key, options, [dependencyA])`.

## List any benchmarks after implementing the changes to show impacts of the proposed solution (if any)
N/A

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

**Version Number:** v9.0.62-4
**Reproducible in staging?:** yes
**Reproducible in production?:** yes
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** https://github.com/Expensify/App/pull/49919#pullrequestreview-2346813622
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:** 

[View all open jobs on Upwork](https://www.upwork.com/ab/jobs/search/?q=Expensify%20React%20Native&sort=recency&user_location_match=2)

<details><summary>Issue Owner</summary>Current Issue Owner: @sonialiap</details>

**Comment by pac-guerreiro** [comment]
@vit can you make this issue internal? @fabioh8010 and I are working on it

**Comment by fabioh8010** [comment]
You tagged the wrong person @pac-guerreiro , it's @mountiny 😄

**Comment by pac-guerreiro** [comment]
Ups, sorry! 😅

**Comment by mountiny** [comment]
Sounds good

**Comment by pac-guerreiro** [comment]
Last friday I didn't work on this but tomorrow I'll open a draft PR with a possible solution

**Comment by pac-guerreiro** [comment]
I opened a draft PR with a possible solution for this issue - https://github.com/Expensify/react-native-onyx/pull/599

If you all agree, I can also create an eslint rule to enforce the usage of the dependency array when developers pass variables in `useOnyx` selector. To achieve it, I'll need to adapt [this](https://github.com/facebook/react/blob/main/packages/eslint-plugin-react-hooks/src/ExhaustiveDeps.js) and create an additional PR to add this new rule to https://github.com/Expensify/eslint-config-expensify

**Comment by pac-guerreiro** [comment]
I'm waiting on @fabioh8010 feedback on this since he has an alternate solution

**Comment by fabioh8010** [comment]
We are currently discussing the issue internally.

**Comment by pac-guerreiro** [comment]
Today @fabioh8010 and I discussed this issue internally. There are some ideas on the table on how to tackle this issue, so we'll continue discussing them tomorrow!

**Comment by pac-guerreiro** [comment]
Today @fabioh8010 continued our discussion, we are still trying to find a proper solution for this issue.

**Comment by pac-guerreiro** [comment]
Today I tried more possible solutions and discussed them with @fabioh8010. I've been having problems with infinite loops on getSnapshot. On Monday I'm going to discuss an alternative idea of @fabioh8010 for this performance issue.

**Comment by pac-guerreiro** [comment]
Today I reviewed @fabioh8010 solution and we discussed it. We need to confirm which one is the best and how we should proceed next

**Comment by fabioh8010** [comment]
Update: We agreed to test my solution against E/App and if everything is ok, we will proceed with it.

**Comment by fabioh8010** [comment]
Created a [WIP Draft PR](https://github.com/Expensify/react-native-onyx/pull/605), testing the solution against E/App.

**Comment by fabioh8010** [comment]
Update: PR opened to review!

cc @mountiny

**Comment by fabioh8010** [comment]
Update: Onyx PR was merged! I will proceed with the Onyx bump PR

**Comment by fabioh8010** [comment]
@mountiny Could you take a quick 👀 in [this PR](https://github.com/Expensify/react-native-onyx/pull/606)? Onyx `main` is currently broken and we need that fix before proceeding with the Bump PR. Thanks!

**Comment by mountiny** [comment]
Merged

**Comment by fabioh8010** [comment]
Will open the Bump PR today

**Comment by fabioh8010** [comment]
Bump PR created -> https://github.com/Expensify/App/pull/53890

**Comment by mountiny** [comment]
$250 to @sobitneupane No need for regression testing on this one

**Comment by sonialiap** [comment]
Payment summary:
- @sobitneupane $250 via NewDot

**Comment by garrettmknight** [comment]
$250 approved for @sobitneupane
