### ISSUE TITLE
[Company cards] Cards collection is returned as an array

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#52616]
Coming from [here](https://expensify.slack.com/archives/C06ML6X0W9L/p1731657580587169?thread_ts=1731609778.494899&cid=C06ML6X0W9L)

When no cards are assigned on a feed yet, the collection is returned as an empty object, which PHP then turns into an empty array.

We cannot merge object into an array in onyx so we need to unsure an empty object remains that way in API

**Comment by mountiny** [comment]
PR in staging

**Comment by Christinadobrzyn** [comment]
monitoring PR- https://github.com/Expensify/Web-Expensify/pull/44442

**Comment by Christinadobrzyn** [comment]
PR in production, doesn't look like there were any contributors involved so closing this.
