### ISSUE TITLE
[HOLD for payment 2024-12-05] [$250] Search - Expenses change position briefly when switching from Settings to Search

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#52632]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.63-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+kh051101@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition:
- Have many expenses
1. Go to staging.new.expensify.com
2. Go to Search
3. Change sorting a few times (click Merchant, From, To etc)
4. Click Settings
5. Go back to Search
6. Might need to repeat Step 4 and 5 a few times to see the expenses changing position briefly

## Expected Result:
The expenses will not change position briefly when switching from Settings to Search after changing sorting order.

## Actual Result:
The expenses change position briefly when switching from Settings to Search after changing sorting order.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/014ee706-3257-4095-9ee9-7728cfcdd733

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021858539185487721038</li>
        <li>Upwork Job ID: 1858539185487721038</li>
        <li>Last Price Increase: 2024-11-18</li>
<li>Automatic offers: </li>
<ul>
<li>FitseTLT | Contributor | 105027229</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @isabelastisser</details>

**Comment by isabelastisser** [comment]
@jjcoffee can you please review the proposal above? Thanks!

**Comment by jjcoffee** [comment]
@FitseTLT's [proposal](https://github.com/Expensify/App/issues/52632#issuecomment-2479958699) LGTM! As an example, if we are comparing two equivalent values (e.g. two expenses both with a merchant of "Test"), we would not be returning the expected value of 0 as we only perform conversion to lower case on one of the compared values. 

I think we should perform conversion to lower case on both values as otherwise we'd be doing case-sensitive sorting which doesn't really make sense in this context.

:ribbon::eyes::ribbon: C+ reviewed

**Comment by FitseTLT** [comment]
@marcochavezf bump on this one

**Comment by FitseTLT** [comment]
@marcochavezf Bump for assignment Thx

**Comment by jjcoffee** [comment]
@isabelastisser Could you star the issue for @marcochavezf, so that it gets his attention? Thanks!

**Comment by isabelastisser** [comment]
@marcochavezf, can you please provide an update? Thanks!

**Comment by isabelastisser** [comment]
Payment summary:

@jjcoffee requires payment through NewDot Manual Requests C+ $250 `PENDING`
@FitseTLT requires payment [automatic offer](https://www.upwork.com/nx/wm/offer/105027229) (Contributor) `PAID!`

**Comment by isabelastisser** [comment]
All set!

**Comment by garrettmknight** [comment]
$250 approved for @jjcoffee
