### ISSUE TITLE
Workspace - Archived workspace chat is not displayed when search member's email

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#52637]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.63-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5229589&group_by=cases:section_id&group_order=asc&group_id=296762
**Email or phone of affected tester (no customers):** gocemate+a2862@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Login with gmail account
2. Create Workspace
3. Invite a member
4. Remove the same member
5. Go to Search
6. Enter removed member email address

## Expected Result:
User's email and archived workspace chat should be displayed in search results list

## Actual Result:
Archived workspace chat is not displayed when search removed member's email

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/ed6f132e-ca4c-4e09-ac29-29a5658e3cba

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by johncschuster** [comment]
I couldn't action this today.

**Comment by johncschuster** [comment]
No update. I'll get this actioned tomorrow.

**Comment by johncschuster** [comment]
@lanitochka17 I feel like this is expected behavior if the chat between the users does not contain any chat history. Can you check what happens when there is chat history between User A and User B?

**Comment by lanitochka17** [comment]
@johncschuster You are right, It seems to be expected, if the workspace is deleted it should not be displayed in the search
