### ISSUE TITLE
Workflows -  No Director information screen

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#52631]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.63-1
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y 
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/51648
## Action Performed:
Precondition: WS with enabled workflows
1. Go to ws > workflows
2. Click on "Connect bank account" inside the "Make or track payments" section
3. Go to the 5th step of the flow

## Expected Result:
New Step 5 Director information screen is displayed

## Actual Result:
No new Step 5 Director information screen is displayed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/cdc20e99-e8dc-451d-b378-fde38e7d8f3f

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by twisterdotcom** [comment]
Relabelling as Lauren is OOO now.

**Comment by hungvu193** [comment]
Will be fixed by https://github.com/Expensify/App/pull/52384
