### ISSUE TITLE
Web - Wallet - Onyx "bankAccountList" "cardList" console errors are appearing when opening wallet

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#52636]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.63-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Navigate to https://staging.new.expensify.com/
2. Log in with a new Gmail account
3. Navigate to Settings - Wallet

## Expected Result:
Console errors shouldn't be appearing.

## Actual Result:
Onyx "bankAccountList" and "cardList" console errors are appearing when opening the wallet.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
[1511_2.txt](https://github.com/user-attachments/files/17778891/1511_2.txt)

https://github.com/user-attachments/assets/2d5769b0-a58b-43be-b628-1e49d165495d

 
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Shahidullah-Muffakir** [comment]
When `OpenPaymentsPage` endpoint is called BE returns empty array for "bankAccountList"  and "cardList", if there are none, But an empty Object is expected.
<img width="932" alt="Screenshot 2024-11-16 at 4 51 38 AM" src="https://github.com/user-attachments/assets/da414482-d284-4b91-8f75-bd1040747f59">

**Comment by stephanieelliott** [comment]
Thanks for the investigation @Shahidullah-Muffakir! Not sure if this is something we should prioritize fixing, asked internally for a second opinion: https://expensify.slack.com/archives/C01SKUP7QR0/p1732087142893929

**Comment by techievivek** [comment]
This is fixed and tested here https://github.com/Expensify/Expensify/issues/446584#issue-2679008922, closing it.
