### ISSUE TITLE
[HOLD for payment 2024-12-20] Investigate useOnyx infinite loading state related to the Connection Manager

### ISSUE THREAD

**Issue by fabioh8010** [Expensify/App#52640]
This issue was first noticed here -> https://github.com/Expensify/App/pull/49509.

I recently implemented a [fix in Onyx to solve the infinite loading states after a Onyx.clear() operation](https://github.com/Expensify/react-native-onyx/pull/588), but in this case they are happening without the clear operation, so we must investigate it again.

Report of the problem: https://github.com/Expensify/App/pull/49509#issuecomment-2462699104
Reproducible steps: https://github.com/Expensify/App/pull/49509#issuecomment-2403667996
My initial investigations: https://github.com/Expensify/App/pull/49509#issuecomment-2477373813

<details><summary>Issue Owner</summary>Current Issue Owner: @bfitzexpensify</details>

**Comment by fabioh8010** [comment]
Hi @gijoe0295 Could you confirm for me if you are still being able to reproduce this loading state issue? I'm having difficulties to reproduce it. If you are able could you give me the detailed test steps again? Thanks

**Comment by fabioh8010** [comment]
@ishpaul777 maybe you can help me here with reproducing the problem from your side? We need to remove `reuseConnection: false` from `src/pages/workspace/withPolicy.tsx` before testing.

**Comment by fabioh8010** [comment]
Update: Created a [WIP Draft PR](https://github.com/Expensify/App/pull/53597). Will proceed with testing soon.

**Comment by fabioh8010** [comment]
@ishpaul777  PR open to review!

**Comment by bfitzexpensify** [comment]
Offer sent @ishpaul777

**Comment by bfitzexpensify** [comment]
Payment complete.
