### ISSUE TITLE
[$250] Make sure the Concierge "setup specialist" message only sends once, and update the copy slightly

### ISSUE THREAD

**Issue by jamesdeanexpensify** [Expensify/App#52647]
## Background
From the conversation starting [here](https://expensify.slack.com/archives/C07HPDRELLD/p1731688494380019?thread_ts=1731628192.397779&cid=C07HPDRELLD), we currently send the setup specialist message from Concierge multiple times. I believe we send it once for every new workspace creation. Here's an example of when a recent user created two workspaces in the same session:

<img width="1461" alt="image" src="https://github.com/user-attachments/assets/6eea5a06-e833-4044-8bca-c081b89078b2">

## Changes
- We'd like to send this message **only once total**
- Slight copy update, too. I'll use the screenshot above as an example of what we'd like to update to:
> Let's get your company set up! Andres, your setup specialist, is online now and can answer your initial questions or provide a demo. 
>
> CHAT WITH YOUR SETUP SPECIALIST
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021858375493228287049</li>
        <li>Upwork Job ID: 1858375493228287049</li>
        <li>Last Price Increase: 2024-11-18</li>
    </ul>
</details>

**Comment by greg-schroeder** [comment]
Hey @jamesdeanexpensify! Hmm - I don't know, depends on if this requires BE changes or not. Let's assign a C+ and see if they can help us decide

**Comment by greg-schroeder** [comment]
@akinwale Can you help us confirm whether this can be worked on by an external contributor? Thanks!

Removed `Help Wanted` for now until we're sure

**Comment by blimpich** [comment]
[PR out for review](https://github.com/Expensify/Web-Expensify/pull/44485)

**Comment by greg-schroeder** [comment]
This is on staging. Awaiting deploy to prod

**Comment by danielrvidal** [comment]
@greg-schroeder this is on production now so I wanted to check in and see if it's all good.
