### ISSUE TITLE
Close account - "Another login page is open" page opens after closing account

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#52645]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.63-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** [djosjosido@gmail.cm](mailto:djosjosido@gmail.cm)
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Log in
3. Go to Account settings > Security
4. Click Close account
5. Enter email and close account

## Expected Result:
App will redirect to login page without issue

## Actual Result:
App redirects to login page and it says that "Another login page is open" when it is not

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/9d9e4143-adfb-43aa-ae13-39a172619e28

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by thienlnam** [comment]
Looks like the same bug that's happening [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1731632747782129)

**Comment by thienlnam** [comment]
Maybe related to this PR? https://github.com/Expensify/App/pull/52444

**Comment by thienlnam** [comment]
Yup, fixed by reverting it
