### ISSUE TITLE
mWeb - Workspace - Second created workspace is grayed out everytime internet is turned off

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#52651]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
 
**Version Number:** 9.0.63-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5230599&group_by=cases:section_id&group_order=asc&group_id=229067
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Open the staging.new.expensify.com website.
2. Turn off internet connection.
3. Open workspace selector on the top left corner.
4. Tap on the "+" button to create a new one.
5. Tap on the arrow on the top left corner.
6. Create a second one.
7. Return to LHN.
8. Verify both workspaces were created.
9. Turn on internet connection.
10. Verify both workspaces are not grayed out anymore.
11. Turn on internet connection again.
12. Verify both workspaces are not grayed out.

## Expected Result:
Just created workspaces should remain in normal colour when turning internet connection off.

## Actual Result:
When creating two workspaces while offline, the second one becomes grayed out everytime that internet connection is off.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/b2cfc252-52f2-4be9-b11b-fc6ba25a368c

  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by RachCHopkins** [comment]
Working fine for me. Please retest.

**Comment by RachCHopkins** [comment]
Requested retest in [slack](https://expensify.slack.com/archives/C9YU7BX5M/p1732157611483079)

**Comment by izarutskaya** [comment]
Not reproducible anymore
Build  9.0.65-1

https://github.com/user-attachments/assets/6f59a9a6-e97b-4772-a3ff-a0c21a8ba1ad

**Comment by RachCHopkins** [comment]
Great, closing!
