### ISSUE TITLE
[HOLD for payment 2024-12-06] [$250] Update workspace switcher to look and act more like a filter

### ISSUE THREAD

**Issue by jamesdeanexpensify** [Expensify/App#52654]
## Background
Coming from [this long convo](https://expensify.slack.com/archives/C03U7DCU4/p1731536477731219), we'd like to update the workspace switcher to look and act more like a filter.

## Problem
The current workspace chat switcher has the "Everything" > "Expensify" selection as its default, which is unnecessary in general (especially when you don't have any workspaces) and takes up valuable real estate. 

## Solution
- Remove the "Everything" > "Expensify" section of the workspace switcher completely. Showing everything both on and off workspace will just be the default of the product.
- Since showing everything both on and off workspace will now be the default of the product, the workspace switcher should default to **no** workspaces selected in the switcher (which means it's showing everything).
  - The closed state of the switch should appear the same as it does now when "Everything > Expensify" is selected.
- Selecting a given workspace will filter only for that workspace.
  - The closed state of the switcher should appear the same as it does now when a workspace is selected.
- Note: If multiple workspaces exist, only allow for filtering on one workspace at a time. Don't allow multi-select.

## Screenshots
Here's what we want the finished product to look like:
![CleanShot 2024-11-15 at 13 43 23@2x](https://github.com/user-attachments/assets/5378590d-9c85-46b8-9432-1ccde238cf1c)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021858848669430376492</li>
        <li>Upwork Job ID: 1858848669430376492</li>
        <li>Last Price Increase: 2024-11-19</li>
<li>Automatic offers: </li>
<ul>
<li>paultsimura | Reviewer | 105060504</li>
<li>Krishna2323 | Contributor | 105060505</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @CortneyOfstad</details>

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Update workspace switcher to look and act more like a filter

### What is the root cause of that problem?

new feature

### What changes do you think we should make in order to solve the problem?


1. Change translation key title here
2. Remove every thing section
3. Update `onSelectRow` function in `SelectionList`
4. Add new button `Clear filter`

### What alternative solutions did you explore? (Optional)
NA

**Comment by shawnborton** [comment]
Not overdue, we're looking at proposals

**Comment by JmillsExpensify** [comment]
Added the help wanted label so that it's clear this issue is open for proposals.

**Comment by shawnborton** [comment]
Not overdue, waiting for the PR now

**Comment by CortneyOfstad** [comment]
Payment is due on Saturday for some reason, so going to adjust this to Friday 😂
