### ISSUE TITLE
[HOLD for payment 2024-11-29]  Android - Expensify Card - Username, last 4 and limit amount are not aligned on the same line

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#52663]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.63-3
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** 
**Email or phone of affected tester (no customers):** applausetester+29302390@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/52529
## Action Performed:
Precondition:
- Expensify Card is enabled in the workspace.
- There is at least one workspace member with virtual card
1. Launch ND or hybrid app
2. Go to workspace settings
3. Go to Expensify Card

## Expected Result:
User name, last 4 digits and limit amount will be aligned on the same line

## Actual Result:
User name, last 4 digits and limit amount are not aligned on the same line (please refer to screenshot)

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Standalone
- [x] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 
<img width="308" alt="57 44" src="https://github.com/user-attachments/assets/d7619dee-3345-470f-ae8e-d3517bcdf909">

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @bfitzexpensify</details>

**Comment by lanitochka17** [comment]
Production:
![IMG_7080](https://github.com/user-attachments/assets/db439e11-d590-49d5-ab85-45a145d16f12)

**Comment by mountiny** [comment]
happy to take over as I work on this one

**Comment by mountiny** [comment]
I agree this is not a blocker, as we made this change intentionally. However, I can see that the card name is a little bit off, imho. @Expensify/design are you able to check the images cc @nkdengineer

**Comment by dannymcclain** [comment]
I also agree this is not a blocker, but the alignment is definitely off. From [Figma](https://www.figma.com/design/9J4v6CzMVLQbzXMnXC5Izq/%23wave-collect%3A-Workspace-Card-Feeds?node-id=6129-25555&node-type=frame&t=hXQUQZqGrUIuhwIc-11), the Name, Last 4, and Limit should all sit on a common baseline.

![CleanShot 2024-11-18 at 09 32 27@2x](https://github.com/user-attachments/assets/091e61d5-7469-4aa5-bd59-e324958500e7)

**Comment by mountiny** [comment]
@nkdengineer sorry for the trouble but this is something we did not catch in the PR so I should assign you here, can you please comment?

**Comment by nkdengineer** [comment]
I'm here

**Comment by nkdengineer** [comment]
<img width="924" alt="Screenshot 2024-11-18 at 22 51 21" src="https://github.com/user-attachments/assets/26fd2220-78ee-4ad5-8817-db01164bee37">

@DylanDylann, @mountiny, @Expensify/design here is the result from my side, it seems they are not on the same line and are about 1-2px different
I will investigate and create PR to fix tomorrow

**Comment by shawnborton** [comment]
Agree with the comments above. Hopefully it's a quick fix!

**Comment by nkdengineer** [comment]
![result](https://github.com/user-attachments/assets/40ea7999-612e-4e55-b0ea-745ac0b41d46)

@DylanDylann, @mountiny, @Expensify/design We have open PR [here](https://github.com/Expensify/App/pull/52743)

**Comment by dannymcclain** [comment]
Nice!

**Comment by mountiny** [comment]
PR merged 🎉

**Comment by mountiny** [comment]
This is good, I think no payment required on this issue as it was a regression from the PR before

**Comment by mountiny** [comment]
$250 to @nkdengineer @DylanDylann for their work on this one, discussion was on this issue https://github.com/Expensify/App/issues/52370#issuecomment-2501490068

**Comment by bfitzexpensify** [comment]
Offers sent @DylanDylann @nkdengineer

**Comment by bfitzexpensify** [comment]
Payments complete.
