### ISSUE TITLE
Chat - For bold and italic, markdown is applied inconsistently

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#52679]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** V9. 0.63-3 
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Launch app
2. Open a chat
3. Enter `**bold**, *italic*
__italic__,_italic_`
4. Send the message

## Expected Result:
For bold and italic, markdown must be applied consistently.

## Actual Result:
For bold and italic, markdown is applied inconsistently.

## Workaround:
Unknown

## Platforms:

- [x] Android: Standalone
- [x] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/b2283616-a431-472c-aa83-90a0d8bddaf2

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by alexpensify** [comment]
Adding to my testing list

**Comment by alexpensify** [comment]
I didn't get to test this one before going OOO. This week, I'll try to log in to confirm the next steps.

**Comment by alexpensify** [comment]
No update

**Comment by alexpensify** [comment]
Closing - I've been unable to replicate 

![2024-12-02_20-52-18](https://github.com/user-attachments/assets/9fc4424a-d855-429e-8d22-f0097bd91800)
