### ISSUE TITLE
Update CONTRIBUTING.md to reflect Upwork job link isn't publicly viewable

### ISSUE THREAD

**Issue by mallenexpensify** [Expensify/App#5268]
Creating this issue because @Beamanator and I agree that @mateomorris should be compensated for [reporting this in Slack](https://expensify.slack.com/archives/C01GTK53T8Q/p1631444220192700). 

FYI: The Upwork jobs list shows up empty for users without an account (or signed out). To me, this communicated that there aren’t any active jobs. Obviously this is an issue with Upwork, but maybe a notice could be added to the Contribution Guidelines next to the link to warn prospective contributors.

**Comment by mallenexpensify** [comment]
@mateomorris Can you apply for the job here https://www.upwork.com/jobs/~01e389cf88d1262687
Then add a comment here letting me know you have and I'll hire and pay?

**Comment by mateomorris** [comment]
@mallenexpensify done. Thanks!

**Comment by mallenexpensify** [comment]
Hired, you'll need to accept the offer then I can pay @mateomorris

**Comment by mallenexpensify** [comment]
Paid in Upwork, thanks again @mateomorris
