### ISSUE TITLE
[HOLD for payment 2024-12-03] Web - QBD-Account payable is auto selected

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#52692]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.63-3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Navigate to Accounting
2. Click on Export
3. Click on "Export out-of-pocket expenses"
4. Verify the options "Export Out-of-Pocket Expenses as" is displayed
5. Verify on the "Export Out-of-Pocket Expenses as" page field for Account Payable account is shown and clicking leads to the Accounts payable" page
6. Verify options for Accounts payable imported from QBD shown in checkmark

## Expected Result:
The "Account payable" field should be populated by the first account payable of the list from the "Accounts payable" page.

## Actual Result:
The "Account payable" field is auto-populated after changing the selection of the "Export as" option to any other (for instance, Check or Journal entry) and going back to Vendor bill.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

![Bug6666852_1731713475042!Account_payable_-_Not_configured](https://github.com/user-attachments/assets/82c023d7-729a-4964-aafd-eb3b7f1db3c9)
![Bug6666852_1731713475028!Account_payable_-_Auto_selected](https://github.com/user-attachments/assets/b94b5113-d3fd-4e62-a2aa-186179ec5ba3)

https://github.com/user-attachments/assets/c33d1b7d-b801-4807-a251-1ce2ab466ea1

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @CortneyOfstad</details>

**Comment by CortneyOfstad** [comment]
For this I wonder if the logic is changed based on the number of options available. For example, if there is only one AP account available from the Chart of Accounts in QBD, that we select automatically. However, since there are 2 options, we default to having the customer choose.

Within Classic, we populate the first option automatically, but do wonder if the logic was tweaked for this. Going to check with the team internally on this.

**Comment by lakchote** [comment]
@ZhenjaHorbach please address the issue since you've worked on this in your [PR](https://github.com/Expensify/App/pull/50234).

Assigning @hoangzinh as well as the C+ reviewer.

No payment will be due since it can be considered a regression from OldDot.

**Comment by CortneyOfstad** [comment]
Payment is not due until next week but @ZhenjaHorbach, I sent you an offer in Upwork which can be found [here](https://www.upwork.com/nx/wm/offer/105082013). Please accept at your earliest convenience — thanks!
