### ISSUE TITLE
Merge Expense - Cash expense is not merged with Expensify card expense after smartscan

### ISSUE THREAD

**Issue by isagoico** [Expensify/App#52704]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.63-3
**Reproducible in staging?:** yes
**Reproducible in production?:** yes

**Email or phone of affected tester (no customers):** tester+mergetests@applausecard.expensifail.com

**Issue reported by:** @jamesdeanexpensify 
**Slack conversation** (hyperlinked to channel name): [#retain](https://expensify.slack.com/archives/C07NZ8B1VTQ/p1731456360197519)

## Action Performed:

1. Log in as a workspace member that has a Expensify card assigned (e.g: [tester+mergetests@applausecard.expensifail.com](mailto:tester+mergetests@applausecard.expensifail.com))
2. Navigate to the workspace chat
3. Upload the following [receipt](https://drive.google.com/file/d/1F2R2VNgVAAFmIiaWd-ID7EhC_1sjk7OH/view?usp=drive_link)
4. Verify the receipt is uploaded and displayed on the workspace chat as scanning
5. Wait for the Smartscan to finish

## Expected Result:
Cash transaction should be merged with the ECard transation as they are the same

## Actual Result:
2 separate expenses remain of the same transaction.

Report ID: 4810215398926315
Expense IDs (Ecard): 46353471501180
Expense ID (Cash): 4174323036990033

## Workaround:
N/A

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [] MacOS: Desktop

## Screenshots/Videos

![image](https://github.com/user-attachments/assets/5a0a03e4-2c66-4f89-b5d0-3daa91dfaba9)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mountiny** [comment]
cc @nkuoch related to the one we looked into for workspace feeds, but this is general any expensify card

**Comment by jamesdeanexpensify** [comment]
I'm not sure how much you want to try to duplicate my case, but I did this:

<img width="1050" alt="image" src="https://github.com/user-attachments/assets/00403f9a-0aa3-4076-add9-ef50d5a1ffa1">

If it helps, the card transaction was still pending when the receipt attached to it. I went into my Expensify account and saw it attached very soon after I made the actual transaction itself.

**Comment by nkuoch** [comment]
These didn't merge because smartscan failed

request_id:ZBoAO0

> [SmartScanDos] ParseReceipt - Got response from parsers ~~ receiptID: '8573152033724506' jsonCode: '200' message: 'Started parsing for url https://www.expensify.com/receipts/w_78b02b13d660c64824e57b429b6fad6e39ffc6e9.png' parseData: '[receiptID: '8573152033724506' hitID: '23899890159398922673b4fee464924.00439275' result: 'fail' data: '{"transactionList":"<REDACTED>","reservationList":[],"source":"Zoom_ImageParser_Worker_00040","ocrFilename":null,"status":{"code":404,"message":"No parser reported success"},"parserResults":{"fileExtension":"json"},"zipCode":""}' authToken: '<REDACTED>']' imageSizes: '[]'

> ReceiptReader - [AgentZero] Receipt scanned ~~ receiptID: '8573152033724506' fileName: 'w_78b02b13d660c64824e57b429b6fad6e39ffc6e9.png' result: '[merchant: 'Expensify' amount: '200' currency: 'USD' date: '' paymentType: 'card']'

> [SmartScanDos] SmartScan - The scan failed ~~ receiptID: '8573152033724506' 

> [SmartScanDos] SmartScan - SmartScan set as illegible for receipt ~~ receiptID: '8573152033724506' isAgentZero: '1'

**Comment by isagoico** [comment]
@nkuoch Is there're a specific reason on why it would fail? Here's the receipt I used, not sure why the smartscan would be incomplete 🤔 
![image](https://github.com/user-attachments/assets/3c9adee7-656a-4c20-8ee2-2f1c0a9757e0)

**Comment by nkuoch** [comment]
@thienlnam would you know https://github.com/Expensify/App/issues/52704#issuecomment-2498491049?

**Comment by thienlnam** [comment]
No date on the receipt, I suppose we could default to the current date though

**Comment by isagoico** [comment]
Isn't defaulting to the current date the expected behavior? I was under the impression that was the the case when the date is 
missing.

**Comment by isagoico** [comment]
@thienlnam friendly bump on the question above
