### ISSUE TITLE
[$250] HybridApp - Workspace Switcher - I don't get redirected when selecting a workspace

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#52726]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.63-3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
Preconditions:
- The user must be logged out of the app
1. Launch the NewDot app
2. Login with an existing account that has a workspace
3. Tap the New Expensify icon to open the Workspace Switcher
4. Select the workspace

## Expected Result:
I should be redirected to workspace-related chats only

## Actual Result:
When I tap the workspace, I'm not redirected. It stays in the same section and doesn't let me exit by touching the back button

Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [x] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/fe61b59e-e237-44cb-ba04-c49404e464e5

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021858661046829691470</li>
        <li>Upwork Job ID: 1858661046829691470</li>
        <li>Last Price Increase: 2024-11-18</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @parasharrajat</details>

**Comment by greg-schroeder** [comment]
Awaiting proposals

**Comment by ikevin127** [comment]
> Which of our officially supported platforms is this issue occurring on?

Is checking the box for `Android: HybridApp` but the video shows `iOS: HybridApp` from what I can tell - I tried reproducing the issue on both **iOS / Android Native** platforms but it's not reproducible on any of the two.

I suspect this is a FE issue related to navigation but because `External` contributors don't have access to HybridApp repo, there's no way to debug this issue, find the root cause and propose a fix.

This is why I think nobody posted a proposal so far, even though the issue's title leads one to think the issue is **iOS: Native** related when in fact it's **iOS: HybridApp**.

**Comment by greg-schroeder** [comment]
Ahh, word, thanks @ikevin127

**Comment by greg-schroeder** [comment]
Adjusted

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by greg-schroeder** [comment]
Yeah, I asked for a review in Slack, waiting for someone to volunteer

**Comment by greg-schroeder** [comment]
Still waiting for a volunteer

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (Second week)

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (Third week)

**Comment by greg-schroeder** [comment]
Seems this isn't reproducible anymore, so I'll close accordingly. Please comment/reopen if you disagree.
