### ISSUE TITLE
Classic Flow - Redirection to app instead of classic web

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#52756]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.64-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Issue was found when executing this PR:** https://github.com/Expensify/App/pull/52526
**Email or phone of affected tester (no customers):** nathanmulugetatesting+2123@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Navigate to staging.expensify.com
2. Select 10+ employees and input new gmail
3. Open OD LHN and tap on support and tap on concierge
4. After being navigated to NewDot tap on settings > Switch to Expensify classic > Tap on take me there

## Expected Result:
App redirects to Expensify Classic on mWeb

## Actual Result:
App redirects to Expensify Classic app

## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/517543ac-f9de-40ed-990f-45d713ada615
  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mountiny** [comment]
Closaroooo
