### ISSUE TITLE
MacOS - Report Action - No strike through and gray opacity is applied on offline deleted message

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#52753]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.64-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5238380
**Email or phone of affected tester (no customers):** expensify416+da2@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Navigate to any chat > Send message
2. Apply offline mode
3. Delete the sent message

## Expected Result:
Message should be strike through, and grayed out

## Actual Result:
Message is not strike through and grayed out.

Issue happens only on MacOS, not repro on WindowsOC.
## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/332bf8c2-ea46-46a4-8829-a9ef11c9a02b
  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by ChavdaSachin** [comment]
PR https://github.com/Expensify/App/pull/52752#issue-2671757577 will fix this issue as well.

**Comment by iwiznia** [comment]
PR was cherry picked @IuliiaHerets can you retest please?

**Comment by IuliiaHerets** [comment]
@iwiznia Tester can't reproduce this issue in the build v9.0.64-2 

https://github.com/user-attachments/assets/39784899-bdfd-4d58-a3d4-12dfaf4bdc1d

**Comment by iwiznia** [comment]
Nice!
