### ISSUE TITLE
[HOLD for payment 2024-11-29] Web - Onboarding task - Old copy Click your profile photo displayed for accounting task

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#52760]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.64.0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Issue was found when executing this PR:** https://github.com/Expensify/App/pull/52653
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/and log with a new account
2. Select "Manage my team's expenses" on the onboarding modal
3. Select any number of employees
4. On the the last step select any integration
5. In the Concierge chat and open the task to connect accounting software

## Expected Result:
The first step in the task description should be "Click the settings tab"

## Actual Result:
The old copy "Click your profile photo" is displayed in the first step in the task description

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/c9d9a56b-5b20-41e5-a789-873bccb957ae

 
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @trjExpensify</details>

**Comment by mountiny** [comment]
cc @trjExpensify seems like we missed one spot

**Comment by trjExpensify** [comment]
Howwwwwwwww!

**Comment by trjExpensify** [comment]
Hm, why isn't that one in the Const file? https://github.com/Expensify/App/blob/7bfb34527508b47732cab6d4280a943ffab48066/src/CONST.ts#L137

**Comment by trjExpensify** [comment]
Oh, it is.. but it's "Click your profile photo" not "Click your profile picture" like the others were... 🙄 https://github.com/Expensify/App/blob/7bfb34527508b47732cab6d4280a943ffab48066/src/CONST.ts#L5037

**Comment by trjExpensify** [comment]
Sent a PR. https://github.com/Expensify/App/pull/52808

**Comment by mountiny** [comment]
@trjExpensify do you want to handle the checklist here? I dont think we need regression tests

**Comment by trjExpensify** [comment]
Agreed, all good! Copy change and can be closed.
