### ISSUE TITLE
Changing approval settings in OldDot creates an 'Everyone' approval workflow without an approver that leads to Hmm... page

### ISSUE THREAD

**Issue by garrettmknight** [Expensify/App#52776]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.63-3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:** https://github.com/Expensify/Expensify/issues/445681
**Issue reported by:** @kadiealexander 
**Slack conversation** (hyperlinked to channel name): [#expense](https://expensify.slack.com/archives/C06ML6X0W9L/p1731973185996689), but it should probably be in #retain

## Action Performed:

1. Create workspace
2. Invite three users: A, B, C
3. Enable approvals
4. Set approval workflow as A > B > C in ND
5. Navigate to OldDot workspace editor > Members

## Expected Result:
Approval should be set to Advanced

## Actual Result:
Approval is set to Submit/Approve + BASIC on the backend

6. Update approval to Advanced in OD (Notice that the forwardsTo we set in ND automatically populates so it's set on the backend)
7. Go back to ND > Members

## Expected Result:
We didn't really change anything in the workspace, so I'd expect it the workflows to look the same as they did before.

## Actual Result:
There's a workflow for Everyone that heads to a `Hmmm...` not there page when you click it.

## Workaround:
From my testing, this effectively stops users from setting a second level to a workflow on ND. Only workaround is to correctly set in OD.

The `Hmm...` not there bit is just confusing. I _think_ you can work around that by disabling and enabling approvals, but we should fix anyway.

## Platforms:
All

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

Uploading Screen Recording 2024-11-19 at 4.12.06 PM.mov…

  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @garrettmknight</details>

**Comment by tgolen** [comment]
I'll look into this once I have my VM running again (hopefully this week!)

**Comment by tgolen** [comment]
# Daily Update
- I wrote a test on the backend that verifies this is indeed a bug

### Next Steps
- @tgolen write a PR to fix the bug

#### ETA
- PR is written today (Nov 20), merged by Friday Nov 22, and deployed next week

**Comment by tgolen** [comment]
# Update
- I was able to write an [Auth PR](https://github.com/Expensify/Auth/pull/13255) to fix the bug
- I ran out of time to fully test it today
- The PR ended up being quite a bit larger than I expected which will result in a longer ETA

### Next Steps
- @tgolen Test the entire bug flow from start-to-finish to ensure it's fixed
- Submit the PR for review

#### ETA
- PR merged by Monday Nov 23

**Comment by tgolen** [comment]
# Daily Update
- I have tested everything and submitted the [Auth PR](https://github.com/Expensify/Auth/pull/13255) for review

### Next Steps
- @lakchote Review and merge the PR

#### ETA
- Tomorrow Nov 22

**Comment by lakchote** [comment]
PR reviewed and merged!

**Comment by tgolen** [comment]
# Daily Update
- Thank you @lakchote for reviewing and merging the Auth PR

### Next Steps
- Wait for deploy
- Verify this issue is fixed

#### ETA
- Deploy should happen today, Nov 25

**Comment by tgolen** [comment]
This was deployed. @garrettmknight Can you give it another shot and see how it's working?

**Comment by garrettmknight** [comment]
It worked, I think we're good to close!
