### ISSUE TITLE
[HOLD for payment 2024-12-05] Improve the UI test guidelines and add couple of examples

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#52771]
Coming from [here](https://expensify.slack.com/archives/C05LX9D6E07/p1731929294634979), we would like to improve the UI tests guidelines to make them easier to follow and more approachable for the community.

Let's also add a couple more examples of UI tests that the community could look at to help them create the tests for their issues.

**Comment by OlimpiaZurek** [comment]
Hi. I'm Olimpia from Callstack and I'd like to work on this issue.

**Comment by mountiny** [comment]
@OlimpiaZurek What is your ETA on this one? Can you try to have a draft ready today? Would be great to get this going so we can start asking for the tests sooner than later

**Comment by OlimpiaZurek** [comment]
I will try to get the draft PR ready today or tomorrow morning.

**Comment by OlimpiaZurek** [comment]
PR is ready for review: https://github.com/Expensify/App/pull/52867

**Comment by mountiny** [comment]
No regression testing or payments needed here
