### ISSUE TITLE
[$250] [CRITICAL] - Welcome Message GIF is not displayed

### ISSUE THREAD

**Issue by isagoico** [Expensify/App#52788]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.64-1
**Reproducible in staging?:** Yes 
**Reproducible in production?:** Yes

**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A

**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @zsgreenwald 
**Slack conversation** (hyperlinked to channel name): [#convert](https://expensify.slack.com/archives/C07HPDRELLD/p1731970650377549)

## Action Performed:
1. Navigate to a conversation where a welcome message was posted 

## Expected Result:
The gif image should load. 

## Actual Result:
Gif image is not loading. 

## Workaround:
N/A 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

![image](https://github.com/user-attachments/assets/464e0c1e-4d70-4f9a-9c6b-bf4a51d105f5)

![image](https://github.com/user-attachments/assets/a56815bb-7b6f-4eff-8902-bc2bb72916c2)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021859037104963002265</li>
        <li>Upwork Job ID: 1859037104963002265</li>
        <li>Last Price Increase: 2024-11-20</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @jjcoffee</details>

**Comment by RachCHopkins** [comment]
I can't work out how to repro, but it's clear from the testing and the thread that it's a very real issue.

**Comment by badeggg** [comment]
Guess it's because this js resource [thirdPartyScripts.js](https://new.expensify.com/r/thirdPartyScripts.js) is not fetched properly. While the name 'thirdPartyScripts.js' indicates that this file is a js type file, server actually responds with a html file.
![Screenshot 2024-11-20 at 11 10 14](https://github.com/user-attachments/assets/f86951f1-b9e1-4323-a928-47908ab1145b)
![Screenshot 2024-11-20 at 11 11 50](https://github.com/user-attachments/assets/603e8115-4262-4e5e-9f76-77a8444bb48a)

**Comment by jjcoffee** [comment]
It looks like the image is trying to load from `animations/animation_setupguide.gif` instead of the full URL to the CDN (https://d2k5nsl2zxldvw.cloudfront.net/images/animations/animation_setupguide.gif).

**Comment by MarioExpensify** [comment]
Looking into it, it seems the backend's onyx update is being sent with only `animations/animation_setupguide.gif` as path (as @jjcoffee mentioned). Looking into Auth it seems the URL is being correctly build, let me try to find out where this is getting cut.

**Comment by youssef-lr** [comment]
Yeah looks like we do construct it properly, very weird how it reaches the frontend cut off like that. I'll let you handle this @MarioExpensify but ping me if you need anything!

**Comment by ikevin127** [comment]
Most likely something to do with the CDN env variable on BE side since `https://d2k5nsl2zxldvw.cloudfront.net/images/` seems to be missing from the source of the image passed to the FE on recent **#admins** rooms.

This must've happened recently as I have older WS **#admins** rooms where the GIF shows as expected.

**Comment by MarioExpensify** [comment]
PR was merged & deployed to production.

**Comment by MarioExpensify** [comment]
@zsgreenwald provided [some production tests](https://expensify.slack.com/archives/C07HPDRELLD/p1732297915976789?thread_ts=1731970650.377549&cid=C07HPDRELLD), looks like we're good! Closing this.
