### ISSUE TITLE
Track expense - Error when submitting track distance expense to new workspace

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#52787]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.64-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5240743
**Email or phone of affected tester (no customers):** dfijdoijdifojdfo@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to self DM.
3. Track a distance expense from + menu.
4. Click Categorize it from the actionable whisper.
5. Click New workspace button (if there is existing workspace).
6. Select a category.
7. Submit the track distance expense to the workspace.

## Expected Result:
The track distance expense will be submitted to the workspace without issue.

## Actual Result:
Error shows up when categorizing track distance expense and submitting it to the workspace.
It shows
"Unexpected error submitting this expense. Please try again later.The workspace is no longer accessible. Please try again on a different workspace."

The newly created workspace chat also disappears after the error appears.

## Workaround:
Unknown

## Platforms:

- [x] Android: Standalone
- [x] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/150131fd-58c4-44b4-a08d-dc82075a9740

  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by AndrewGable** [comment]
@dukenv0307 @rlinoz @narefyev91 - Do you think this is related to https://github.com/Expensify/App/pull/52482?

**Comment by narefyev91** [comment]
> @dukenv0307 @rlinoz @narefyev91 - Do you think this is related to #52482?

Yeah it should be related - @rlinoz i double checked what cause the issue. If we use QA steps from this issue - `CategorizeTrackExpense` API call returns an error: "The workspace is no longer accessible. Please try again on a different workspace". If i manually remove `waypoints` from `CategorizeTrackExpense` - API call returns no errors - and flow is working fine. Could you please double check

**Comment by rlinoz** [comment]
Ah yes, this is happening because we will create the policy only after calculating the rate, not sure how we will fix this in the backend yet, but meanwhile let's revert that PR

**Comment by rlinoz** [comment]
Asked for CP here https://expensify.slack.com/archives/C07J32337/p1732105497368409

**Comment by kavimuru** [comment]
Issue fixed 

https://github.com/user-attachments/assets/6b3f2f7d-3db1-4cc4-9da0-5aa1aaea9388

**Comment by AndrewGable** [comment]
Thanks for the quick fix all!
