### ISSUE TITLE
[HOLD for payment 2024-12-03] [$125] Polish updates to Amex card flow

### ISSUE THREAD

**Issue by joekaufmanexpensify** [Expensify/App#52798]
Coming from [here](https://expensify.slack.com/archives/C06ML6X0W9L/p1732026655414689?thread_ts=1731525071.415359&cid=C06ML6X0W9L), we need to add support for the case where someone wants to setup an Amex personal on their workspace because they (and others) use it for their business. To do this, we'll:

- Add a third row on the Amex connection page. Header is `American Express Personal Cards`. Subheader `Select this if your cards are personal`. Mock below. 
- Selecting it does the same thing as the existing `American Express Business Cards` option. 

<img width="252" alt="image" src="https://github.com/user-attachments/assets/1fc5cc68-333e-4052-871b-7a3349e3fea0">

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021859223772392911036</li>
        <li>Upwork Job ID: 1859223772392911036</li>
        <li>Last Price Increase: 2024-11-20</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @twisterdotcom</details>

**Comment by twisterdotcom** [comment]
Does this need to be External? Or will @mountiny and @allgandalf handle it?

**Comment by narefyev91** [comment]
Hi, I'm Nicolay from Callstack - expert contributor group - and I would like to work on this issue.
