### ISSUE TITLE
[HOLD for payment 2024-12-05] [$250] Workspaces page - Update the New workspace button colour, and add "Go to workspace" to the three dot overflow menu

### ISSUE THREAD

**Issue by trjExpensify** [Expensify/App#52795]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.64-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @trjExpensify 
**Slack conversation**: [#convert thread](https://expensify.slack.com/archives/C07HPDRELLD/p1731974640186639)

## Action Performed:
1. Create a new account on new.expensify.com
2. Select "Manage my team's expenses"
3. Complete the onboarding steps
4. Click "Settings" bottom tab > Workspaces 

## Expected Result:
_This is a new feature_

1. Change the `New workspace` button to our standard button colour 
2. Add "Go to workspace" to the three dot overflow menu. When clicked, navigate to the workspace settings just like you tapped the whole row. 

![image](https://github.com/user-attachments/assets/364fc3c3-d161-47db-9827-fa53ad7d87f2)

## Actual Result:
The button colour is green
There's no "Go to workspace" option in the overflow menu. 

## Workaround:
N/A

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Standalone
- [x] Android: HybridApp
- [x] Android: mWeb Chrome
- [x] iOS: Standalone
- [x] iOS: HybridApp
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
In-line above. 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021858960137282592665</li>
        <li>Upwork Job ID: 1858960137282592665</li>
        <li>Last Price Increase: 2024-11-19</li>
<li>Automatic offers: </li>
<ul>
<li>gijoe0295 | Contributor | 104993249</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @trjExpensify</details>

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Update the New workspace button colour, and add "Edit workspace" to the three dot overflow menu

### What is the root cause of that problem?

new feature

### What changes do you think we should make in order to solve the problem?


1. Remove `success` props 

https://github.com/Expensify/App/blob/a73f681f60e940868db253b63234292e00a58f32/src/pages/workspace/WorkspacesListPage.tsx#L369

2. Add edit menu item 

https://github.com/Expensify/App/blob/a73f681f60e940868db253b63234292e00a58f32/src/pages/workspace/WorkspacesListPage.tsx#L180

```
threeDotsMenuItems.push({
    icon: Expensicons.Pencil,
    text: 'Edit Workspace',
    onSelected: item.action,
});
```

### What alternative solutions did you explore? (Optional)

**Comment by jayeshmangwani** [comment]
@Krishna2323 's [initial proposal](https://github.com/Expensify/App/issues/52795#issuecomment-2486615820) was a partial solution to the issue (addressing the button color only). They edited their proposal later, but by that time, @gijoe0295  had already posted their proposal.

**Comment by jayeshmangwani** [comment]
Lets go with @gijoe0295's [Proposal](https://github.com/Expensify/App/issues/52795#issuecomment-2486618054)

🎀 👀 🎀 C+ reviewed

**Comment by dannymcclain** [comment]
Updated the OP with a new mock based on related Slack threads. Posting the mocks here just for super ultra clarity.

![image](https://github.com/user-attachments/assets/06a13604-fc38-4761-b6ab-36456a0b527f)

![image](https://github.com/user-attachments/assets/abf56323-6d77-4bd2-b082-c384732acc98)

**Comment by jayeshmangwani** [comment]
This was a new feature, so the bug checklist does not apply here. Instead, I am proposing the following regression test:



## Regression Test Proposal

1. Go to Settings and navigate to Workspaces.
2. Press the 3-dot icon in the workspace row.
3. Verify that the Go to Workspace option is displayed.
4. Verify that pressing it opens the Workspace Settings.

Do we agree 👍 or 👎

**Comment by trjExpensify** [comment]
Nice, thanks. We have a 3-dot menu test in TestRail [here](https://expensify.testrail.io/index.php?/cases/view/2617188&group_by=cases:section_id&group_order=asc&display_deleted_cases=0&group_id=229065), copied below so you can see it. I think this needs a little refresh. Can you confirm the #announce menu item doesn't show here anymore, and suggest edits that incorporates testing for the new Go to Workspace option? Thanks!

> 1. Navigate the workspace settings list with the workspace selector set to the E logo
> 2. Click on the three dot menu next to a workspace
> 3. Make sure that followings are present "Go to #admins room" and "Go to #announce room"
> 4. Click on "Go to #admins room"
> 5. Verify you're navigated to the #admins room of the workspace and the LHN displays the #admins report
> 6. Navigate to any other report
> 7. Verify that the #admins report is not shown in LHN
> 8. Repeat steps 1 to 3 and navigate back to #admins room
> 9. Leave a comment in #admins room and navigate to any other report.
> 10. Verify that the #admins report remains shown and does not hide anymore.
> 11. Repeat steps 1 to 3
> 12. Click on "Go to #announce room"
> 13. Verify you're navigated to the #announce room of the workspace

**Comment by jayeshmangwani** [comment]
> I think this needs a little refresh. Can you confirm the #announce menu item doesn't show here anymore

@trjExpensify For older workspaces, I can still see the 'Go to #announce room' option, but it doesn't seem to be available in workspaces created today.

**Comment by jayeshmangwani** [comment]
@trjExpensify IMO, we can update the regression test to include the two new options: 'Go to workspace' and 'Delete workspace' These options should only be visible to admins or workspace owners.

For non-admin users, they won't have the 'Delete workspace' or 'Go to #admins room' options. Instead, they'll see the 'Leave' option. For these specific cases involving non-admins, do we need a separate regression test, or can we incorporate these scenarios into the existing TestRail?

<details>
  <summary>non-admin user's options</summary>
  
  <img width="1137" alt="Screenshot 2024-12-04 at 17 05 41" src="https://github.com/user-attachments/assets/604ff26a-8cc9-475b-ace1-bf25e4786016">
  
</details>

**Comment by trjExpensify** [comment]
>@trjExpensify For older workspaces, I can still see the 'Go to #announce room' option, but it doesn't seem to be available in workspaces created today.

Cool, and what about if you add 3+ members to that new workspace. Does it then show? 

>@trjExpensify IMO, we can update the regression test to include the two new options: 'Go to workspace' and 'Delete workspace' These options should only be visible to admins or workspace owners.

Yikes, `Delete workspace` should only be shown to a workspace owner. Can a non-owner admin actually delete the workspace? 

>For non-admin users, they won't have the 'Delete workspace' or 'Go to #admins room' options. Instead, they'll see the 'Leave' option. For these specific cases involving non-admins, do we need a separate regression test, or can we incorporate these scenarios into the existing TestRail?

We can add them in the same test case, with different headers for the scenarios.

**Comment by jayeshmangwani** [comment]
> Cool, and what about if you add 3+ members to that new workspace. Does it then show?

Ohh, yes it shows for 3+ members 🤦

**Comment by jayeshmangwani** [comment]
> Yikes, Delete workspace should only be shown to a workspace owner. Can a non-owner admin actually delete the workspace?

yes you're right, owner only can see the Delete option and non-owner admin cannot see/delete the workspace

**Comment by jayeshmangwani** [comment]
### 1. Precondition: User is the owner of the workspace

1. Navigate the workspace settings list with the workspace selector set to the E logo
2. Click on the three-dot menu next to a workspace.
3. Ensure the following options are present:

- "Go to workspace"
- "Delete workspace"
- "Go to #admins room"
- If the workspace has more than 3 participants, "Go to #announce room" should also be visible.
4. Click on "Go to workspace."
5. Verify that clicking it opens the Workspace Settings page.
6. Click on "Delete workspace."
7. Verify that the Delete Workspace confirmation modal appears.
8. In the modal:
- Confirm that clicking "Delete" deletes the workspace.
- Confirm that clicking "Cancel" closes the modal without any changes.
9. Click on "Go to #admins room"
10. Verify you're navigated to the #admins room of the workspace and the LHN displays the #admins report
11. Navigate to any other report
12. Verify that the #admins report is not shown in LHN
13. Repeat steps 1 to 3 and navigate back to #admins room
14. Leave a comment in #admins room and navigate to any other report.
15. Verify that the #admins report remains shown and does not hide anymore.
16. Repeat steps 1 to 3
17. Click on "Go to #announce room"
18. Verify you're navigated to the #announce room of the workspace


### 2. Precondition: User is an admin of the workspace

1. Navigate the workspace settings list with the workspace selector set to the E logo
2. Click on the three-dot menu next to a workspace.
3. Ensure the following options are present:

- "Go to workspace"
- "Go to #admins room"
- If the workspace has more than 3 participants, "Go to #announce room" should also be visible.
4. Click on "Go to workspace."
5. Verify that clicking it opens the Workspace Settings page.
6. Click on "Go to #admins room"
7. Verify you're navigated to the #admins room of the workspace and the LHN displays the #admins report
8. Navigate to any other report
9. Verify that the #admins report is not shown in LHN
10. Repeat steps 1 to 3 and navigate back to #admins room
11. Leave a comment in #admins room and navigate to any other report.
12. Verify that the #admins report remains shown and does not hide anymore.
13. Repeat steps 1 to 3
14. Click on "Go to #announce room"
15. Verify you're navigated to the #announce room of the workspace

### 3. Precondition: User is a member of the workspace

1. Navigate the workspace settings list with the workspace selector set to the E logo
2. Click on the three-dot menu next to a workspace.
3. Ensure the following options are present:

- "Go to workspace"
- "Leave"
- If the workspace has more than 3 participants, "Go to #announce room" should also be visible.

4. Click on "Go to workspace."
5. Verify that clicking it opens the Workspace Settings page.
6. Click on "Leave"
7. Verify that the workspace is no longer visible in the workspaces list.
8. Repeat steps 1 to 3
9. Click on "Go to #announce room"
10. Verify you're navigated to the #announce room of the workspace

**Comment by jayeshmangwani** [comment]
@trjExpensify, please have a look on this [regression test](https://github.com/Expensify/App/issues/52795#issuecomment-2517286193) it seems fairly detailed. Let me know if there's anything else that needs to be included here.

**Comment by trjExpensify** [comment]
Excellent! I've created an issue for Applause! 

Payment summary as follows: 

- $250 to @jayeshmangwani for the C+ review (go ahead and request!)
- $250 to @gijoe0295 for the fix (paid!)

Settled up, closing!

**Comment by garrettmknight** [comment]
$250 approved for @jayeshmangwani
