### ISSUE TITLE
Homepage - Enter your email or phone number input focused when there saved credentials

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#52791]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.64-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5241946
**Issue reported by:** Applause - Internal Team

## Action Performed:
precondition: user has saved credentials, and enabled autofill passwords
1. Go to https://www.expensify.com/
or https://staging.expensify.com/

## Expected Result:
The "Enter your email or phone number" input should not be focused

## Actual Result:
The "Enter your email or phone number" input is focused and saved credentials are suggested when navigating to the home page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/991b6ff9-ffd6-4741-97b1-7969cf27e014

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mallenexpensify** [comment]
Pulled up expensify.com on Android, Chrome and it didn't autofocus on the compose box
Since we're not using passwords any more, in favor of magic codes, I don't think we should prioritize fixing this
