### ISSUE TITLE
Wrong email sent during auto-reimbursement

### ISSUE THREAD

**Issue by ryanschaffer** [Expensify/App#52800]
**Version Number:** v9.0.63-3
**Reproducible in staging?:** Unsure
**Reproducible in production?:** Unsure
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?: Unsure
**If this was caught during regression testing, add the test name, ID and link from TestRail: No
**Email or phone of affected tester (no customers):** ryan@expensify.com
**Logs:** N/A
**Expensify/Expensify Issue URL:** Made it here and not E/E. 
**Issue reported by:** Ryan Schaffer
**Slack conversation** (hyperlinked to channel name): #retain: https://expensify.slack.com/archives/C07NZ8B1VTQ/p1732050274936679

## Action Performed:
1. Approve expense
2. Expense gets auto-reimbursed
3. Received incorrect email

## Expected Result:
I expected to receive an email that said Expensify US paid David Bondy $23.36. 

## Actual Result:
I got an email that said Expensify US paid you $23.26. 
(This made me think that I received money, but the YOU being referred to in the email subject is David Bondy, not me. I received the email that David Bondy should have got.) 

## Workaround:
Yes, but this is bad UX. 

## Platforms:
This is an email issue, so backend. Not platform dependent (I don't think). 

## Screenshots/Videos

<img width="930" alt="image" src="https://github.com/user-attachments/assets/87c2b0b0-822d-43fb-84a2-1788f8d5dc6a">

<img width="743" alt="image" src="https://github.com/user-attachments/assets/8c3334a6-d3a3-4467-9fb2-c1565cbc506b">

**Comment by ryanschaffer** [comment]
@blimpich Is knowledgable in this area. Not sure if he has the bandwidth to pick it up or not, but can be a resource.

**Comment by VictoriaExpensify** [comment]
There is some other work going on with incorrect emails [here](https://github.com/Expensify/App/issues/52120). I'm not sure they are entirely related, but they seem similar

**Comment by blimpich** [comment]
Can't pick up right now but will keep on radar

**Comment by VictoriaExpensify** [comment]
@Beamanator any chance this is related to the work you're doing on email notifications?

**Comment by Beamanator** [comment]
It looooks like here's the logs: https://staging.expensify.com/_devportal/tools/logSearch/#query=request_id:(%228e524bf999002b88-LAX%22)+AND+timestamp:[2024-11-19T17:34:55.263Z+TO+2024-11-19T19:34:55.263Z]&index=logs_expensify-031280

I will continue looking in a minute 😅

**Comment by Beamanator** [comment]
```
ReportUtils - Queued notifications for payment receipt ~~ payerEmail: 'accountspayable@expensify.com' payeeEmail: 'ryan@expensify.com'
```

Hmmmmmmmm

**Comment by Beamanator** [comment]
requestedTo: 'Expenses - Expensify US' 👍 
subject: 'Expenses - Expensify US paid you $23.36' ❌ 

Looks like ^ comes from `$payeeSubject` [here](https://github.com/Expensify/Web-Expensify/blob/b0a844b0190283290cc814add97ac03740a11180/lib/ReportUtils.php#L2562) which should only be used as the email `subject` if `$forPayer` is `false`, and that comes from `sendWalletPaymentReceipt` [here](https://github.com/Expensify/Web-Expensify/blob/b0a844b0190283290cc814add97ac03740a11180/lib/ReportUtils.php#L2531)...

I think the problem is that there's only 2 notifiable participants on the account..l

`ReportUtils - Found notifiable participants ~~ participantAccountIDs: '[0: '1381556' 1: '4314165']'`

... Which are Ryan & accountspayable@expensify.com

So we somehow thought ryan was being paid at this point

**Comment by Beamanator** [comment]
@lakchote and @rlinoz seem to also have a lot of context in the area i believe, hopefully 1 of them can help in the next few days? 🙏

**Comment by trjExpensify** [comment]
Coming from [the thread](https://expensify.slack.com/archives/C07NZ8B1VTQ/p1732050274936679). Just a note that we're keen to consolidate to the one email subject to both the payer and payee (the real one though! 😅) with the subjectLine: `[%payerFirstName% || %workspaceName%] paid %payeeFirstName% %amount%`

If a name isn't set, we should still fallback on the primaryLogin as standard.

**Comment by Beamanator** [comment]
Love it 👍  and i wish i understood how to make that simple sounding change, but our notification-creating code is kinda a webby mess so I am hoping someone with more context (those ping'd before & ben) could figure this out quicker than me

**Comment by rlinoz** [comment]
I think it goes wrong in this line: https://github.com/Expensify/Web-Expensify/blob/9b5bb16df975eadfd724db63ac01aa6c184920dd/lib/ReportUtils.php#L2470

We can't know for sure that the payee is the first in the `$participantAccountIDs` array.

We probably want to find the `accountID` of the submitter of the report

**Comment by Beamanator** [comment]
That soundsss pretty legit, any chance you want to take that task? :D

**Comment by rlinoz** [comment]
Yeah sure, I can fix the bug

@trjExpensify are we handling the subject change elsewhere?

**Comment by trjExpensify** [comment]
Nope, here would be great!


*Tom Rhys Jones *
*Expensify*

**Comment by rlinoz** [comment]
This is deployed to prod 🎉
