### ISSUE TITLE
Amex/Wells Fargo connection not working for direct feeds

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#52818]
From testing from @joekaufmanexpensify and @JmillsExpensify seems like the Amex connection is not working properly in NewDot but its in OldDot.

Investigate where this is breaking and fix it

**Comment by joekaufmanexpensify** [comment]
[Updated title](https://expensify.slack.com/archives/C06ML6X0W9L/p1732142804663789?thread_ts=1731609778.494899&cid=C06ML6X0W9L) as we're having the same issue with Wells Fargo

**Comment by mountiny** [comment]
Made a PR which adds much more logs to help debug. Also hopefully will fix the Wells Fargo issue

**Comment by mountiny** [comment]
Wells FArgo is fixed and the Amex connection is also fixed in the BE so we can close this now
