### ISSUE TITLE
[HOLD for payment 2024-12-25] E2E: Improve stability of linking test

### ISSUE THREAD

**Issue by hannojg** [Expensify/App#52813]
The e2e test pipeline produces a false positive now once a day on average. It is always the linking test that turns out false positive.
We should investigate why that test is unstable and fix it (it could also mean that there is actually a performance problem on that screen that causes performance to fluctuate).

Examples of false positives are:

- https://github.com/Expensify/App/pull/52743#issuecomment-2488228278
- https://github.com/Expensify/App/pull/51709#issuecomment-2485870606
- https://github.com/Expensify/App/pull/52656#issuecomment-2482795692

<details><summary>Issue Owner</summary>Current Issue Owner: @anmurali</details>

**Comment by hannojg** [comment]
cc @kirillzyusko

**Comment by hannojg** [comment]
I am available to look into this issue so feel free to assign me 📘

**Comment by hannojg** [comment]
Now that https://github.com/Expensify/App/pull/53854 is merged we are monitoring to see if the stability has increased.

However, there are current build errors in the e2e pipeline which @perunt is working on fixing

**Comment by puneetlath** [comment]
>However, there are current build errors in the e2e pipeline which @perunt is working on fixing

Is this still ongoing?

**Comment by perunt** [comment]
> Is this still ongoing?

The pipeline is currently working. I'm now fixing issues [here](https://margelo.slack.com/archives/C05LX9D6E07/p1734438960216189) and adding new e2e tests.

Do you have anything specific you'd like me to look into?

**Comment by puneetlath** [comment]
Nothing in particular. Just wondering about the status of this issue and whether it still needs to be open.

**Comment by perunt** [comment]
We received one reaction so far, but to be honest, it looks like a valid one.
https://margelo.slack.com/archives/C05LX9D6E07/p1734057241423909
So, if we receive some issues related to that, we can reopen it. But for now, after 7 days, there have been no issues with it, so I can carefully assume that it is fixed

**Comment by puneetlath** [comment]
Ok sounds good @perunt. I think all that's left then is for @anmurali to pay out @eVoloshchak.

**Comment by anmurali** [comment]
**Payment Summary**

- [ ] @eVoloshchak $250 approved via New Dot.
