### ISSUE TITLE
Track expense- Category list loads infinitely when categorizing expense from invited workspace

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#52834]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.64-4
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Y
**Email or phone of affected tester (no customers):** applausetester+kh0711008@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. [User A] Invite User B to workspace.
3. [User B] Do not open workspace chat invited by User A.
4. [User B] Go to self DM.
5. [User B] Track a manual expense.
6. [User B] Select Categorize it from the actionable whisper.
7. [User B] Click on the invited workspace.

## Expected Result:
Category list will load without issue.

## Actual Result:
Category list loads infinitely when categorizing expense from invited workspace and the invited workspace chat has not been opened yet.

## Workaround:
Unknown

## Platforms:

- [x] Android: Standalone
- [x] Android: HybridApp
- [x] Android: mWeb Chrome
- [x] iOS: Standalone
- [x] iOS: HybridApp
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/18eb49b0-fe39-4192-8bad-259b8e0fabe4

 
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by huult** [comment]
This is backend issue. 

- <img width="1510" alt="Screenshot 2024-11-21 at 16 06 31" src="https://github.com/user-attachments/assets/546567d5-2613-45bd-9e6e-945df85b683d">

**Comment by johncschuster** [comment]
Triaged

**Comment by johncschuster** [comment]
Waiting on proposals for this one

**Comment by huult** [comment]
we have one proposal to review

**Comment by johncschuster** [comment]
I couldn't action this today. I will check it out this weekend.

**Comment by johncschuster** [comment]
@IuliiaHerets can I get a retest on this to see if it persists?

**Comment by IuliiaHerets** [comment]
@johncschuster Tester can't repro this issue in the latest build 

https://github.com/user-attachments/assets/4201a6b6-f175-4fd6-8a86-df930e0435f6

**Comment by johncschuster** [comment]
Great! In that case, let's close this up!
