### ISSUE TITLE
[$250] Users gets logged out after posting a list in this  FullStory-https://fsty.io/v/Gj3y2abz

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#52838]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:** Needs Reproduction
**Reproducible in production?:** Needs Reproduction
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @danielrvidal 
**Slack conversation** (hyperlinked to channel name): [ts_external_expensify_convert](https://applause-ts.slack.com/archives/C07HPDRELLD/p1732069424756029)

## Action Performed:

1. [luxuryintuition@icloud.com](mailto:luxuryintuition@icloud.com) is writing a note for herself (screen 1)
2. Then get’s logged out immediately [when posting](https://fsty.io/v/v93yeEEm)
3. Then when she comes back, the list is not there (image 2).

## Expected Result:
User remains logged in after posting a list in fullstory
## Actual Result:
User gets logged out after posting a list in fullstory
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details>

![image (9)](https://github.com/user-attachments/assets/706cd431-dcf5-4a4d-af3a-72d6fdaf70dc)

![image (10)](https://github.com/user-attachments/assets/47471623-c17f-4948-a030-603c6b099e35)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021859430214689131084</li>
        <li>Upwork Job ID: 1859430214689131084</li>
        <li>Last Price Increase: 2024-11-21</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @ahmedGaber93</details>

**Comment by greg-schroeder** [comment]
Hmm ... I can't reproduce this

**Comment by greg-schroeder** [comment]
Removing `Help Wanted` until we can reproduce. @ahmedGaber93 - do you mind giving reproduction a shot? Maybe I'm missing something. 🤔

**Comment by ahmedGaber93** [comment]
Honestly, this is the first time I hear about `FullStory`. Also, there is no clear reproduction steps, is there is any guide about how to integrate and using `FullStory` with expensify?

**Comment by greg-schroeder** [comment]
Hmm. I'm going to close as I still can't repro, but please reopen if you disagree.
