### ISSUE TITLE
Web - Chat - Native emojis are doubled in the composer when selected

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#52840]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.64-4
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5238143&group_by=cases:section_id&group_id=229070&group_order=asc
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Navigate to https://staging.new.expensify.com/
2. Log in with a new Gmail account
3. Create a 1:1 DM with any account
4. Right click in the composer and click on "Emoji"
5. Select any emoji from the list

## Expected Result:
Emoji should only be inserted once.

## Actual Result:
Native emojis are doubled in the composer when selected.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/99db4ef7-5408-4a6b-8dc2-d0bfe957b70f
  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by twisterdotcom** [comment]
@IuliiaHerets - you've put `MacOS: Chrome / Safari` here, but... the video is on Windows and I can't recreate on Mac.

https://github.com/user-attachments/assets/e370c5fc-d0a0-4050-a307-8e3caa732dd6

**Comment by IuliiaHerets** [comment]
@twisterdotcom This is our standard format for submitting an issue, the error is reproduced on Win/Chrome. 
Issue is still valid, build - v9.0.65-2

https://github.com/user-attachments/assets/047fd59d-fbfd-4174-988f-68ae0d59397d

**Comment by QichenZhu** [comment]
This is a known issue https://issues.chromium.org/issues/40794925 in Chromium on Windows. The input event is sent twice.

**Comment by twisterdotcom** [comment]
I don't think we should try to fix this on our end if the issue is with the underlying platform. If this were a big feature of ours, I would leave it open and hold on that, but it's not. It's an emoji picker. So I'm going to close in our repo for now and one day, the Chromium team will magically fix it.

Thanks so much for pointing that out @QichenZhu.
