### ISSUE TITLE
Copilot name not displayed properly if user don't have chat history

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#52853]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.64-4
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @twisterdotcom 
**Slack conversation** (hyperlinked to channel name): [ts_external_expensify_bugs](https://expensify.slack.com/archives/C049HHMV9SM/p1731933726306869)

## Action Performed:

1. User A and User B have an existing chat
2. User A adds User C as a copilot. (User C has not interacted with User B)
3. User C copilots into User A's account and sends a message to User B

## Expected Result:
Main name for the message is from User C and message as on behalf of user A
## Actual Result:
Main name for the message is from User A on behalf of User A

## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details>

![image (11)](https://github.com/user-attachments/assets/782cbbee-3afb-46f0-a1be-104fdf160dc4)

![Snip - New Expensify - Google Chrome (2)](https://github.com/user-attachments/assets/3a00093b-b308-4bb1-a13c-ef004cb4cce3)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @dangrous</details>

**Comment by dangrous** [comment]
This is on prod so we should be good here - can we test again? Thanks!
