### ISSUE TITLE
Group - Website crashes when leaving group chat

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#52868]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.65-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5247671&group_by=cases:section_id&group_order=asc&group_id=229067
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Open the staging.new.expensify.com website.
2. Open any group chat or create one if necessary.
3. Tap on the group header.
4. Tap on "Leave"
5. Verify the user succesfully left and the group disappeared from LHN.

## Expected Result:
User should be able to leave and the group should disappear from LHN.

## Actual Result:
Website crashes after leaving a group chat.
Error Message - "Uh oh, something went wrong."
Issue occasionally reproduces on Web and reproduces every time on mWeb.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/7772911a-6793-46e2-9ab6-470326aaf724

[2111_2.txt](https://github.com/user-attachments/files/17845066/2111_2.txt)

  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mkzie2** [comment]
@madmax330  The same RCA with https://github.com/Expensify/App/issues/52864.

**Comment by chiragsalian** [comment]
Fix has been tested - https://github.com/Expensify/App/issues/52862#issuecomment-2494619078, removing blocker label.

**Comment by Christinadobrzyn** [comment]
I think this is the same issue, right? https://github.com/Expensify/App/issues/52864

So can this be closed without payment?

**Comment by chiragsalian** [comment]
Yeah we can close this out. The fix is live. Contributor payment will be handled here - https://github.com/Expensify/App/issues/52864
