### ISSUE TITLE
Workspace - Custom invite message remains when invite other members

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#52869]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.65-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5250724&group_by=cases:section_id&group_order=asc&group_id=229065
**Email or phone of affected tester (no customers):** gocemate+a2880@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Create new workspace
2. Go to Members> Invite member> Add email address> Click next
3. In message field type a custom invite message> Invite
4. Click on Invite member button> Add email address> Click next
5. Take a look at invite message content

## Expected Result:
Workspace description should be default invite message when invite new members

## Actual Result:
Workspace description is not default invite message when invite new members after once setting a custom invite message

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [x] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/41a81fef-6fdd-4469-9a1c-289840e14872

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mkzie2** [comment]
Expected as per https://github.com/Expensify/App/issues/51096.

**Comment by NikkiWines** [comment]
Yep, not a blocker nor a bug - thanks for pointing that out @mkzie2 🙇
