### ISSUE TITLE
[HOLD for payment 2024-12-03] [HOLD for payment 2024-11-29] Search - Website crashes after exploring expenses in search for some time

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#52864]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.65-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Open the staging.new.expensify.com website.
2. Log in with an account with several expenses on it.
3. Tap on search on the bottom of the page.
4. Open any expense.
5. Tap on the arrow on the top left corner.
6. Open a different expense.
7. Tap on the arrow on the top left corner.
8. Repeat steps 4 - 5 a few more times.
9. Verify that the user can continue exploring all the expenses without the website crashing.

## Expected Result:
The user should be able to explore expenses in search without the website crashing.

## Actual Result:
The website crashes after opening and closing expenses for some time in search section.
Error Message - "Uh oh, something went wrong."

## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/044d8248-6eda-4453-8974-b993896758b3

[2111_1.txt](https://github.com/user-attachments/files/17844617/2111_1.txt)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @CortneyOfstad</details>

**Comment by chiragsalian** [comment]
Fix has been tested - https://github.com/Expensify/App/issues/52862#issuecomment-2494621567
removing blocker label.

**Comment by mountiny** [comment]
@rayane-djouah can you please complete the checklist?

**Comment by CortneyOfstad** [comment]
@rayane-djouah — sent you an offer in Upwork [here](https://www.upwork.com/nx/wm/offer/105082686). Please accept and complete the check list at your earliest convenience — thanks!

**Comment by Christinadobrzyn** [comment]
@rayane-djouah can you confirm if this is the same issue? https://github.com/Expensify/App/issues/52868 I think so?

**Comment by MonilBhavsar** [comment]
Thank you all! 🙇
