### ISSUE TITLE
mWeb-chat-The text and code block box is smaller in staging

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#52870]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.65-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Issue was found when executing this PR:** https://github.com/Expensify/App/pull/52680
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/home
2. Open a chat
3. Paste ``te`](https://dev.new.expensify.com:8082/r/2157807467093927/4055329730264388003)`
4. Send the message

## Expected Result:
The text and code block box must look consistent in staging and production.

## Actual Result:
The text and code block box is smaller in staging but in production, it is slightly bigger.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/3f7becfa-a6a1-470c-9d9b-537460692e03
  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lakchote** [comment]
This is not a blocker, and the text size rendered in staging when pasting

``[`te`](https://dev.new.expensify.com:8082/r/2157807467093927/4055329730264388003)``

is consistent with the text size from standard code block:

**Staging**
<img width="295" alt="image" src="https://github.com/user-attachments/assets/20883adc-9c40-4c06-9dd1-e64bb15c73cc">


**Production**
<img width="295" alt="image" src="https://github.com/user-attachments/assets/27e9c541-7863-4e43-838a-1927f24b8664">

Closing the issue.
