### ISSUE TITLE
Hybrid - Attachment-Attachments become unavailable after sending them to the chat

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#52885]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.65-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5241952
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Launch staging new.expensify Hybrid app and sign in with gmail account.
2. Open 1:1 chat.
3. Tap + icon near the compose box.
4. Select "Add attachment".
5. Select any option and tap Send.
6. Observe chat history.

## Expected Result:
Attachment is available for viewing in the chat after sending it.

## Actual Result:
Attachment become unavailable in 1-2 seconds after sending it to the chat. Preview of the image in the chat turns blank.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [x] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/05a43639-fa8e-46f5-b415-943b7d2df751

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by huult** [comment]
I can't reproduce this issue. This attachment in the ticket is the Expensify source. Maybe we have updated the backend, which is why we can't reproduce it anymore.

https://github.com/user-attachments/assets/c802d70c-3e09-4a41-840d-1e14a759e128

**Comment by twisterdotcom** [comment]
Yes, agree. I cannot reproduce either.
