### ISSUE TITLE
mWeb - Search - Long thread message open in search is not shown with cursor

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#52902]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** V9. 0.65-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Open app in both mweb and Android
2. Open 1:1 chat with an user
3. Paste the long text - Jxxj, jh j j n n j jj jj j jjcjcjcjcjcjccjcjjcjccjjcjcjccjcjjcjcjvjvjv
4. Send the message
5. Long press the message sent and open reply in thread
6. Tap on search at top
7. Tap text shown in drop down

## Expected Result:
Long thread message open in search must show cursor in both mweb and Android.

## Actual Result:
In Android, long thread message open in search is shown with cursor but in mweb cursor is not shown.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/d531c1bc-4029-4825-aed9-43a99930ac1a

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by FitseTLT** [comment]
[Dupe](https://github.com/Expensify/App/issues/52599)
