### ISSUE TITLE
[HOLD for payment 2024-12-12] [$250] Take a 2-minute tour task not displayed in concierge

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#52908]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.64-4
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @danielrvidal 
**Slack conversation** (hyperlinked to channel name): [ts_external_expensify_convert](https://applause-ts.slack.com/archives/C07HPDRELLD/p1731371352606329)

## Action Performed:
1. Go to staging.new.expensify.com
2. Signup for new account (use a non gmail account like - [abc@defg123.com](mailto:abc@defg123.com)
3. Choose Track and budget expenses and continue
## Expected Result:
Take a 2-minute tour task displayed in concierge
## Actual Result:
Take a 2-minute tour task not displayed in concierge

## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details>

![image (12)](https://github.com/user-attachments/assets/8720a10e-e2d2-48d4-b6b6-6f799eeab3a3)

https://github.com/user-attachments/assets/f1329ea2-e33c-45b9-be3b-cec11ebb393b

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021859657220522969112</li>
        <li>Upwork Job ID: 1859657220522969112</li>
        <li>Last Price Increase: 2024-11-21</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

**Comment by sonialiap** [comment]
@rafecolton do you think this is BE or FE?

**Comment by rafecolton** [comment]
So what's the right way to get this assigned to everybody? Do I assign you both manually?

**Comment by c3024** [comment]
Yes, I think that is the way.

**Comment by sonialiap** [comment]
Nice, adding the labels 💃

**Comment by sonialiap** [comment]
Not overdue, waiting for PR review from Rafe https://github.com/Expensify/App/pull/52912

**Comment by rafecolton** [comment]
PR merged! Marking this `Reviewing`

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by sonialiap** [comment]
Payment summary:
- @rushatgabhane $250 via NewDot - please complete the [checklist](https://github.com/Expensify/App/issues/52908#issuecomment-2520555585)
- @c3024 $250 via NewDot

**Comment by sonialiap** [comment]
I'm OOO Dec 16-20, adding a leave buddy

next steps:
- @rushatgabhane complete the [checklist](https://github.com/Expensify/App/issues/52908#issuecomment-2520555585)
- add regression test if applicable

**Comment by rafecolton** [comment]
Not overdue, waiting on @rushatgabhane I believe

**Comment by sakluger** [comment]
I bumped Rushat in Slack as well.

**Comment by sakluger** [comment]
Thanks!

**Comment by garrettmknight** [comment]
$250 approved for @rushatgabhane
