### ISSUE TITLE
Search - There is no WS from search suggestions when searching via Query Syntax

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#52911]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.65-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5246998
**Email or phone of affected tester (no customers):** testpayment935+664@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
Prerequisite:
Create WS and submit an 10$ expense

1. Navigate to http://www.staging.new.expensify.com/
2. Click on the search icon on the top right
3. Type "to:"
4. Notice there’s an autocomplete suggestion to use the search syntax for to

## Expected Result:
Search suggestions include workspaces

## Actual Result:
Search suggestions didn't include workspaces. Only users are displayed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/abe6cfc3-7b1c-4de6-8cf2-cafa9cb4adfc

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by alexpensify** [comment]
I didn't get to test this one before going OOO. This week, I'll try to log in to confirm the next steps.

**Comment by alexpensify** [comment]
No update

**Comment by alexpensify** [comment]
@luacmartins—I think this is by design for Search, but let me know if I should reopen it. I confirmed that I only see emails. 

![2024-12-02_21-16-37](https://github.com/user-attachments/assets/09dda173-d262-4195-a872-1181906aca21)

**Comment by luacmartins** [comment]
Yea, that's only emails since we send the request to a specific person in the workspace
