### ISSUE TITLE
[HOLD for payment 2024-12-05] [$250] In Search LHN, only saved search area is scrollable rather than the whole LHN being scrollable

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#52910]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.64-4
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @shawnborton 
**Slack conversation** (hyperlinked to channel name): [ts_external_expensify_expense](https://expensify.slack.com/archives/C06ML6X0W9L/p1732197568030849)

## Action Performed:
Prerequisite:  User have more than 4 saved searches
1. Click Search
2. Scroll the LHN
## Expected Result:
The whole LHN scrolls just like it does in Settings
## Actual Result:
Only saved search area is scrollable
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details>

<img src="https://github.com/user-attachments/assets/b084a79f-cf71-47b4-8162-a6e5df349e89" width="40%" height="40%">

https://github.com/user-attachments/assets/b6578320-8678-4f5b-8dc7-61824a5f15ae

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021859709289451685912</li>
        <li>Upwork Job ID: 1859709289451685912</li>
        <li>Last Price Increase: 2024-11-21</li>
<li>Automatic offers: </li>
<ul>
<li>allgandalf | Reviewer | 105066006</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @jliexpensify</details>

**Comment by FitseTLT** [comment]
Might be intentional we want the search types to always be visible

**Comment by shawnborton** [comment]
This is a bug, we want the whole area to be scrollable like we have on Settings.

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
In search LHN, only the saved search is scrollable.
### What is the root cause of that problem?
Currently, we only wrap the saved search list with a scroll view, so it's only the saved search that is scrollable.
https://github.com/Expensify/App/blob/4c44827398f884af626872c33f64dd358d19eff4/src/pages/Search/SearchTypeMenu.tsx#L275-L280


### What changes do you think we should make in order to solve the problem?

Wrap the whole search type menu in scroll view instead and remove the scroll view from the saved searches.
https://github.com/Expensify/App/blob/4c44827398f884af626872c33f64dd358d19eff4/src/pages/Search/SearchTypeMenu.tsx#L246-L284

**Comment by bernhardoj** [comment]
PR is ready

cc: @allgandalf

**Comment by jliexpensify** [comment]
Payment Summary

- C: @bernhardoj $250 (to be paid via New.Dot)
- C+: @allgandalf (to be paid via Upworks)

[Upwork job](https://www.upwork.com/jobs/~021859709289451685912)

**Comment by bernhardoj** [comment]
Requested in ND.

**Comment by JmillsExpensify** [comment]
$250 approved for @bernhardoj

**Comment by jliexpensify** [comment]
Paid and job closed
