### ISSUE TITLE
Update Pullerbear to assign Concierge reviewer to HelpDot PRs

### ISSUE THREAD

**Issue by stephanieelliott** [Expensify/App#52930]
### Problem: 

HelpDot PRs are often approved despite not meeting our internal quality standards for helpsite articles. 

### Solution

Assign a Concierge team member to review all HelpDot PRs prior to engineering review. 

### Context: 

See this Slack conversation: https://expensify.slack.com/archives/GP2FVSJ7Q/p1732197881553919?thread_ts=1732056046.254649&cid=GP2FVSJ7Q

------

### Function: 

When an App PR with changes to the docs is assigned to PullerBear for review, in addition to the assigned engineer, assign someone from concierge. Then comment on the issue with Concierge reviewer checklist. 

### Concierge reviewer checklist: 

 - [ ] **I have verified the accuracy of the article**
    - [ ] The article is within a hub that makes sense, and the navigation is correct 
    - [ ] All processes, screenshots, and examples align with current product behavior.
    - [ ] All links within the doc have been verified for correct destination and functionality.
 - [ ] **I have verified the readability of the article**
    - [ ] The article's language is clear, concise, and free of jargon.
    - [ ] The grammar, spelling, and punctuation are correct.
    - [ ] The article contains at least one image, or that an image is not necessary
- [ ] **I have verified the formatting of the article** 
    - [ ] The article has consistent formatting (headings, bullet points, etc.) with other HelpDot articles and that aligns with the [HelpDot formatting standards](https://stackoverflowteams.com/c/expensify/questions/17353).
    - [ ] The article has proper text spacing and breaks for readability.
- [ ] **I have verified the article has the appropriate tone and style**
    - [ ] The article's tone is professional, friendly, and suitable for the target audience.
    - [ ] The article's tone, terminology, and voice are consistent throughout.
- [ ] **I have verified the overall quality of the article**
    - [ ] The article is not missing any information, nor does it contain redundant information.
    - [ ] The article fully addresses user needs.
- [ ] **I have verified that all requested improvements have been addressed** 

For more detailed instructions on completing this checklist, see [How do I review a HelpDot PR as a Concierge Team member?](https://stackoverflowteams.com/c/expensify/questions/20516)

**Comment by rafecolton** [comment]
Oh interesting, I didn't realize that label assigned design - Shawn, you can disregard

**Comment by rafecolton** [comment]
Wow that `NewFeature` label is aggressive 😅

**Comment by rafecolton** [comment]
Catching up from OOO last week, hope to get to this very soon

**Comment by rafecolton** [comment]
Got a draft PR up

**Comment by rafecolton** [comment]
Thanks for your patience, PR is up for review

**Comment by stephanieelliott** [comment]
Thanks @rafecolton! Looks like this has been deployed to prod now.

**Comment by rafecolton** [comment]
Yes it has!
