### ISSUE TITLE
[$250] Not recognizing selected category while receipt is scanning.

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#52936]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.64-4
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @joekaufmanexpensify 
**Slack conversation** (hyperlinked to channel name): [ts_external_expensify_bugs](https://expensify.slack.com/archives/C049HHMV9SM/p1732122906315359)

## Action Performed:
1. Scan a receipt and don't select category
2. Open the report and select a category while the receipt is scanning
## Expected Result:
Category type saved for expense
## Actual Result:
The selection appeared in the comments but was not saved, Selecting the category the second time worked.
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details>

![image (13)](https://github.com/user-attachments/assets/0656717d-8fc2-46db-872f-3a42f48bc55a)

![image (14)](https://github.com/user-attachments/assets/26a89922-1b4b-49fc-acc5-6c14df6d0eb8)

https://github.com/user-attachments/assets/66791930-b3f4-4bf3-a0be-1b74c48aff65

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021861189785093636018</li>
        <li>Upwork Job ID: 1861189785093636018</li>
        <li>Last Price Increase: 2024-12-09</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @allroundexperts</details>

**Comment by missbond2017** [comment]
Confirmed, I can repro this bug.
When you chose the Category and at the same time the Merchant scan is done, then the bug happened.

**Comment by RachCHopkins** [comment]
I can't repro this - it works fine for me.

**Comment by RachCHopkins** [comment]
Smart. Yes I can reproduce this with a custom category, not the defaults.

**Comment by missbond2017** [comment]
> ## Proposal
> ### Please re-state the problem that we are trying to solve in this issue.
> Not recognizing selected category while receipt is scanning.
> 
> ### What is the root cause of that problem?
> The **transactionCategory** in L618 used an old value.
> 
> https://github.com/Expensify/App/blob/04ac4c6e0f40151cf0450b1a68318461ce8ac18f/src/components/ReportActionItem/MoneyRequestView.tsx#L618
> 
> And the **transactionCategory** is defined in L123.
> https://github.com/Expensify/App/blob/04ac4c6e0f40151cf0450b1a68318461ce8ac18f/src/components/ReportActionItem/MoneyRequestView.tsx#L114-L127
> ### What changes do you think we should make in order to solve the problem?
> We need to use the new value from transaction?.category. In L618 it should be 
> 
> ```
> title={updatedTransaction?.category ?? transaction?.category}
> 
> ```
> You can check the **Tag** and **Tax**, they use the **category** as parameter to the the **TagName/TaxName**

**Comment by RachCHopkins** [comment]
@allroundexperts how do you feel about the proposal we have so far?

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by missbond2017** [comment]
By adding some custom categories, I can reproduce this issue.

**Comment by allroundexperts** [comment]
> By adding some custom categories, I can reproduce this issue. And I have provided a [proposal](https://github.com/Expensify/App/issues/52936#issuecomment-2499691671) to resolve this issue.

@missbond2017 Have you pulled in the latest main? I can't seem to reproduce it as well.

**Comment by RachCHopkins** [comment]
Note: It must be custom categories, not system defaults @allroundexperts .

**Comment by allroundexperts** [comment]
> Note: It must be custom categories, not system defaults @allroundexperts .

@RachCHopkins I tested with a custom category. Can you reproduce this on staging?

**Comment by missbond2017** [comment]
@allroundexperts It is easy to reproduce, when you create some custom categories.

**Comment by RachCHopkins** [comment]
@allroundexperts seems to be sticking for me on Staging now!

**Comment by missbond2017** [comment]
@RachCHopkins Can you reproduce on Staging?

**Comment by RachCHopkins** [comment]
@missbond2017 nope, not at all.

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (Second week)

**Comment by RachCHopkins** [comment]
Thanks @mvtglobally !
