### ISSUE TITLE
[Company cards] Cards are not synce upon connection in NewDot

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#52952]
Coming from [here](https://expensify.slack.com/archives/C06ML6X0W9L/p1732223189515069?thread_ts=1732108983.281759&cid=C06ML6X0W9L), the card transactions are not synced up upon connecting bank feed and assigning a card either custom or direct feed.

We need to call the scrapeCard command when the card is assigned so we pull the latest transactions for the user

**Comment by mountiny** [comment]
Either me or @nkuoch will pick this one up

**Comment by mountiny** [comment]
Not overdue, we will start working on this

**Comment by nkuoch** [comment]
Done!
