### ISSUE TITLE
[HOLD for payment 2024-12-19] [$150] IOS/Android-Verify account-Inconsistent behavior when returning from Let's make sure it is you

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#52959]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.65.1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/52232
## Action Performed:
precondition: user has enabled Expensify card
1. Open the app and log in
2. Navigate to the account settings > Security >Copilot
3. Continue with the flow
4. On "Let's make sure it is you" step, tap the back icon
5. Create a new workspace and open the workspace settings
6. Select More feature and enable Workflows
7. Open Workflows > toggle on "Make or track payments" option
8. Tap Connect bank account > any option
9. On "Let's make sure it is you" step, tap the back icon
10. Navigate to the workspace with Expensify card enabled
11. Start issuing a new card
12. On "Let's make sure it is you" step, tap the back icon
13. Navigate to account settings > Profile > Contact method
14. Start adding a new contact method
15. On "Let's make sure it is you" step, tap the back icon

## Expected Result:
User is navigated to the previous screen after tapping the back icon on "Let's make sure it is you" in the flows where code validation is required

## Actual Result:
When tapping the back icon on "Let's make sure it is you" step in the Add copilot and Add bank account flows (steps 4 and 9), the keyboard gets dismissed while in the other flows (Issue a new card, Add new contact method, Reveal card details) user is returned to the previous screen immediately (steps 12 and 15)

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Standalone
- [x] Android: HybridApp
- [ ] Android: mWeb Chrome
- [x] iOS: Standalone
- [x] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/e9500f66-66e4-43b5-88c2-42e9df2752b0

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021861312036312016837</li>
        <li>Upwork Job ID: 1861312036312016837</li>
        <li>Last Price Increase: 2024-11-26</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @VictoriaExpensify</details>

**Comment by VictoriaExpensify** [comment]
Hmm ok so I think this is a pretty minor issue, but because we do want everything to be consistent, we should fix it.

My feeling is that this is a pretty easy fix so I'm going to lower the bounty on this one. If I'm missing anything to do with the complexity here, please let me know.

**Comment by danieldoglas** [comment]
assigned

**Comment by bernhardoj** [comment]
PR is ready

cc: @thesahindia 

@VictoriaExpensify btw, I think we can keep the price at a normal price (250) since we need to fix this at 3 pages, so we need to test more too.

**Comment by VictoriaExpensify** [comment]
Payment summary:
Contributor: @bernhardoj owed $250 via Upwork
C+: @thesahindia owed $250 via Upwork

**Comment by bernhardoj** [comment]
Requested in ND.

**Comment by JmillsExpensify** [comment]
$250 approved for @bernhardoj

**Comment by garrettmknight** [comment]
$250 approved for @thesahindia
