### ISSUE TITLE
[HOLD for payment 2024-12-07] Clean up terms used when adding a card feed

### ISSUE THREAD

**Issue by joekaufmanexpensify** [Expensify/App#52970]
@JmillsExpensify and I were chatting and are thinking how we refer to adding a card feed could be more consistent and less jargony. Here are some screenshots highlighting use of a bunch of different terms to refer to the same thing: 

![CleanShot_2024-11-22_at_14 54 56_2x-2024-11-22 16_22_21 796](https://github.com/user-attachments/assets/b232cd7c-1ac7-499f-8f03-3ff94ed6f76f)

![CleanShot_2024-11-22_at_14 55 28_2x-2024-11-22 16_22_30 067](https://github.com/user-attachments/assets/65251170-6c80-4df2-9bcc-ed2d48068377)

![CleanShot_2024-11-22_at_14 56 05_2x-2024-11-22 16_22_33 868](https://github.com/user-attachments/assets/5583e457-c78d-4bc6-8125-98fbf01606f2)

Let's clean this up. Specifically: 

- Let's update the button to add a new feed from `Add company cards` to `Add cards` (on both the empty state and feed selector). 
- Let's change the header on the feed selector from `Select card feed` to `Select cards` (also when selecting a feed to assign a card from the workspace member profile). 
- Let's change the header when adding a card feed from `Add card feed` to `Add cards`. 

<details><summary>Issue Owner</summary>Current Issue Owner: @puneetlath</details>

**Comment by joekaufmanexpensify** [comment]
Likely going to be someone from callstack who takes this. [Discussing](https://expensify.slack.com/archives/C06ML6X0W9L/p1732293686499729?thread_ts=1732108983.281759&cid=C06ML6X0W9L)!

**Comment by joekaufmanexpensify** [comment]
@VickyStash mind commenting so i can assign you?

**Comment by VickyStash** [comment]
The [PR](https://github.com/Expensify/App/pull/53054) has been opened for the review!

**Comment by joekaufmanexpensify** [comment]
@VickyStash one more minor change. Could we also change `Learn more about the connection methods` to `Learn more about the options` and remove the extraneous period?

**Comment by VickyStash** [comment]
Sure, done: https://github.com/Expensify/App/pull/53054#issuecomment-2500078187

**Comment by joekaufmanexpensify** [comment]
TY!

**Comment by puneetlath** [comment]
Sounds good. Closing.
