### ISSUE TITLE
[HOLD for payment 2024-12-07] Debug Mode - "Hmm... it's not here page" is shown when deleting a created violation

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#52997]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.66-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Can't check on prod as no `Debug mode` option
**Issue was found when executing this PR:** https://github.com/Expensify/App/pull/50745
**Email or phone of affected tester (no customers):** dave0123seife@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Enable debug mode in Troubleshoot
3. Open an expense thread (create one if you don't have any)
4. Enter debug view then check on "View transaction" tab
5. Go to "violations" > Create a violation and save it
6. Go to the created violation and delete it.

## Expected Result:
Violation is deleted and navigates to the previous page (violation tab).

## Actual Result:
"Hmm... it's not here page" is shown.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/dc742a93-f880-4c5a-a263-512a0a6b23ba

 
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @slafortune</details>

**Comment by DylanDylann** [comment]
cc @pac-guerreiro

**Comment by pac-guerreiro** [comment]
Hi! I’m Pedro Guerreiro from Callstack - expert contributor group. I’d like to work on this task!

**Comment by pac-guerreiro** [comment]
I just opened a draft PR with the fix -> https://github.com/Expensify/App/pull/53095

**Comment by pac-guerreiro** [comment]
Today I added test steps and filled my checklist. I need to add screenshots / screen recordings tomorrow.

**Comment by pac-guerreiro** [comment]
Just added the missing screen recordings. The PR is now ready for review 😄 

This next week I'll be off, but someone from my team will take care of any feedback on this PR 😄

**Comment by JKobrynski** [comment]
Hi, I'm Julian from Callstack and I'm going to work on this issue in Pedro's absence.

**Comment by puneetlath** [comment]
@DylanDylann is this a regression or does this require payment?

**Comment by DylanDylann** [comment]
This is so minor that we missed it in the previous PR, let's close this issue
