### ISSUE TITLE
[HOLD for payment 2024-12-16] Search - No sound when paying expense in Search

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#53009]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.66-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):** applausetester+29302390@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace chat.
3. Submit an expense to the workspace.
4. Click dropdown button on the expense preview.
5. Select Pay elsewhere (do not pay it).
6. Go to Search.
7. Click Pay button.

## Expected Result:
There will be sound when paying expense in Search.

## Actual Result:
There is no sound when paying expense in Search.

## Workaround:
Unknown

## Platforms:

- [x] Android: Standalone
- [x] Android: HybridApp
- [x] Android: mWeb Chrome
- [x] iOS: Standalone
- [x] iOS: HybridApp
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/bcab246a-46d3-4a7a-b0a0-147a9b323320

  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @bfitzexpensify</details>

**Comment by luacmartins** [comment]
Yea, I'll look into this thank!

**Comment by luacmartins** [comment]
Working on it this week

**Comment by bfitzexpensify** [comment]
Payment summary:

@jjcoffee owed $250 via NewDot manual request

**Comment by garrettmknight** [comment]
$250 approved for @jjcoffee
