### ISSUE TITLE
QAB - QAB is displayed empty on second device when leaving group after submitting expense

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#53005]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.66-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** ibellicotest+36@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Open the staging.new.expensify.com website
2. Open any group chat and tap on the "+" button
3. Select "Split Expense" and complete the expense creation flow
4. Tap on group header and select "Leave"
5. Log in to the same account on a different device or environment. (Android App)
6. Tap on the FAB
7. Verify that the last action is still displayed and a message about the group chat not existing anymore is displayed while completing creation flow

## Expected Result:
QAB on second device, should still display the last action after leaving group, and a message about submitting expense to a different chat should be displayed when starting the expense creation flow

## Actual Result:
QAB in Android Hybrid app shows only avatars and no text after the group used for last action is left in mWeb session

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/37fbccc5-356c-4d35-8d44-9927c24b85de

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by joekaufmanexpensify** [comment]
Reproduced. However, this is a super niche flow. I am not convinced it is realistic that someone will split an expense in a group chat and then immediately remove the other members and leave it themselves. Further, even if they do that, the flow still works exactly as expected (besides the blank QAB). And split isn't a priority right now. 

I think we should close this and revisit if any real customers ever actually experience this. Doing that for now, but LMK if anyone disagrees!
