### ISSUE TITLE
Room - `Who can post` displays `All members` after setting it to Admins 

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#53002]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.66-0
**Reproducible in staging?:** Y
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5257611
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Log in to NewDot with an account that owns an existing Workspace
2. Click on FAB/ Start Chat/ #Room.
3. Enter room name and select a workspace.
4. Set "Who can post" setting to "admins only"
5. Create a room.
6. Click on the header of created room chat/ Settings.
7. Verify that Who can post setting is set to "Admins only".

## Expected Result:
`Who can post` setting is set to `Admins only` in the room details after selecting this option during room creation process.

## Actual Result:
`Who can post` setting is set to `All members` in the room details after selecting "Admins only" during room creation process.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [x] iOS: Standalone
- [x] iOS: HybridApp
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/909c66c3-5040-4f8b-8be8-16238f5fcb0e

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by rojiphil** [comment]
This is a BE issue as `AddWorkspaceRoom` API request returns response for `writeCapability` as `all` even when it is requested with `admins`.

![Screenshot 2024-11-25 at 5 48 27 PM](https://github.com/user-attachments/assets/80e8920d-fe94-4650-b3f4-322622904399)

**Comment by rlinoz** [comment]
Apparently this is Web-E as mentioned in the code above, still trying to find out what it is.

**Comment by rlinoz** [comment]
Oh actually, apparently in prod we call `OpenReport` right after calling `AddWorkspaceRoom` which returns the correct `writeCapability`

**Comment by rlinoz** [comment]
Im gonna remove the blocker since I think we should fix the `AddWorkspaceRoom` response.

**Comment by rlinoz** [comment]
Deployed to prod
