### ISSUE TITLE
 Thread - Edited link glitches back to original when sending a message

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#53001]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.66-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:**https://expensify.testrail.io/index.php?/tests/view/5256663
**Email or phone of affected tester (no customers):** negasofonias+10@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to a chat and send Google.com
2. Open thread to the above message and edit the link to test.com ( edit both the link adress and the name i.e (test.com)[test.com]
3. Observe the thread title and parent message are both edited
4. Send a message in the thread and observe the title and parent message glitch and revert back to Google.com for a few seconds

## Expected Result:
Edited link should not glitch and revert to original content

## Actual Result:
Edited link glitches and reverts back to original content for a few seconds

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/1f43e620-0ce1-497b-8198-be827693190b

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by stephanieelliott** [comment]
Wasn't able to repro this, looks to be working now! 

https://github.com/user-attachments/assets/131c2e2e-aba6-4d06-b380-fa44b09f2feb
