### ISSUE TITLE
[$250] Categories - Opening troubleshoot menu with ctrl + D shortcut closes RHP first

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#53014]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.66-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+nl800@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

**Issue found  when executing PR** https://github.com/Expensify/App/pull/52250
## Action Performed:
1. Navigate to staging.new.expensify.com
2. Go to Workspace > Categories > Setetings
3. Open one of the sub categories
4. Press ctrl + D

## Expected Result:
Troubleshoot menu appears without the RHP going back

## Actual Result:
RHP goes back one step before the troubleshoot menu appears

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/27df1b4e-7dd5-44a2-93bb-49037df4dab9

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021861520890396239814</li>
        <li>Upwork Job ID: 1861520890396239814</li>
        <li>Last Price Increase: 2024-11-26</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @rushatgabhane</details>

**Comment by JmillsExpensify** [comment]
Opened up to the community
