### ISSUE TITLE
[Search v1.2] - Hold and Delete button are present when the expense is paid in Search

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#53015]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.66-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+kh0911001@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace chat
3. Submit an expense to the workspace
4. Click dropdown button on the expense preview
5. Select Pay elsewhere (do not pay it)
6. Go to Search
7. Click Pay button
8. Select the expense via checkbox
9. Click dropdown button

## Expected Result:
Hold and Delete button should not be present once the expense is paid

## Actual Result:
Hold and Delete button are present when the expense is paid. The buttons only disappear after refreshing the page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Standalone
- [x] Android: HybridApp
- [x] Android: mWeb Chrome
- [x] iOS: Standalone
- [x] iOS: HybridApp
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/bf6ff86b-3ffe-470b-9b33-5b5918a9b628

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @luacmartins</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @luacmartins</details>

**Comment by luacmartins** [comment]
Working on it this week

**Comment by luacmartins** [comment]
PR in review

**Comment by luacmartins** [comment]
This is all internal, so gonna unassign BZ

**Comment by luacmartins** [comment]
This is done
