### ISSUE TITLE
[HOLD for payment 2024-12-19] [$250] LHN- No GBR shown in LHN after cancelled payment instantly

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#53024]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.66-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** testpayment935+600as@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
Prerequisite
Create a workspace and send an expense

Steps
1. Navigate to https://staging.new.expensify.com/
2. Navigate to the submited expense notice a GBR in LHN
3. Pay with elsewhere the expense and notice no more GBR in LHN
4. Cancel the payment and navigate back to LHN

## Expected Result:
There is a GBR as the expense is not paid anymore

## Actual Result:
No GBR shown in LHN after cancelled payment instantly until you navigate back to the expense again

## Workaround:
Unknown

## Platforms:

- [x] Android: Standalone
- [x] Android: HybridApp
- [x] Android: mWeb Chrome
- [x] iOS: Standalone
- [x] iOS: HybridApp
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/e28837c4-eacc-4922-afe5-cc09e16cfe5c
 
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021861071187794353184</li>
        <li>Upwork Job ID: 1861071187794353184</li>
        <li>Last Price Increase: 2024-12-02</li>
<li>Automatic offers: </li>
<ul>
<li>nkdengineer | Contributor | 105163052</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @lschurr</details>

**Comment by sonialiap** [comment]
Checking if this is a bug https://expensify.slack.com/archives/C06ML6X0W9L/p1732537072380849

**Comment by nkdengineer** [comment]
@francoisl Please take a look at this [comment](https://github.com/Expensify/App/issues/53024#issuecomment-2504225410) when you have a chance.

**Comment by francoisl** [comment]
I agree we should go with the solution that sets/resets all data correctly - going to assign @nkdengineer.

**Comment by sonialiap** [comment]
I'm OOO Dec 16-20, adding a leave buddy

next steps:
- make payment
- regression test already added ✔️

**Comment by lschurr** [comment]
Not overdue. Payment is due on the 19th.

**Comment by lschurr** [comment]
Payment summary:

- Contributor: @nkdengineer $250 paid [via Upwork](https://www.upwork.com/nx/wm/workroom/39141814/overview)
- Reviewer: @parasharrajat $250 - please request via NewDot

**Comment by JmillsExpensify** [comment]
$250 approved for @parasharrajat
