### ISSUE TITLE
Expense - New chat report is not bold in LHN when expense is received from other user

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#53021]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.66-0
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+29302390@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition:
- User A and B have never chatted to each other before
1. Go to staging.new.expensify.com
2. [User A] Go to FAB > Submit expense > Manual
3. [User A] Submit an expense to user B
3. [User B] Check LHN for the expense from user A

## Expected Result:
The chat report from user A should be bold

## Actual Result:
The chat report from user A is not bold when user A submits an expense to user B
If user A sends message to user B, user B will receive bold report in LHN

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/34a9cb27-6649-4efb-887b-a1105680bc05

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by puneetlath** [comment]
@trjExpensify is this an expected result from the IOU project?

**Comment by trjExpensify** [comment]
Yep, likely this auth PR: https://github.com/Expensify/Auth/pull/13130

**Comment by puneetlath** [comment]
Great, going to close it out then.
