### ISSUE TITLE
Search - Pay button does not appear on the expense after the duplicates are sorted

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#53023]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.66-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Email or phone of affected tester (no customers):** applausetester+29302390@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
Precondition:
- Add approvals feature is enabled.
- Admin is the approver.

1. Go to staging.new.expensify.com
2. Go to workspace chat.
3. Submit an expense and pay elsewhere.
4. Submit another expense of the same amount and merchant.
5. Go to Search.
6. Click Approve on the expense.
7. Click Approve on expense RHP.
8. Click Approve all the amount.
9. Close the RHP.

## Expected Result:
Pay button should appear on the expense because the duplicates are sorted and Pay button also appears on the expense RHP.

## Actual Result:
Pay button does not appear on the expense after the duplicates are sorted.
It only appears after the page is refreshed.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

- [x] Android: Standalone
- [x] Android: HybridApp
- [x] Android: mWeb Chrome
- [x] iOS: Standalone
- [x] iOS: HybridApp
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/c08580d8-bf96-42fa-99f0-f4658920b18f

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @luacmartins</details>

**Comment by mountiny** [comment]
this is specific flow and the pay button appears after refreshing or navigating away and back so I dont think this has to be a blocker for the deploy as the user is not blocked from taking the action they want to

**Comment by luacmartins** [comment]
I'll work on this since my PR introduced the feature

**Comment by luacmartins** [comment]
Working on it this week

**Comment by luacmartins** [comment]
This seems to be fixed. Closing.

https://github.com/user-attachments/assets/005173d4-cb8d-490a-aaf5-279180cea77e
