### ISSUE TITLE
[HOLD for payment 2024-12-05] [HOLD for payment 2024-12-03] Thread - App opens not here page when returning to previous page from thread

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#53040]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.66-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Y
**Email or phone of affected tester (no customers):** applausetester+2930233@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
Issue 1:

1. Go to staging.new.expensify.com
2. Go to self DM.
3. Track a manual expense via + > Create expense.
4. Go to transaction thread.
5. Click Description.
6. Enter a description and save it.
7. Right click on the description edit system message > Reply in thread.
8. Click on the blue "Thread" link above the system message.

Issue 2:
1. Go to staging.new.expensify.com
2. Create a public room.
3. Go to the room.
4. Send a message.
5. Right click on the message > Reply in thread.
6. Click on the header subtitle link.

## Expected Result:
App will return to the parent thread.

## Actual Result:
App opens not here page when returning to previous page from thread.

## Workaround:
Unknown

## Platforms:

- [x] Android: Standalone
- [x] Android: HybridApp
- [x] Android: mWeb Chrome
- [x] iOS: Standalone
- [x] iOS: HybridApp
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/1ee0763c-7688-47b9-add1-18cc5b8a2e15

https://github.com/user-attachments/assets/5227d468-8d99-4714-9e15-32d06b1407a7

  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @bfitzexpensify</details>

**Comment by bernhardoj** [comment]
yes

**Comment by mountiny** [comment]
PR CPed

**Comment by mountiny** [comment]
@hoangzinh can you please complete the checklist and then we can close this one, thanks!
