### ISSUE TITLE
Doc follow up for Tooltips: Detail out user journeys and tooltip considerations

### ISSUE THREAD

**Issue by zanyrenney** [Expensify/App#53068]
#### **Tooltips**  

- **Existing Tooltips**:  
  - *Get Started*  
  - *RenameSavedSearch*  
  - *QuickActionButton*  

- **New Tooltips**:  
  - *searchRouterIcon* (under discussion)  
  - *InboxBottomNav*  
  - *workspaceChatLHN*  
  - *globalCreate*  

#### **User Journeys**  

1. **Brand New User: Selects "Get Paid Back"**  
   - User begins their experience with a focus on payments

2. **Brand New User: Selects "Manage My Team"**  
   - User starts their journey centered on team management 

3. **Brand New User: Invited to a Workspace**  
   - User is introduced to the platform via a workspace invitation and starts directly in the workspace chat

4. **Brand New User: Invited via an IOU**  
   - User joins the platform through an IOU invitation and begins in a DM with the inviter

### Next steps

- [ ] Run through each user journey and consider the implications for the ordering of tooltips
- [ ] Compare notes and consider reordering

**Comment by zanyrenney** [comment]
Slack thread: [here](https://expensify.slack.com/archives/C07NMDKEFMH/p1732206283940469?thread_ts=1731354813.312789&cid=C07NMDKEFMH)

[Google sheet](https://docs.google.com/spreadsheets/d/1T-FY0QjeEwU8EeHASrjbKBgBgacn1ggSk5-Q9oIE940/edit?gid=0#gid=0)

https://docs.google.com/document/d/1m8e1ASwG70t651qSO6OfsSvW18RFrcWkO897iUllDLs/edit?tab=t.0

**Comment by danielrvidal** [comment]
I think we're good here so closing for now.
