### ISSUE TITLE
[$250] Dedupe multiple LogOut requests

### ISSUE THREAD

**Issue by rinej** [Expensify/App#53070]
### Problem
We are seeing some scenarios where multiple LogOut requests are serialized in a row. When multiple such requests are sent, it's redundant, as only one is relevant. It slows down the app, and contributes to server traffic.

### Solution
Dedupe multiple LogOut requests

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021862137674835272041</li>
        <li>Upwork Job ID: 1862137674835272041</li>
        <li>Last Price Increase: 2024-11-28</li>
<li>Automatic offers: </li>
<ul>
<li>rojiphil | Contributor | 105110958</li>
</ul></li>
    </ul>
</details>

**Comment by rinej** [comment]
PR -> https://github.com/Expensify/App/pull/53143

**Comment by rojiphil** [comment]
@mountiny Please assign me to the issue as well. Thanks.

**Comment by mountiny** [comment]
$250 to @rojiphil

**Comment by rojiphil** [comment]
@zanyrenney I have accepted the offer. Thanks.

**Comment by zanyrenney** [comment]
**payment summary**

paid @rojiphil $250 via Upwork.

**Comment by zanyrenney** [comment]
PR is merged so payment complete and now closing!
