### ISSUE TITLE
[HOLD for payment 2024-12-17] Display the Welcome Modal for migrated users as soon as they sign in to New Expensify

### ISSUE THREAD

**Issue by ishpaul777** [Expensify/App#53085]
# Part of the Migrate Existing Users to NewDot project
Main issue: https://github.com/Expensify/Expensify/issues/437980
Doc section: https://docs.google.com/document/d/1m8e1ASwG70t651qSO6OfsSvW18RFrcWkO897iUllDLs/edit?tab=t.0#heading=h.1996ydl0cxy4
Project:

# Feature Description

Display the Welcome modal for migrated users as soon as they sign in to New Expensify
| Web | Mobile |
|--------|--------|
| ![Welcome modal desktop](https://github.com/user-attachments/assets/66a34f63-24a9-4117-9603-6751a76598e1) | ![welcome modal mobile](https://github.com/user-attachments/assets/d0d9e96b-f314-4f8b-8bbb-4416a50abef9) | 

Notes for completiness: 

- Welcome Modal that appears for migrated users on the new Expensify. This modal will be over any Search/report/account settings page depending on which they land.
- The modal would read “Travel and expense at the speed of chat!”
- Subheading: “New Expensify has the same great automation, but now with amazing collaboration:” With the following lines and associated icons
- “Chat directly on any expense, report, or workspace”
- “Scan receipts and get paid back”
- “Do everything from your phone or browser”
- With a confirmation button titled “Let’s go!”
- Upon clicking “Let’s go!” the modal disappears
- The user should not be able to click on any of the background UI whilst the modal is shown.

Follow implementation from https://docs.google.com/document/d/1m8e1ASwG70t651qSO6OfsSvW18RFrcWkO897iUllDLs/edit?tab=t.0#heading=h.1996ydl0cxy4

**Comment by dannymcclain** [comment]
@Expensify/design when you all are back online, do you know if we have another version of the globe animation (and if so where) or if we just have the one?

**Comment by dubielzyk-expensify** [comment]
Pretty sure that's the only one we have as it's the same as the one we use for Workspaces empty space. Happy to use that one 👍

**Comment by dubielzyk-expensify** [comment]
The modal screenshotted above should be dismissible. When we talk about non-dismissible modals it's only the first sign up onboarding modals. 

So for the workspace creation modal we should allow it to be dismissed.

**Comment by shawnborton** [comment]
I think we just have one version of the rotating planet/workspace items. 

Small thing though - should we make the image area of the modal go full bleed to the edges? I guess we have both styles across the app, so just curious when we should use one vs the other. For example, this is the full bleed style I was thinking of:
![image](https://github.com/user-attachments/assets/ce124f18-8e31-4312-90a3-d0c27a5d9d49)

**Comment by shawnborton** [comment]
> Our current Generic modal component does not provide any abitlitly to not close when clicking on backdrop, before implementing a hotfix i want to confirm if this is strict requirement?

I don't feel too strongly here, personally I would be fine allowing the user to escape/exit the modal by clicking on the background but I can see where we might want to strictly force the user to read the modal and confirm via the button.

**Comment by dannymcclain** [comment]
>should we make the image area of the modal go full bleed to the edges? I guess we have both styles across the app, so just curious when we should use one vs the other

I'm fine with either—I think they both look good. Maybe we can pick one and standardize? Which do you prefer?

>personally I would be fine allowing the user to escape/exit the modal by clicking on the background

I agree, and would also be fine letting the user close via the background. I think the only time we should not allow that behavior is if we really need some input from the user in the modal (like the first sign up modal Jon mentioned).

**Comment by shawnborton** [comment]
I don't feel super strongly really... The full-bleed looks super clean on desktop, though I can see where the borders are nice on mobile as the bottom-docked modal. Let's see what @dubielzyk-expensify thinks?

**Comment by dubielzyk-expensify** [comment]
> I don't feel super strongly really... The full-bleed looks super clean on desktop, though I can see where the borders are nice on mobile as the bottom-docked modal. Let's see what @dubielzyk-expensify thinks?

Happy to go full-bleed. Nice to change things up a bit too :)

**Comment by shawnborton** [comment]
Sweet, let's do it then! 🩸

**Comment by dannymcclain** [comment]
🩸🩸🩸

**Comment by Christinadobrzyn** [comment]
@rayane-djouah @ishpaul777 do we need a regression test? 

Are you both paid through Upwork? If yes, can you accept the above offers?

**Comment by Christinadobrzyn** [comment]
Thanks @ishpaul777 and @rayane-djouah 

@ishpaul777 I didn't pay you in Upwork as it sounds like you'll be paid later for this job - let me know if that's not the case
@rayane-djouah I paid you in Upwork. 

Going to close this out as complete!
