### ISSUE TITLE
All the pinned messages are not displayed in chat search filters

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#53090]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.66-3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @quinthar 
**Slack conversation** (hyperlinked to channel name): [ts_external_expensify_convert](https://expensify.slack.com/archives/C07HPDRELLD/p1732560376654349?thread_ts=1732493955.531249&cid=C07HPDRELLD)

## Action Performed:
1. Pin the messages from social chat
2. Click Search from LHN and choose chats
3. Click on sort by option to  `pinned `
## Expected Result:
All the pinned chats are displayed
## Actual Result:
Only one chat is displayed 
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details>

![image (3)](https://github.com/user-attachments/assets/fdf20214-c537-40fd-ab85-f06a88621136)

![Snip - (57) New Expensify - Google Chrome](https://github.com/user-attachments/assets/c3160b27-6e16-4f05-a8f5-bca141bf4867)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @luacmartins</details>

**Comment by luacmartins** [comment]
Working on it this week

**Comment by strepanier03** [comment]
Yup, able to repro this no problem.

**Comment by strepanier03** [comment]
@luacmartins - before I apply the external label, is this something you're working on, is that why you were assigned?

**Comment by strepanier03** [comment]
Got it, thanks so much @luacmartins.

**Comment by strepanier03** [comment]
Feel free to toss this back to my ownership when it's time.

**Comment by luacmartins** [comment]
Looking at it today

**Comment by luacmartins** [comment]
I can't reproduce this locally, but I can in staging. It seems to only happen when results from `social` are present and it returns only 1 result. I looked at [logs](https://www.expensify.com/_devportal/tools/logSearch/#sort=asc&size=10000&query=request_id%3A%228f0103550bbb843b-YVR%22%20AND%20timestamp%3A%5B2024-12-10T00%3A00%20TO%202024-12-11T23%3A59%5D) for one of my requests and everything looks normal. One interesting thing is that we have `hasMoreResults = true` which means the query is returning 51 results, so my current theory is that we're truncating the results when building the response.

One side-effect of this bug is that because we only return 1 result and `hasMoreResults = true` we end up in an infinite loop in App, because we reach the "end" of the scrollable content and call Search again with a new offset.

**Comment by luacmartins** [comment]
[This PR](https://github.com/Expensify/Auth/pull/13152) touched the chat logic and was deployed just 5 days before this issue was reported. Looking into it now

**Comment by luacmartins** [comment]
Not sure what's going on still. I cloned the messages from `social` to my local dev environment to try to rule out any data specific issues, but it works locally.

**Comment by luacmartins** [comment]
Ok, logs went live and we're indeed getting 50 results, but they all seem to be the same 🤔 Gonna ask for a CQ, so I can confirm where the error is.

**Comment by luacmartins** [comment]
[Requested a CQ](https://github.com/Expensify/Expensify/issues/453287) to confirm the above

**Comment by luacmartins** [comment]
Confirmed that the query is returning the same data over and over. Gonna work on a fix for it.

**Comment by luacmartins** [comment]
We identified the issue. I'll work on a fix for the query.

**Comment by luacmartins** [comment]
PR in review

**Comment by luacmartins** [comment]
This is fixed
