### ISSUE TITLE
App crashes when deeplinking to any room as anonymous user

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#53099]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
Bug found when validating the CP https://github.com/Expensify/App/pull/53069
**Version Number:** 9.0.66-0
**Reproducible in staging?:**  Yes
**Reproducible in production?:** In production clicking on the deeplink opens in mweb
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** No
**If this was caught during regression testing, add the test name, ID and link from TestRail:** n/a
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation** (hyperlinked to channel name):

## Action Performed:
1. Open Hybrid App and log out if logged in
2. Navigate to any room via deep link, eg https://staging.new.expensify.com/r/7522723033868280
## Expected Result:
Room should open in Hybrid app

## Actual Result:
App crashes when deeplinking to any room as anon user

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [x] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [x] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>
[Bug6676319_1732575208137!log.txt](https://github.com/user-attachments/files/17909986/Bug6676319_1732575208137.log.txt)

https://github.com/user-attachments/assets/7e4b833f-f65c-4de0-9719-d08db208395f

  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mountiny** [comment]
In this [slack thread](https://expensify.slack.com/archives/C9YU7BX5M/p1732634473937209) we confirmed the latest CP fixed this issue

**Comment by joekaufmanexpensify** [comment]
TY!
