### ISSUE TITLE
Hybrid - Android - Chat - Compose box does not move above keyboard

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#53119]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v.9. 0. 66-7
**Reproducible in staging?:** N
**Reproducible in production?:** N
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Y
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Launch Hybrid App
2. Open any chat
3. Tap on compose box
## Expected Result:
Compose box should be above keyboard.

## Actual Result:
Compose box does not move above keyboard, it is hidden.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [x] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/20716345-4416-4a46-9f78-53293a269ad1

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mountiny** [comment]
In this [slack thread](https://expensify.slack.com/archives/C9YU7BX5M/p1732634473937209) we confirmed the latest CP fixed this issue
