### ISSUE TITLE
[HOLD for payment 2024-12-07] [$250] [QBO] Prevent making an unnecessary API call if the value hasn't changed

### ISSUE THREAD

**Issue by lakchote** [Expensify/App#53114]
**Version Number:** `v9.0.66-7`
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N
**Email or phone of affected tester (no customers):** lucien+xero@expensifail.com
**Logs:** NA
**Expensify/Expensify Issue URL:** NA
**Issue reported by:** @lakchote 
**Slack conversation** (hyperlinked to channel name): NA

## Action Performed:

Prerequisite: having the browser's console open

1. Connect QBO to a Workspace
2. Go to `Advanced`
3. Click on `QuickBooks invoice collections account`
4. Select the same value already selected

## Expected Result:
An API call isn't made if the value hasn't changed

## Actual Result:
An API call is made even though the value hasn't changed

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?
Yes

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Standalone
- [x] Android: HybridApp
- [x] Android: mWeb Chrome
- [x] iOS: Standalone
- [x] iOS: HybridApp
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Video</summary>

https://github.com/user-attachments/assets/3ec9e928-125c-492b-804a-6f43319d27a9
  
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @twisterdotcom</details>

**Comment by twisterdotcom** [comment]
Do we need a C+ for review here?

**Comment by twisterdotcom** [comment]
Payment Summary:

- @paultsimura requires payment (Needs manual offer from BZ)
