### ISSUE TITLE
Whitelist a sub-group of Add_Comment Actions so they are visible in New Expensify Supportal

### ISSUE THREAD

**Issue by VictoriaExpensify** [Expensify/App#53113]
**Background:**
We recently implemented some changes to allow all LHN Chats to be shown in New Expensify Supportal, but messages would be redacted to ensure the customers privacy. ([GH Issue](https://github.com/Expensify/App/issues/51221))

To start, we decided that any `Add_Comment` actions would be redacted ([Slack discussion](https://expensify.slack.com/archives/C07NZ8B1VTQ/p1731007618526259?thread_ts=1730941943.486409&cid=C07NZ8B1VTQ))

**Problem:**
By redacting all `Add_Comment` actions, there are certain chats that we do not have visibility of that are needed for troubleshooting. This makes it difficult to quickly give customers the support they need when reaching out to a Guide or via Concierge.

**Solution**
Now that we have redacted **all** `Add_Comment` actions we need to start whitelisting the actions that are valuable for troubleshooting and support.

To start, let's allow the following to be visible in New Supportal:

- Workspace chats
- #admins rooms
- Invoice rooms
- DMs to people with a [expensify.com/teams.expensify.com](http://expensify.com/teams.expensify.com) address
- Any chats where Concierge is a participant
- Threads in any of the report scenarios listed above
 
We may find there are other actions that need to be whitelisted down the track, we will raise new GHs for these if/when that happens.

**Comment by marcaaron** [comment]
Looking at this for a bit today.

**Comment by marcaaron** [comment]
>DMs to people with a [expensify.com/teams.expensify.com](http://expensify.com/teams.expensify.com) address

I am assuming that this doesn't count for internal DMs where all participants have `expensify.com` email addresses. I think we should keep redacting in that case.

**Comment by marcaaron** [comment]
Made some progress on this today. Found some bugs related to chat threads not getting redacted so will fix those while I am in here...

**Comment by VictoriaExpensify** [comment]
> I am assuming that this doesn't count for internal DMs where all participants have expensify.com email addresses. I think we should keep redacting in that case.

Yeah good pick up! Those should definitely be redacted. But if a customer reaches out to their Account Manager (who will have an [expensify.com/teams.expensify.com](http://expensify.com/teams.expensify.com) address), we should be able to see those chats

**Comment by marcaaron** [comment]
Based on [this conversation](https://expensify.slack.com/archives/C07NZ8B1VTQ/p1733151094634389?thread_ts=1732246024.999409&cid=C07NZ8B1VTQ) I updated the description to include that we also want to show chats where Concierge is a participant.

**Comment by marcaaron** [comment]
Yeah, I guess it would. Though, one exception would be an internal expensifier who is chatting with Concierge. I think there's a valid case for that being visible by supportal.

**Comment by marcaaron** [comment]
This is in review.

**Comment by marcaaron** [comment]
This is done now.

**Comment by VictoriaExpensify** [comment]
Amazing! Thanks so much Marc. [Posting supportal update today](https://github.com/Expensify/Expensify/issues/435261)
