### ISSUE TITLE
[$250] Chat - A message between only 1 backtick creates a code block

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#53144]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.66-8
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5175216
**Email or phone of affected tester (no customers):** buiminhanh08062023+1996@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Open testing app
2. Open any conversation
3. Click on compose box
4. Send a message between three backticks "```text```"

## Expected Result:
Because a message between three backticks should create a code block, so that it should create a code block with "text" in this code block

## Actual Result:
It created a code block with "``text``" in this code block. It means only need a pair of backtick to create a code block

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/78feb86d-8c88-455a-b7ac-792e4a5a1dea

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021862475730653768184</li>
        <li>Upwork Job ID: 1862475730653768184</li>
        <li>Last Price Increase: 2024-11-29</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @DylanDylann</details>

**Comment by sonialiap** [comment]
@DylanDylann what do you think of the above proposals?

**Comment by sonialiap** [comment]
Chatted with design and in the react native channel, the consensus was that we do nothing because this is not causing any issues and works with the react native requirements 

> The only strong requirement we have is that the parsing process needs to be reversible – we must be able to tell what the original Markdown input was based on the HTML output.
