### ISSUE TITLE
[$250] Oldest unread message not displayed in Concierge

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#53169]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.67-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @garrettmknight 
**Slack conversation** (hyperlinked to channel name): [ts_external_expensify_convert](https://expensify.slack.com/archives/C07HPDRELLD/p1732561879417629)
 
## Action Performed:

1. Signup for a new user and choose manage my team
2. Choose number of employees and accounting software option
3. Click Continue
Link for session: https://fsty.io/v/ujphfF43

## Expected Result:
Oldest unread message displayed in Concierge
## Actual Result:
Oldest unread message not displayed in Concierge, scroll to the bottom of the setup tasks/message
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [x] iOS: Standalone
- [x] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details>

<img src="https://github.com/user-attachments/assets/d60efc09-b8dd-4826-8493-befa71a9a01b" width="40%" height="40%">

https://github.com/user-attachments/assets/29b61d82-88ed-4a4c-ba67-dd8f6218f25d

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021866434424819479758</li>
        <li>Upwork Job ID: 1866434424819479758</li>
        <li>Last Price Increase: 2024-12-10</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @garrettmknight</details>

**Comment by JmillsExpensify** [comment]
I'm almost certain this is by design. @garrettmknight do you bring this up in Slack?

**Comment by danielrvidal** [comment]
Bringing it up in the weekly update.

**Comment by JmillsExpensify** [comment]
Sounds good. I'm still not sure that this is a real bug.

**Comment by JmillsExpensify** [comment]
@garrettmknight do you mind clarifying what you're trying to get at in this issue?

**Comment by garrettmknight** [comment]
Also, this might be an internal issue, but I wanted to give external a shot before recruiting.

**Comment by brunovjk** [comment]
Please correct me if Im wrong, but, I think this behavior might be intentional, as I worked on a similar issue (#52025) weeks ago.

**Comment by garrettmknight** [comment]
Gonna try to find where this is definitively written down before moving forwad.

**Comment by garrettmknight** [comment]
https://expensify.slack.com/archives/C9YU7BX5M/p1734030390771639

**Comment by brunovjk** [comment]
> https://expensify.slack.com/archives/C9YU7BX5M/p1734030390771639

I don't have access, @garrettmknight  any update for us? Thank you.

**Comment by garrettmknight** [comment]
Still waiting for a response on the TestFlight that has documented this behavior.

**Comment by garrettmknight** [comment]
Confirmed that we're going to go with the opposite of my suggested behavior.
