### ISSUE TITLE
[HOLD for payment 2024-12-09] [$250] [Performance] BottomTabBar improve state using Initializer function

### ISSUE THREAD

**Issue by gedu** [Expensify/App#53162]
### Problem
The BottomTabBar component initializes one of its states using the getChatTabBrickRoad function. This function is being called directly within the useState hook, which means it gets executed on every render, even though it only needs to run during the initial state setup.
Current implementation:
```
const [chatTabBrickRoad, setChatTabBrickRoad] = useState<BrickRoad>(
    getChatTabBrickRoad(activeWorkspaceID, currentReportID, reports, betas, policies, priorityMode, transactionViolations),
);
```
This approach causes unnecessary re-execution of getChatTabBrickRoad on every render, leading to performance overhead.

### Solution
We can pass getChatTabBrickRoad as an initializer function to the useState hook instead. This ensures the function is only executed once during the initial render, improving performance:
Updated implementation:
```
const [chatTabBrickRoad, setChatTabBrickRoad] = useState<BrickRoad>(() =>
    getChatTabBrickRoad(activeWorkspaceID, currentReportID, reports, betas, policies, priorityMode, transactionViolations),
);
```
By making this change, the component avoids unnecessary re-execution of getChatTabBrickRoad on every render. This optimization reduces the render time from approximately ±500ms to just 50-100ms, resulting in a more than 5x performance improvement.

### Before
<img width="1672" alt="bottomTabBar_BEFORE" src="https://github.com/user-attachments/assets/e4b40586-e7c4-44fb-a5b5-f173814e2b6b">

### After
<img width="1275" alt="bottomTabBar_AFTER" src="https://github.com/user-attachments/assets/3a1b02e6-b4b8-4fdf-afb5-6183d53b6bff">

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021862478694382529016</li>
        <li>Upwork Job ID: 1862478694382529016</li>
        <li>Last Price Increase: 2024-11-29</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @trjExpensify</details>

**Comment by gedu** [comment]
@mountiny PR created

**Comment by mountiny** [comment]
$250 to @eVoloshchak

**Comment by trjExpensify** [comment]
Not sure why an offer wasn't sent to @eVoloshchak there. 🤔

**Comment by rezkiy37** [comment]
I've created one more issue where I am going to prevent such problems across the entire project - https://github.com/Expensify/App/issues/53322. Also, I am working on a new Eslint rule - https://github.com/Expensify/eslint-config-expensify/pull/138.

cc @gedu @eVoloshchak @mountiny

**Comment by mountiny** [comment]
Nice thank you!

**Comment by eVoloshchak** [comment]
> Not sure why an offer wasn't sent to @eVoloshchak there. 🤔

@trjExpensify, that's because I request payments via NewDot, all good

**Comment by trjExpensify** [comment]
Ah cool, got it!

**Comment by mountiny** [comment]
@eVoloshchak can you please complete the checklist?

**Comment by trjExpensify** [comment]
Can we get the checklist here, please? Thanks!

**Comment by trjExpensify** [comment]
Sounds good to me, thanks! Confirming payment summary as follows: 

- $250 to @eVoloshchak for the C+ review. 

Go ahead and request!

**Comment by JmillsExpensify** [comment]
$250 approved for @eVoloshchak
