### ISSUE TITLE
Held expense - Pay button disappears after holding one of the expenses

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#53166]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.67-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Y
**Email or phone of affected tester (no customers):** applausetester+283911@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. [User A] Submit two expenses to user B.
3. [User B] Go to chat with user A.
4. [User B] Go to expense report.
5. [User B] Hold one of the expenses.

## Expected Result:
Pay button should not disappear after holding one of the expenses.

## Actual Result:
Pay button disappears after holding one of the expenses.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [x] iOS: Standalone
- [x] iOS: HybridApp
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/6e898d46-72ca-4767-be2a-b421267fc027
  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by RachCHopkins** [comment]
@Beamanator also just picked up on this while testing a different issue. I have just been testing and can replicate.

**Comment by mountiny** [comment]
@hoangzinh @abzokhattab Maybe related to https://github.com/Expensify/App/pull/51133 can you check please?

**Comment by mountiny** [comment]
Discussing in slack, `hold` is technically a violation too, but we should not hide the buttons in this case, so lets exclude it

**Comment by mountiny** [comment]
We reverted the original PR and the PCed PR because the expected results been incorrect https://github.com/Expensify/App/issues/50479 lets handle that back in that issue
