### ISSUE TITLE
[HOLD for payment 2024-12-07] [HOLD for payment 2024-12-05] [$500] Web - Expense - Submit button on confirmation page has extra bottom margin

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#53161]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.67-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Email or phone of affected tester (no customers):** applausetester+232803@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace chat.
3. Go to + > Submit expense > Next.
4. Enter amount > Next.

## Expected Result:
Submit button will not have extra bottom margin (production behavior).

## Actual Result:
Submit button has extra bottom margin.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/44ad6d0f-df5d-44bc-bdb1-fb3c1d32e5e5

  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @twisterdotcom</details>

**Comment by mountiny** [comment]
cc @kirillzyusko

**Comment by mountiny** [comment]
I think the margin was added to make sure the button is correctly added on android native so we need to make sure it looks fine there too

**Comment by mountiny** [comment]
Also noting that this does not have to be a blocker, but lets look into trying to fix this while not breaking the native android

I think we should assign @kirillzyusko to look into this as the PR author

**Comment by chiragsalian** [comment]
> Also noting that this does not have to be a blocker, but lets look into trying to fix this while not breaking the native android
> I think we should assign @kirillzyusko to look into this as the PR author

I agree with both points. 
But can't assign to him just cause he hasn't commented on this issue yet. Hopefully he sees it soon.

**Comment by kirillzyusko** [comment]
Hey, feel free to assign me 👋

**Comment by chiragsalian** [comment]
Done 🙂

**Comment by kirillzyusko** [comment]
> We should remove styles.mb6 in this style

On iOS in this case the button will be very close to the bottom of safe area.

> Or we can revert to use safeAreaPaddingBottomStyle from ScreenWrapper

On Android with 3 button navigation bar the button will be moved to high from nav bar.

So both proposals will introduce issues on different platforms.

**Comment by MariaHCD** [comment]
@kirillzyusko could you confirm whether these two deploy blockers (related to the way buttons appear in Android) are also related to this issue?

- https://github.com/Expensify/App/issues/53190
- https://github.com/Expensify/App/issues/53181

**Comment by kirillzyusko** [comment]
@MariaHCD yes, I think so. Probably all these issues are coming from the fact that `edge-to-edge` mode has been enabled and because of that some screens may have an incorrect padding or the wrong distance between button and keyboard.

**Comment by kirillzyusko** [comment]
Can we assign @chrispader on this?

He is working on this ticket at the moment

**Comment by chrispader** [comment]
commenting for assignment!

**Comment by mountiny** [comment]
<img width="417" alt="image" src="https://github.com/user-attachments/assets/211a7d7a-c76f-4328-9de4-2c7af8699b30">
fixed

**Comment by mountiny** [comment]
$250 to @allroundexperts for their review

No regression test needed as it was a challenging new feature flag for android and these small styling issues are temporary

**Comment by allroundexperts** [comment]
@mountiny I reviewed two PRs (https://github.com/Expensify/App/pull/53223 & https://github.com/Expensify/App/pull/53250) here. Can you please update the [payment summary](https://github.com/Expensify/App/issues/53161#issuecomment-2507397204)? 🙇

**Comment by mountiny** [comment]
Updated

**Comment by twisterdotcom** [comment]
Payment Summary:

- @chrispader **does not** require payment (Contractor)
- @kirillzyusko **does not** require payment (Contractor)
- @allroundexperts paid $500 via NewDot Manual Request

**Comment by JmillsExpensify** [comment]
$500 approved for @allroundexperts
