### ISSUE TITLE
[HOLD for payment 2024-12-07] [HOLD for payment 2024-12-05] Android - Taxes - Save button appears above the keyboard with huge spacing in Name page

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#53181]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.67-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Y
**Email or phone of affected tester (no customers):** applausetester+232803@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Launch the app.
2. Go to workspace settings > Taxes.
3. Tap Add rate.
4. Tap Name.

## Expected Result:
Save button will not appear above the keyboard with huge spacing.

## Actual Result:
Save button appears above the keyboard with huge spacing or overlap with keyboard.
Same happens in Report fields.
Seems issue is repro only with Samsung devices. Tester used  Samsung Galaxy Z Fold4 device

## Workaround:
Unknown

## Platforms:

- [x] Android: Standalone
- [x] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/294e3fef-9f3e-47ca-acb3-c16600dab3ad

https://github.com/user-attachments/assets/9fc9abc6-91e2-461a-a692-53f51de93bdb

  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @isabelastisser</details>

**Comment by kirillzyusko** [comment]
Hello, I'm Kiryl from Margelo expert agency and I'd like to work on that problem (most likely this regression was introduced by my changes in `edge-to-edge` PR).

**Comment by mountiny** [comment]
Fix CPed

**Comment by isabelastisser** [comment]
Not overdue, payment on Dec 7.

**Comment by c3024** [comment]
Payment for this issue was handled [here](https://github.com/Expensify/App/issues/51673) for all edge-to-edge mode PRs. No payment is due here.
