### ISSUE TITLE
Chat - Composer is cut off when trying to edit message after opening it on a search result

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#53191]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:**
**Reproducible in production?:**
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation** (hyperlinked to channel name):

## Action Performed:
1. Open the staging.new.expensify.com website.
2. Open any chat that has messages on it.
3. Tap on the search icon on the top right corner.
4. Tap on the option to search on the current chat.
5. Add a word that will trigger a result on the search.
6. Tap on enter.
7. Open the last message on the search results.
8. Long tap on the message and select "Edit Message"
9. Verify that the edition composer is displayed compleе.

## Expected Result:
Edition composer should be displayed entirely when trying to edit a message accessed via search result.

## Actual Result:
When opening a message on a search result and trying to edit it, the edition composer is displayed cutted off.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [x] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/59c5fdbd-bbc8-49d4-bb2b-cb42a9306df4

 
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by RachCHopkins** [comment]
Goit my hands on Android, working on installing Hybridapp.

**Comment by RachCHopkins** [comment]
I can't replicate this on Android Hybridapp or Safari MacOS. Requesting a retest.

**Comment by RachCHopkins** [comment]
I think this is organically fixed. No one can repro.
