### ISSUE TITLE
Hybrid - Launch - App crashes when closing and reopening app

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#53204]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.67-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N
**Email or phone of affected tester (no customers):** applausetester+232803@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Launch hybrid app.
2. Go to ND (if in OD).
3. Close the app by tapping device back navigation (or swipe to exit, not kill the app).
4. Open the app.

## Expected Result:
App will not crash.

## Actual Result:
App crashes when closing and reopening app.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [x] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/1db520a0-ec94-41ba-8e19-c7fd390e64dc

[Bug6677893_1732705869341!QA.txt](https://github.com/user-attachments/files/17934006/Bug6677893_1732705869341.QA.txt)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by iwiznia** [comment]
Conversation here https://expensify.slack.com/archives/C01GTK53T8Q/p1732709475527329

**Comment by mountiny** [comment]
firebase crash [here](https://console.firebase.google.com/u/0/project/expensify-mobile-app/crashlytics/app/android:org.me.mobiexpensifyg/issues/c4dfef1a824f8786633f17c9497a35b3?time=last-seven-days&types=crash&versions=9.0.67.1%20(509006701)&sessionEventKey=67471ED30074000172721A7D81FE6325_2020396435853711314)

Mariusz is investigating

**Comment by staszekscp** [comment]
👋

**Comment by mountiny** [comment]
I believe the QA confirmed this is resolved. There is nobody to pay and the fix was in hybrid app so I think we can close this one now
