### ISSUE TITLE
[HOLD for payment 2024-12-11] [HOLD App#53192] Expensify Card - Navigation bar overlaps the Next button in Choose a limit type step

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#53217]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.67-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5268041
**Issue reported by:** Applause - Internal Team

## Action Performed:
Preconditions
User logged in with an expensifail account.
User is an admin of a workspace and has enabled Expensify Cards in more features.
Workflows MUST be disabled in the workspace.
User has set a fully verified VBA before.
Steps
1. Add another member to the WS so there's at least 2 members
2. Navigate to the "Expensify Card" page in WS settings
3. Tap on "Issue new card"
4. Select the user you are using
5. Select Virtual Card

## Expected Result:
The Next button in the "Select a Limit Type" step should be displayed above the navigation bar

## Actual Result:
The navigation bar overlaps the Next button in the "Choose a limit type" step

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [x] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/cf12de19-f001-4f5f-a7b1-8e522c4b7a58

![Bug6677640_1732677257890!Next_button (1)](https://github.com/user-attachments/assets/c1c3050b-c6e3-46ae-a9ac-f12fa64b1175)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @muttmuure</details>

**Comment by mountiny** [comment]
Similar to other android issues with the margin now after enabling the edge-to-edge feature cc @chrispader @kirillzyusko

**Comment by kirillzyusko** [comment]
Yes, looks like safe area padding is missing on Android

**Comment by mountiny** [comment]
@kirillzyusko i will put this on hold for the other issue

**Comment by muttmuure** [comment]
@c3024 - $250 C+
