### ISSUE TITLE
[$250] IOS - Lag when swiping on distance rate settings page

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#53210]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.67-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5266802
**Email or phone of affected tester (no customers):** nathanmulugetatesting+2189@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Create a workspace
2. Enable distance rates
3. Go to distance rate editor
4. Go to Add a rate or edit a rate page
5. Swipe from left to right to go back
6. Swipe again and again to compare the swipe behavior (While swiping release your finger from the screen after the first swipe, don't go from edge to edge while holding your finger on the screen)

## Expected Result:
Swipe behavior stays the same throughout the app

## Actual Result:
Swipe behavior on distance rate page has a lag

## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [x] iOS: Standalone
- [x] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/c517bf19-fd75-4bda-964e-06ba3f61b68b
 
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021866174807187903196</li>
        <li>Upwork Job ID: 1866174807187903196</li>
        <li>Last Price Increase: 2024-12-16</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @abdulrahuman5196</details>

**Comment by johncschuster** [comment]
I'm catching up from being OOO for the holiday last week. Will get this slotted in tomorrow.

**Comment by johncschuster** [comment]
I couldn't action this today. I will check it out this weekend.

**Comment by VickyStash** [comment]
Hi, I'm Viktoryia from Callstack - expert contributor group - and I would like to work on this issue.

**Comment by VickyStash** [comment]
**Updates:**

- I was able to reproduce the issue, but in the production build only. It's not reproduced on the simulator and I have some issues with running dev build on the device, which I'm trying to resolve.
- The issue is reproduced on similar screens as well (ex: Workspace Categories, Tags, Taxes). My main guess is that it's all related to **useFocusEffect** hook usage. But I need to be able to test in the dev mode to be sure and find the fix. I'll keep you updated.

**Comment by VickyStash** [comment]
Not overdue, WIP on it!

**Comment by abdulrahuman5196** [comment]
There is no proposal to review yet. Not overdue.

**Comment by VickyStash** [comment]
I've updated the prod app version to the latest, and I'm not able to reproduce it anymore!

https://github.com/user-attachments/assets/ada3d51c-1c21-4c64-8ce7-28f36e7050b5

@IuliiaHerets @abdulrahuman5196 Could you confirm if the issue is still reproducible for you?

**Comment by johncschuster** [comment]
Asking for a retest

**Comment by VickyStash** [comment]
Not overdue, waiting for the issue to be re-tested!

**Comment by abdulrahuman5196** [comment]
> Asking for a retest

Waiting on this

**Comment by IuliiaHerets** [comment]
@abdulrahuman5196 @johncschuster Issue is not reproducible anymore 

https://github.com/user-attachments/assets/52bbb047-68c2-4915-9ecf-04987a474aa0

**Comment by VickyStash** [comment]
kind bump @johncschuster 🙂
