### ISSUE TITLE
[HOLD for payment 2024-12-05] Android - Video - Video controls are too close to the device navigation buttons

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#53215]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.67-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+232803@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
 Device navigation is buttons instead of swipe gestures
1. Launch ND or hybrid app
2. Go to chat
3. Upload a video
4. Play the video in full screen

## Expected Result:
Video controls will not be too close to the device navigation buttons

## Actual Result:
Video controls are too close to the device navigation buttons

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Standalone
- [x] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/5d9b4219-aa9e-4025-a7ae-015cbe12696d

![Bug6678070_1732716809298!Screenshot_20241127_220419](https://github.com/user-attachments/assets/baebe381-78ff-4b50-9a12-525b4f8d5481)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @RachCHopkins</details>

**Comment by lanitochka17** [comment]
Production:

https://github.com/user-attachments/assets/78a7ccb5-0556-4324-b151-d6334a66f1f0

**Comment by mountiny** [comment]
@kirillzyusko @chrispader new one

**Comment by chrispader** [comment]
commenting for assignment!

**Comment by mountiny** [comment]
<img width="451" alt="image" src="https://github.com/user-attachments/assets/0d0c3bed-69d2-43ca-a46a-b135c3f38a6f">

**Comment by mountiny** [comment]
Payment to @allroundexperts handled elsewhere

No regression test needed as it was a challenging new feature flag for android and these small styling issues are temporary
