### ISSUE TITLE
Investigate why the onboarding modal was being re-shown and resulting in errors. 

### ISSUE THREAD

**Issue by trjExpensify** [Expensify/App#53222]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.66-8
**Reproducible in staging?:** N
**Reproducible in production?:** N
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):** See thread. 
**Logs:** See thread, but the CompleteGuidedSetup command logs are [here](https://www.expensify.com/_devportal/tools/logSearch/#query=request_id:(%228e8b465388b3760f-SEA%22)+AND+timestamp:[2024-11-26T15:32:28.809Z+TO+2024-11-26T17:32:28.809Z]&index=logs_expensify-031385). 
**Expensify/Expensify Issue URL:**
**Issue reported by:** @trjExpensify 
**Slack conversation** [#convert thread](https://expensify.slack.com/archives/C07HPDRELLD/p1732713593164209)

## Action Performed:
_Note: This is a bit of a "best guess" situation to try and recreate the conditions we saw._

1. Sign-up on NewDot 
2. Don't complete the onboarding modal, such that `hasCompletedGuidedSetupFlow` remains `false`.
3. Close the browser tab
4. Invite that user to a workspace that has isPolicyExpenseChatEnabled set to `true` via OldDot .
5. Go to expensify.com with that new account and sign-in
6. Click Support > Concierge to be redirected to NewDot
7. Observe the onboarding modal appears 
8. Choose "Manage my team's expenses" > 1-10 > QBO > confirm 
9. Observe the onboarding modal reappears and you start running into errors. 

## Expected Result:
Suggestion: If a user with `hasCompletedGuidedSetupFlow===false` is invited to a workspace, set it to `true`, so we don't show the onboarding modal. 
Bug: User shouldn't be hitting [this 402](https://github.com/Expensify/Auth/blob/07a67192f98f743c778b9f4a6afafee8d1a90890/auth/command/CompleteGuidedSetup.cpp#L124-L128) when trying to complete the onboarding steps: 

```
Throw ExpException - d3f30e8e3ec40a7e653ef74717c257bf ~~ message: '402 Invalid message data' exceptionMessage: 'Auth CompleteGuidedSetup returned an error' exceptionFile: '/git/releases/expensify.com/26cdf1f/lib/Auth.php' exceptionLine: '133' exceptionCode: '402'
```

## Actual Result:
Can't complete the onboarding modal and results in errors on task creation. 

## Workaround:
No, they can't get past the onboarding modal. 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari --- the user was on Windows Chrome (Windows NT 10.0; Win64; x64)
- [ ] MacOS: Desktop

## Screenshots/Videos
[Internal FS](https://app.fullstory.com/ui/o-1WN56P-na1/session/8723809313069277463:8723809313069277463!4450241449460292825)

  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mountiny** [comment]
Have not got around to look into this one yet.

**Comment by mountiny** [comment]
I will add more logs

**Comment by mountiny** [comment]
I will add more logs

**Comment by trjExpensify** [comment]
You've added ~chocolate~ logs, right?

**Comment by mountiny** [comment]
Yep it was deployed but there are no logs in the flow, do we know if this is still reproducible? This was not hit in last 2 days

`402 Invalid message data`

https://www.expensify.com/_devportal/tools/logSearch/#sort=asc&size=10000&query=blob%3A%22402%20Invalid%20message%20data%22%20AND%20timestamp%3A%5B2024-12-06T00%3A00%20TO%202024-12-07T23%3A59%5D

**Comment by mountiny** [comment]
Still nothing so I think we can close this one now https://www.expensify.com/_devportal/tools/logSearch/#sort=asc&size=10000&query=blob%3A%22402%20Invalid%20message%20data%22%20AND%20timestamp%3A%5B2024-12-08T00%3A00%20TO%202024-12-11T23%3A59%5D
