### ISSUE TITLE
[CRITICAL] New sign-ups redirected from OldDot have two workspaces created on completion of the onboarding modal.

### ISSUE THREAD

**Issue by trjExpensify** [Expensify/App#53236]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.66-8
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A 
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @trjExpensify 
**Slack conversation** (hyperlinked to channel name): [#convert thread](https://expensify.slack.com/archives/C07HPDRELLD/p1732758451249279). 

## Action Performed:

1. Go to [expensify.com](http://expensify.com/)
2. Click “Manage my expenses for a small team (1-9)”
3. Enter an email address > click “Get Started”
4. Redirected to NewDot
5. Observe a workspace has been created.
6. Complete the accounting step to close the onboarding modal
7. Observe another workspace is created.

## Expected Result:
Only one workspace should be created in the onboarding flow. 

## Actual Result:
A second workspace is created on completion of the last step of the onboarding flow.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/255aa9e2-8c0f-421d-91be-be7ee9eb5d02

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @rayane-djouah</details>

**Comment by trjExpensify** [comment]
https://expensify.slack.com/archives/C02NK2DQWUX/p1732761149927579 - asking the C+ team for eyes on the problem here as this is pretty bad in the onboarding journey.

**Comment by trjExpensify** [comment]
Possible leads: 

- https://github.com/Expensify/App/issues/52894
- https://github.com/Expensify/App/issues/50758
- https://github.com/Expensify/App/issues/51750

In fact, @FitseTLT for #52894. [One PR](https://github.com/Expensify/App/pull/52899) is merged, then there's [another PR](https://github.com/Expensify/App/pull/53093)  with exactly the same title that's not merged. What's going on there, and is that going to fix this? CC: @mountiny

**Comment by mountiny** [comment]
@FitseTLT original solution did not work on desktop and one other platform so thats why there is one more fix

**Comment by trjExpensify** [comment]
Cool, would be helpful to name the PRs a bit differently 😅 

That said, this bug above is on web production. I don't need to refresh or close/reopen etc. Is that PR going to fix it?

**Comment by mountiny** [comment]
I am not sure, @FitseTLT @rayane-djouah Are you able to reproduce based on the instructions from the OP?

**Comment by FitseTLT** [comment]
yeah this will solved by the recent [PR](https://github.com/Expensify/App/pull/53093) @mountiny Let's just hold this for it. And also @mountiny bump for your review on that PR. Thx

**Comment by trjExpensify** [comment]
I think we need to CP that to staging to test and hopefully go with today's app deploy to production. This is borderline a fire in my mind, creating two workspaces for every sign-up is rough.

**Comment by trjExpensify** [comment]
Linking for posterity: https://github.com/Expensify/App/pull/53093

We can probably close this now.
