### ISSUE TITLE
[HOLD for payment 2024-12-09] [HOLD for payment 2024-12-07] Track expense - App opens not here page from Learn more link in upgrade modal

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#53247]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.68-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N/A - new feature, doesn't exist in prod
**Email or phone of affected tester (no customers):** applausetester+232803@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Create a new account (no workspace).
3. Go to self DM.
4. Track a manual expense.
5. Click Categorize it.
6. Click Learn more link in the upgrade modal.

## Expected Result:
App will open valid page.

## Actual Result:
App opens not here page from Learn more link in upgrade modal.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
  
https://github.com/user-attachments/assets/796b7684-f353-46b0-93a5-552426b71401

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @trjExpensify</details>

**Comment by mountiny** [comment]
@nkdengineer @Ollyws probably from this https://github.com/Expensify/App/pull/52737

**Comment by trjExpensify** [comment]
Not a blocker, pretty minor. I think we can link them here instead: https://help.expensify.com/articles/new-expensify/billing-and-subscriptions/Plan-types-and-pricing

**Comment by nkdengineer** [comment]
Got it. @mountiny Please assign me here and I will raise a follow-up PR.

**Comment by nkdengineer** [comment]
@trjExpensify Can you also assign @Ollyws here?

**Comment by nkdengineer** [comment]
@Ollyws The PR is ready for review.

**Comment by mjasikowski** [comment]
PR is CP'd, this is no longer a blocker

**Comment by trjExpensify** [comment]
Same as [here](https://github.com/Expensify/App/issues/53309#issuecomment-2527588402), right?

**Comment by trjExpensify** [comment]
Closing this out to consolidate on the OG issue linked.
