### ISSUE TITLE
[HOLD for payment 2024-12-11] [$250] Expense - Tag in A: B style is displayed as A\: B in expense preview

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#53248]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.68-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N/A - new feature, doesn't exist in prod
**Issue was found when executing this PR:** https://github.com/Expensify/App/pull/52758
**Email or phone of affected tester (no customers):** applausetester+232803@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
Precondition:
- Workspace has a tag in A: B format.

1. Go to staging.new.expensify.com
2. Go to workspace chat.
3. Submit an expense with tag in A: B format.
4. Submit another expense if there is no expense.
5. Go to expense report.

## Expected Result:
Tag in A: B style will be displayed as A: B in expense preview.

## Actual Result:
Tag in A: B style is displayed as A\: B in expense preview.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/f1a83d9f-0302-45a2-a1ee-84087a8213d4

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021862164320724693300</li>
        <li>Upwork Job ID: 1862164320724693300</li>
        <li>Last Price Increase: 2024-11-28</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @sonialiap</details>

**Comment by mkzie2** [comment]
@carlosmiceli Please assign me here, and I will raise a follow-up PR.

**Comment by mkzie2** [comment]
@dukenv0307 The [PR](https://github.com/Expensify/App/issues/53248) is ready.

**Comment by mkzie2** [comment]
This is a follow up from my previous PR. So no need payment for me here cc @sonialiap

**Comment by sonialiap** [comment]
Payment summary:
- @dukenv0307 $250 via NewDot - thank you for being so prompt with the checklist!
- @mkzie2 $250 - offer sent in upwork

**Comment by mkzie2** [comment]
@sonialiap Based on this [comment](https://github.com/Expensify/App/issues/53248#issuecomment-2511743749), no need a payment for me here.

**Comment by JmillsExpensify** [comment]
$250 approved for @dukenv0307
