### ISSUE TITLE
Workspace - Not here page is displayed when opening row to workspace chat

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#53252]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.68-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N/A - new feature, doesn't exist in prod
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):** htad26+jhgjty@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Log in to both new dot and old dot with the same account in different tabs
2. Create a new control workspace
3. Navigate back to the tab where you are logged in new dot
4. Go to workspace list > Click on the control workspace you created
5. Here notice that the fall back avatar for workspace is displayed with the default name "Workspace" in the row "Submit expenses using your workspace chat below"
6. Click on the row "Submit expenses using your workspace chat below"

## Expected Result:
Default workspace with a fall back avatar shouldn't be displayed and it shouldn't navigate to "Hmm not here" page

## Actual Result:
Default workspace with a fall back avatar is displayed and "Hmm not here" page is displayed when navigating to it

## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/8eb3c99b-55f7-4832-9b18-9e6bea91e579
  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by garrettmknight** [comment]
Discussing in thread - tl;dr: We didn't add a check for isPolicyExpenseChatEnabled before showing the workspace chat option.

**Comment by garrettmknight** [comment]
This is the PR that did it: https://github.com/Expensify/App/pull/52449

**Comment by garrettmknight** [comment]
@nkdengineer can you get a PR up to check for isPolicyExpenseChatEnabled on the workspace before showing the WS chat row in the Workspace?

**Comment by nkdengineer** [comment]
Will raise the PR tomorrow morning.

**Comment by s77rt** [comment]
@rlinoz or @garrettmknight Please close this one. Bug is fixed and no payment is due (regression)
