### ISSUE TITLE
Workspace - The button to save the type of plan doesn't work

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#53254]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.68-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N/A - new feature, doesn't exist in prod
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Login with the new Gmail account in incognito mode.
3. Complete the incorporation process using the option “Something Else”
4. Enter a first name and click on the Continue button.
5. Click on the "FAB" button and click on "New Workspace".
6. Click on the "Plan type" section and select "Control" and click on "Save".
7. Click on the "Upgrade button" and click on the "Got it, Thanks" button.
8. Change the Subscription details to Pay-per-use.
9. Try changing the Plan type from the workspace section to "Collect".

## Expected Result:
The save button should work correctly.

## Actual Result:
The button to save the plan type chosen for the workspace does not work after changing the subscription type.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/18f1d065-d111-4e0f-b75b-67dec44ddebe
  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mountiny** [comment]
@trjExpensify i thought its not possible to downgrade in app now?

**Comment by carlosmiceli** [comment]
Yeah, we should revert this, I asked about the risk of this happening [here](https://github.com/Expensify/App/pull/52117#issuecomment-2504101224) 😅 

cc @jayeshmangwani @DylanDylann can we get a revert PR up quick? This needed to wait for the BE to be ready 🙏

**Comment by jayeshmangwani** [comment]
> Yeah, we should revert this, I asked about the risk of this happening https://github.com/Expensify/App/pull/52117#issuecomment-2504101224 😅

Sorry about this! We should have placed that button behind the beta here 😓.

**Comment by carlosmiceli** [comment]
@jayeshmangwani all good, I also should have checked!

**Comment by DylanDylann** [comment]
> The button to save the type of plan doesn't work 

This is intentional because we haven't implemented the downgrade feature. But we forgot to put this page behind the beta

**Comment by mountiny** [comment]
This was CPed so we can close
