### ISSUE TITLE
[HOLD for payment 2024-12-19] [$250] Workspace - Workspace chat shows default avatar when custom avatar is uploaded offline

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#53257]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.68-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Issue was found when executing this PR ** https://github.com/Expensify/App/pull/53100
**Email or phone of affected tester (no customers):** applausetester+232803@applause.expensifail.com
**Issue reported by:** Applause Internal

## Action Performed:
1. Go to staging.new.expensify.com
2. Go offline.
3. Create a workspace.
4. Go to workspace settings > Profile.
5. Click on the workspace avatar.
6. Upload a photo.
7. Go to workspace chat.

## Expected Result:
The workspace avatar in workspace chat should show the custom avatar.

## Actual Result:
The workspace avatar in workspace chat shows default avatar when custom avatar is uploaded offline.

Workspace switcher shows the custom avatar instead of default avatar for the workspace.

## Workaround:
Unknown

## Platforms:

- [x] Android: Standalone
- [x] Android: HybridApp
- [x] Android: mWeb Chrome
- [x] iOS: Standalone
- [x] iOS: HybridApp
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/2e4fce97-bf55-4db5-8d68-0cc1bfea79bf
  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021864244048539221826</li>
        <li>Upwork Job ID: 1864244048539221826</li>
        <li>Last Price Increase: 2024-12-04</li>
<li>Automatic offers: </li>
<ul>
<li>paultsimura | Reviewer | 105193828</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @JmillsExpensify</details>

**Comment by JmillsExpensify** [comment]
Good polish item for us to handle in the name of offline first, so I'm opening up to the community.

**Comment by MarioExpensify** [comment]
Yep, @bernhardoj's solution sounds great. Thank you @paultsimura, let's move forward!

**Comment by bernhardoj** [comment]
PR is ready

cc: @paultsimura

**Comment by JmillsExpensify** [comment]
Payment summary: 

Contributor: @bernhardoj $250 via New Expensify
Reviewer: @paultsimura $250 via Upwork

@bernhardoj feel free to request now. @paultsimura please complete the BZ checklist and we can get the regression test and Upwork payment handled.

**Comment by bernhardoj** [comment]
Requested in ND.

**Comment by garrettmknight** [comment]
Payment summary:

Contributor: @bernhardoj $250 via New Expensify
Reviewer: @paultsimura $250 via Upwork

**Comment by JmillsExpensify** [comment]
$250 approved for @bernhardoj
