### ISSUE TITLE
Expense - Hmm not found page shows after distance expense being deleted

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#53260]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.66-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+bk122@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Navigate to https://staging.new.expensify.com/
2. Log in with Expensifail account ( Important step)
3. Create distance expense
4. Delete both Expenses

## Expected Result:
Both expense delete without remaining balance shown In the WS with "Hmm it is not here" page
LHN of the WS should not show the deleted balance

## Actual Result:
Hmm not found page shows after duplicate distances being deleted
LHN show the deleted balance

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/fbc09968-9bce-4e99-aca1-19d0f5145b6f

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by VictoriaExpensify** [comment]
> Log in with Expensifail account ( Important step)

So this issue can only be recreated under the expensifail domain? While that isn't ideal for testing, it's a very specific situation and I really don't think we should prioritise a fix for it
