### ISSUE TITLE
[$250] Workspace - The member list is blank when a member leaves the workspace

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#53267]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.68-0
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5273433&group_by=cases:section_id&group_id=229065&group_order=asc
**Issue reported by:** Applause - Internal Team

## Action Performed:
Preconditions
User is an employee of a workspace
1. Go to the workspace list as employee
2. Click 3 dot menu of the workspace where the user is not an admin
3. Verify the Leave option is displayed
4. Click on Leave

## Expected Result:
The user is removed from the workspace and is no longer displayed in the workspace, but all other users are displayed

## Actual Result:
The member list is blank when a member leaves the workspace

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/d07c9d47-b070-4057-b867-90ae8146a952

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021862285124256668480</li>
        <li>Upwork Job ID: 1862285124256668480</li>
        <li>Last Price Increase: 2024-11-28</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @paultsimura</details>

**Comment by huult** [comment]
This is a backend issue because the pusher data returns the wrong value for employeeList, which causes the issue with getUser. So, we need the backend to update the value of employeeList or remove it to resolve this issue.

https://github.com/Expensify/App/blob/e99ede55a720b8bbb749912a01ade6f8ebe0cc77/src/pages/workspace/WorkspaceMembersPage.tsx#L334

- <img width="1506" alt="Screenshot 2024-11-29 at 12 53 15" src="https://github.com/user-attachments/assets/9212cf28-7e67-4e2d-8ec9-40b048af3afe">

**Comment by mountiny** [comment]
I believe PR with a fix is up

**Comment by mountiny** [comment]
Asked for a retest https://expensify.slack.com/archives/C9YU7BX5M/p1733740286188859

**Comment by mountiny** [comment]
Perfect, thanks!
