### ISSUE TITLE
[Search v2.5] - Approve button is shown on expense item but not in dropdown when expense is duplicate

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#53266]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.68-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Email or phone of affected tester (no customers):** applausetester+232803@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
Precondition:
- Workflows are enabled.
- Add approvals are enabled.
- Admin is the approver.

1. Go to staging.new.expensify.com
2. Go to workspace chat.
3. Submit an expense.
4. Approve the expense and pay it.
5. Submit another expense of the same amount and merchant (do not approve it).
6. Go to Search.
7. Select the expense via checkbox.
8. Click on the dropdown.
9. Note that Approve button is present on the expense item but not in the dropdown list.
10. Click on the expense, change the amount so that it is not a duplicate.
11. Close the RHP.
12. Select the expense via checkbox.
13. Click on the dropdown.
14. Note that now Approve button is present in the dropdown list.

## Expected Result:
In Step 9, there should be consistency in displaying Approve button on the expense item and the dropdown list when the expense is a duplicate.

## Actual Result:
In Step 9, it shows Approve button on the expense item but not in the dropdown list when the expense is a duplicate.

## Workaround:
Unknown

## Platforms:

- [x] Android: Standalone
- [x] Android: HybridApp
- [x] Android: mWeb Chrome
- [x] iOS: Standalone
- [x] iOS: HybridApp
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/758f3f5e-d6ba-498f-b731-b7edb4bc8412
  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @luacmartins</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @luacmartins</details>

**Comment by IuliiaHerets** [comment]
Production behaviour 

https://github.com/user-attachments/assets/dbfb1ce2-01e0-4df1-bc1d-1078e4006573

**Comment by mountiny** [comment]
The users can still approve just fine so demoting but let's find the offending pr so the authors can fix it cc @luacmartins

**Comment by luacmartins** [comment]
I can take this one since it's coming from my PR

**Comment by luacmartins** [comment]
This is expected for now until the `Review` action is implemented. I'll close this issue.
