### ISSUE TITLE
[HOLD for payment 2024-12-11] [$250] Android & iOS - Start chat - Add to group button is top-aligned instead of centered

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#53261]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.68-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+232803@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Launch ND or hybrid app
2. Open FAB > Start chat

## Expected Result:
"Add to group" button will be centered on the right (web and mweb behavior)

## Actual Result:
"Add to group" button is top-aligned on the right

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Standalone
- [x] Android: HybridApp
- [x] Android: mWeb Chrome
- [x] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/738cb03d-873b-40e1-98f4-21e1431ab3e3

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021862203018243480384</li>
        <li>Upwork Job ID: 1862203018243480384</li>
        <li>Last Price Increase: 2024-11-28</li>
<li>Automatic offers: </li>
<ul>
<li>neonbhai | Contributor | 105126607</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @zanyrenney</details>

**Comment by zanyrenney** [comment]
adding external

**Comment by zanyrenney** [comment]
cc @Expensify/design

**Comment by zanyrenney** [comment]
hey @fedirjh please can you review the proposal above?

**Comment by dubielzyk-expensify** [comment]
Looks like a bug worth solving. Thanks for highlighting 👍

**Comment by zanyrenney** [comment]
@fedirjh please complete the checklist so i can pay this out. Payout will only be due once the checklist has been posted in here. Thank you!

**Comment by zanyrenney** [comment]
Thanks @fedirjh

**Comment by zanyrenney** [comment]
I have bumped @neonbhai to accept the Upwork job because it is still pending!

**Comment by zanyrenney** [comment]
payment summary is: 

@fedirjh requires payment through NewDot Manual Requests - please request $250
@neonbhai requires payment [automatic offer](https://www.upwork.com/nx/wm/offer/105126607) (Contributor) - please accept Upwork offer

**Comment by zanyrenney** [comment]
Updated the payment summary above, closing.

**Comment by garrettmknight** [comment]
$250 approved for @fedirjh
