### ISSUE TITLE
Submit Expense - Duplicate expense is created when admin pays expense submitted by employee.

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#53279]
**Version Number:** 9.0.68-0
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** biruknew45+3h@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. As an admin, create a workspace and add an employee
3. As an admin, set delay submission to manually and enable approval
4. As an employee, go to the workspace chat and submit an expense
5. As an employee, click on the submit button.
6. As an admin, Approve the expense and pay elsewhere.

## Expected Result:
No duplicate expense created.

## Actual Result:
Duplicate expense is created when the admin approves and pays the expense submitted by the employee.

## Workaround:
Unknown

## Platforms:
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/1679c812-ca0a-4b13-bb74-535079d5e208

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by trjExpensify** [comment]
Very easily reproducible: 
<img width="1511" alt="image" src="https://github.com/user-attachments/assets/af8a7bd8-bfcb-4fce-9dd1-06e8d4977793">

**Comment by trjExpensify** [comment]
I think this is borderline fire territory.

**Comment by trjExpensify** [comment]
Posted in eng-chat [here](https://expensify.slack.com/archives/C03TQ48KC/p1732885449678799) for a volunteer.

**Comment by Beamanator** [comment]
So looks like submitter is: biruknew45+5gg@gmail.com
And approver / admin is: biruknew45+3h@gmail.com

Policy: 2215ABEFFBF9702C
ReportID: 5267969861707025

**Comment by Beamanator** [comment]
Looks like this was caused by https://github.com/Expensify/Auth/pull/13232 - @youssef-lr is making the fix

**Comment by Beamanator** [comment]
Merp didn't mean to unassign everyone 😅  assigning @youssef-lr since he's making the PR to fix

**Comment by youssef-lr** [comment]
This is done.
