### ISSUE TITLE
[$250] Web - Card expense - Not here page displayed when opening created card expense

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#53283]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
 
**Version Number:** 9.0.68.0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Issue was found when executing this PR:** https://github.com/Expensify/App/pull/53058
**Email or phone of affected tester (no customers):** tester+ndcardtests@applausecard.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/ and log in with [tester+ndcardtests@applausecard.expensifail.com](mailto:tester+ndcardtests@applausecard.expensifail.com) account
2. Navigate the workspace chat
3. Create a card expense
4. Return to the tab with open workspace chat
5. Open the report > card expense transaction

## Expected Result:
Card expense details are displayed

## Actual Result:
"Hmm it is not here" is displayed when opening the card expense transaction

## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/9ee8179c-5b12-4981-9ad1-ba0d2ccf59b5

  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021862233294202879815</li>
        <li>Upwork Job ID: 1862233294202879815</li>
        <li>Last Price Increase: 2024-11-28</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @ntdiary</details>

**Comment by IuliiaHerets** [comment]
Production 

https://github.com/user-attachments/assets/d36d6f5b-522b-487a-ac3e-515b3d301c3c

**Comment by marcochavezf** [comment]
Hi @IuliiaHerets, sorry, can you describe step by step how you are creating a card expense from PayPal? Are there some instructions in TR that I can follow to reproduce the bug?

**Comment by IuliiaHerets** [comment]
@marcochavezf Yes, we have [steps](https://expensify.testrail.io/index.php?/tests/view/5273347) in TR 
![image](https://github.com/user-attachments/assets/e3fca552-c4a1-4f68-8799-9ec5614bd9be)

**Comment by marcochavezf** [comment]
Thanks @IuliiaHerets!

**Comment by mountiny** [comment]
I have just tested with a real coffee card transaction with no problem in staging so I am going to demote.
https://github.com/user-attachments/assets/65e1d831-c174-4da9-b510-9ed5315a0ab5

@IuliiaHerets @kavimuru, are you able to reliably reproduce with the tool on staging and not on production?

**Comment by marcochavezf** [comment]
There's already an issue for the PayPal payment which has the same steps from TR https://github.com/Expensify/App/issues/48597, so it's not a blocker and I'm going to close it in favor of that one
