### ISSUE TITLE
[HOLD for payment 2024-12-07] Search - Group chat preview shows "Group" (email for 1:1 DM) instead of latest message

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#53291]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.68-2
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Y
**Email or phone of affected tester (no customers):** applausetester+kh1211006@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Create a group chat.
3. Send a message in the group chat.
4. Open search router.
5. Look for the group chat.

## Expected Result:
Group chat preview will show the latest message.

## Actual Result:
Group chat preview shows "Group" instead of latest message.

For 1:1 DM, it shows the user email instead of the latest message.

## Workaround:
Unknown

## Platforms:

- [x] Android: Standalone
- [x] Android: HybridApp
- [x] Android: mWeb Chrome
- [x] iOS: Standalone
- [x] iOS: HybridApp
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/03808e74-3e75-4bb8-a902-a37bc82da69f

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @jliexpensify</details>

**Comment by IuliiaHerets** [comment]
Production
![image (242)](https://github.com/user-attachments/assets/7ff0eab1-4923-4591-8129-c68469b13eda)

**Comment by aldo-expensify** [comment]
Reproduced in staging, confirmed that in production it doesn't happen

**Comment by aldo-expensify** [comment]
https://github.com/Expensify/App/blob/03639a9a0fc6f7adc77ffbdff10aed9b48e40658/src/libs/OptionsListUtils.ts#L443-L445

```
showChatPreviewLine: false
formattedLastMessageText: 'asdasd'
```

Seems like `showChatPreviewLine` has the wrong value?

**Comment by aldo-expensify** [comment]
I believe this may have been caused by: https://github.com/Expensify/App/pull/52568

**Comment by aldo-expensify** [comment]
@Kicu @SzymczakJ are you around for taking a look at this? 🙏

**Comment by aldo-expensify** [comment]
I'm not sure if the solution could be simply as https://github.com/Expensify/App/pull/53293 or if that would break something

**Comment by aldo-expensify** [comment]
@hannojg / @ahmedGaber93 , since you worked here in something very related https://github.com/Expensify/App/pull/53056, would you happen to know if this change https://github.com/Expensify/App/pull/53293 makes sense to fix this?  🙇

**Comment by aldo-expensify** [comment]
Probably the same root cause as https://github.com/Expensify/App/issues/53289

**Comment by aldo-expensify** [comment]
Made the PR ready for review: https://github.com/Expensify/App/pull/53293

**Comment by jliexpensify** [comment]
No payment or checklist needed here, correct @aldo-expensify?

**Comment by aldo-expensify** [comment]
> No payment or checklist needed here, correct @aldo-expensify?

Correct
