### ISSUE TITLE
[$250] [HOLD for payment 2024-12-09] [HOLD for payment 2024-12-07] Search - Pay button from the dropdown does nothing when trying to pay without bank account

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#53292]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.68-2
**Reproducible in staging?:** Y
**Reproducible in production?:** N/A - new feature, doesn't exist in prod
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Y
**Email or phone of affected tester (no customers):** applausetester+232803@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Create a new workspace (do not set up bank account).
3. Go to workspace chat.
4. Submit an expense.
5. Click on the down caret button on the expense preview in the workspace chat.
6. Select Pay with Expensify.
7. Go to Search.
8. Click Pay on the expense item.
9. Note that it opens expense details RHP.
10. Close the RHP.
11. Select the same expense via checkbox.
12. Click on the dropdown.
13. Click Pay.

## Expected Result:
Expense detalis RHP will open since the expense cannot be paid directly because bank account is not set up.

## Actual Result:
Clicking Pay from the dropdown list does not do anything except that the Pay button loads and reverts to the initial state.

## Workaround:
Unknown

## Platforms:

- [x] Android: Standalone
- [x] Android: HybridApp
- [x] Android: mWeb Chrome
- [x] iOS: Standalone
- [x] iOS: HybridApp
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/2c3067ae-1389-46ca-921c-4a44ec18a44b
  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021866077420608244096</li>
        <li>Upwork Job ID: 1866077420608244096</li>
        <li>Last Price Increase: 2024-12-09</li>
    </ul>
</details>

**Comment by aldo-expensify** [comment]
Seems like the backend is returning an error:

```
{
    "onyxData": [
        {
            "key": "snapshot_243428839",
            "onyxMethod": "merge",
            "value": {
                "data": {
                    "report_8794135360699161": {
                        "hasError": true
                    }
                }
            }
        }
    ],
    "httpCode": 200,
    "jsonCode": 200,
    "authResponseMessage": "200 OK",
    "requestID": "8e9e95da7b892d84-YVR"
}
```

**Comment by aldo-expensify** [comment]
This can be time consuming to test because the `Search` view keeps getting stuck "loading" even if the `Search` request already returned 200:

<img width="1719" alt="image" src="https://github.com/user-attachments/assets/8968e335-62dc-4da3-a83e-cde6ceadc569">

**Comment by aldo-expensify** [comment]
@luacmartins @lakchote I think you may be more familiar with this feature, do you know if the `Pay` button should show in the dropdown when you select Pay in Expensify but you don't have a bank account?

**Comment by aldo-expensify** [comment]
This is a new feature introduced in this Pr: https://github.com/Expensify/App/pull/51913/files

**Comment by lakchote** [comment]
Taking the lead on this one to fix the blocker

**Comment by lakchote** [comment]
> @luacmartins @lakchote I think you may be more familiar with this feature, do you know if the `Pay` button should show in the dropdown when you select Pay in Expensify but you don't have a bank account?
>

Answered in Slack [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1732868949035029?thread_ts=1732831503.406759&cid=C01GTK53T8Q)

**Comment by garrettmknight** [comment]
@shubham1206agra [offer](https://www.upwork.com/nx/wm/offer/105255888) is out to you.

**Comment by garrettmknight** [comment]
Cool, paid and closed.
