### ISSUE TITLE
[HOLD for payment 2024-12-09] [HOLD for payment 2024-12-07] Categorize it -Upgrade success view opens when navigating back from category list/confirm page

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#53309]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.68-2
**Reproducible in staging?:** Y
**Reproducible in production?:** N/A - new feature, doesn't exist in prod
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Y
**Email or phone of affected tester (no customers):** applausetester+232803@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
Precondition:
- Account has no workspace.

1. Go to staging.new.expensify.com
2. Go to self DM.
3. Track a manual expense.
4. Tap Categorize it.
5. Tap Upgrade.
6. Tap Got it, thanks.
7. Tap app back button.
8. Note that it still opens upgrade success view.
9. Tap Got it, thanks.
10. Select a category.
11. Tap app back button on the confirmation page.
12. Note that it still opens upgrade success view.
13. Tap app back button again.
14. Note that now only category list will open.

## Expected Result:
In Step 8 and 12, upgrade success view should be removed from the navigation path once "Got it, thanks" is tapped (similar to what is done here https://github.com/Expensify/App/pull/52091).

## Actual Result:
In Step 8 and 12, upgrade success view opens when navigating back to the previous page.

## Workaround:
Unknown

## Platforms:

- [x] Android: Standalone
- [x] Android: HybridApp
- [x] Android: mWeb Chrome
- [x] iOS: Standalone
- [x] iOS: HybridApp
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
https://github.com/user-attachments/assets/7f7379bc-12c5-491f-940a-ad879db2a5a4
  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @trjExpensify</details>

**Comment by trjExpensify** [comment]
Talking with @nkdengineer about it [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1732877428115959?thread_ts=1732874384.540609&cid=C01GTK53T8Q). I'll take over BZ.

**Comment by trjExpensify** [comment]
Yep, let's dismiss the RHP if they go back, which would be consistent with other flows. For example: 

https://github.com/user-attachments/assets/2b50f780-3f5c-411a-8818-294c294b9b01

**Comment by trjExpensify** [comment]
@nkdengineer want to comment here so we can assign you?

**Comment by nkdengineer** [comment]
@trjExpensify Yes.

**Comment by mountiny** [comment]
PR being CPed

**Comment by trjExpensify** [comment]
This was a fix from the categorize it update PR, so I think we can handle payment there centrally for this, right?

**Comment by trjExpensify** [comment]
Closing this out to consolidate on the OG issue linked.
