### ISSUE TITLE
Remove unnecessary react-native-macos and react-native-windows from package json

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#53303]
### Problem

Some time ago, by mistake we added react-native-macos and react-native-windows to our package-lock.json by bumping clipboard lib which added those platforms as peerDependencies. It was fixes in the newer versions, so just bumping the package removes those libs again. You can see it in package-lock.json.

### Solution

Remove those packages from the package.json and ensure the app builds and works just fine after that

**Comment by mountiny** [comment]
cc @WoLewicki

**Comment by mjasikowski** [comment]
Fix PR merged, app builds fine, clipboard works too, nothing to see here anymore.
