### ISSUE TITLE
[HOLD for payment 2024-12-09] [HOLD for payment 2024-12-07] Categorize it - "Edit categories" button opens Not here page when Categories are disabled

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#53305]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.68-2
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Y
**Email or phone of affected tester (no customers):** applausetester+kh1211007@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
Precondition:
- Account has a workspace.

1. Go to staging.new.expensify.com
2. Go to workspace settings > More features.
3. Disable category.
4. Go to self DM.
5. Track a manual expense.
6. Click Categorize it.
7. Click Edit categories.

## Expected Result:
User will be asked to enable categories or create a new workspace.

## Actual Result:
Not here page opens.

## Workaround:
Unknown

## Platforms:

- [x] Android: Standalone
- [x] Android: HybridApp
- [x] Android: mWeb Chrome
- [x] iOS: Standalone
- [x] iOS: HybridApp
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/7f05f3e4-30bd-4f2d-a75a-4047d4e9867f

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @trjExpensify</details>

**Comment by IuliiaHerets** [comment]
Production 

https://github.com/user-attachments/assets/0581ed5d-fd23-4af5-8bad-8ae4737bacfd

**Comment by trjExpensify** [comment]
Talking with @nkdengineer about it [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1732877428115959?thread_ts=1732874384.540609&cid=C01GTK53T8Q). I'll take over BZ.

**Comment by nkdengineer** [comment]
I'm here.

**Comment by trjExpensify** [comment]
Closing to consolidate on the OG issue.
