### ISSUE TITLE
[$250] Sign in - OpenApp request is sent every login

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#53325]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.68-7
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:**(https://github.com/Expensify/App/issues/50076)
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition: Open the DevTools (3 dots -> More tools -> Developer Tools). Go to Network tab, and throttle to Slow 4G
1. Sign in with an existing account
2. Send some messages (just to add items into the queue)
3. Sign out
4. Do steps 3 and 4 a couple of times

## Expected Result:
Observe that OpenApp request was fired only once in the Network tab

## Actual Result:
OpenApp request is sent each time user signs in

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/7d706641-675a-4c2b-aaef-7e62b400c0ea

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021863414839450757624</li>
        <li>Upwork Job ID: 1863414839450757624</li>
        <li>Last Price Increase: 2024-12-09</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @suneox</details>

**Comment by burczu** [comment]
Hi! I'm Bartek from Callstack - expert contributor group. I’d like to take a look at this task.

**Comment by suneox** [comment]
This issue cannot be reproduced on the latest staging version `v9.0.72-0`. The current network filter [in video](https://github.com/Expensify/App/issues/53325#issue-2705892354) has `Preserve log` enabled, ensuring that previous requests are retained. So I think we can retest without `Preserve log` enabled

**Comment by burczu** [comment]
@suneox Just checked on dev with Preserve log disabled and the issue is still reproducible.

**Comment by suneox** [comment]
> @suneox Just checked on dev with Preserve log disabled and the issue is still reproducible.

@burczu I’ve just verified on the latest main `v9.0.72-1`, and this issue cannot be reproduced. Could you please share a recording of the issue?

https://github.com/user-attachments/assets/8bc9a3c2-a396-4528-95a4-d2e961862c5d

**Comment by burczu** [comment]
Hey @suneox! I'm not sure if understand the issue correctly, but in your video the `OpenApp` request is called every login, which should not happen, based on the description of the issue. Am I confusing something?

**Comment by suneox** [comment]
> Hey @suneox! I'm not sure if understand the issue correctly, but in your video the `OpenApp` request is called every login, which should not happen, based on the description of the issue. Am I confusing something?

API `OpenApp` is included personal data so i think it makes sense to called after sign in. Based on issue #50076 is prevented duplicate request `OpenApp`but the [test step](https://github.com/Expensify/App/issues/50076#issuecomment-2436695678) doesn't match with [checklist](https://github.com/Expensify/App/pull/50258#issuecomment-2406518878). 
And the QC team has enabled the [Preserve Log](https://github.com/Expensify/App/issues/53325#issuecomment-2520626293) option during testing, which I believe is the reason behind this issue.

cc: @lanitochka17

**Comment by muttmuure** [comment]
This is not a bug.
