### ISSUE TITLE
Hybrid Android - Pages do not open smoothly, white background when navigating between pages

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#53338]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.69-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N
**Email or phone of affected tester (no customers):** applausetester+232803@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
Precondition:
- App theme should be Dark.

1. Launch Android hybrid app.
2. Go to Expensify Classic, then switch back to New Expensify (important to reproduce the white background issue when navigating app).
3. Go to Account settings.
3. Open Wallet or Preferences or Security or About.
4. Tap app back button.
5. Go to Home.
6. Open workspace switcher.
7. Select any workspace.

## Expected Result:
- Wallet/Preferences/Security/About will open smoothly.
- When returning from Wallet/Preferences/Security/About page and also switching workspace filter, there will not be white background.

## Actual Result:
- Wallet, Preferences, Security and About do not open smoothly.
- When returning from those pages and switching workspace filter, there is white background. The white background issue appears when navigating throughout the app.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [x] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
 
https://github.com/user-attachments/assets/f8557664-0619-4e66-ba41-5cc7c2f2c579

https://github.com/user-attachments/assets/aef76636-cc61-43eb-85fc-e6c535fc2714
 
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by jnowakow** [comment]
Hello, I'm from SoftwareMansion and I'll work on this one

**Comment by mountiny** [comment]
@jnowakow how is this looking?

**Comment by puneetlath** [comment]
QA confirmed this is fixed via CP.
