### ISSUE TITLE
[$250] Chat - Chat created offline displayed as group for some seconds and messages change places

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#53339]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.69-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5281340&group_by=cases:section_id&group_order=asc&group_id=229067
**Email or phone of affected tester (no customers):** ibellicotest+57@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Open the staging.new.expensify.com website.
2. Turn off internet connection.
3. Tap on the FAB and select "Start Chat"
4. Search for any user you don´t have messages with and start a chat.
5. Send some messages to chat.
6. Turn internet connection on.
7. Verify that chat information loads correctly and sent messages doesn´t change places.

## Expected Result:
Conversation started while offline, should load correctly as 1:1 chat and not as a group and the messages sent, should be displayed in the correct order.

## Actual Result:
Conversation started while offline is displayed as group for some time when recovering internet connection and the messages sent, change order for some time.
Issue happens only with Gmail accounts.

## Workaround:
Unknown

## Platforms:

- [x] Android: Standalone
- [x] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/bcf9e4b6-59c8-4d32-aca7-666337e19ef3
 
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021864060952875013175</li>
        <li>Upwork Job ID: 1864060952875013175</li>
        <li>Last Price Increase: 2024-12-10</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @eh2077</details>

**Comment by jacobkim9881** [comment]
Not reproducible.

**Comment by eh2077** [comment]
Still waiting for proposals

**Comment by CortneyOfstad** [comment]
I just checked and I am not able to recreate anymore either. @eh2077 — when you have a chance, can you see if you can consistently recreate?

**Comment by CortneyOfstad** [comment]
I am still not able to recreate so going to close. If anyone else can recreate, please let me know and we can reopen!
