### ISSUE TITLE
[HOLD for payment 2024-12-11] [HOLD for payment 2024-12-09] Android - Navigation bar is white, FAB and more options menu overlap with navigation bar

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#53337]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.69-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Y
**Email or phone of affected tester (no customers):** applausetester+238092302@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
Precondition:
- Device navigation is buttons and not gestures.

1. Launch ND or hybrid app.
2. Open FAB.
3. Go to Search.
4. Select any expense by long pressing on the expense and choose Select.
5. Tap on the dropdown.

## Expected Result:
Production behavior:
- Navigation bar is green (follows app color)
- FAB and more options menu do not overlap with navigation bar

## Actual Result:
- Navigation bar is white.
- FAB and more options menu overlap with navigation bar

3-dot menu, search modal, emoji picker (when opened from long press menu, then tap add emoji icon) from different app area also overlaps with the navigation bar.

## Workaround:
Unknown

## Platforms:

- [x] Android: Standalone
- [x] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
  
https://github.com/user-attachments/assets/1f6725ef-3350-4a89-a033-22cf929b2b3f

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @slafortune</details>

**Comment by mountiny** [comment]
I think we might be able to demote this one as the overlap should be fixed in this pr https://github.com/Expensify/App/pull/53250 which is in main and this issue was in previous versions but we did not deploy to production hybrid.

The colour of the navigation bar also does not feel like a blocking aspect, with the edge to edge it should take the bg of the screen

cc @kirillzyusko @chrispader @hannojg

**Comment by mountiny** [comment]
The navigation bar is apparently reproducible in standalone android app that was not the case in the previous version i believe. Can you repro in emulator locally? @kirillzyusko

**Comment by kirillzyusko** [comment]
@shubham1206agra PR is ready for review: https://github.com/Expensify/App/pull/53376

**Comment by slafortune** [comment]
@shubham1206agra  - offer sent [here](https://www.upwork.com/nx/wm/offer/105293447)

**Comment by slafortune** [comment]
@kirillzyusko Role Contributor does not require payment
@shubham1206agra Role C+ Paid $250 via Upworks
