### ISSUE TITLE
[HOLD for payment 2024-12-11] [HOLD for payment 2024-12-09] iOS/Android - Track expense & Log in - Background turns blank when educational modal comes up

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#53342]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.69-1 
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Y
**Email or phone of affected tester (no customers):** applausetester+kh1311003@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
Issue 1:

Precondition:
- Use an account that has "Track expense" instead of "Create expense".

1. Launch ND or hybrid app.
2. Open FAB.
3. Open Track expense.

Issue 2:
1. Create a new account on Old Dot.
2. Log in to the same account for the first time on hybrid app.
3. App will auto redirect to ND on hybrid app.

## Expected Result:
Background will not turn blank when educational modal comes up.

## Actual Result:
Background turns blank when educational modal comes up.

## Workaround:
Unknown

## Platforms:

- [x] Android: Standalone
- [x] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [x] iOS: HybridApp
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/9b9e9a32-7d6d-424b-a866-0f926515dffa

https://github.com/user-attachments/assets/86312f87-ee6a-422e-a624-da9349039467

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @abekkala</details>

**Comment by mountiny** [comment]
This one does not seem to be a blocker to me but we should fix it for sure

@kirillzyusko @hannojg @chrispader

**Comment by adamgrzybowski** [comment]
@mountiny I will take a look at this one

**Comment by adamgrzybowski** [comment]
@shubham1206agra You can start. I am currently recording videos and got a little stuck on building android 😄

**Comment by mountiny** [comment]
@shubham1206agra can you please complete the checklist? Thanks!

**Comment by abekkala** [comment]
@shubham1206agra can you please complete the checklist? Thanks!

**Comment by abekkala** [comment]
### PAYMENT SUMMARY FOR DEC 11

- Fix: @adamgrzybowski - no payment needed 
- PR Review: @shubham1206agra [$250] [Offer](https://www.upwork.com/nx/wm/offer/105291004)
payment made once checklist is completed

**Comment by abekkala** [comment]
@shubham1206agra friendly bump here for checklist - once completed I can issue payment

**Comment by abekkala** [comment]
@shubham1206agra payment sent and contract ended - thank you! 🎉
