### ISSUE TITLE
Expense - 92 unknown replies after reacting with emoji to expense and approving it

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#53378]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.69-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** applausetester+232803@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
Precondition:
- Add approvals feature is enabled.
- Admin is the approver.

1. Go to staging.new.expensify.com
2. Go to workspace chat.
3. Click + > Submit expense > Manual.
4. Submit a manual expense.
5. Hover over the expense preview or right click on it.
6. Note that there is no add emoji option.
7. Click on the expense preview and return to main chat.
8. Hover over the expense preview or right click on it.
9. Now that there is add emoji option.
10. Add an emoji reaction.
11. Click Approve.

## Expected Result:
In Step 6, there should be add emoji option after submitting the expense.
In Step 11, there will be no phantom replies after reacting to the expense with an emoji and approving it.

## Actual Result:
In Step 6, there is no add emoji option after submitting the expense. It only appears after the page is refreshed.
In Step 11, there are 92 phantom replies after reacting to the expense with an emoji and approving it.

## Workaround:
Unknown

## Platforms:

- [x] Android: Standalone
- [x] Android: HybridApp
- [x] Android: mWeb Chrome
- [x] iOS: Standalone
- [x] iOS: HybridApp
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/a7f177d9-73e5-4399-b864-25098fd36465
  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by CyberAndrii** [comment]
BE issue

![image](https://github.com/user-attachments/assets/a0fe3a24-a94c-49b7-80bc-4b9b4cd476db)

**Comment by alexpensify** [comment]
Adding to my testing list

**Comment by alexpensify** [comment]
I'll get to this one soon.

**Comment by alexpensify** [comment]
Closing - I'm unable to replicate 

--- 

## Heads up, I will be offline until Wednesday, December 18, 2024, and will not actively watch over this GitHub during that period.

If this GitHub requires an urgent update, please ask for help in the #expensify-open-source Slack Room. If the inquiry can wait, I'll review it when I return online.
