### ISSUE TITLE
IOS Hybrid - Text selection handles get behind the error indicator input

### ISSUE THREAD

**Issue by vincdargento** [Expensify/App#53387]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.69-1
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** No
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5283448
**Email or phone of affected tester (no customers):** nathanmulugetatesting+2251@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Open hybrid app, Sign out if already signed in
2. Tap on Email and type something invalid in the email input field
3. While the input is in the error state hold on a text for the selection handle to show up

## Expected Result:
The selection handle becomes in front of the error state input field

## Actual Result:
The selection handle gets behind the error indicator input field

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [x] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<img src="https://github.com/user-attachments/assets/917ed4e8-557a-46bd-a754-c5ced002c81a" width="40%"> 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by puneetlath** [comment]
Asked if SWM could take a look here: https://expensify.slack.com/archives/C04878MDF34/p1733247340981189

**Comment by puneetlath** [comment]
Closing this as discussed in Slack thread since the sign-in experience on Hybrid is being completely replaced.
