### ISSUE TITLE
[HOLD for DISCUSSION][$250] Add a permanent back arrow in product to take you to the last thing you were looking at

### ISSUE THREAD

**Issue by flaviadefaria** [Expensify/App#53391]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:** New Feature
**Reproducible in production?:** New Feature
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** -
**If this was caught during regression testing, add the test name, ID and link from TestRail:** -
**Email or phone of affected tester (no customers):** -
**Logs:** https://stackoverflow.com/c/expensify/questions/4856 -
**Expensify/Expensify Issue URL:** -
**Issue reported by:** New Feature
**Slack conversation** (hyperlinked to channel name): [#convert](https://expensify.slack.com/archives/C07HPDRELLD/p1732813229831159)

**Background:**  I'm seeing more and more users get stuck on pages that they don't know where to come back from.

**Problem:** When users don't know how to navigate to a page they get frustrated and end up clicking in different places to try to get back to where they wanted.

**Solution:** Add a permanent back button to NewDot (desktop) next to the user's avatar in the chat view. When a user signs in, the arrow would be greyed out. As soon as they move to a different chat, thread, or task then the back button would take them back to the previous page.

This is where the arrow should go:

![image (1)](https://github.com/user-attachments/assets/7c92f62c-d7ca-42e6-b185-ce23a9612233)

This should be the style of the arrow:

![image](https://github.com/user-attachments/assets/9cac9ab9-3862-48fa-b187-78a02e6b0e28)

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021863885057654585820</li>
        <li>Upwork Job ID: 1863885057654585820</li>
        <li>Last Price Increase: 2024-12-03</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @abdulrahuman5196</details>

**Comment by flaviadefaria** [comment]
I updated the description to clarify that we want to add the back button just as we have on mobile but now on desktop.

**Comment by flaviadefaria** [comment]
We're having some additional conversations in Slack regarding the solution so let's put this on hold for now until we have made a decision.

**Comment by slafortune** [comment]
Can you please link the discussion @flaviadefaria ?
