### ISSUE TITLE
[$250] Android Hybrid - Login - White screen when backgrounding app after entering magic code

### ISSUE THREAD

**Issue by vincdargento** [Expensify/App#53397]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.69-2
**Reproducible in staging?:** Yes
**Reproducible in production?:** No
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** No
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** ibellicotest+60@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Open the Expensify app.
2. Tap on "Continue With Email"
3. Enter valid credentials.
4. Tap on "Next" and wait until receiving the magic code.
5. Enter the received magic code and tap on "Log In"
6. While the app is loading, background it.
7. Wait a few seconds and reopen it.
8. Verify that the login process was successful and you land on inbox.

## Expected Result:
The user should be correctly logged in, despite backgrounding the app during the login process.

## Actual Result:
A white screen is displayed when backgrounding the app for a few seconds while loading after entering the received Magic Code. The user has to kill the app and relaunch it to enter the account after this.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [x] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/f491ae87-63dd-4de4-b8d7-888579692049

[log.txt](https://github.com/user-attachments/files/17982788/bug.txt)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021863674659316493760</li>
        <li>Upwork Job ID: 1863674659316493760</li>
        <li>Last Price Increase: 2024-12-02</li>
<li>Automatic offers: </li>
<ul>
<li>ikevin127 | Reviewer | 105172764</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @ikevin127</details>

**Comment by vincdargento** [comment]
@stitesExpensify FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by ikevin127** [comment]
@stitesExpensify This is `Android: HybridApp` therefore should be `Internal` as `External` contributors don't have access to the HybridApp repo.

**Comment by stitesExpensify** [comment]
ah thanks @ikevin127 I wasn't aware that hybrid app issues were specific to that repo and couldn't be caused by the regular /app repo

**Comment by ikevin127** [comment]
Sure, usually when `Android: Standalone` or `Android: mWeb Chrome` are **not checked** in the **Platforms** section and when the issue's title states `Android Hybrid` we assume this is specific to `Android: HybridApp`.

**Comment by mountiny** [comment]
Assigning myself too as its most likely coming from the native-stack PR that I have pushed ahead. SWM will have a look into this tomorrow

**Comment by mateuuszzzzz** [comment]
Hi, I'm going to investigate this issue

**Comment by mateuuszzzzz** [comment]
Update: I haven't found anything that could lead to recent changes in codebase. I'm continuing investigation

**Comment by mateuuszzzzz** [comment]
I confirmed that Android blocks activity start, because app is in background. I'm looking for a fix

**Comment by mountiny** [comment]
Nice, great digging!

**Comment by mateuuszzzzz** [comment]
I managed to find a fix, and I'm preparing a PR so that anyone can verify it. I would also like to test the transition between OD and ND, as well as different scenarios where the app is opened from the background.
