### ISSUE TITLE
[HOLD for payment 2024-12-19] [$250] Split- Deleted workspace is still shown in recents list

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#53392]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.69-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** [applausetester+232803@applause.expensifail.com](mailto:applausetester+232803@applause.expensifail.com)
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition:
- Account has at least two workspaces
1. Go to staging.new.expensify.com
2. Go to workspace chat
3. Split an expense in the workspace chat
4. Delete the workspace
5. Open FAB
6. Click Split expense under Quick action section
7. Enter amount > Next

## Expected Result:
~In Step 9, the selected workspace will not display "Unavailable workspace"~
~In Step 11, "Hidden" will not be shown every time the selected workspace is clicked~

In Step 7, the deleted workspace should not be displayed in the recents list.

## Actual Result:
In Step 7, the deleted workspace is displayed in the recents list.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [x] Android: HybridApp
- [x] Android: mWeb Chrome
- [x] iOS: Standalone
- [ ] iOS: HybridApp
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/9282360a-c6d9-4293-9936-5e001bb4786a

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021864448103150318798</li>
        <li>Upwork Job ID: 1864448103150318798</li>
        <li>Last Price Increase: 2024-12-04</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @sakluger</details>

**Comment by sakluger** [comment]
I think the actual bug here is that the deleted workspace shows up in the recents list. We shouldn't show the deleted workspace in any selectable list for choosing where to submit or who to split with.

All the other weird behavior after selecting the deleted workspace is irrelevant because it shouldn't be there in the first place.

**Comment by narefyev91** [comment]
Hi, I'm Nicolay from Callstack - expert contributor group - and I would like to work on this issue.

**Comment by narefyev91** [comment]
Find a root case - will provide a fix today

**Comment by sakluger** [comment]
Hey @Ollyws, could you please complete the BZ checklist before the payment date tomorrow? Thanks!

**Comment by sakluger** [comment]
Thanks for the regression test steps. I added a step to verify that the deleted workspace did not show up in the list, but otherwise, looks great. 👍

**Comment by garrettmknight** [comment]
$250 approved for @Ollyws

**Comment by sakluger** [comment]
Thanks everyon!
