### ISSUE TITLE
[HOLD for payment 2024-12-17] [$250] Tweak camera flash control to make it more obvious

### ISSUE THREAD

**Issue by dubielzyk-expensify** [Expensify/App#53422]
## Problem

When scanning a receipt it's hard to know when the camera flash is on or off as the icon only changes color. This isn't good for usability or accessibility.

## Solution

Instead of relying on color, let's use two icons to signal whether flash is on or off:

![image](https://github.com/user-attachments/assets/0e16efc3-026a-4259-b1d2-80c47d3338dc)

cc @Expensify/design
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021863898613066197496</li>
        <li>Upwork Job ID: 1863898613066197496</li>
        <li>Last Price Increase: 2024-12-03</li>
<li>Automatic offers: </li>
<ul>
<li>allgandalf | Reviewer | 105189019</li>
<li>twilight2294 | Contributor | 105189020</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @lschurr</details>

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Tweak camera flash control to make it more obvious

### What is the root cause of that problem?

We are using only 1 icon for both cases flash on and off

### What changes do you think we should make in order to solve the problem?


We can replace the icon here with another icon in case `isFlashLightOn` is false

```
  <Icon
        height={32}
        width={32}
        src={isFlashLightOn ? Expensicons.Bolt : <new-icon>}
        fill={theme.iconHovered}
    />
```

### What alternative solutions did you explore? (Optional)

**Comment by saifelance** [comment]
### Proposal

### Please re-state the problem that we are trying to solve in this issue.

Tweak camera flash control to make it more obvious

### What is the root cause of that problem?
When scanning a receipt, it’s difficult to distinguish whether the camera flash is on or off since the current indicator only changes color. This lacks clear usability and accessibility, especially for colorblind users.

Proposed Solution

**1. Icon Differentiation:**

Use distinct icons for the "flash on" and "flash off" states:
Flash On: A lightning bolt with a glow effect or rays around it.
Flash Off: A lightning bolt crossed out or dimmed.

**2. Text Label (Optional but recommended for accessibility):**

Add a small tooltip or label beneath the icon that says "Flash On" or "Flash Off." This ensures clarity for all users, including those with vision impairments.

**3. State Feedback:**

When toggled, show a brief confirmation (e.g., "Flash turned on") using a toast notification or subtle animation.

4. **Accessibility Improvements:**

Ensure that the new icons are paired with appropriate ARIA labels (e.g., aria-label="Flash On").
Use high-contrast colors and shapes for the icons to enhance visibility in different lighting conditions.


```
import React, { useState } from 'react';

// FlashToggle Component
function FlashToggle({ isFlashOn, onToggle }) {
  return (
    <button 
      className="flash-toggle" 
      onClick={onToggle} 
      aria-label={isFlashOn ? "Turn flash off" : "Turn flash on"}
    >
      {isFlashOn ? (
        <i className="icon-flash-on"></i> // Flash on icon
      ) : (
        <i className="icon-flash-off"></i> // Flash off icon
      )}
    </button>
  );
}

// Parent Component Example
function CameraControl() {
  const [isFlashOn, setIsFlashOn] = useState(false);

  const handleFlashToggle = () => {
    setIsFlashOn((prevState) => !prevState);
    // Add additional logic for hardware interaction here if needed
    console.log(`Flash is now ${!isFlashOn ? 'ON' : 'OFF'}`);
  };

  return (
    <div className="camera-control">
      <h2>Camera Control</h2>
      <FlashToggle isFlashOn={isFlashOn} onToggle={handleFlashToggle} />
      {/* Additional camera controls go here */}
    </div>
  );
}

export default CameraControl;
```

**Comment by saifelance** [comment]
To integrate the FlashToggle functionality into your existing mobileCameraView component, you'll need to modify the code to include a state for flash control, manage the toggle logic, and update the UI accordingly.


Updated **mobileCameraView** Code

```
import React, { useState } from 'react';
import { View, ActivityIndicator } from 'react-native';
import { Icon, Text, Button, PressableWithFeedback, Shutter } from 'components'; // Replace with actual imports
import { FlashToggle } from './FlashToggle'; // Adjust path to FlashToggle component
import CONST from 'constants'; // Replace with actual constants
import styles from './styles'; // Adjust path to styles

const mobileCameraView = () => {
    const [isFlashLightOn, setIsFlashLightOn] = useState(false);
    const [isTorchAvailable, setIsTorchAvailable] = useState(true); // Simulating torch availability, adjust accordingly

    const toggleFlashlight = () => {
        setIsFlashLightOn(prevState => !prevState);
        // Add actual flashlight toggle logic here (e.g., using device APIs)
        console.log(`Flashlight toggled: ${!isFlashLightOn ? 'ON' : 'OFF'}`);
    };

    return (
        <>
            <View style={[styles.cameraView]}>
                {PDFThumbnailView}
                {((cameraPermissionState === 'prompt' && !isQueriedPermissionState) || 
                  (cameraPermissionState === 'granted' && isEmptyObject(videoConstraints))) && (
                    <ActivityIndicator
                        size={CONST.ACTIVITY_INDICATOR_SIZE.LARGE}
                        style={[styles.flex1]}
                        color={theme.textSupporting}
                    />
                )}
                {cameraPermissionState !== 'granted' && isQueriedPermissionState && (
                    <View style={[styles.flex1, styles.permissionView, styles.userSelectNone]}>
                        <Icon
                            src={Hand}
                            width={CONST.RECEIPT.HAND_ICON_WIDTH}
                            height={CONST.RECEIPT.HAND_ICON_HEIGHT}
                            additionalStyles={[styles.pb5]}
                        />
                        <Text style={[styles.textReceiptUpload]}>{translate('receipt.takePhoto')}</Text>
                        <Text style={[styles.subTextReceiptUpload]}>{translate('receipt.cameraAccess')}</Text>
                        <Button
                            medium
                            success
                            text={translate('common.continue')}
                            accessibilityLabel={translate('common.continue')}
                            style={[styles.p9, styles.pt5]}
                            onPress={capturePhoto}
                        />
                    </View>
                )}
                {cameraPermissionState === 'granted' && !isEmptyObject(videoConstraints) && (
                    <NavigationAwareCamera
                        onUserMedia={setupCameraPermissionsAndCapabilities}
                        onUserMediaError={() => setCameraPermissionState('denied')}
                        style={{ ...styles.videoContainer, display: cameraPermissionState !== 'granted' ? 'none' : 'block' }}
                        ref={cameraRef}
                        screenshotFormat="image/png"
                        videoConstraints={videoConstraints}
                        forceScreenshotSourceSize
                        cameraTabIndex={tabIndex}
                        audio={false}
                        disablePictureInPicture={false}
                        imageSmoothing={false}
                        mirrored={false}
                        screenshotQuality={0}
                    />
                )}
            </View>

            <View style={[styles.flexRow, styles.justifyContentAround, styles.alignItemsCenter, styles.pv3]}>
                <AttachmentPicker acceptedFileTypes={[...CONST.API_ATTACHMENT_VALIDATIONS.ALLOWED_RECEIPT_EXTENSIONS]}>
                    {({ openPicker }) => (
                        <PressableWithFeedback
                            accessibilityLabel={translate('receipt.chooseFile')}
                            role={CONST.ACCESSIBILITY_ROLE.BUTTON}
                            onPress={() => {
                                openPicker({
                                    onPicked: setReceiptAndNavigate,
                                });
                            }}
                        >
                            <Icon
                                height={32}
                                width={32}
                                src={Expensicons.Gallery}
                                fill={theme.textSupporting}
                            />
                        </PressableWithFeedback>
                    )}
                </AttachmentPicker>
                <PressableWithFeedback
                    role={CONST.ACCESSIBILITY_ROLE.BUTTON}
                    accessibilityLabel={translate('receipt.shutter')}
                    style={[styles.alignItemsCenter]}
                    onPress={capturePhoto}
                >
                    <Shutter
                        width={CONST.RECEIPT.SHUTTER_SIZE}
                        height={CONST.RECEIPT.SHUTTER_SIZE}
                    />
                </PressableWithFeedback>

                {/* FlashToggle Component */}
                <FlashToggle 
                    isFlashOn={isFlashLightOn} 
                    onToggle={toggleFlashlight} 
                />
            </View>
        </>
    );
};

export default mobileCameraView;
```


### Key Changes:
**State Management:**
Added isFlashLightOn state for flash control.
Added a placeholder isTorchAvailable state for torch availability.

**FlashToggle Integration:**
Replaced the existing flashlight toggle UI with the FlashToggle component.
Passed isFlashLightOn and toggleFlashlight to FlashToggle for dynamic behavior.

**Custom Logic:**
Included a placeholder toggleFlashlight function to handle flashlight toggling.

**UI Update:**
FlashToggle renders the appropriate icon and handles toggling state seamlessly.

**Comment by mountiny** [comment]
@dubielzyk-expensify is that icon in the App already. If not, do you have svg of it by any chance?

**Comment by mountiny** [comment]
@allgandalf it flashes when I take the picture, it should not turn on as a torch

**Comment by saifelance** [comment]
> Job added to Upwork: https://www.upwork.com/jobs/~021863898613066197496

invite please Upwork job https://www.upwork.com/freelancers/saifurrehman

**Comment by nkdengineer** [comment]
@allgandalf @mountiny 
1. The implementation is just an example, the color style can be changed easily when asking the design team in PR as I mention in my [proposal](https://github.com/Expensify/App/issues/53422#issuecomment-2513683455) 
2. This bug is in the scan screen and both the native file and the index file have this, so updating the native file is the default behavior

**Comment by nkdengineer** [comment]
> Your proposal was missing details @nkdengineer

@allgandalf What details that I'm missing? I only see the difference between my proposal and @twilight2294's proposal is this proposal mentioned the change in the native file.


> also please mind that we updated the proposal template and same has been posted on [slack](https://expensify.enterprise.slack.com/archives/C01GTK53T8Q/p1733148961659549) as well, so please post proposals in latest format

Thanks, I noted.

**Comment by dubielzyk-expensify** [comment]
Here's the SVG file
[bolt-slash.svg.zip](https://github.com/user-attachments/files/18002225/bolt-slash.svg.zip)

**Comment by saifelance** [comment]
> > invite please Upwork job https://www.upwork.com/freelancers/saifurrehman
> 
> @saifelance welcome 👋 , you are hired to a job once C+ and internal engineer approves your proposal, please go through the contributors guidelines [here](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md) and know more about the process.
> 
> Hope to see you around 😄

Thanks

**Comment by saifelance** [comment]
Great 👍

**Comment by mountiny** [comment]
Yeah I dont think we need, but lets complete the checklist

**Comment by lschurr** [comment]
Payment summary:

- Contributor: @twilight2294 $250 paid via [Upwork](https://www.upwork.com/nx/wm/workroom/39155332/overview)
- Reviewer: @allgandalf $250 paid via [Upwork](https://www.upwork.com/nx/wm/workroom/39167373/overview)
