### ISSUE TITLE
Search - Search dropdown button is green in wide layout and gray in narrow layout

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#53426]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.70-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Y
**Email or phone of affected tester (no customers):** applausetester+kh1311020@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. On web, go to staging.new.expensify.com
2. Go to Search.
3. Select expense via checkbox.
4. Note that the dropdown button is green.
5. Change it to narrow layout (mweb, Android and iOS).
6. Now the dropdown button is gray.

## Expected Result:
There should be consistency in dropdown button color in wide and narrow layout.

## Actual Result:
The dropdown button color is green in wide layout, and gray in narrow layout.

## Workaround:
Unknown

## Platforms:

- [x] Android: Standalone
- [x] Android: HybridApp
- [x] Android: mWeb Chrome
- [x] iOS: Standalone
- [x] iOS: HybridApp
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/b06691e9-92d9-4855-bcea-ad80e36484ad

https://github.com/user-attachments/assets/5ded7fef-a2a5-47b6-8095-eed26d0e0090

  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by IuliiaHerets** [comment]
Production 

https://github.com/user-attachments/assets/a982272c-3b66-4ef7-991f-165beef622c4

**Comment by hungvu193** [comment]
Taking a look 👀

**Comment by hungvu193** [comment]
Hmm yeah, looks like we miss that case:
`SearchSelectedNarrow.tsx`

**Comment by hungvu193** [comment]
@twilight2294  Let's migrate `Button` inside `SearchSelectedNarrow` to use `ButtonWithDropdownMenu`

**Comment by MonilBhavsar** [comment]
Issue is fixed on staging. Thank you all for the help! 🙇
