### ISSUE TITLE
[HOLD for payment 2024-12-12] [HOLD for payment 2024-12-11] iOS Start chat - Next button is partially covered by the keyboard

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#53429]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.70-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Y
**Email or phone of affected tester (no customers):** applausetester+kh1311020@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Launch ND or hybrid app.
2. Open FAB > Start chat.
3. Tap Add to group.
4. Focus on the search field to bring up keyboard if not yet.

## Expected Result:
Next button will not be covered by the keyboard (production behavior).

## Actual Result:
Next button is partially covered by the keyboard.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [x] iOS: Standalone
- [x] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/7cd4c411-8b77-4676-899f-c9cb2bd8c685

  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @isabelastisser</details>

**Comment by hannojg** [comment]
cc @kirillzyusko @chrispader

**Comment by kirillzyusko** [comment]
Hey, I'm Kiryl from Margelo expert agency and I'd like to work on this issue!

**Comment by puneetlath** [comment]
QA confirmed this is fixed after CP.

**Comment by cristipaval** [comment]
> @cristipaval @isabelastisser @kirillzyusko The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed. Please copy/paste the BugZero Checklist from [here](https://raw.githubusercontent.com/Expensify/App/main/contributingGuides/BUGZERO_CHECKLIST.md) into a new comment on this GH and complete it. If you have the K2 extension, you can simply click: HERE

this was a regression.
