### ISSUE TITLE
[HOLD for payment 2024-12-11] Android - Report fields - Save button overlaps with device navigation in name page

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#53423]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.70-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Y
**Issue reported by:** Applause Internal Team

## Action Performed:
Precondition:
- Device navigation is buttons and not gestures.

1. Launch ND or hybrid app.
2. Go to workspace settings > Report fields.
3. Tap Add field.
4. Tap Name.

## Expected Result:
Save button will not overlap with device navigation.

## Actual Result:
Save button overlaps with device navigation.

## Workaround:
Unknown

## Platforms:

- [x] Android: Standalone
- [x] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/73f3260b-f089-4d32-9458-d0656915e7e6

  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @OfstadC</details>

**Comment by hannojg** [comment]
cc @kirillzyusko

**Comment by kirillzyusko** [comment]
Hey, I'm Kiryl from Margelo expert agency and I'd like to work on this issue!

**Comment by isagoico** [comment]
Issue was not reproducible on build 70-9 🎉 Video [here](https://applause.enterprise.slack.com/files/U03337ZGLCA/F08340Y4NMD/2024-12-04_7.51.24___am.mp4)

**Comment by mountiny** [comment]
@OfstadC There will be no payments here

@ZhenjaHorbach can you please complete the checklist? Thanks!
