### ISSUE TITLE
Fix Additional Information Text Margin 

### ISSUE THREAD

**Issue by MitchExpensify** [Expensify/App#5343]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

### Problem

The margin/padding of the Additional Information text is running right up to the screen edge on iOS (likely on Android too)

![image](https://user-images.githubusercontent.com/36425901/133896262-d296c4e3-28f4-47be-9cf3-5f80813bfa66.png)

### Solution

Introduce a margin for this page that prevent text running to the screen edge. cc @Expensify/design for suggestions on the actual placement. 

[Internal Slack Thread](https://expensify.slack.com/archives/C020EPP9B9A/p1631904052069800)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by shawnborton** [comment]
I think it should look like this - thoughts?
![image](https://user-images.githubusercontent.com/2319350/134030653-a9aeb82d-5cfb-44bd-900a-94ad5b9ae4eb.png)

**Comment by luacmartins** [comment]
Look good! Putting up a PR now.

**Comment by MitchExpensify** [comment]
Not on staging

**Comment by MitchExpensify** [comment]
done
