### ISSUE TITLE
Android - Settings-On tapping options in settings page,all options greyed out

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#53446]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** V9. 0.70-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Y
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Launch site in both mweb and Android
2. Tap settings
3. Tap profile and navigate back
4. Tap workspace

## Expected Result:
On tapping options in settings page, behavior must be consistent in mweb and android.

## Actual Result:
On tapping options in settings page, all options are greyed out in android but not in mweb.

## Workaround:
Unknown

## Platforms:

- [x] Android: Standalone
- [x] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/e0e4f3c5-7de3-4f94-a6cc-bf336d1b4840

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by stephanieelliott** [comment]
Hm, this seems to be working correctly? I'm not seeing any obvious bug in the video, but I tested the repro steps on both platforms and they seem to be consistent.
