### ISSUE TITLE
[HOLD for payment 2024-12-20] The central page page is not rendered when resized to narrow and then to wide view again

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#53445]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:**
**Reproducible in production?:**
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @WojtekBoman 
**Slack conversation** (hyperlinked to channel name):

## Action Performed:
Break down in numbered steps

1. go to workspace settings
2. Select the workspace profile page
3. Resize the window to the narrow view
4. Go back to the workspace LHN
5. Resize the view to wide view
6. Notice that the central pane content is blank

## Expected Result:
Describe what you think should've happened

The profile page should be shown there

## Actual Result:
Describe what actually happened

Black page

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

https://github.com/user-attachments/assets/60431dc0-04e1-4ab5-9279-7f9473ea486a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @adelekennedy</details>

**Comment by WojtekBoman** [comment]
Hi! I'd like to work on this issue :)

**Comment by FitseTLT** [comment]
Don't you guys think this is a dupe of https://github.com/Expensify/App/issues/53395

**Comment by mountiny** [comment]
Hmm yeah that is the same, I did not see that issue before.

**Comment by mountiny** [comment]
We have automated test for this and the payment will be handled on this issue https://github.com/Expensify/App/issues/53395

We can close now - This came from the native stack PR
