### ISSUE TITLE
QBO - Tags and report fields toggle are disabled after connecting to QBO

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#53456]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.70-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Email or phone of affected tester (no customers):** applausetester+bm410@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Create workspace and connect to QBO
3. Navigate to More features and see the tags and report fields toggle.

## Expected Result:
The Tags and report fields toggle should be enabled, as they are visible in workspace settings.

## Actual Result:
The Tags and report fields toggle are disabled and locked.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/aa506938-0ff8-4d8d-896a-8e5573694d7e
  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment]
Not reproducible anymore
Build v9.0.70-3

https://github.com/user-attachments/assets/99d0f30c-fcc5-4d10-9149-c75566bfa633
