### ISSUE TITLE
Onboarding - Onboarding tasks arenot moved to admins room in manage teams expenses

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#53450]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.70-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Issue was found when executing this PR:** https://github.com/Expensify/App/issues/51443
**Email or phone of affected tester (no customers):** negasofonias@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Logon to ND with a new account.
2. Click on "Manage my team's expenses" intent on the onboarding flow and complete the onboarding.
3. Observe is onboarding tasks are not shown in admins room

## Expected Result:
Onboarding tasks should be shown in admins room

## Actual Result:
Onboarding tasks are stillshown in conceirege chat

## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/0cee34a2-60b5-4796-80d1-08bc092bb847
  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by jjcoffee** [comment]
This is on purpose. We don't assign guides to emails with `+` in them, so we [decided](https://github.com/Expensify/App/pull/52314#issuecomment-2490563938) it didn't make sense to post the tasks in the `#admins` room in this case.

**Comment by alexpensify** [comment]
Thanks for the heads up @jjcoffee - Closing!
