### ISSUE TITLE
53406 - Onboarding - Selection in employee page is lost when reloading

### ISSUE THREAD

**Issue by mitarachim** [Expensify/App#53502]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.70-6
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:** -
**Email or phone of affected tester (no customers):** dave0123seife@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Login with a new gmail account 
2. On the onboarding page click on "manage my teams expense"
3. Choose any number of employees
4. Reload the page

## Expected Result:
Selected employee number shown

## Actual Result:
Selected employee number is not shown

## Workaround:
Unknown

## Platforms:
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/19dad5fb-bb5c-414c-91de-3359f7e19f52

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by isagoico** [comment]
Reopening as this was created by one of our team leads

**Comment by kadiealexander** [comment]
I don't think this is a bug worth fixing, it's an extreme edge case and isn't unexpected. Closing, please feel free to reopen if you disagree.
