### ISSUE TITLE
The pattern for linking out to a bank does not fully align with the intended design in the documentation, and the stack effect is not being applied 

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#53508]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.71-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @joekaufmanexpensify 
**Slack conversation** (hyperlinked to channel name): [ts_external_expensify_expense](https://expensify.slack.com/archives/C06ML6X0W9L/p1733261900392489)

## Action Performed:

1. Enable company card in workspace
2. Click Add card
3. Choose any bank and click Next

## Expected Result:
The pattern for linking out to a bank aligns with the intended design outlined in the documentation and incorporates the stack effect as specified.

## Actual Result:
The pattern for linking out to a bank does not fully align with the intended design in the documentation, and the stack effect is not being applied as expected.

## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [x] iOS: Standalone
- [x] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details>

<img src="https://github.com/user-attachments/assets/ee59aa96-3e02-4d10-b1dd-0879c79bbb02" width="40%" height="40%">

<img src="https://github.com/user-attachments/assets/ddbfaa74-c967-4cdb-b64f-5cb77ec872b9" width="40%" height="40%">

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by DylanDylann** [comment]
I'd love to take this issue as C+

**Comment by mountiny** [comment]
Making this weekly as I think we still need to discuss how to handle this and ideally we handle this alongside the accounting change

**Comment by joekaufmanexpensify** [comment]
We [decided](https://expensify.slack.com/archives/C06ML6X0W9L/p1733397193476009?thread_ts=1733261900.392489&cid=C06ML6X0W9L) to do nothing here. Closing this for now. Will reopen if we later change our minds!
