### ISSUE TITLE
Direct feed card missing last 4 digits on card list.

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#53512]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:**
**Reproducible in production?:**
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @joekaufmanexpensify 
**Slack conversation** (hyperlinked to channel name): [ts_external_expensify_expense](https://expensify.slack.com/archives/C06ML6X0W9L/p1733262008865949)

## Action Performed:

1. Enable company card in workspace
2. Click Add card and choose Wells Fargo
3. Add different cards by both feeds (Direct and Custom feed)
4. Click back to company cards page
## Expected Result:
Last 4 digits of card displayed for both the feeds
## Actual Result:
Direct feed card missing last 4 digits on card list.

## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [x] iOS: Standalone
- [x] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details>

<img src="https://github.com/user-attachments/assets/14097b64-87c8-4a1a-8f96-3669eeb92431" width="40%" height="40%">

<img src="https://github.com/user-attachments/assets/cd70fa35-0bff-4abb-aa5b-01b28134e6c4" width="40%" height="40%">

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @mountiny</details>

**Comment by DylanDylann** [comment]
Contributor Plus of Company Feed Feature - I'd love to take this issue as C+

**Comment by DylanDylann** [comment]
cc @waterim 

Maybe you be interested in this issue because we already worked on "last 4 digits" problem

**Comment by narefyev91** [comment]
Hi, I'm Nicolay from Callstack - expert contributor group - and I would like to work on this issue.

**Comment by DylanDylann** [comment]
@mountiny is on fixing

**Comment by mountiny** [comment]
This is because there is no hyphen in the name but we expect the hyphen to be there `BILT WORLD ELITE MASTERCARD 2602`

**Comment by mountiny** [comment]
havent got around yet

**Comment by mountiny** [comment]
Will work on it this week

**Comment by mountiny** [comment]
Fixed
