### ISSUE TITLE
Allow deleting transactions toggle doesn't save

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#53516]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:**
**Reproducible in production?:**
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @joekaufmanexpensify 
**Slack conversation** (hyperlinked to channel name): [ts_external_expensify_expense](https://expensify.slack.com/archives/C06ML6X0W9L/p1733262091959049)

## Action Performed:

Prerequisite: User added a company card

1. Click settings for the added card
2. Enable the toggle for 'Allow deleting transactions"
3. Click the back arrow
4. Again click the settings

## Expected Result:
Toggle enabled for Allow deleting transactions
## Actual Result:
Toggle in disabled status
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [x] iOS: Standalone
- [x] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details>

https://github.com/user-attachments/assets/b73cf169-ab89-4604-a6d2-8c3bdf5b157e

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @mountiny</details>

**Comment by narefyev91** [comment]
Hi, I'm Nicolay from Callstack - expert contributor group - and I would like to work on this issue.

**Comment by mountiny** [comment]
@narefyev91 Are you able to reproduce? I think this might be an issue with the toggle purely on native

**Comment by narefyev91** [comment]
> @narefyev91 Are you able to reproduce? I think this might be an issue with the toggle purely on native


https://github.com/user-attachments/assets/76f6545c-9fec-4403-945c-958136540b17

https://github.com/user-attachments/assets/32fc5904-80e2-4b3c-8b5b-89572c7f2beb


Not really able...
But it maybe the problem with API call - if API failed we switch back toggle
Potentially it maybe related - that during testing for some reason API failed.

**Comment by mountiny** [comment]
Interesting, will have to look into the logs

**Comment by narefyev91** [comment]
> Interesting, will have to look into the logs

Or maybe it's only repro in Hybrid app,

**Comment by mountiny** [comment]
Hmm maybe

**Comment by joekaufmanexpensify** [comment]
Reopening as this is[ still not working for direct feeds](https://expensify.slack.com/archives/C06ML6X0W9L/p1733500465382909?thread_ts=1733262091.959049&cid=C06ML6X0W9L)
