### ISSUE TITLE
Assigned direct feed card is wiped after signing out and back in on mobile

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#53517]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:**
**Reproducible in production?:**
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @joekaufmanexpensify 
**Slack conversation** (hyperlinked to channel name): [ts_external_expensify_expense](https://expensify.slack.com/archives/C06ML6X0W9L/p1733262119487119)

## Action Performed:
Prerequisite: User added a company card

1. Assign the card to a member
2. Sign out of the app and sign back in to the app.
3. Click company cards from more features
## Expected Result:
Card assigned is displayed in cards page
## Actual Result:
Assign card page displayed and assigned details are wiped out
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [x] iOS: Standalone
- [x] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details>

<img src="https://github.com/user-attachments/assets/1f6f1d3f-d64b-46a3-8f06-a5939202cd56" width="40%" height="40%">

<img src="https://github.com/user-attachments/assets/689cf3da-d9a6-4765-a2d9-b55e63c071ff" width="40%" height="40%">

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by JmillsExpensify** [comment]
@joekaufmanexpensify did we want to make this external? I'm missing the linked convo that produced this bug report.

**Comment by joekaufmanexpensify** [comment]
Initial discussion is [here](https://expensify.slack.com/archives/C06ML6X0W9L/p1733939604273319?thread_ts=1733262119.487119&cid=C06ML6X0W9L)! It stalled a bit and I am not sure if this can be external as there was discussion of an API issue. I just bumped the thread to get resolution on that.

**Comment by waterim** [comment]
Hey Im Artem and taking this one

**Comment by waterim** [comment]
Just started the investigation on friday, today have more time and looking into this

**Comment by mountiny** [comment]
This PR might help with this https://github.com/Expensify/Web-Expensify/pull/44833

**Comment by mountiny** [comment]
This should be fixed with BE change

**Comment by waterim** [comment]
@mountiny thats will be great as it looks like data is just missing and optimistically serves before logout

**Comment by mountiny** [comment]
This is now fixed
