### ISSUE TITLE
[$250]  Android - Domains - When returning from domains, headers in the app overlap notification bar

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#53523]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.70-6
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Yes, reproducible on both
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** ibellicotest+61@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Open the Expensify app.
2. Tap on "Settings" on the bottom of the screen.
3. Tap on "Domains"
4. Once redirected to OD, tap on the hamburger menu and tap on "Try New Expensify"
5. Once navigated again to ND, verify that the headers in all the sections are correctly displayed, without overlapping the device notification bar.

## Expected Result:
When returning from OD, after navigating to Domains, headers in all sections should remain in the same position, without being overlapped by notifications bar of the device.

## Actual Result:
After navigating to OD, when tapping on "Domains" and returning to ND, header is moved up and is displayed overlapped by the device notifications bar. This is visible in every section of the app, after returning.

## Workaround:
Unknown

## Platforms:
- [x] Android: Standalone
- [x] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/8c98560b-839b-46b7-bbd1-1e57a91800c2

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021864721405539023301</li>
        <li>Upwork Job ID: 1864721405539023301</li>
        <li>Last Price Increase: 2024-12-05</li>
    </ul>
</details>

**Comment by ikevin127** [comment]
This should be `Internal` as the video shows **Android HybridApp** where the Domains link opens within the HybridApp in a web view - `External` contributors don't have access to the `HybridApp` repo.

Also it's impossible to reproduce and test the issue on **Android: Native** since the `Domains` link opens externally in the web browser, which is why I don't even think this issue exist on **Android: Native**.

**Comment by lschurr** [comment]
Asking here: https://expensify.slack.com/archives/C01SKUP7QR0/p1734018982340219

**Comment by lschurr** [comment]
No response in Slack yet: https://expensify.slack.com/archives/C07HPDRELLD/p1734020160697769

**Comment by AndrewGable** [comment]
The video shows it happening on standalone so not sure I agree it’s exclusive to HybridApp, how did you determine that @ikevin127 ?

**Comment by AndrewGable** [comment]
Ah - Apologies I missed the first part of the video. Agree this seems like a HybridApp only bug, but it seems like this is a deep link bug. We reverted deep links here: https://github.com/Expensify/Mobile-Expensify/pull/13336

So this shouldn't be reproducible anymore, and I cannot reproduce on the latest staging version of Android HybridApp.

https://github.com/user-attachments/assets/f3c7cca2-bb04-4247-8cbd-4da4f16ff763

cc @war-in - Please add this to your test steps when we undo the revert.

Please reopen if you disagree.

**Comment by war-in** [comment]
Sure, I'll keep that in mind 🫡
