### ISSUE TITLE
Hybrid - Android - Login - Chats of both account are seen when re logging in with a different account

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#53531]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.71-0
**Reproducible in staging?:** Yes
**Reproducible in production?:** No
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** No, reproducible on hybrid only
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** ibellicotest+69@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Open the Expensify app.
2. Log in with a valid account.
3. Log out.
4. Log in again with a different account.
5. Verify that the chats displayed are only the ones that belong to this second account.

## Expected Result:
Chats of two different accounts shouldn´t be mixed when logging out and relogging with a different account.

## Actual Result:
Chats of two different accounts are displayed on inbox when logging out and re logging in with a different account. When opening the chats of the first account, a "Hmm, it´s not here" message is displayed and after that, the chat disappears.

## Workaround:
Unknown

## Platforms:
- [ ] Android: Standalone
- [x] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/8afe2601-d612-47fe-a73b-bf283a25cf4d

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by jnowakow** [comment]
Hello, I'm from SoftwareMansion and I'll work on this one
