### ISSUE TITLE
Change Assignee copy in Workspace settings to `Select all`

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#5356]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

Coming from Slack thread [here](https://expensify.slack.com/archives/C020EPP9B9A/p1632154896296600).

We decided to change the `Assignee` word on `/workspace/<policy-id>/people` page to `Select all` as the original expression is mostly just confusing.

![image](https://user-images.githubusercontent.com/36083550/134046606-385b31c2-95ce-4b25-9098-bee16775a2a2.png)

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:**
**Reproducible in staging?:**
**Reproducible in production?:**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mountiny** [comment]
PR is in review

**Comment by MitchExpensify** [comment]
Not on staging- reopening

**Comment by MitchExpensify** [comment]
done
