### ISSUE TITLE
[HOLD for payment 2024-12-19] HybridApp iOS: Fix version mismatch for Notification Service Extension

### ISSUE THREAD

**Issue by arosiclair** [Expensify/App#53569]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.70.9
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** N/A
**Logs:** N/A
**Expensify/Expensify Issue URL:** N/A
**Issue reported by:** @AndrewGable 
**Slack conversation**: https://expensify.slack.com/archives/C03V9A4TB/p1733271524517199?thread_ts=1733262728.540769&cid=C03V9A4TB

## Action Performed:

Deploy new version of HybridApp

## Expected Result:
No warnings from Apple about version mismatches in our bundle

## Actual Result:

![Google Chrome 2024-12-03 at 17 17 59](https://github.com/user-attachments/assets/002ae430-1369-4102-befe-72e92a94f92b)

## Workaround:
None

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [x] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @sakluger</details>

**Comment by arosiclair** [comment]
This is the same as [this old issue](https://github.com/Expensify/App/issues/33961) but now for the HybridApp

**Comment by AndrewGable** [comment]
Thank you!

**Comment by arosiclair** [comment]
This was just an issue with the deploy which should be fixed now. Closing this out
