### ISSUE TITLE
Chat - Deleted message stays in the notification center unless report is manually opened

### ISSUE THREAD

**Issue by vincdargento** [Expensify/App#53578]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.71-0
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Yes, reproducible on both
**If this was caught during regression testing, add the test name, ID and link from TestRail:** Exp
**Email or phone of affected tester (no customers):** nathanmulugetatesting+2331@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Open the New Expensify hybrid app
2. Receive a message from another account
3. Notice the LHN becomes bold for the newly received message
4. Delete the sent message
5. Open the notification center and observe the deleted message stays there after being deleted from the sender account
6. Open the chat with the sender 
7. Open the notification center

## Expected Result:
The notification for the deleted message disappears without the receiver opening the report first

## Actual Result:
The notification for the deleted message stays there until the receiver manually opens the report with the sender

## Workaround:
Unknown

## Platforms:
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [x] iOS: Standalone
- [x] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/a8712a8c-4c37-41d2-b2d6-afc3b3a3b9f9

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Julesssss** [comment]
It's not a bug. 

We can 'clear' notifications but this is a new feature that we haven't yet implemented. The simplest way will probably be to handle this via Airship. We'll get to this eventually
