### ISSUE TITLE
IOS - Workspace - User avatar gets shown briefly when closing workspace avatar

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#53586]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.71-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** nathanmulugetatesting+2335@gmail.com
**Issue reported by:** Applause  - Internal Team

## Action Performed:
1. Open IOS hybrid app
2. Create a workspace
3. Navigate to workspace chat
4. Tap on header
5. Open User's avatar (The smaller one with the circle)
6. Navigate back and open workspace avatar (The bigger one with rectangular border)

## Expected Result:
User's avatar does not get shown when closing workspace avatar

## Actual Result:
User's avatar gets shown briefly when navigating back to close

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [x] iOS: Standalone
- [x] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/4935456c-36f6-4031-b1fb-dedde91003f4

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by VictoriaExpensify** [comment]
This seems like an insignificant issue to me. It doesn't impact the customer experience and I don't think we need to worry about it for now.
