### ISSUE TITLE
Troubleshoot - Double clicking/tapping outside of troubleshoot modal reopens the modal

### ISSUE THREAD

**Issue by vincdargento** [Expensify/App#53585]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.71-0
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Yes, reproducible on both
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** nathanmulugetatesting+2337@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Press CTRL + D to open troubleshoot modal
3. Double click outside of the modal

## Expected Result:
The modal closes

## Actual Result:
The modal closes and reopens again

## Workaround:
Unknown

## Platforms:
- [x] Android: Standalone
- [x] Android: HybridApp
- [x] Android: mWeb Chrome
- [x] iOS: Standalone
- [x] iOS: HybridApp
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/54a4e442-9c04-473b-a4d7-10fb22ba3cf7

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by OfstadC** [comment]
I haven't' had a chance to review. Will look at this this weekend or first thing Monday morning

**Comment by OfstadC** [comment]
Can confirm this is reproducible - just need to sort which project it should fall under 😅

**Comment by OfstadC** [comment]
Chatted in Slack that this is likely not a priority - so Closing
