### ISSUE TITLE
Expense - .CSV file is not translated to Spanish

### ISSUE THREAD

**Issue by vincdargento** [Expensify/App#53594]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.71-0
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5298436
**Email or phone of affected tester (no customers):** hywnnoj+04@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Open the app or go to: https://staging.new.expensify.com/
2. Log in
3. Click on 'Settings' > 'Preferences' > 'Language' > 'Spanish'
4. Click on FAB > Create expense > Submit it
5. Click on 'Search' between 'Inbox' & 'Settings'.
6. Click the checkbox of the expense
7. Click on 'Selected' green button at the top right
8. Click on 'Download'

## Expected Result:
The downloaded .CSV file is in Spanish.

## Actual Result:
The downloaded .CSV file is in English.

## Workaround:
Unknown

## Platforms:
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [x] iOS: Standalone
- [x] iOS: HybridApp
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/216c0a0a-6e2c-4668-97cb-b37f8936b799

<img width="1665" alt="bug" src="https://github.com/user-attachments/assets/78a8f77f-cfcb-4207-8d1b-209ffc7ee7f7">

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Christinadobrzyn** [comment]
Asking the team if this is a quality job and something we want to do - https://expensify.slack.com/archives/C05LX9D6E07/p1733517116280799

**Comment by Christinadobrzyn** [comment]
Based on the [discussion with the eng team](https://expensify.slack.com/archives/C05LX9D6E07/p1733517116280799), we're going to close this without action.
