### ISSUE TITLE
Expense details - Unhold expense option is missing for the employee

### ISSUE THREAD

**Issue by vincdargento** [Expensify/App#53609]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.71-1
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Yes, reproducible on both
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5300025
**Email or phone of affected tester (no customers):** N/A
**Issue reported by:** Applause Internal Team

## Action Performed:
Preconditions: Preconditions: WS owner invited employee and approver, set approvals to the approver.
1. Launch staging hybrid app and log in.
2. As an Employee, submit 2 expenses to the workspace chat.
3. As the Approver, put one of the expenses on hold.
4. As Employee, navigate to a expense on hold.
5. Click on the header of the conversation and verify there's an option to unhold the expense.

## Expected Result:
The option to unhold expense is displayed in the header of an expense, that was put on hold by approver of a WS expenses.

## Actual Result:
Unhold expense option is missing for the employee, when the expense was put on hold by the approver.

## Workaround:
Unknown

## Platforms:
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [x] iOS: Standalone
- [x] iOS: HybridApp
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/166fbad9-4bbe-4a49-87ff-c456c8273c7c

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by isagoico** [comment]
@vincdargento shared that this is expected behavior based on this comment - https://github.com/Expensify/App/issues/45063#issuecomment-2221943172. Will close this issue, please reopen if needed.
