### ISSUE TITLE
LHN- Only "remove" is shown when group creator remove a member until refreshed/navigate back

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#53607]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.71-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** testpayment935+60ye@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Navigate to https://staging.new.expensify.com/
2. Create a group chat with 1 user
3. Navigate to member list and remove the user from the Group
4. Notice LHN shows "removed" only until refreshed/ navigated back to the group

## Expected Result:
LHN should show "removed 1 user" rater than "removed" only without refreshing/ navigating back again to the group (Invite user behavior)

## Actual Result:
Only "remove" is shown when group creator remove a member until refreshed/navigate back

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/26b73650-376a-4076-bb11-9883e6e2be6b

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by joekaufmanexpensify** [comment]
This is a pretty minor issue. I don't think this would have any real user impact, or will anyone really notice this. In an ideal world the full system message would be visible in LHN before refreshing, but I don't think it really matters that it's not. 

I suggest we close this if and until a real user is negatively impacted by this. Please let me know if anyone disagrees!
