### ISSUE TITLE
[HOLD for payment 2024-12-17] Jumpy "Clear filter" button when keyboard gets shown

### ISSUE THREAD

**Issue by kirillzyusko** [Expensify/App#53633]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.72
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):** kiryl@margelo.io
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @kirillzyusko 
**Slack conversation** (hyperlinked to channel name):

## Action Performed:

1. Go to search tab
2. Press workspace switcher
3. See how additional keyboard space appears (above the keyboard) and disappears
4. Select workspace
5. Press workspace switcher
6. See how button gets moved higher and then return to its expected position

## Expected Result:

3. No jumps
6. No jumps 

## Actual Result:

3. For a fraction of second keyboard spacing exceeds the keyboard and we see a space above the keyboard
6. Button should be placed in a correct position immediately

## Workaround:

N/A

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Standalone
- [x] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [x] iOS: HybridApp
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>

https://github.com/user-attachments/assets/5af0a6aa-e91b-4c5f-b5dc-2fd9656943c9
  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @JmillsExpensify</details>

**Comment by kirillzyusko** [comment]
I believe the issue has been fixed so it can be closed 🙂

**Comment by mallenexpensify** [comment]
### Payment Summary 

Contributor+: @Ollyws due $250 via NewDot for [PR review](https://github.com/Expensify/App/pull/53635)

I checked assignment date and it's after their eligibility date

**Comment by isabelastisser** [comment]
@Ollyws has submitted payment for this report on ND [here](https://new.expensify.com/search/view/8793999634286?backTo=%2Fr%2F757523223654585%2F%3FbackTo%3D%252Fr%252F7045783569904003).

SO: https://stackoverflowteams.com/c/expensify/questions/7582

Vendor found in [VML](https://docs.google.com/spreadsheets/d/1Fs-umMmHhCCMzxiczyNydl9Rd6jdO0pQskYA3RvNWQc/edit?gid=1740618654#gid=1740618654): True. Status: Active

Amount requested: $250. Matches the payment summary [here](https://github.com/Expensify/App/issues/53633#issuecomment-3140764569).

I am not already the BZ assignee. I have approved this payment.
