### ISSUE TITLE
[$250] Different back navigation from more features hyperlink on tags page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#53642]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.72-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+nl853@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Navigate to staging.new.expensify.com and sign in with an Expensifail account
2. Create a workspace
3. Enable tags and rules in more features
4. Add a tag
5. Open the tag and tap on "More features" hyperlink
6. Tap on the back icon at the top left corner
7. Open the tag again
8. Tap on the "More features" hyper link
9. Tap on the browser back button

## Expected Result:
App navigates to Tags page

## Actual Result:
App navigates to workspace editor or other page, which is not the same behavior as navigating back using the apps back navigation

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [x] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/fc1387aa-25ea-4fec-8d09-ef835bf7936d

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021865177208410818944</li>
        <li>Upwork Job ID: 1865177208410818944</li>
        <li>Last Price Increase: 2024-12-13</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @hungvu193</details>

**Comment by hungvu193** [comment]
I'll prioritize reviewing this issue tomorrow

**Comment by hungvu193** [comment]
Thanks for the proposal @daledah. I think using both types `UP` for `navigate`  or `closeAndNavigate` will lead to another issue, when pressing back from WorkspaceMoreFeaturePage, it navigates to Tags page instead of WorkspaceListPage.

https://github.com/user-attachments/assets/f907094e-5d31-4c7d-91ee-3b9710a0df42

**Comment by hungvu193** [comment]
> > App navigates to Tags page
> 
> @hungvu193 it seems to be expected in OP

I think that's expected for Safari, but it looks weird to me in Chrome. 

@twisterdotcom Can you take a look at [my comment above](https://github.com/Expensify/App/issues/53642#issuecomment-2528392917) and let me know what's your thought? ty

**Comment by hungvu193** [comment]
Still waiting for proposals

**Comment by twisterdotcom** [comment]
I think given this is niche and doesn't truly affect or even confuse _that much_ I will close. Perhaps if we ever do a big bug rundown we'll come back to it.
