### ISSUE TITLE
[HOLD for payment 2024-12-20] Add inline Submit action to Search

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#53640]
We've added the `Approve` and `Pay` actions to Search in [this PR](https://github.com/Expensify/App/issues/51911. Next, we should add the `Submit` action to the Search results page to make it a complete experience for users looking to batch manage their expenses

<details><summary>Issue Owner</summary>Current Issue Owner: @Christinadobrzyn</details>

**Comment by luacmartins** [comment]
Created an issue [here](https://github.com/Expensify/Expensify/issues/451223)

**Comment by Christinadobrzyn** [comment]
monitoring https://github.com/Expensify/Expensify/issues/451223

**Comment by Christinadobrzyn** [comment]
Preparing for upcoming payment 

Contributor+: @ishpaul777  owed $250 via NewDot

@ishpaul777 do we need a regression test for this?

**Comment by Christinadobrzyn** [comment]
@ishpaul777 are you paid in Upwork? https://www.upwork.com/nx/wm/offer/105419289

Do we need a regression test for this? TY!

**Comment by Christinadobrzyn** [comment]
I'll create the regression test just in case we want to submit one - https://github.com/Expensify/Expensify/issues/455332

I paid you in Upwork @ishpaul777 based on this payment summary - https://github.com/Expensify/App/issues/53640#issuecomment-2556567337

We'll keep this open to see if @luacmartins has any input on the regression test - https://github.com/Expensify/App/issues/53640#issuecomment-2557744660

**Comment by sonkeydotcom** [comment]
Can I work on this

**Comment by sonkeydotcom** [comment]
Contributor details
Your Expensify account email: annagu.kennedy@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0126988bb835c03de3

**Comment by Christinadobrzyn** [comment]
Hi @sonkeydotcom! thanks for your interest! This job is already complete. Feel free to check out the open jobs here https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22

**Comment by Christinadobrzyn** [comment]
I'll close this as complete. @luacmartins is ooo so we'll consider this complete. Thanks everyone!
