### ISSUE TITLE
Copilot - Console error appears when clicking Add copilot and Change access level

### ISSUE THREAD

**Issue by vincdargento** [Expensify/App#53644]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.72-0
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://github.com/Expensify/App/pull/51204
**Email or phone of affected tester (no customers):** N/A
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Navigate to staging.new.expensify.com and sign in with existing gmail account.
2. Go to Security > Add copilot.
3. Add a copilot. 
4. Verify that no errors appear in the JS console
5. Click 3-dot menu next to the copilot, change access level. 
6. Verify that no errors appear in the JS console

## Expected Result:
No errors appears in the JS console when interacting with Security tab and Copilot menu.

## Actual Result:
Console error appears when clicking Add copilot and Change access level. It also appears when opening Security tab.

## Workaround:
Unknown

## Platforms:
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/62fd2bf6-0b07-490e-8d79-25f5593f9fb5

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by jliexpensify** [comment]
I don't think this is a real issue, it's not an actual bug in the product.
