### ISSUE TITLE
Submit expense - Submit button returns briefly after submitting expense

### ISSUE THREAD

**Issue by vincdargento** [Expensify/App#53657]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.72-0
**Reproducible in staging?:** Yes
**Reproducible in production?:** Unable to check
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Yes, reproducible on both
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://github.com/Expensify/App/pull/53051
**Email or phone of affected tester (no customers):** N/A
**Issue reported by:** Applause Internal Team

## Action Performed:
Preconditions: Admin created a WS and added employees A and B. Admin enabled workflows and rules. Added a workflow with user  user B as approver. Delay submissions is enabled and set to Manually.

1. As user A launch the Hybrid app and sign in.
2. Submit an expense to the Workspace chat.
3. Tap "Submit" on the Expense preview.

## Expected Result:
Submit button disappears after tapping on it.

## Actual Result:
Submit button briefly returns after tapping on it.

## Workaround:
Unknown

## Platforms:
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [x] iOS: Standalone
- [x] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/6ded3400-53c7-4d60-b7d4-0145abaf60d6

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by VictoriaExpensify** [comment]
This seems incredibly minor - it only reappears for a split second, blink and you'd miss it. I don't think this is worth using our resources on at the moment
