### ISSUE TITLE
Distance - No system error message when creating an expense with a large amount

### ISSUE THREAD

**Issue by vincdargento** [Expensify/App#53664]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.72-0
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Yes, reproducible on both
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5309343
**Email or phone of affected tester (no customers):** sustinov@applausemail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
Prerequisites:
Set Report Currency = KZT in Individual WS OldDot

Steps:
1. Open HybridApp
2. Create a group conversation with 2 participants
3. Go to the created group
4. Go to + Menu -> Split expense -> Distance
5. Set 2 waypoints “321 West 84th Avenue, Thornton, CO, USA” and “123 William Street, New York, NY, USA”
6. Click on the “Next” button
7. Click on the “Split <Currency><Amount>” button

## Expected Result:
When trying to create a split distance expense with a large total amount, the error “Invalid amount.” or other error should appear depending on the technical documentation

## Actual Result:
No system error message when creating a split distance expense with a large amount

## Workaround:
Unknown

## Platforms:
- [x] Android: Standalone
- [x] Android: HybridApp
- [x] Android: mWeb Chrome
- [x] iOS: Standalone
- [x] iOS: HybridApp
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/d301b72f-253c-4073-8ee0-c75b6677abef

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by stephanieelliott** [comment]
This is edge case I think, it's only occurring for expenses with 10+ chars which I don't everyday users would be creating
