### ISSUE TITLE
Start chat - The padding of the 'Next' button is not proportional

### ISSUE THREAD

**Issue by vincdargento** [Expensify/App#53672]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.72-0
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5305506
**Email or phone of affected tester (no customers):** hywnnoj@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Open the app or go to: https://staging.new.expensify.com/
2. Loggin with an account with multiple contacts
3. Click on FAB > Start chat
4. Click on any contact 'Add to group'

## Expected Result:
The padding of the ‘Next’ button should be aligned proportionally.

## Actual Result:
The padding of the ‘Next’ is not proportional.

## Workaround:
Unknown

## Platforms:
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [x] iOS: Standalone
- [x] iOS: HybridApp
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/8a2bf2d1-fc01-4a32-b57a-b0a4f291fa1a

<img width="1728" alt="bug" src="https://github.com/user-attachments/assets/1bc50974-9a40-47f7-9e96-3a532e37f921">

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by jacobkim9881** [comment]
I agree with @neonbhai. There is `<ReferralProgramCTA>` so may padding/margin top not be needed. W/o `<ReferralProgramCTA>` it seems the next button short of padding/margin top.

**Comment by dannymcclain** [comment]
It is expected for the footer button to not have any top margin/padding. Here's another example from the submit expense flow:
![CleanShot 2024-12-09 at 10 21 13@2x](https://github.com/user-attachments/assets/04f5f2a3-6fac-401d-a745-d1a178e59b74)

**Comment by shawnborton** [comment]
Yeah that's my understanding as well Danny.

**Comment by sakluger** [comment]
Oh interesting, thanks for confirming! Looks odd to me, but if it's expected behavior, then we can close the issue.
