### ISSUE TITLE
Search - Deleted search reappears when using device back button after deleting it.

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#53684]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.72-0
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Yes, reproducible on both
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** ibellicotest+71@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Open the Expensify app.
2. Tap on "Search" on the bottom of the screen.
3. Tap on the filters icon.
4. Apply any filter to the search.
5. Tap on "Save Search"
6. Once redirected to the new search, tap on the dropdown menu and select "Expenses"
7. Tap on the dropdown menu again.
8. Tap on the three dots icon next to the saved search.
9. Delete the search.
10. Use the device back button.
11. Verify that you are redirected to inbox.

## Expected Result:
When using the device back button after deleting a saved search, the user should be redirected to inbox.

## Actual Result:
When using the device back button after deleting a saved search, the user is redirected to that search results again and it reappears on the dropdown menu.

## Workaround:
Unknown

## Platforms:
- [x] Android: Standalone
- [x] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/2871c36e-f1e4-455d-b7b8-c2e9bb73338f

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Tony-MK** [comment]
I believe this is expected behavior.

It is not a saved search but the current one.

**Comment by abekkala** [comment]
I agree with Tony-MK. 
It's not 'saved' but due to back-button the current one shows
