### ISSUE TITLE
Attachment - The preview of an attachment is scrolled through after it has been fully upload

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#53691]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.72-0
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Yes, reproducible on both
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5308681
**Email or phone of affected tester (no customers):** sustinov@applausemail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Open HybridApp
2. Log in to the HT account
3. Send 2 any images 
4. Turn off the internet
5. Add any image
6. Open the image from step 5
7. Turn on the Internet

## Expected Result:
The preview of an attachment should not be scrolled after it has been fully uploaded

## Actual Result:
The preview of an attachment is scrolled through after it has been fully uploaded

## Workaround:
Unknown

## Platforms:
- [x] Android: Standalone
- [x] Android: HybridApp
- [ ] Android: mWeb Chrome
- [x] iOS: Standalone
- [x] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
https://github.com/user-attachments/assets/27524a4b-569f-42ad-be02-eec335ab1d45

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by MitchExpensify** [comment]
I don't think this is worth fixing right now.
