### ISSUE TITLE
Card - On adding virtual card entering incorrect magic code shows incorrect error

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#53696]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** V9. 0.72-0
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Yes, reproducible on both
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N
**Email or phone of affected tester (no customers):** N
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/home
2. Go to workspace settings
3. Enable expensify card
4. Set a bank account
5. Add a virtual card and in the flow enter incorrect magic code

## Expected Result:
On adding virtual card entering incorrect magic code must show correct error.

## Actual Result:
On adding virtual card entering incorrect magic code shows incorrect error " You must be a domain admin to create the virtual card."

## Workaround:
Unknown

## Platforms:
- [x] Android: Standalone
- [x] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/f7e76faa-3b7f-4c5f-a2bb-5dad9312e421

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by FitseTLT** [comment]
BE is returning wrong error
```
 "data": {
        "onyxData": [
            {
                "onyxMethod": "merge",
                "key": "issueNewExpensifyCard",
                "value": {
                    "errors": {
                        "1733490968496807": "You must be a domain admin to create the virtual card."
                    }
                }
            }
```

**Comment by DylanDylann** [comment]
It seems this error message is from BE

cc @mountiny

**Comment by greg-schroeder** [comment]
Do you agree @mountiny? I can make this `Internal` if so

**Comment by greg-schroeder** [comment]
PR is merged, awaiting deploy to staging -> prod

also there is no contributor participation here, so this can be closed alongside the prod deploy

**Comment by greg-schroeder** [comment]
deployed
