### ISSUE TITLE
402 Approvals can only be set for members of the policy” error when setting approver for new user added to workspace

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#53738]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.72-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @garrettmknight 
**Slack conversation** (hyperlinked to channel name): [#expense](https://expensify.slack.com/archives/C06ML6X0W9L/p1733313744201329)

## Action Performed:

1. Create a workspace
2. Invite Submitter + Approver A
3. Enable Workflows > Approval + Delay Submission
4. Set Approver A as approver
(A key step to reproduce this is that all accounts must be on the same validated domain)
## Expected Result:
Approver A is set as Approver
## Actual Result:
402 Approvals can only be set for members of the policy” error when setting approver for new user added to workspace
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details>

https://github.com/user-attachments/assets/3a88257b-f7ad-4b8b-b4be-1d4ce8e803ce

![Snip - New Expensify - Google Chrome (2)](https://github.com/user-attachments/assets/9ff32c54-4939-4605-afe0-e6cd70563e26)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @neil-marcellini</details>

**Comment by neil-marcellini** [comment]
The fix is under review now. It only requires a backend change.

**Comment by neil-marcellini** [comment]
This is all done
