### ISSUE TITLE
[HOLD for payment 2024-12-19] Fix the pusher instance not found crash

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#53752]
We are seeing this specific crash error in firebase that we have not been able to easily reproduce but we can see that its happening:

```
   Fatal Exception: com.facebook.react.common.JavascriptException: Error: TaskQueue: Error with task : [Pusher] instance not found. Pusher.subscribe()
            most likely has been called before Pusher.init(), js engine: hermes, stack:
anonymous@1:3767030
processNext@1:847707
_processUpdate@1:846412
anonymous@1:524811
_callTimer@1:523728
_callReactNativeMicrotasksPass@1:523929
callReactNativeMicrotasks@1:525881
__callReactNativeMicrotasks@1:218344
anonymous@1:216543
__guard@1:218218
flushedQueue@1:216454
callFunctionReturnFlushedQueue@1:216310

       at com.facebook.react.modules.core.ExceptionsManagerModule.reportException(ExceptionsManagerModule.java:65)
       at com.facebook.jni.NativeRunnable.run(NativeRunnable.java)
       at android.os.Handler.handleCallback(Handler.java:958)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
       at android.os.Looper.loopOnce(Looper.java:230)
       at android.os.Looper.loop(Looper.java:319)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:235)
       at java.lang.Thread.run(Thread.java:1012)
```

Here is a link to firebase for the [crash](https://console.firebase.google.com/u/0/project/expensify-mobile-app/crashlytics/app/android:org.me.mobiexpensifyg/issues/022302da0d55dfb152b0c7d7d51a24a7?time=last-seven-days&types=crash&versions=9.0.68.7%20(509006807);9.0.68.6%20(509006806);9.0.68.5%20(509006805);9.0.68.3%20(509006803)&sessionEventKey=674A0D8B030600017893F99DC3CB5E0E_2021299528253113645)

<details><summary>Issue Owner</summary>Current Issue Owner: @mallenexpensify</details>

**Comment by jnowakow** [comment]
Hello, I'm from SoftwareMansion and I'll work on this issue

**Comment by s77rt** [comment]
Hey, I think the PR fixing this caused https://github.com/Expensify/App/issues/54142. Please take a look 👀

**Comment by mountiny** [comment]
$125 for @allroundexperts as there was a regression from this PR

**Comment by mallenexpensify** [comment]
Contributor+: @allroundexperts due $125 via NewDot 

Do we want a test case for this? Or one updated?

**Comment by allroundexperts** [comment]
I don't think we need a test case for this. In the PR, the test steps just mentioned opening the app and verifying if it crashed or not.

**Comment by mountiny** [comment]
I agree, I am not sure what would be a reliable test case for this one. We will monitor the crashes in firebase

**Comment by mallenexpensify** [comment]
Thanks @allroundexperts and @mountiny, closing

**Comment by JmillsExpensify** [comment]
$125 approved for @allroundexperts
