### ISSUE TITLE
 Invoices - "Leave" option is available on archived invoice chat

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#53769]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.73-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N 
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:**N/A
**Email or phone of affected tester (no customers):** applausetester+23i0230@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to FAB > Send invoice
3. Send an invoice to anyone
4. Go to workspace settings
5. Delete the workspace
6. Go to invoice chat
7. Click on the report header

## Expected Result:
There should be no "Leave" option on archived invoice chat (production behavior)

## Actual Result:
There is "Leave" option on archived invoice chat

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/ce6d4bc0-9cee-4cb6-a742-8d4096c88ec2

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by luacmartins** [comment]
This is fixed in staging
![Screenshot 2024-12-09 at 3 39 29 PM](https://github.com/user-attachments/assets/bca832f8-e8a8-41e0-820f-69e15f038409)
