### ISSUE TITLE
Create workspace - Edit avatar modal is blocking the avatar

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#53768]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.73-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+23i0230@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to Account settings > Workspaces
3. Click New workspace
4. Click on avatar
5. Upload an avatar
6. Click on the custom avatar

## Expected Result:
The edit avatar modal will not block the avatar

## Actual Result:
The edit avatar modal is blocking the avatar

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/76348e34-eb51-4a72-9d92-17f5de7de40b

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by MarioExpensify** [comment]
I'm removing the deploy blocker on this one as this is just an UI issue that is not preventing from the user to actually change the avatar or moving forward.

**Comment by luacmartins** [comment]
Seems to come from https://github.com/Expensify/App/pull/52164 
[@Krishna Gupta](https://expensify.slack.com/team/U05JNE54K7X)

**Comment by luacmartins** [comment]
This is fixed in staging
![Screenshot 2024-12-09 at 3 35 28 PM](https://github.com/user-attachments/assets/84ab1fff-50b0-4232-8f95-44cac0f2482a)
