### ISSUE TITLE
Workspace - Unable to save new workspace name

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#53765]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.73-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** sjdiosjiosjojonsjdj@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Sign up with a new Gmail account (random email without +)
3. On onboarding purpose, choose Manage my team's expenses
4. Select organization size
5. Select an accounting
6. Complete the onboarding
7. Go to workspace settings > Profile
8. Click Name
9. Edit the name and save it

## Expected Result:
The new workspace name is saved successfully

## Actual Result:
The new workspace name is not saved. It reverts to the previous name and RBR shows on Profile tab

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/fb5877fb-5ba6-4933-8e47-6ddb994ce84c

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by luacmartins** [comment]
I see `Invalid currency in custom unit rate`. 
![Screenshot 2024-12-09 at 12 33 13 PM](https://github.com/user-attachments/assets/94b85b2e-eb47-4a48-bc26-b97c4fde8ee8)

It seems like the workspace currency is empty
![Screenshot 2024-12-09 at 12 33 57 PM](https://github.com/user-attachments/assets/575e123d-aa88-4908-8019-5c2172183164)

**Comment by luacmartins** [comment]
Likely coming from https://github.com/Expensify/App/pull/52164/files

**Comment by luacmartins** [comment]
Yea, we're now passing an empty string as the currency [here](https://github.com/Expensify/App/blob/main/src/libs/actions/Policy/Policy.ts#L1633)

**Comment by luacmartins** [comment]
This is fixed in staging

https://github.com/user-attachments/assets/7b2bb1b2-5116-45bf-b0fb-ceaa51bd99f2
