### ISSUE TITLE
Create workspace - Selected currecy does not appear selected with a green checkmark

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#53766]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.73-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+kh1311020@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to Account settings > Workspaces
3. Click New workspace
4. Note that Currency field has currency selected
5. Click on the Currency field
6. Scroll down to the selected currency

## Expected Result:
The selected currency will appear selected with a green checkmark

## Actual Result:
The selected currecy does not appear selected with a green checkmark

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/10a71fe3-9207-4ab1-bf75-e2a1298a3f9b

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by ChavdaSachin** [comment]
coming from https://github.com/Expensify/App/pull/52164
cc. @Krishna2323

**Comment by luacmartins** [comment]
This is fixed in staging

https://github.com/user-attachments/assets/547cdc7a-3a8e-432c-abad-1d8871b88840
