### ISSUE TITLE
[$250] Login - Changing link to staging doesn't log in user/display welcome modal

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#53778]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.73-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:**  N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5315890
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Open new expensify web
2. create a new expensifail user
3. once recieved the link, copy it
4. change to staging and paste in browser in different window

## Expected Result:
The link should log in the user with a new account and should display a welcome modal

## Actual Result:
The user is not logged in in any window and welcome modal is not displayed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/881b150a-abe1-473e-b3bd-2c2e6945c569

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021867607890498748252</li>
        <li>Upwork Job ID: 1867607890498748252</li>
        <li>Last Price Increase: 2024-12-20</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @hungvu193</details>

**Comment by bfitzexpensify** [comment]
Though this isn't a customer flow since it's on staging, the flow itself - logging in - is pretty important, so I think we should look into getting this fixed.

**Comment by hungvu193** [comment]
Look like an BE issue 🤔

**Comment by hungvu193** [comment]
Not overdue

**Comment by bfitzexpensify** [comment]
Updating to `Internal` and adjusting the priority

**Comment by bfitzexpensify** [comment]
Actually - since this is only happening on Staging, I am going to close for now.
