### ISSUE TITLE
The last expense on the report is having the date changed to the migration date

### ISSUE THREAD

**Issue by flaviadefaria** [Expensify/App#53775]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** NA
**Reproducible in staging?:**  Yes
**Reproducible in production?:** Yes
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** NA
**If this was caught during regression testing, add the test name, ID and link from TestRail:** NA
**Email or phone of affected tester (no customers):** flavia.usertesting+migrationuser1@gmail.com
**Logs:** NA
**Expensify/Expensify Issue URL:** NA
**Issue reported by:** @flaviadefaria 
**Slack conversation** (hyperlinked to channel name): https://expensify.slack.com/archives/C07NMDKEFMH/p1733514826233499

## Action Performed:
1. Create a report with multiple expenses in Classic
2. Migrate the user

## Expected Result:
The date of the last expense shouldn't have it's date updated on the report so that the chronological order of expenses and comments is kept.

## Actual Result:
The last expense on the report has the date changed to the migration date which is messing up the order of expenses/comments in the report. But if you open the actual expense the date is correct.

<img width="1044" alt="image" src="https://github.com/user-attachments/assets/e4b0d818-cb07-4ffe-8b90-b5cef931a987">

## Workaround:
NA

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by puneetlath** [comment]
It's very strange. I'm not able to reproduce this bug myself. And it seems to only be for that one report: 2261815874276001. The same user has another report (4551785031518595) that also has two expenses and was approved and doesn't have this issue. 

<img width="604" alt="image" src="https://github.com/user-attachments/assets/30029cbd-bf53-43b9-b908-3a207168b458" />

**Comment by puneetlath** [comment]
Ok I figured it out. Raised a PR: https://github.com/Expensify/Auth/pull/13511

**Comment by puneetlath** [comment]
This is fixed.
