### ISSUE TITLE
Chat - Attachment modal and delete workspace modal open with delay

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#53780]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.73-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:** applausetester+23i0230@applause.expensifail.com
**Email or phone of affected tester (no customers):** applausetester+23i0230@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to chat
3. Upload an attachment
4. Click on the attachment
5. Note that the attachment modal opens with delay
6. Go to Account settings > Workspaces
7. Click on 3-dot menu next to workspace
8. Click Delete workspace
9. Note that the delete modal opens with delay

## Expected Result:
Attachment modal and delete workspace modal will not open with delay

## Actual Result:
Attachment modal and delete workspace modal open with delay

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/3f6cf7ce-5c9a-41df-b85d-9b9a92eb852a

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by luacmartins** [comment]
Fixed in staging

https://github.com/user-attachments/assets/915bf2bd-c64f-4f9e-bd52-91e7242f483e
