### ISSUE TITLE
FAB - Page crashes after tracking an expense from QAB

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#53793]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.73-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause  - Internal Team
Reproduced on  device:
 Windows 11 /Chrome 
 IPhone 14 Pro/Chrome

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Login with the new Gmail account in incognito mode
3. Complete the incorporation process using the option “Manage My team's expense”
4. Select any size of employees
5. Select any accounting software and click "Continue"
6. Click on "+" Fab Button and create a manual Expense with $1
7. Click on the "Next" button and click on "Just track it" and Track the expense
8. Click on Share with my Accountant and select the WS created
9. Type a merchant and submit the expense
10. Click on "+" Fab Button and click on "Track expense" from the QAB

## Expected Result:
The RHP should be opened to place an amount to track a new expense

## Actual Result:
After clicking on the QAB to track an expense the page crashes

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/ca52bddb-4038-4217-8aa5-0aacb7b0affc

[logs (2).txt](https://github.com/user-attachments/files/18067940/logs.2.txt)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by luacmartins** [comment]
```
Uncaught RangeError: Invalid currency code : 
    at new NumberFormat (<anonymous>)
    at eval (index.ts:78:1)
    at Object.getSet (ArrayCache.ts:57:1)
    at new memoized (index.ts:76:1)
    at Module.formatToParts (index.ts:12:1)
    at Module.getLocalizedCurrencySymbol (CurrencyUtils.ts:47:17)
    at BaseTextInputWithCurrencySymbol (BaseTextInputWithCurrencySymbol.tsx:85:10)
```

I think this will be fixed by this CP https://github.com/Expensify/App/pull/53786

**Comment by luacmartins** [comment]
Yea, I can confirm this is fixed on the latest main and will be fixed by the CP above

**Comment by luacmartins** [comment]
Fixed in staging


https://github.com/user-attachments/assets/9b9b6da7-9895-43c3-ac04-babc109f469d
