### ISSUE TITLE
Track Expense - Transaction created in OldDot appears in NewDot after chat revisit

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#53796]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.73-1
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5316310&group_by=cases:section_id&group_order=asc&group_id=309130
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Sign in ND and OD.
2. In OldDot - Create an unreported transaction 
3. In ND, observe the self-DM.

## Expected Result:
Created expenses should immediately appear in the self-DM.

## Actual Result:
Transaction created in OldDot appears in NewDot after chat revisit

## Workaround:
Unknown

## Platforms:
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/34933763-83f7-4143-bc08-23bb751b9927

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by adelekennedy** [comment]
I can reproduce repeatedly but this is such a polish to me when switching between the platforms I don't think we need to address it now
