### ISSUE TITLE
All - Approvers Flow - WS Chat in LHN with new report is shown as read for Approver/Admin

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#53828]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.73-6
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Yes, reproducible on both
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5320352
**Email or phone of affected tester (no customers):** fischer9966+120924aemp@gmail.com, fischer9966+120924aapp@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Create admin account with Gmail
2. Create Collect workspace, set Workflows to enabled
3. Invite Employee and Approver with Gmail accounts to this workspace
4. Enable Approvals in Workflows and set Approver account as Approver
5. Enable Workflows > Delay submissions and set it to Manually
6. Login as the employee and submit a report to Approver
7. Login as Approver and check LHN

## Expected Result:
Workspace chat is in UNREAD status (bold font) because of the expense submitted

## Actual Result:
Workspace chat in LHN with new report is shown as READ (not bold font) for Approver/Admin

## Workaround:
Unknown

## Platforms:
- [x] Android: Standalone
- [x] Android: HybridApp
- [x] Android: mWeb Chrome
- [x] iOS: Standalone
- [x] iOS: HybridApp
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/b9bfef14-23e2-49e4-8ef7-0a73f08cf789

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by JmillsExpensify** [comment]
This is not a bug and is by design.
