### ISSUE TITLE
Android - Concierge - Backward and forward button in video behaves differently

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#53829]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** V9. 0.73-6
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Yes, reproducible on both
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N
**Email or phone of affected tester (no customers):** N
**Issue reported by:** Applause Internal Team

## Action Performed:
Pre-condition: login new gmail account using track and budget expense
1. Launch app
2. Tap concierge
3. Tap video and expand to full screen
4. Keep video at start and tap forward button until it goes to end of video
5. Note at 2 pauses to goes to end of video
6. Now keep video at end and tap backward button until it goes to start of video
7. Note at 4 pauses it goes to start of the video

## Expected Result:
Backward and forward button in video must not behave differently in concierge video.

## Actual Result:
Tapping backward button , at 4 pauses it goes to start of video but on tapping forward button in 2 pauses it goes to end of video.

## Workaround:
Unknown

## Platforms:
- [x] Android: Standalone
- [x] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/3f65e7d8-e899-4de8-9f8c-f7bea14002c7

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by MitchExpensify** [comment]
This is not worth fixing right now
