### ISSUE TITLE
QBD - The selected vendor changes its place in the list after the selection

### ISSUE THREAD

**Issue by vincdargento** [Expensify/App#53887]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.73-6
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/cases/view/3284955
**Email or phone of affected tester (no customers):** applausetester+aguti.ha1410@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
Precondition
Use the following account: applausetester+aguti.ha1410@applause.expensifail.com. It has a workspace with QBD connected and several vendors.

Steps
1. Navigate to Accounting
2. Click on Export
3. Click on "Export company card expenses as"
4. Click Export as and select Vendor bill
5. Enable Default vendor toggle
6. Open the list of vendors
7. Select "Credit Card Misc." and any other vendor by waiting between every selection until the sync is complete

## Expected Result:
The selected vendor keeps its place in the list after the selection.

## Actual Result:
The selected vendor changes its place in the list after the selection. Sometimes it can be observed how the list of vendors changes their order when the list is opened, and the Default vendor field flickers between the previously selected vendor and the current one.

## Workaround:
Unknown

## Platforms:
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/44713ac2-f634-4571-8678-65a9173ffab4

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by garrettmknight** [comment]
I don't think there's any harm in this even if it's slightly unexpected.
