### ISSUE TITLE
Copilot - "These members can access..." does not disappear instantly after removing copilot

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#53919]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.74-0
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Yes, reproducible on both
**If this was caught during regression testing, add the test name, ID and link from TestRail:** Exp
**Email or phone of affected tester (no customers):** applausetester+kh1311020@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
Precondition:
- User has added a copilot.

1. Go to staging.new.expensify.com
2. Go to Account settings > Security.
3. Click on the copilot.
4. Click Remove copilot.
5. Remove the copilot.

## Expected Result:
"These members can access your account" will disappear instantly after removing copilot.

## Actual Result:
"These members can access your account" does not disappear instantly after removing copilot.

## Workaround:
Unknown

## Platforms:
- [x] Android: Standalone
- [x] Android: HybridApp
- [x] Android: mWeb Chrome
- [x] iOS: Standalone
- [x] iOS: HybridApp
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/4e5a0ef1-8f95-40c2-9c50-abc710d5900b

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by sakluger** [comment]
I'm going to close this bug actually. It is a fairly uncommon action and I can't imagine the 1-2 second delay causing much user confusion.
