### ISSUE TITLE
[HOLD for payment 2024-12-30] [$250] Fix OldDot invoice title in NewDot

### ISSUE THREAD

**Issue by cristipaval** [Expensify/App#53914]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:**
**Reproducible in production?:**
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @shawnborton 
**Slack conversation** (hyperlinked to channel name):

## Action Performed:
1. Create an invoice in OldDot
2. Open the invoice in NewDot

## Expected Result:
The invoice title should be the same in the header of the invoice report page, in the RHN, and when it is edited. It should be the same as in OldDot.

## Actual Result:
The report title is not correct in the report page header, and the RHN.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>

<img width="1247" alt="Screenshot 2024-12-11 at 13 05 48" src="https://github.com/user-attachments/assets/c91867a6-4d23-4934-b98e-5b88fecbb32d">

  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021866802844168681142</li>
        <li>Upwork Job ID: 1866802844168681142</li>
        <li>Last Price Increase: 2024-12-11</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @alexpensify</details>

**Comment by rezkiy37** [comment]
Hi, I am Michael (Mykhailo) from Callstack, an expert agency and I can work on this issue.

**Comment by twisterdotcom** [comment]
@rezkiy37 do you want to take fixing the ability to edit too as we have in https://github.com/Expensify/App/issues/53694?

**Comment by rezkiy37** [comment]
@twisterdotcom, yes I do. These issues have the same root cause.

**Comment by alexpensify** [comment]
Payment due date: 2024-12-30

Contributor: @rezkiy37 contractor 
Contributor+: @dukenv0307 owed $250 via NewDot

--- 

@dukenv0307, please submit a request in Chat. Since I'm out of the office until January 3, I'll close and work on the QA step when I'm back online.

**Comment by alexpensify** [comment]
@dukenv0307, after looking over this one more, I think it's a duplicate of https://github.com/Expensify/App/issues/53694. Can you please confirm if a payment is due here or if there is another PR other than https://github.com/Expensify/App/pull/54031? Thanks!
