### ISSUE TITLE
mWeb - Expense -Title text moves left to right on tapping back arrow

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#53912]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** V9. 0.74-0
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/home
2. Open a workspace chat with few expenses
3. Open the expense report
4. Tap header - title 
5. Paste https://staging.new.expensify.com/r/2348509720956985 and save it
6. Tap on title and then tap on top left arrow and go back
7. While performing step 6, note the text in title field.

## Expected Result:
In expense report title page, the text must not move left to right on tapping back arrow on top left.

## Actual Result:
In expense report title page, the text moves left to right on tapping back arrow on top left.

## Workaround:
Unknown

## Platforms:
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/74aa3f9c-4236-494b-a01d-1180fb1381c4

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by stephanieelliott** [comment]
Hey @IuliiaHerets can you point to the timestamp in the video where the bug is happening? I'm not seeing any weird behavior here

**Comment by truph01** [comment]
@stephanieelliott Around the 18th second in the video, you can try it

**Comment by stephanieelliott** [comment]
This is a minor display display issue it's hardly noticeable. I am gonna close this but will add the 'Not a Priority` label in case we want to address it later.
