### ISSUE TITLE
Android - Attachment-Download dialog box is displayed in dark theme

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#53925]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** V9. 0.74-0
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Yes, reproducible on both
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N
**Email or phone of affected tester (no customers):** N
**Issue reported by:** Applause Internal Team

## Action Performed:
Pre-condition: Open app in light theme
1. Launch app
2. Open a  chat with attachment
3. Open the attachment
4. Tap download on top right
5. Note the download dialog box

## Expected Result:
Download dialog box must not be displayed in dark theme.

## Actual Result:
Download dialog box is displayed in dark theme.

## Workaround:
Unknown

## Platforms:
- [x] Android: Standalone
- [x] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

![Bug6690696_1733905381038!Screenshot_2024-12-11-13-48-33-067_org me mobiexpensifyg-edit](https://github.com/user-attachments/assets/415e01f7-0f52-437a-873b-4f3c12fd7044)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by joekaufmanexpensify** [comment]
I can reproduce this, but I think this is a native android modal, rather than something we control. If you look at the top of the overlay, you see the native device icons, which aren't something we do/could add. I also verified iOS uses a native download confirmation here, so that tracks too. 

<img width="297" alt="image" src="https://github.com/user-attachments/assets/b406c09b-462f-4fc6-abd5-a963796982e1" />

**Comment by joekaufmanexpensify** [comment]
Closing as I don't think this is something we control in the app.
