### ISSUE TITLE
Unable to pass Onfido on web with Washington State Driver's License

### ISSUE THREAD

**Issue by marcaaron** [Expensify/App#5395]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go through VBA flow and upload driver's license

## Expected Result:
1. Onfido accepts the driver's license

## Actual Result:
1. And error pops up about the document not being detected.

## Workaround:
1. Must pass Onfido via OldDot

## Platform:
- Web
- Desktop App
- Mobile Web

**Version Number:**
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by marcaaron** [comment]
It would be good to have someone test if this is affecting all state driver's licenses and not just my own 

cc @kevinksullivan if this is broken for everyone then I'd _think_ this would be a blocker.

**Comment by kevinksullivan** [comment]
Not sure why botify closed, but FWIW we've had a lot of successful adds of driver's licenses. Will keep an eye on this as we continue testing though.

**Comment by marcaaron** [comment]
Because the linked PR was deployed to staging I think.
