### ISSUE TITLE
Concierge - No GBR for Concierge tasks until navigating for the second login

### ISSUE THREAD

**Issue by vincdargento** [Expensify/App#53950]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.74-0
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** testpayment935+789@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Navigate to https://staging.new.expensify.com
2. Login with new account - use any onboarding purposes except "Something else option"
3. Navigate to concierge and notice there is a GBR for each tasks and LHN of the concierge 
4. Without completing anything log out and log in again with the same account
5. Notice GBR in LHN but no GBR for the concierge tasks until navigating to each tasks

## Expected Result:
Until completing tasks, there is GBR for each concierge tasks and LHN in concierge chat.
User can click the box for completing the task in the concierge chat without navigating to the task detail

## Actual Result:
GBR in concierge tasks are disappeared for the second login until navigating to each tasks
User can't complete the task in the concierge chat

## Workaround:
Unknown

## Platforms:
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/bae4001e-c411-4060-9f61-bfcc20d60371

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by RachCHopkins** [comment]
I don't have any checklist _at all_. Even when I specifically click Start a Free Trial and then Complete your Setup Checklist

![image](https://github.com/user-attachments/assets/484d3396-937e-4660-99da-d45562821d6f)

**Comment by RachCHopkins** [comment]
I don't get the GBR problem, but I do get the inability to check off a task without clicking into it - are we sure this is not deliberate? Will check.

**Comment by RachCHopkins** [comment]
Checking in [Slack](https://expensify.slack.com/archives/C07HPDRELLD/p1734400391190059).

**Comment by RachCHopkins** [comment]
Bumped in Slack.

**Comment by RachCHopkins** [comment]
No response in slack, so I'll have to assume this is intentional.
