### ISSUE TITLE
[$250] Search - Individual expenses displays "Submit"/"Approve" button when the expenses are grouped

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#53986]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.75-0
**Reproducible in staging?:** Yes
**Reproducible in production?:** No
**If this was caught during regression testing, add the test name, ID and link from TestRail:** Exp
**Email or phone of affected tester (no customers):** applausetester+kh1311020@applause.expensifail.com
**Issue reported by:** Applause Internal Team
**Device used:** Mac 15.0 / Chrome
**App Component:** Search

## Action Performed:
Precondition:
- Delayed submission is enabled.
- Add approvals is enabled.

1. Go to staging.new.expensify.com
2. Go to workspace chat.
3. Submit two expenses to the workspace chat.
4. Go to Search > Draft.
5. Click Submit button on the individual expense (not the button next to report title).
6. Click the Submit button next to report title.
7. Click Approve button on the individual expense.

## Expected Result:
There should be only one "Submit/Approve" button on the group expenses. 
The individual expenses should display "view" button under the report title (production behavior).

## Actual Result:
The individual expenses display "Submit"/"Approve" button when the expenses are grouped expenses.
Clicking on the buttonon the individual expense opens expense RHP instead of submitting/approving.

The same issue also happens with "Pay" button.

## Workaround:
Unknown

## Platforms:
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/d8fcfcdb-aeee-41db-9973-39dc3005709f

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021867228840223993009</li>
        <li>Upwork Job ID: 1867228840223993009</li>
        <li>Last Price Increase: 2024-12-12</li>
<li>Automatic offers: </li>
<ul>
<li>ishpaul777 | Reviewer | 105308742</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

**Comment by IuliiaHerets** [comment]
Production has a different behavior

https://github.com/user-attachments/assets/66ba0449-884d-4ad4-a925-b91fd36fe618

**Comment by mountiny** [comment]
cc @lakchote @luacmartins @ishpaul777 seems like this is coming from here https://github.com/Expensify/App/pull/53641

**Comment by luacmartins** [comment]
I can take this one

**Comment by mountiny** [comment]
The PR is being reviewed by a C+

**Comment by mountiny** [comment]
PR reverted, we can close once checked in staging

**Comment by luacmartins** [comment]
Fixed in staging
