### ISSUE TITLE
[HOLD for payment 2024-12-20] [$250] Expense - Merchant error message is not cleared after completing the field properly

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#53991]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.75-0
**Reproducible in staging?:** Yes
**Reproducible in production?:** No
**Email or phone of affected tester (no customers):** ibellicotest+91@gmail.com
**Issue reported by:** Applause Internal Team
**Device used:** Motorola MotoG60 - Android 12 - Chrome / Windows 10 - Chrome
**App Component:** Money Requests

## Action Performed:
1. Open the staging.new.expensify.com website.
2. Tap on the FAB and select "Create Expense"
3. Complete with any amount and tap on "Next"
4. Select any workspace and try to submit the expense without any merchant.
5. When the error message is displayed, complete the merchant field with valid information.
6. Try to submit expense again.

## Expected Result:
User should be able to submit the expense after completing the merchant field and fixing the error.

## Actual Result:
After the user tries to submit an expense to a workspace without merchant, the displayed error message remains despite the field being completed. User is not able to submit the expense after the error is displayed.

## Workaround:
Unknown

## Platforms:
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/79bd685d-3ec3-49e4-9b4c-7cbba1cb9f4e

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021867142072270891331</li>
        <li>Upwork Job ID: 1867142072270891331</li>
        <li>Last Price Increase: 2024-12-12</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @joekaufmanexpensify</details>

**Comment by rojiphil** [comment]
> I can raise the quick PR if my proposal is correct

@dominictb [proposal's](https://github.com/Expensify/App/issues/53991#issuecomment-2538593289) RCA and solution makes sense to me. I think we can go ahead with the PR. 
@Gonals @joekaufmanexpensify what do you think?

**Comment by joekaufmanexpensify** [comment]
Defer to @Gonals on the solution. If he's good, good with me!

**Comment by Gonals** [comment]
Sounds good to me too. We are going with @paultsimura's solution, then, @rojiphil?

**Comment by joekaufmanexpensify** [comment]
Sounds good to me to have @Pujan92 review if this is a follow up from another issue

**Comment by luacmartins** [comment]
Fixed in staging

**Comment by joekaufmanexpensify** [comment]
PR is merged

**Comment by joekaufmanexpensify** [comment]
PR is out on prod. There isn't any payment to be issued here. This issue was a regression from https://github.com/Expensify/App/pull/51517 , which originally came from https://github.com/Expensify/App/issues/46897. All payment will be handled here. 

Going to close this for now, but LMK if anyone has questions on that!
