### ISSUE TITLE
[$250]  Login - Onboarding flow is dismissed before selecting accounting software.

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#53999]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.75-0
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**Email or phone of affected tester (no customers):** gibethlehem@gmail.com
**Issue reported by:** Applause Internal Team
**Device used:** macOS/chrome
**App Component:** Other

## Action Performed:
1. Create a new user
2. "What do you want to do today?" modal appears > Select the option "Manage my team's expenses"
3. Choose number of employees > click continue

## Expected Result:
accounting software modal is displayed and able to choose accounting software

## Actual Result:
Onboarding flow is dismissed before selecting accounting software.

## Workaround:
Unknown

## Platforms:
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/a73ee543-eee9-426c-93a5-37ae6a592569

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021867244068382506844</li>
        <li>Upwork Job ID: 1867244068382506844</li>
        <li>Last Price Increase: 2024-12-12</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @francoisl</details>

**Comment by c3024** [comment]
I can repro this on production too.

https://github.com/user-attachments/assets/5285c8e6-8b1b-47f0-bd2f-d94d5306ad78


Does not seem to be related to #53661.

**Comment by francoisl** [comment]
This is a backend issue sorry, we're working on it now.

**Comment by francoisl** [comment]
This is fixed.
