### ISSUE TITLE
 Expense - Distance rate is reset when editing distance in a distance track expense

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#54004]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.75-0
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**Email or phone of affected tester (no customers):** ibellicotest+91@gmail.com
**Issue reported by:** Applause Internal Team
**Device used:** Motorola MotoG60 - Android 12 - Chrome / Windows 10 - Chrome
**App Component:** Money Requests

## Action Performed:
1. Open the staging.new.expensify.com website.
2. Open self DM.
3. Tap on the "+" button and select "Track Expense"
4. Select distance and complete the creation flow.
5. Once redirected to chat, tap on "Categorize it"
6. Select any category.
7. Add a merchant.
8. Submit the expense to any workspace.
9. Change the distance rate to be able to send it to workspace.
10. Open the expense report and tap on "Distance"
11. Change any waypoint so the distance and amount are updated.

## Expected Result:
After changing the distance of a categorized track expense, the distance rate should remain the same that the user selected when submitting it.

## Actual Result:
Distance rate gets reseted and user has to change it again after the distance of the categorized track expense is edited when submitted to a workspace.

## Workaround:
Unknown

## Platforms:
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/4b15b69b-5426-4c77-93c4-ef5c8b6e89c8

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by RachCHopkins** [comment]
Instructions are overly complex and don't appear to reflect reality. There is no merchant on a distance expense. There is no way following this, to not-send it to a workspace immediately, because that's what the Categorise it action does. 

There's definitely something funky happening with the distance travelled, but that's not covered here.
