### ISSUE TITLE
Accounting - Menu items are briefly shown after disconnect

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#54026]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.75-0
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/cases/view/3073350
**Email or phone of affected tester (no customers):** -
**Issue reported by:** Applause Internal Team
**Device used:** MacOS Catalina 10.15.7
**App Component:** Other

## Action Performed:
Precondition: workspace with enabled accounting. Connection (e.g. NetSuite) established.

1. Go to WS > Accounting
2. Click on three dots near connection > Disconnect

## Expected Result:
Disconnection should remove the integration from the workspace.

## Actual Result:
Disconnection remove the integration from the workspace, but menu items are briefly appeared again.

## Workaround:
Unknown

## Platforms:
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/19a32837-fd40-4800-ad60-ed2af1c20b22

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by stephanieelliott** [comment]
I think this is low value and pretty minor, seeing as it doesn't look especially buggy and doesn't affect functionality. Going to close as `Not a priority` for now
