### ISSUE TITLE
Android - Chat - User lands on inbox for a second when returning from a search to chat

### ISSUE THREAD

**Issue by vincdargento** [Expensify/App#54047]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.75-0
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** No, reproducible on hybrid only
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5338694&group_by=cases:section_id&group_order=asc&group_id=296775
**Email or phone of affected tester (no customers):** ibellicotest+91@gmail.com
**Issue reported by:** Applause Internal Team
**Device used:** Motorola MotoG60 - Android 12
**App Component:** Other

## Action Performed:
1. Open the Expensify app.
2. Open any chat that already has messages on it.
3. Tap on the search icon on the top right corner.
4. Tap on "Search in this chat" button.
5. Write any search that will trigger results.
6. When navigated to the results, return to chat using the device back button.

## Expected Result:
When returning from a search to the conversation, the user should be automatically redirected to the chat.

## Actual Result:
User lands on inbox for a second, when returning from a search to a conversation using the device back button.

## Workaround:
Unknown

## Platforms:
- [ ] Android: Standalone
- [x] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/b7600b04-7847-4f5f-8291-8f87eaf40b3c

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by JmillsExpensify** [comment]
This is technically correct in my opinion, and ultimately it's so small that I am inclined to close this bug report.
