### ISSUE TITLE
[$250] Onboarding - Onboarding modal closes for manage expenses when arriving on accounting modal

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#54059]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.75-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://github.com/Expensify/App/pull/52803
**Email or phone of affected tester (no customers):** nathanmulugetatesting+2443@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Sign in with a new user
3. Select 'Manage my team's expenses' from the onboarding purpose
4. Select your team size

## Expected Result:
The modal to select accounting integration stays open

## Actual Result:
The modal to select accounting integration closes abruptly before user chooses an integration

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Standalone
- [x] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/eb07cb57-7bae-473d-9ab8-2152c96dea07

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021867535816080448386</li>
        <li>Upwork Job ID: 1867535816080448386</li>
        <li>Last Price Increase: 2024-12-13</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @fedirjh</details>

**Comment by afaayerhan** [comment]
can't reproduce

**Comment by MrMuzyk** [comment]
I am Michał from Callstack - expert contributor group. I’d like to work on this job.

**Comment by MrMuzyk** [comment]
I am unable to reproduce this issue - modal stays open. See the recording below

https://github.com/user-attachments/assets/e98d067d-9a96-44e9-b7c7-0128cba41ac1
