### ISSUE TITLE
Track distance - Selected rate is not preserved after returning to category list

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#54066]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.75-5
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+kh1311020@applause.expensifail.com
**Issue reported by:** Applause - Internal Team
**Component** Money Requests

## Action Performed:
Precondition:
- Account has a workspace.
- Workspace can have one or more distance rate.

1. Go to staging.new.expensify.com
2. Go to self DM
3. Track a distance expense
4. Click Categorize it
5. Select a category
6. Click Rate on the confirmation page
7. Select any rate
8. Click RHP back button
9. Select any category

## Expected Result:
When user has selected a workspace rate and returned to previous page to select a different category, the selected rate will not change (production behavior)

## Actual Result:
When user has selected a workspace rate and returned to previous page to select a different category, the rate reverts to the individual rate
This issue does not happen when user selects a different category directly on the confirmation page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Standalone
- [x] Android: HybridApp
- [x] Android: mWeb Chrome
- [x] iOS: Standalone
- [x] iOS: HybridApp
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/a6e69de9-2059-43fb-93e2-c55d69fe46c2

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by luacmartins** [comment]
Haha I was just gonna post that it's coming from that PR. I think I'll just revert it for now since there are 2 blockers associated with it already.

**Comment by luacmartins** [comment]
Fixed in staging
