### ISSUE TITLE
 QAB - No QAB after deleting workspace

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#54063]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.75-3
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/cases/view/2990375
**Issue reported by:**Applause - Internal Team
**Component** Left Hand Navigation (LHN)

## Action Performed:
Precondition: new account. User have one workspace.
1. FAB > submit manual expense to workspace
2. Delete workspace
3. Open FAB

## Expected Result:
Quick action section is present with a last action

## Actual Result:
QAB is not displayed in FAB

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/93a0c753-f13a-48d9-ae5c-89b6975d4e4b

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by tgolen** [comment]
Hm, I think this is expected behavior, isn't it? Since the workspace was deleted, we shouldn't show the QAB again because it would be non-functional.
