### ISSUE TITLE
Lint and Test Kotlin check fails for HybridApp PRs

### ISSUE THREAD

**Issue by arosiclair** [Expensify/App#54118]
**Version Number:** N/A
**Reproducible in staging?:** N/A
**Reproducible in production?:** N/A
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** N/A
**Logs:** N/A
**Expensify/Expensify Issue URL:** N/A
**Issue reported by:** @arosiclair
**Slack conversation** (hyperlinked to channel name): https://expensify.slack.com/archives/C03TQ48KC/p1734109683580439

## Action Performed:
Posted a [Mobile-Expensify PR](https://github.com/Expensify/Mobile-Expensify/pull/13324)

## Expected Result:
`Lint and Test Kotlin` passes

## Actual Result:
`Lint and Test Kotlin` fails with an unrelated error:

```
FAILURE: Build failed with an exception.

* Where:
Settings file '/home/runner/work/Mobile-Expensify/Mobile-Expensify/Android/settings.gradle' line: 2

* What went wrong:
Error resolving plugin [id: 'com.facebook.react.settings']
> Included build '/home/runner/work/Mobile-Expensify/node_modules/@react-native/gradle-plugin' does not exist.
```

https://github.com/Expensify/Mobile-Expensify/actions/runs/12319565150/job/34388423051?pr=13324

## Workaround:
None

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [x] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [x] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

None

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by arosiclair** [comment]
@staszekscp can you take a look at this error? It's blocking a couple of PRs. cc @AndrewGable

**Comment by AndrewGable** [comment]
I think we need to:

1. Checkout App
2. Clone the Mobile-Expensify submodule
3. cd into Mobile-Expensify submodule
4. Run the rest of the commands
