### ISSUE TITLE
Android - Chat - App crashes when opening emoji picker

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#54123]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.76-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+kh1311020@applause.expensifail.com
**Issue reported by:** Applause - Internal Team
**Component** Chat Report View

## Action Performed:
1. Launch ND or hybrid app
2. Open chat
3. Send a message
4. Tap on the composer to bring up keyboard if it is not opened (important)
5. Long press on the message
6. Tap Add reaction icon

## Expected Result:
App will not crash

## Actual Result:
App crashes

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Standalone
- [x] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/a9be003c-74b9-458e-9271-13426a5ae994

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by huult** [comment]
@rlinoz Due to this pr https://github.com/Expensify/App/pull/53806 . Can I open pull request to fix this issue?

**Comment by rlinoz** [comment]
Reverting https://github.com/Expensify/App/pull/53949 locally seems to fix it

**Comment by luacmartins** [comment]
We CPed a fix. Can we test this again please?

**Comment by rlinoz** [comment]
Tested and it is fixed
