### ISSUE TITLE
Desktop - No tooltip is shown

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#54127]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.76-0
**Reproducible in staging?:** Yes
**Reproducible in production?:** No
**Issue was found when executing this PR:** https://github.com/Expensify/App/pull/53396
**Email or phone of affected tester (no customers):** new gmail account
**Issue reported by:** Applause Internal Team
**Device used:** MacOS Catalina 10.15.7
**App Component:** Other

## Action Performed:
1. (Main device) Sign up with new Account. Completed Onboarding flow
2. (If you use desktop, resize screen to mobile size) verify Tooltip on Concierge is displayed
3.Create a workspace, go back and open FAB menu
4. Verify that a tooltip on QAB is visible
5. Go to search screen > Filters 
6. Add and save a filter, verify tooltip is shown on saved search threedot. (this is visible on desktop screen size only)
7. As another user (on second device) create a workspace > invite your account to the workspace
8. (Main device) Go the invited workspace chat verify tooltip on "+" is shown.

## Expected Result:
Tooltips are shown on step 2, 4, 6, 8

## Actual Result:
No tooltip is shown on step 2, 4, 6, 8

## Workaround:
Unknown

## Platforms:
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/fdf3ef02-f97d-4c54-9b3b-95c23befa10b

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by IuliiaHerets** [comment]
Production 

https://github.com/user-attachments/assets/2090bba3-f7e5-4aab-9a78-9e2cfb70aaa8

**Comment by joekaufmanexpensify** [comment]
Sounds good. Thinking that means there isn't actually a bug here?

**Comment by joekaufmanexpensify** [comment]
Cool cool. Going to close this one out then. TY!
