### ISSUE TITLE
Onboarding - No onboarding modal when signing in with a new account

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#54126]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.76-0
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** htad26+djfhdjkg@gmail.com
**Issue reported by:** Applause Internal Team
**Device used:** Windows 10/Chrome, mWeb/Chrome
**App Component:** Other

## Action Performed:
1. Navigate to new dot app
2. Log in with a new Gmail account

## Expected Result:
Onboarding modal shows up

## Actual Result:
No onboarding modal when signing in with a new account

## Workaround:
Unknown

## Platforms:
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/276a18be-9b0d-42de-a872-78fc573a71a1

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Shahidullah-Muffakir** [comment]
Same as https://github.com/Expensify/App/issues/53724#issuecomment-2542042148, I am working on the PR.

**Comment by jliexpensify** [comment]
Seems like this will be solved as part of  https://github.com/Expensify/App/issues/53724#issuecomment-2542042148

**Comment by jliexpensify** [comment]
@carlosmiceli not sure if you want to monitor this as well?

**Comment by carlosmiceli** [comment]
@jliexpensify yeah, totally, thanks!

**Comment by jliexpensify** [comment]
Cool! Just as a heads up, I've made this a `weekly` so we aren't consistently pinged. @carlosmiceli do you mind adding this to a project too?

I'll also be OOO from 19th-29th December, but I'm guessing you'll close this when the other PR is deployed? No payments needed right?

**Comment by carlosmiceli** [comment]
Yeah, exactly, I'll close it then 👍

**Comment by jliexpensify** [comment]
Perfect, ty!

**Comment by carlosmiceli** [comment]
Closing since this was fixed by another issue's PR.
