### ISSUE TITLE
Android HybridApp SAML is not working with a `Cancelled SAML Sign in` error

### ISSUE THREAD

**Issue by AndrewGable** [Expensify/App#54145]
## Problem

In the latest production version of Android HybridApp multiple users are reporting seeing an error of `Cancelled SAML Sign in`

https://github.com/user-attachments/assets/88610bfd-c213-4564-9fd1-0eb99338e10e

----

@cead22 and I think it might be related to this PR: https://github.com/Expensify/Mobile-Expensify/pull/13288, when we tried to revert it we got tangled up with https://github.com/Expensify/Mobile-Expensify/pull/13309 and were not able to confirm whether reverting this PR fixes the issue.

We know that the error was introduced between HybridApp versions 9.0.55.8 and 9.0.76.0

Here is the diff for those changes: https://github.com/Expensify/Mobile-Expensify/compare/a831d917e8fc26ed5aa27ff1fdb4e3c4683abf72...a025eb26f81edd55baa026ad7c3d4373f4fb80e8

## Solution

When signing in with andrew@expensifail.com and hitting "Single Sign On" you should be redirected to OneLogin, instead of seeing the `Cancelled SAML Sign in` error.

https://github.com/user-attachments/assets/ec225afa-d0fa-471a-b2db-165bbe59dc1c

cc @war-in @staszekscp

**Comment by AndrewGable** [comment]
1. Here https://github.com/Expensify/Mobile-Expensify/pull/13332 is where we tried to revert https://github.com/Expensify/Mobile-Expensify/pull/13288
2. Here https://github.com/Expensify/Mobile-Expensify/pull/13334 is where we reverted that attempt and tried to get everything back to `main`.

**Comment by AndrewGable** [comment]
Yes, I just checked and the issue still seems to persist on the latest TestFlight: 9.0.76-3. This seems up to date with `main` (other than our failed reverts) so it seems like maybe there is a difference between `main` and the staging/production environments causing this?




https://github.com/user-attachments/assets/44256841-89f8-4d5b-94ed-d13be15df2d8

**Comment by AndrewGable** [comment]
Confirmed this was fixed by the linked PR on version 9.0.76-7




https://github.com/user-attachments/assets/5bcd79cf-c407-419b-aae5-da9bbadaada9

**Comment by oaktowner** [comment]
Sorry for the intrusion, but do you have any idea how long it will be until this makes it to the Play store? I'm getting 9.0.75.6 there (and waiting for the new one so I can finish an expense report!). (Pixel 9, Android 15)

**Comment by AndrewGable** [comment]
No worries @oaktowner! We are looking at a different crash: https://github.com/Expensify/App/issues/54169 but hoping to have it resolved today and will begin a slow rollout.

---

If this isn't fast enough for your expense report:

* [This is the APK from Google Play](https://drive.google.com/file/d/1ItBMIzHqJYvtqakhdKGNCpWb8LxrjqY3/view?usp=sharing) if you want to install it manually (just make sure to uninstall or you won't get auto updates)
* This release has the aab file attached: https://github.com/Expensify/App/releases/tag/9.0.76-7 and has the fix as seen above.

**Comment by oaktowner** [comment]
wow. thank you so much!

**Comment by mateuuszzzzz** [comment]
Hi @AndrewGable, what is your OS version and device model? We’re investigating why the deeplinks PR might be causing issues, and our current hypothesis suggests that only certain devices or Android versions are affected.

**Comment by AndrewGable** [comment]
Pixel 7A, Android 14

**Comment by mateuuszzzzz** [comment]
We reproduced the issue on physical Pixel 7A

**Comment by mateuuszzzzz** [comment]
Ok it seems like our office Pixel 7A didn't have browser installed. After installation bug is not reproducible anymore. The only thing that comes to my mind to at least understand better the root cause of this issue is to add better logs [here](https://github.com/Expensify/Mobile-Expensify/blob/ea3433a5e6356e04b5f7b906d7b49908b4e34d6d/Android/src/yapl/android/managers/ChromeCustomTabsManager.java#L174)  and [here](https://github.com/Expensify/Mobile-Expensify/blob/ea3433a5e6356e04b5f7b906d7b49908b4e34d6d/Android/src/yapl/android/managers/ChromeCustomTabsManager.java#L192) 

Currently we don't know if the issue is related to intent that is `null` or to contents of intent that are in wrong format.

**Comment by AndrewGable** [comment]
Sounds good, happy to help test.

**Comment by mateuuszzzzz** [comment]
> Sounds good, happy to help test.

Cool! I will try to prepare PR with better logs today
