### ISSUE TITLE
Invoices - Not here page opens when opening invoice room from the deleted workspace

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#54171]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.76-6
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Yes, reproducible on both
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5343700
**Email or phone of affected tester (no customers):** applausetester+239230292903@applause.expensifail.com
**Issue reported by:** Applause Internal Team
**Device used:** Mac 15.0 / Chrome
**App Component:** Money Requests

## Action Performed:
1. Go to staging.new.expensify.com
2. Create a new workspace and enable Invoices in More features page.
3. Go to FAB > Send invoice.
4. Send an invoice to anyone.
5. Create a second workspace and enable Invoices in More features page.
6. Go to FAB > Send invoice.
7. Send an invoice to the same person in Step 4, but from the second workpsace created in Step 5.
8. Delete the second workspace in Step 5.
9. Go back to Inbox.
10. Open the invoice room created in Step 7.

## Expected Result:
The invoice room from the deleted workspace will open without issue.

## Actual Result:
Not here page opens when opening invoice room from the deleted workspace

## Workaround:
Unknown

## Platforms:
- [x] Android: Standalone
- [x] Android: HybridApp
- [x] Android: mWeb Chrome
- [x] iOS: Standalone
- [x] iOS: HybridApp
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/312747ee-201e-4344-8e47-e88f8885251f

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Tony-MK** [comment]
I believe this needs to be handled internally.

The `openReport` request responds with a `errorFields.notFound` error.

![OpenReport Response](https://github.com/user-attachments/assets/1bc1bd8a-a517-4677-9fd1-8ed53e78c074)

**Comment by stephanieelliott** [comment]
This seems edge case, given that it's exclusive to deleted workspaces. I am gonna close this but will add the 'Not a Priority` label in case we want to address it later.
