### ISSUE TITLE
[$250] Clicking back button on room description brings you to room details

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#54225]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.76-6
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @hannojg 
**Slack conversation** (hyperlinked to channel name): [expensify_bugs](https://expensify.slack.com/archives/C049HHMV9SM/p1734184593153329)

## Action Performed:

1. Open a room
2. Click on the rooms description in the header (not the title)
3. Room description page opens
4. Click on the back Button

## Expected Result:
Clicking back returns to the chat
## Actual Result:
The detail page is opening
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [x] iOS: Standalone
- [x] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details>

https://github.com/user-attachments/assets/8bd7106d-8bfc-4022-b7db-6e9911fc279b

https://github.com/user-attachments/assets/989e283d-6102-4252-8a1f-4d59e8348ceb

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021869469066764366882</li>
        <li>Upwork Job ID: 1869469066764366882</li>
        <li>Last Price Increase: 2024-12-18</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @ntdiary</details>

**Comment by FitseTLT** [comment]
> The default fallback is useful to cover this case:
> 
> 1. Open a room
> 2. Press the header
> 3. Press the description field
> 4. Refresh
> 5. Go back
> 
> Without the default, it will simply close the RHP instead of going back to the details page.

No @bernhardoj the backTo is already in the route so we still don't need it there

https://github.com/user-attachments/assets/d62d38cb-c864-48c9-b4e4-dcec5fd7016d

**Comment by bernhardoj** [comment]
Oh, you're right. Then it's just to handle the case if the user directly access the description page (either deeplink, tying the url, open the link from chat, etc.).

**Comment by FitseTLT** [comment]
> Oh, you're right. Then it's just to handle the case if the user directly access the description page (either deeplink, tying the url, open the link from chat, etc.).

But in that case, the user won't expect to be navigated back to the details page as we don't always navigate to the description page via the details page. For instance, there is a case they can directly navigate from chat by directly clicking the room description on the header as in this issue case. I think it would be more intuitive to close the RHP in this case.

**Comment by bernhardoj** [comment]
I think that makes sense, but it's up to the team.

**Comment by cead22** [comment]
I agree with @FitseTLT, but before I assign, can you check if this is a regression? I believe this used to work fine at some point, right?

**Comment by FitseTLT** [comment]
REPORT_DESCRIPTION page previously can only be opened from the details page so this issue could not arise the issue is only reproducible when opened directly from header view. Maybe that's the reason.

**Comment by cead22** [comment]
It sounds like @ntdiary is right and Adam Grzybowski agrees, that this is working like it should
