### ISSUE TITLE
Expense - Expense status sentence is larger than held status sentence

### ISSUE THREAD

**Issue by vincdargento** [Expensify/App#54304]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.77-0
**Reproducible in staging?:** Yes
**Reproducible in production?:** No
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+7909707@applause.expensifail.com
**Issue reported by:** Applause Internal Team
**Device used:** Mac 15.0 / Chrome
**App Component:** Money Requests

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace chat.
3. Submit an expense.
4. Click on the expense preview.
5. Note that the expense status sentence "Waiting for You to approve expense(s)." is big.
6. Click on the report header.
7. Click Hold.
8. Enter a reason and save it.
9. Note that the held message is not as big.

## Expected Result:
In Step 5 and 9, there should be consistency in font size in expense status and held status.

## Actual Result:
In Step 5, the expense status sentence "Waiting for You to approve expense(s)." is bigger than the held message in Step 9.

## Workaround:
Unknown

## Platforms:
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/e97f6daa-768c-4550-aa9a-a781420a2f3e

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by vincdargento** [comment]
@lschurr FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by luacmartins** [comment]
This was fixed by https://github.com/Expensify/App/issues/54304
