### ISSUE TITLE
Chat - Cmd + Shift+ K shows small Lag on Expensifail Domain accounts

### ISSUE THREAD

**Issue by vincdargento** [Expensify/App#54324]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.77-0
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+en@applause.expensifail.com
**Issue reported by:** Applause Internal Team
**Device used:** Macbook Pro 2023 / Sonoma 14.4.1
**App Component:** Chat Report View

## Action Performed:
1. Access staging.new.expensify.com
2. Sign into a valid Expensifail account (HT)
3. Click on CMD+SHIFT+K

## Expected Result:
User expects the Start chat modal to open/close smoothly

## Actual Result:
On Expensifail accounts, it opens with a slight delay. Does NOT repro on regular gmail accounts. Lag also happens when the Modal is closed

## Workaround:
Unknown

## Platforms:
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/7d659e37-9c0e-4aa2-a274-e65012823c79

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by RachCHopkins** [comment]
@vincdargento can you give me a little insight here? Why would we fix something for Expensifail? That domain is enormous with 7974 domain members and doesn't behave normally at all. 

Can I geet some insight into why this is something to be fixed, please?
