### ISSUE TITLE
LHN - Personal DM is not being created when signing up with a new Gmail account

### ISSUE THREAD

**Issue by mitarachim** [Expensify/App#54345]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.77-0
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:** Exp
**Email or phone of affected tester (no customers):** nathanmulugetatesting+2494@gmail.com
**Issue reported by:** Applause Internal Team
**Device used:** Windows 11 pro/chrome
**App Component:** Left Hand Navigation (LHN)

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Sign out if you're already signed in
3. Sign in with a new account
4. Search the account you have signed in with in the router

## Expected Result:
There's a personal DM pinned in the LHN

## Actual Result:
There's no personal DM pinned in the LHN and can not be found when searched using the router

## Workaround:
Unknown

## Platforms:
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/51abbe88-bda4-4fbe-96e8-4a203481d62c

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Shahidullah-Muffakir** [comment]
I believe solving https://github.com/Expensify/App/issues/54322#issuecomment-2552908792 will solve the current issue as well.
