### ISSUE TITLE
Custom feed card name retained after deleting the pending card and readding new

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#54367]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:** 
**Reproducible in production?:**
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @joekaufmanexpensify 
**Slack conversation** (hyperlinked to channel name): [expense](https://expensify.slack.com/archives/C06ML6X0W9L/p1734560474214649)

## Action Performed:
Prerequisite: User added a company card and in pending state

1. Navigate to Company card
2. Click Settings > Remove card feed
3. Add a card again by custom feed

## Expected Result:
A new feed of the same type not to retain the old feed

## Actual Result:
Custom feed card name retained after deleting the pending card and readding new

## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details>

https://github.com/user-attachments/assets/1e71f1b8-37af-4a1c-9f4a-33df8b21aa94

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @mountiny</details>

**Comment by twisterdotcom** [comment]
Is this assigned to @mountiny because he will fix it, or can I make this external? cc @joekaufmanexpensify.

**Comment by twisterdotcom** [comment]
Do we need a C+ for review?

**Comment by mountiny** [comment]
This is just backend fix

**Comment by joekaufmanexpensify** [comment]
TY!

**Comment by mountiny** [comment]
PR is up https://github.com/Expensify/Auth/pull/13612

**Comment by mountiny** [comment]
We can close this one now
