### ISSUE TITLE
[HOLD for payment 2025-01-02] Option to change the card-level export account type with Xero, even though bank accounts is the only option supported

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#54372]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:**
**Reproducible in production?:**
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @joekaufmanexpensify 
**Slack conversation** (hyperlinked to channel name): [expense](https://expensify.slack.com/archives/C06ML6X0W9L/p1734560547677399)

## Action Performed:
Prerequisite: User added a company card

1. Navigate to company card
2. Click the added cards to view the details page
3. Click Xero bank account export option

## Expected Result:
No other options as only bank accounts are supported 

## Actual Result:
Option to change the card level export account type is displayed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details>

![image - 2024-12-18T172231 584](https://github.com/user-attachments/assets/fcffc58f-e565-43c7-ac31-6332b56b9d4c)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @OfstadC</details>

**Comment by narefyev91** [comment]
Hi, I’m Nicolay from Callstack and I would like to investigate this issue.

**Comment by mountiny** [comment]
I dont think we need the test for this one and we will handle payments in bulk, so we can close now. Thanks everyone!
