### ISSUE TITLE
Web - Scan – RBR is not displayed in LHN when editing an amount to be higher than the scan

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#54381]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.77-4
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. As the employee navigate to the workspace chat
2. Click on + icon > Submit expense > Scan
3. Upload a digital receipt > Submit > Wait for the smart scan to be completed
4. Once the smart scan is finished navigate to the expense details
5. Click on the amount > edit the amount to be higher than the scanned amount > Save
Notice that after a while a violation is displayed indicating the amount is higher than the scanned receipt
Now observe the LHN of the workspace chat

## Expected Result:
RBR is displayed in the expense and LHN

## Actual Result:
RBR is not displayed in LHN

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/0ccde504-0c00-45ac-a48e-09e5a9670c18

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by FitseTLT** [comment]
@trjExpensify this is expected. Tagging @JmillsExpensify

**Comment by s77rt** [comment]
No, this is not expected. The RBR should appear on the **workspace chat** LHN.

**Comment by trjExpensify** [comment]
^^ agree with that.

**Comment by FitseTLT** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Web - Scan – RBR is not displayed in LHN when editing an amount to be higher than the scan

### What is the root cause of that problem?
We are missing the notice type violation here
https://github.com/Expensify/App/blob/582c6f14e2ae53fc4d12d355d37fa007d9796925/src/libs/ReportUtils.ts#L6420-L6422
### What changes do you think we should make in order to solve the problem?

we should also display notice type violations
```
return potentialReports.some(
        (potentialReport) =>
            hasNoticeTypeViolations(potentialReport.reportID, transactionViolations) ||
            hasViolations(potentialReport.reportID, transactionViolations) ||
            hasWarningTypeViolations(potentialReport.reportID, transactionViolations),
    );
```
### What specific scenarios should we cover in automated tests to prevent reintroducing this issue in the future?

Write a test for shouldDisplayViolationsRBRInLHN to assert that it returns true for notice type violations
### What alternative solutions did you explore? (Optional)

**Comment by JmillsExpensify** [comment]
For clarity, @FitseTLT is correct this is the intended design. Here's the relevant screenshot from the accompanying design doc. 

![CleanShot 2024-12-19 at 20 26 33@2x](https://github.com/user-attachments/assets/fb396921-51fc-48f9-bc21-d9753ae7de64)

**Comment by JmillsExpensify** [comment]
That said, I'm open to changing this if we find the intended design confusing.

**Comment by trjExpensify** [comment]
Mhm, gotcha. Yeah, it's pretty nuanced for someone to understand the difference using exactly the same style. S'all good though, no need to change that here and now.

**Comment by JmillsExpensify** [comment]
Cool, we can keep an eye on it. I tend to agree that this distinction is very subtle, so it might be worth undoing.
