### ISSUE TITLE
Update testrails so selfDM is only expected for users with "introSelected" for Track -- NVP: newDotPersonalSpend

### ISSUE THREAD

**Issue by danielrvidal** [Expensify/App#54417]
There have been a series of GHs we created that ultimately landed with us removing the SelfDM being pinned for users from everyone except user who go through a the Track onboarding flow and end up with a NVP: newDotPersonalSpend

More information here: https://github.com/Expensify/App/issues/53405

@isagoico @mvtglobally do you think you could make sure the test rails all get updated accordingly? It's not done yet, but we should update it when it goes live because I imagine it touches a couple of flows. 

Let me know if there are any questions!

**Comment by isagoico** [comment]
Updated the following TC to check that the self DM is pinned after selecting track on the onboarding flow: [Onboarding Flow - Track and budget expenses](https://expensify.testrail.io/index.php?/cases/view/2990435) and also this one to check that it's not pinned with the other options [Onboarding Flow - Chat and split expenses with friends](https://expensify.testrail.io/index.php?/cases/view/2990433)

Closing the issue, please reopen if needed.
