### ISSUE TITLE
Wallet - "phone number is not valid email address" error when activating card with phone number

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#54487]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**  9.0.78-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+909608@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition:
- Personal details are not filled
- User has been assigned a physical card
1. Go to staging.new.expensify.com
2. Go to Account settings > Wallet
3. Click on the physical card
4. Click Get physical card
5. Enter name > Next
6. On phone number page, enter a valid phone number from your country but without the country code
7. Proceed to confirmation page
8. Enter magic code
9. Note that the error message shows that it is not a valid email address when the phone number is used without country code and the code is valid
10. Go back to phone number page, and add a country code
11. Proceed to confirmation page
12. Enter magic code
13. Now there is no validation error when phone number with country code is used

## Expected Result:
In Step 9, on confirmation page, there should be no validation error for phone number without country code since we can enter phone number without country code in Step 6

## Actual Result:
In Step 9, on confirmation page, there is error for phone number without country code when we can enter phone number without country code in Step 6
Also, the validation error is incorrect as it says "phone number is not a valid email address"

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [x] iOS: HybridApp
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/a711da7d-3001-4c9b-a35b-d4ec5fff47b8

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by sobitneupane** [comment]
@NJ-2020 I can still reproduce the issue. But the error is different.

<img width="367" alt="Screenshot 2024-12-26 at 15 30 14" src="https://github.com/user-attachments/assets/5c059e3c-82fb-40ba-9e2a-1f680a737e39" />

**Comment by sobitneupane** [comment]
**Reproduction Step:**

1. Press on "Get a Physical Card" button
2. Enter the phone number. I entered an old, valid landline phone number. > Ship Card
3. Enter wrong magic code > Verify.

**Comment by jasperhuangg** [comment]
@NJ-2020 Can you finish your PR and get it ready for CP since this is still in your regression period?

**Comment by jasperhuangg** [comment]
We are reverting the original PR. It should solve the issue fully without introducing any other regressions.
