### ISSUE TITLE
 iOS - App briefly shows blank page when returning to LHN after opening DM from FAB

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#54505]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.78-0
**Reproducible in staging?:** Yes
**Reproducible in production?:** No
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:** Exp
**Email or phone of affected tester (no customers):** applausetester+909608@applause.expensifail.com
**Issue reported by:** Applause Internal Team
**Device used:** iPhone 15 Pro Max / iOS 18.2
**App Component:** Left Hand Navigation (LHN)

## Action Performed:
1. Launch ND or hybrid app.
2. Open FAB > Start chat.
3. Tap on any user.
4. Use device gesture to return to LHN.

## Expected Result:
App will not show blank page when returning to LHN after opening DM from FAB.

## Actual Result:
App briefly shows blank page when returning to LHN after opening DM from FAB.

## Workaround:
Unknown

## Platforms:
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [x] iOS: Standalone
- [x] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/a5c74af5-9ff6-444c-8a77-aa7d1374682d

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Christinadobrzyn** [comment]
Maybe related to - https://github.com/Expensify/App/issues/52477#issue-2655531398

Asking...

**Comment by Christinadobrzyn** [comment]
Contributors are saying this https://github.com/Expensify/App/issues/52477#issue-2655531398 isn't related. I'll keep digging to see what I can find...

**Comment by jasperhuangg** [comment]
We do not need to fix this, way too minor
