### ISSUE TITLE
Expense - From expense report page tapping app's back button navigated to Workspace chat page

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#54508]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.78-1
**Reproducible in staging?:** Yes
**Reproducible in production?:** No
**Issue reported by:** Applause Internal Team
**Device used:** Redmi note 10s Android 13
**App Component:** Money Requests

## Action Performed:
1. Go to https://staging.new.expensify.com/home
2. Tap fab - new workspace
3. Create 2 expenses
4. Open the expense and navigate to the report page
5. Tap the app's back button

## Expected Result:
From expense report page tapping app's back button user must be navigated to workspace chat page.

## Actual Result:
From expense report page tapping app's back button user navigated to LHN instead workspace chat page.

## Workaround:
Unknown

## Platforms:
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/1594f7b4-46f4-4e84-bc97-a560a20b76d2

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Beamanator** [comment]
Looooks like the same as https://github.com/Expensify/App/issues/54496

**Comment by Beamanator** [comment]
PR Merged & CP'd, waiting on test!

**Comment by kavimuru** [comment]
Bug is not reproduced 

https://github.com/user-attachments/assets/71b408a4-73a5-4769-b811-cc51b64e62d2

**Comment by Beamanator** [comment]
Nice! Fixed, so closing this out
