### ISSUE TITLE
mWeb - Workspace - Using back button on WS chat, leads to inbox instead of WS profile.

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#54517]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.78-1
**Reproducible in staging?:** Yes
**Reproducible in production?:** No
**Email or phone of affected tester (no customers):** ibellicotest+115@gmail.com
**Issue reported by:** Applause Internal Team
**Device used:** Motorola MotoG60 - Android 12 - Chrome
**App Component:** Workspace Settings

## Action Performed:
1. Open the staging.new.expensify.com website.
2. Tap on "Settings" and select "Workspaces" 
3. Open any workspace.
4. Tap on the workspace chat button on the bottom.
5. Once redirected to workspace chat, tap on the back button on the top left corner.

## Expected Result:
After tapping on the back button, user should return to workspace settings.

## Actual Result:
After opening workspace chat via workspace settings and tapping on the back button, the user lands on inbox instead of returning to workspace settings.

## Workaround:
Unknown

## Platforms:
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/1ed5bb0a-4320-41cf-b88e-442666efd276

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Beamanator** [comment]
Pretty sure this is also going to be fixed in https://github.com/Expensify/App/pull/54511 🤔

**Comment by Beamanator** [comment]
PR Merged & CP'd, waiting on test!

**Comment by kavimuru** [comment]
Not reproduced 

https://github.com/user-attachments/assets/eded8fbc-a05d-4da3-b33a-6da6cba7db0a

**Comment by Beamanator** [comment]
Great, closing this out - will handle payouts in https://github.com/Expensify/App/issues/54496
