### ISSUE TITLE
Referral - No referral modal when the selection list content is empty

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#54526]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.78-1
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Yes, reproducible on both
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://github.com/Expensify/App/pull/54445
**Email or phone of affected tester (no customers):** htad26+gfdffdgfd@gmail.com
**Issue reported by:** Applause Internal Team
**Device used:** Windows 10/Chrome mWeb/Chrome, IPhone 13/IOS 18/2
**App Component:** Other

## Action Performed:
1. Log in with a new Gmail account
2. Open global create > Submit expense > Manual > Enter amount and click next
3. Now observe the RHP when the selection list content is empty

## Expected Result:
'get $250' referral modal appears

## Actual Result:
No referral modal appears when the selection list content is empty

## Workaround:
Unknown

## Platforms:
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [x] iOS: Standalone
- [x] iOS: HybridApp
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/897ee302-f901-46a8-8bd8-f075f844923b

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Christinadobrzyn** [comment]
Thanks! @FitseTLT closing this since there are proposals here https://github.com/Expensify/App/issues/54470
