### ISSUE TITLE
Expenses don't show in Staging Supportal Old Dot

### ISSUE THREAD

**Issue by Christinadobrzyn** [Expensify/App#54532]
**Slack chat** https://expensify.slack.com/archives/C03TQ48KC/p1735052827689619

## Action Performed:

1. Go to https://staging.expensify.com/_support/
2. Click Reports
3. Click on a report
4. Notice the expenses don't show

## Expected Result:

1. Go to https://staging.expensify.com/_support/
2. Click Reports
3. Click on a report
4. Expenses should show

## Actual Result:

On staging alone (not prod) expenses on OD reports do not show in Supportal

## Screenshots/Videos

https://github.com/user-attachments/assets/84141ab7-0a36-456d-a9e9-df76712d9902

Network error shows

<img width="1090" alt="image" src="https://github.com/user-attachments/assets/e26d4c83-f895-4029-9aad-da783d3ac475" />

**Comment by Christinadobrzyn** [comment]
Discussing here - https://expensify.slack.com/archives/C03TQ48KC/p1735055051351899?thread_ts=1735052827.689619&cid=C03TQ48KC

**Comment by aldo-expensify** [comment]
This got fixed here in the end: https://github.com/Expensify/Web-Expensify/pull/44899#issuecomment-2561362205
