### ISSUE TITLE
Chat - Code block text appears inconsistent in mWeb & Android

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#54558]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.78-2
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**Issue reported by:** Applause Internal Team
**Device used:** Redmi note 10s Android 13
**App Component:** Chat Report View

## Action Performed:
1. Launch site in both mweb and Android and perform below steps in both
2. Open a report
3. Paste text - changed the category to "Car" (previously "Benefits") in compose box
4. Send the message
5. Edit the message - changed the category to "Car" `(previously "Benefits")` - first add this code block
5. In the same edit message now add header markdown - # changed the category to "Car" (previously "Benefits")
6. Note the code block text in both mweb and Android

## Expected Result:
In Android and mweb, code block must be displayed in consistent way in edit box and after sending message.

## Actual Result:
In Android, in edit box, code block text is bold and after sending, message is not in bold. But in mweb, in edit box, code block text is not in bold and after sending, message is in bold. Inconsistency in behavior.

## Workaround:
Unknown

## Platforms:
- [x] Android: Standalone
- [x] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/ae4b1204-0107-4bf8-b44f-4a6f8a315d3c

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by bernhardoj** [comment]
This should be fixed in https://github.com/Expensify/App/issues/39623

**Comment by anmurali** [comment]
Dupe - https://github.com/Expensify/App/issues/39623
