### ISSUE TITLE
Search - App freezes when using search

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#54553]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.78-2
**Reproducible in staging?:** Yes
**Reproducible in production?:** No
**Email or phone of affected tester (no customers):** applausetester+ds@applause.expensifail.com
**Issue reported by:** Applause Internal Team
**Device used:** Mac 14.5/ Chrome
**App Component:** Search

## Action Performed:
1. Login with applause email 
2. Click on the search icon 
3. Try writing something on the search box

## Expected Result:
App works smoothly when writing on the search box

## Actual Result:
App freezes when writing on the search box

## Workaround:
Unknown

## Platforms:
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/29091b0d-e364-4fac-a39f-7708fa502185

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by techievivek** [comment]
I think this is already reported here https://github.com/Expensify/App/issues/54050?

**Comment by techievivek** [comment]
Closing it based on above comment.
