### ISSUE TITLE
Reports > Trips - The booked hotel does not appear in the trip filter

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#54567]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.78-2
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**Email or phone of affected tester (no customers):** applausetester+l4@applause.expensifail.com
**Issue reported by:** Applause Internal Team
**Device used:** macOS Sequoia 15.1.1, Desktop-Web / iPhone SE 3rd generation, iOS 18.2, app-mWeb
**App Component:** Search

## Action Performed:
1. Open the URL: https://staging.expensify.com
2. Log in with a expensifail account
2. Click on Travel > Book or manage travel
3. Book a hotel can be any (On payment filter select: 'Pay at property')
4. Go to https://staging.new.expensify.com/
5. Log in with the same account
6. Click on Reports > Trips

## Expected Result:
The booked hotel is shown in the trips filter.

## Actual Result:
The booked hotel does not appear in the trips filter.

## Workaround:
Unknown

## Platforms:
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [x] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/24a6d2e4-e884-43d0-ba6c-56ed3e66fe2e

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by bfitzexpensify** [comment]
This is being worked on in https://github.com/Expensify/App/issues/37823. Closing
