### ISSUE TITLE
 Android Hybrid - Logout - User lands on Magic Code tab when logging out

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#54568]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.78-1
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** No, reproducible on hybrid only
**Email or phone of affected tester (no customers):** ibellicotest+121@gmail.com
**Issue reported by:** Applause Internal Team
**Device used:** Motorola MotoG60 - Android 12
**App Component:** Other

## Action Performed:
1. Open the Expensify app.
2. Log in with any account via Magic Link.
3. Tap on "Settings" on the bottom of the screen.
4. Tap on "Sign Out"

## Expected Result:
When signing out of the account, the user should land on the "How would you like to connect" tab.

## Actual Result:
When signing out of the account, the user lands on the Magic Code tab.

## Workaround:
Unknown

## Platforms:
- [ ] Android: Standalone
- [x] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/84f33079-1011-45be-b8e3-dd7d2eab01c3

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by anmurali** [comment]
I cannot reproduce this on the latest testflight
