### ISSUE TITLE
Track expense - Illustration in the empty state recipient list is top-aligned and not centered

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#54564]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.78-2
**Reproducible in staging?:** Yes
**Reproducible in production?:** No
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:** Exp
**Email or phone of affected tester (no customers):** applausetester+kh1012033@applause.expensifail.com
**Issue reported by:** Applause Internal Team
**Device used:** Mac 15.0 / Chrome
**App Component:** Money Requests

## Action Performed:
Precondition:
- Account has at least one workspace.

1. Go to staging.new.expensify.com
2. Go to self DM.
3. Track an expense.
4. Click Share it with my accountant.
5. Enter anything on the search field that will return no result.

## Expected Result:
Illustration in the empty state should be centered (production behavior).

## Actual Result:
Illustration in the empty state is top-aligned.

## Workaround:
Unknown

## Platforms:
- [x] Android: Standalone
- [x] Android: HybridApp
- [x] Android: mWeb Chrome
- [x] iOS: Standalone
- [x] iOS: HybridApp
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/faca17d3-1be6-41b3-96ed-c48f7b62297a

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by MonilBhavsar** [comment]
Looks like this is introduced by https://github.com/Expensify/App/pull/54231
cc @mkzie2 @Pujan92 if you could please take a look

**Comment by Pujan92** [comment]
Yes @MonilBhavsar, @mkzie2 plz check this, otherwise I will check this tomorrow. I think we can demote this.

**Comment by MonilBhavsar** [comment]
Thanks! Fine demoting but seems like simple fix to implement

**Comment by MonilBhavsar** [comment]
@Pujan92 if you could please review and test https://github.com/Expensify/App/pull/54577 for the existing and previous issue

**Comment by jasperhuangg** [comment]
This was fixed!
