### ISSUE TITLE
Mac/Chrome -  Image - Zoom is too poor

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#54588]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.78-5
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5345498
**Email or phone of affected tester (no customers):** hywnnoj+0001@gmail.com
**Issue reported by:** Applause Internal Team
**Device used:** macOS Sequoia 15.1.1 / Desktop / Web
**App Component:** Chat Report View

## Action Performed:
1. Open the Desktop app or go to: https://staging.new.expensify.com/
2. Go to 1:1 convo
3. Upload this large file (check the attachments)
4. Open the file
5. Click on the image to zoom in

## Expected Result:
The user is able to zoom in and see the image clearly

## Actual Result:
The user can zoom in, but the zoom is too poor compared to web zoom and other platforms.

## Workaround:
Unknown

## Platforms:
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

![Bug6693829_1734123227600!USE_THIS_FILE](https://github.com/user-attachments/assets/0a31e57c-405a-46e7-b441-054949d77dc7)
<img width="1664" alt="Bug6693829_1734123082067!Screenshot_2024-12-13_at_5 49 48_PM" src="https://github.com/user-attachments/assets/295f0469-fb7d-42e1-b881-5a5bed3842e5" />

https://github.com/user-attachments/assets/148ccdb2-8cad-46e8-bb0e-a79e17e7fc8d

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by QichenZhu** [comment]
I think this was introduced on purpose to improve performance in https://github.com/Expensify/App/issues/38180.
