### ISSUE TITLE
[$250] iOS Chat - Report view briefly jumps after closing search router

### ISSUE THREAD

**Issue by mitarachim** [Expensify/App#54598]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.79-0
**Reproducible in staging?:** Yes
**Reproducible in production?:** No
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Yes, reproducible on both
**If this was caught during regression testing, add the test name, ID and link from TestRail:** Exp
**Email or phone of affected tester (no customers):** applausetester+8078787@applause.expensifail.com
**Issue reported by:** Applause Internal Team
**Device used:** iPhone 15 Pro Max / iOS 18.2
**App Component:** Chat Report View

## Action Performed:
1. Launch ND or standalone app.
2. Open any chat.
3. Do not open keyboard (do not tap composer).
4. Tap Search icon.
5. Tap app back button.

## Expected Result:
Report view will not jump after closing search router.

## Actual Result:
Report view briefly jumps after closing search router.

## Workaround:
Unknown

## Platforms:
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [x] iOS: Standalone
- [x] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/acdfd699-0380-4678-8ba4-0cedaf9525e4

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @rayane-djouah</details>
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021872620537798063747</li>
        <li>Upwork Job ID: 1872620537798063747</li>
        <li>Last Price Increase: 2024-12-27</li>
    </ul>
</details>

**Comment by mountiny** [comment]
Looking for proposals that identify the offending PR too. @christianwen @DylanDylann I think it might be related to this https://github.com/Expensify/App/pull/51172 can you confirm?

I am demoting as this is just a minor ux issue in specific case when the chat is open without keyboard being opened

**Comment by DylanDylann** [comment]
I can't reproduce this bug on the latest main

https://github.com/user-attachments/assets/7485dc48-57d8-499b-8f37-cf07e367afc2

**Comment by slafortune** [comment]
I also cannot reproduce this
