### ISSUE TITLE
LHN - Tooltip appears for each workspace chat including invited member's workspace chat

### ISSUE THREAD

**Issue by mitarachim** [Expensify/App#54601]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.79-0
**Reproducible in staging?:** Yes
**Reproducible in production?:** Unable to check
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:** Exp
**Email or phone of affected tester (no customers):** applausetester+909608@applause.expensifail.com
**Issue reported by:** Applause Internal Team
**Device used:** Mac 15.0
**App Component:** Left Hand Navigation (LHN)

## Action Performed:
1. Go to staging.new.expensify.com
2. Log in with a new account.
3. Create a workspace, but do not go back to Inbox.
4. Go to workspace settings > Members.
5. Invite a few members.
6. Go back to Inbox.

## Expected Result:
There will be only one tooltip for the workspace chat which is the admin's own workspace chat.

## Actual Result:
Tooltip appears for each workspace chat including invited member's workspace chat.

## Workaround:
Unknown

## Platforms:
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [x] iOS: Standalone
- [x] iOS: HybridApp
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/20bb4807-904e-4bb5-b4f1-8b829f7ff819

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by youssef-lr** [comment]
This is coming from [here](https://github.com/Expensify/App/pull/54263), I've asked the contributor to take a look.

**Comment by Beamanator** [comment]
CP'd PR just got to staging! @ishpaul777 if you have a moment, would you mind testing on staging?

**Comment by Beamanator** [comment]
amazing, thanks so much!!

**Comment by Beamanator** [comment]
closing as i believe no payment due here
