### ISSUE TITLE
Email - Email received for 1:1 conversation has wrong subject

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#54662]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.79-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/cases/view/1971092
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Navigate to a 1:1 conversation with a user you have email inbox access - must be a main email address without the + iteration
3. Send some messages
4. Wait 10 minutes. This will trigger an email notification to this account
5. Log out
6. After 10 min has passed, check the main account email inbox

## Expected Result:
There is an email with this subject "Chat between <A> and <B>"

## Actual Result:
The email subject is "<A> and <B>"

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

![Bug6703713_1735462307008!Screenshot__262_](https://github.com/user-attachments/assets/8c7ccad4-0492-4c1f-a518-096939f06f81)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by jliexpensify** [comment]
Tested with my dummy gmail account and can repro:

![image](https://github.com/user-attachments/assets/9b747f9c-ed89-4ea9-9f5c-ec04a19655d2)

**Comment by jliexpensify** [comment]
Posted [here](https://expensify.slack.com/archives/C06ML6X0W9L/p1735622991359659) to see if anyone knows if we should be fixing this.

**Comment by jliexpensify** [comment]
Going to close this as it's a change that was made from since at least December 2023, so it must be intentional:

![image](https://github.com/user-attachments/assets/fe90a5f5-a70b-4d89-aa0e-baf1d4e262dd)
