### ISSUE TITLE
Build new "Connect Bank Account" workspace page 

### ISSUE THREAD

**Issue by MitchExpensify** [Expensify/App#5697]
Coming from [this](https://docs.google.com/document/d/1neW8g9ks2LUtD71gnuANbh_hy0lv4JNIJMZe_8-R_KY/edit#bookmark=id.u8uo2r42wx65) section of the doc, we are building a new "Connect Bank Account" workspace page.

Note - All PRs should target the `tgolen-workspace-settings` branch

**Comment by marcaaron** [comment]
I need the assets for this ASAP all icons etc in the doc please.

**Comment by marcaaron** [comment]
![Screen Shot 2021-10-06 at 9 07 37 AM](https://user-images.githubusercontent.com/32969087/136267282-8389d774-b73d-45a0-ab23-ac1977ff027d.png)
![Screen Shot 2021-10-06 at 9 07 30 AM](https://user-images.githubusercontent.com/32969087/136267287-82da89c6-6abb-4c7a-ae31-c388fe092259.png)
![Screen Shot 2021-10-06 at 9 07 13 AM](https://user-images.githubusercontent.com/32969087/136267288-a818aab3-026d-4cd3-900f-8e59e47a5922.png)
![Screen Shot 2021-10-06 at 9 07 03 AM](https://user-images.githubusercontent.com/32969087/136267291-a6c97a30-a507-4cda-afd8-599503ad5d08.png)
