### ISSUE TITLE
Email is displayed in LHN when IOU is settled using "Settled up elsewhere" 

### ISSUE THREAD

**Issue by isagoico** [Expensify/App#5712]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch the app
2. Log in with any account - Account A
3. Select any user - Account B
4. Request money from this user
5. Log in with account B and Pay the bill with Settled as elsewhere
6. Go back to LHN and check the last message preview
## Expected Result:
Payment "Settled up elsewhere" method is showing in LHN
## Actual Result
Payment "Settled up elsewhere" method is showing in LHN, email of the user is displayed. 
This **does not happen** when using PayPal as the payment method. 

## Workaround:
None needed, visual issue

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.6-0

**Reproducible in staging?:** yes
**Reproducible in production?:** yes

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

<img src="https://user-images.githubusercontent.com/44479856/136420957-bbf5e381-3bb3-406f-9fa6-1a768b988e7c.png" width="40%"> <img src="https://user-images.githubusercontent.com/44479856/136421024-3515c300-6993-4958-b309-2fe522d7fcca.png" width="40%">

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause and @puneetlath 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1633615145473400

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by MariaHCD** [comment]
Hey, @TomatoToaster! I don't think anyone who works on this issue will need to set up a wallet on dev considering that the payment option here is "Settled up elsewhere" and not "Pay with Expensify.

**Comment by TomatoToaster** [comment]
I have a feeling if we fix this issue for `settled up elsewhere` it'll also fix it for settling up with expensify. I guess this could be external then, but either way @luacmartins has picked it up 🙇🏾 thank you!

**Comment by luacmartins** [comment]
Did some investigating and it seems like we have a race condition here. Right after clicking "I'll settle up elsewhere", I see that the text under the user's name changes to "Settled up elsewhere" briefly before changing to the user's email address. I'll look more into it next week.

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (Second Week)

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (Third Week) 
Closing
