### ISSUE TITLE
Workspace - Able to add Chronos and Concierge to workspace and unable to remove

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#5723]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to https://staging.new.expensify.com
2. Log in with expensifail account
3. Go to any Workspace and Click Invite
4. On Email or Phone number box start but Chronos@expensify.com or Concierge@expensify.com and Click Invite

## Expected Result:
Error message should appear

## Actual Result:
Able to add Chronos and Concierge to workspace and unable to remove. If I use lower case in chronos@expensify.com or concierge@expensify.com it works fine.

## Workaround:
Unknown
## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.7-0
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/136494029-ed91845e-e115-494f-b4b6-ab4938b9c57d.mp4

https://user-images.githubusercontent.com/43996225/136494040-aa4888b6-34c4-42d1-88b0-7a0a5cebc65b.mp4

![Bug5270689_Work1](https://user-images.githubusercontent.com/43996225/136494026-9e268118-2f66-44f9-b329-f6e6766e84b2.png)
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (Second Week)

**Comment by pecanoro** [comment]
Since it's not reproducible, I am going to close
