### ISSUE TITLE
Getting 404 error when submttting company info step

### ISSUE THREAD

**Issue by joelbettner** [Expensify/App#5761]
[This issue was originally](https://github.com/Expensify/Expensify/issues/180774) posted by @kevinksullivan in the Expensify/Expensify repo, but after researching it I determined it is due to issues with code in the App repo. I've re-created the issue here and closed it in the Expensify/Expensify repo

# Problem

I cannot continue past company info step **on staging only**

### Reproduction steps

1. Create workspace
2. Select `Connect Bank Account` tab
3. Select `[Connect bank account]`  button
4. Enter routing/account number
5. Enter fake company info, hit 404 error, company address clears

![image](https://user-images.githubusercontent.com/22508290/136829251-b382a08c-b3e8-4339-b44a-025a16e425e2.png)

I feel like this has something to do with the company address change in https://github.com/Expensify/App/pull/5643 , since the address is clearing every time I try to submit, but I'm not sure.

# Solution

I would expect to move forward, and if not, company info not to clear every time if I fail a certain check.
.

**Comment by MariaHCD** [comment]
Looking into this:
1. Cannot seem to reproduce the 404 error on dev nor on staging 🤔 
2. Even if the company information form is submitted successfully, the company address field is cleared if the user goes back to the form. So it looks to me that the company address field just needs to be set correctly.

**Comment by kevinksullivan** [comment]
No, let's close this out till we reproduce again.
