### ISSUE TITLE
[HOLD for payment 2021-11-04] Routing number error on incorrect step

### ISSUE THREAD

**Issue by Beamanator** [Expensify/App#5762]
The step to add manually a bank account has a more relaxed validation on the routing number compared to the validation performed during the company step.

Ideally, the error should appear during the manually add account step.

Test data:

Routing number: `123456789`
Account number: `123`

## Action Performed:

1. Create and verify an account for NewDot
2. In NewDot, create workspace and start VBA flow
3. Click "Connect manually"
4. Input: Routing number: `123456789`, Account number: `123`
5. Click "Save & continue", it should let you continue to the Company Step
6. Enter ""valid"" information in the Company Step form (see error screenshot below if you need sample data)
7. Click "Save & Continue"

## Expected Result:
I would have expected to move forward to the next step

## Actual Result:
There is an error above the "Save & continue" telling me that the routing number is invalid. This error could have been notified on the previous step.

![Screen Shot 2021-09-27 at 6 33 52 PM](https://user-images.githubusercontent.com/87341702/135009070-626f9170-f99a-473b-8847-f278d4b792e8.png)

## Workaround:
No workaround necessary, it just makes experience a little worse.

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** Latest
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes

**Upwork URL: https://www.upwork.com/jobs/~012258c903b29a0f0d

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

cc @aldo-expensify

**Comment by Santhosh-Sellavel** [comment]
@Beamanator How it's done on the server-side?  Is there a separate API we use to verify bank account & routing numbers then we can use it to verify the same here?

**Comment by Santhosh-Sellavel** [comment]
Also, I see some proposals in the old issue #5554  using an algorithm implementation from here http://en.wikipedia.org/wiki/Routing_transit_number#MICR_Routing_number_format

Is it an acceptable solution?

**Comment by aldo-expensify** [comment]
> So the proposal on the old related issue isn't 100% acceptable, we do need to have different validation based on the 'country'

Hmm, I think we may be restricting VBA accounts in NewDot to the US. When you get to the company step, you cannot choose country, and you can only choose States and Zip codes from the US. Shouldn't we just use the US routing validation?

**Comment by Beamanator** [comment]
Wow great call both of you! I hadn't realized that 😆 

Yeah I think it would be nice to go with the http://www.brainjar.com/js/validation/ validation to make it consistent :D

**Comment by Beamanator** [comment]
@Santhosh-Sellavel I like your proposal, let's go with that, making sure to use the algorithm we agreed on [here](https://github.com/Expensify/App/issues/5762#issuecomment-941228132).

> Also we could move the regex also to validateRoutingNumber, and just call it validate the number.
I don't think this is necessary, since the other validations in [this function](https://github.com/Expensify/App/blob/8fd5aecc0cd0dfe35c4b037d2d888b26d72151c5/src/pages/ReimbursementAccount/BankAccountStep.js#L82-L98) are validating other items (accounting number and `hasAcceptedTerms`)

**Comment by Santhosh-Sellavel** [comment]
Ping for Upwork!

**Comment by trjExpensify** [comment]
Hey Santhosh. Doesn't look like the contract was started for this one. I've sent the offer, so we can settle it once you accept. 👍

**Comment by trjExpensify** [comment]
Cool, job done. 👍
