### ISSUE TITLE
[HOLD for payment 2021-12-06] Add app download links to workspace invitation validation email - Reported by: @akshayasalvi 

### ISSUE THREAD

**Issue by isagoico** [Expensify/App#5774]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Invite a new user account (that you have access to) to a workspace
2. Check the validation email

## Expected Result:
If the apps are mentioned in the email there should be a download link for iOS and Android. 

## Actual Result:
Apps are mentioned in email but no download link is included. 

## Workaround:
None needed. 

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.7-3

**Reproducible in staging?:** yes 
**Reproducible in production?:** yes 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

![image](https://user-images.githubusercontent.com/44479856/136997807-c2f62908-ea38-47cf-97c6-c9edc96716fb.png)

**Expensify/Expensify Issue URL:**

**Issue reported by:** @akshayasalvi 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1633983814141300

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by akshayasalvi** [comment]
@Beamanator  If I add the content to the message it shows up the raw HTML like this 

![image](https://user-images.githubusercontent.com/57435789/139596233-e459b27f-92e0-4847-a242-14e2d7e17cd7.png)

I was wondering if I should update only the API call by appending the download app links.
```
  invite(logins, this.state.welcomeNote || this.getWelcomeNotePlaceholder(), this.props.route.params.policyID);
    ```

**Comment by Beamanator** [comment]
Hmm good point @akshayasalvi - Personally I think it's fine, but what do you have in mind for just appending in the api Call?

**Comment by akshayasalvi** [comment]
Yeah I was wondering if we could just append in the app call.

**Comment by Beamanator** [comment]
I'm interested in your specific thoughts b/c I think we'd only be able to append directly to `this.getWelcomeNotePlaceholder()`... We can't just append to `this.state.welcomeNote` because it's possible the user deleted and rewrote their welcome note, so the download links would be weird there. But how do we know if the current value of `this.state.welcomeNote` is the default welcome note or something that the user specifically wrote?

**Comment by akshayasalvi** [comment]
We're setting the default welcomeNote in state as  `this.getWelcomeNotePlaceholder()`. and we're calling `invite(logins, this.state.welcomeNote || this.getWelcomeNotePlaceholder(), this.props.route.params.policyID);`. 

> because it's possible the user deleted and rewrote their welcome note, so the download links would be weird there
I get what you mean. Even we could maintain a flag, we can't be sure that the user removed the download app content or retained. Should we add some kind of a placeholder? So that if it exists, we'll append else we won't?

`App links {{Android}}, {{iOS}} and {{Desktop}}`

With a small note at the bottom of the field?

**Comment by Beamanator** [comment]
> `App links {{Android}}, {{iOS}} and {{Desktop}}`
>
> With a small note at the bottom of the field?

Can you please explain what you're suggesting here? It sounds like you're saying we can add just `App links {{Android}}, {{iOS}} and {{Desktop}}` in the `getWelcomeNotePlaceholder` test, and before we send it using `invite` we can replace the `{{Android}}` with the Android download links, etc.?

**Comment by akshayasalvi** [comment]
yeah that's what I am saying

**Comment by Beamanator** [comment]
Hmm this could work well, but I'd like to hear what other people think. It's possible `{{Android}}, {{iOS}} and {{Desktop}}` makes sense for developers but won't make sense for normal users 🤔 Do you mind asking in #expensify-open-source what people prefer out of these options:
1. Go with the original idea, which shows the links in raw html [here](https://github.com/Expensify/App/issues/5774#issuecomment-955767068)
2. Go with your latest suggestion [here](https://github.com/Expensify/App/issues/5774#issuecomment-958894224)
3. Something else?

**Comment by Beamanator** [comment]
As mentioned [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1636651035126800?thread_ts=1636036533.472000&cid=C01GTK53T8Q), we decided to link directly to this page which will have the download links: https://use.expensify.com/download

**Comment by Beamanator** [comment]
Actually I'm going to post again to the main channel to get a few more 👍 / 👎  on the idea before moving forward with this idea

**Comment by akshayasalvi** [comment]
PR Raised

**Comment by Beamanator** [comment]
Not overdue, just waiting to get to production for payment 👍

**Comment by botify** [comment]
The solution for this issue has been :rocket: deployed to production :rocket: in version 1.1.16-10 and is now subject to a 7-day regression period :calendar:. Here is the list of pull requests that resolve this issue:

- https://github.com/Expensify/App/pull/6292


If no regressions arise, payment will be issued on 2021-12-06. :confetti_ball:

**Comment by akshayasalvi** [comment]
> @MitchExpensify Need your help on this one. It seems I wasn't formally hired on Upwork.I clicked on the Upwork link and it says the job is no longer available.

@MitchExpensify Bump

**Comment by MitchExpensify** [comment]
Sorry for the delay @akshayasalvi, the OG Upwork job expired. Please apply to the new one I've created [here](https://www.upwork.com/jobs/~01548c0da752dc34b1). Thanks!

**Comment by akshayasalvi** [comment]
Thanks for the posting @MitchExpensify. I’ve applied.

**Comment by MitchExpensify** [comment]
Hired @akshayasalvi ! Sorry for the delay, I was ooo

**Comment by akshayasalvi** [comment]
Thanks @MitchExpensify. Awaiting payment now 😄

**Comment by MitchExpensify** [comment]
Payment with bonus for reporting made @akshayasalvi

**Comment by Beamanator** [comment]
I guess we can close now right @MitchExpensify ? :D

**Comment by MitchExpensify** [comment]
Yes!
