### ISSUE TITLE
[N6] Wrong value in AddressSearch after refresh

### ISSUE THREAD

**Issue by aldo-expensify** [Expensify/App#5840]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Create NewDot account, verify it, log in
2. Create Workspace
3. Do the add Bank account step (first step) of VBA flow (use this [SO]())
4. You should be in `Company Step`
5. Type something in the `Company Address` field, choose an address result
6. Type something in another field
7. Refresh the page

## Expected Result:
The `Company Address` field should have the value we input before refresh

## Actual Result:

The `Company Address` doesn't have the right value:

https://user-images.githubusercontent.com/87341702/137230266-e6c60a2c-34f4-47b6-9e45-7b50b1b91a72.mov

## Workaround:
The user can input the address again

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:**
**Reproducible in staging?:**
**Reproducible in production?:**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by trjExpensify** [comment]
Ah yeah, I hit the `undefined`, `undefined` bit too. Noted that here: https://expensify.slack.com/archives/C020EPP9B9A/p1634207884072800?thread_ts=1634147967.452400&cid=C020EPP9B9A

Are you taking this one on, @aldo-expensify?

**Comment by roryabraham** [comment]
I'm not able to reproduce this.

**Comment by roryabraham** [comment]
jk it happens with 88 Kearney Street

**Comment by roryabraham** [comment]
Unfortunately the fix I tried did not work. Going to keep digging

**Comment by roryabraham** [comment]
In this case, I _think_ we'll just want the `premise` field to become `addressStreet` [here](https://github.com/Expensify/App/blob/6f8e2dc67566e5b65e89fde2f28b6d5dba652c3e/src/components/AddressSearch.js#L60).

**Comment by aldo-expensify** [comment]
Well, it actually seems to work if we add `types: 'address'` in the [query object](https://github.com/Expensify/App/blob/1689a57290f80669b28311be1f3bcc155ddc25dc/src/components/AddressSearch.js#L75-L76)

Do you want me to submit a PR?

**Comment by roryabraham** [comment]
> If you input 88 Kearny Street you get the full address result and not the premise with missing data.

In the example of 88 Kearny Street, it looked like the `premise` had all the necessary data. But that might not work consistently.

Also, heads up! I encountered some queries where Google Places would return a result, but then spit back an invalid address. For example, if you input `25220 Quail Ridge Road, Escondido, CA 97027` then Google Places will take that as a valid input, but the place returned in the callback is just `Quail Ridge Road, Escondido, CA 97027` (missing street number). I think this maybe means that there's a development planned there but that address doesn't exist yet. Let's make sure we cover that case as well.

**Comment by aldo-expensify** [comment]
> > If you input 88 Kearny Street you get the full address result and not the premise with missing data.
> 
> In the example of 88 Kearny Street, it looked like the `premise` had all the necessary data. But that might not work consistently.
> 
> Also, heads up! I encountered some queries where Google Places would return a result, but then spit back an invalid address. For example, if you input `25220 Quail Ridge Road, Escondido, CA 97027` then Google Places will take that as a valid input, but the place returned in the callback is just `Quail Ridge Road, Escondido, CA 97027` (missing street number). I think this maybe means that there's a development planned there but that address doesn't exist yet. Let's make sure we cover that case as well.

😨  will test that too! thanks!

**Comment by aldo-expensify** [comment]
> Yeah, so it looks like the `type: address` doesn't cover that case alone. Is it safe to assume that any valid address street must start with a number?

you are right, it is missing the number :(

> If so, we should throw an error when the end result does not begin with a number?
I guess that is an option, I'll have a look again to see if there is a way we could filter incomplete results

**Comment by aldo-expensify** [comment]
> > Is it safe to assume that any valid address street must start with a number?
> 
> I think this is probably a safe assumption 99.99% of the time, so if we find counter-examples then we can handle them when they pop up?

I think you are probably right there

**Comment by aldo-expensify** [comment]
> 2\. street_number

That sounds good to me, but I would suggest doing (2) and (3) as filters in our backend so we don't show those results to the user. I think it is better experience than showing results that eventually will lead to validation errors. What do you think about that?

**Comment by roryabraham** [comment]
It might not be a _perfect_ solution, but it will be an improvement from what we have currently. We can address issues with other addresses as they come up. I think we should maybe also add some unit test coverage of the `saveLocationDetails` function to help maintain it in the future.

**Comment by aldo-expensify** [comment]
> What is the estimate on the PR being ready for review? Anything I can do to help?

Hmm, I have to update the "Steps / QA" section. I can do that now. About the tests that @roryabraham suggested, I'm having some doubts about it.

To make it easier to test, I would remove the function `saveLocationDetails` from `AddressSearch` and make it receive a callback `onChangeText` as a parameter. This function is very related to the `AddressSearch` component and probably won't be used anywhere else, so I'm a bit hesitant about moving it to a separate file just for testing purposes. Another option is to define it in the `AddressSearch` component file and export it from there, but I haven't seen another case where we export something else besides the component.
