### ISSUE TITLE
Existing Workspaces are not displayed in mobile apps

### ISSUE THREAD

**Issue by isagoico** [Expensify/App#5865]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login in mobile with an account that has a existing workspace 
2. Navigate to settings

## Expected Result:
Existing workspaces should be displayed. 

## Actual Result:
Existing workspaces are not displayed. 

## Workaround:
None found. 

## Platform:

Where is this issue occurring?

- iOS
- Android

**Version Number:** 1.1.7-22

**Reproducible in staging?:** Yes
**Reproducible in production?:** No 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation
![image](https://user-images.githubusercontent.com/44479856/137413659-dbb8fecd-0001-4957-a925-2ab338af03d5.png)

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause 
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by aldo-expensify** [comment]
I see no workspaces in Android

![Screenshot_20211014-184719](https://user-images.githubusercontent.com/87341702/137419426-018c50f6-b8ed-4d77-afad-f95d4893776b.png)

Web:

![Screen Shot 2021-10-14 at 6 49 46 PM](https://user-images.githubusercontent.com/87341702/137419461-abaac48e-49dd-4d06-9346-b30e4314f885.png)

To create multiple workspace in NewDot, I just went to OldDot and created a new Free group policy:

![Screen Shot 2021-10-14 at 6 50 26 PM](https://user-images.githubusercontent.com/87341702/137419519-b449f5c5-dc13-495d-9770-47c29e2da21f.png)

**Comment by kevinksullivan** [comment]
@aldo-expensify also discussed and reproduced here.

https://expensify.slack.com/archives/C9YU7BX5M/p1634258856206000?thread_ts=1634173120.171900&cid=C9YU7BX5M
