### ISSUE TITLE
[HOLD for payment 2021-12-06] $500 Holding 2 fingers on PDF opens context menu - Reported by: @parasharrajat 

### ISSUE THREAD

**Issue by isagoico** [Expensify/App#5870]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Navigate to a conversation
2. Send a PDF 
3. Open the preview 
4. Hold 2 fingers over the PDF

## Expected Result:
No context menu should be displayed in attachment preview

## Actual Result:
Context menu displayed. 

## Workaround:
None needed. 

## Platform:

Where is this issue occurring?

- iOS
- Android 

**Version Number:** 1.1.7-22

**Reproducible in staging?:** Yes 
**Reproducible in production?:** Yes 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

**Expensify/Expensify Issue URL:**

**Issue reported by:** @parasharrajat 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1634141035220700

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by parasharrajat** [comment]
Not sure why the video wasn't uploaded here https://expensify.slack.com/archives/C01GTK53T8Q/p1634141057220800?thread_ts=1634141035.220700&cid=C01GTK53T8Q.

@Luke9389 according to the Video, the context menu is opening on the Preview Modal which it should not.

**Comment by Luke9389** [comment]
Ok, let's give this a try @CamilaRivera. You've got the 🟢 green light 🟢 to go ahead and make a PR.

**Comment by SofiedeVreese** [comment]
Niiice! I've hired @CamilaRivera via Upwork now.

**Comment by SofiedeVreese** [comment]
No changes: it has an open PR.

**Comment by SofiedeVreese** [comment]
Not overdue: PR is open.

**Comment by SofiedeVreese** [comment]
PR merged, waiting for deploy so I can add the payment hold.

**Comment by botify** [comment]
The solution for this issue has been :rocket: deployed to production :rocket: in version 1.1.16-10 and is now subject to a 7-day regression period :calendar:. Here is the list of pull requests that resolve this issue:

- https://github.com/Expensify/App/pull/6169


If no regressions arise, payment will be issued on 2021-12-06. :confetti_ball:

**Comment by SofiedeVreese** [comment]
Created a separate job in Upwork to pay out @parasharrajat 's reporting bonus. 

Paid out @CamilaRivera + company offsite bonus.

Contributor paid: ✅ 
Contract cancelled: ✅ 
Upwork posting removed: ✅
