### ISSUE TITLE
[HOLD for payment 2021-10-30] Log in - Promo Colors are changing each time the user writes a new character for new password

### ISSUE THREAD

**Issue by isagoico** [Expensify/App#5912]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Navigate to log in screen
2. Enter a new email
3. Look for the validation mail on email inbox
4. Change link to staging
5. Write some characters in password fields
6. Dance 💃 

## Expected Result:
Colors should not change with each character written

## Actual Result:
Colors are changing with each character written

## Workaround:
None needed, visual issue. 

## Platform:

Where is this issue occurring?

- Web
- Desktop App

**Version Number:** 1.1.8-2

**Reproducible in staging?:** Yes 
**Reproducible in production?:** No

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/44479856/137570530-6c49617f-6916-406f-b502-490c7b468330.mp4

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by rushatgabhane** [comment]
In the interest of time, pushed a PR that fixes this issue.

**Comment by botify** [comment]
The solution for this issue has been :rocket: deployed to production :rocket: in version 1.1.8-9 and is now subject to a 7-day regression period :calendar:. Here is the list of pull requests that resolve this issue:

- https://github.com/Expensify/App/pull/5913


If no regressions arise, payment will be issued on 2021-10-30. :confetti_ball:

**Comment by Jag96** [comment]
Paid!
