### ISSUE TITLE
[HOLD for payment 2021-11-05] Payments - add a fill background to "Add new payment method"

### ISSUE THREAD

**Issue by isagoico** [Expensify/App#5915]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Navigate to payments
2. Click on "add new payment method" 

## Expected Result:
There should be a grey background the the payment methods menu is open. 

## Actual Result:
Background stays white. 

## Workaround:
None needed, visual issue. 

## Platform:

Where is this issue occurring?

- Web
- Desktop App

**Version Number:** 1.1.8-0

**Reproducible in staging?:** Yes 
**Reproducible in production?:** Yes 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation
![image](https://user-images.githubusercontent.com/44479856/137600963-e71f60e5-3405-485a-b795-6aa9a8058285.png)

**Expensify/Expensify Issue URL:**

**Issue reported by:** @Santhosh-Sellavel 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1634144802229400

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kakajann** [comment]
## Proposal
1. Pass a new prop `isAddPaymentMenuVisible={this.state.shouldShowAddPaymentMenu}` to `PaymentMethodList` component after `isLoadingPayments` prop
https://github.com/Expensify/App/blob/74b77a81d2c3fddee43b2c8b04802fed9251d96f/src/pages/settings/Payments/PaymentsPage.js#L127-L131

2. Small modification in addPaymentMethod object
```js
combinedPaymentMethods.push({
    type: MENU_ITEM,
    title: this.props.translate('paymentMethodList.addPaymentMethod'),
    icon: Plus,
    onPress: e => this.props.onPress(e),
    key: 'addPaymentMethodButton',
    disabled: this.props.isLoadingPayments,
    
    // ↓↓↓ THIS KEY ADDEDD
    wrapperStyle: this.props.isShowAddPaymentMenuVisible && styles.switchInactive,
});
```

3. Finally add `wrapperStyle={item.wrapperStyle}` prop to `MenuItem` component in here:
https://github.com/Expensify/App/blob/74b77a81d2c3fddee43b2c8b04802fed9251d96f/src/pages/settings/Payments/PaymentMethodList.js#L153-L162

And of course I'll add new props to propTypes.

**Comment by sylveawong** [comment]
sorry! going to remove myself and @shawnborton / @michelle-thompson so they can get to this first!

**Comment by Beamanator** [comment]
@shawnborton I just noticed this button technically has 3 states:
1. Sitting alone
2. Hovered
3. Active (when being clicked)

Here's a vid showing all 3 - which do you prefer keeping when the menu is active?:

https://user-images.githubusercontent.com/3885503/138003010-9667efaa-6867-4eba-8805-83a4e0096323.mov

**Comment by shawnborton** [comment]
Hmm good find @Beamanator I think the :active state probably makes the most sense since the row is kind of "active" while the dropdown is shown. Thoughts?

**Comment by Beamanator** [comment]
Yeah I agree, I think "active" - also making sure the `+` sign is black, as it is when being clicked & hovered.

@Santhosh-Sellavel @kakajann can you both please update your proposals to include keeping the `+` icon black? I think in both of your solutions the background will be darker but the `+` icon changes back to gray

**Comment by kakajann** [comment]
That's how I would solve this anyway) as @Santhosh-Sellavel did. `iconFill` is simply enough. No advanced logic required

**Comment by Beamanator** [comment]
Thanks for the swift responses guys! 

@Santhosh-Sellavel I will give this job to you, i like your use of existing style methods like `getButtonBackgroundColorStyle` and `getIconFillColor`, I also like the prop names you suggested. Please move forward with submitting a PR when you have a chance 👍

**Comment by botify** [comment]
The solution for this issue has been :rocket: deployed to production :rocket: in version 1.1.11-1 and is now subject to a 7-day regression period :calendar:. Here is the list of pull requests that resolve this issue:

- https://github.com/Expensify/App/pull/5981


If no regressions arise, payment will be issued on 2021-11-05. :confetti_ball:

**Comment by mallenexpensify** [comment]
Paid @Santhosh-Sellavel  today since this falls on a weekend.  Included reporting and `n6-hold` bonuses
