### ISSUE TITLE
Feature Request - Add a share option when sharing files directly from Gallery or Files - Reported by: @Santhosh-Sellavel 

### ISSUE THREAD

**Issue by isagoico** [Expensify/App#5916]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app on iOS or Android
2. Navigate to gallery and select any image
3. Click on the share option

## Expected Result:
There should be an option to share via New Expensify

## Actual Result:
There's no option to share via New Expensify. 

## Workaround:
Share the file directly from the New Expensify app. 

## Platform:

Where is this issue occurring?

- iOS
- Android

**Version Number:** 1.1.8-0

**Reproducible in staging?:** Yes 
**Reproducible in production?:** Yes

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation
![image](https://user-images.githubusercontent.com/44479856/137603166-9f9bd2dd-d339-4546-afca-21f02e1d72ed.png)

**Expensify/Expensify Issue URL:**

**Issue reported by:** @Santhosh-Sellavel 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1634250479311800

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by sonialiap** [comment]
I agree with @parasharrajat I think this is covered by the two issues. Closing in favor of https://github.com/Expensify/App/issues/4817 (the open one of the two)
