### ISSUE TITLE
[Tracking] Expensify/App cleanup + style guide + README improvements

### ISSUE THREAD

**Issue by marcaaron** [Expensify/App#5984]
# Problem

Expensify/App, Onyx, and our JS styles are inconsistently enforced in the `Expensify/App` repo. This can happen for many reasons, but one obvious one is that we just haven't written down in our style guide clear examples.

# Why is this important?

Incorrect patterns will create more incorrect patterns and general confusion about the "right way" to make a change or implement a feature. Every Expensify contributor should ideally have what they need to be able to champion our code styles and philosophies when reviewing any contribution (internal or external). But this can be difficult without a clear guide to refer to.

# Solution

Let's do a quick audit of various things that need clarification and clean them up by creating an issue for each best practice. 

The assignee will:

1. Figure out _why_ we have chosen to do things this way
2. Update the style guide with a clear explanation and make sure that it can easily be linked to (if necessary)
3. Update the `Expensify/App` codebase to eliminate any inconsistencies

**Here's a list of things that need to be addressed and can be broken out into other issues:**

- [x] #5985
- [x] #5986
- [x] #5998
- [x] #6011
- [x] #6000
- [x] #6002
- [x] #6004
- [x] #5989
- [x] #6092
- [x] #5995
- [x] #6250
- [x] #6251
- [x] #6072
- [ ] Make sure that we are always using `Onyx.merge()` over `Onxy.set()` except for when absolutely necessary

Feel free to suggest other things to this list!

**Comment by marcaaron** [comment]
I like the idea of looking into some custom lint rules for things like using an array method instead of `_`. Especially if they direct you to the style guide to also learn why we prefer to do things one way over another. I don't have much experience with writing them so maybe others have ideas on if it's practical.

**Comment by kidroca** [comment]
I can't find a specific rule on how to deal with comments that span on multiple lines

- on some reviews I've been told that my comments doesn't match the style guide 
```diff
-    /* To work as controlled and uncontrolled input only value or defaultValue should be used
-     * there should be no default value like empty string */
+    /**
+     * To be able to function as either controlled or uncontrolled component we should not
+     * assign a default prop value for `value` or `defaultValue` props
+     */
     value: PropTypes.oneOfType([PropTypes.instanceOf(Date), PropTypes.string]),
```
- on others to write multiline comments on multiple lines as regular comments `//` 

I guess the first case applies only to prop types, but it's a bit confusing as I thought that's what should be used for all multiline comments

**Comment by marcaaron** [comment]
Good question. I've seen more multi-line comments with `//` than block style throughout our codebases so that's usually what I suggest to people when they are writing comments that are not docs, headings, or `propTypes`. 

We are using the block style for `propTypes` because that's what seems to work with `react-docgen`.

So yeah I agree it's confusing because

- JSDoc uses it's own style
```
/**
 * Test
 */
```
- Regular code comments use `// Test`
- propTypes use multiline style `/** Test */`

Maybe that's something that can be clarified in the style guide at least if everyone agrees.

**Comment by marcaaron** [comment]
Oh! Also update for @johnmlee101 - I spent some time looking into custom eslint rules and it's actually not too bad. Was able to create custom rules for most of the things on our original list.

**Comment by roryabraham** [comment]
How would people feel about standardizing on "No props destructuring"? So the rule would look like this:

```javascript
// Bad
const MyComponent = ({aProp, someOtherProp}) => (
   <SomeComponent
       aProp
       someOtherProp
   />
);

// Good
const MyComponent = (props) => (
    <SomeComponent
        aProp={props.aProp}
        someOtherProp={props.someOtherProp}
    />
);
```

In my opinion, this make components a bit more readable because it's always easy to tell if a variable comes from props or something else. This example doesn't illustrate it well, but when we have larger components with a mix of derived variables and variables coming directly from props, prop destructuring can make components more confusing.

**Comment by Luke9389** [comment]
I'd support "No props destructuring". Readability > saving a few keystrokes.

**Comment by roryabraham** [comment]
So actually, our [style guide](https://github.com/Expensify/App/blob/main/STYLE.md#destructuring) already states "Use parameter destructuring for stateless function components when there are no additional variable declarations in the render.", which should eliminate the problem I mentioned earlier, but is more nuanced to enforce. I still might prefer to just blanket ban props destructuring because I'm not sure we get any value from it but feel less strongly given the rules we already have in place.

**Comment by marcaaron** [comment]
>How would people feel about standardizing on "No props destructuring"? So the rule would look like this:

I'd feel pretty good about updating that tbh. I like having the `props` prefix because it makes it easier to differentiate what is a prop vs. variable in the function body or imported from some place else.

**Comment by roryabraham** [comment]
I posted a PR to implement my above suggestion banning props/state destructuring.

**Comment by roryabraham** [comment]
Another suggestion ... no ternaries in JSX:

```javascript
// Bad
const MyBadComponent = (props) => (
    <>
	      {props.shouldRenderA
	          ? <A />
	          : null}
	      {props.shouldRenderB
	          ? <B />
	          : null}
    </>
);

// Good
const MyGoodComponent = (props) => (
    <>
        {shouldRenderA && <A />}
        {shouldRenderB && <B />}
    </>
);
```

**Comment by tgolen** [comment]
I definitely agree with your bad example, but I think there is still a valid use case for ternaries, such as this:

```
{thisThing
    ? <A />
    : <B />
}
```

**Comment by roryabraham** [comment]
Okay, so maybe "No ternaries in JSX where the second half of the ternary is `null`"

**Comment by tgolen** [comment]
Yeah, I like that. I wonder if there is ever a valid case for any ternary to have the second half be `null`?

**Comment by tgolen** [comment]
I guess I can find quite a few of them in our code, but maybe we just stick to JSX for now.

**Comment by roryabraham** [comment]
Looks like there's a pre-existing eslint plugin/rule for this: https://github.com/divyagnan/eslint-plugin-ternaries/blob/master/docs/rules/no-null-ternary.md 🎉

**Comment by marcaaron** [comment]
>I wonder if there is ever a valid case for any ternary to have the second half be null?

I think yes, because React will try to render the left hand side in some cases e.g. if it is a `0`. But there are other solutions to that like ensuring you have a boolean for your left hand operator.

```js
{items.length && <List items={items} />} // prints 0
```

**Comment by Luke9389** [comment]
Definitely on board for 'no-null-ternaries'. By 'no ternaries in JSX' are we really saying no ternaries in the `return` method? In general, I think they're a pretty useful shorthand that work fine for other logic happening elsewhere in the component.

**Comment by Luke9389** [comment]
Ah OK, I think I should have been more clear. What I was wanting to clarify is that we can have ternaries in a `.jsx` file, but we don't want them returning actual JSX components, correct?

**Comment by tgolen** [comment]
@marcaaron I'd still say there is a valid case for your example pattern. I like using that pattern when data is being loaded and I don't want to display anything (including a spinner). However, outside of "data being loaded", I would agree that pattern isn't a good one.

@Luke9389 I think what we're saying is to not allow ternary-nulls inside the part that is returned from render():

```
render() {
    // this part is OK
    return (
        // this part is not OK
    );
}
```

.jsx files are only used in web-e, but the same rule would apply in that repo.

**Comment by kidroca** [comment]
IMO early returns in `componentDidUpdate` or anywhere else we run a side effect due to certain conditions is harmful 

Check this thread: https://expensify.slack.com/archives/C01GTK53T8Q/p1636393736077100

Let's say we have a code like this 

```js
componentDidUpdate(prevProps) {
        if (!prevProps.visible && this.props.visible) {
            this.input.focus();
        }
    }
```

we're now forced to change the signature to early return 

```js
componentDidUpdate(prevProps) {
    if (prevProps.visible || !this.props.visible) {
        return;
    }
    this.input.focus();
}
```

But if we need to include another side effect we'll have to get rid of the early return and revert the code
```js
componentDidUpdate(prevProps) {
        if (!prevProps.visible && this.props.visible) {
            this.input.focus();
        }

        if (prevProps.message.length < this.props.messageLength) {
            this.doSomething();
        }
    }
```

---

Early return can be handy for functions that return something (e.g. other than void/undefined) 
Usually a boolean function that can return `false` at the start
Or a filtering function that return `[]`

But for code that is causing side effects it can be confusing
A condition like `!prevProps.visible && this.props.visible)` is clear - it's a specific transition from old prop state to new prop state that causes a side effect

Sometimes more side effects would be added and they might need to run concurrently (like in my last example) in that case the early return code will be modified and a bug can be introduced if it's not inverted correctly
The least it's a change that could've been skipped

**Comment by marcaaron** [comment]
>a bug can be introduced if it's not inverted correctly

I can definitely see how someone could make that mistake, but unsure if this is actually a problem we've run into apart from people having opinions about it. A few ideas for solving your concern might be...
- Write a test if you are unsure whether logic has been inverted correctly or are afraid it will be broken in the future
- Use parens and invert an entire statement that way it is easier to invert again later (tbh dislike this practice because I find these kinds of statements hard to understand)
- Refactor by extracting the conditional into a method so that the intention is clearer (my preference)

e.g. 

```js
componentDidUpdate(prevProps) {
    if (!this.shouldFocusInput()) {
        return;
    }

    this.input.focus();
}

shouldFocusInput() {
    return !prevProps.visible && this.props.visible;
}
```

Will just need to be changed to...

```js
componentDidUpdate(prevProps) {
    if (this.shouldFocusInput()) {
        this.input.focus();
    }

    // other side effects...
}
```

**Comment by kidroca** [comment]
An early return is suitable for functions that aren't supposed to trigger side effects like `shouldComponentUpdate`

When we want to trigger a side effect we should strive for clarity for the exact conditions that trigger the side effect
- writing an unit test is great but it won't improve the readability of the statement
- using inverted statements also degrade readability
- extracting a method might work, but it's not as easy to enforce

---

If this code:
```js
componentDidUpdate(prevProps) {
    if (!this.canFocusInput(prevProps)) {
        return;
    }

    this.input.focus();
}
```

Would have to turn into this code:

```js
componentDidUpdate(prevProps) {
    if (this.canFocusInput(prevProps)) {
        this.input.focus();
    }

    if (this.shouldDoSomething(prevProps)) {
       this.doSomething();
    }
}
```

Then simply start with

```js
componentDidUpdate(prevProps) {
    if (this.canFocusInput(prevProps)) {
        this.input.focus();
    }
}
```

**Comment by kidroca** [comment]
There are cases where we'd like to skip all side effects - an early return comes naturally and conveys that well 
It doesn't degrade readability for the rest of the statements

```js
componentDidUpdate(prevProps) {
    if (this.props.disabled) {
        return;
    }

    if (this.canFocusInput(prevProps)) {
        this.input.focus();
    }
}
```

IMO that's the only case where an early return is preferable in a side effects producing code

**Comment by marcaaron** [comment]
Let's wait and see if this causes any issues. It should not be hard to modify the custom rule to skip when inside a `componentDidUpdate()` function body if this creates enough issues for us. I thought early returns were a bit weird at first but trust me it gets easier the more you do it!

**Comment by kidroca** [comment]
I'm on the latest `main` and have been spotting this eslint error across the app 

![image](https://user-images.githubusercontent.com/12156624/143283395-03e9adc4-b5e6-42c3-9a02-bce6e00482bf.png)

This is inside `src/libs/actions/ActiveClients.js` so why isn't the rule satisfied?

**Comment by marcaaron** [comment]
>so why isn't the rule satisfied

Do you see it when eslint runs in a GH action? Or just locally?

**Comment by kidroca** [comment]
> Do you see it when eslint runs in a GH action? Or just locally?

Locally

**Comment by marcaaron** [comment]
Ah hmm interesting. Just checked to be sure and doesn't complain for me. Perhaps there is something specific to your environment that causes the rule to show errors in your IDE.

**Comment by marcaaron** [comment]
Looks like there is only one thing left to cover here which is:

>Make sure that we are always using Onyx.merge() over Onxy.set() except for when absolutely necessary

Unsure if we have really landed on the exact guidance for that and the discussion can continue to happen [here](https://github.com/Expensify/react-native-onyx/issues/109). 

But I think we accomplished a lot here and can close this out. Thanks for everyone's help!

**Comment by kidroca** [comment]
> Ah hmm interesting. Just checked to be sure and doesn't complain for me. Perhaps there is something specific to your environment that causes the rule to show errors in your IDE.

I've traced the problem to file path checks and path separators 
Depending on the OS the separator can be a forward a backward slash
For me `context.getFilename()` resolves to this string `D:\Expensify.cash\src\libs\actions\ActiveClients.js`
The check below would not match:
```js
/**
 * @param {String} filename
 * @returns {Boolean}
 */
function isInLibs(filename) {
    return filename.includes('/src/libs/');
}
```

To make it platform agnostic it should be

```js
const path = require('path');

/**
 * @param {String} filename
 * @returns {Boolean}
 */
function isInLibs(filename) {
    const prefix = path.normalize('/src/libs/');
    return filename.includes(prefix);
}
```

Alternatively all separators can be replaced with `/` like `filename.replaceAll(path.sep, '/').includes('/src/libs/)`
