### ISSUE TITLE
[HOLD for payment 2021-11-12] LHN: Hide the pencil icon when message is sent or draft is deleted and show the icon when user started to type

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#6050]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Type a draft message in some chat.
    - The pencil icon for draft does not show up.
3. Switch to another chat to see the pencil icon appear and then move back to the chat with draft.
4. Sent or delete the message. 

## Expected Result:

The pencil icon should not be visible when there is no draft in the report.

Let's separate the pencil icon behaviour from the LHN reordering. Show the pencil icon whenever users creates the draft (_immediately_) and hide the pencil icon as soon as the draft is either deleted or message sent (_also immediately_). However, keep the LHN reordering same, we do not want the LHN to reorder while typing as that is very distracting.

## Actual Result:

Observe that the pencil icon is still visible in the LHN even though we have no draft at the moment.

## Workaround:
User can switch to different report or reload and the pencil icon will disappear.

## Platform:

Where is this issue occurring?

- Web
- Desktop App

**Version Number:**
**Reproducible in staging?:**
**Reproducible in production?:**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:**
**Issue reported by:** @AndrewGable 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1635195542084000

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mountiny** [comment]
PR is in a review!

**Comment by SofiedeVreese** [comment]
Close to being deployed.

**Comment by mountiny** [comment]
@marktoman @SofiedeVreese There has been a regression detected which has been introduced in PR solving this issue. We need to resolve that. Link is slack: https://expensify.slack.com/archives/C01GTK53T8Q/p1636082766011900


BUG: Blank screen after logout
![image](https://user-images.githubusercontent.com/36083550/140512323-0eaed425-68d8-4897-82e6-752843d062f8.png)

**Comment by SofiedeVreese** [comment]
Looks like the regression's been fixed. I'm going to add a "hold for payment", 7 days from the original deploy.

**Comment by marktoman** [comment]
@SofiedeVreese To our best knowledge, the only place where the reported error or any related issue could occur has indeed been fixed. Thank you for putting this forward.

**Comment by mountiny** [comment]
@SofiedeVreese Confirming this job shoul dbe good to pay out on the 12th.

**Comment by SofiedeVreese** [comment]
Paid and closed! Thanks for your patience @marktoman.

**Comment by botify** [comment]
The solution for this issue has been :rocket: deployed to production :rocket: in version 1.1.14-4 and is now subject to a 7-day regression period :calendar:. Here is the list of pull requests that resolve this issue:

- https://github.com/Expensify/App/pull/6084


If no regressions arise, payment will be issued on 2021-11-22. :confetti_ball:

**Comment by SofiedeVreese** [comment]
Hmm that's weird ^ It was already deployed 🤷

**Comment by mountiny** [comment]
This is because of the PR which fixed the regression. All good here.

**Comment by mountiny** [comment]
Oh actually looking into this more, https://github.com/Expensify/App/pull/6084#issuecomment-969396532 the original PR has been deployed to production just now so the comment was correct after all, so we have paid out prematurately here. It got delayed because of the week when we have not deployed. Nothing to do about it here, just noting for future.

**Comment by SofiedeVreese** [comment]
Ah darn it, ok that's good to know, thank you @mountiny !

**Comment by marktoman** [comment]
@mountiny @SofiedeVreese Just a hopefully redundant FYI: In case of a regression, I will continue being around :)

**Comment by mountiny** [comment]
@marktoman Let's hope it wont be needed 😊 but at the same time, I hope to see you working on new issues 🎉
