### ISSUE TITLE
[Offline mode] User is able to remove Workspace members while offline- Reported by: @Santhosh-Sellavel 

### ISSUE THREAD

**Issue by isagoico** [Expensify/App#6058]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Navigate to workspace settings 
2. Kill the internet connection
3. Navigate to manage members 
4. Select a member and click on remove

## Expected Result:
User should not be able to remove/add members while offline. If enabled, it should show a message about the offline status. 

## Actual Result:
User is able to remove members while offline. 

## Workaround:
None needed. Offline mode. 

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:**1.1.8-17

**Reproducible in staging?:** Yes 
**Reproducible in production?:** Yes 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/44479856/138803495-fc49cfc4-5cb3-441e-b14c-3f54a7e201c9.mp4

**Expensify/Expensify Issue URL:**

**Issue reported by:** @Santhosh-Sellavel 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1634766032028000

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mallenexpensify** [comment]
@michaelhaxhiu and I are meeting next week to discuss 'offline first'

**Comment by mallenexpensify** [comment]
Still on hold, meeting with Hax went well last week, should be able to get to this no later than end of *next* week

**Comment by mallenexpensify** [comment]
@michaelhaxhiu and I need to make progress on this.   Been slow going with holidays and vacation.

**Comment by mallenexpensify** [comment]
@michaelhaxhiu is working on the on/offline plan, more soon

**Comment by mallenexpensify** [comment]
Still holding

**Comment by mallenexpensify** [comment]
Still holding, leaving a weekly to remind @michaelhaxhiu and I we need to address in the new year

**Comment by mallenexpensify** [comment]
Still holding..

**Comment by mallenexpensify** [comment]
@michaelhaxhiu , thoughts on this? I might/should have some time the next weekish to work on

**Comment by michaelhaxhiu** [comment]
@mallenexpensify I'm still not ready to delve into this design doc yet, but if you have free cycles and want to kick it off, I'm sure I can pile in within the next 2-3 weeks!

**Comment by mallenexpensify** [comment]
We've started an initial discussion with a handful of folks, I anticipate it will be raised in a public, internal room soon then we'll have a better idea of how we want to proceed

**Comment by mallenexpensify** [comment]
Bumped to monthly cuz I'm not sure when we're going to get to

**Comment by michaelhaxhiu** [comment]
not overdue

**Comment by michaelhaxhiu** [comment]
not overdue

**Comment by michaelhaxhiu** [comment]
holding still

**Comment by michaelhaxhiu** [comment]
We intend to pay and close this GH.

**Comment by Santhosh-Sellavel** [comment]
Applied

**Comment by michaelhaxhiu** [comment]
done.
