### ISSUE TITLE
[HOLD for payment 2021-11-11] Payments - Remove label from payment options menu

### ISSUE THREAD

**Issue by isagoico** [Expensify/App#6074]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. On mobile navigate to settings > Payments
2. Tap on add new payment method

## Expected Result:
There should be no label in the popup menu. 

## Actual Result:
Comment from @shawnborton: I feel like the small label above the payment options menu doesn't really add anything valuable and also doesn't look great. 

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platform:

Where is this issue occurring?

- iOS
- Android
- Mobile Web

**Version Number:** 1.1.10-0

**Reproducible in staging?:** Yes 
**Reproducible in production?:** Yes 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

![image](https://user-images.githubusercontent.com/44479856/138995683-b509c334-3a2f-4f1c-9d62-2333d0fe8cfa.png)

**Expensify/Expensify Issue URL:**

**Issue reported by:** @shawnborton 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1635185564079700

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mallenexpensify** [comment]
Apologies for the delay, I was out late last week.  @parasharrajat is hired in Upwork and assigned here.

**Comment by ogumen** [comment]
From the accessibility perspective the visible label should be preserved, otherwise it will fail WCAG SC 3.3.2

**Comment by botify** [comment]
The solution for this issue has been :rocket: deployed to production :rocket: in version 1.1.13-2 and is now subject to a 7-day regression period :calendar:. Here is the list of pull requests that resolve this issue:

- https://github.com/Expensify/App/pull/6139


If no regressions arise, payment will be issued on 2021-11-11. :confetti_ball:

**Comment by parasharrajat** [comment]
Ping for 
![image](https://user-images.githubusercontent.com/24370807/134382258-0f298dd9-9bf7-45a5-bb51-2b02b66736bd.png)

**Comment by mallenexpensify** [comment]
Paid $250 in Upwork!  Thanks @parasharrajat
