### ISSUE TITLE
Desktop - Blank screen appears when exiting the onfido page in IOU flow

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#6082]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch Desktop app and login
2. Tap on [+] and select 'Send money" > enter amount > next
3. Enter email in the field 'Name, email or phone"
4. Tap on Continue for "Verify identity" page
5. Close 'Verify identity" modal

## Expected Result:
"Send to" modal page should be open.

## Actual Result:
App is shown blank screen after closing "Verify identity" page

## Workaround:
Unknown
## Platform:

Where is this issue occurring?

- Desktop App

**Version Number:** v1.1.10-0
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/139087734-2302e321-6806-4087-aeb5-a53c4a3d5001.mp4

**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by nickmurray47** [comment]
Tested on reguler web and the blank screen doesn't occur there in this flow, which makes me think we need to add `index.desktop.js` logic to the existing Onfido flow.

**Comment by mvtglobally** [comment]
Issue reproducible during KI retests.

**Comment by nickmurray47** [comment]
also going to demote for weekly for the time being considering this is behind a beta rn

**Comment by nickmurray47** [comment]
Going to put this back in the pool for now and can pick back up later

**Comment by luacmartins** [comment]
Issue is also present in the VBA flow. It doesn't seem to be a navigation issue, since it goes away when replacing the Onfido component. Looking for more help https://expensify.slack.com/archives/C03TQ48KC/p1637718164105600?thread_ts=1635347185.233000&cid=C03TQ48KC
