### ISSUE TITLE
Settings - Blank page opens when user navigates to Profile screen

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#6110]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1.Open the app
2. Login with existing account
3. Tap on user's avatar
4. Select "Profile"
## Expected Result:
Profile page should open
## Actual Result:
Blank page opens when user navigates to Profile screen

## Workaround:
Unknown
## Platform:

Where is this issue occurring?

- iOS
- Android

**Version Number:**  1.1.11-0
**Reproducible in staging?:** Yes
**Reproducible in production?:** No
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** https://user-images.githubusercontent.com/43996225/139373204-c72b808c-b820-4abe-a1d2-6c39ae9aefbc.mp4
**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by chiragsalian** [comment]
Nice, yup you are correct santhosh and your solution is good too. Since this is a deploy blocker i've gone ahead and created a PR so we can CP and inform QA to test soon.

**Comment by roryabraham** [comment]
[Fix](https://github.com/Expensify/App/pull/6114) for this was merged and will be deployed in `1.1.11-1`

**Comment by roryabraham** [comment]
This worked 🎉
