### ISSUE TITLE
Prevent layout shift caused by the AddressSearch dropdown

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#6116]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. On NewDot, navigate to `/bank-account/company`
2. In the address field, start typing an address.
3. Notice that as the dropdown shows up, it shifts the entire form down.

https://user-images.githubusercontent.com/22219519/139494999-86b7862b-6ca3-4105-881c-a498becc7041.mov

## Expected Result:
The form shouldn't shift.

## Actual Result:
The form shifts.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround? Yes, layout only.

## Platform:
- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:**
**Reproducible in staging?:**
**Reproducible in production?:**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by luacmartins** [comment]
@Expensify/design is this something we should fix?

**Comment by shawnborton** [comment]
Agree, the dropdown should be absolutely positioned on top of the other elements. Maybe we should even give it a bit of a shadow too to create some more visual separation as well.

**Comment by luacmartins** [comment]
Thanks for confirming @shawnborton! I'm coming across an edge case when:

1. The dropdown is too close to the bottom of the screen
![Screen Shot 2021-11-01 at 3 58 25 PM](https://user-images.githubusercontent.com/22219519/139747974-22d06c5c-7f72-48a2-a65c-2253ab2cfeca.png)

2. The input is inside a nested form. 
![Screen Shot 2021-11-01 at 3 57 56 PM](https://user-images.githubusercontent.com/22219519/139747968-5a77014e-5d9e-429b-b4bd-38a2021d98be.png)

The library we are using does not expose a way to limit the maximum number of results (so we always display 5 if there are enough matches). One suggestion that I have is to display the dropdown show above the input in those cases. Any thoughts here?
![Screen Shot 2021-11-01 at 4 01 50 PM](https://user-images.githubusercontent.com/22219519/139748055-f37ccc0d-943f-46bf-a707-8ee378656fe1.png)

**Comment by shawnborton** [comment]
Displaying above is interesting - how might that look on mobile? Are we able to get the text input to be focused and scrolled directly above the keyboard so that there is ample room for the results?

**Comment by luacmartins** [comment]
Hmm my suggestion might have issues with shorter forms. If the form is short there isn't enough room for the dropdown above the input and we can't scroll, so the view is either cut at the bottom or at the top. Here's an example:
![Screen Shot 2021-11-01 at 6 15 08 PM](https://user-images.githubusercontent.com/22219519/139759164-34faf9eb-6e77-4b3e-ae4b-99844892f0ef.png)
![Screen Shot 2021-11-01 at 6 09 24 PM](https://user-images.githubusercontent.com/22219519/139759162-8ebc0235-5d22-47a4-8b45-c07a955e4adc.png)

Now I'm not too sure how to solve this one. Any ideas @shawnborton?

**Comment by shawnborton** [comment]
Hmm the only thing I can think of is to always launch the form to the bottom of the input and try to scroll the input towards the top of the viewport as much as possible.

**Comment by luacmartins** [comment]
Still not sure how to approach the edge cases here. I'm gonna try to come back to this one next week.

**Comment by luacmartins** [comment]
Haven't made any progress here yet. I will try to look into it next week.

**Comment by parasharrajat** [comment]
I have a suggestion. :chipmunk:  :clown_face: 

The issue with the approach we are exploring so far.
- This just doesn't work for mobile.
- This will not fit the mobile web (we don't know the resolution of the device). This becomes worse when the keyboard is Open.
- There would be positioning challenges.

I think we should create a new screen for selecting the address and show the Address selector as it is on that screen.
1. Show a read-only input in this form whose UI does not change.
2. When a user clicks it, Open the new page with a single input on the top where the user can select the address and press enter.
3. On Press of entering, he would come back to this screen and that read-only input would be filled with selected address.

**Comment by shawnborton** [comment]
I like that idea, it reminds me of how Google Maps handles adding in addresses for directions.

**Comment by luacmartins** [comment]
Sounds like a good idea! I'll do some more thinking on how to handle the [manual address input solution](https://github.com/Expensify/App/pull/6200) we are implementing.

**Comment by luacmartins** [comment]
I will try to carve out some time to work on this issue this week!

**Comment by luacmartins** [comment]
I actually discussed this 1:1 with @marcaaron. Since nothing is broken and the solution at hand is really involved and hard to maintain, we will just close this for now.
