### ISSUE TITLE
Adding a phone login sends a /v/<accountID>/<validateCode> link but this route was removed

### ISSUE THREAD

**Issue by marcaaron** [Expensify/App#6136]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Add phone login
2. Get text message
3. See link has `/v/<accountID>/<validateCode>` syntax
4. Tap it and brought to app but nothing happens (route doesn't exist)

## Expected Result:

1. Validate code is passed to `validateLogin()` and the secondary login gets added ? cc @NikkiWines 

## Actual Result:
Nothing happens

## Workaround:
They can't add a phone login

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:**
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by iwiznia** [comment]
hmmm is the problem that the app should not be opening that link at all? Or what is the expected behavior when the app opens it?

**Comment by marcaaron** [comment]
>hmmm is the problem that the app should not be opening that link at all

We send you a link and it opens the app, but does not validate your secondary login. Because the link we send has no corresponding route so it is like a very basic deep link that does nothing but open the app. The expected behavior is that your secondary login will get automatically validated.

**Comment by roryabraham** [comment]
I'll add the validate route back, then we should make sure this flow is added to the regression testing suite.

**Comment by marcaaron** [comment]
>Alternatively, we could do that in oldDot, that already should have a page for that, no?

AFAIK the design that was implemented was to have the user return to NewDot - so unsure if we should change that. But maybe @NikkiWines has thoughts on this.

**Comment by NikkiWines** [comment]
The original implementation had the user routed back to NewDot if they initiated adding the secondary login from NewDot - I don't think we should change it so they're routed to OldDot. Seems like a weird flow for them to go through
