### ISSUE TITLE
VBA - Dropdown arrow non functional in zip code field for company info page

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#6324]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
Issue was found when executing #6210
## Action Performed:
1. Launch the app and login
2.Open the workspace and click Connect Bank account
3.Make it to the Company information step
4.Click on Can't find your address? Enter it manually link
5.Click the dropdown arrow in zipcode field

## Expected Result:
Dropdown arrow functional and on clicking states to select displayed
## Actual Result:
Dropdown arrow non functional
## Workaround:
Unknown
## Platform:

Where is this issue occurring?

- Web
- Desktop App
- Mobile Web

**Version Number:** 1.1.15.1
**Reproducible in staging?:** Yes 
**Reproducible in production?:** New feature and not able to check in production with staging credentials
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 
Issue was found when executing #6210

https://user-images.githubusercontent.com/43996225/142027180-6f1bb5ea-8d93-4682-92ca-e06f73563618.mp4

**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by luacmartins** [comment]
Removing the Deploy Blocker label as the issue is minor and already on staging and production. Gonna try to work on a fix asap.

**Comment by luacmartins** [comment]
PR up!
