### ISSUE TITLE
Profile - Messaging an account not created will display an unconfirmed time zone

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#6428]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open app and login
2. Start a chat with an account not created yet
3. Tap on its profile icon

## Expected Result:
Profile is opened and only confirmed information is shown

## Actual Result:
Profile tab is opened and it shows PST time zone, which is an information not known nor confirmed

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.16-1
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/143069648-49d48994-a73f-4b26-a45c-7a4f588184ee.mp4

**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by parasharrajat** [comment]
I would say that I already raised it here https://github.com/Expensify/App/issues/4771 but CME was not able to reproduce it at that time. Probably we can now with these steps. 
So I suggest opening that issue and adding this info to that issue.

**Comment by ctkochan22** [comment]
Just tried to reproduce, couldn't reproduce on dev, staging, or prod. Could have been fixed?
