### ISSUE TITLE
Disable landscape view on phones

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#6568]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
Coming from this thread https://expensify.slack.com/archives/C01GTK53T8Q/p1638473174146400?thread_ts=1638471596.142900&cid=C01GTK53T8Q

## Action Performed:
1. Launch the app and rotate your phone to landscape view.
2. Notice that the app goes into landscape mode.

Note that landscape should still be supported on tablets.

## Expected Result:
App should stay in portrait mode.

## Actual Result:
App rotates to landscape mode.

## Workaround:
None needed. App still works.

## Platform:

Where is this issue occurring?

- iOS
- Android

**Version Number:**
**Reproducible in staging?:**
**Reproducible in production?:**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by dklymenk** [comment]
Hi, if you decide to make this issue external I am willing to submit a PR for it.

To lock the portrait orientation on iPhones the go to approach is to toggle the check boxes in xcode to make it so all the device orientations are enabled on iPad and only portrait is enabled on iPhone.
![image](https://user-images.githubusercontent.com/64093836/144618756-62c79200-acfd-4b74-a3ab-746d4fb90f29.png)
![image](https://user-images.githubusercontent.com/64093836/144618775-c416efed-7dbd-4fb2-b036-3bcc7b479dcf.png)

This would result in a following diff where for all devices only the portrait orientation is enabled, but for iPad all 4 are enabled.
```diff
diff --git a/ios/NewExpensify/Info.plist b/ios/NewExpensify/Info.plist
index 909b907a7..81b7792f8 100644
--- a/ios/NewExpensify/Info.plist
+++ b/ios/NewExpensify/Info.plist
@@ -102,6 +102,10 @@
                <string>armv7</string>
        </array>
        <key>UISupportedInterfaceOrientations</key>
+       <array>
+               <string>UIInterfaceOrientationPortrait</string>
+       </array>
+       <key>UISupportedInterfaceOrientations~ipad</key>
        <array>
                <string>UIInterfaceOrientationPortrait</string>
                <string>UIInterfaceOrientationLandscapeLeft</string>
 ```
 
 Sadly, for android the situation is worse. You are allowed to add `android:screenOrientation=“portrait”` to `AndroidManifest.xml`, but this will apply to all devices regardless of their screen size, so for that I would suggest using a lib that would hook into native apis to allow setting the orientation from javascript - https://github.com/wonday/react-native-orientation-locker. Using that in combination with https://github.com/react-native-device-info/react-native-device-info would allow us to do something like this:
 ```js
 if (!isTablet()) {
     lockToPortrait()
 }
 ```
 
I would need to think of a good place for this code to make sure it doesn't run on ios or web, but overall it should work.

Installing 2 libraries to archive a behaviour as simple as this sounds sub-optimal, so maybe there is a better solution. Alternatively, we might just lock the portrait orientation on all android devices with `AndroidManifest.xml` .

**Comment by luacmartins** [comment]
Thanks for the input @dklymenk! I will keep this as internal for now.
