### ISSUE TITLE
Update request a call page functionality to match Old Dot

### ISSUE THREAD

**Issue by puneetlath** [Expensify/App#7067]
The request a call modal on Old Dot has some functionality that isn't there on New Dot. Let's add it to bring feature parity: 

- Extension field 
- Dynamic messaging in subtext based on when the call is requested and current wait time
- API call to get current wait time 

Because of the new API call, this will need to be internal. 

Current New Dot: 
![image](https://user-images.githubusercontent.com/1371996/148453794-7135b78e-c51e-4ea3-be37-8bbbeae9e445.png)

Current Old Dot: 
![image](https://user-images.githubusercontent.com/1371996/148453831-1c786c6d-39c0-40fb-a33d-9cb58002157f.png)

cc @kevinksullivan

**Comment by neil-marcellini** [comment]
Puneet kindly gave me this issue.
