### ISSUE TITLE
Deploy success message is posted even if multiple platforms fail

### ISSUE THREAD

**Issue by Jag96** [Expensify/App#7163]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Run a deploy, see that some builds failed
2. See message in #announce saying that the deploy failed
3. Immediately see success message after
![image](https://user-images.githubusercontent.com/3981102/149200050-bf7823c0-6ed8-44bf-ac0d-89f4dac990d9.png)

## Expected Result:
We should show a table with the result of each deploy similar to what we post in GH, or at least show similar info

![image](https://user-images.githubusercontent.com/3981102/149200110-67f016cc-0542-4572-a62b-fdd37cffb4a8.png)

cc @Expensify/mobile-deployers

**Comment by luacmartins** [comment]
I'll be ooo for the rest of this week. I'll come back to this next week.

**Comment by luacmartins** [comment]
Had other N7 issues that took priority over this. I'll try to get to it next week.

**Comment by luacmartins** [comment]
I'll try to get to this next week.

**Comment by luacmartins** [comment]
PR up!

**Comment by luacmartins** [comment]
Closing in favor of https://github.com/Expensify/App/issues/8199
