### ISSUE TITLE
Web - App downloading links - Clicking on mac OS link opens another tab

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#7189]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue was found when executing #7132**
## Action Performed:
1. Open https://staging.new.expensify.com
2. Navigate to Settings > About > App download links > MacOS

## Expected Result:
Option to download the app should appear

## Actual Result:
Another new.dot tab opens

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- Mobile Web
-  iOS

**Version Number:** v1.1.29-2
**Reproducible in staging?:** Yes 
**Reproducible in production?:** No
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 
**Issue was found when executing #7132**

![Bug5404960_Screen_Shot_2022-01-12_at_6 09 52_PM](https://user-images.githubusercontent.com/43996225/149244798-4a385a3d-03e2-4362-80ae-d5b2359efccf.png)

https://user-images.githubusercontent.com/43996225/149244806-199d1f06-6bd3-43a7-9253-d6db705610dd.mp4

**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by parasharrajat** [comment]
My PR is failing https://github.com/Expensify/App/pull/7132. It's that damn `//` slash. Sending the fix now.

**Comment by parasharrajat** [comment]
@Gonals  https://github.com/Expensify/App/pull/7194. CP it. Thanks.

**Comment by Jag96** [comment]
This has been fixed and is being deployed to staging, closing
