### ISSUE TITLE
mweb Safari - Chat - Download icon is overlapping with text in Preview

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#7204]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to https://staging.new.expensify.com
2. Log in with any account which has picture attachment
3. Tap on attachment which has longer name to preview

## Expected Result:
Download icon isn't overlapping with text in Preview

## Actual Result:
Download icon is overlapping with text in Preview

## Workaround:
Visual

## Platform:

Where is this issue occurring?

- Mobile Web

**Version Number:** 1.1.29-2
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 
![Bug5405614_Image_from_iOS__2_](https://user-images.githubusercontent.com/43996225/149346098-9865cd2e-eb57-4ec4-9e51-f14b28a5b4ec.jpg)

**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Beamanator** [comment]
Definitely can be worked externally 👍

**Comment by parasharrajat** [comment]
This will be indirectly fixed from https://github.com/Expensify/App/pull/7097. So let's wait before exporting.

**Comment by Beamanator** [comment]
Ooh nice good catch 👍

**Comment by michaelhaxhiu** [comment]
Cool, seems like this won't get assigned or paid out in that case. Right?

**Comment by michaelhaxhiu** [comment]
Meaning, it won't be exported at all? I'll keep it assigned until https://github.com/Expensify/App/pull/7097 is done.

**Comment by Beamanator** [comment]
Yeah I think you're right, as long as the PR you linked does fix this too :D

**Comment by michaelhaxhiu** [comment]
Yep, good point. I think it's ideal to have QA re-test this after the PR is live.

**Comment by michaelhaxhiu** [comment]
Update - still waiting on https://github.com/Expensify/App/pull/7097 and then we can test to see if this is still a problem.

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by michaelhaxhiu** [comment]
That's 1 week, good to close this then!
