### ISSUE TITLE
[Discussion] No mutually exclusive boolean props

### ISSUE THREAD

**Issue by roryabraham** [Expensify/App#7220]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

Coming from [here](https://github.com/Expensify/App/pull/6856#discussion_r782409028), I'm proposing a new code style guideline: "No mutually exclusive boolean props".

What I mean by this is that we should ban the use of boolean props that are meant to be mutually exclusive: i.e: instead of having `small`, `medium`, `large` each be their own separate boolean props, create a single `size` prop that's `PropTypes.oneOf(['small', 'medium',  'large'])`.

This prevents unpredictable behavior in the event that two mutually exclusive boolean props are passed as the same time.

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by marcaaron** [comment]
This sounds good to me if the alternative is having both `isSmall` and `isLarge` as separate props. 

Are there other examples?

**Comment by roryabraham** [comment]
None that come to mind

**Comment by parasharrajat** [comment]
We can take the Button component as an example. It has three Boolean props `small`, 'medium' and 'large'. 

What Rory suggested above is to create a single prop `size` which will accept above mentioned values are strings.

**Comment by roryabraham** [comment]
> What Rory suggested above is to create a single prop size which will accept above mentioned values are strings.

Yeah, this makes more sense to me. Since I couldn't find other examples for the time being, I would be fine doing nothing here 🤷 It's not really a problem we should prioritize atm.

**Comment by tgolen** [comment]
I like the idea, and as long as we can find an example of it in our code, then let's do it!
