### ISSUE TITLE
The triggerWorkflowAndWait action does not correctly link to the triggered workflow

### ISSUE THREAD

**Issue by roryabraham** [Expensify/App#7239]
## Problem
The `triggerWorkflowAndWait` action lists the ID of the triggered workflow, but not an html link to the workflow running:

![image](https://user-images.githubusercontent.com/47436092/149577289-b2328a11-f973-4b82-850d-a8a35fa4a44b.png)

This makes it harder to follow along what's happening.

## Why this is important
This is a QOL improvement for our deployers.

## Solution
Include the HTML url for the workflow run in the log output in addition to the workflow run ID

**Comment by roryabraham** [comment]
cc @Expensify/mobile-deployers if anyone wants this simple QOL improvement.

**Comment by AndrewGable** [comment]
I'll take it!
