### ISSUE TITLE
[$250] Race condition with the CP Staging label

### ISSUE THREAD

**Issue by roryabraham** [Expensify/App#7284]
Coming from https://github.com/Expensify/App/pull/7255 ...

### Problem
There exists a race condition when the `CP Staging` is applied to a pull request after it's merged. Both of the following are possible:

1. When the merged pull request is fetched [here](https://github.com/Expensify/App/blob/b2dbefabfa40249aaabae23d1fdf4b591765ecbe/.github/workflows/preDeploy.yml#L25), it already has the `CP Staging` label, and is deployed to staging.
1. When the merged pull request is fetched in the location listed above, it does not have the `CP Staging` label, and is not deployed to staging.

In both scenarios, a comment that looks like this will be left on the pull request:

![image](https://user-images.githubusercontent.com/47436092/149822025-aab167bc-0831-416c-93d5-edc438f7faf5.png)

### Why this is important
In the second scenario, this is confusing because the expected behavior/whether or not the pull request was CP'd to staging is unclear.

### Solution
Update the [warnCPLabel.yml](https://github.com/Expensify/App/blob/b2dbefabfa40249aaabae23d1fdf4b591765ecbe/.github/workflows/warnCPLabel.yml) workflow to tailor its comment based on whether or not the `CP Staging` label was applied to the pull request when it was already merged.

- If the pull request not yet merged, keep the same comment.
- If the pull request is already merged, use the following comment:
    1. Find the `preDeploy.yml` workflow run for the pull request. 
    1. List jobs for that workflow run and find the `skipDeploy` job.
    1. If the conclusion of that job is not resolved, poll the API until it is resolved.
    1. If the conclusion is `success` or something else, use the following comment:
    
	      ---
	      
	      :warning: **Heads up!** :warning: Since the `CP Staging` label was applied _after_ this PR was merged, it was not CP'd to staging. If you need it to be deployed to staging, tag a member of @Expensify/mobile-deployers to CP it manually.
	      
	      ---
    
    1. If the conclusion is `skipped`, use the following comment:
    
	      ---
	      
	      :warning: **Heads up!** :warning: The `CP Staging` label was applied _after_ the PR was merged. This leads to unpredictable behavior. In this case this PR will be deployed to staging, but to guarantee this in the future be sure to apply the `CP Staging` _before_ merging the pull request.
	      
	      --- 
## Upwork Automation - Do Not Edit
- Upwork Job URL: https://www.upwork.com/jobs/~0131b521e37dc4e067
- Upwork Job ID: 1593348486831874048

**Comment by roryabraham** [comment]
This is pretty low priority, no update.

**Comment by roryabraham** [comment]
Again no update.

**Comment by roryabraham** [comment]
No update

**Comment by roryabraham** [comment]
No update

**Comment by roryabraham** [comment]
No update

**Comment by puneetlath** [comment]
@mateocole no I think this will need to be handled internally by @roryabraham or someone else.

**Comment by arielgreen** [comment]
Is this actually a bug or is it a new feature? If it's a bug, is it reproducible and can it therefore be assigned to the demolition team? @mateocole can you look into this and figure out what needs to be done to push this forward?

**Comment by mateocole** [comment]
@arielgreen looking at this from a P/S statement it looks like a feature but I'll wait for @roryabraham to clarify

**Comment by roryabraham** [comment]
Typically GitHub Actions stuff is handled internally, but in this case I think it might be fine to make external, especially since there's a pretty clear implementation plan above ^

**Comment by roryabraham** [comment]
It's weird that this assigned @iwiznia, since I was already assigned to the issue so should've been an eligible CME. Unassigning you @iwiznia!

Also going to remove the C+ review on this issue and PR. Because they can't really test the PR anyways, it's just not as valuable

**Comment by mateocole** [comment]
Job posted- https://www.upwork.com/ab/applicants/1591235610161598464/job-details

**Comment by roryabraham** [comment]
Waiting for proposals

**Comment by puneetlath** [comment]
@cead22 taking this internal given the age of the issue as discussed [here](https://expensify.slack.com/archives/CC7NECV4L/p1668711272916389). Please try to move this forward with urgency so that we can get WAQ done!

@mollfpr sorry for the confusion. This should be Internal.

**Comment by cead22** [comment]
Started a discussion about the solution here https://expensify.slack.com/archives/C03TQ48KC/p1669054325132319

**Comment by roryabraham** [comment]
This is fixed
