### ISSUE TITLE
[TEST] Test issue 2 for 191398

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#7336]
Do not mind this issue, this is a test for https://github.com/Expensify/Expensify/issues/191398

**Comment by mountiny** [comment]
Sorry for the pings @rushatgabhane, I am testing one QA related to linking issues to PRs.

**Comment by rushatgabhane** [comment]
haha, no worries :)

**Comment by mountiny** [comment]
QA has passed, closing.
