### ISSUE TITLE
'.' is not recognized as an internal or external command,

### ISSUE THREAD

**Issue by osama256** [Expensify/App#7457]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
after cloning the App and npm install I get this error :

C:\Expensify\App>npm i
> new.expensify@1.1.33-3 postinstall
> ./build/react-native-web.sh

'.' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code 1
npm ERR! path C:\Expensify\App
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c ./build/react-native-web.sh
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\osama\AppData\Local\npm-cache\_logs\2022-01-28T21_01_27_821Z-debug.log

## Expected Result:
after cloning the App and writing npm install all modules should install successfully without any issue.

## Actual Result:
Describe what actually happened
after cloning the App and type npm install i get the following error:
'.' is not recognized as an internal or external command,

and this is the log file outs:
14908 timing reify:trash Completed in 0ms
14909 timing reify:save Completed in 3287ms
14910 timing reify Completed in 1048863ms
14911 timing command:install Completed in 1048908ms
14912 verbose stack Error: command failed
14912 verbose stack     at ChildProcess.<anonymous> (C:\Users\osama\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\promise-spawn\index.js:64:27)
14912 verbose stack     at ChildProcess.emit (node:events:394:28)
14912 verbose stack     at maybeClose (node:internal/child_process:1064:16)
14912 verbose stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
14913 verbose pkgid new.expensify@1.1.33-3
14914 verbose cwd C:\Expensify\App
14915 verbose Windows_NT 10.0.19042
14916 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\osama\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "i"
14917 verbose node v16.8.0
14918 verbose npm  v7.12.0
14919 error code 1
14920 error path C:\Expensify\App
14921 error command failed
14922 error command C:\WINDOWS\system32\cmd.exe /d /s /c ./build/react-native-web.sh
14923 verbose exit 1
## Workaround:
User can use Expensify without this being fixed
## Area issue was found in:
when trying to install node_modules

## Failed WCAG checkpoints
What WCAG checkpoints were failed?

## User impact:
it doesn't affect the user
## Suggested resolution:
What can we do to fix the issue?
I don't know
## Platform:

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:1.1.32-0**
**Reproducible in staging?:**
**Reproducible in production?:**
**Notes/Photos/Videos:** Any additional supporting documentation
**Issue reported by:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Sheharyar566** [comment]
Hi there... were you able to fix the issue?

**Comment by osama256** [comment]
@Sheharyar566 this issue happens  in windows and I skipped it by removing this line from package.json

`"postinstall": "scripts/react-native-web.sh && cd desktop && npm install",`
