### ISSUE TITLE
Flash on the screen where the input field, when switch to a chat user has't been in for a while

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#7467]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open App 
2. Open Open some chat and leave it 
3. Navigate back to same chat after a long time  

## Expected Result:
There should be no visual distortions 

## Actual Result:
When user switches to a chat where haven't been in for a while, user sees a flash on the screen where the input field isn't there at first and then it appears, pushing all the text up.

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Desktop App

**Version Number:** 1.1.30-3
**Reproducible in staging?:** 
**Reproducible in production?:** Y 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 
n/a
**Expensify/Expensify Issue URL:**
**Issue reported by:** @rafecolton 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1642644889225900

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by rafecolton** [comment]
It's not really a flash per se. What I see is when I open the app fresh:
* Sometimes the main panel is blank (all white)
* When I switch to a new chat, first it is blank, then the chat appears but it goes all the way to the bottom, no input field
* Then the input field appears
* Sometimes, the main panel shows a chat with a different person or is blank, and clicking on other chats doesn't cause them to populate that main window. I have to refresh several times to get it to do so.

**Comment by isagoico** [comment]
I was able to reproduce something similar to this today when first login in to the app in Chrome. No errors were displayed in console. 
![image](https://user-images.githubusercontent.com/44479856/151898450-911ca488-ed3a-4703-832a-48c3b61211ac.png)

**Comment by mallenexpensify** [comment]
Reopening cuz experienced this twice this morn. Both were with someone I haven't chatted with before, was able to capture vid of the second time.  No errors in logs. @rafecolton is this what you were experiencing? Curious if we should use this issue (I can update title/OP if so) or open a new issue

Repro steps
- Open a chat with someone you never have chatted with before. 
- Observe the flash for "Hmm... It's not here" (at the 20 second mark  in the vid below)

https://user-images.githubusercontent.com/22508304/199575187-1c0903f3-b906-4b20-9213-e16b3f02656e.mp4

**Comment by mallenexpensify** [comment]
@mvtglobally can you see if you can reproduce based on my post above?

**Comment by mallenexpensify** [comment]
@lschurr can you see if you can reproduce?  I'm OOO for a month
- If so, can you add the `Engineering` label. 
- If not, see if @kbecciv can repro. If they can, add the `Engineering` label.  If not, please close

**Comment by lschurr** [comment]
I wasn't able to reproduce this. Opening a chat with someone I haven't chatted with before worked fine. Adding eng for another set of eyes.

**Comment by lschurr** [comment]
@kbecciv - are you able to reproduce this?

**Comment by kbecciv** [comment]
@lschurr Let me check with team and I will get back to you shortly.

**Comment by kbecciv** [comment]
Issue is not reproduced, build 1.2.26.0

https://user-images.githubusercontent.com/93399543/201205433-73f14442-1992-455c-b721-72814b3a026d.mp4


https://user-images.githubusercontent.com/93399543/201205440-b3fc8166-4305-4ec3-b0c3-9caa28273d0b.mp4

**Comment by lschurr** [comment]
Great, going to close. Thanks!
