### ISSUE TITLE
If you send 2 consecutive message the second message auto-repeated - Reported by @Ahmed sherif

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#7473]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open app
2. Type text, enter and quickly type again 

## Expected Result:
User messages should be independent and should not repeat 

## Actual Result:
If you write "world" speedy after you press send for "hello". Happens when you write speedy on physical keyboard.
 
## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Web
- Desktop App

**Version Number:** 1.1.33-0
**Reproducible in staging?:** N 
**Reproducible in production?:** N 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:**
**Issue reported by:** @ahmdshrif 
**Slack conversation:**  https://expensify.slack.com/archives/C01GTK53T8Q/p1642782464276900

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mvtglobally** [comment]
potentially related to https://github.com/Expensify/App/issues/4129

**Comment by ahmdshrif** [comment]
hi, @mvtglobally I can't ' reproduce this on the web again (the text input gets unfocus when we send the message)  but still can have it mobile(android and ios).
 
to reproduce it just type any character when you send the message.
it will send the message 
and keep the old message with the entered character in the text box.

as a proposal if external. 
I suggest that we unfocus the text input in native also when we send button is pressed,  
and refocus it when the message is sent. ( so we will flow web behavior )
