### ISSUE TITLE
Unable to invite user via phone number to a Workspace

### ISSUE THREAD

**Issue by NicMendonca** [Expensify/App#7500]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Invite user from workspace
2. Enter Phone Number
3. Click Invite
4. Observe error message "an error occurred inviting user to workspace, please try again"

## Expected Result:
User should be invited via their phone number

## Actual Result:
"an error occurred inviting user to workspace, please try again"

![image](https://user-images.githubusercontent.com/24947345/152017766-6959e725-d473-4cb4-b4ee-45c3038fff2f.png)

## Workaround:
They can try inviting user via email address

## Platform:
- Web

**Version Number:** v1.1.32-0
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:** https://github.com/Expensify/Expensify/issues/193446
**Issue reported by:** @laurenreidexpensify 
**Slack conversation:** n/a

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mvtglobally** [comment]
@chiragsalian  Not sure if this is related, but SMS account creation is blocked and SMS users can't be added to policy and its expected 
https://github.com/Expensify/Expensify/issues/189976

**Comment by NicMendonca** [comment]
Yep, sorry! Going to close this.
