### ISSUE TITLE
Audit forms and fix inconsistencies with autofill behavior

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#7529]
We should audit all our forms and fix any inconsistencies with autofill behavior. The expected behavior is as follows:

1. Forms should autofill information whenever possible i.e. they should work with browsers and password managers auto complete features.
2. As a best practice we should avoid asking for information we can get via other means e.g. asking for City, State, and Zip if we can use Google Places to gather information with the least amount of hassle to the user.

Here's a list of forms to be audited:

- [x] [AddPlaidBankAccount.js](https://github.com/Expensify/App/blob/main/src/components/AddPlaidBankAccount.js)
- [x] [ACHContractStep.js](https://github.com/Expensify/App/blob/main/src/pages/ReimbursementAccount/ACHContractStep.js)
- [x] [BankAccountStep.js](https://github.com/Expensify/App/blob/main/src/pages/ReimbursementAccount/BankAccountStep.js)
- [x] [CompanyStep.js](https://github.com/Expensify/App/blob/main/src/pages/ReimbursementAccount/CompanyStep.js)
- [x] [RequestorStep.js](https://github.com/Expensify/App/blob/main/src/pages/ReimbursementAccount/RequestorStep.js)
- [x] [ValidationStep.js](https://github.com/Expensify/App/blob/main/src/pages/ReimbursementAccount/ValidationStep.js)
- [x] [Workspace - Invite new members](https://github.com/Expensify/App/blob/main/src/pages/workspace/WorkspaceInvitePage.js)
- [x] [Workspace - General settings](https://github.com/Expensify/App/blob/main/src/pages/workspace/WorkspaceSettingsPage.js)
- [x] [IOU confirmation page](https://github.com/Expensify/App/blob/30118b75ba9693ee5518464c8d7073a9c6883b19/src/components/IOUConfirmationList.js)
- [x] [KYC flow](https://github.com/Expensify/App/blob/30118b75ba9693ee5518464c8d7073a9c6883b19/src/pages/EnablePayments/AdditionalDetailsStep.js)
- [x] [New Room screen](https://github.com/Expensify/App/blob/main/src/pages/workspace/WorkspaceNewRoomPage.js)
- [x] [Add Debit card flow](https://github.com/Expensify/App/blob/main/src/pages/settings/Payments/AddDebitCardPage.js)
- [x] [Add Personal Bank account flow](https://github.com/Expensify/App/blob/30118b75ba9693ee5518464c8d7073a9c6883b19/src/components/AddPlaidBankAccount.js)
- [x] [Settings - Change Password](https://github.com/Expensify/App/blob/30118b75ba9693ee5518464c8d7073a9c6883b19/src/pages/settings/PasswordPage.js)
- [x] [Settings - Profile](https://github.com/Expensify/App/blob/30118b75ba9693ee5518464c8d7073a9c6883b19/src/pages/settings/Profile/ProfilePage.js)
- [x] [Login form](https://github.com/Expensify/App/blob/main/src/pages/signin/LoginForm.js)
- [x] [Password form](https://github.com/Expensify/App/blob/main/src/pages/signin/PasswordForm.js)
- [x] [Set password](https://github.com/Expensify/App/blob/main/src/pages/SetPasswordPage.js)
- [x] [New password form](https://github.com/Expensify/App/blob/30118b75ba9693ee5518464c8d7073a9c6883b19/src/pages/settings/NewPasswordForm.js)
- [x] [Request a Call modal](https://github.com/Expensify/App/blob/main/src/pages/RequestCallPage.js)

**Comment by neil-marcellini** [comment]
👀

**Comment by neil-marcellini** [comment]
[ACHContractStep.js](https://github.com/Expensify/App/blob/main/src/pages/ReimbursementAccount/ACHContractStep.js) autofills information correctly in Chrome, but I did notice that it looked weird when I was hovering over the autofill suggestion because the autofill content overlaps with the placeholder text. Fixing this is probably low priority since most users only hover the suggestion for a very small amount of time, but here is what it looks like:
<img width="1728" alt="Screen Shot 2022-02-15 at 1 25 19 PM" src="https://user-images.githubusercontent.com/26260477/154152678-67d07bf2-f29f-4de3-83f7-556107460aaf.png">
As soon as I click on the suggestion everything fills in and the placeholders move up.

**Comment by neil-marcellini** [comment]
These are the only two pages that I found where there should be autofill and it doesn't work.
- [ ] [Settings - Profile](https://github.com/Expensify/App/blob/30118b75ba9693ee5518464c8d7073a9c6883b19/src/pages/settings/Profile/ProfilePage.js) The first name and last name do not show an autofill prompt.
- [ ] [Request a Call modal](https://github.com/Expensify/App/blob/main/src/pages/RequestCallPage.js) The first name, last name, and the phone number do not autofill.

I only tested on Chrome. Do I need to run through these checks on all platforms and on other browsers or is this good?

**Comment by luacmartins** [comment]
Great work @neil-marcellini! Thanks for auditing all the forms. Do you wanna work on a fix for those two forms? If not, we should create issues for them and assign them out to contributors.

>I only tested on Chrome. Do I need to run through these checks on all platforms and on other browsers or is this good?
I think this is fine.

**Comment by neil-marcellini** [comment]
Yeah I would like to work on a fix. Should I fix it as is or use the new form component to fix it?

**Comment by luacmartins** [comment]
Form inputs are not refactored yet, so this will have to be fixed using the old forms.
