### ISSUE TITLE
Set default wallet payment method when one card/account exists

### ISSUE THREAD

**Issue by kevinksullivan** [Expensify/App#7613]
# Problem

Coming from [this conversation](https://expensify.slack.com/archives/C02NZ2HGJAZ/p1643834892220039?thread_ts=1643638216.390969&cid=C02NZ2HGJAZ), a user is forced to pick the bank account/card they want to transfer their balance to, even when they only have one bank account/card associated with their Expensify account. This is an unnecessary step in the likely situation where they want to transfer to the one account/card they added.

![image](https://user-images.githubusercontent.com/22508290/152883444-230edfec-3286-498b-be21-4b2de23ba0e8.png)

![image](https://user-images.githubusercontent.com/22508290/152883494-5b084d3b-b329-4f12-bafe-bc2e87d5cabf.png)

# Solution
Let's set the default payment method when only one bank account or card is associated with a user's Expensify account, but not show the "Default" badge until there are multiple accounts/cards to choose from.

**Comment by marcaaron** [comment]
Technically this is a few issues - but I'll use this one to track them:

- [ ] Make sure to set a default automatically whenever it is added (back end change)
- [ ] Only show a default badge when there are more than 1 payment methods (front end change)
- [ ] Skip account selection screen when there is only one option (front end change)

**Comment by marcaaron** [comment]
Ah, so first bullet is on prod now.
Joel has a PR that should solve the second bullet that's in review.
I can look into the default badge change next - should be pretty small.

**Comment by marcaaron** [comment]
Just merged https://github.com/Expensify/App/pull/7767 which fixes

>Only show a default badge when there are more than 1 payment methods (front end change)

And waiting for it to go on staging. Joel's PR [here](https://github.com/Expensify/Auth/pull/6412) is also on Production now so that takes care of the second bullet.

**Comment by marcaaron** [comment]
Last PR still on staging.

**Comment by marcaaron** [comment]
Looks like all related PRs are done here.
