### ISSUE TITLE
App hangs when loading on web/desktop due to infinite loop

### ISSUE THREAD

**Issue by tgolen** [Expensify/App#7630]
# Problem
For some people (@joekaufmanexpensify @luacmartins) when they load App, the code goes into a seemingly infinite loop that hangs the browser for a long time.

![image](https://user-images.githubusercontent.com/1228807/153035479-d560a4ae-1d76-445c-8dc8-c1960bab7667.png)

# Why is this important?
It makes the app unusable

# Solution
Determine what is causing the loop and find a way to fix it

**Comment by tgolen** [comment]
I am able to determine that the long loop happens here: https://github.com/Expensify/App/blob/47ec8f4ae0598e55c4d75b275ef4feeec8f14d6e/src/libs/actions/Report.js#L446

The method `PersonalDetails.getFromReportParticipants(simplifiedReportsList)` is called once, but the method inside of `.then()` is called repeatedly over and over again in this loop. 

This code was recently refactored in https://github.com/Expensify/App/pull/7453 so the first step I am going to do is revert that PR to see if the problem clears up, then we can go from there. I suspect it has something to do with the addition of `getFromReportParticipants()` returning a Promise.

cc @sobitneupane

**Comment by sobitneupane** [comment]
> I am able to determine that the long loop happens here:
> 
> https://github.com/Expensify/App/blob/47ec8f4ae0598e55c4d75b275ef4feeec8f14d6e/src/libs/actions/Report.js#L446
> 
> The method `PersonalDetails.getFromReportParticipants(simplifiedReportsList)` is called once, but the method inside of `.then()` is called repeatedly over and over again in this loop.
> 
> This code was recently refactored in #7453 so the first step I am going to do is revert that PR to see if the problem clears up, then we can go from there. I suspect it has something to do with the addition of `getFromReportParticipants()` returning a Promise.
> 
> cc @sobitneupane

I am also facing the same issue. But my branch doesnot have changes from  https://github.com/Expensify/App/pull/7453

**Comment by sobitneupane** [comment]
> I am able to determine that the long loop happens here:
> 
> https://github.com/Expensify/App/blob/47ec8f4ae0598e55c4d75b275ef4feeec8f14d6e/src/libs/actions/Report.js#L446
> 
> The method `PersonalDetails.getFromReportParticipants(simplifiedReportsList)` is called once, but the method inside of `.then()` is called repeatedly over and over again in this loop.
> 
> This code was recently refactored in #7453 so the first step I am going to do is revert that PR to see if the problem clears up, then we can go from there. I suspect it has something to do with the addition of `getFromReportParticipants()` returning a Promise.
> 
> cc @sobitneupane

I was also facing similar issue few hours back. But My branch does not have changes from https://github.com/Expensify/App/pull/7453.

**Comment by luacmartins** [comment]
@sobitneupane can you reproduce this on dev? I only see this issue on production.

**Comment by sobitneupane** [comment]
I am not having the issue now. But before in incognito window I was stuck in login page. After I entered email and pressed continue. Continue sign was loading forever. 
In non-incognito window, there was loading sign in the middle and nothing was happening.

**Comment by luacmartins** [comment]
That seems to be a different issue. My login pages work fine, but the app hangs when I'm already logged in and it refreshes.

**Comment by tgolen** [comment]
Thanks for the info! I think I have yet to determine that this change is 100% the root cause, but at least it's as far as I could trace the problem to for now. With it being reverted, I'm hoping it will point me toward the next place.

**Comment by tgolen** [comment]
Picking this back up today and making progress.
