### ISSUE TITLE
Global Create Menu - Error message when creating New Workspace

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#7680]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Precondition: Create a new expensifail account and  Validate it
1. Launch the app and log in with a new account
2. Open Global Create Menu
3. Click "Create New Workspace"

## Expected Result:
Workspace edit page opens when clicking "create new workspace"

## Actual Result:
An error message appears when clicking "Create New Workspace" and won't open the workspace edit page, regardless new or old account.

## Workaround:
Unknown 

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.38.1

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/153475838-39a6c5b2-3561-4973-ac8d-13177f54f25b.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by marcaaron** [comment]
I'm not able to reproduce this. What account is this? We can check logs to see if there was an error, but only if we know which account was used.

**Comment by kbecciv** [comment]
@marcaaron Tester login credentials: veraclementina@gmail.com , Password: 9879869Clemen.

**Comment by marcaaron** [comment]
Hmm, I am not sure, but I don't see anything in the logs like an attempt to create the policy so guessing this is an authentication error or something else. Is it consistently reproducible? Going to close, but feel free to reopen if there are reliable reproduction steps.
