### ISSUE TITLE
mWeb - Connect bank - Error page loaded after select any field on the Company Information page

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#7775]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to https://staging.new.expensify.com and sign in with new applause.expensifail account
2. Select to Create a New Workspace at Global Create Menu
3. Enable staging Web secure server in Account Preferences
4. Navigate to Workspace editor page and select Connect bank account
5. Select Connect online option
6. Select Wells Fargo and enter test credentials (user_good/pass_good)
7. Choose the savings account "Plaid Saving11122XXXXXX111" and select Continue
8. Select any text field on the Company Information page

## Expected Result:
Able to proceed with VBA flow after select any text field on the Company Information page

## Actual Result:
Unknown 

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platform:

Where is this issue occurring?

- Mobile Web

**Version Number:** 1.1.39-1

**Reproducible in staging?:** Yes

**Reproducible in production?:** Can not check the VBA flow in Production

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/154294990-faed6424-5532-42c9-b4bb-bee171e2d4de.mp4

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by parasharrajat** [comment]
It is a possible regression from my PR https://github.com/Expensify/App/pull/7318. I am trying to fix it https://github.com/Expensify/App/issues/7769. I will share update in an hour.
