### ISSUE TITLE
Android - Number pad input lags - reported by @mdneyazahmad

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#7790]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open app
2. Start IOU request 
3. Type any number 

## Expected Result:
Numbers should be immediately displayed 

## Actual Result:
 For some small time the second digit becomes first and it restores
 
## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Android

**Version Number:** 1.1.38-0
**Reproducible in staging?:** Need repro 
**Reproducible in production?:** need repro 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 

https://user-images.githubusercontent.com/43995119/154411244-eafa1c78-e1b4-4f95-972a-322cb7d40494.mp4

**Expensify/Expensify Issue URL:**
**Issue reported by:** @mdneyazahmad
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1643396599038599

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mdneyazahmad** [comment]
Video in the issue is at 0.25x
