### ISSUE TITLE
New lint rule: make sure all props have JSDoc-style comments.

### ISSUE THREAD

**Issue by roryabraham** [Expensify/App#7820]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Write some code that introduces a prop without a comment and run the linter.

## Expected Result:
The linter should complain that the new prop does not have a JS-doc style comment.

## Actual Result:
No lint error.

## Workaround:
n/a

## Platform:
n/a

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by roryabraham** [comment]
Expanding on this a bit, here are some examples of code that should trigger the linter:

```js
const propTypes = {
    myUndocumentedProp: PropTypes.number.isRequired,
};
```

```js
const propTypes = {
    // This is not the correct type of comment to document props
    myIncorrectlyDocumentedProp: PropTypes.number.isRequired,
 
    /* This also is not right */  
    myOtherProp: PropTypes.number.isRequired,
}l
```

And this code should pass:

```javascript
const propTypes = {
    /** This is the correct JSDoc format for documenting props. */
    myCorrectlyDocumentedProp: PropTypes.number.isRequired,
    
    ...spreadPropThatDoesNotGetASeparateDocHere,
};
```

**Comment by Justicea83** [comment]
Eslint FunctionExpressions do not support JSDocs yet

**Comment by roryabraham** [comment]
Sorry @Justicea83, any chance you can expand on what you mean by your last comment?
