### ISSUE TITLE
[HOLD for payment 2022-09-16] [$500] New Lint Rule: DisplayName property

### ISSUE THREAD

**Issue by roryabraham** [Expensify/App#7822]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Write a functional component but don't set the `displayName` property OR write a class component and set the `displayName` property.

## Expected Result:
ESLint should complain.

## Actual Result:
ESLint does not complain.

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by roryabraham** [comment]
Looked into this a while ago, and it turned out that it's pretty hard for a lint rule to determine if an object is a React functional component or not. Going to unassign this for now due to high difficulty-to-value ratio.

**Comment by mountiny** [comment]
Could this be external?

**Comment by roryabraham** [comment]
Yeah, good thinking. https://github.com/Expensify/eslint-config-expensify is public

**Comment by arielgreen** [comment]
Price increased

**Comment by parasharrajat** [comment]
I think we can cap the price for this.

**Comment by andrewlor** [comment]
## Proposal

Here is my source code for a custom rule that will report function components that don't set displayName or class components that do set displayName, along with comments for explanation.

```javascript
const _ = require('lodash');
const {isReactViewFile} = require('./utils');
const {DISPLAY_NAME_PROPERTY_CLASS, DISPLAY_NAME_PROPERTY_FUNCTION} = require('./CONST').MESSAGE;

module.exports = {
    create: context => ({
        Program(node) {
            // Only looking at react files
            if (!isReactViewFile(context.getFilename())) {
                return;
            }

            // Infer the component name from the filename
            const componentName = _(context.getFilename())
                .split('/')
                .last()
                .split('.')[0];

            // Find a root level variable delcaration that matches the component name
            const isFunctionComponent = _.find(node.body, n => n.type === 'VariableDeclaration'
                    && _.get(n, 'declarations[0].id.name') === componentName);

            // Find a root level class delcaration that matches the component name
            const isClassComponent = _.find(node.body, n => n.type === 'ClassDeclaration'
                && _.get(n, 'id.name') === componentName);

            if (!isFunctionComponent && !isClassComponent) {
                return;
            }

            // Find a root level assignment expression that matches <componentName>.displayName = ...
            const hasDisplayNameProperty = _.find(node.body, bodyNode => bodyNode.type === 'ExpressionStatement'
                && _.get(bodyNode, 'expression.type', '') === 'AssignmentExpression'
                && _.get(bodyNode, 'expression.left.property.name', '') === 'displayName'
                && _.get(bodyNode, 'expression.left.object.name', '') === componentName);

            // Allow function components with displayName set
            if (isFunctionComponent && hasDisplayNameProperty) {
                return;
            }

            // Allow class components without displayName set
            if (isClassComponent && !hasDisplayNameProperty) {
                return;
            }

            // Otherwise report
            context.report({
                node,
                message: isClassComponent ? DISPLAY_NAME_PROPERTY_CLASS : DISPLAY_NAME_PROPERTY_FUNCTION,
            });
        },
    }),
};
```

### Unit tests
```javascript
const RuleTester = require('eslint').RuleTester;
const rule = require('../display-name-property');
const {DISPLAY_NAME_PROPERTY_CLASS, DISPLAY_NAME_PROPERTY_FUNCTION} = require('../CONST').MESSAGE;

const ruleTester = new RuleTester({
    parserOptions: {
        ecmaVersion: 6,
        sourceType: 'module',
    },
});

ruleTester.run('display-name-property', rule, {
    valid: [
        {
            code: `
                const Test = () => null;
                Test.displayName = 'Test';
            `,
            filename: './src/components/Test.js',
        },
        {
            code: `
                class Test extends Component {
                    render() {
                        return null;
                    }
                }
            `,
            filename: './src/components/Test.js',
        },
    ],
    invalid: [
        {
            code: `
                const Test = () => null;
            `,
            filename: './src/components/Test.js',
            errors: [{
                message: DISPLAY_NAME_PROPERTY_FUNCTION,
            }],
        },
        {
            code: `
                class Test extends Component {
                    render() {
                        return null;
                    }
                }
                Test.displayName = 'Test';
            `,
            filename: './src/components/Test.js',
            errors: [{
                message: DISPLAY_NAME_PROPERTY_CLASS,
            }],
        },
    ],
});
```

### Examples in the codebase

![Screen Shot 2022-08-06 at 11 15 29 AM](https://user-images.githubusercontent.com/8475244/183259201-bd2cee2a-8bd0-4187-b151-3a35091987eb.png)

![Screen Shot 2022-08-06 at 11 15 48 AM](https://user-images.githubusercontent.com/8475244/183259202-f0978b47-b281-41a1-a906-141911c67cf9.png)

**Comment by andrewlor** [comment]
> @andrewlor you'll be creating a new file over here https://github.com/Expensify/eslint-config-expensify/tree/main/eslint-plugin-expensify right?

@rushatgabhane  Correct. As I understand it, for each rule I should add two files: `eslint-plugin-expensify/<rulename>.js` and `eslint-plugin-expensify/tests/<rulename>.test.js`, and also add an entry in https://github.com/Expensify/eslint-config-expensify/blob/main/rules/expensify.js.

As for your second point, having these as two separate rules, I think that makes sense could make the code slightly more simple to read. I have no objections writing it like that.

**Comment by andrewlor** [comment]
Good point. We can just modify slightly to handle that case.

```javascript
            // Infer the component name from the filename
            const filenameParts = _.split(context.getFilename(), '/');
            let componentName = _(filenameParts).last().split('.')[0];
            if (componentName === 'index') {
                componentName = filenameParts[filenameParts.length - 2];
            }
```

Hopefully that should cover everything? Assuming component files should only be in those two formats: `Test/index.js` or `Test.js`.

**Comment by arielgreen** [comment]
@MonilBhavsar please confirm https://github.com/Expensify/App/issues/7822#issuecomment-1207261209

**Comment by MonilBhavsar** [comment]
Looks good to me too 👍 
Since this property displays error message according to class/functional component, I'm fine with single rule.

**Comment by MonilBhavsar** [comment]
@andrewlor assigning you to issue

**Comment by arielgreen** [comment]
@andrewlor @rushatgabhane sent offers in Upwork

**Comment by andrewlor** [comment]
I'll get started on creating the PR for [eslint-config-expensify](https://github.com/Expensify/eslint-config-expensify), but I also want to quickly clarify what the exact scope is for this job.

Is the job considered completed after merging the PR for the new rule definition? Or will I also be required to install the new eslint-config version in the main repo and fix all of the new lint errors it will create. It seems there will be around 20 - 30 errors in the main repo that need to be fixed when this rule is added, which is a bit more extra work.

**Comment by andrewlor** [comment]
> @andrewlor They're just displayName errors right? If yes, I'll fix them with a follow-up PR because it shouldn't take more than 10 mins.

Yes, that's correct. Just wanted to clarity, thanks. I believe I'll also need someone to publish the package to npmjs.com after merging since I don't have access.

**Comment by MonilBhavsar** [comment]
Happy to help with publishing the package

**Comment by MonilBhavsar** [comment]
PR is in reviewing stage

**Comment by arielgreen** [comment]
Can we get an update on this please?

**Comment by MonilBhavsar** [comment]
PR is merged and eslint-sonfig package is updated. @rushatgabhane will send a PR to update the package in App repo and fix the lint errors.

**Comment by andrewlor** [comment]
https://github.com/Expensify/App/issues/7822#issuecomment-1190350454 This link for me says the job is closed. Let me know if someone can repost/reopen the job so I can apply, thanks!

**Comment by arielgreen** [comment]
@andrewlor sorry about that -- just sent over an offer! Once you accept I will pay this out. Thanks!

**Comment by arielgreen** [comment]
Super quick turnaround there, thanks. Paid.

**Comment by roryabraham** [comment]
I love this ❤️ 

You know it's a good lint rule when turning it on reveals a bunch of violations
