### ISSUE TITLE
New PR Check: Validate that all translation files have the same shape

### ISSUE THREAD

**Issue by roryabraham** [Expensify/App#7824]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

This is an idea I had to help improve app stability a bit.

## Action Performed:
Change one translation file object key but not all the others.

## Expected Result:
This new PR check should fail, because all translation files should have the same set of keys. If they do not, then we'll end up having strings missing or un-translated in some languages.

## Actual Result:
No such PR check yet exists.

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by roryabraham** [comment]
We could also validate that there are no duplicate values (which would mean that the value of the translation is not only duplicated in one file, but the values at those same paths are duplicates _all_ translation files).

**Comment by parasharrajat** [comment]
I think there is one lint check to check if the translation is added in all files. https://github.com/Expensify/App/blob/05bf7423ffb92e596ef6dea4444619b2faf9319c/tests/unit/TranslateTest.js#L59

**Comment by roryabraham** [comment]
Gotcha, so the main idea I created in this issue for already exists (using the English translation as the main source of truth) 👍

**Comment by roryabraham** [comment]
We could still ensure that there are no duplicates and validate all usages of the `translate` function.

**Comment by roryabraham** [comment]
Going to just close this for now. I think the checks that we have in place are probably good enough.
