### ISSUE TITLE
Not able to run the project- M1 chip

### ISSUE THREAD

**Issue by rajscet** [Expensify/App#7848]
5-duplicate-symbols-for-architecture-x86-64

![Screenshot 2022-02-21 at 2 16 12 PM](https://user-images.githubusercontent.com/6961313/154919579-0db23e30-6494-4e98-baff-bf1140624369.png)

**Comment by okansahin** [comment]
Hello @rajscet, if you are using yarn instead of npm. Please try to use npm.

**Comment by marcaaron** [comment]
Thanks for reporting, but please ask for help in our Slack channel and we will create the issue if necessary 🙇

**Comment by rajeshivn** [comment]
its fixed, by npm
