### ISSUE TITLE
Save button within room's settings page breaks in smaller devices - reported by @mateusbra

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#7908]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open a room.
2. Open details.
3. Open settings.

## Expected Result:
Button text should be displayed without break.

## Actual Result:
Button text breaks in smaller devices

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- iOS
- Android
- mWeb

**Version Number:** 1.1.38-0
**Reproducible in staging?:** need repro 
**Reproducible in production?:** need repro 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 
![image - 2022-02-25T004752 674](https://user-images.githubusercontent.com/43995119/155661435-07fa93b4-bd6b-444e-8fae-bb3b3a898bbe.png)
![image - 2022-02-25T004751 269](https://user-images.githubusercontent.com/43995119/155661437-eecaf1fa-2f24-4fa3-b132-7315f81f4574.png)

**Expensify/Expensify Issue URL:** 
**Issue reported by:**  @mateusbra
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1644419141614149

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mateusbra** [comment]
### PROPOSAL
Proposing early as I reported this issue:
Within:
https://github.com/Expensify/App/blob/d586981aa5aeb607c3f2cb7dee5d3e251fa7421c/src/pages/ReportSettingsPage.js#L192-L200
replace line 192 by:
```js
<View style={[styles.flex2]}>
```
SCREENSHOTS
![image](https://user-images.githubusercontent.com/56851391/155725979-233a2615-dfca-4e60-95c2-f90619a45b54.png)

![image](https://user-images.githubusercontent.com/56851391/155726021-2f477936-33c7-460e-b22e-fdea4aee3027.png)
