### ISSUE TITLE
[Performance] Refactor `SidebarLinks` to not use `getDerivedStateFromProps()` and other static methods

### ISSUE THREAD

**Issue by marcaaron** [Expensify/App#7948]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

Coming from https://github.com/Expensify/App/pull/7907/files#r816376801

## Code cleanup

The file here seems to be following some practices that we should avoid because they are very uncommon in this codebase:

https://github.com/Expensify/App/blob/00805b2b495fac25f53a42231dd3e5ae78138a2a/src/pages/home/sidebar/SidebarLinks.js#L165-L174

There are some well documented reasons why we should use this and not here:

https://reactjs.org/blog/2018/06/07/you-probably-dont-need-derived-state.html

And it _looks_ like we just want to perform a side effect where when various props change we update the reports we display in the sidebar. But for some reason have used derived state to do this instead of something like `componentDidUpdate()`.

Finding this component pretty hard to understand in general...

## Solution

1. Clean this up and make it use `componentDidUpdate()`
2. Put something in the style guide or eslint rule to forbid this practice
- [ ] Be sure to complete [this TODO](https://github.com/Expensify/App/pull/10619/files#diff-2ffec546a1daed561661d53400f598af96b06560c6d842886e2c100bbfb34654R239)

**Comment by ctkochan22** [comment]
Taking up your offer on letting me steal this :)

**Comment by parasharrajat** [comment]
There is one more component that uses it. `PopoverWithMeasuredContent`. 

But I think it is needed there. The popover render function is expensive for EmojiPicker and using it prevents render until we are fully ready. I don't remember why I used it there but there was a race condition that I was trying to overcome.

**Comment by parasharrajat** [comment]
Ok. Great.

**Comment by ctkochan22** [comment]
Punting

**Comment by tgolen** [comment]
Work is coming along here nicely. Getting a lot of unit tests written

**Comment by trjExpensify** [comment]
Added this App issue to the [WhatsApp Quality project](https://github.com/orgs/Expensify/projects/16/views/1) to keep track of it.

**Comment by tgolen** [comment]
Got the first PR done which optimizes some of the current code which figures out the order reports should be displayed in. My second PR refactors the sidebar to render items more efficiently.

**Comment by tgolen** [comment]
The last PR is in final stages of review and testing. It should merge this week!

**Comment by tgolen** [comment]
This is all done
