### ISSUE TITLE
No way to retry just one platform deploy

### ISSUE THREAD

**Issue by roryabraham** [Expensify/App#8099]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

### Problem
If the `platformDeploy.yml` workflow fails on just one platform, and we fix the issue and want to retry the build on just that one platform, there is no way to do it. Instead, we must retry the build on all platforms, which inevitably leads to workflow failures on the platforms that already deployed successfully (and maybe other unexpected side-effects).

**Note:** The root reason for this is that individual jobs cannot be retried, only whole workflows.

### Solution
We need a way to wait for all platform deploys to finish before continuing to leave deploy comments, etc... and that's why we combined all the platform deploys into a single workflow in the first place.

But since building out NewDot's CI/CD GitHub has introduced the concept of [callable/reusable workflows](https://docs.github.com/en/actions/using-workflows/reusing-workflows), and I think we should explore using that in this case. There may be limitations, so research is required but it has a much better UI/UX than `triggerWorkflowAndWait` with built-in flowcharts to show how the workflows are linked.

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by roryabraham** [comment]
The main [limitations](https://docs.github.com/en/actions/using-workflows/reusing-workflows#limitations) we'll need to be wary of are:

- Reusable workflows can't call other reusable workflows. (shouldn't be a problem in this case, but currently would prevent us from fully deprecating `triggerWorkflowAndWait`)
- Any environment variables set in an env context defined at the workflow level in the caller workflow are not propagated to the called workflow.

**Comment by roryabraham** [comment]
@Expensify/mobile-deployers This would be a valuable one for someone to pick up

**Comment by AndrewGable** [comment]
What about an auto retry?

**Comment by roryabraham** [comment]
> What about an auto retry?

I don't think that would be as valuable. I think it would be better to give deployers control over when deploy workflows retry. One example that comes to mind is when we need to sign some Google or Apple something-or-other, then retry just that platform.

**Comment by roryabraham** [comment]
This problem is not correct as written anymore. GitHub released a feature where you can retry only failed jobs in a workflow. We still may want to split out each platform into a callable workflow for code/workflow organization reasons, but that's a separate problem. closing this out.
