### ISSUE TITLE
Web - VBA - "X" icon isn't centered for the date picker field under Company and Personal info

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#8156]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to https://staging.new.expensify.com/[](javascript:)

2. Log in with expensifail account
3. Go to Settings - Performances - Enable the Secure Staging Server
4. Go to any Workspace
5. Click Connect Ban k account
6. Select Plaid option
7. Use Wells Fargo bank
8. Username: user_good | Password: pass_good
9. Account type: Plaid Saving (2nd option)
10. CompanyName: Alberta Bobbeth Charleson
11. CompanyTaxID: 123456789
12. Select any date for Incorporated date

## Expected Result:
"X" icon is centered for the date picker field under Company and Personal info

## Actual Result:
"X" icon isn't centered for the date picker field under Company and Personal info

## Workaround:
Visual

## Platform:

Where is this issue occurring?

- Web
-mWeb

**Version Number:** 1.1.41.5
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** applausetester+0707abb@applause.expensifail.com / Feya87Katya
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 
![Bug5484966_dateFF](https://user-images.githubusercontent.com/43996225/158397192-5e6fb217-76e2-4cac-81b3-749229cfd6ec.png)
![Bug5484966_FF](https://user-images.githubusercontent.com/43996225/158397209-6990d812-0a7a-47bd-b94f-e2ae88bb1acb.jpg)

**Expensify/Expensify Issue URL:** 
**Issue reported by:** Applause
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by trjExpensify** [comment]
I wonder whether we need this icon in the field at all? @kevinksullivan @shawnborton, can you recall why this was added instead of just expanding the date picker when you click/tap the field?

**Comment by shawnborton** [comment]
I actually think this is a native control, and technically it is centered because the actual text input part of the overall input sits lower and below the small label above it. I vote we close this and do nothing.

**Comment by trjExpensify** [comment]
Oh okay, that makes sense then if it's a native control. I'll just go ahead and close this.
