### ISSUE TITLE
IOS- Room - Keyboard is opened and cursor focused on input box when open #annonce or #admins room for Admin user

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#8225]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Precondition: Create expensifail account and make is admin

1. Launch the app and log in with admin account
2. Tap on #admin or #announce rooms

## Expected Result:
App behavior should be the same for all rooms

## Actual Result:
Keyboard is opened and cursor focused on input box when open #annonce for Admin user

## Workaround:
Unknown 

## Platform:

Where is this issue occurring?

- iOS

**Version Number:** 1.1.44.3

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** applausetester+031522abb@applause.expensifail.com

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause

https://user-images.githubusercontent.com/93399543/159034779-10567731-fd6d-4173-a72b-8a2769f8ef0f.MP4

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by parasharrajat** [comment]
This is not a bug. 

The app is designed to autofocus the input when a user opens a new chat. It means if a chat has old messages composer will not be autofocused but if there is none, a composer will be autofocused.

This happens to all types of chats not just rooms.
