### ISSUE TITLE
Most of the redirect URLs on Terms and fees page are invalid - reported by @adeel0202

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#8243]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Navigate to Terms and fees page (enter /settings/payments/enable-payments in the URL directly for testing purposes)
2. Click on any redirect URL except Privacy policy

## Expected Result:
Links should redirect to the valid page

## Actual Result:
Links do not redirect to the valid page

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.40-2
**Reproducible in staging?:** need repro
**Reproducible in production?:** need repro 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 

https://user-images.githubusercontent.com/43995119/159203082-63795c68-8f90-4003-96a9-5c586d19dc39.mov

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @adeel0202
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1646672211487429

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by adeel0202** [comment]
### Proposal (If considered external)

We can replace the invalid URLs with the valid ones in the following places
https://github.com/Expensify/App/blob/04154702434b53a9de3f99a50b839297da4e4f31/src/pages/EnablePayments/TermsStep.js#L75

https://github.com/Expensify/App/blob/04154702434b53a9de3f99a50b839297da4e4f31/src/pages/EnablePayments/TermsStep.js#L96

https://github.com/Expensify/App/blob/04154702434b53a9de3f99a50b839297da4e4f31/src/CONST.js#L203
