### ISSUE TITLE
Payment option selection fill is incomplete - reported by @Santhosh-Sellavel 

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#8250]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to Settings -> Payments
2. Click on Add Payment Methods

## Expected Result:
Selection fill should available for full width

## Actual Result:
Selection fill is incomplete

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- iOS

**Version Number:** 1.1.41-6
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 

https://user-images.githubusercontent.com/43995119/159206401-76b3bbf2-f918-482f-ab05-8f62f58947f5.MP4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @Santhosh-Sellavel 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1646923510519039

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by thesahindia** [comment]
Already fixed in https://github.com/Expensify/App/pull/7677

**Comment by CortneyOfstad** [comment]
Didn't realized this wasn't closed after it was fixed. Closing.
