### ISSUE TITLE
Push notifications are coming in delayed

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#8252]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login on app and background the app 
2. from another account send few messages 
3. Check for Push notifications to appear 

## Expected Result:
Push notifications are Not coming in delayed

## Actual Result:
Push notifications are coming in delayed

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Desktop App

**Version Number:** 1.1.42-0
**Reproducible in staging?:** need repro
**Reproducible in production?:** need repro
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:** 
**Issue reported by:** @rafecolton 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1646937732262259

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by roryabraham** [comment]
Going to close this – push notifications go through several severs:

1. Our server
1. UrbanAirship servers
1. Apple/Google servers

With these notifications going through so many different services, they are prone to random delays, sometimes up to about 2 minutes. There's usually nothing we can do about it, so I'm going to close this for now.
