### ISSUE TITLE
 Eye icon area has border radius in password input - reported by @Tushu17

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#8274]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to login page
2. Add email or phone
3. Use autofill for password.

## Expected Result:
Password input shouldn't have border radius

## Actual Result:
Password input has border radius

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.43-2
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation  
https://github.com/Expensify/App/issues/7016 Issue was changed so the styles that were needed were removed in some PR 

![Screenshot_20220301-001118_WhatsApp](https://user-images.githubusercontent.com/43995119/159768195-2f152230-2b53-42ca-9f8d-51a49726e089.jpg)

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @Tushu17
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1646074016247889

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by parasharrajat** [comment]
This is duplicate. There was another issue like this. But in reality this is not a issue. Even Netflix does not have full covered autofill.

**Comment by thesahindia** [comment]
@parasharrajat, yeah I had reported this and the issue was solved with a different approach but the issue isn't duplicate, I think the title and description isn't correct the issue is about the border radius.
We had added this `secureInput` for the border radius but now we aren't passing this. 
https://github.com/Expensify/App/blob/116398b0d2195e43c185ee72e70b214def73e410/src/styles/styles.js#L715-L717

**Comment by thienlnam** [comment]
Reading the thread it looks like we just need to add the separator back to make it look more intentional

**Comment by Tushu17** [comment]
### Proposal 
we need to pass `styles.secureInput` here instead of styles.pr2
https://github.com/Expensify/App/blob/116398b0d2195e43c185ee72e70b214def73e410/src/components/TextInput/BaseTextInput.js#L262

**Comment by thienlnam** [comment]
This is a pretty straightforward change, @thesahindia you commented on the issue first, do you want to complete the PR? Otherwise I will hand it to Tushu17

**Comment by thesahindia** [comment]
> This is a pretty straightforward change, @thesahindia you commented on the issue first, do you want to complete the PR? Otherwise I will hand it to Tushu17

Yeah you can assign Tushu17 on this as I already have some other PRs pending

**Comment by kevinksullivan** [comment]
Posted - https://www.upwork.com/jobs/~01ec8f623dbff22877

@Tushu17 mind applying so I can hire you? Thanks!

**Comment by thienlnam** [comment]
Currently in review, changes are made - just want to verify travis tests are working on the PR

**Comment by kevinksullivan** [comment]
Not overdue, on staging.

**Comment by marcochavezf** [comment]
Seems the border radius is still shown on the Login Page: https://github.com/Expensify/App/issues/8394

**Comment by Tushu17** [comment]
It's a regression from #8346
cc : @Santhosh-Sellavel

**Comment by Santhosh-Sellavel** [comment]
Thanks, @Tushu17! I'll follow up on this.

**Comment by kevinksullivan** [comment]
Sounds good. @Tushu17 I just sent the offer. Please accept and I'll pay for the reporting + fix

**Comment by kevinksullivan** [comment]
Paid for reporting and fixing. Thanks @Tushu17 !
