### ISSUE TITLE
New incoming chats not showing in main chat window or Left Hand Nav (LHN)

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#8290]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Opened Desktop (was quit last night, there might have been a new version available for update)

## Expected Result:
New Chats to show

## Actual Result:
1. No new chats showed for ~3 mins
2. Out of nowhere two new chats showed in LHN
3. For one, I replied then the user sent many more messages (got notification on phone) but those chats aren't showing in main chat window or LHN

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Desktop App

**Version Number:** 1.1.42-6
**Reproducible in staging?:** Y 
**Reproducible in production?:** 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 
Logs 
[take 2 chats not showing mar 17.txt](https://github.com/Expensify/App/files/8338709/take.2.chats.not.showing.mar.17.txt)

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @mallenexpensify 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1647530120355079

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by marcaaron** [comment]
I'm gonna chalk this up to being some inconsistent Pusher service stuff and close this since this is not actionable at the moment.
