### ISSUE TITLE
Web - staging.new.expensify/statement/202112 does not redirect to appropriate page

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#8313]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
Issue was found when executing #8174
## Action Performed:
1. Login to your account on NewDot and navigate to /statement/202112.

## Expected Result:
Verify that clicking any of the links will redirect you to the appropriate page in-app, i.e. the new page is not rendered within the iframe.

## Actual Result:
Page is refreshed and not redirected to correct page

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web

**Version Number:** v1.1.46-0

**Reproducible in staging?:** y

**Reproducible in production?:** y

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** 
![Bug5505249_Screen_Shot_2022-03-24_at_9 28 51_PM](https://user-images.githubusercontent.com/43996225/160043601-8e60e7b4-9f55-4cf4-82fd-04ed7490fbdf.png)

https://user-images.githubusercontent.com/43996225/160043602-d2a1ae25-2621-4b58-87c1-aace97e0eec1.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)
Issue was found when executing #8174

**Comment by timszot** [comment]
@luacmartins any insight on this since it's related to your PR?

**Comment by luacmartins** [comment]
Ah yes! We can check this off. This should be tested on prod instead! Sorry, forgot to add the label.
