### ISSUE TITLE
Blank screen is displayed after log in with new expensifail account

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#8320]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

Precondition: Create a new expensifail account and add as admin
1. Launch the app
2. Log in with expensifail account

## Expected Result:
Should be successfully log in with a new account

## Actual Result:
Blank screen is displayed after log in with new expensifail account

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.46.0

**Reproducible in staging?:**  y

**Reproducible in production?:** n

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/160154948-d395d07b-b8d4-40b3-b2c9-aa0857c1f7c3.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by luacmartins** [comment]
@kavimuru I wasn't able to reproduce this particular issue (check video below). I did however see a blank screen after entering a new expensifail account, but before being able to enter a password. Can you confirm if that is the issue?

Existing expensifail account
https://user-images.githubusercontent.com/22219519/160158917-ab1408d8-5cb4-4e18-943f-88b6a1925ae7.mov

New expensifail account

https://user-images.githubusercontent.com/22219519/160159183-0702f916-c6d8-4c49-be20-2883a2442e47.mov

**Comment by kavimuru** [comment]
Log in for the first time after creating is inconsistent, but when we create an expensifail account it happens every time. 

https://user-images.githubusercontent.com/43996225/160169228-9ee97e9d-d3cc-4fce-b982-321006a40c6d.mp4

**Comment by luacmartins** [comment]
Thanks for confirming! That is the same issue that I'm seeing!

**Comment by luacmartins** [comment]
Seems like it was introduced by changes to API.js in [this PR](https://github.com/Expensify/App/pull/8087) @marcaaron

**Comment by marcaaron** [comment]
Which change in particular? Any more context?

**Comment by luacmartins** [comment]
Chatted 1:1 with Marc and we figured out the expected behavior.
