### ISSUE TITLE
Setting - Phone number - Resent button disappeared after refresh the page for phone account  

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#8333]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to https://staging.new.expensify.com
2. Log in with any account
3. Go Setting - click on Icon Profile
4. Tap on Add phone number
5. Put valid phone number
6. Put Account Password and tap Send Validations
7. Tap on Resend button
8. After received sms  on your phone  and tap on valuation link 
9.  Go back to expensify app 

## Expected Result:
Resent button  is not visible in Setting page

## Actual Result:
Resent button disappeared after refresh the page for phone account  

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.46.2

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** kbecciv+0914@gmail.com

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/160472250-61865418-4fde-4abf-8819-aacd1caa4603.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by AndrewGable** [comment]
This seems like expected behavior, the resend button should only exist when the phone number is unvalidated. Please let me know if I've misunderstood the bug report.
