### ISSUE TITLE
[HOLD for payment 2022-05-20][$2000] IOU balance disappears after sending money to owed user - reported by @Santhosh-Sellavel 

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#8352]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Create two accounts User A and User B
2. Login with those accounts on different devices into the newDot app.
3. Now Request money from User B as User A   Ex: Amount 2000
4. Now using from User B send money i.e 1000 back to User A

## Expected Result:
IOU Balance should be shown until fully settled.

## Actual Result:
IOU Balance gets hidden from LHN for both users. One more Issue, IOU card in the chat list also gets hidden.

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Web

**Version Number:** 1.1.46-0
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 
<img width="415" alt="Screenshot 2022-03-02 at 12 39 49 AM" src="https://user-images.githubusercontent.com/43995119/160734175-fa675898-7002-4e7e-b8fe-a0601c741383.png">

https://user-images.githubusercontent.com/43995119/160734177-c6e89c3c-1225-4899-b70d-4dbc357c98b9.mov

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @Santhosh-Sellavel 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1646161753960719

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by johnmlee101** [comment]
Opening up for external. The requisites for rendering 
somewhere from here below is breaking would be my guess, but would need extra eyes to see why this case isn't being handled: https://github.com/Expensify/App/blob/21ab9432332e4b2ae5451273b5e17d4df53977db/src/pages/home/report/ReportActionItem.js#L132-L136

**Comment by jliexpensify** [comment]
Posted

Internal - https://www.upwork.com/ab/applicants/1511226520114122752/job-details
External - https://www.upwork.com/jobs/~01782081efffe44962

Invited @Santhosh-Sellavel

**Comment by jliexpensify** [comment]
Price doubled!

**Comment by jliexpensify** [comment]
OOO for 2 weeks, so re-assigning my issues - thanks Matt!

**Comment by mallenexpensify** [comment]
Doubled price to $1000 (a day early since I was in here updating daily > weekly)
https://www.upwork.com/jobs/~01782081efffe44962

**Comment by mallenexpensify** [comment]
Doubled price to $2000
https://www.upwork.com/jobs/~01782081efffe44962

**Comment by Julesssss** [comment]
@jliexpensify would you mind closing the UpWork issue and paying @Santhosh-Sellavel for raising the bug please?

**Comment by Julesssss** [comment]
Conveniently, the IOU action type is available in the reportAction:

![Screenshot 2022-04-28 at 15 37 47](https://user-images.githubusercontent.com/10736861/165777738-1c02adeb-2b01-4981-97d4-806413bc25bf.png)


```
if (reportAction.originalMessage.type == 'pay') {
    return;
}
```

**Comment by mallenexpensify** [comment]
Paid @Santhosh-Sellavel $250 for reporting and closed the Upwork job

**Comment by Julesssss** [comment]
[PR in progress](https://github.com/Expensify/App/pull/8816)
