### ISSUE TITLE
[$250] You can invite a phone Number more than once in a Workspace - reported by @Tushu17

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#8360]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
 1. Go to setting > Workspace > Manage members
 2. Click Invite
 3. Invite a new member using a phone number
 4. Search and invite that same Phone Number again.

## Expected Result:
Existing worskpace members should be filtered out in the results, so we should be filtering out phone numbers in the same way we do existing members email addresses.

## Actual Result:
Existing members that have a phone number as their primaryLogin are not filtered out and therefore can be added to the workspace multiple times.

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.46-3
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 

https://user-images.githubusercontent.com/43995119/160738443-8cb7000d-087e-4597-ad27-affa9755f116.mp4

**Upwork URL:** https://www.upwork.com/jobs/~01e574f8680752d5ec
**Issue reported by:** @Tushu17
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1647723725311069

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by trjExpensify** [comment]
Looks like the same thing happens with email, so I don't think this is isolated to just inviting phone numbers.

<img width="372" alt="image" src="https://user-images.githubusercontent.com/16232057/160933839-45274e15-f91f-42b7-9a60-2a40e64e2723.png">

@Tushu17 did you confirm that as well? If so, we can update the OP of the issue to be more broad. In the meantime, I think we can loop in engineering for triage.

**Comment by trjExpensify** [comment]
:( Melv didn't trigger the other day.

**Comment by Tushu17** [comment]
@trjExpensify I think you can invite user with emails multiple time but only when you tap invite button multiple times and there's already an issue(#6676) open for that.

>@Tushu17 did you confirm that as well?

In this issue you can invite a phone number and you can search that number again to invite.

https://user-images.githubusercontent.com/89839952/161285993-92cefa86-0681-4c89-927a-70dc587a2aa3.mp4

**Comment by madmax330** [comment]
I think we need to update the API to not allow mutliple emails or phone numbers in a group

**Comment by trjExpensify** [comment]
Okay, got it. So @Tushu17 you're saying that emails get filtered out in the results to add to the workspace if they are already a member, but phone numbers don't?

**Comment by madmax330** [comment]
Oh right I think there's 2 issues. 
1 is what you're saying @trjExpensify  (can be external)
2 the api allows multiple times the same email (internal)

**Comment by Tushu17** [comment]
> Okay, got it. So @Tushu17 you're saying that emails get filtered out in the results to add to the workspace if they are already a member, but phone numbers don't?

@trjExpensify Yeah correct👍

**Comment by trjExpensify** [comment]
Cool, so I think we update the OP to make it a tad clearer. I've gone ahead and done that. @madmax330 you happy for this to go back on `external`?

**Comment by madmax330** [comment]
> I think the second will be taken care of in thehttps://github.com/Expensify/App/issues/6676 too right?
Doesn't look like it since it's external. If it's an API update it has to be internal. 
But we can keep this one as external and create a separate issue for the API change

**Comment by luacmartins** [comment]
Issue reproducible in dev for phone numbers only. I couldn't reproduce the dupe email invite (unless offline) as described in https://github.com/Expensify/App/issues/6676.

Internal issue [here](https://github.com/Expensify/Expensify/issues/205148). I'll pick up the internal issue to fix the API command and might take on the external one too if we get no proposals in the meantime.

**Comment by luacmartins** [comment]
I'll work on this internally. @trjExpensify we should pay the reporting bonus to @Tushu17.

**Comment by trjExpensify** [comment]
Cool, @Tushu17 - sent you a contract in Upwork for reporting.

**Comment by Tushu17** [comment]
> Cool, @Tushu17 - sent you a contract in Upwork for reporting.

@trjExpensify Ok, Accepted👍🏼

**Comment by trjExpensify** [comment]
Perfect, settled! 👍
