### ISSUE TITLE
[HOLD for payment 2022-06-15] [$250] Pressing the enter/return key on Request money page, when the button is disabled, takes focus away from the input field - reported by @adeel0202

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#8362]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click on + and then Request money option
2. Press enter key without entering any value in the input field
3. Now enter some value in the input field
4. Observe that nothing is being entered in the input field as the focus is no longer on the input field

## Expected Result:
Pressing the enter key when the button is disabled should keep the focus on the input field

## Actual Result:
Pressing the enter key when the button is disabled takes focus away from the input field

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Web
- Desktop App

**Version Number:** 1.1.43-2
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 

https://user-images.githubusercontent.com/43995119/160739891-9e3ba2ef-e13d-491a-8fb5-b458b1a0efc8.mov

**Upwork URL:** https://www.upwork.com/jobs/~01c7ab5a8744a037c1
**Issue reported by:** @adeel0202
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1647782854047619

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by conorpendergrast** [comment]
I reproduced on Production too, thanks!

**Comment by trjExpensify** [comment]
Job is on Upwork here: https://www.upwork.com/jobs/~01c7ab5a8744a037c1 

CC: @adeel0202 if you were interested in this one!

**Comment by sobitneupane** [comment]
**Proposal:**
We can achieve the required output by passing prop `alwaysFocusIfEmpty` in the following component.
https://github.com/Expensify/App/blob/564ec88b345a6da1478bab5e5060054a8cb5ad74/src/pages/iou/steps/IOUAmountPage.js#L228-L239

And using the prop in BaseTextInput to focus the input.
https://github.com/Expensify/App/blob/564ec88b345a6da1478bab5e5060054a8cb5ad74/src/components/TextInput/BaseTextInput.js#L64-L69
```diff
    componentDidUpdate() {
        // Activate or deactivate the label when value is changed programmatically from outside
        // Only update when value prop is provided
+       if (this.props.alwaysFocusIfEmpty && this.props.value === '') {
+           this.input.focus();
+       }
```

**Comment by rushatgabhane** [comment]
@sobitneupane wouldn't a better way do it `onBlur`?
And is it really necessary to put this in `TextInput`? Where else do you anticipate this prop to be used?

**Comment by sobitneupane** [comment]
Yes. We can use onBlur function in IOUAmountPage.
**Updated Proposal:**
```
    onBlur() {
        if (this.state.amount === '') {
            this.textInput.focus();
        }
```
https://github.com/Expensify/App/blob/564ec88b345a6da1478bab5e5060054a8cb5ad74/src/pages/iou/steps/IOUAmountPage.js#L228-L239
```diff
<TextInput
    disableKeyboard
    autoGrow
    hideFocusedState
    inputStyle={[styles.iouAmountTextInput, styles.p0, styles.noLeftBorderRadius, styles.noRightBorderRadius]}
    textInputContainerStyles={[styles.borderNone, styles.noLeftBorderRadius, styles.noRightBorderRadius]}
    onChangeText={this.updateAmount}
    ref={el => this.textInput = el}
    value={formattedAmount}
    placeholder={this.props.numberFormat(0)}
    keyboardType={CONST.KEYBOARD_TYPE.NUMBER_PAD}
+   onBlur = {this.onBlur}
/>
```

**Comment by rushatgabhane** [comment]
> And is it really necessary to put this in TextInput
Where else do you anticipate this prop being used

@sobitneupane I didn't mean to say that we *should* use onBlur, I just wanted your thoughts on where all this prop could be used.

If we can find more than one input where we want this, then we should add a prop to `TextInput`.

What do you think?

**Comment by sobitneupane** [comment]
I don't find any other specific use case of the prop. I prefer not to tamper TextInput for now. If we find other places where we want similar behavior than we can pass prop. Rather than onBlur I think we should use EventHandler in IOUAmountPage. If Enter is pressed and there is no amount, textInput remains focused.
```
setupEventHandlers() {
    if (!document) {
        return;
    }

    this.keyUpHandler = (keyBoardEvent) => {
        // Select the currently highlighted emoji if enter is pressed
        if (keyBoardEvent.key === 'Enter') {
            if (this.state.amount === '') {
                console.log('debug', this.state.amount);
                this.textInput.focus();
            }
            return;
        }
    };

    document.addEventListener('keyup', this.keyUpHandler, true);

}
```

**Comment by rushatgabhane** [comment]
@sobitneupane I don't like the idea of using event handlers. Why is it better than onBlur?

**Comment by sobitneupane** [comment]
> @sobitneupane I don't like the idea of using event handlers because it isn't really aplicable for native (eg: iPad with a keyboard attached to it).
> 
> Why is it better than onBlur?

Oh! In that case, we can go with onBlur. I suggested the event handler because 'Enter' event makes the TextInput blur. So, tried to catch the main cause. In this case, onBlur works fine as well.

**Comment by rushatgabhane** [comment]
🎀 👀 🎀 C+ reviewed

@Beamanator I recommend @sobitneupane's [proposal](https://github.com/Expensify/App/issues/8362#issuecomment-1086887411).

**Comment by sobitneupane** [comment]
> Job is on Upwork here: https://www.upwork.com/jobs/~01c7ab5a8744a037c1
> 
> CC: @adeel0202 if you were interested in this one!

Applied for the job.

**Comment by trjExpensify** [comment]
Sent the offer 👍

**Comment by sobitneupane** [comment]
> @sobitneupane can you address the comments on the PR from @rushatgabhane, please?

I was away from my laptop for few days. Sorry for the delay. Pushed changes.

**Comment by trjExpensify** [comment]
PR awaiting a deploy.

**Comment by Julesssss** [comment]
FYI. This PR was reverted, as it introduced [this bug](https://github.com/Expensify/App/issues/8926#issuecomment-1124245538). 

I think we'll need to resolve the issue with a different proposal.

**Comment by rushatgabhane** [comment]
@sobitneupane interesting...
I have no idea why that fixes the issue. Maybe you can help me with that :)

**Comment by rushatgabhane** [comment]
@Beamanator I don't know why it works, but the fix suggested by @sobitneupane is simple https://github.com/Expensify/App/issues/8362#issuecomment-1124980854

There should be no regressions because currency selection page just sets a value in Onyx.

**Comment by rushatgabhane** [comment]
@trjExpensify yep, that's right!

**Comment by trjExpensify** [comment]
Cool, updated the title and removed the label.

**Comment by Beamanator** [comment]
Next PR still under review

**Comment by trjExpensify** [comment]
PR is waiting to be deployed to staging, Melv. 👍

**Comment by trjExpensify** [comment]
Settled up with @sobitneupane, @rushatgabhane & @adeel0202.
