### ISSUE TITLE
[HOLD payment 01-30-23] Remove loading screen logs

### ISSUE THREAD

**Issue by thienlnam** [Expensify/App#8367]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

As part of https://github.com/Expensify/App/issues/7424, we added logs to help identify locations where slow spinners appear.  Now that we've resolve the issue of slow spinners, should we remove the logs or have they been helpful in debugging other loading screen issues?

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012d8e2262399c8ead</li>
        <li>Upwork Job ID: 1616501995085864960</li>
        <li>Last Price Increase: 2023-01-20</li>
    </ul>
</details>

**Comment by thienlnam** [comment]
Still holding

**Comment by thienlnam** [comment]
Same as above, logs haven't been useful for now

**Comment by thienlnam** [comment]
Same

**Comment by thienlnam** [comment]
I think this is fine to remove, we haven't used it - will get a PR up later

**Comment by thienlnam** [comment]
Haven't done this, not really a priority

**Comment by thienlnam** [comment]
Adding 'Internal' and BugZero so we can make sure to pay out @mananjadhav for reviewing the PR here https://github.com/Expensify/App/pull/14374

**Comment by sakluger** [comment]
Just sent an offer to @mananjadhav in Upwork!

**Comment by mananjadhav** [comment]
Thanks @sakluger. Accepted

**Comment by thienlnam** [comment]
7 day regression wait is done 01-30-23

This is a pretty small bug so I don't imagine any problems though 👍

**Comment by mananjadhav** [comment]
Quick bump @sakluger

**Comment by thienlnam** [comment]
@mananjadhav There doesn't seem to be anything actionable here, payment date will be 01-30-23.  Sorry if I didn't make that clear in my last comment

**Comment by mananjadhav** [comment]
Sorry my bad @thienlnam @sakluger. I read this as Jan 23, instead of 2023.

**Comment by thienlnam** [comment]
No problem! 😄

**Comment by mananjadhav** [comment]
@sakluger Quick bump on the payout.

**Comment by sakluger** [comment]
Sorry for the delay and thanks for the bump. I paid through Upwork, thanks everyone!
