### ISSUE TITLE
Payments - No hint appears in company or personal info pages when adding a debit card or bank account

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#8399]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
Issue was found when executing #8232

## Action Performed:
1. Go to newdot and login
2. Go to payments and select a debit card
3. Focus cursor on any field

## Expected Result:
Hint should appear underneath the box

## Actual Result:
No hint is appearing, however if I click "Save" with incorrect data throws error message in red

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.49-0

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**Email or phone of affected tester (no customers):** applausetester+b3101b@applause.expensifail.com / Utest123

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/161079602-01acd382-e910-4f30-96d5-36558e169492.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by AndrewGable** [comment]
"hint" or "auto fill"?

**Comment by AndrewGable** [comment]
@rushatgabhane @parasharrajat @mountiny - Can you verify the expected result here? I am a bit confused.

**Comment by mountiny** [comment]
Hmmm, I dont think that is correct, there should be no hints as the tests steps in the linked PR mention:

<img width="856" alt="image" src="https://user-images.githubusercontent.com/36083550/161164254-28b20533-80c9-4c6d-afbf-bf0cdd4ab9db.png">

I guess this was just a bit confusing because we were fixing the hint feature, which was not used anywhere 😄 so no, the hints should not show up, thus everything works fine 👍

**Comment by AndrewGable** [comment]
Closing then!

**Comment by rushatgabhane** [comment]
@mountiny Those tests are meant for PR reviewers right?

 I didn't put those tests in the QA section. It only had storybook tests.
Is there anything that I could have done to prevent this confusion?

**Comment by mountiny** [comment]
@rushatgabhane Nono, I think you did great! This can happen easily!
