### ISSUE TITLE
Log in - Error message displayed when logged in with invited user via IOU

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#8420]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to https://staging.new.expensify.com and log in with your account
3. Click the green + icon and select request money
4. Enter an amount and click next
5. Enter the email address of a user that doesn't have an existing account and request $x to confirm and send the request
6. Go to the email inbox of that user you just invited and make sure the email is received
7. Click the hyperlink in the email and make sure you're navigated to the New Expensify sign-in page and not the expensify.com sign-in page.
8. Enter the email address of that newly invited user and click continue. Make sure you hit the 'we've sent you a magic sign-in link` page on the sign-in page when you've done that
9. Go to your email inbox again and make sure the email containing the validation link is received
10. Click the hyperlink in the email and make sure you land on the New Expensify Set Password page.
11. Enter a password and click Set Password to verify you can sign-in.

## Expected Result:
No error message displayed when logged in with invited user via IOU

## Actual Result:
Error message displayed when logged in with invited user via IOU

## Error message:
The chat you are looking for cannot be found

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.49.1
 
**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** iheretsutest+30031@gmail.com

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/161161475-3714a146-cde5-4842-b254-aa547aeb90df.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by robertjchen** [comment]
The video recording of the bug isn't loading for me, could we please try re-uploading it? 🙏

**Comment by kavimuru** [comment]
@robertjchen Reuploaded the video.

https://user-images.githubusercontent.com/43996225/161339402-5f030551-bc91-476a-8147-50818a04e5d6.mp4

**Comment by robertjchen** [comment]
no update

**Comment by robertjchen** [comment]
no update, sorry

**Comment by robertjchen** [comment]
On the list for this week

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by robertjchen** [comment]
No update

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (Second week)

**Comment by robertjchen** [comment]
Returning this to the pool as I can't get to it in a timely manner. Sorry! Hopefully it was just a fluke and is no longer an issue moving forward 👍

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (Third week) Closing
