### ISSUE TITLE
We dont support .pptx formats as attachments

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#8425]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Navigate to any chat 
2. Send .pptx file 

## Expected Result:
User should be able to send .pptx file 

## Actual Result:
User is unable to send .pptx file. Infinite spinner displayed 

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.49-0
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 
![Screen Shot 2022-03-31 at 11 28 14 PM](https://user-images.githubusercontent.com/43995119/161189748-fcda3364-85cd-4cb4-a94f-cb315b25dde2.png)

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @AndrewGable 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1648510177378939

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by MariaHCD** [comment]
Internal issue, we need to support the file type [here](https://github.com/Expensify/Web-Expensify/blob/221782b5be924e619b760df8e9996bd7f392196f/lib/ReportUtils.php#L69)

**Comment by AndrewGable** [comment]
Thanks for the quick fix!

**Comment by MariaHCD** [comment]
The fix has been deployed to production: https://github.com/Expensify/Web-Expensify/pull/33458#issuecomment-1089458573
