### ISSUE TITLE
[HOLD - Offline] Web browser showing user as offline when user online

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#8444]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Navigate to the app on low internet 
2. Log out 
3. Log back in. 

## Expected Result:
User should be online 

## Actual Result:
User is showing offline
Offline message keeps flickering
Network requests are failing

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platform:

Where is this issue occurring?

- Web
- Desktop App

**Version Number:** 1.1.43-2
**Reproducible in staging?:** 
**Reproducible in production?:** Y 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 
![image - 2022-04-01T133825 677](https://user-images.githubusercontent.com/43995119/161314336-659a273c-6696-4a3f-b537-97daf8f3eee3.png)
[LOG.txt](https://github.com/Expensify/App/files/8399875/you.appear.to.be.offline.matt.march.30.1.txt)

https://user-images.githubusercontent.com/43995119/161314340-f9e34f9f-5479-4e39-8f7a-be24f010ea1c.mov

https://user-images.githubusercontent.com/43995119/161314358-359dd60c-f7f8-4221-a3a8-1fe4c468f6d7.mov
![image - 2022-04-01T134054 716](https://user-images.githubusercontent.com/43995119/161314713-7c724eec-3987-4b1c-ac9e-709f2e0250a6.png)

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @miljakljajic 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1648646866606329

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by tgolen** [comment]
This also happened to me yesterday.

![image](https://user-images.githubusercontent.com/1228807/162006437-1cdc03a3-65a4-4647-9509-b4d2f549c49a.png)

I think it might be related to user-is-typing because the message appeared while I was typing, then I stopped typing when the message appeared. As soon as I started typing again, the message went away.

**Comment by pecanoro** [comment]
Still on hold
