### ISSUE TITLE
Web - Attachment - Low resolution picture is displayed large in Preview Page

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#8451]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open http://staging.new.expensify.com/[](javascript:)
2. Open to any chat
3. Click "+" navigation
4. Select Add attachment
5. Choose a low resolution image
6. Click Send

## Expected Result:
A picture with a low resolution is displayed the same as it is displayed when opened on a computer.

## Actual Result:
A picture with a low resolution is displayed many times larger in Preview Page than the version in which it is displayed when opened on a computer.

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.46.1

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** qa.mykola@gmail.com/Passwords provided are not acceptable1

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/161408739-0a6eb0c8-f329-4b0e-9ed6-f837de048668.mp4

![daddzb7-7f2bc649-d7d6-4f27-bf37-a68e76c7a41c](https://user-images.githubusercontent.com/93399543/161408726-13cf756c-1da4-42b4-8437-76254b97141a.png)
![1x1_52be9cff](https://user-images.githubusercontent.com/93399543/161408728-90f09af8-217e-414b-8c92-7b7cdb7b17bf.png)

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by thienlnam** [comment]
Closing duplicate for this: https://github.com/Expensify/App/issues/8471
