### ISSUE TITLE
[HOLD for payment 2022-05-02] [$250] Close account page input field label doesn't fit in one line (Español) - reported by @thesahindia

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#8454]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to preferences page and change your language to Español
2. Go to close account page check the second input for entering default contact method
3. Add some text

## Expected Result:
The label text should be in a single line

## Actual Result:
Label doesn't fit in one line

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.49-0
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 
<img width="375" alt="Screenshot 2022-03-21 at 1 44 40 PM" src="https://user-images.githubusercontent.com/43995119/161470506-4e6ffef2-840d-44de-bba4-edba5f93ce5e.png">

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @thesahindia
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1647851496725259

**Job Post** https://www.upwork.com/ab/applicants/1515111330801573888/job-details

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kadiealexander** [comment]
Yes, I can see this too! The instruction text isn't aligned properly:

<img width="373" alt="image" src="https://user-images.githubusercontent.com/59587260/161471942-51cd9151-c82e-40df-a16c-e6ace8a6e0b6.png">

And it doesn't disappear when you input text:

<img width="373" alt="image" src="https://user-images.githubusercontent.com/59587260/161471950-4e98cbdd-8d94-48f0-a450-ded2cd99dc8e.png">

**Comment by flodnv** [comment]
Hmmm, asked about it [in Slack](https://expensify.slack.com/archives/C21FRDWCV/p1649068815357449)

**Comment by flodnv** [comment]
@thesahindia @mvtglobally @kadiealexander this is a tricky one. I don't see any great option. We could:
1. Change it to `Introduce tu metodo de contacto`, but we use `metodo de contacto predeterminado` everywhere
2. Do nothing
3. ???

😕

**Comment by thesahindia** [comment]
Maybe something like this -

<img width="383" alt="Screenshot 2022-04-07 at 7 18 33 PM" src="https://user-images.githubusercontent.com/83179295/162214390-e0bd475a-da42-41d5-acc3-054ab619831c.png">

**Comment by flodnv** [comment]
Hmmmm this could work, thoughts @Julesssss @luacmartins ?

**Comment by luacmartins** [comment]
Hmm I'm not a big fan of the input without labels and that might fail accessibility features as well.

I think another option is to have the user type a static string, e.g. `CLOSE` or `DELETE`. We seem to only use it to disable the `Close account` button and that would serve the same fat finger prevention/intentional action confirmation purpose. We could also get rid of the default contact method above the input. It would look something like this:

<img width="500" alt="en" src="https://user-images.githubusercontent.com/22219519/162238507-1801d20e-8757-45c4-a39b-131c66d1f253.png">
<img width="428" alt="es" src="https://user-images.githubusercontent.com/22219519/162238533-8fcf69b8-a3b7-45eb-be9f-e8bfaf8b726f.png">

**Comment by Julesssss** [comment]
Hmm, I suppose it's a good enough solution. It would be good to enforce that this is a dangerous task though. Something like 'I understand', or at least the full 'close account'?

**Comment by flodnv** [comment]
Asking again in Slack: https://expensify.slack.com/archives/C01GTK53T8Q/p1649773232745629

**Comment by flodnv** [comment]
We are going with: remove `Introduce` from the translation.

**Comment by thesahindia** [comment]
### Proposal

I would like to take this. 
We have to remove `Introduce` here -
https://github.com/Expensify/App/blob/c237f3659d843850662d728824aeff6a1a3d587f/src/languages/es.js#L325

**Comment by rushatgabhane** [comment]
@luacmartins unassigning myself, because C+ review isn't required here, and the [solution](https://github.com/Expensify/App/issues/8454#issuecomment-1098240047) was found on [slack](https://expensify.slack.com/archives/C01GTK53T8Q/p1649773232745629).

**Comment by luacmartins** [comment]
@thesahindia proposal looks good!

**Comment by thesahindia** [comment]
I have raised the PR.

**Comment by kevinksullivan** [comment]
@thesahindia please accept the offer in upwork when you get a chance!

**Comment by kevinksullivan** [comment]
@thesahindia just a heads up the offer still looks like it's awaiting your acceptance!

**Comment by thesahindia** [comment]
> @thesahindia just a heads up the offer still looks like it's awaiting your acceptance!

Hi @kevinksullivan, I am getting error when trying to accept the offer. I thought there's some problem in upwork or my account but I just accepted a different offer so I guess it's working fine.

<img width="773" alt="Screenshot 2022-04-25 at 7 20 27 PM" src="https://user-images.githubusercontent.com/83179295/166104132-df77dd7d-47a5-4eec-9dd4-b715957b589b.png">

**Comment by kevinksullivan** [comment]
Hmm @thesahindia I just withdrew the offer and resent it. Let me know if that works!

**Comment by thesahindia** [comment]
@kevinksullivan, it worked. 
Thanks.
