### ISSUE TITLE
[HOLD for payment 2022-05-20][$500] Auto-filling my information on Request a call page fills my name in the opened chat's compose box too - reported by @adeel0202

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#8456]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to https://new.expensify.com/ on Safari web
2. Go to any workspace
3. Click on Get assistance icon
4. Click on Request a setup call
5. Click on First name field
6. Click on the auto-fill icon to autofill your info
7. Observe that your auto-filled name is filled on the opened chat's compose box too

## Expected Result:
Opened chat should not be filled with auto-filled name

## Actual Result:
Opened chat is also filled with auto-filled name

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Web (Safari)

**Version Number:** 1.1.49-0
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 

https://user-images.githubusercontent.com/43995119/161470901-e44f60db-8a72-41a1-a383-a90a8a84976c.mov

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @adeel0202
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1647887778628489

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by luacmartins** [comment]
This should be external!

**Comment by MitchExpensify** [comment]
[Upwork Job](https://www.upwork.com/jobs/~017e055cdacf808682)

**Comment by luacmartins** [comment]
Still looking for proposals.

**Comment by MitchExpensify** [comment]
Doubled the price of the [Upwork Job](https://www.upwork.com/jobs/~017e055cdacf808682)!

**Comment by parasharrajat** [comment]
Hmm...no proposals yet.

**Comment by parasharrajat** [comment]
### Proposal
There are two things that need to be correct here. 
1. We should enclose the whole form on the Request call page in a Form element. I created a Form component a few days back which does this, now called `SignInPageForm`. Browser autofill checks for the form elements to group the form elements together. Due to the absence of a form tag, it considers every input element on the page as part of the form. 

`SignInPageForm` needs some cleanup and renaming.

2. (optional) We should turn the autocomplete Off on the Composer input as it does not really need it. it can be done via passing the `autoCompelete="off"` prop to the composer. 


--- 
One suggestion would be to do the same for the `Form` component. My original proposal would be to convert the requestCallpage to use the Form component but I don't see any usages of `Form` and am not sure what is planned for it.

**Comment by luacmartins** [comment]
Your proposal makes sense. I'd suggest that we refactor Form to be auto-fill enabled and convert `requestCallPage` to use it. 

The reason why we are still not using `Form` is because some inputs are still being refactored. However, it seems like that page only uses TextInput which should be ready!

**Comment by parasharrajat** [comment]
Ok. There are a couple of challenges here. 
- Button is not fixed at the bottom. 
- How will we pass the additional footer message and disable the button for `isBlockedFromConcierge`.
- FullNameInputRow is not compatible with Form.
- Design on the button. 
![image](https://user-images.githubusercontent.com/24370807/163443701-782c80ca-8769-4f43-9138-e16062807bb3.png)

**Comment by luacmartins** [comment]
Hmm ok, there are some other known issues with `Form`, e.g. https://github.com/Expensify/App/issues/8567. So maybe we postpone using it for now until it's ready. We can continue with your proposal [here](https://github.com/Expensify/App/issues/8456#issuecomment-1099093468), without the Form suggestion for now.

**Comment by parasharrajat** [comment]
Ok. Thanks. I will push the PR shortly.

**Comment by parasharrajat** [comment]
On it today.

**Comment by parasharrajat** [comment]
Should we remove the Help Wanted label here?

**Comment by luacmartins** [comment]
Ah yes! Removed :)

**Comment by luacmartins** [comment]
I believe the only action item left here is payment. @MitchExpensify could you pay @parasharrajat for the fix and close this issue please?

**Comment by luacmartins** [comment]
@laurenreidexpensify I just reassigned this since Mitch is ooo until Jun 9. The only action item left here is to pay @parasharrajat for the fix. Could you do that please?

**Comment by laurenreidexpensify** [comment]
@parasharrajat offer sent

**Comment by adeel0202** [comment]
I'm also eligible for the reporting bonus :)

**Comment by laurenreidexpensify** [comment]
cool @adeel0202 offer sent to you too! sorry we missed you there!

**Comment by adeel0202** [comment]
No worries, @laurenreidexpensify. I have accepted the offer. Thanks.

**Comment by laurenreidexpensify** [comment]
everyone has been paid, thanks folks!
