### ISSUE TITLE
[HOLD]  "okay, got it." Modal has some extra empty space on top - reported by @Tushu17

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#8457]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
 1. You need to have a workspace and some members in it
 2. Go to close account page
 3. Type default contact method
 4. Press close account button
5. View the "ok, got it" modal.

## Expected Result:
There should be same space across borders 

## Actual Result:
Modal has too much extra empty space on top

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.49-0
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 
![Screenshot_20220324-032238_New Expensify](https://user-images.githubusercontent.com/43995119/161471802-e4049db3-9c2b-4a8e-adf3-716e88f11725.jpg)

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @Tushu17
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1648072472591519

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mallenexpensify** [comment]
Hold plz, this might be a dupe (which was reported first) for https://github.com/Expensify/App/issues/8404

**Comment by isabelastisser** [comment]
Sorry, I just saw Matt's comment now so I'm removing engineering.

**Comment by mallenexpensify** [comment]
Gonna close this one, added @Tushu17 as reported by on https://github.com/Expensify/App/issues/8404
