### ISSUE TITLE
Console Error when UpArrow is pressed in emoji picker - reported by @sobitneupane

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#8458]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open Emoji Picker.
2. Press down arrow to highlight emoji.
3. Now Press UpArrow

## Expected Result:
there should be no console errors 

## Actual Result:
Console error when press UP 

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Web

**Version Number:** 1.1.46-0
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 

https://user-images.githubusercontent.com/43995119/161472017-7505293f-c879-4b63-b987-9c38648641e7.mov

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @sobitneupane
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1648122317605959

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by sobitneupane** [comment]
**Solution:**
Proposing solution as I reported this issue.
As the error statement suggests, error is occuring in following code segment. Addition of the following lines of code will solve the issue.
https://github.com/Expensify/App/blob/6e9d429ad47044d71cb028fb14d5defc2de0af8a/src/components/EmojiPicker/EmojiPickerMenu/index.js#L256-L259
```diff
           do {
               newIndex += steps;
+               if (newIndex < 0) {
+                   break;
+               }
           } while (isHeader(this.state.filteredEmojis[newIndex]));
       };
```

**Comment by sobitneupane** [comment]
Hello @Justicea83 @NicMendonca, Looks like code was deployed to production 9 days ago. Waiting for my payment.

**Comment by NicMendonca** [comment]
@sobitneupane sorry! Can you please apply for the job so we can issue payment: https://www.upwork.com/jobs/~018897a01f0bd438e7

**Comment by sobitneupane** [comment]
> @sobitneupane sorry! Can you please apply for the job so we can issue payment: https://www.upwork.com/jobs/~018897a01f0bd438e7

Applied.

**Comment by NicMendonca** [comment]
paid!
