### ISSUE TITLE
Chat - Updated pronouns are not changed in the group chat welcome text until relogin

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#8468]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Requirements: You need to previously create a group and have selected a pronoun for the participant where you will modify the information.
1. On the web, click on your profile picture
2. Click on Profile
3. Modify your pronoun and save
4. On the app, check the pronoun of the user that just changed it.

## Expected Result:
After the pronoun is modified, it should change in the chat information.

## Actual Result:
After the pronoun is modified, it does not change in the chat information until relogin

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.49_1

**Reproducible in staging?:** y

**Reproducible in production?:** y

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/161577391-3ffd7f7b-6d43-4117-a363-f22dd18feed0.mp4
![Bug5515009_Captura_de_Pantalla_2022-04-01_a_la_s__00 47 11](https://user-images.githubusercontent.com/43996225/161577431-f403cf9b-19d2-40bd-a35f-4b3dfb062afb.png)

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by marcochavezf** [comment]
It seems that we'll need to update `personalDetails` in Onyx when the pronouns are changed. I'm going to take this issue because I think it's related to another issue that I'm working on.

**Comment by marcochavezf** [comment]
Focused on Offline first, I'm going to continue with this issue soon

**Comment by marcochavezf** [comment]
No update yet

**Comment by marcochavezf** [comment]
Hi @kavimuru, I noticed the pronouns of the user logged in don't appear in the group chat, I think you're referring to the pronouns of other users in the group chat, right? 

Let's say I'm logged in with an account A, and I have a group chat with the accounts B and C, then the account B changes the pronouns (logged in from another browser/handset), but the changes are not reflected in account A until relogin, is that correct?

**Comment by marcochavezf** [comment]
This issue will be resolved with the [NewDot Optimization API](https://docs.google.com/document/d/1AF1iTabP3WUSpNPE8-C2NJ7jYSBIISViRRBZSvXNSug/edit#heading=h.ns12dr1f35rx) changes (where the response of a WRITE request will come via Pusher to all the subscribed clients). I'm going to close the ticket but we can re-open it if it's still an issue after implementing the new API changes.
