### ISSUE TITLE
[HOLD for payment 2022-05-23] [$250] Update default avatar and empty state text for #%domain% default room

### ISSUE THREAD

**Issue by kevinksullivan** [Expensify/App#8469]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Join `defaultRooms` beta using email address associated with a private domain
2. Search for the #%domain% chat room (use CMD + K)
3. Select the #%domain% chat room

## Expected Result:
The avatar should better align with a domain, and the initial text should provide a clearer purpose for this room v. others like #announce and #announce

**Avatar**

<img width="176" alt="image" src="https://user-images.githubusercontent.com/22508290/161811729-53b27c4c-4e7a-431a-9116-99a8b720363c.png">

[domain-room.svg.zip](https://github.com/Expensify/App/files/8413788/domain-room.svg.zip)
 

**Initial text**

>Collaboration with everyone at %domain% starts here!
Use #%domain% to chat with colleagues, share tips, and ask questions.

## Actual Result:
We still use a couch default avatar, and the initial text is ambiguous. 

## Platform:
- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes

**Notes/Photos/Videos:** 

![image](https://user-images.githubusercontent.com/22508290/161603325-6f50a6cf-093a-416f-a973-a31d12cc9829.png)

**Slack conversation:** https://expensify.slack.com/archives/C02MW39LT9N/p1648693249504989 

**Upwork post** https://www.upwork.com/jobs/~01d511a116d1cc31ad

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by shawnborton** [comment]
I could see something like a globe working for domain? Quick search for "domain" on Noun Project:

<img width="680" alt="image" src="https://user-images.githubusercontent.com/2319350/161606204-f5f1b605-5259-4fc9-9e74-d95c3b29b39c.png">

**Comment by kevinksullivan** [comment]
I like the first globe option best there.

**Comment by shawnborton** [comment]
Cool, we already have a globe icon in our suite - that would look like this amongst the other room type icons:
<img width="586" alt="image" src="https://user-images.githubusercontent.com/2319350/161608440-ae20292f-81dd-4d62-bc64-19ab00c23454.png">


But I can't tell if I like the outlined globe version better... thoughts?
<img width="858" alt="image" src="https://user-images.githubusercontent.com/2319350/161608990-75628323-6050-4a0f-9998-9dd33838b241.png">

**Comment by megankelso** [comment]
I think the outline version is nice but is maybe a bit out of place among this set of icons that have more solid fills/shapes.

**Comment by shawnborton** [comment]
That's a fair point, I'm cool with the globe in the first image. 

@kevinksullivan this svg should be all you need for the new room icon asset: [domain-room.svg.zip](https://github.com/Expensify/App/files/8413788/domain-room.svg.zip)

**Comment by kevinksullivan** [comment]
Thanks @megankelso @shawnborton , updated the OP and will move this forward.

**Comment by Puneet-here** [comment]
Hey can I work on this?

Here's my proposal
### Proposal

Need to add this function in reportUtils
```js
function isDomainRoom(report) {
    return lodashGet(report, ['chatType'], '') === CONST.REPORT.CHAT_TYPE.DOMAIN_ALL;
}
```
Will add another check here
https://github.com/Expensify/App/blob/2e118780cdbf1a07cfa4abfc0338361d61002978/src/libs/OptionsListUtils.js#L214-L224
```
 if (ReportUtils.isDomainRoom(report)) {
             return Expensicons.DomainRoomAvatar;
         }
```
will add
`const isDomainRoom = ReportUtils.isDomainRoom(props.report);`

https://github.com/Expensify/App/blob/2e118780cdbf1a07cfa4abfc0338361d61002978/src/components/ReportWelcomeText.js#L51-L53

and will use isDomainRoom to show a different text like we already have
https://github.com/Expensify/App/blob/2e118780cdbf1a07cfa4abfc0338361d61002978/src/components/ReportWelcomeText.js#L78-L89

**Comment by Gonals** [comment]
I think this is a good candidate for external!

**Comment by JmillsExpensify** [comment]
@kevinksullivan happy to pick this one back up now that I'm back from OOO. Just let me know!

**Comment by rushatgabhane** [comment]
@Beamanator I think it's a good idea to hold this issue until PR https://github.com/Expensify/App/pull/8239#issuecomment-1076780473 is merged.

Because we might wanna use RenderHTML to tidy it up a bit.

**Comment by Beamanator** [comment]
Great idea @rushatgabhane 👍 I'll put this on hold for now!

**Comment by Beamanator** [comment]
@kevinksullivan / @JmillsExpensify we're putting this on hold b/c the solution for this issue will be very very similar to how we'll fix these two issues:
- https://github.com/Expensify/App/issues/7625
- https://github.com/Expensify/App/issues/8272

**Comment by rushatgabhane** [comment]
@Beamanator we've reached a resolution - move forward with this issue using the regular split text approach.
```
{
    myMessagePart1: 'yadayada',
    myMessagePart2: 'yadayada',
}
```

Then go back and refactor once we settle on a better approach

**Comment by rushatgabhane** [comment]
🎀 👀 🎀 C+ reviewed 

I recommend @Puneet-here's [proposal](https://github.com/Expensify/App/issues/8469#issuecomment-1089267174).

**Comment by Beamanator** [comment]
@rushatgabhane good point, but it now looks like their PR has been merged 👍

**Comment by Beamanator** [comment]
Also thanks for noting that this doesn't need to be on hold anymore - and I agree @Puneet-here 's proposals looks solid, hiring! 👍

**Comment by Puneet-here** [comment]
Thank you. I will raise a PR soon.

**Comment by Puneet-here** [comment]
Hi, I don't have a private domain account I have made the changes but to test them I need an account with private domain, is there any testing account for that?

**Comment by Beamanator** [comment]
Great question @Puneet-here - I don't know of any off the top of my head, but please ask your question in #expensify-open-source because I'm sure other contributors are wondering the same thing.

If there aren't any test accounts for you to use, feel free to create the PR with your changes and I will test

**Comment by rushatgabhane** [comment]
I have a domain, but I'm clueless on how to create a domain chat room.

**Comment by Puneet-here** [comment]
Yeah me too, I found a private domain email from temp mail site and tried creating a domain chat but couldn't do it.

**Comment by rushatgabhane** [comment]
@Puneet-here maybe raise a PR and someone internal/ QA can test it out?

**Comment by Beamanator** [comment]
Yeah I agree with @rushatgabhane - @Puneet-here can you please create a PR? I will test since this seems like a pretty small change :D

**Comment by Puneet-here** [comment]
Sure, I will raise the PR. 
Also I need the translation for these lines. Should I ask about it on slack?
1. "Collaboration with everyone at %domain% starts here!"
2. "Use #%domain% to chat with colleagues, share tips, and ask questions."

**Comment by Beamanator** [comment]
@Puneet-here Yes please feel free to ask for those translations in slack :D 👍

**Comment by Puneet-here** [comment]
@Beamanator, I have asked for the translation [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1650977105152189)
 
At announce room we use `Collaboration starts here! 🎉` as the first line,
at announce room we use `Collaboration between all ${workspaceName} members starts here! 🎉`

instead of using `Collaboration with everyone at %domain% starts here!` should I just use the existing one for the first line?
https://github.com/Expensify/App/blob/8fae5e8c1adf0c2c1b6bae84cb1c979140fe6465/src/languages/en.js#L182

**Comment by Puneet-here** [comment]
Also i found that workspace name isn't bold at rooms
<img width="773" alt="Screenshot 2022-04-26 at 8 44 42 PM" src="https://user-images.githubusercontent.com/101883770/165348526-426c825f-f5a3-4a45-80a4-f35f5a0ddc35.png">

**Comment by Puneet-here** [comment]
I didn't get any reply on slack for translation so I have pushed the thread again on channel.

**Comment by Beamanator** [comment]
@Puneet-here sorry for the delay, I tagged a few more people in the Slack thread, people who were involved in the initial convo so let's see what they say 👍

**Comment by Beamanator** [comment]
@Puneet-here yes please, sorry for the delayed response

**Comment by Puneet-here** [comment]
> @Puneet-here yes please, sorry for the delayed response

No worries. I have raised the PR (forgot it's saturday hehe)

**Comment by Beamanator** [comment]
Not overdue, PR is on staging 👍

**Comment by mallenexpensify** [comment]
Hired @rushatgabhane and @Puneet-here , let me know when y'all have accepted https://www.upwork.com/jobs/~01d511a116d1cc31ad

**Comment by Puneet-here** [comment]
I have accepted the offer. 
Thanks.

**Comment by mallenexpensify** [comment]
Paid @Puneet-here and @rushatgabhane $250 ea for the fix and C+. Thanks for the help!

**Comment by kevinksullivan** [comment]
Thanks @mallenexpensify , sorry about the delay, was OOO.
