### ISSUE TITLE
Default policy-related rooms are still accessible after being removed from the policy 

### ISSUE THREAD

**Issue by kevinksullivan** [Expensify/App#8470]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Add two email addresses to `defaultRooms beta
2. Create a workspace with user 1
3. Go to the `Manage members` tab of the workspace, invite user 2
4. Login to user 2 via incognito window, verify that there is an #announce chat room shown in LHN
5. Navigate back to user 1 session, remove user 2 from the policy
6. Navigate back to user 2 session

## Expected Result:
User 2 should immediately stop seeing the #announce room (and #admins room if they are an admin) associated with the policy after they were removed.

## Actual Result:
User 2 still had access to the policy room until logging out and logging back in. the subheader changes to "Unavailable" and user 2's messages don't send to others, but they can still view the history and it appears as though they can chat there as well.

## Platform:
- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**Email or phone of affected tester (no customers):** kevin@expense.business (user 1), kevin+0000@expense.business (user 2)

**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/22508290/161608297-733b4304-9858-466e-b8e1-0b9d724b4c88.mp4

**Slack conversation:**  https://expensify.slack.com/archives/C02MW39LT9N/p1648693269832029

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kevinksullivan** [comment]
@yuwenmemon just want to flag this one for you in case you have any other input.

**Comment by JmillsExpensify** [comment]
Commenting on this one so it goes into my "participating" filter.

**Comment by yuwenmemon** [comment]
Do we want to be removing access to the room upon refresh - or right away without even refreshing?

**Comment by kevinksullivan** [comment]
@yuwenmemon ideally it would be without needing a refresh, which was the initial design.

**Comment by yuwenmemon** [comment]
FYI, from testing it looks like the other way around doesn't work either.

If I'm logged in as User A, and then get invited to Workspace X by User B, I don't see the announce room for Workspace X until signing out and then back in again - are we aware of that?

**Comment by kevinksullivan** [comment]
Hm I didn't catch that in my first [test run](https://docs.google.com/document/d/15dlNuGsFSFRTy2lziExW2j8_vARPKll-pYDwQIRZorg/edit#heading=h.k7cxic8i7ncc) while removing / re-adding a user. I definitely was not logging out and back in to see the rooms either.

**Comment by kevinksullivan** [comment]
I just tested by inviting kevin+0000@expense.business and I had to hard refresh to see the room, but didn't need to log out/ log in.
