### ISSUE TITLE
Too large message hangs the app

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#8482]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Send a really long message (e.g. 233k characters) 

## Expected Result:
User should either not be allowed to send a very long messages or app should work fine 

## Actual Result:
if you send a message that is too large the entire app hangs and you end up in an unknown state until you force quit the app or in the case of the web app close the tab and open a new one.

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.49-0
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 
![Screen Shot 2022-04-04 at 11 15 25 PM](https://user-images.githubusercontent.com/43995119/161671924-1fa86a65-8b49-49a1-9d8e-ec0c3f4ef743.png)

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @coleaeason 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1648836761395939 & 
https://expensify.slack.com/archives/C01GTK53T8Q/p1648854495944779 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Julesssss** [comment]
Yep, I can confirm this is occuring. I'm also seeing heavy lag as the user typing the long message -- especially when making an edit to the message before sending it. Ideally we would reduce the max message length, I recall us deciding against this previously so let's get additional thoughts before moving forward here.

**Comment by Julesssss** [comment]
We discussed [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1649168770226539), the desired solution is to simply split the message on the backend and send two messages one after the other. 

It's an internal issue.

**Comment by Julesssss** [comment]
Actually, I'm going to close this and reopen internally.
