### ISSUE TITLE
workspace.invite.pleaseEnterValidLogin does not exist

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#8495]
## Action Performed:
1. Navigate to `Workspace > Manage members > Invite`
2. Type a login that doesn't exist
3. Click invite
4. Verify that nothing happens and you see the following error in the console.

![Screen Shot 2022-04-05 at 2 51 01 PM](https://user-images.githubusercontent.com/22219519/161846850-5c69ca65-efe0-497f-905f-fd50528a265b.png)

## Expected Result:
We should display feedback to the user

## Actual Result:
Nothing happens.

## Workaround:
User can retry until they realize they typed the wrong value.

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 
**Reproducible in staging?:** 
**Reproducible in production?:** 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:** 
**Issue reported by:** 
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by thesahindia** [comment]
Hi @luacmartins, is this eligible for the reporting bonus as it was reported [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1648323880003309)

**Comment by luacmartins** [comment]
Hey @thesahindia! Sorry, I found this issue while working on [this PR](https://github.com/Expensify/App/pull/8496) and didn't see that it had been reported before (since your GH was created after this one). I'll ask what our policy is in this case and report back.

**Comment by luacmartins** [comment]
@thesahindia we'll proceed with the reporting bonus payment. I just asked Applause to update the reporter of the issue, as it's incorrectly stated on your GH. Once that's done, we will follow the normal flow for payment. Thanks!
