### ISSUE TITLE
[$250] Pressing down-key after searching a new user Crashes the Website - reported by @Tushu17

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#8505]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
 1. Open Website > Search
 2. Write a Random Phone No.
 3. Press Down-key

## Expected Result:
It should highlight the shown result.

## Actual Result:
It crashes the website.

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Web

**Version Number:** 1.1.51-1
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 
<img width="461" alt="image - 2022-04-05T235031 362" src="https://user-images.githubusercontent.com/43995119/161892331-224bdcd9-81d0-4821-a286-9a22d80ab760.png">

https://user-images.githubusercontent.com/43995119/161892334-aa94cfd7-e387-42da-acee-3a5b923c6f03.mov

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @Tushu17
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1649153212387179

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

https://www.upwork.com/jobs/~01bb2be4f8a5df6802

**Comment by sobitneupane** [comment]
**Proposal:**
**Reason:** We are pushing three section in getSections function in SearchPage which is later used in OptionsSelector. When we enter new user's name or phone number the first two sections has data empty []. So, we are getting the error.
https://github.com/Expensify/App/blob/1b0687408896efd9a1e0808d2f7b08b518846760/src/pages/SearchPage.js#L92-L116
We need to replace above code with following lines of code:
```
getSections() {
    let sections = [];
    if (this.state.recentReports.length > 0) {
        sections.push(({
            data: this.state.recentReports,
            shouldShow: true,
            indexOffset: 0,
        }));
    }

    if (this.state.personalDetails.length > 0) {
        sections.push(({
            data: this.state.personalDetails,
            shouldShow: true,
            indexOffset: this.state.recentReports.length,
        }));
    }
    
    if (this.state.userToInvite) {
        sections.push(({
            undefined,
            data: [this.state.userToInvite],
            shouldShow: true,
            indexOffset: 0,
        }));
    }

    return sections;
}
```

**Comment by Justicea83** [comment]
great suggestion @sobitneupane , but the issue persists on Desktop as well so you can update the issue.

**Comment by Tushu17** [comment]
@Justicea83 The fix is in the production and the payment is pending for this can you assign someone to create an upwork job for me.

**Comment by Justicea83** [comment]
PR already done, and fix applied @dylanexpensify can we create a job and pay @Tushu17 ?

**Comment by Tushu17** [comment]
I've applied to the job.

**Comment by jboniface** [comment]
[this post](https://www.upwork.com/jobs/~0144114aadaf9db2b7)

**Comment by Tushu17** [comment]
@jboniface I have already applied to the job made by @dylanexpensify Should I be applying to the new job as there's already a job open.

Also we don't need a c+ and contributor manager here as this issue has already been fixed can you unassign them.

**Comment by jboniface** [comment]
@Tushu17 oh, i'm a dope, I didn't even realize the job was already made 🦤 , just use the original one and i'll delete mine

**Comment by Santhosh-Sellavel** [comment]
@jboniface Let's close this one out!
