### ISSUE TITLE
Workspace chat - Attachments hides under the footer text when scrolling

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#8532]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to https://staging.new.expensify.com/[](javascript:)

2. Create a new workspace from an account that's on the policyExpenseChat beta (e.g @expensifail.com)
3. Add a new member to the workspace via Manage Members > Invite
4. Log-in as the member and send a message and and Attachment in the member's workspace chat
5. Log back in again to the admin account and remove the member from the workspace via Manage Members > Remove
6. Verify the row chat (in LHN and search bar) should display the default subtitle (workspace name)
7. Now log-in as the member again
8. Verify the row chat (in LHN and search bar) includes the workspace name
9. Verify the footer message displays the workspace

## Expected Result:
Attachment should be fully visible

## Actual Result:
Attachment is hidden under footer message

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- iOS

**Version Number:**  1.1.52-0

**Reproducible in staging?:** y

**Reproducible in production?:** y

**Email or phone of affected tester (no customers):** applausetester+033122abb@applause.expensifail.com / Feya86Katya

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** 

**Expensify/Expensify Issue URL:** 

https://user-images.githubusercontent.com/43996225/162202148-01272ddb-9335-4fe0-a03f-f654595090cd.mp4

**Issue reported by:** Applause

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by NikkiWines** [comment]
Hmm, I don't think this is actually a bug? I would think that it's expected for the footer would overlap with chat text, but maybe I'm wrong. 

cc: @roryabraham since I saw you implemented [this PR](https://github.com/Expensify/App/pull/7831) around adding the workspace footer.

**Comment by roryabraham** [comment]
🚫 🐛
