### ISSUE TITLE
You cannot start a Group DM with Concierge or concierge@expensify.com

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#8586]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Start a Group DM, try to type Concierge or [concierge@expensify.com](mailto:concierge@expensify.com)

## Expected Result:
Like starting a chat with Concierge, or emailing [concierge@expensify.com](mailto:concierge@expensify.com) and cc'ing other participants will start a DM with Concierge included, we should allow for group DM's to be created with Concierge as a participant.
Note: You should still absolutely NOT be able to split a bill or request money from or pay money to Concierge.

## Actual Result:
No results found

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.54-0
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 
<img width="380" alt="image - 2022-04-11T010351 788" src="https://user-images.githubusercontent.com/43995119/162668268-d5f481b4-10c6-42e0-bdf2-e5a68cffe5b3.png">

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @twisterdotcom 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1649409599962969

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by MariaHCD** [comment]
I think the issue lies [here](https://github.com/Expensify/App/blob/main/src/pages/NewChatPage.js#L63-L67) when setting the `excludedGroupEmails`, it looks like [_.without](https://lodash.com/docs/4.17.15#without) does not accept an array of values to exclude but rather accepts the values as multiple arguments.

Just to clarify, we definitely want to exclude `CONST.EMAIL.RECEIPTS` & `CONST.EMAIL.INTEGRATION_TESTING_CREDS` when creating a group chat, correct?

cc: @marcaaron @parasharrajat

**Comment by twisterdotcom** [comment]
I agree we shouldn't include receipts. I'm not sure what integration testing creds does though or how that would adversely affect us if they did start a chat with it.

**Comment by MariaHCD** [comment]
> I agree we shouldn't include receipts

Agreed!

> I'm not sure what integration testing creds does though or how that would adversely affect us if they did start a chat with it.

Since that email is used for internal testing, I'd say we should exclude this email as well.

> What is the expected behavior here?

I think we'll need to do something like this to exclude all other expensify emails except concierge when starting a new group chat:

```js
this.excludedGroupEmails = _.without(CONST.EXPENSIFY_EMAILS, CONST.EMAIL.CONCIERGE);
```
