### ISSUE TITLE
Feature request: Add a download button to the context menu for attachments.

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#8588]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Problem: 
It’s hard to locate the download button, and it’s a two step process (open attachment -> click download).

## Solution: 
Add a download attachment button to the context menu.

## Action Performed:
1. Open any chat 
2. Send few attachments 
3. Try to download attachment sent

## Expected Result:
User should see download icon in chat 

## Actual Result:
User has to click on the file to open it before locating download button 

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.54-0
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 
![Screen Shot 2022-04-11 at 1 11 04 AM](https://user-images.githubusercontent.com/43995119/162669021-900744f0-c40f-4f4c-a1e6-5469858aefe7.png)

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @joaniew 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1649278748377769

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by techievivek** [comment]
Seems like a good feature to add to New Expensify. We would also need help from the Design team.

**Comment by megankelso** [comment]
Perhaps we just add the download button to our current hover design for attachments?

![dnload](https://user-images.githubusercontent.com/49413768/162840798-9ffbc746-cc26-418b-b2be-111c3c51d78b.png)

**Comment by techievivek** [comment]
wouldn't it be convenient if we have just over the image, just like how we have in Slack?

**Comment by techievivek** [comment]
@megankelso But I think your suggestion wilL provide a consistent UI and also be easy to implement. So let's take a call on one of these and I will move forward with implementing it.

**Comment by megankelso** [comment]
cc @Expensify/design for thoughts but I think this would be the correct way to add this feature into our existing UI

**Comment by shawnborton** [comment]
Interesting, I can see both sides of this. 

Slack does this where you just hover over an image:
<img width="397" alt="image" src="https://user-images.githubusercontent.com/2319350/163020592-e7fd6349-e93d-4e19-8b7f-050b6a179798.png">

And I think that makes sense because with Slack, you could have a message that has multiple images attached to it. 

For Expensify though, I believe we currently only show one image per message in all cases. So I actually think what Megan has mocked up makes sense for the v1 of this feature (it seems like the most consistent and easiest thing to implement) until we start to support multiple images per message in the future.

**Comment by megankelso** [comment]
good point, this wouldn't work for multiple images in a message

**Comment by techievivek** [comment]
Ok cool thanks for all the inputs, I will start working on it now. 🙌

**Comment by megankelso** [comment]
not overdue! any updates here?

**Comment by JmillsExpensify** [comment]
Interesting yeah I agree that the comment action menu feels like the right place for now. 

That said, I also have one request: If would be great to pull these kinds of platform decisions out of Github and into Slack. I'd highly recommend posting in #expensify-open-source and then reposting in #product so we get ample feedback from both the community as well as Expensify employees.

**Comment by techievivek** [comment]
Sure @JmillsExpensify will keep that in mind going forward. And will push a PR today itself.
