### ISSUE TITLE
[$500] Andriod/IOS - Can not see preview of password protected PDF file @parasharrajat

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#8593]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
 1. Open the app on Android.
 2. Open any chat.
 3. Press on plus button and select add attachment > select Document.
 4. Choose any password protected PDF.
 
You can use this protected PDF file to test: [password-protected.pdf](https://github.com/Expensify/App/files/8465125/password-protected.pdf)

The password is `1234`

## Expected Result:
It should either should a message " Can not show encrypted pdf's preview" or ask for password to open the preview.

## Actual Result:
  Blank view on Attachment preview on Android/IOS app.

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- iOS
- Android

**Version Number:** 1.1.54.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** applausetester+0901abb@applause.expensifail.com

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

![image - 2022-04-11T012924 657](https://user-images.githubusercontent.com/93399543/162756774-983c5a79-c5be-43d5-bf88-afc94b26f64c.png)

**Expensify/Expensify Issue URL:** 

**Issue reported by:** @parasharrajat

**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1649155901812739

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by stephanieelliott** [comment]
Exported to Upwork: https://www.upwork.com/jobs/~0109467a22a120bcb4

**Comment by stephanieelliott** [comment]
2x'd to $500: https://www.upwork.com/jobs/~0109467a22a120bcb4

**Comment by thienlnam** [comment]
Closing this in favor of https://github.com/Expensify/App/issues/8595
