### ISSUE TITLE
Chat- 500 Error message for the receipts@expensify.com

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#8600]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to https://staging.new.expensify.com
2. Log in with expensifail account
3. Click on Fub menu - Create New Chat
4. Type receipts@expensify.com
5. Click on receipts@expensify.com

## Expected Result:
Error message should have meaning for the user

## Actual Result:
500 Error message for the receipts@expensify.com

## Error message:
500 need to pass at least two accounts

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.54.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** n/a

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/162798619-41bc5c05-7bb0-438b-8e22-12bc90b8c134.mp4

![error500](https://user-images.githubusercontent.com/93399543/162798594-363480b8-1968-46e8-8133-36cd1ea428fc.jpg)

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by pecanoro** [comment]
Hmm, I can't reproduce with any other account besides the expensifail domain, I am not able to send a message to `receipts@expensify.com`. Since we get the details from all policies, I think this is due to an old bug before we blocked adding receipts as a policy member. I am going to close because of that!
