### ISSUE TITLE
[$500] Closing a modal navigates back to the OldDot transition

### ISSUE THREAD

**Issue by neil-marcellini** [Expensify/App#8601]
[This PR for Web Expensify](https://github.com/Expensify/Web-Expensify/pull/33520) will fix this issue by opening the transitions in a new tab, but it would be good to fix this issue so that we can transition in the same tab. If this PR has already been merged, undo the changes locally to reproduce this issue.

## Action Performed:

1. Go to OldDot and sign up for a new account with an @gmail.com address
2. Click on the "Get started" on the inbox task that says "Would you like to get started with our free plan?".
3. Sign out of NewDot
4. Go back to the OldDot inbox and refresh the page
5. Click "Continue setup" on the inbox task that says "Finish setting up your bank account".
6. After the "Connect bank account" modal page opens in the RHN, hit back or close

## Expected Result:
The "Connect bank account" modal closes and the home screen is displayed

## Actual Result:
The user is navigated back to the OldDot transition page.

## Workaround:
Open NewDot in a new tab and navigate there.

## Platform:

- Web
- Mobile Web

**Version Number:** v1.1.52-0
**Reproducible in staging?:** yes
**Reproducible in production?:** yes
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:** 
**Issue reported by:** 
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by timszot** [comment]
@neil-marcellini is this something that could be external? It sounds like it might be an internal issue to me, but I might be missing something here.

**Comment by neil-marcellini** [comment]
I think it could be external since I'm pretty sure it has to do with React navigation.

**Comment by arielgreen** [comment]
https://www.upwork.com/jobs/~01b5bd589c6d58aeb0

**Comment by arielgreen** [comment]
Increased price
