### ISSUE TITLE
`Push_Authenticate` (and others) cause forced log outs when reauthentication attempt happens and a `jsonCode: 403` is returned

### ISSUE THREAD

**Issue by marcaaron** [Expensify/App#8637]
## Problem

There are tons of logs like this

```
[hmmm] Redirecting to Sign In because we failed to reauthenticate ~~ command: 'Push_Authenticate' error: 'passwordForm.error.invalidLoginOrPassword' 
```
`passwordForm.error.invalidLoginOrPassword` means we got a `jsonCode: 403` when calling `Authenticate`, but it's not clear why.

## Solution

- Add more logging to see if we can fix this or get more information at least
- Make this log an alert. `Log.hmmm()` is way too chill.

**Comment by marcaaron** [comment]
In one case ([logs](https://www.expensify.com/_devportal/tools/logSearch/#sort=asc&size=10000&query=request_id%3A%226fb00b223fbfa87c-SJC%22%20AND%20timestamp%3A%5B2022-04-12T23%3A21%3A47.084Z%20TO%202022-04-13T01%3A21%3A47.084Z%5D)), looks like Auth is throwing `404 No user with that partner/userID`, but then PHP rethrows a `403` here:

https://github.com/Expensify/Web-Expensify/blob/9c7ba8f3e18126844bdd9da4a488ec987c57fb6b/lib/UserAPI.php#L1124-L1127

I'm confused how it's possible though because `$twoFactorAuthCode` would need to be _truthy_, but we only call `Authenticate` with a 2fa code when we sign in here 🤯 

https://github.com/Expensify/App/blob/fc3e13ea735874b4223b3ce2a88cc03e83ec9ee7/src/libs/actions/Session/index.js#L231-L253

**Comment by marcaaron** [comment]
Ah hmmm... so this is interesting... looking at other logs and this can also happen if a user hasn't validated their account yet (e.g. they created a free workspace). But we are turning all authenticate errors from NewDot into `403` because this is a string of `undefined` somehow.. cc @johnmlee101 seems indirectly related to https://github.com/Expensify/Web-Expensify/pull/33469 

![2022-04-13_12-29-15](https://user-images.githubusercontent.com/32969087/163280548-2a26fbd0-0a33-4d0c-9aa8-7b55bcc9bf7d.png)

**Comment by johnmlee101** [comment]
😬 so your proposal is to make $twoFactorAuthCode check for true and `!==` `undefined`?

**Comment by johnmlee101** [comment]
We can also change that to `if ($twoFactorAuthCode && $e->getCode() === 403)` potentially

**Comment by marcaaron** [comment]
Haha well first I'm going to look into why is it a `String` of `'undefined'` ?

**Comment by marcaaron** [comment]
Ahahaha OK so if we send any parameter to Web-Expensify with `FormData` it will show up as `'undefined'`. Think it's pretty safe to say we will never want to do this for any reason.

**Comment by johnmlee101** [comment]
Good catch
