### ISSUE TITLE
[HOLD for payment 2022-05-20][$250] Update Form.md with the correct input character counter and enter press behavior

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#8645]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
The Form.md doc is outdated. In particular, the sections below:

1. https://github.com/Expensify/App/blob/main@%7B2022-04-12T19:03:07Z%7D/FORMS.md#character-limits - this feature was removed for now
2.[Additionally, ressing the enter key on any focused field should submit the form.](https://github.com/Expensify/App/blob/main@%7B2022-04-12T19:03:07Z%7D/FORMS.md#focus-and-tab-behavior) - we should add an exception for a multiline input.

## Expected Result:
The doc should be up to date and inputs.

## Actual Result:
Doc is outdated.

## Workaround:
Ignore the outdated sections of the doc.

## Platform:

Where is this issue occurring?

**Version Number:** 
**Reproducible in staging?:** 
**Reproducible in production?:** 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:** 
**Issue reported by:** @parasharrajat 
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Upwork Job** https://www.upwork.com/jobs/~0126ebd7bae5f2670c

**Comment by Puneet-here** [comment]
Hi, I can update it.

**Comment by Puneet-here** [comment]
We can make these changes:-

### Character Limits

If a field has a character limit we should give that field a max limit. This is done by passing the maxLength prop to TextInput.

```jsx
<TextInput
    maxLength={20}
/>
```
Note: We shouldn't place a max limit on a field if the entered value can be formatted. eg: Phone number.
The phone number can be formatted in different ways 

- 2109400803
- +12109400803
- (210)-940-0803

https://github.com/Expensify/App/blob/fd230734f5341faff08df79cb2a8d6e26d16b0e7/FORMS.md?plain=1#L69
we can add another line here:

`Note: This doesn't apply to the multiline fields, pressing enter on multiline fields shouldn't submit the form`

**Comment by luacmartins** [comment]
Your proposal looks good @Puneet-here!

**Comment by luacmartins** [comment]
@Puneet-here please apply to the job in Upwork once it's exported.

**Comment by parasharrajat** [comment]
@Puneet-here's proposal looks good here. I don't think C+ is needed for such an issue but I am fine with reviewing the PR.

cc: @Julesssss 

:ribbon: :eyes: :ribbon:  C+ reviewed

**Comment by Julesssss** [comment]
I think we still need the UpWork job to be created first? But yep, the proposal looks good.

**Comment by Julesssss** [comment]
Oh nevermind, Melvin was delayed for some reason 🤷‍♂️

**Comment by Puneet-here** [comment]
I have applied to the upwork job.
Thanks.

**Comment by Puneet-here** [comment]
I have raised the PR.
Thanks.

**Comment by Julesssss** [comment]
PR merged, awaiting deploy

**Comment by Julesssss** [comment]
We're still awaiting deploy, had a couple of issues this week but it should occur pretty soon now.

**Comment by Julesssss** [comment]
@kevinksullivan this one is good for payment 👍

**Comment by kevinksullivan** [comment]
Paid @Puneet-here . Job was closed so I reposted a new one to cover C+ @parasharrajat [here](https://www.upwork.com/jobs/~012c437de622b34192). Please let me know when you accept and I'll handle that payment!

**Comment by parasharrajat** [comment]
@kevinksullivan Accepted it.

**Comment by parasharrajat** [comment]
@kevinksullivan Bump.

**Comment by luacmartins** [comment]
@parasharrajat Kevin is ooo until Monday. Let me know if this can't wait and I'll assign another CM.

**Comment by kevinksullivan** [comment]
All set thanks for your patience @parasharrajat .
