### ISSUE TITLE
mWeb - Payments - "Add to payment method" blinks when user accesses the menu 

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#8646]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Access [www.staging.new.expensify.com](http://www.staging.new.expensify.com/)[](javascript:)
2. Log into any valid account
3. Tap on the "Profile" icon on the top right
4. Tap on "Payments" option

## Expected Result:
The user expects that when the page loads, there is no flickering or delayed loading

## Actual Result:
The "Add Payment method" text is initially "Blocked" before turning black as it should be

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Mobile Web

**Version Number:** 1.1.55.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** n/a

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/163432663-052966fc-7e04-413c-bccb-d4bd277e2d39.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by neil-marcellini** [comment]
We gray out and disable adding payments when the payment methods are loading, but I can't see why we would do that, so I'll ask about it in Slack.

**Comment by neil-marcellini** [comment]
This could be external, but I'm going to take it for myself. I think it would be worth fixing, but I'll wait for more feedback before I start working on it.
