### ISSUE TITLE
Phone Account - SMS validation link is not received for creating new phone account (Ukraine region)

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#8648]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to https://staging.new.expensify.com
2. Enter the phone number +380672202413 for creating new account
3. Tap Send Validation Link

## Expected Result:
SMS validation link arrives for creating a new account

## Actual Result:
SMS validation link is not received for creating new phone account

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.55.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** +380672202413/Yulia1986Gerets

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/163482430-112b5897-08b7-472d-8e22-bf76718394e1.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by tylerkaraszewski** [comment]
This looks similar to this issue: https://github.com/Expensify/Expensify/issues/205669 in that we probably need to sign up somewhere to be able to send texts in Ukraine. Unassigning myself from triage for someone else to work on it.
