### ISSUE TITLE
[$500] Upgrade OnFido SDK to 8.0.0

### ISSUE THREAD

**Issue by michaelhaxhiu** [Expensify/App#8652]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
## Expected Result:

- OnFido needs to be updated to the newest version of the SDK (6.20.0), and so we need to upgrade accordingly -- full details of the new release are here https://github.com/onfido/onfido-sdk-ui/releases/tag/6.20.0.
- We need to do this because it's a prerequisite to troubleshooting/resolving potential issues that arise in their SDK 
- Here's an example of where we upgraded the SDK in the past https://github.com/Expensify/App/pull/6211

Please update the Onfido UI SDK and Onfido React Native SDK in E/App

```
### Fixed in 6.20.1

- Public: Fix useLiveDocumentCapture onComplete not working (cross device capture `variant` missing)
```
---

## Actual Result:
OnFido SDK isn't updated to the latest.

## Workaround:
>Can the user still use Expensify without this being fixed? Have you informed them of the workaround?
Yes.

## Platform:

Where is this issue occurring?

- Web

**Version Number:** 
**Expensify/Expensify Issue URL:** https://github.com/Expensify/Expensify/issues/206694

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by michaelhaxhiu** [comment]
@marcaaron can you help confirm that this is eligible for `External`?

**Comment by marcaaron** [comment]
>OnFido needs to be updated to the newest version of the SDK (6.20.0)

Where does it need to be upgraded? Everywhere or only New Expensify?

**Comment by marcaaron** [comment]
Agree this can be `External` as it's just updating a library. But the flow needs to be tested still so maybe we can make sure QA is done correctly and there are no regressions after updating.

**Comment by MitchExpensify** [comment]
[Upwork Job ](https://www.upwork.com/jobs/~0193e8647cb6379c68)

**Comment by amyevans** [comment]
> Where does it need to be upgraded? Everywhere or only New Expensify?

I just searched for where we're using the package, and it looks like it's in Web-Secure in addition to App. So perhaps this should stay internal after all?

**Comment by michaelhaxhiu** [comment]
cc @nkuoch or @chiragsalian for your input too, since you both were involved in the last SDK update for OnFido. Seems we still are uncertain about whether this is **internal** or **external**.

**Comment by marcaaron** [comment]
We can have a contributor update `Expensify/App`, but if we want to bump the SDK versions in Web-Secure that will need to be `Internal`. Seems they do not need to be updated at the same time or by the same engineer. 

**suggestion:** 

- Leave this `External` and ask for Onfido UI SDK + Onfido React Native SDK to be updated in `App`
- Open a new issue in `E/E` to update the `Web-Secure` repo

**Comment by rushatgabhane** [comment]
Sorry, I can't help here. I'm gonna unassign myself because I have school stuff going on 📚

**Comment by michaelhaxhiu** [comment]
@marcaaron thanks for the guidance 🙏 I repurposed https://github.com/Expensify/Expensify/issues/206694 in E/Expensify to be for web-secure, and will keep this GH as-is for E/App.

**Comment by marcochavezf** [comment]
Not overdue, waiting for proposals

**Comment by michaelhaxhiu** [comment]
Should we be doubling price of this job @MitchExpensify ?

**Comment by MitchExpensify** [comment]
Yes I will today @michaelhaxhiu

**Comment by MitchExpensify** [comment]
Doubled! [Upwork Job](https://www.upwork.com/jobs/~0193e8647cb6379c68)

**Comment by Regaron** [comment]
# Proposal
Looking at the change logs there doesn’t seem to be any breaking changes. So we can just update the packages and test for regressions.

**Comment by jayeshmangwani** [comment]
### **Proposal**

it is a straightforward change of the updating package, need to update to the latest version of onfido-sdk-ui, as at this time it is [8.0.0](https://github.com/onfido/onfido-sdk-ui/releases/tag/8.0.0), and then need to test in web and desktop , that update the package is working fine or not

**Comment by michaelhaxhiu** [comment]
There is no C+ on this issue since Rajat un-assigned himself, so I'm triggering re-assignment.

**Comment by twisterdotcom** [comment]
@jayeshmangwani is right, this is now 8.0.0. Updated the issue title.

**Comment by michaelhaxhiu** [comment]
This SDK seems to be updating pretty frequently, and consecutively each week... is this the norm? If so, I wonder if this is best handled internally after all?

**Comment by nkuoch** [comment]
I agree. I think whoever does Web-Secure internally could do App at the same time - it's not much more work.

**Comment by Santhosh-Sellavel** [comment]
Is this still external? or internal? @michaelhaxhiu

**Comment by michaelhaxhiu** [comment]
@Santhosh-Sellavel I'm working on making this internal right now, based on the comments [above](https://github.com/Expensify/App/issues/8652#issuecomment-1121005859).
