### ISSUE TITLE
[HOLD for payment 2022-05-20][$250] After changing language to Espanol "Are you sure" didn't change - reported by @Puneet-here

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#8662]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
 1. Change the default language to Espanol
 2. Add bank account manually
 3. Fill the company form and submit it, after that you will see personal information page
 4. Press the cross on top right to exit to the homepage
 5. Now from homepage go back to bank account page you will see an option to start over click on it

## Expected Result:
 You should see the correct translated text

## Actual Result:
After changing language to Espanol "Are you sure" is not translated

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.54-0
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 
<img width="438" alt="modal" src="https://user-images.githubusercontent.com/43995119/163697812-7186114c-b0d1-431d-aae7-f2b7093d6e57.png">

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @Puneet-here
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1649326577396609 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Puneet-here** [comment]
### Proposal 
https://github.com/Expensify/App/blob/6c53be1ea7a022e8a5e788cc7e7efd62c4573474/src/pages/workspace/WorkspaceResetBankAccountModal.js#L39
need to change it to 
```js
title={props.translate('workspace.bankAccount.deleteConfirmation')}
```
and we also need to add that key at en.js and es.js

I think the translation of "Are you sure" in spanish would be "Estás seguro". Correct me if the translation is wrong.

**Comment by robertjchen** [comment]
Looks good, though I believe the exact translation would have to be "`¿Estás seguro?`". Tagging as `External` for next steps, thanks!

**Comment by adelekennedy** [comment]
[internal](https://www.upwork.com/ab/applicants/1516197562143006720/job-details)
[external](https://www.upwork.com/jobs/~01a3558732f426ee8a)

**Comment by parasharrajat** [comment]
@Puneet-here 's proposal looks good to me. 

cc: @Luke9389 

:ribbon: :eyes: :ribbon:  C+ reviewed

**Comment by Luke9389** [comment]
Cool cool. Go ahead and make the PR @Puneet-here

**Comment by Puneet-here** [comment]
I have raised the PR.
Thanks.

**Comment by parasharrajat** [comment]
@Puneet-here Could you please post the English version here? I think the title should be different from Are you sure?

**Comment by Puneet-here** [comment]
<img width="561" alt="Screenshot 2022-04-22 at 12 26 36 AM" src="https://user-images.githubusercontent.com/101883770/164533615-361e0299-54ba-43dd-a0f1-35176e67e702.png">

**Comment by parasharrajat** [comment]
Ok looks good.

**Comment by adelekennedy** [comment]
Not overdue!

**Comment by adelekennedy** [comment]
It looks like this was just [deployed to production](https://github.com/Expensify/App/pull/8737#issuecomment-1126225290)!

**Comment by adelekennedy** [comment]
And it's time to pay!

**Comment by adelekennedy** [comment]
done and done
