### ISSUE TITLE
[HOLD for payment 2022-05-20][$250] Android/IOS - Link is not aligned vertically in pay bills section on public domain @thesahindia

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#8664]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. launch the app
2. Log in with gmail account
3. Go to any Workspace - Bills

## Expected Result:
Link is aligned vertically in pay bills section on public domain

## Actual Result:
Link is not aligned vertically in pay bills section on public domain

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Android

**Version Number:** 1.1.55.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** any public account

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

![Screenshot_20220416-231156_New Expensify](https://user-images.githubusercontent.com/93399543/163719165-b705988c-eb94-41b9-9090-05cbf92cc46c.jpg)

**Expensify/Expensify Issue URL:** 

**Issue reported by:** @thesahindia

**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1639149882009500

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by thesahindia** [comment]
### Proposal 

https://github.com/Expensify/App/blob/6c53be1ea7a022e8a5e788cc7e7efd62c4573474/src/pages/workspace/bills/WorkspaceBillsFirstSection.js#L57-L59 
Using `Text` instead of `TouchableOpacity` will fix this.
```js
    <Text
      style={[styles.link]}
      onPress={() => Link.openExternalLink('https://community.expensify.com/discussion/7500/how-to-pay-your-company-bills-in-expensify/')}
    >
      example.com@expensify.cash
    </Text>
```

Shouldn't we add a `NewWindow` icon here because it's a hyperlink?

**Comment by thesahindia** [comment]
@sakluger, to repro this you need an account made with public domain email.

**Comment by strepanier03** [comment]
@sakluger -- I was able to repro on Android:

1. Open New Expensify app,
2. Login with a  public domain email (ex: I used strepanier2003@gmail.com)
3. Go to Workspace
4. Pay Bills

![Screenshot_20220419-110845](https://user-images.githubusercontent.com/10925636/164068401-5e615910-650c-4080-843d-2d85467c31cf.png)

**Comment by sakluger** [comment]
Thanks @strepanier03 for verifying! I think this is limited to Android since I couldn't reproduce on iOS. I'll update the original description and pass along to engineering triage.

**Comment by NicMendonca** [comment]
Job posting: https://www.upwork.com/jobs/~011c96071a6ad0431c

**Comment by parasharrajat** [comment]
> Link is aligned vertically in pay bills section on public domain

I think there is supposed to be a copy icon next to the email. Right? @NicMendonca

**Comment by parasharrajat** [comment]
Expected behavior here is:

A copy icon should be shown next to the email and the Link is aligned vertically in the pay bills section on the public domain. 

@kbecciv Could you please update the expected behavior with the above?

@thesahindia Could you post an updated proposal?

**Comment by thesahindia** [comment]
Are you saying that copy icon should be shown next to example.com@expensify.cash?

**Comment by parasharrajat** [comment]
Yes

**Comment by thesahindia** [comment]
I don't understand the reason behind showing the copy icon here because it's a link

**Comment by parasharrajat** [comment]
Sorry, got confused with the email. It should have an external Link icon instead of a copy icon.

**Comment by thesahindia** [comment]
> Do you think it makes sense to show the [external link](https://github.com/Expensify/App/blob/main/assets/images/new-window.svg) icon?

We aren't showing the external link icon for links like this anywhere also it doesn't look great here so I think we can leave that.

**Comment by parasharrajat** [comment]
Can you share the screenshot? I have seen a few places where this icon is used. Let's see what others have to say. cc: @stitesExpensify @NicMendonca

**Comment by thesahindia** [comment]
![Simulator Screen Shot - iPhone 13 - 2022-04-25 at 22 33 16](https://user-images.githubusercontent.com/83179295/165138180-945e01d8-0912-46d9-bca0-e762f86c5f00.png)

![Simulator Screen Shot - iPhone 13 - 2022-04-25 at 22 33 09](https://user-images.githubusercontent.com/83179295/165138195-baef4b69-bdfd-4972-8905-bf1639771418.png)

**Comment by Justicea83** [comment]
## Proposal 
 
 TouchableOpacity doesn't work well in `android` according to this [issue](https://github.com/facebook/react-native/issues/27549).

A work around it is 

1.  Refactor the codes in [components/CopyTextToClipboard.js](https://github.com/Expensify/App/blob/main/src/components/CopyTextToClipboard.js).
 
#### Update the PropTypes

```javascript
const propTypes = {
    /** The text to display and copy to the clipboard */
    text: PropTypes.string.isRequired,

    /** Styles to apply to the text */
    textStyles: PropTypes.arrayOf(PropTypes.object),

    /** The default icon to show */
    icon: PropTypes.func,

    /* Whether to show the text or not */
    showText: PropTypes.bool,

    ...withLocalizePropTypes,
}; 
```

#### Update Default Prop Types

```javascript
const defaultProps = {
    textStyles: [],
    icon: Expensicons.Clipboard,
    showText: true,
};
```

#### Update the render function to this

```javascript
render() {
        return (
            <Text
                onPress={this.copyToClipboard}
                style={[styles.flexRow, styles.cursorPointer]}
            >
                {this.props.showText && <Text style={this.props.textStyles}>{this.props.text}</Text>}
                <Tooltip text={this.props.translate('reportActionContextMenu.copyToClipboard')}>
                    <Icon
                        src={this.state.showCheckmark ? Expensicons.Checkmark : this.props.icon}
                        fill={this.state.showCheckmark ? themeColors.iconSuccessFill : themeColors.icon}
                        width={variables.iconSizeSmall}
                        height={variables.iconSizeSmall}
                        inline
                    />
                </Tooltip>
            </Text>
        );
    }
```

2.Refactor the codes in [workspace/bills/WorkspaceBillsFirstSection.js](https://github.com/Expensify/App/blob/main/src/pages/workspace/bills/WorkspaceBillsFirstSection.js). 

Replace https://github.com/Expensify/App/blob/main/src/pages/workspace/bills/WorkspaceBillsFirstSection.js#L2 with

```javascript
import {View, TouchableOpacity, TouchableNativeFeedback, Platform} from 'react-native';
```

Replace the codes in https://github.com/Expensify/App/blob/main/src/pages/workspace/bills/WorkspaceBillsFirstSection.js#L56-L61 with

```javascript
               {
                                Platform.OS === 'android'
                                    ? (
                                        <TouchableNativeFeedback
                                            onPress={() => Link.openExternalLink('https://community.expensify.com/discussion/7500/how-to-pay-your-company-bills-in-expensify/')}
                                        >
                                            <Text style={[styles.textBlue]}>example.com@expensify.cash</Text>
                                        </TouchableNativeFeedback>
                                    )
                                    : (
                                        <TouchableOpacity
                                            onPress={() => Link.openExternalLink('https://community.expensify.com/discussion/7500/how-to-pay-your-company-bills-in-expensify/')}
                                        >
                                            <Text style={[styles.textBlue]}>example.com@expensify.cash</Text>
                                        </TouchableOpacity>
                                    )
                            }
```

So were are rendering TouchableNativeFeedback if the platform is android otherwise the TouchableOpacity is rendered.


That should work fine, thats the output in android. Everything shows the same in the other platforms.

<img width="353" alt="Screenshot 2022-04-26 at 12 05 42 PM" src="https://user-images.githubusercontent.com/26106822/165298105-3e88bdc1-2c94-46a4-870d-d762d706e391.png">

**Comment by Justicea83** [comment]
Assigning myself since my proposal was accepted

**Comment by thesahindia** [comment]
I think we can go with the approach that I had proposed earlier instead of using two different Touchable

### Proposal 

https://github.com/Expensify/App/blob/6c53be1ea7a022e8a5e788cc7e7efd62c4573474/src/pages/workspace/bills/WorkspaceBillsFirstSection.js#L57-L59 
Using `Text` instead of `TouchableOpacity` will fix this.
```js
    <Text
      style={[styles.link]}
      onPress={() => Link.openExternalLink('https://community.expensify.com/discussion/7500/how-to-pay-your-company-bills-in-expensify/')}
    >
      example.com@expensify.cash
    </Text>
```
What you think @parasharrajat, @stitesExpensify ?

**Comment by parasharrajat** [comment]
Sorry, @thesahindia but this is already being worked on.

**Comment by NicMendonca** [comment]
@parasharrajat @thesahindia I am so sorry, this job post expired before I could issue payment 😞 Can you please accept my offer?

**Comment by thesahindia** [comment]
No prob. Accepted the offer ✅

**Comment by NicMendonca** [comment]
paid - sorry for the delay!
