### ISSUE TITLE
[HOLD for payment 2022-05-23] [$250] Android - When you navigate back using the back arrow the keyboard takes time to close @thesahindia

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#8666]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to settings > Profile
2. Tap on any field so that your keyboard gets open
3. Press back arrow ( top left )

## Expected Result:
Keyboard should close instantly

## Actual Result:
Keyboard takes a while to close

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Android

**Version Number:** 1.1.55.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/163720856-dec5d2c9-b20b-46a4-86ae-8a9d2bfb61e5.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** @thesahindia

**Slack conversation:**  https://expensify.slack.com/archives/C01GTK53T8Q/p1647380047867809

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by PauloGasparSv** [comment]
Set as monthly since it doesn't break the app or affect users too much.
Tested here and this only happens in Android

**Comment by bfitzexpensify** [comment]
Upwork post [here](https://www.upwork.com/jobs/~01231b599617962cff)

**Comment by Domnic95** [comment]
Hello there
I understood the issue you described and recorded a video.

this will work exactly you are looking:

InputMethodManager imm = (InputMethodManager)
                                  getSystemService(Context.INPUT_METHOD_SERVICE);
if(imm != null){
        imm.toggleSoftInput(0, InputMethodManager.HIDE_IMPLICIT_ONLY);
    }

It will hide the keyboard before the user moves to the back screen.

**Comment by phivh** [comment]
## Proposal
Add a condition inside the onPress back arrow button to check if the virtual keyboard is opening then hide it before landing back in previous screen at `HeaderWithCloseButton.js` (src/components/HeaderWithCloseButton.js)

By re-use `isOpen` common function that defined in `virtualKeyboard` (src/libs/virtualKeyboard/index.js).

Note: Perhaps it isn't necessary to check by Platform = Android

```
...
{props.shouldShowBackButton && (
    <Tooltip text={props.translate('common.back')}>
        <TouchableOpacity
            onPress={() => {
                if(virtualKeyboard.isOpen()) {
                    Keyboard.dismiss();
                }
                props.onBackButtonPress();
            }}
            style={[styles.touchableButtonImage]}
        >
            <Icon src={Expensicons.BackArrow} />
        </TouchableOpacity>
    </Tooltip>
)}
...
```

### Demo

https://user-images.githubusercontent.com/5449119/166426040-90c7c357-15e6-45ca-9539-a435c1801f02.mp4

**Comment by MonilBhavsar** [comment]
@phivh @Santhosh-Sellavel Thanks for the proposal and review. Looks good to me 👍
@bfitzexpensify can we please assign @phivh to this job

**Comment by bfitzexpensify** [comment]
Sure! @phivh please apply for the job on Upwork and let me know when you have done so.

**Comment by phivh** [comment]
> Sure! @phivh please apply for the job on Upwork and let me know when you have done so.

@bfitzexpensify applied for Upwork job.

**Comment by Santhosh-Sellavel** [comment]
@bfitzexpensify It's time for payment!

**Comment by bfitzexpensify** [comment]
Hey @phivh and @thesahindia - I tried to pay out your contracts but got a timeout error on Upwork. Can you confirm if you received payment? This happened last week and the payment went through, but would be good to either/both of you to confirm!

**Comment by phivh** [comment]
Hi @bfitzexpensify I still didn't get the payment.

**Comment by bfitzexpensify** [comment]
Thanks for confirming — we're working with our Upwork account manager to get this sorted, as soon as they can let me know what's going on I'll process the payment. Thanks for your understanding!

**Comment by phivh** [comment]
Wait @bfitzexpensify , there are something, let me check again. Hm seems Upwork has issue.

**Comment by bfitzexpensify** [comment]
So does it look like it worked @phivh?

**Comment by phivh** [comment]
@bfitzexpensify it seems double charged. There are two pending transactions

**Comment by bfitzexpensify** [comment]
OK, thanks for letting me know. We're chatting to Upwork support to get this figured out, and I'll let you know here once that's complete.

**Comment by thesahindia** [comment]
@bfitzexpensify, I have received the payment correctly
<img width="764" alt="Screenshot 2022-05-24 at 11 45 43 AM" src="https://user-images.githubusercontent.com/83179295/169961726-5b8151f9-ed5c-48ff-b809-7447fd361b42.png">

**Comment by bfitzexpensify** [comment]
Thanks for letting me know!

**Comment by bfitzexpensify** [comment]
OK, it looks like we've figured out things with Upwork. 

@Santhosh-Sellavel - I've paid one and cancelled the other, please confirm all is correct from your end
@phivh - have you received payout for both? We've been advised by Upwork to request a refund on one, so I'll do that shortly
@thesahindia - you were the lucky one who received payment correctly, so I think you're all good 

Sorry for the mess here! The root issue I had with managing issues seems to have been fixed now.

**Comment by phivh** [comment]
yes @bfitzexpensify both transactions still there.

**Comment by Santhosh-Sellavel** [comment]
I think @phivh you can initiate a refund from the contract.

**Comment by bfitzexpensify** [comment]
I believe I sent a request for a refund of one transaction @phivh - thanks!

**Comment by bfitzexpensify** [comment]
Great, thanks @phivh! OK, finally all squared away here I believe.
