### ISSUE TITLE
[HOLD for payment 2022-05-24] [$250] Offline icon is not fully grey

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#8681]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. open app 
2. Set yourself offline 

## Expected Result:
Offline icon should be fully grey 

## Actual Result:
Offline icon is not fully grey 

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- iOS
- Android

**Version Number:** 1.1.55-0
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 
![2022-04-15_12-05-24](https://user-images.githubusercontent.com/43995119/163872290-eb01fc74-ab73-4a61-815d-ddcbddc8e842.png)

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @marcaaron 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1650061727200429

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Puneet-here** [comment]
### Proposal 
We need to add a new icon and have to replace this one
https://github.com/Expensify/App/blob/8f654504b989bf78f141b72504e48e5993a1ab7f/src/components/Icon/Expensicons.js#L47
We are using the icon here
https://github.com/Expensify/App/blob/8f654504b989bf78f141b72504e48e5993a1ab7f/src/pages/home/report/ReportActionCompose.js#L594

**Comment by mateusbra** [comment]
### PROPOSAL
We need to remove the `fill="black"` property from the SVG file:
https://github.com/Expensify/App/blob/af1054e3ed50bb4ba5237b485db86661768086a8/assets/images/offline.svg?short_path=a4d5391#L3

**Comment by bfitzexpensify** [comment]
Upwork job [here](https://www.upwork.com/jobs/~018d68ea82da64064b)

**Comment by wildanmuhlis2** [comment]
@mvtglobally this issue is not reproducible in [1.1.55-2](https://github.com/Expensify/App/releases/tag/1.1.55-2)
<img width="349" alt="image" src="https://user-images.githubusercontent.com/11847279/164160009-225f5115-0816-4617-a03d-a5badd1c9a24.png">

**Comment by mvtglobally** [comment]
@wildanmuhlis2 Just checked on Android and I can still repro on 1.1.55-2. maybe some platforms are resolved.

**Comment by rushatgabhane** [comment]
🎀 👀 🎀 C+ reviewed

@mateusbra's [proposal](https://github.com/Expensify/App/issues/8681#issuecomment-1103109284) works like a charm.
The issue is repro on iOS and Android.

cc: @tgolen

**Comment by tgolen** [comment]
Shouldn't the color of the icon be set in `style.js`?

**Comment by tgolen** [comment]
OK, I think we can agree that we shouldn't be using `fill="anycolor"` directly in the SVG files, is that right? Ideally, it looks like `<Icon>` has a `fill` property which should be used to color icons.

So, I am in favor of removing the fill from the SVG file. It looks like one other file is doing something similar, which is `workspace-default-avatar.svg`. Can we also fix that one while we're at it?

**Comment by mateusbra** [comment]
>OK, I think we can agree that we shouldn't be using fill="anycolor" directly in the SVG files, is that right?

@tgolen you're right!

I think somehow this svg property overwrite our fill property on native platforms, I think we should remove them.
I'm ok with changing both `offline.svg` and `workspace-default-avatar.svg` with this PR.

**Comment by tgolen** [comment]
Great, thanks! @bfitzexpensify 🟢  to hire @mateusbra for this.

**Comment by Tandin-Moon** [comment]
**Proposal** 

For the icon, since you are using SVG, I purpose to create a create SVG component. So we can easily control the color and edit them at any time. Creating the SVG component lets us pass dynamic color. For example:

**Facebook SVG logo**

const Facebook: FC = (props) => (
    <Svg
        width={32}
        height={32}
        fill='none'
        xmlns='http://www.w3.org/2000/svg'
        xmlnsXlink='http://www.w3.org/1999/xlink'
        {...props}
    >
    <path>.........</path>             
    </Svg>
)


**Another Solution**

SVG colors can be overwritten in their tag. Example: 

<svg class="h-40 w-40 primary-color fill-current mr-6"></svg>

**CSS**
.primary-color {
  color: red;
}

.fill-current {
 fill: currentColor;
}

The two methods mentioned above can solve your problem.

**Comment by tgolen** [comment]
Thanks @Tandin-Moon we already have an `<Icon>` component which is similar to what you are proposing.

**Comment by Tandin-Moon** [comment]
@tgolen If that's the case, are you using react native vector icons or is it just SVG? If its vector icons:

<Icon as={FontAwesome5} name='eye'  _dark={{ color: '#D3D3D3' }   />

or 

if it is SVG, in html file

<SVG fill="D3D3D3"> </svg>

**Comment by rushatgabhane** [comment]
@Tandin-Moon thankss but @mateusbra was already hired for this issue, and the PR has been approved.
I'd suggest that you take a look at other open issues with the `Help wanted` label.

Again, thanks for your time!

**Comment by bfitzexpensify** [comment]
All payments finalised and contracts ended on Upwork. Thanks for the work here!
