### ISSUE TITLE
IOS - Profile - Time zone is automatically selected without clicking on it.

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#8687]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch the app
2. Log in with any account
3. Click Profile
4. Unselect Set my timezone automatically
5. Open the Time zone box and start search for your zone
6.  Stop on one of it

## Expected Result:
Time zone must be selected when click on it 

## Actual Result:
Time zone is automatically selected without clicking on it.

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- iOS

**Version Number:** 1.1.55.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/164028146-cb904063-f4e7-46db-8bb0-615b9de40daf.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by pecanoro** [comment]
@kbecciv You mean that the time zone is stored by just scrolling down or up in the options?

**Comment by kbecciv** [comment]
@pecanoro The time zone is selected automatically when you just stop scrolling. In production app - in order to get it selected you need to tap on it.

**Comment by luacmartins** [comment]
This issue was first reported [here](https://github.com/Expensify/App/issues/8570). Was it not solved in [this PR](https://github.com/Expensify/App/pull/8596)?

**Comment by kbecciv** [comment]
@luacmartins This is slightly different issue https://github.com/Expensify/App/issues/8570 than we just reported.

**Comment by luacmartins** [comment]
Ah I see, this is for manual timezone selection. Yea, seems like a different issue then.

**Comment by pecanoro** [comment]
Maybe the same PR caused it? https://github.com/Expensify/App/pull/7807 I will try to debug it

**Comment by pecanoro** [comment]
Hmm, I actually think it might have been @chiragsalian's [PR](https://github.com/Expensify/App/pull/8596) since the rest of the selectors are working fine. I am going to test it without that PR.

**Comment by pecanoro** [comment]
Yes, it was Chirag's PR, when he added the value, it stopped working. @chiragsalian Why do we need to add the key there? I can't find where it is used as a prop.

**Comment by pecanoro** [comment]
That temporary fix for that deploy blocker created this one 😄  Why do we need that `key` parameter and why can't we use something else? Not sure where it is used

**Comment by chiragsalian** [comment]
Yup like carlosM mentioned. It was a temporary fix that was suggested by the author here - https://github.com/Expensify/App/pull/7807#issuecomment-1093528141 until a more permanent fix could be found. Definitely annoying it created another deploy blocker. Shall post in the PR and investigate too.

**Comment by pecanoro** [comment]
I can help you with it, it's just that I am not completely sure how adding the key to the picker broke it since I can't seem to find where that key is being used

**Comment by pecanoro** [comment]
Maybe the problem is not passing the key down to the BasePicker along with the value?

**Comment by chiragsalian** [comment]
@kbecciv, the fix for this has been cherry picked. Its on version `1.1.55-2`. 
Can you re-test @kbecciv and if the issue does not reoccur can you close this issue and check it off the checklist? 🙂
