### ISSUE TITLE
[HOLD] - (Wait for API refactor as it will affect this) Workspace Room is not refreshed when member is removed from Workspace

### ISSUE THREAD

**Issue by yuwenmemon** [Expensify/App#8710]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Create a workspace with user 1
2. Go to the `Manage members` tab of the workspace, invite user 2
3. Login to user 2 via incognito window, verify that there is a `[Company Name]'s Workspace` chat room shown in LHN
5. Navigate back to user 1 session, remove user 2 from the policy
6. Navigate back to user 2 session

## Expected Result:
User 2 should see the workspace room as archived now that they are no longer a member of the workspace.

## Actual Result:
The UI shows that User 2 can still send messages in the workspace room and that it is active, even though User 2 has no such access. User 2 needs to refresh the page before they see that the room is archived.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platform:
- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**Notes/Photos/Videos:**
https://user-images.githubusercontent.com/4741899/164336918-76689a49-f498-4b93-a670-12604e6f704d.mp4

**Coming from:** https://github.com/Expensify/App/pull/8437#issuecomment-1103958227

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by yuwenmemon** [comment]
cc @TomatoToaster

**Comment by yuwenmemon** [comment]
For whoever picks this up: The issue behind this is described [here](https://github.com/Expensify/App/pull/8437#issuecomment-1102013321). We try fetching _all_ workspace chats [here](https://github.com/Expensify/Web-Expensify/blob/9f59c7a6da074119e97e2178c062437c1d49467f/lib/PolicyAPI.php#L827) - which is optimized for the admin case. For a policy _member_, we'll just get a 404 response from [GetReportSummaryList](https://github.com/Expensify/App/blob/efe4f0c7f1aa36d06d373905371704380003140c/src/libs/actions/Report.js#L357) since they would not have access to all workspace chats.

**Comment by mallenexpensify** [comment]
Went down a triage 🐰🕳 trying to lean more about workspaces to provide context to a contributor (if they end up working on this). [This Community link ](https://community.expensify.com/search?query=new.expensify.com%20workspace&scope=site&source=community)will help get more details on workspaces

Also... @yuwenmemon I _feel_ like we've had a similar issue in the past where users haven't been fully signed out when they should have. For now, let's assume they're not related, just bringing up in case we run across similar issues

**Comment by sketchydroide** [comment]
I think I'll pick this one myself, if anyone thinks this sould be an external instead I'm happy with that as well.
Seems like a weekly, so I'm changing to that

**Comment by sketchydroide** [comment]
Will work on it this week

**Comment by mallenexpensify** [comment]
You still wanting to work on this @sketchydroide ?

**Comment by sketchydroide** [comment]
Yes, will work on it over the next couple of days

**Comment by sketchydroide** [comment]
Working on this today

It feels there should be some sort of notification that updates the state, otherwise I see no way of user2 being aware of this change until it refreshes.

**Comment by sketchydroide** [comment]
Seems like we send a push to the Policy Channel [here](https://github.com/Expensify/Web-Expensify/blob/642165302951fe18eae79788be6e5a4320cb012f/lib/PolicyAPI.php#L651) but I'm not sure if the user is listening

**Comment by sketchydroide** [comment]
on the App this is subscribed [here](https://github.com/Expensify/App/blob/64257486d966504cf4c60319b0e5ef238a855646/src/libs/actions/Policy.js#L519)

**Comment by sketchydroide** [comment]
this is just a guess at this point, but I would say that when user2 is added to policy it does not subscribe to the event pushes on the new policy

**Comment by sketchydroide** [comment]
Ok I got my dev environment working again for the app, I can start making some tests

**Comment by sketchydroide** [comment]
So I was partially right, the `subscribeToPolicyEvent` was not being trigered on UserB when UserA removed it from the workspace.
After fixing that, it still doesn't completly works, so I'm going to try and understand why

**Comment by mallenexpensify** [comment]
@sketchydroide is working on

**Comment by sketchydroide** [comment]
I have made some more work on this, and came to a new issue.
When [fetching](https://github.com/Expensify/App/blob/65f20e83d074927e3cb85e56928a9f18d6e556b8/src/libs/actions/Report.js#L356) the Chats/Reports after the user is deleted, the call returns a 404.
This seems to be because the user has no longer access to this report. [This returns false](https://github.com/Expensify/Auth/blob/5388fba2be6a80cfcf93fe1e51ac9aad379dd51c/auth/lib/Report.cpp#L739)

**Comment by sketchydroide** [comment]
I think we might need to wait for the API refactor for this to be looked at, or make this part of that work.
At the moment I might be doing work that is going to be redone by API refactor

**Comment by mallenexpensify** [comment]
I _think_ @sketchydroide is working on. also... onshore..

**Comment by sketchydroide** [comment]
I think we should put this on HOLD for now, the new API refactor will probably affect this, and fixing it would be a duplication of labor.

**Comment by sketchydroide** [comment]
downgrading to montly for now, as I don't think we need a weekly update atm

**Comment by sketchydroide** [comment]
still same status

**Comment by sketchydroide** [comment]
still same status

**Comment by sketchydroide** [comment]
I think most of the refactor is done, we can see again if it makes sense to do this now.

**Comment by mallenexpensify** [comment]
@sketchydroide 
1. Do you _want_ to work on this? 
2. If not, do you think it can be `External`?
3. If it's external, think we should create a new, clean issue before labeling?

**Comment by mallenexpensify** [comment]
oh wow.. this issue was hiding in the abyss. 

1. @sketchydroide 
2. Do you want to work on this?
3. If not, do you think it can be External?
4. If it's external, think we should create a new, clean issue before labeling?

**Comment by mallenexpensify** [comment]
@MitchExpensify Reassigning as I'm heading OOO for a month

**Comment by sketchydroide** [comment]
sorry, was OOO, the last few days, let me look at it today, and see if it's worth it make it an external or not.

**Comment by sketchydroide** [comment]
I think we should mantain this as internal for now, I need to go investigate the entire process again, as things have changed quite a lot since this was created, but my feeling for now it that if this has not been fixed in the mean time, it will probably be some sort of API refactor.
The way 1:1:1 work should send a push to all parties envolved, and do the Onyx update.
Because I think this will probably be a fix/change related to doing something on the Onyx side, I would prefer to keep it internal. There also might be some Web work involved.

**Comment by sketchydroide** [comment]
continue working on it this week

**Comment by sketchydroide** [comment]
Not much has been done the Refactor took priority this week, also my kids have both been sick so I had less time than usual, I'll give this my top priority next week

**Comment by MitchExpensify** [comment]
Seeing as this is being handled internally I'm going to unassign myself

**Comment by sketchydroide** [comment]
no updates, this week has been a bit of a bust with only working half a day with being sick

**Comment by sketchydroide** [comment]
ok just tried testing this again, and it seems to be working as it's supposed to, so I'm closing this
