### ISSUE TITLE
[HOLD][$250] At some places we are using error/success messages that aren't localized - reported by @thesahindia

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#8714]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Set language to spanish 
2. Add phone number which already belongs to existing account 

## Expected Result:
error should be translated to spanish 

## Actual Result:
error is in English 

Code links of some other places :-
https://github.com/Expensify/App/blob/564ec88b345a6da1478bab5e5060054a8cb5ad74/src/libs/actions/User.js#L56
https://github.com/Expensify/App/blob/564ec88b345a6da1478bab5e5060054a8cb5ad74/src/libs/actions/User.js#L222-L226
https://github.com/Expensify/App/blob/564ec88b345a6da1478bab5e5060054a8cb5ad74/src/libs/actions/User.js#L187-L190

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.56-0
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 
<img width="899" alt="Screenshot 2022-03-30 at 5 48 21 PM" src="https://user-images.githubusercontent.com/43995119/164365224-39c43958-3b46-4a5e-af61-12f0673192e7.png">
<img width="375" alt="Screenshot 2022-03-30 at 5 40 25 PM" src="https://user-images.githubusercontent.com/43995119/164365225-130ac4dd-554a-4bcf-b53b-767df139a51d.png">
![Screen Shot 2022-04-20 at 11 21 24 PM](https://user-images.githubusercontent.com/43995119/164365470-5d5a3fdc-789b-4958-b83c-b40c0c4b6b19.png)

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @thesahindia
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1648644871987449

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by conorpendergrast** [comment]
Good catch1

**Comment by chiragsalian** [comment]
Should be easy enough for anyone to address. To the person working on this can you check the codebase for any instances where localizations are not used then share us the english text so that we can provide the spanish text.

**Comment by bfitzexpensify** [comment]
Thanks @chiragsalian! 

Upwork job [here](https://www.upwork.com/jobs/~01b60da6dd6b3a2fbd) - @thesahindia, please apply there for reporting bonus too.

**Comment by tgolen** [comment]
I think we should HOLD on doing anything here until we have a better strategy for error handling. This came up in the discussions about Offline First and I talked quite a bit about it with @quinthar and @iwiznia. 

As we move into refactoring the API for NewDot optimization, the idea would be that the server ONLY responds with numeric error codes (I know there is still some debate on this). Then the error code will get put into Onyx. The UI layer (views) will then be responsible for properly displaying translated text for error codes.

**Comment by iwiznia** [comment]
Closing this per [this comment](https://expensify.slack.com/archives/C01GTK53T8Q/p1650963741424669?thread_ts=1650386332.857569&cid=C01GTK53T8Q). Feel free to comment there or reopen if you disagree.
