### ISSUE TITLE
[HOLD for payment 2022-06-13] [$250] Update the IOU "Cancel" button so that it has a fixed size - reported by @Puneet-here

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#8715]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
 1. Request money from someone
 2. Cancel the money request the button size will increase when loading

## Expected Result:
Update the logic of the Cancel button so that it doesn't re-size at all.

## Actual Result:
After being clicked, the IOU Cancel button size increases momentarily and then disappears. That's strange visually.

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.56-0
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 

https://user-images.githubusercontent.com/43995119/164365759-60d38bf6-831c-4eb4-ad9f-31edea281943.mp4

**Upwork job link:** https://www.upwork.com/jobs/~019f02e58e1d9ac630
**Issue reported by:** @Puneet-here
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1648666290760469

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by thesahindia** [comment]
### Proposal 
We can just set a minWidth for this button.
`minWidth: 61` will be good for cancel/decline button and `minWidth: 69` for spanish ones. We can add a function in `StyleUtils` which will return minWidth based on the `preferredLocale`.

Or instead of this we can just set the minWidth to larger one (that's what we did for the resend link button https://github.com/Expensify/App/pull/6958) 
We can add the style like this -
https://github.com/Expensify/App/blob/65432d60dd0be71e8830099c93b3ab0f25da0139/src/styles/styles.js#L937-L939

We will have to use the style here and we can remove line 96-
https://github.com/Expensify/App/blob/65432d60dd0be71e8830099c93b3ab0f25da0139/src/components/ReportTransaction.js#L92-L97

**Comment by michaelhaxhiu** [comment]
@Santhosh-Sellavel nice to see you get auto-assigned 😄 (lol, yesterday we almost convinced ourselves that the "random" assignment wasn't random!)

**Comment by Santhosh-Sellavel** [comment]
@roryabraham

Based on the code here, this is working as expected only.
https://github.com/Expensify/App/blob/65432d60dd0be71e8830099c93b3ab0f25da0139/src/components/ReportTransaction.js#L96

Can you confirm what's expected here?

**Comment by roryabraham** [comment]
I'm not sure – it does seem weird that the button gets wider when you tap on it, but my instinct is that this is fine / not worth fixing. Going to tag in design to either:

1. Define the expected behavior, OR
1. Close this issue if the current behavior is fine.

**Comment by michelle-thompson** [comment]
I would prefer that the button stays the same size, so let's move forward with setting a minimum width here.

**Comment by michaelhaxhiu** [comment]
This issue sorta reminds me of https://github.com/Expensify/App/issues/8590 but it's not _as bad_ visually. I agree with @michelle-thompson on proceeding - let's get the consistent behavior nailed down!

**Comment by michaelhaxhiu** [comment]
Updating the GH title and body a little, to make it clear that we are updating the expected behavior!

**Comment by thesahindia** [comment]
> We'll just trial-and-error that minWidth, unless @michelle-thompson can provide one? It needs to be wide enough for `Cancelar`

`minWidth: 69` will do the work I have tested that.

**Comment by michaelhaxhiu** [comment]
@thesahindia feel free to apply for the upwork job, btw

@Santhosh-Sellavel lmk if you agree with the gameplan!

**Comment by michelle-thompson** [comment]
Let's go with @thesahindia suggestion 👍

**Comment by thesahindia** [comment]
<img width="374" alt="Screenshot 2022-05-04 at 11 20 58 PM" src="https://user-images.githubusercontent.com/83179295/166748955-1433e9f4-8c36-4ce2-9935-7e82417efbf5.png">
<img width="374" alt="Screenshot 2022-05-04 at 11 20 28 PM" src="https://user-images.githubusercontent.com/83179295/166748986-bb1f9642-4de5-4904-b778-e3f8fb3e3f44.png">
<img width="374" alt="Screenshot 2022-05-04 at 11 20 05 PM" src="https://user-images.githubusercontent.com/83179295/166748994-11fc8c12-900e-4850-b3ce-edb4a32ff3fd.png">
<img width="374" alt="Screenshot 2022-05-04 at 11 18 38 PM" src="https://user-images.githubusercontent.com/83179295/166749001-1ad4c1e5-39d1-4dd9-8b57-e605f56ee060.png">

**Comment by thesahindia** [comment]
> @thesahindia feel free to apply for the upwork job, btw

Applied ✅

**Comment by Santhosh-Sellavel** [comment]
Thanks @thesahindia can you add loading also?

**Comment by thesahindia** [comment]
https://user-images.githubusercontent.com/83179295/166753752-bd5ddae6-1664-4254-8dc9-7d90596cee41.mov

**Comment by Santhosh-Sellavel** [comment]
Thank you @thesahindia!

**Comment by Santhosh-Sellavel** [comment]
@michelle-thompson @roryabraham 

We have a clear idea of how it looks in https://github.com/Expensify/App/issues/8715#issuecomment-1117637701 and https://github.com/Expensify/App/issues/8715#issuecomment-1117643908 comments.

I kind of feel there is some little extra padding in the `en` version of the button, if the button's of full width then we won't notice much but in this case, there's a little extra space! I'm afraid this could come up as a separate issue.

Are we all good with this?

cc: @michaelhaxhiu

**Comment by michelle-thompson** [comment]
That looks good to me!

**Comment by Santhosh-Sellavel** [comment]
@michaelhaxhiu let's assign it to @thesahindia!

**Comment by michaelhaxhiu** [comment]
Hired, let's get this party started.

**Comment by roryabraham** [comment]
Waiting for consensus in [slack](https://expensify.slack.com/archives/C01GTK53T8Q/p1651695607990559) to move forward.

**Comment by michaelhaxhiu** [comment]
Thanks for linking that @roryabraham, I was just about to do the same :D

**Comment by thesahindia** [comment]
Was just experimenting some things to find the best approach for this. I will just update the PR as we already have a better way to fix this.

**Comment by thesahindia** [comment]
Update the PR 
cc: @Santhosh-Sellavel

**Comment by michaelhaxhiu** [comment]
Seems the PR is seeing gradual progress. It needs some conflicts to be resolved and then can be reviewed.

**Comment by Santhosh-Sellavel** [comment]
PR got merged today, it's already on staging.

I'm going OOO, If there are any new breakages/regression while I am away, feel free to un-assign me and add a new C+ here thanks!

cc: @roryabraham

**Comment by michaelhaxhiu** [comment]
@Santhosh-Sellavel want to apply for the job before you go OOO? https://www.upwork.com/jobs/~019f02e58e1d9ac630

**Comment by michaelhaxhiu** [comment]
All are paid. Closing. Thanks for your assistance!
