### ISSUE TITLE
[$250] Frequently used emojis shown even when user didnt select this emoji before - reported by @Puneet-here

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#8716]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
 1. Login to new account
 2. Open emoji picker
 3. Select an emoji it will show up in frequently used section

## Expected Result:
It should only show up as frequently used when you have used that emoji multiple times or we should change the it to Recently used.

## Actual Result:
It shows up after selecting an emoji only one time

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.56-0
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 

https://user-images.githubusercontent.com/43995119/164366069-169c879a-d019-45b9-a9e7-1612fac0d528.mp4

**Upwork URL:** https://www.upwork.com/jobs/~01f2ba2b8e27f04695
**Issue reported by:** @Puneet-here
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1648671339728759

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by stitesExpensify** [comment]
@Puneet-here I'm a little confused on why you feel this is a bug. 

The way that frequently used emojis works is we keep a count each time you use one (smile: 1, laugh: 5 etc). Once you have 16 frequently used emojis, we only show the top 16 from that list. If you are someone who doesn't use emojis often, then only the ones you have used will be there, even if they have only been used once. In my opinion, that is the correct behavior.

Am I missing something?

**Comment by Puneet-here** [comment]
Hi @stitesExpensify, I think frequently used emoji means the emojis that we use frequently and other platform list like slack only lists an emoji in frequently used category when it gets used sometimes but in Expensify we are listing emojis that the user has selected even for once and even if they don't send that emoji it will be in frequently used, which isn't correct I think because of this when the 16 frequently used emoji gets listed some of them will be replaced just because of selecting a new emoji once even you don't use it. I think if we wanna keep the functionality like this we should change the title to `recently used` as they work like recently used emoji and in mobile native emoji picker they also use the term recently used and they list recently used emojis.

Sorry for the lengthy comment.

**Comment by stitesExpensify** [comment]
No worries about the comment length! 

> in Expensify we are listing emojis that the user has selected even for once

If you have used an emoji once and that's more than any other emoji, then it would be more frequently used than the others though, right? 

> I think because of this when the 16 frequently used emoji gets listed some of them will be replaced just because of selecting a new emoji once even if you don't use it

That will only happen if the emoji has been selected more than the 16 that are currently being shown though right? 

>  I think if we wanna keep the functionality like this we should change the title to recently used

I don't think `recently used` is really what's happening though right? It is actually the 16 emojis you have selected the most times

**Comment by Puneet-here** [comment]
I just checked we list 24 emoji in that section 

>That will only happen if the emoji has been selected more than the 16 that are currently being shown though right?
>I don't think recently used is really what's happening though right? It is actually the 16 emojis you have selected the most times

No I checked it's not the case they are getting replaced by any new emoji

**Comment by stitesExpensify** [comment]
Oh wow, that's definitely a bug then thanks for checking! I still think that emojis only used once should be in the frequently used, if they are in the top 24 on the list. Do you want to propose a solution?

**Comment by Puneet-here** [comment]
I don't have a proposal for this also currently I am trying to find solution for some other issues so I won't be able to work on it.

**Comment by stitesExpensify** [comment]
Sounds good, I'll open it up to others then (and you will get the reporting fee)!

**Comment by trjExpensify** [comment]
Upwork job here: https://www.upwork.com/jobs/~01f2ba2b8e27f04695

**Comment by mananjadhav** [comment]
@stitesExpensify @Puneet-here When I worked on this, I added support for both - frequently uses as well as recently used. This also might sound a bit confusing but recent emojis takes precedence over some frequently used. 

https://github.com/Expensify/App/issues/4559#issuecomment-910726330

**Comment by stitesExpensify** [comment]
Thanks for reminding me @mananjadhav I totally forgot about that! TBH I like that design a lot so I think this should just be closed. Thanks for creating the upwork job @trjExpensify! My bad for not remembering

**Comment by trjExpensify** [comment]
Cool, I've pulled the job down from Upwork.
