### ISSUE TITLE
Can't zoom in/out a gif  - reported by @thesahindia

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#8717]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to actions > Add attachment > select a gif
2. Click to zoom in/out see if it works and send the gif
3. Now open the gif that you just sent try to zoom again
4. Repeat the same steps again if can't repro.

## Expected Result:
User should be able to zoom in/out.

## Actual Result:
Zoom in/out not working

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Web
- Desktop App

**Version Number:** 1.1.55-0
**Reproducible in staging?:** Y (inconsistent)
**Reproducible in production?:** Y (inconsistent)
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 

https://user-images.githubusercontent.com/43995119/164371102-8cb72185-af9c-4337-923f-0aaf5d09408c.mp4

**Expensify/Expensify Issue URL:**  
**Issue reported by:** @thesahindia
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1648721923711489

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by stephanieelliott** [comment]
Tried 10x to repro this, and each time the gif zoomed in as expected. I believe this is happening sporadically, but given that it seems to be very infrequent and is pretty low impact I am going to close this for now.
