### ISSUE TITLE
Feature Request: When a user has changed their password, then they should be logged out from all the places where they are logged in - reported by @thesahindia 

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#8721]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
## Problem: 
When user is changing password, user is not logged out on other platforms. 
Scenarios where it might help: 1. If a user lost his device where he is logged in.
                                                    2. If someone has logged into your account somehow then even after changing your password they can still use your account
                                                    
## Solution: 
When changing password we can show an option for logging out from all the devices

## Action Performed:
1. Login on 2 different devices to same account 
2. On the one account go to settings>security>change password
3. Change password 
4. on Device 2 navigate to the app to use it 

## Expected Result:
User should not be able to continue using the app on second device 

## Actual Result:
User is able to use the app 

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.56-0
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 
**Expensify/Expensify Issue URL:** 
**Issue reported by:** @thesahindia
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1649183214788119

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by flodnv** [comment]
Weird. This is a bug because that's how it should work: https://github.com/Expensify/Auth/blob/84323b362aaaa034efc7162940b0bd1ee316b60a/auth/command/ChangePassword.cpp#L64

**Comment by Justicea83** [comment]
should the user be logged out of the device used to change the password as well?

**Comment by flodnv** [comment]
Good question. I don't think so?

**Comment by mallenexpensify** [comment]
> should the user be logged out of the device used to change the password as well?

Is there a best practice for this?  Maybe ask in #expensify-open-source, #engineering-chat or #infra?

**Comment by iwiznia** [comment]
> should the user be logged out of the device used to change the password as well?

Definitely not. That is the only device that should remain logged in, as it is the only one that has the new password.

**Comment by iwiznia** [comment]
My proposed solution is that when you change your password:
- The API call from newDot should be done with MakeRequestWithSideEffects
- We would delete all newDot (?) logins
- Create a new login with random password
- Return the login and an authToken for that login in the https response
- Have newDot set it where they belong in onyx

**Comment by iwiznia** [comment]
Oh lol I now realize there is a PR 🤦 
Seems it is similar to what I suggest, but not adapted for the 1:1:1 philosophy... but we can do that later when we migrate all things.

**Comment by flodnv** [comment]
I think this is done?

**Comment by stephanieelliott** [comment]
Hey @thesahindia, I invited you to this job on Upwork. Please accept it when you get a chance so that we can pay you out for reporting this issue! 

Upwork job: https://www.upwork.com/jobs/~016afb2bde8e6f3371

**Comment by thesahindia** [comment]
> Hey @thesahindia, I invited you to this job on Upwork. Please accept it when you get a chance so that we can pay you out for reporting this issue!

Applied ✅ 
Thanks.

**Comment by stephanieelliott** [comment]
All paid up, thanks!
