### ISSUE TITLE
Amount splits two times if I keep pressing Split button - reported by @adeel0202

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#8722]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open any group chat
2. Tap on + icon
3. Select Split bill
4. Enter any amount
5. Keep pressing Split button

## Expected Result:
Amount should be split only one time

## Actual Result:
Amount splits two times

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.56-0
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 

https://user-images.githubusercontent.com/43995119/164376141-24057e6d-23ff-4eab-aa98-9de2f858603f.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @adeel0202
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1649191240676269

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by NicMendonca** [comment]
job posting: https://www.upwork.com/jobs/~01ef047ee2d4003a0d

**Comment by marcaaron** [comment]
**thought:** If this is upgraded to use the `Form` component then we won't have to specifically handle this "double submit" issue as it would be prevented by default. @luacmartins I guess we are not yet 100% ready to do that though?

**Comment by luacmartins** [comment]
Yea, we are not there yet.

**Comment by mollfpr** [comment]
### Proposal

#### **Why**
The variable that is responsible to disable the button is not having value from `iou.loading` so it's should be disabled when `iou.loading` true.
https://github.com/Expensify/App/blob/32d8f0261b825cb6e47e441b9cf08400340a164e/src/components/IOUConfirmationList.js#L352
https://github.com/Expensify/App/blob/32d8f0261b825cb6e47e441b9cf08400340a164e/src/components/IOUConfirmationList.js#L388-L389

#### **How**
Adding `iou.loading` to `shouldDisableButton` variable. The button will disabled when iou start loading.
```diff
-        const shouldDisableButton = selectedParticipants.length === 0 || this.props.network.isOffline;
+        const shouldDisableButton = selectedParticipants.length === 0 || this.props.iou.loading || this.props.network.isOffline;
```


https://user-images.githubusercontent.com/25520267/164612387-ea74b237-b566-4f68-b7cc-985f3a1663ac.mov

**Comment by Santhosh-Sellavel** [comment]
@mollfpr The change would affect button style, I think this is not the expected solution.

cc: @luacmartins

**Comment by Santhosh-Sellavel** [comment]
## Proposal
@luacmartins 
I think adding this check at the beginning of `onPress` method [here](https://github.com/Expensify/App/blob/32d8f0261b825cb6e47e441b9cf08400340a164e/src/components/IOUConfirmationList.js#L153-L161) is the simple way to address this issue now.

```js
if (this.props.iou.isLoading) {
    return;
}
```

What do you say?

**Comment by mollfpr** [comment]
> @mollfpr The change would affect button style, I think this is not the expected solution.
> 
> @luacmartins can you confirm?

I thinks it’s common to disable style with loader on progress buttons.
![4B638DF4-B51D-4957-B161-020AD0DA8697](https://user-images.githubusercontent.com/25520267/164946176-3a571166-9744-4010-85c5-7c214211836b.jpeg)

**Comment by Santhosh-Sellavel** [comment]
@marcaaron If were are okay with disabled style then the @mollfpr proposal looks good to me.

But before moving should loop in design & check with them.

**Comment by luacmartins** [comment]
>I thinks it’s common to disable style with loader on progress buttons.

@mollfpr you can check the expected Submit button style by running `npm run storybook` and seeing it in the Form story. The current behavior is:

1. Replace button text with loading indicator
2. Disable button from being clicked
3. Do NOT use disabled style

https://user-images.githubusercontent.com/22219519/165124129-21f9d1fc-1dfe-4de7-8d00-8d76fbb8b1d0.mov

**Comment by Santhosh-Sellavel** [comment]
@marcaaron 
I have submitted a proposal here!

**Comment by marcaaron** [comment]
Sorry, I think it's better to just keep this on HOLD until we are ready to implement the form component. We already have a solution for this so it doesn't make sense to patch it now.

**Comment by marcaaron** [comment]
@luacmartins can we add this to some kind of milestone to follow up with after the forms project is done?

**Comment by marcaaron** [comment]
This is not really an urgent issue so I think ultimately it's better to do the work once instead of twice.

**Comment by luacmartins** [comment]
Sounds good! I'll add this to the list of forms that need to be refactored! Thanks!

**Comment by marcaaron** [comment]
Going ooo for a week so I'm dropping the priority here as we agreed to absorb this one into the forms project. cc @luacmartins assigned you temporarily - I can take over again when I return.

**Comment by NicMendonca** [comment]
@Santhosh-Sellavel @luacmartins just confirming if this is still on hold?

**Comment by luacmartins** [comment]
Same as above!

**Comment by luacmartins** [comment]
On hold

**Comment by luacmartins** [comment]
Still on hold

**Comment by NicMendonca** [comment]
@luacmartins still on hold?

**Comment by luacmartins** [comment]
Yes!

**Comment by luacmartins** [comment]
Still on hold

**Comment by luacmartins** [comment]
This will actually be solved by https://github.com/Expensify/App/issues/8722 since we are optimistically creating the IOU and there's no more loading state.

**Comment by luacmartins** [comment]
@NicMendonca this issue is solved via https://github.com/Expensify/App/pull/11720. Do we need to pay any contributors? If not, we are good to close.

**Comment by NicMendonca** [comment]
sorry for the delay @adeel0202! Can you please accept the[ job offer](https://www.upwork.com/jobs/~011a103cd16a338388) I sent over?

**Comment by NicMendonca** [comment]
@adeel0202 I've issued payment! Thanks again for the bump.
