### ISSUE TITLE
IOS/Android - The message about successful avatar change is duplicated

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#8729]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue was found when execute the PR:** https://github.com/Expensify/App/pull/8499

## Action Performed:

1. Go to https://staging.new.expensify.com/
2. Login with any account
3. Go to Workspace setting
4. Tap on Workspace - General Setting
5. Tap on Default picture icon
6. Tap Upload Photo - Choose from gallery
7. Tap Save

## Expected Result:
Message about successful change should displayed ones

## Actual Result:
The message about successful avatar change is duplicated

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- iOS
- Android

**Version Number:** 1.1.56.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/164483866-c7e3d7fc-d09b-43e2-82c0-d5846dd07768.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by johnmlee101** [comment]
Quick check maybe seems like https://github.com/Expensify/App/pull/8499 is related? cc @marcochavezf

**Comment by johnmlee101** [comment]
@chiragsalian did a great dive and we don't think it should be a blocker, however I think we should fix this flow to not allow clicking Save while an image is uploading to avoid a double notification

**Comment by marcochavezf** [comment]
Yeap, this is a different bug, but also I think the success message will be removed when the Offline UX Patterns will be implemented; I believe this is going to be an optimistic action without feedback, is this assumption correct @marcaaron @tgolen?

**Comment by marcaaron** [comment]
>the success message will be removed when the Offline UX Patterns will be implemented; I believe this is going to be an optimistic action without feedback, is this assumption correct @marcaaron @tgolen?

Sounds correct to me. I don't think "success growl" will be a common pattern in general - things like this should just work.

**Comment by johnmlee101** [comment]
Good to :donothing: in the meantime then?

**Comment by marcochavezf** [comment]
> Good to :donothing: in the meantime then? 

Yup, I think this issue can be closed
