### ISSUE TITLE
Android - Connect Bank Account - Seeing continue with setup screen for a brief moment when connecting manually - reported by @thesahindia

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#8745]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch the app
2. Go to workspace > connect bank account
3. Click connect manually and press native back button of your mobile
OR
4. Go to workspace > connect bank account
5. Navigate back using back arrow or native back button of your mobile

## Expected Result:
You should see the connect bank account page

## Actual Result:
Seeing continue with setup screen for a brief moment when connecting manually

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Android

**Version Number:** 1.1.56.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** n/a

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/164580755-c4c1635d-2d18-41a0-9b30-62e5ddc05318.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** @thesahindia

**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1649070836326089

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by thesahindia** [comment]
We can close this as we already have the same issue logged here https://github.com/Expensify/App/issues/8541
