### ISSUE TITLE
"No chat found" error when signing up from a workspace invite

### ISSUE THREAD

**Issue by neil-marcellini** [Expensify/App#8748]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Sign in to your test account on NewDot
2. Create a workspace if needed, then go to Settings > Workspace > Manage
Members and invite a brand new user on the new domain, ex.
neil+invite@expensifail.com.
3. Sign out
4. Sign up as the new user
5. Click the link sent to your email and set a password 

## Expected Result:
You will be logged in and navigated to the workspace chat.

## Actual Result:
You are logged in and a growl error appears saying "The chat you are looking for cannot be found", and you are not navigated to the workspace chat.

## Workaround:
On prod you can't see the workspace chat, on staging simply click on the workspace chat.

Note: The error likely has to do with the welcome action and [navigating to the chat here](https://github.com/Expensify/App/blob/2038776a7ba86639906c4033f22de8b48d75fb1e/src/libs/actions/WelcomeActions.js#L64) before it has been fetched.

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** v1.1.55-2
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
[Download screen recording](https://user-images.githubusercontent.com/26260477/164754973-9c49a876-ee3b-4fe5-b5f7-65dfc8422c61.mov)

https://user-images.githubusercontent.com/26260477/164754973-9c49a876-ee3b-4fe5-b5f7-65dfc8422c61.mov

**Expensify/Expensify Issue URL:** 
**Issue reported by:** Neil Marcellini
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by chiragsalian** [comment]
Shall investigate today.

**Comment by neil-marcellini** [comment]
>I feel like the issue is very low ROI because if you test signing on in a new incognito tab you won't get this issue and most of our customers usually have a session just for themselves and not to switch between accounts.

@chiragsalian That's true, good point. I should explain that originally discovered this issue while testing transitions from OldDot to NewDot. If a user is already signed in to a different account than the one that they are transitioning with, the old user is signed out and the new user is signed in, and this issue occurs if the transition involves creating a workspace. It's not a big deal but it would be good to fix, especially with transitions.

**Comment by chiragsalian** [comment]
>  I should explain that originally discovered this issue while testing transitions from OldDot to NewDot. 

Yup definitely a good find and always good to report issues because even if we close this today some day maybe its ROI will increase and we can reopen the issue and it will have some historical context to help.

For context why i say low ROI is because most users have 1 account and not many hence this is something that would affect people like us testing across different emails than actual customers. Even if it does affect a real customer its not a breaking experience atm since its an incorrect growl for them. 

Anyway with those thoughts in mind i'm going to close it from to focus on other tasks. If you feel like we should continue working on this or are passionate to work on this feel free to reopen/work on it 🙂
