### ISSUE TITLE
[HOLD for payment 2022-05-20] [$250] The attachment name overlaps with the red/yellow/green buttons at the top

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#8762]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Make the window small and open an attachment

## Expected Result:
Text does not overlap

## Actual Result:
When on a compressed desktop screen and viewing an attachment, the attachment name overlaps with the red/yellow/green buttons at the top

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Desktop App

**Version Number:** 1.1.55-0
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 
<img width="677" alt="Screen Shot 2022-04-21 at 1 05 09 PM" src="https://user-images.githubusercontent.com/43995119/165028218-dfb163ad-4f56-4e7b-ab90-55d4c790b1fd.png">

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @rafecolton 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1650571751927279

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by dylanexpensify** [comment]
Internal: https://www.upwork.com/ab/applicants/1518886451848237056/job-details
External: https://www.upwork.com/jobs/~019f5d9ff6440c4be2

**Comment by tgolen** [comment]
Looks good to me! I see we are using `<HeaderGap>` in another similar spot. 🟢  to hire @mollfpr for this.

**Comment by rushatgabhane** [comment]
Unassigned because I'm OOO

**Comment by misingo255** [comment]
**Proposal** 

1. Wrap the buttons into different view to that of the attachments.
2. Add a margin between the views.

**Comment by mollfpr** [comment]
@tgolen It is okay if I raise PR now? Since there's no C+ in here or should I wait for something first? Thanks!

**Comment by mollfpr** [comment]
@tgolen Okay, thank you!

I already applied to upwork, will be raise the PR ASAP!

**Comment by jliexpensify** [comment]
Dylan's on parental leave, so I'll take care of payment. Thanks!

**Comment by jliexpensify** [comment]
Paid!
