### ISSUE TITLE
Android/IOS - Invalidate button is not fully visible

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#8783]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch the app
2. Log in with expensifail account
3. Go to Settings - Preferences

## Expected Result:
Invalidate button is fully visible

## Actual Result:
Invalidate button is not fully visible

## Workaround:
Unknow

## Platform:

Where is this issue occurring?

- iOS
- Android

**Version Number:** 1.1.57.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** No 

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

![viber_image_2022-04-26_11-01-43-722](https://user-images.githubusercontent.com/93399543/165331280-327cc729-16b9-4841-8ced-185bb16268f0.jpg)
![Image from iOS (1)](https://user-images.githubusercontent.com/93399543/165331693-c9a1b670-460b-4c3f-adea-dbdae1cd0a9c.jpg)

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Julesssss** [comment]
I'm going to go ahead and remove the deployBlocker label. It's an easy fix, and not THAT important. 

Doing this for Tim as the US is asleep.

**Comment by Julesssss** [comment]
I also marked it off the deploy checklist

**Comment by tgolen** [comment]
I'm gonna grab this and fix it.
