### ISSUE TITLE
Update API so uploading an image doesn't cause the thumbnail to resize 3 times

### ISSUE THREAD

**Issue by michaelhaxhiu** [Expensify/App#8784]
This GH is being created as the counterpart to [this E/app github](https://github.com/Expensify/App/issues/8590), per @chiragsalian's request:
>can you create an issue and assign it to me so that i can make the API changes.
___

## Action Performed:
1. Open any chat
2. Upload a larger file to share

## Expected Result:
The API should support thumbnail should load once uploaded, or if it's a large file it should display a spinner until it's uploaded. We need to update the API to return the dimensions of the image upload.

## Actual Result:
If you share an image, the uploading thumbnail resizes 3 times. Then it finalizes the upload.

## Workaround:
>Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

No

## Platform:

Where is this issue occurring?

- Web

**Comment by michaelhaxhiu** [comment]
Let me know if it's ok to keep this in the E/App repository @chiragsalian (I can make it under E/E if that's better)?

**Comment by chiragsalian** [comment]
I think its fine as is. I've just put the PR for review.

**Comment by michaelhaxhiu** [comment]
weeeeee

**Comment by chiragsalian** [comment]
This went to prod last week. Closing issue.
