### ISSUE TITLE
[Chase] Expenses are wrongfully importing into parent and child CCs 

### ISSUE THREAD

**Issue by michaelhaxhiu** [Expensify/App#8785]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Chat:** https://www.expensify.com/concierge/#/chat/9689033
**Admin:** pam@cillessenconstruction.com
**Last message:** 
>Heath - 4659 is the parent. Felix - 1629 is the child.
>On card ending in 1629 there are charges that should actually be for card 4659.

## Expected Result:
If a user sets up their Chase CC connection using their username/password, we should import transactions into each dedicated card accounts (i.e. expenses shouldn't import and commingle between child CC or parent CC accounts).

## Actual Result:
The customer is claiming that transactions from the parent card (x4659 assigned to heath@cillessenconstruction.com) are importing to the wrong child card account (x1629 assigned to felix@cillessenconstruction.com)

![image](https://user-images.githubusercontent.com/13206896/165344572-ccf9722f-eed3-4f13-a20c-e5afa87136c4.png)

All expenses on report ID 92996797 should NOT have imported under the CC ending in xx1629 assigned to felix@cillessenconstruction.com (these actually belong to x4659)

<img width="1369" alt="image" src="https://user-images.githubusercontent.com/13206896/165352773-6d4a765e-f648-43be-9bf7-6ef244890a14.png">

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 
**Reproducible in staging?:** 
**Reproducible in production?:** 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:** 
**Issue reported by:** 
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by michaelhaxhiu** [comment]
Waiting on the customer to clarify which fo these transactions do not belong under the CC x 1629 assigned to 
felix@cillessenconstruction.com

**Comment by koswalto** [comment]
https://www.expensify.com/concierge/#/chat/10126599
djuneau@calmicroturbine.com - admin

>we have a company Chase card with 10 or so employees, one employee got expenses that should go to another employee

smarquez@calmicroturbine.com - got connected to the parent card **9297** instead of his own card **4581**

Card **9297** does not belong to an Expensify employee, so this is not good. 

Example, this expense shows that it's coming through to smarquez@calmicroturbine.com on card 4581...

![image](https://user-images.githubusercontent.com/13737717/165350844-c29b4227-60fb-446f-84af-258154ad9d75.png)

... but when the admin shows us the statement, it's actually on card 9297. They didn't paste a screenshot of the exact statement, but this still tells the story:

![image](https://user-images.githubusercontent.com/13737717/165351096-84243631-4bb8-4745-8e79-2b0077de3e57.png)

**Comment by koswalto** [comment]
Sounds like @marklouisdeshaun also had a customer run into this issue too and will be posting details soon, so safe to say 3 of these suddenly should be looked into pretty quickly. Leaving as a daily.

**Comment by sarajojacobson** [comment]
carissa@assemblygroup.com
https://www.expensify.com/concierge/#/chat/5983906

All of Carissa's charges are showing up on Pilar's account as well as hers.

Report ID 92901515

Carissa - 8101
Pilar - 3785

![image](https://user-images.githubusercontent.com/12812676/165355563-b9f5201e-26cd-43c9-b7aa-55bf35a979a0.png)

**Comment by michaelhaxhiu** [comment]
fuck ... this is under E/App. Need to make under E/E
