### ISSUE TITLE
Mac/Safari - Book Travel - "Learn more" link opens a new window instead of a new tab

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#8786]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Pre-Condition: Have workspace set up and bank account connected
1. Access staging.new.expensify.com
2. Sign into an applause.expensifail,com account
3. Click on the "Profile" icon and proceed to the user workspace
4. Click on "Book Travel"
5. Click on "Learn more"

## Expected Result:
The user expects to remain on the same page and a new tab open with the https://community.expensify.com/discussion/7066/introducing-concierge-travel link

## Actual Result:
The user is redirected to a completely new window instead of a new tab. This is the only option in all of the workspace settings in which this happens. The user may not notice at first that it is a new window and will then be forced to re access the entire site by changing the URL

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web (Mac/Safari

**Version Number:** 1.1.57.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/165353486-bbc66d6d-9294-4b27-992a-c9a699ee5b32.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by luacmartins** [comment]
@kbecciv is this a regression or did we change the expected behavior?

**Comment by kbecciv** [comment]
@luacmartins This is from Regression
