### ISSUE TITLE
[HOLD for payment 2022-05-23] [$250] Validate password complexity in the front end

### ISSUE THREAD

**Issue by marcaaron** [Expensify/App#8794]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Sign in with a password that is too short

## Expected Result:

1. Error message is shown and we do not call `Authenticate` command

## Actual Result:

1. Authenticate command is called and error message is shown

![2022-04-26_13-33-12](https://user-images.githubusercontent.com/32969087/165409577-f8913935-dbd5-4005-bb54-fd1569899bb5.png)

## Workaround:

Yes

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:** 
**Issue reported by:** 
**Slack conversation:** 

**Job Post** https://www.upwork.com/jobs/~01b4cd92ce29d9f69c

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

# IMPORTANT

Our password complexity check is in use here we're just not using it for sign in

https://github.com/Expensify/App/blob/84d058f5ade145a8bc89e00c36b340ba9078a8b0/src/CONST.js#L376-L377

**Comment by tgolen** [comment]
@thesahindia Care to put a quick proposal together for this?

**Comment by thesahindia** [comment]
> @thesahindia Care to put a quick proposal together for this?

Yeah sure.

### Proposal

We have a function for this already -
https://github.com/Expensify/App/blob/bd548576e288229e516223d2ac40929a7825b6a0/src/libs/ValidationUtils.js#L276-L277

We can just use it inside `validateAndSubmitForm `
https://github.com/Expensify/App/blob/bd548576e288229e516223d2ac40929a7825b6a0/src/pages/signin/PasswordForm.js#L93-L100

```js
        if (!ValidationUtils.isValidPassword(this.state.password)) {
            this.setState({formError: 'passwordForm.error.incorrectLoginOrPassword'});
            return;
        }
```
Just a quick question, we wanna show the same error message right?

**Comment by tgolen** [comment]
Looks good to me! @kevinksullivan Can you spin up something in Upwork for this and hire @thesahindia?

> Just a quick question, we wanna show the same error message right?

Yeah, I think `passwordForm.error.incorrectLoginOrPassword` is fine to use for now.

**Comment by kevinksullivan** [comment]
hm sorry about that @mananjadhav , I added you back in case we need a C+ for review.

@thesahindia I sent an offer for the [job](https://www.upwork.com/jobs/~01b4cd92ce29d9f69c) in Upwork, please accept when you get a chance.

**Comment by thesahindia** [comment]
Accepted the offer, will raise the PR today.

**Comment by kevinksullivan** [comment]
Waiting on deploy.

**Comment by mallenexpensify** [comment]
Hired ya @mananjadhav , let us know when you accept
Paid @thesahindia $250 for the fix,

**Comment by mananjadhav** [comment]
Accepted @mallenexpensify

**Comment by mallenexpensify** [comment]
Paid @mananjadhav $250 for C+
Thanks for the help y'all
