### ISSUE TITLE
[HOLD] Chat - Duplicate message appears using the "Simulate failing network requests" toggle

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#8811]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue was found when executing PR:** https://github.com/Expensify/App/pull/8713 

## Action Performed:
1. Launch the app
2. Log in with expensifail account
3. Go to Setting - Preferences
4. Toggl the "Simulate failing network requests".
5. Go to any chat and send message

## Expected Result:
 One message appears using the "Simulate failing network requests" toggle

## Actual Result:
 Duplicate message appears using the "Simulate failing network requests" toggle

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.57

**Reproducible in staging?:** Yes

**Reproducible in production?:** No (new feature)

**Email or phone of affected tester (no customers):** applausetester+42222abb@applause.expensifail.com

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

![Screenshot_20220427-163542_New Expensify](https://user-images.githubusercontent.com/93399543/165656344-e62def41-7487-4876-94d6-f316c074fbff.jpg)

https://user-images.githubusercontent.com/93399543/165656346-0f829b76-842b-4457-8b5c-3868d9607943.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by nkuoch** [comment]
cc @marcochavezf

**Comment by marcaaron** [comment]
Let's put this one on hold for now. I'm making a lot of changes to the network code atm and can look into why this happens.

**Comment by marcochavezf** [comment]
Hi @marcaaron! I'm going to assign this issue to you, I suppose there are still ongoing changes to the network code :)

**Comment by marcaaron** [comment]
Yeah I'm just going to close this for now. If there's an issue with the testing tool we'll find out when we give specific guidance for how it should be used.
