### ISSUE TITLE
Web -  Two frequently used emoji sections after deleting the search term and pressed Enter Key @Puneet-here

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#8824]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to https://staging.new.expensify.com and log in with any account
2. Go to Chat > Open Emoji menu
3. Write few words in the emoji search box
4. Delete the searched term and press Enter

## Expected Result:
 One frequently used emoji sections after deleting the search term and pressed Enter Key

## Actual Result:
 Two frequently used emoji sections after deleting the search term and pressed Enter Key

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web

**Version Number:** 1.1.57.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/165832861-f8451841-e1df-4d54-b2e5-6377028c318d.mov

**Expensify/Expensify Issue URL:** 

**Issue reported by:** @Puneet-here

**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1648993457842049

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by tgolen** [comment]
I'm going to take a look into this. There are a few bugs here... For example, if you search for an emoji, delete all the search text, then press enter, the words `frequentlyUsed` will be inserted into the compose input.

**Comment by Puneet-here** [comment]
@tgolen, can we open this as it is eligible for the reporting.

**Comment by tgolen** [comment]
Hi @Puneet-here, there has already been a PR merged to fix this.

**Comment by tgolen** [comment]
Oh, wait, I misunderstood what you meant. Does it need to be reopened to be eligible for the reporting? I'm not sure, but maybe @sonialiap knows.

**Comment by Puneet-here** [comment]
> Oh, wait, I misunderstood what you meant. Does it need to be reopened to be eligible for the reporting? I'm not sure, but maybe @sonialiap knows.

Yes I had reported this on slack.

**Comment by Puneet-here** [comment]
> Oh, wait, I misunderstood what you meant. Does it need to be reopened to be eligible for the reporting? I'm not sure, but maybe @sonialiap knows.

cc: @sonialiap

**Comment by Puneet-here** [comment]
@mallenexpensify  can you look into this I think @sonialiap is OOO.

**Comment by mallenexpensify** [comment]
Eeeeeeps!  Sorry about this @Puneet-here .  The way I see this

1. You reported the issue
2. We fixed it internally
3. You are due compensation for reporting the issue, $250. 

If so, you are definitely due $$$.  I created a job and invited you (I think).  Let me know when you've accepted the invite
https://www.upwork.com/jobs/~01b062fa8979bd5cbe

**Comment by Puneet-here** [comment]
@mallenexpensify, thanks for creating the job. Applied.

**Comment by mallenexpensify** [comment]
Hired @Puneet-here , let me know when you've accepted and I'll pay then close this issue. 
https://www.upwork.com/jobs/~01b062fa8979bd5cbe

**Comment by Puneet-here** [comment]
@mallenexpensify, I have accepted the offer now. Thanks.
