### ISSUE TITLE
Improve #8721 to reopen issue once assigned to CM to issue payment to reporting contributor

### ISSUE THREAD

**Issue by mallenexpensify** [Expensify/App#8833]
In https://github.com/Expensify/App/issues/8721 we updated the time when a CM is assigned to issue payment to a contributor for issues they report that get fixed internally.  

**Problem:** Issue stays closed when the CM is assigned so it's easy for them to miss it, ie. in K2
**Solution:** When assigning the CM, reopen the issue **and make it a daily** so the CM knows there's an action to be taken. 

Slack discussion: https://expensify.slack.com/archives/C01SKUP7QR0/p1651190801743499

**Comment by mallenexpensify** [comment]
Sorry @MitchExpensify , should have removed the assigner label before posting, don't need 👀 cuz it's a relatively small update that we discussed in slack.

**Comment by mallenexpensify** [comment]
@Beamanator while you're in there... can you take a look at 
https://github.com/Expensify/App/issues/7835#issuecomment-1113517714
I think this comment might be added in error?  (and _might_ be related to the previous work you did)

**Comment by Beamanator** [comment]
It also looks like there's another bug in my code (mentioned here: https://github.com/Expensify/Web-Expensify/pull/33616#issuecomment-1113585147) where we're posting on E/E issues where we should be posting on E/App issues 🤔  will fix that one here too!

**Comment by Beamanator** [comment]
PR to fix the the comment being added when the `Help Wanted` label was applied is ^

**Comment by Beamanator** [comment]
PR ^ added to create a new function that will allow us to reopen GH issues

**Comment by Beamanator** [comment]
Final PR to finish it off ^ (waiting on PHP-Libs PR to be merged first)

**Comment by Beamanator** [comment]
PR merged! Waiting on production deploy

**Comment by Beamanator** [comment]
@mallenexpensify Looks like I missed your idea to make the reopened issue a daily (to make sure the contributor gets paid) - I assume we still want that, right? If so I'll try to add that tomorrow 👍

**Comment by mallenexpensify** [comment]
Yeah, I think it should be a daily, otherwise it could _linger_ for a while and not get paid

**Comment by Beamanator** [comment]
Making weekly again just to keep the old priority - this was completed in the linked PR (not sure why this didn't close)
