### ISSUE TITLE
New internal label webhook tests - reported by @danieldoglas

### ISSUE THREAD

**Issue by danieldoglas** [Expensify/App#8835]
Testing https://github.com/Expensify/Web-Expensify/pull/33616

**Comment by Beamanator** [comment]
going to test again! first with a label that's NOT `Internal` (this was causing the comment to appear before) then WITH `Internal`, which should result in a comment posting on this issue

**Comment by Beamanator** [comment]
No comment 👍

**Comment by Beamanator** [comment]
Yaya comment on this issue, not the same issue number in E/E 👍

**Comment by Beamanator** [comment]
Tests passed 🥳 thanks @JmillsExpensify this was just for testing!
