### ISSUE TITLE
Settings - Part of Test Preferences isn't translated in Spanish

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#8843]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensify.com
2. Log in domain account
3. Settings - Preferences
4. Change language to Spanish

## Expected Result:
 Part of Test Preferences is translated in Spanish

## Actual Result:
 Part of Test Preferences isn't translated in Spanish

## Workaround:
Unknown
## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.57.4

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**Email or phone of affected tester (no customers):** any domain account

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation
![Spanish](https://user-images.githubusercontent.com/93399543/166112806-ce414629-f833-419c-901b-e1b1dc7964a5.png)

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by thienlnam** [comment]
Looks like these are part of the TestToolRow component and just need localization added.  https://github.com/Expensify/App/pull/8713

These only live on the staging environment so I think it's fine if we don't have localization added here cc @marcaaron

**Comment by tgolen** [comment]
Yeah, I agree that since these are only for testing purposes, we don't need them translated. I'll close this.
