### ISSUE TITLE
Opening Emoji picker on Android is very slow

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#8848]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Navigate to any chat 
2. click on Emoji picker 
3. Select emoji 

## Expected Result:
Emoji picker should open quickly and paste

## Actual Result:
Emoji takes longer to load 

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Android

**Version Number:** 1.1.57-0
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 

https://user-images.githubusercontent.com/43995119/166193111-845719ff-b537-4504-8ad1-7ca57d6b6773.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @cead22 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1649791658653949
https://expensify.slack.com/archives/C01GTK53T8Q/p1647905810766269

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by flodnv** [comment]
@cead22 can you please define "slow"? It feels pretty fast to me.

**Comment by cead22** [comment]
@flodnv this was reported by @kidroca so tagging him. I don't have an android, but it sounds like it isn't slow for you which is good. Could this be a device specific thing? What devices do you guys have?

**Comment by kidroca** [comment]
Opening is a bit slow, but actually selecting an emoji is the thing that seem to hang

Maybe it doesn't hang, but for some reason the first tap is not detected 
In the video from the description emojis are picked only after the 2nd tap

My test device is Samsung Galaxy S7 edge from 2017 so it's a bit old 😃

**Comment by cead22** [comment]
Thanks for the context

> My test device is Samsung Galaxy S7 edge from 2017 so it's a bit old 😃

Given this, I'm thinking we should close unless we know it's happening on newer phones, but curious for your opinions as well, because I could see an argument that new dot should work well on older phones too, but I also know older phones and laptops tend to get slow no matter what

**Comment by mvtglobally** [comment]
Couldn't hold my QA mind away from this one :) specially as I also have Samsung Galaxy S7 
Here is a comparison SG S7 and SG S20 FE 
Video is a bit backwards as It shot with upside laptop camera, but you can catch the device response speed (all other indicators are same - wifi, account, build)

https://user-images.githubusercontent.com/43995119/168209931-69d4abf3-535a-4463-a2ab-39aa4e2f83b0.MOV

**Comment by mvtglobally** [comment]
https://user-images.githubusercontent.com/43995119/168210586-9e45dea3-1167-46ca-8144-92e8d40726d5.mp4

**Comment by flodnv** [comment]
Nice one @mvtglobally 😄 I'd be interested in the same comparison in other apps like Slack or a simpler one like Whatsapp.

I kinda agree that ideally our app should run fast on old devices, although I am not sure how realistic that dream is (2017 is not actually **old**, what a world we live in...)

**Comment by cead22** [comment]
Making this monthly while I focus on this one https://github.com/Expensify/Expensify/issues/206455

**Comment by cead22** [comment]
@mvtglobally thanks for the side by side! 

I'm closing this for now, I think it's more important to focus on all the N7 docs and the performance for newer devices first, and the difference here is pretty small
