### ISSUE TITLE
[HOLD for payment 2022-05-27] [$250] Notification Growl on Workspace manage member show-up only once - reported by @Tushu17

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#8850]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open website in Desktop > settings > workspace 
2. Go to Manage member
3. Touch on Admin multiple times

## Expected Result:
It should show Notification Growl on every attempt.

## Actual Result:
It show growl only once.

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- iOS
- Android
- Mobile Web

**Version Number:** 1.1.57-0
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 

https://user-images.githubusercontent.com/43995119/166193649-348413f5-36a9-48b3-952d-6c7592ff2906.mov

**Upwork job link:** https://www.upwork.com/jobs/~01bc20ad2e82856ef6
**Issue reported by:** @Tushu17
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1649878756138299

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kakajann** [comment]
# Proposal
Revoking the `showTooltipForLogin` state back to empty string, immediately after setting it to `login` will fix this issue.

Code:
```diff
diff --git a/src/pages/workspace/WorkspaceMembersPage.js b/src/pages/workspace/WorkspaceMembersPage.js
index b6415ca7d..88d1343ad 100644
--- a/src/pages/workspace/WorkspaceMembersPage.js
+++ b/src/pages/workspace/WorkspaceMembersPage.js
@@ -153,7 +153,13 @@ class WorkspaceMembersPage extends React.Component {

         const canBeRemoved = this.props.policy.owner !== login && this.props.session.email !== login;
         if (!canBeRemoved) {
-            this.setState({showTooltipForLogin: login});
+            this.setState({
+                showTooltipForLogin: login,
+            }, () => {
+                this.setState({
+                    showTooltipForLogin: '',
+                });
+            });
         }

         return !canBeRemoved;
```

# Result

https://user-images.githubusercontent.com/11542415/166311757-dc955cf3-5de0-4489-9c26-25c3c82e8f67.mov

**Comment by tgolen** [comment]
@kakajann Can you please explain how the tooltip causes a problem with the growl?

**Comment by kadiealexander** [comment]
Not overdue. Seems like a good one to fix.

**Comment by marcochavezf** [comment]
Applying the `External` label

**Comment by kakajann** [comment]
> @kakajann Can you please explain how the tooltip causes a problem with the growl?

Actually, this component triggers the Growl in `WorkspaceMembersPage`. Even if its name is `CheckboxWithTooltip`
https://github.com/Expensify/App/blob/724ccb46ca4b2f48f6052592cbacc7ffe9528c5c/src/pages/workspace/WorkspaceMembersPage.js#L207-L214

And as you can see there's a prop
```js
toggleTooltip={this.state.showTooltipForLogin === item.login}
```

So, when a user presses their own name, a new state is dispatched here:

https://github.com/Expensify/App/blob/724ccb46ca4b2f48f6052592cbacc7ffe9528c5c/src/pages/workspace/WorkspaceMembersPage.js#L154-L157

But `toggleTooltip` won't react on 2nd press because `showTooltipForLogin` doesn't change and you don't see Growl error.

My proposal above will fix this issue

**Comment by michaelhaxhiu** [comment]
Sorry I missed this, last week was busy. Job is posted!

**Comment by NikkiWines** [comment]
Hmm, yeah this is interesting. @kakajann's proposal will fix the issue but I agree it might be worth decoupling the growl from checkbox with tooltip - it feels weird that they're intertwined. 

@pecanoro looks like you worked on this (somewhat) recently, what are your thoughts on decoupling the growl and checkbox? Or do you think we should just take the quick fix for this.

**Comment by pecanoro** [comment]
We originally bundled them together due to having lots of trouble making the growl work on all platforms since obviously hovering won't work on mobile. I know it's not great, but after discussing it with @tgolen for a while, this was the only way we found to make it work on all platforms. If any of you are able to come up with a proposal to decouple them and make them work fine on all platforms that would be great!

**Comment by parasharrajat** [comment]
cc: @NikkiWines :arrow_up:

**Comment by michaelhaxhiu** [comment]
@NikkiWines lil bump - are we good to proceed with what has been clarified and proposed?

**Comment by NikkiWines** [comment]
Sorry, was OOO last week. Thanks for the clarification @pecanoro. If someone comes up with a proposal to decouple things that would be great, but for now @kakajann's [proposal](https://github.com/Expensify/App/issues/8850#issuecomment-1120478723) is a good path forward 👍 

@michaelhaxhiu can you hire them in UpWork for this job please? 🙏

**Comment by michaelhaxhiu** [comment]
Sounds good. @kakajann can you please apply for the job on upwork? It's linked in the GH body, and here too for easy reference - https://www.upwork.com/jobs/~01bc20ad2e82856ef6

**Comment by kakajann** [comment]
Just applied

**Comment by michaelhaxhiu** [comment]
hired

**Comment by michaelhaxhiu** [comment]
@parasharrajat are you able to apply for this job too? https://www.upwork.com/jobs/~01bc20ad2e82856ef6
@Tushu17 same thing, please!

**Comment by kakajann** [comment]
ping for Upwork, kinda urgent )

**Comment by michaelhaxhiu** [comment]
Thanks for your patience and work on this job, @kakajann. Just paid you.

Need to pay Tushu & Rajat next.

**Comment by Tushu17** [comment]
@michaelhaxhiu Offer accepted, Thanks.

**Comment by michaelhaxhiu** [comment]
All paid.
