### ISSUE TITLE
[HOLD for payment 2022-05-23][$250] Make emojis larger when multiple are sent at the same time. 

### ISSUE THREAD

**Issue by JmillsExpensify** [Expensify/App#8867]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Send a message of only emojis (at least two).

## Expected Result:
All emojis should appear very large (27pt) in the report history.

## Actual Result:
Emojis only appear large in the report history if there is only one emoji in the message.

## Workaround:
The only workaround is to send one emoji at a time

## Platform:
All 

**Version Number:** v1.1.56-0
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**Email or phone of affected tester (no customers):** jason@expensicorp.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:**
<img width="253" alt="Screen Shot 2022-05-03 at 3 54 38 PM" src="https://user-images.githubusercontent.com/1127863/166564204-9d573dc2-40e2-4cf3-956e-8b72d837a817.png">

**Expensify/Expensify Issue URL:** 
**Issue reported by:** Jason Mills
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by JmillsExpensify** [comment]
I'll just take this one, un-assigning Jeremy.

**Comment by JmillsExpensify** [comment]
This issue is being broken off from https://github.com/Expensify/App/issues/4114. See there for more context.

**Comment by eVoloshchak** [comment]
Duplicating my original [proposal](https://github.com/Expensify/App/issues/4114#issuecomment-1102753010):
1. Add the following function to [EmojiUtils](https://github.com/Expensify/App/blob/main/src/libs/EmojiUtils.js):
```javascript
function containsOnlyEmojis(message) {
    const match = message.match(CONST.REGEX.EMOJIS);
    return match && match.length === [...message].length;
}
```
2. In `ReportActionItemFragment.js` replace [this](https://github.com/Expensify/App/blob/8f654504b989bf78f141b72504e48e5993a1ab7f/src/pages/home/report/ReportActionItemFragment.js#L109) line with:
```javascript
style={EmojiUtils.containsOnlyEmojis(props.fragment.text) ? styles.singleEmojiText : undefined}
```
3. Rename `styles.singleEmojiText` to something more fitting, probably `styles.messageEmojiText`

**Result:**
![image](https://user-images.githubusercontent.com/9059945/166571183-a0559a02-6d25-4d2c-95eb-8bcee01a9357.png)

**Comment by JmillsExpensify** [comment]
@Julesssss when you get a chance, please prioritize @eVoloshchak's proposal. I just added the exported label but this issue has a long history.

**Comment by JmillsExpensify** [comment]
Ok cool! That sounds good. I'll remove him from the issue and assign @eVoloshchak.

**Comment by Santhosh-Sellavel** [comment]
Yep I was away, just looking forward for the PR!

**Comment by eVoloshchak** [comment]
Is there Upwork job for this so I could apply?

**Comment by Santhosh-Sellavel** [comment]
@JmillsExpensify

**Comment by JmillsExpensify** [comment]
https://www.upwork.com/jobs/~0194ac8a9245d25860

cc @eVoloshchak @Santhosh-Sellavel

**Comment by tgolen** [comment]
I have one quick question about the proposal...

@eVoloshchak, What is the purpose of using the spread operator here? Is it necessary?

```
[...message].length
```

**Comment by eVoloshchak** [comment]
> @eVoloshchak, What is the purpose of using the spread operator here? Is it necessary?

It is necessary because `message.length` would give us the count of UTF-16 units, and emojis can be up to 32 UTF-16 units, if I'm not mistaken. So using spread operator allows us to get the actual number of characters (emojis in this case).
[Snack](https://snack.expo.dev/C8zGRB65R)

**Comment by tgolen** [comment]
TIL! Thank you. Please be sure to add that as a comment in the code when you write it. I wonder why the spread operator does that...

**Comment by tgolen** [comment]
Cool investigation! My initial concern is that it looks like a pretty intensive function that will be run a LOT (several maps, filters, etc.). I think we need to make sure it's optimized as much as it can be. It looks like there are multiple methods there which you didn't include the source of (trimEmojiUnicode, getEmojiUnicode, etc.). Maybe some of those can be memoized? Let's make sure the end result is evaluated for extreme performance.

I think it's going to be a very good idea to have good unit tests around this.

**Comment by tgolen** [comment]
It almost seems to me like we should only be doing this calculation once for every message when it's created (and edited) and then stored as a field on the message. That would prevent us from doing the same calculation over and over and over everytime this message is displayed for everyone.

**Comment by eVoloshchak** [comment]
> Thank you for checking on those things. Do you get similar results on mobile platforms? Android is typically where we have seen the biggest performance bottleneck.

Android is about 3 times slower, message with ~250 emojis takes 4.4ms. But, unlike in web, memoization doesn't yield any noticeable difference.
![Screenshot from 2022-05-09 19-43-56](https://user-images.githubusercontent.com/9059945/167457923-ad5b87c4-f688-4fa7-89d7-52eae80628bb.png)

**Comment by tgolen** [comment]
OK, it looks like the performance isn't terrible (but also frustrating that it's 3x worse). I think it's OK to move forward and we can keep in mind the alternative solution in the future if this is something we want to come back and optimize.

cc @cead22 just so you are aware of this performance discussion (since you're working on some performance projects).

@JmillsExpensify can you please hire @eVoloshchak for this and let's get a PR going 👍

**Comment by Julesssss** [comment]
Thanks Tim, good idea to actually measure the performance impact of this change. 

We had already hired, but were awaiting the outcome of this discussion. Looks like we're good to review the PR now.

**Comment by eVoloshchak** [comment]
PR is already up, but since we're discovered that memoization reduces time (at least for web), I need to update it.
I need to memoize [getEmojiUnicode](https://github.com/Expensify/App/blob/919a384991e6c88d570bd7061a53f0adebf822b3/src/libs/EmojiUtils.js#L12) function, that looks like this:
```javascript
function getEmojiUnicode(input) {
...
```
When testing i just did 
```javascript
const getEmojiUnicode = _.memoize((input) => {
```
but this feels wrong because all other methods in this file are non-anonymous functions.
Is there a way to memoize a `function` without making it anonymous?

**Comment by tgolen** [comment]
What's the problem with making it anonymous?

One solution:
```
function getEmojiUnicode(input) {
    return _.memoize(blah blah);
}
```

**Comment by eVoloshchak** [comment]
> What's the problem with making it anonymous?

No problem, if that's acceptable from the styling perspective. I just thought about this because all other methods in this file are non-anonymous
Thanks!

**Comment by JmillsExpensify** [comment]
PR made it to staging. Hoping the issue will update automatically once it hits production, but if not I'll circle back and update to reflect the holding period.

**Comment by JmillsExpensify** [comment]
This was an interesting one to catch up on! At this point we've made it to the 7-day regression period, though @marcaaron jumped in to help out in the linked PR. I agree with his [comment there](https://github.com/Expensify/App/pull/8896#issuecomment-1129427955) that it's unclear if that counted as a regression. Accordingly, I'm issuing the payment and closing this issue now that we're out 7 days regardless.

**Comment by JmillsExpensify** [comment]
@eVoloshchak has been successfully paid. @Santhosh-Sellavel we'll get you squared away as soon as you're able to accept the offer I just sent. At that point, I'll come back and close the issue.

**Comment by Santhosh-Sellavel** [comment]
Done, @JmillsExpensify!

**Comment by JmillsExpensify** [comment]
Great payment issued, thanks! Let me know if either of you have any questions. Closing for now.
