### ISSUE TITLE
Improve feedback on opening non-existing workspace

### ISSUE THREAD

**Issue by aldo-expensify** [Expensify/App#8885]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Login into new dot
2. Open workspace url with id that doesn't exists (or you don't have access too): https://new.expensify.com/workspace/xxx

## Expected Result:
Get feedback on that the workspace doesn't exists or your don't have access

## Actual Result:
Spinner rotating forever in RHN

![image](https://user-images.githubusercontent.com/87341702/166999434-f0a5910a-aa44-4a59-9c0f-b5deccbb7240.png)

## Workaround:
User can just close the RHN clicking outside

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 
**Reproducible in staging?:** 
**Reproducible in production?:** 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:** 
**Issue reported by:** 
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by tgolen** [comment]
Is there a specific case or flow that leads to this? If it's just about randomly modifying the URL, then I don't really think we need to do anything. However, if there is a legit flow, then I can see how we should display something. At least a "cannot be found" page.

**Comment by aldo-expensify** [comment]
It is not an expected flow, just an edge case. A way to replicate it is:

1. Login in OldDot with an account that has a workspace, go to `Settings > Policies > Group`
2. Login in NewDot in a different tab
3. Delete the workspace from NewDot
4. In OldDot, click the workspace that is still there and you will end up with a URL of a workspace that doesn't exist

I think of very low importance, but normally I would expect an app to handle properly not finding a resource. Feel free to close if you think it is not worth fixing :)

**Comment by strepanier03** [comment]
This does seem like an extreme edge case and one not likely to be raised by a customer. I think we close this for now and reopen it when we're looking to polish NewDot or if this becomes an issue for users. 

I do not understand the scope of the technical work that goes into handling this, so please feel free to get a second opinion if needed.

**Comment by tgolen** [comment]
OK, thanks! I think it's probably fine to leave open and see if a
contributor wants to take it. We should probably add some guidance about
what we want this page to look like. Ping design for that?
