### ISSUE TITLE
Group chat messages not being marked as read

### ISSUE THREAD

**Issue by Julesssss** [Expensify/App#8891]
## Action Performed:
- Be part of a group chat
- Be on a different chat
- Recieve a new message
- (A) Click into the chat
- (B) Scroll up and down

## Expected Result:
- Events A & B should cause the bolded text and 'New Message' line to disappear

## Actual Result:
- The bolded message and 'New Message' line only disappears when I click the group chat in the LHN for the second time

https://user-images.githubusercontent.com/10736861/167118801-52ecf9aa-9ba6-4387-863d-988dbe53b49a.mov

## Workaround:
- Click the LHN group chat a second time

## Platform:

Where is this issue occurring?

- Web 
- Possibly Desktop, I'm unable to check currently

**Version Number:** v1.1.57-6
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**Email or phone of affected tester (no customers):** jules@exp...
**Notes/Photos/Videos:**Shown above

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Julesssss** [comment]
Hi @Christinadobrzyn, I'd like to keep this internal for the moment, as I might fix it myself

**Comment by Christinadobrzyn** [comment]
Sounds good! I'll keep it assigned as is for the time being.

**Comment by Christinadobrzyn** [comment]
Hey @Julesssss would it be okay to move this to a `weekly` label instead of `daily`?

**Comment by Julesssss** [comment]
Oh yeah, of course :)

**Comment by Julesssss** [comment]
No update

**Comment by Julesssss** [comment]
Closing as dupe
