### ISSUE TITLE
IOS 14 - Login- Chat standalone app very slow to load when entering credentials.

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#8931]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch the app
2. On sign in page start typing your user name
3. On password page start typing your password 
4. Tap Sign in

## Expected Result:
Chat standalone app very slow to load when entering credentials.

## Actual Result:
Chat standalone app should work normally after entering credentials.

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- iOS 14.2

**Version Number:** 1.1.15.12

**Reproducible in staging?:** Yes

**Reproducible in production?:**  Yes

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/167741824-e7952c72-102d-49e7-961c-5840e8f11481.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by aldo-expensify** [comment]
@kbecciv 👋 , is this something that happens with any account you try on IOS 14?

**Comment by aldo-expensify** [comment]
And does the same account work faster if you try on Android?

**Comment by kbecciv** [comment]
@aldo-expensify Entering credentials is working as expected in Andriod 12

https://user-images.githubusercontent.com/93399543/167916676-9db781c5-45d9-4c52-bab6-456c732e4057.mp4

**Comment by aldo-expensify** [comment]
Is this last video from an Android 12 device?

**Comment by aldo-expensify** [comment]
No overdue, waiting for @kbecciv

**Comment by aldo-expensify** [comment]
No overdue, still waiting for feedback

**Comment by kbecciv** [comment]
@aldo-expensify Yes, Andriod 12, sorry for delay, I missed your tread.

**Comment by aldo-expensify** [comment]
@kbecciv no worries, so... would you agree with that this may not be specific to IOS, but maybe related to the account you are using? I'm saying this because the Android video look as slow as the IOS video (unless I'm missing something).  Does this also happen in web for this account?

**Comment by kbecciv** [comment]
@aldo-expensify Just retest with latest build 1.1.62 and issue is no longer reproduced.

https://user-images.githubusercontent.com/93399543/168908654-8c9b8553-41b1-4091-ae3a-44aca0326708.MP4

**Comment by aldo-expensify** [comment]
Ok, I'm going to close this for now. Feel free to reopen if you see this happening again.
