### ISSUE TITLE
Feature Request: Allow MacOS app download link to be copy from Right Hand Nav/Pane

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#8933]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
## Problem: 
When you want to share a link with someone to download the MacOS app, it's not possible to copy it from within the app

## Solution: 
Add the ability to right-click on macOS in App download links in About in Settings in Right Hand Nav/Pane

## Action Performed:
1. Navigate to Settings > About > App download links

## Expected Result:
There should be the correct link to download desktop build (e.g. https://new.expensify.com/NewExpensify.dmg)

## Actual Result:
Unable to copy via Desktop or Web (Chrome)

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Web
- Desktop App

**Version Number:** 1.1.57-12
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 
<img width="454" alt="image - 2022-05-10T234016 584" src="https://user-images.githubusercontent.com/43995119/167764644-5923ee97-6773-4bc7-bce7-7f20505fa52f.png">

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @mallenexpensify 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1652194232420029

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by strepanier03** [comment]
Oops, sorry for the hold up. This wasn't showing on my dashboard until it was overdue so I missed it. Looking now.

**Comment by strepanier03** [comment]
I can see how this could be handy, not 100% sure of the value or difficulty in adding it though. Sending on for another opinion.

**Comment by madmax330** [comment]
should be pretty straightforward

**Comment by Justicea83** [comment]
picking this up

**Comment by Justicea83** [comment]
picking this up

**Comment by JmillsExpensify** [comment]
Nice! I'll hold off on posting to Upwork for the time being, but will keep myself assigned to the issue.

**Comment by Justicea83** [comment]
I think we should be able to copy the links of all the items in the list, maybe the user just wanna share the link. In all cases the user already has the application installed so they might wanna share the urls with their friends.

**Comment by JmillsExpensify** [comment]
Linked PR made it to production 4 days ago.
