### ISSUE TITLE
[HOLD] App looks broken in OS Level Dark mode - reported by @Santhosh-Sellavel 

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#8937]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Enable dark mode in Mobile
2. Open the app

## Expected Result:
No color/theme change at all.

## Actual Result:
Broken theme

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Android

**Version Number:** 1.1.57-4
**Reproducible in staging?:** need repro 
**Reproducible in production?:** need repro
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:**  

https://user-images.githubusercontent.com/43995119/167766420-3f986ed0-c4ab-45ab-aecc-3f431da47bee.mp4

**Issue reported by:** @Santhosh-Sellavel 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1650301710192109?thread_ts=1650299941.141589&cid=C01GTK53T8Q

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mvtglobally** [comment]
Added Needs Repro label as we dont have MIUI device to confirm, but issue seem valid

**Comment by roryabraham** [comment]
Maybe should HOLD on [this beautiful gem](https://expensify.slack.com/archives/C03TME82F/p1652295038231249?thread_ts=1652132673.534919&cid=C03TME82F)?

cc @Luke9389 @michelle-thompson

**Comment by Luke9389** [comment]
Yep, let's put it on hold. 👍

**Comment by roryabraham** [comment]
This is still on hold for now, and I actually think we should close this and pay @Santhosh-Sellavel the reporting bonus.

As exciting as darkmode is, it needs to be its own project, for which the lion's share of the work will be on design's side. This issue just tells us that we should dynamically switch the app theme to match the OS theme. While I'd be _THRILLED_ to help implement darkmode, I don't really have the design chops. I know @michelle-thompson does though 😉

**Comment by roryabraham** [comment]
@jliexpensify let's pay @Santhosh-Sellavel the reporting bonus and then close this out.

**Comment by roryabraham** [comment]
Go away melvin, not overdue

**Comment by jliexpensify** [comment]
Ah sorry, I must have missed this one. WIll spin up an Upworks job and pay now!

**Comment by jliexpensify** [comment]
Internal - https://www.upwork.com/ab/applicants/1537772930159931392/job-details
External - https://www.upwork.com/jobs/~01aea769533677b9b3

hired @Santhosh-Sellavel

**Comment by rahmanharoon** [comment]
Is this issue is related with that yellow background on textinput?

**Comment by Santhosh-Sellavel** [comment]
No @rahmanharoon, it's about supporting night mode. This is not open for external work yet, please look at other [open jobs](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22).

**Comment by jliexpensify** [comment]
Apologies @Santhosh-Sellavel - I was OOO. Have hired you, once accepted I'll pay out the bonus and close.

**Comment by jliexpensify** [comment]
Paid, and closing!
