### ISSUE TITLE
Focus outline is not getting removed on blur of the select dropdown - reported by @parasharrajat

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#8939]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the Preference page via Settings > Preferences
2. Click on any dropdown.
3. Click outside to close the dropdown.

## Expected Result:
Blue border on the dropdown should be removed as soon as user blurs it.

## Actual Result:
Select dropdown stays in focused style.

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Web
- Desktop App

**Version Number:** 1.1.57-4
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 
![image - 2022-05-11T002503 158](https://user-images.githubusercontent.com/43995119/167768935-4dd0a1e2-d50c-4fde-833e-a321d2985516.png)

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @parasharrajat
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1650821915782839

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by parasharrajat** [comment]
I already asked to fix this on the PR which caused this regression. https://github.com/Expensify/App/issues/7535#issuecomment-1107885622. 

So this is being fixed here https://github.com/Expensify/App/pull/8765. But Reporting bonus was not paid.

**Comment by kadiealexander** [comment]
Thanks for that context @parasharrajat, I'll have a chat to @laurenreidexpensify and @stitesExpensify to see how best to handle this one.

**Comment by stitesExpensify** [comment]
Okay so that PR is just now being approved. I think we close this issue, get that PR merged, and then pay @parasharrajat on the original issue where he reported it. What do you think @laurenreidexpensify

**Comment by kadiealexander** [comment]
Sounds like a good plan to me! Lauren's at a conference this week, so I'll help out until she's back.
