### ISSUE TITLE
[HOLD for payment 2022-06-13] [$250] mWeb - Chat - Drawer does not close after tapping download file

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#8942]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go https://staging.new.expensify.com/
2. Log in with any account
3. Find the chat where you can download the file
4. Hold the finger on any type of file (mp4, png., mov)
5. Tap download

## Expected Result:
Drawer is closing after tapping download file.

## Actual Result:
Drawer not closing after tapping download file. Drawer closes for other options but not for the download one

## Workaround:
Unknown 

## Platform:

Where is this issue occurring?

- Mobile Web

**Version Number:** 1.1.57.12

**Reproducible in staging?:** Yes

**Reproducible in production?:** No 9new feature)

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/167868364-fed6095a-dc24-4a8c-9780-bbb45d54cb98.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by sobitneupane** [comment]
**Proposal**
This issue is occurring in web as well. Addition of following lines of code should solve the issue.
https://github.com/Expensify/App/blob/a2f8cf96d095ded70a15d04ee69bd37be2638c14/src/pages/home/report/ContextMenu/ContextMenuActions.js#L46-L54

```diff
        onPress: (closePopover, {reportAction}) => {
            const message = _.last(lodashGet(reportAction, 'message', [{}]));
            const html = lodashGet(message, 'html', '');
            const attachmentDetails = getAttachmentDetails(html);
            const {originalFileName} = attachmentDetails;
            let {sourceURL} = attachmentDetails;
            sourceURL = addEncryptedAuthTokenToURL(sourceURL);
            fileDownload(sourceURL, originalFileName);
+          if (closePopover) {
+              hideContextMenu(true, ReportActionComposeFocusManager.focus);
+          }
        },
```

**Comment by stephanieelliott** [comment]
Posted to Upwork: https://www.upwork.com/jobs/~01a4a5d881f891960a

**Comment by stephanieelliott** [comment]
Heads up, @neil-marcellini and @rushatgabhane we have a proposal for this already [here](https://github.com/Expensify/App/issues/8942#issuecomment-1124500275).

**Comment by jayeshmangwani** [comment]
Proposal:

we can call `hideContextMenu` on `fileDownload` promise is finally either fulfilled or rejected,

https://github.com/Expensify/App/blob/56213d07d5e10b5ecf1cb2fae2d82aff9360bb5a/src/pages/home/report/ContextMenu/ContextMenuActions.js#L46-L54

```diff
onPress: (closePopover, {reportAction}) => { 
     const message = _.last(lodashGet(reportAction, 'message', [{}])); 
     const html = lodashGet(message, 'html', ''); 
     const attachmentDetails = getAttachmentDetails(html); 
     const {originalFileName} = attachmentDetails; 
     let {sourceURL} = attachmentDetails; 
     sourceURL = addEncryptedAuthTokenToURL(sourceURL); 
-    fileDownload(sourceURL, originalFileName);
+    fileDownload(sourceURL, originalFileName)
+                .finally(()=> hideContextMenu(true, ReportActionComposeFocusManager.focus));
```
```

**Comment by rushatgabhane** [comment]
🎀 👀 🎀 C+ reviewed 
@yuwenmemon I like @sobitneupane's [proposal](https://github.com/Expensify/App/issues/8942#issuecomment-1124500275). I don't see why we should wait for the promise to be resolved. We prefer optimistic UI changes.

P. S. @sobitneupane do we really need to check this condition? `if (closePopover)`. Please make sure to explain why this is or isn't required in the PR. Thanks

**Comment by neil-marcellini** [comment]
I agree with @rushatgabhane that @sobitneupane has a good proposal. Personally I think we should check `if (closePopover)`, but I'm also curious to hear your explanation.

**Comment by sobitneupane** [comment]
`closePopover` is false only for `MiniReportActionContextMenu` which remains active as long as mouse is hovered over the message.
<img width="179" alt="Screen Shot 2022-05-24 at 17 32 56" src="https://user-images.githubusercontent.com/25876548/170028167-bc76f2e3-28eb-487a-9900-941c864af2c7.png">

With the condition check, we are avoiding unnecessary call of `hideContextMenu` as `MiniReportActionContextMenu` remains active as long as message is being hovered.

**Comment by neil-marcellini** [comment]
@sobitneupane Thanks for your explanation. I will assign you to this issue and I look forward to reviewing your PR.

**Comment by stephanieelliott** [comment]
Hey @sobitneupane, can you apply to the job on Upwork when you get a chance? https://www.upwork.com/jobs/~01a4a5d881f891960a

**Comment by sobitneupane** [comment]
> Hey @sobitneupane, can you apply to the job on Upwork when you get a chance? https://www.upwork.com/jobs/~01a4a5d881f891960a

Applied.

**Comment by neil-marcellini** [comment]
PR is under review now.

**Comment by stephanieelliott** [comment]
PR is on staging

**Comment by stephanieelliott** [comment]
All paid, thank you!
