### ISSUE TITLE
mWeb - Chat - Download icon is not active for mp4 and mov files.

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#8943]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue was found when executing PR:** https://github.com/Expensify/App/pull/8739

## Action Performed:
1. Go https://staging.new.expensify.com/
2. Log in with any account
3. Find the chat where you can download the mp4 file
4. Hold the finger on file
5. Tap download

## Expected Result:
Download icon is active for mp4 and mov files.

## Actual Result:
Describe what actually happened

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.57.12

**Reproducible in staging?:** Yes

**Reproducible in production?:** No (new feature)

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/167872007-f1375146-db16-4046-b877-034e58fbda89.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by thienlnam** [comment]
This appears to be happening on Web as well and not just isolated to mp4 and mov files.  The structure of the html did not change and so this seems like it must be an issue with how we determine items are files

**Comment by thienlnam** [comment]
Found the offending PR https://github.com/Expensify/App/pull/8769
