### ISSUE TITLE
Android/IOS - App is crashed when you tap on the unread message indicator

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#8945]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to the app and log in with account A 
3. Send a message from Account B, using another device to account A
4. Check message in Account A
5. Verify that the unread message indicator appears at the top of the page
6. Tap on the unread message indicator

## Expected Result:
App is redirected to a new unread message

## Actual Result:
App is crashed when you tap on the unread message indicator

## Workaround:
Unknown 

## Platform:

Where is this issue occurring?

- iOS
- Android

**Version Number:** 1.1.57-12

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

[log.txt](https://github.com/Expensify/App/files/8671621/log.txt)

https://user-images.githubusercontent.com/93399543/167896508-dba15850-f3ef-4cb0-874d-794c04dacf53.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by luacmartins** [comment]
I see the error below. Seems to be happening in [this call](https://github.com/Expensify/App/blob/42da9392c8b33545b77499a3053a6e4d1467221c/src/pages/home/report/ReportActionsView.js#L295).

![Screenshot_1652306720](https://user-images.githubusercontent.com/22219519/167956280-a78c87b6-ff42-48db-b188-6483724350f0.png)

**Comment by marcochavezf** [comment]
Yup, the `scrollToBottomAndUpdateLastRead` is not bound to `this`, creating a PR

**Comment by chiragsalian** [comment]
This should be resolved on version `1.1.57-15`. i'd like it to be staging tested so,
@kbecciv, can you retest and if it passes then remove deployBlocker and check if off the checklist? 🙇‍♂️

**Comment by chiragsalian** [comment]
Looks like it was tested and checked off the list. Closing issue.
