### ISSUE TITLE
Log in - "Set Password" button should be disable when field is blank

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#8962]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to https://staging.new.expensify.com
2. Start typing a new email account
3. Click Continue
4. Go back to your email and tap on link
5. Change the URL to staging
6. Click on "Set Password" button

## Expected Result:
 "Set Password" button should be disable when field is blank 

## Actual Result:
 "Set Password" button is enabled when field is blank

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.57.15

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/168085482-839f5b5a-57fb-4cb5-b3fa-81b5726d08db.mp4

https://user-images.githubusercontent.com/93399543/168085480-134014c9-fd4a-4eb1-94e1-ba7775a01e1c.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by thesahindia** [comment]
It's a regression from https://github.com/Expensify/App/pull/8680

Need to pass `isDisabled={!this.state.isFormValid}` here -
https://github.com/Expensify/App/blob/f25c38f374a09434e698b51e85add25c0481b3b1/src/pages/SetPasswordPage.js#L133-L135

**Comment by chiragsalian** [comment]
Hi @kbecciv, this should be resolved in version `1.1.57-16` or higher.
Can you retest and confirm? if its resolved feel free to close the issue.

**Comment by chiragsalian** [comment]
Passed the checklist, closing isssue.
