### ISSUE TITLE
UI is not fully fitting the frame on autofill input field - reported by @aneequeahmad

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#8981]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open app 
2. Autofill email or password field.

## Expected Result:
Ui should occupy all space.

## Actual Result:
UI is not fully fitting the frame on autofill input field

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.57-4
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:**  
![UI-Issue](https://user-images.githubusercontent.com/43995119/168206641-0f94b14a-8857-4234-a468-bf0480978218.jpeg)
![Ui-bug](https://user-images.githubusercontent.com/43995119/168206644-229af7d9-8341-4785-be6a-ba21a4ab785f.jpeg)

**Issue reported by:** @aneequeahmad
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1650488426303659

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Christinadobrzyn** [comment]
I'm not sure if this is intentional or if it might be fixed with this change - https://github.com/Expensify/App/issues/7470. Sending to engineers to review!

**Comment by Gonals** [comment]
Yep, @Christinadobrzyn, I believe they are basically the same issue :). Closing this one!

**Comment by aneequeahmad** [comment]
@Gonals I think this is another issue as it was appearing on every platform and that is because of 1px more/less `border-radius`

**Comment by parasharrajat** [comment]
Agree with @Christinadobrzyn. It should be fixed on the other issue if that is supposed to be fixed.  This is a very edge case and not worth of ROI.
