### ISSUE TITLE
Android - VBA - App is crashed after tap Connect bank account

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#8992]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch the app
2. Log in with Expensifail account
3. Go to Setting - Preferences
4. Enable the Staging server
5. Go to any Workspace
6. Tap Connect Bank Account

## Expected Result:
App is not crashed after tap Connect bank account

## Actual Result:
App is crashed after tap Connect bank account

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.60.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/168337763-36cdd1a3-92db-4a50-be59-6854d8d64422.mp4

[log.txt](https://github.com/Expensify/App/files/8689803/log.txt)

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by neil-marcellini** [comment]
This was caused by my PR #8966. I put up #8993 to fix it.

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)
