### ISSUE TITLE
Older report comments are not loaded once we scroll to the top - reported by @santhosh-sellavel

### ISSUE THREAD

**Issue by chiragsalian** [Expensify/App#8994]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to https://staging.new.expensify.com
2. Click on any search that contains a good amount of history.
3. Scroll up to the top.

## Expected Result:
Once we reach the top more comments should have loaded.

## Actual Result:
No comments are loaded once we scroll to the top. So for a chat we can only see around 50-100 comments and not more.

## Workaround:
Unkown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.60-0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** any

**Logs:** https://expensify.slack.com/archives/C01GTK53T8Q/p1652463943094999

**Notes/Photos/Videos:** Any additional supporting documentation

**Expensify/Expensify Issue URL:** 

**Issue reported by:** @Santhosh-Sellavel 

**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1652463943094999

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by chiragsalian** [comment]
cc @thesahindia

**Comment by chiragsalian** [comment]
Its being worked on [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1652465594406659?thread_ts=1652463943.094999&cid=C01GTK53T8Q)

**Comment by thesahindia** [comment]
PR is up.

**Comment by chiragsalian** [comment]
PR has been merged but feel free to compensate @Santhosh-Sellavel for finding the issue and @thesahindia for helping resolve the issue.

**Comment by chiragsalian** [comment]
Reopening since i'll ask QA to test when this is on staging.

**Comment by roryabraham** [comment]
Looks like this passed QA

**Comment by michaelhaxhiu** [comment]
>PR has been merged @michaelhaxhiu, feel free to compensate @Santhosh-Sellavel for finding the issue and @thesahindia for helping resolve the issue when appropriate.

Yep! So here's what we should have:

@Santhosh-Sellavel - $250 for reporting the bug
@thesahindia - $250 for assisting in finding/fixing the deploy blocker

Can you both please apply to the upwork job [**here**](https://www.upwork.com/jobs/~0185f28766a8bdf0bc)

**Comment by Santhosh-Sellavel** [comment]
Applied, thanks!

**Comment by thesahindia** [comment]
Done ✅

**Comment by michaelhaxhiu** [comment]
Paid both!
