### ISSUE TITLE
Group Chat - Unable to create group chat, app crashed

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#8997]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Log in app
2. Click on the green plus button Untested
3. Click on Create Group
4. Search for at least 4 users and add them to the group.
2. Click created group

## Expected Result:
Able to create group chat

## Actual Result:
Unable to create group chat, app crashed

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.60

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/168347419-fcf42722-0b6d-4d90-8cc4-aac0fb8e08fc.mp4

![Group crashed](https://user-images.githubusercontent.com/93399543/168347615-6a377a41-b81a-49db-8757-cb16654b0d24.jpg)

**Expensify/Expensify Issue URL:** 

**Issue reported by:** 

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by roryabraham** [comment]
Going to look into this

**Comment by roryabraham** [comment]
This is already fixed on `main` by https://github.com/Expensify/App/pull/8998. Going to CP it to staging

**Comment by roryabraham** [comment]
This is fixed now
