### ISSUE TITLE
Chat - County code displayed for phone account in chat header

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#9019]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
Issue was found when executing #8436 
## Action Performed:
1. Launch the app
2. Log in with expensifail account
3. Search the phone account (Account D)
4. Select phone account

## Expected Result:
County code should not display for phone account

## Actual Result:
County code displayed for phone account

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.0.60.1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 
![Bug5571282_Screenshot_20220514-090816_New_Expensify](https://user-images.githubusercontent.com/43996225/168440248-75ed8270-df33-4b40-98db-e5b07560ee65.jpg)

**Expensify/Expensify Issue URL:** 
**Issue reported by:** 
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by roryabraham** [comment]
Not sure if this is a problem actually.

**Comment by danieldoglas** [comment]
I'll close this one.
