### ISSUE TITLE
 mWeb / Chrome - Blue outline focus isn't disappeared 

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#9041]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
Issue was found when executing #8765 
## Action Performed:
1. Go to staging.new.expensifail.com
2. Log in with any account
3. Go to Settings --> Preferences
4. Change the Priority mode to #focus

## Expected Result:
The blue focus style disappear as soon as the menu is closed.

## Actual Result:
Blue outline focus isn't disappeared in mWeb/Chrome.

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Mobile Web - Android Chrome only

**Version Number:** 1.1.61.3
**Reproducible in staging?:**  Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/168675745-e309d3d9-9312-423f-aa32-614100b4b5a4.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** Applause
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by parasharrajat** [comment]
Code merged on main. It will be fixed bin next QA cycle.
