### ISSUE TITLE
mWeb - IOU - After completing request money chat list appears for a brief moment

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#9049]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Tap on FAB button and select `Request Money`
3. Enter an amount
4. Select an attendee from the list, then select the confirmation button

## Expected Result:
The user expects a smooth transition when tapping on "Request Money"

## Actual Result:
Some part of the intermediate page is visible after tapping on "Request Money"

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Mobile Web

**Version Number:** v1.1.61-3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):**  applausetester+ihchat4@applause.expensifail.com / Yulia1986Gerets
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/168841261-3bda9d29-c779-47a1-9b62-792b5564efa3.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** Applause
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by marcaaron** [comment]
>The user expects a smooth transition when tapping on "Request Money"

The modal is opened over the chat list so it makes sense that we would close the modal then navigate to the chat. What is specifically meant by a "smooth transition"?

**Comment by aldo-expensify** [comment]
Agreed with @marcaaron , this looks fine for me. The bad thing I see is the laggy transitions, but that's not part of this GH issue :)

**Comment by marcaaron** [comment]
Nice gonna close then. Doesn't seem like this is worth putting through triage or getting outside help on.
