### ISSUE TITLE
Workspace - Reimburse expenses- "Fast reimbursements = happy members!" and  "Unlock Next day"  headings are switching after every refresh

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#9057]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Precondition: Add VBA flow
1. Go to https://staging.enew.xpensify.com/
2. Make sure you added VBA
3. Go to Settings - Reimburse expenses
4. Refresh the page

## Expected Result:
Either Fast reimbursements = happy members!  or Unlock Next day should keep appearing after refresh the page

## Actual Result:
Fast reimbursements = happy members! have been switched with Unlock Next day after refresh the page

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web

**Version Number:** 1.1.62.0
**Reproducible in staging?:**  y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/168916137-20c14424-0797-435b-917a-8aa64f7400c2.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** Applause
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by amyevans** [comment]
Would like to hang onto this and fix internally

**Comment by amyevans** [comment]
PR: https://github.com/Expensify/App/pull/9138 (Not sure why it didn't link itself?)
