### ISSUE TITLE
Web - Sign up - Endless loading spinner appears when creating a password for a new account

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#9058]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. In the email field, enter a email address for a new account and press continue
3. Navigate to the email inbox of the account and open the validation email
4. Copy the link and change it to staging
5. Set a password that follows the password requirements

## Expected Result:
After setting the password, the user must be navigated to the main screen

## Actual Result:
Loading spinner when creating a password for a new account until the user refreshes the page

## Workaround:
Page refresh resolves the issue

## Platform:

Where is this issue occurring?

- Web - Reproducible incosistently

**Version Number:** v1.1.62-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** iheretsutest+1705@gmail.com / Yulia1986Gerets
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/168920770-65a633a8-7124-4ddf-a79b-b28665033041.mp4

Issue is reproduced by this tester consistently
**Expensify/Expensify Issue URL:** 
**Issue reported by:** Applause
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by yuwenmemon** [comment]
cc @marcaaron could this be related to https://github.com/Expensify/App/pull/8865?

**Comment by marcaaron** [comment]
Pretty hard to say based on the video. They gave the email used so we could look at logs and try to see why.

**Comment by kavimuru** [comment]
@marcaaron This issue occurs only if the user hits "`Enter`" in the `set  password` screen. I have confirmed with the tester too.

**Comment by tgolen** [comment]
I was able to reproduce this and implement a fix.
