### ISSUE TITLE
iOS - Group chat - User name is highlighted when tapping on it to show the details of the user

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#9081]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

Issue found when executing #8409
## Action Performed:
1. Launch the app
2. Log in with any account
3. Create a group
4. Tap on any user in the group

## Expected Result:
User is not highlighted when tapping on it for group chat

## Actual Result:
User is highlighted when tapping on it in group chat to show the details

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- iOS

**Version Number:** 1.1.63.0
**Reproducible in staging?:** y
**Reproducible in production?:**  no (New feature)
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 
![Bug5576829_Image_from_iOS__2_](https://user-images.githubusercontent.com/43996225/169147110-727e633b-d462-41e2-94ec-9267b21bd2ad.jpg)

https://user-images.githubusercontent.com/43996225/169147112-d509216b-849c-4d04-9d74-ff18c1c5388b.MP4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** 
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by thesahindia** [comment]
Not a deploy blocker ❌. It's known and it was reported [here](https://github.com/Expensify/App/issues/7796)

**Comment by AndrewGable** [comment]
Ok great - Thanks for the link @thesahindia, let's close as a dupe and then reopen the original if needed.
