### ISSUE TITLE
[$250] Focus is lost in search after hitting enter 

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#9088]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open search
2. Write something that returns no results and press enter/return

## Expected Result:
Focus should stay in the search text

## Actual Result:
Focus is lost and you need to click on the search text again

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.63-0
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 

https://user-images.githubusercontent.com/43995119/169211589-d8f87544-ca35-4779-876a-2c8bee736bc6.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @iwiznia 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1652891764421739

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by sobitneupane** [comment]
**Proposal:**
While handling key press events, we can keep the text input focused if there are no options and Enter is pressed.
https://github.com/Expensify/App/blob/cc912ffac883d59f1ea1ca7a4173ed565bdf3f61/src/components/OptionsSelector.js#L156-L158

```diff
        if (allOptions.length === 0) {
+            if (e.nativeEvent.key==='Enter') {
+                InteractionManager.runAfterInteractions(() => {
+                    // Focus text input
+                    if (!this.textInput) {
+                        return;
+                    }
+                    this.textInput.focus();
+                });
+            }
            return;
        }
```
I also propose to remove selectTextOnFocus from TextInput because when Enter is pressed or text is focused, entered text is selected.
https://github.com/Expensify/App/blob/cc912ffac883d59f1ea1ca7a4173ed565bdf3f61/src/components/OptionsSelector.js#L232-L251

**Comment by nkuoch** [comment]
I don't feel like we need a fix for it, but asking @shawnborton 's opinion

**Comment by shawnborton** [comment]
I think it makes sense to keep the focus even after pressing enter.

**Comment by jliexpensify** [comment]
Internal - https://www.upwork.com/ab/applicants/1527464673445306368/job-details
External - https://www.upwork.com/jobs/~0133988b8f90396950

**Comment by Julesssss** [comment]
I agree with @nkuoch that it probably isn't necessary. But defer to Shawn. 

Awaiting proposals.

**Comment by iwiznia** [comment]
FWIW I reported this, without it, one small mistake and you are forced to use the mouse (THE MOUSE!) to do this 😄

**Comment by jayeshmangwani** [comment]
**Proposal:** 

We will add a prop blurOnSubmit on the search page, it will be prevented from submitting data on press enter, 
and condition will be like this,

1. we have to add 2 props at BaseTextInput for enabling blurOnSubmit on the specific pages and passing the length of the section

https://github.com/Expensify/App/blob/02fb4e9738fbe491c3a8e48dfb7abd141320baa6/src/components/TextInput/baseTextInputPropTypes.js#L3-L5
```
    sectionsLength: PropTypes.bool,
    isUseBlurOnSubmit: PropTypes.bool,
```

2. if isUseBlurOnSubmit enabled and input has value and sections length is zero, then disable the blurOnSubmit (prevent the user from submitting data)

```        
const doSectionEmpty = this.props.isUseBlurOnSubmit && this.state.value && this.props.sectionsLength === 0;
```

https://github.com/Expensify/App/blob/02fb4e9738fbe491c3a8e48dfb7abd141320baa6/src/components/TextInput/BaseTextInput.js#L248-L275

```
blurOnSubmit={!doSectionEmpty}
```

3. added isUseBlurOnSubmit prop to SearchPage
```
 isUseBlurOnSubmit={true}
```

https://github.com/Expensify/App/blob/02fb4e9738fbe491c3a8e48dfb7abd141320baa6/src/pages/SearchPage.js#L179-L189

4. passed 2 props in TextInput on OptionsSelector page

```
isUseBlurOnSubmit={this.props.isUseBlurOnSubmit}
sectionsLength={this.props.sections ? this.props.sections.length : 0}
 ```

https://github.com/Expensify/App/blob/02fb4e9738fbe491c3a8e48dfb7abd141320baa6/src/components/OptionsSelector.js#L232-L251

**Result:**

https://user-images.githubusercontent.com/35371050/169546803-3f859af1-fc3f-4304-b029-f12198bf9ae2.mov

**Comment by rushatgabhane** [comment]
> I also propose to remove selectTextOnFocus from TextInput because when Enter is pressed or text is focused, entered text is selected.

@sobitneupane the entered text is meant to be selected so that it can be cleared when searching for the next user in pages like new group and split bill.

**Comment by rushatgabhane** [comment]
@jayeshmangwani can you think of a simpler way to do this?
Passing `sectionsLength` as a prop to `TextInput` doesn't sound like a good idea.

**Comment by jayeshmangwani** [comment]
@rushatgabhane Updated proposal:

1. we can pass blurOnSubmit value from the SearchPage to OptionSelector like this if searchValue is not available and the section is empty then disable the submit button by pressing enter

https://github.com/Expensify/App/blob/02fb4e9738fbe491c3a8e48dfb7abd141320baa6/src/pages/SearchPage.js#L179-L189

```diff
+ blurOnSubmit={!(this.state.searchValue && sections.length === 0)}
```

2. we will define a prop blurOnSubmit for handling scenario when we don't have to call submit when data is empty 

https://github.com/Expensify/App/blob/02fb4e9738fbe491c3a8e48dfb7abd141320baa6/src/components/OptionsSelector.js#L78-L81

```diff
+/** Should we remove the focus when sections data is empty? */
+blurOnSubmit: PropTypes.bool,
    
```

default will be true
https://github.com/Expensify/App/blob/02fb4e9738fbe491c3a8e48dfb7abd141320baa6/src/components/OptionsSelector.js#L97-L98

```diff
+blurOnSubmit: true,
```
we will pass this prop to TextInput
https://github.com/Expensify/App/blob/02fb4e9738fbe491c3a8e48dfb7abd141320baa6/src/components/OptionsSelector.js#L268-L269

```diff
+blurOnSubmit={this.props.blurOnSubmit}
```

**Comment by rushatgabhane** [comment]
@jayeshmangwani why is SearchPage deciding the value of `blurOnSubmit`? 
What if we leave it to `OptionsSelector` instead? Then the issue will be solved for 5 pages, right?

**Comment by iamjey6** [comment]
@rushatgabhane Yes if we put this logic in `OptionsSelector` then it will be handling empty data on all the pages where we are using `OptionsSelector`, and I have added `blurOnSubmit` on `SearchPage` only bcause I thought we have to handle this in 1 page only

**Comment by jayeshmangwani** [comment]
@rushatgabhane 
1. I thought we have to handle this scenario for searchpage only
2. then it will disable onsubmit on all the 5 places if sections will be empty

**Comment by jayeshmangwani** [comment]
@rushatgabhane then we have to made 1 change only here,
https://github.com/Expensify/App/blob/02fb4e9738fbe491c3a8e48dfb7abd141320baa6/src/components/OptionsSelector.js#L232-L251

```diff
+ blurOnSubmit={!(this.props.value && this.props.sections.length === 0)}
```

**Comment by jayeshmangwani** [comment]
> > I thought we have to handle this scenario for searchpage only
> 
> Yes, but other pages also face the same issue. So let's fix them too!
> 
> > blurOnSubmit={!(this.props.value && this.props.sections.length === 0)}
> 
> @jayeshmangwani one last question, in which particular case `this.props.value` is important? 
> In other words, can we do `blurOnSubmit={Boolean(this.props.sections.length)}`?
> 

this.props.value is for checking that if any value then and then prevent empty data otherwise user can submit textinput and remove focus

**Comment by jayeshmangwani** [comment]
@rushatgabhane Updated proposal:

we have to filter sections like this,
https://github.com/Expensify/App/blob/d465ad07c74767842490a5f94c546c7f76c66ace/src/components/OptionsList/BaseOptionsList.js#L161

because response at new chat and other pages is like this empty array of data inside an object of the recents and contacts,
![Screenshot 2022-05-24 at 11 53 19 PM](https://user-images.githubusercontent.com/35371050/170106802-141a5f39-b554-44ef-a6f6-691ea0646332.png)

https://github.com/Expensify/App/blob/02fb4e9738fbe491c3a8e48dfb7abd141320baa6/src/components/OptionsSelector.js#L232-L251
```diff
+ blurOnSubmit={!(this.props.value 
+      && _.filter(this.props.sections, section => section.data.length !== 0).length === 0)}
```

**Comment by rushatgabhane** [comment]
@jayeshmangwani doing additional `O(n)` operations on every render for an expensive component doesn't sound like a great idea. Can we do better?

**Comment by rushatgabhane** [comment]
Since this is a non-critical issue, I think that it's a good idea to wait for more optimal proposals.

**Comment by orkunkarakus** [comment]
> @jayeshmangwani doing additional `O(n)` operations on every render for an expensive component doesn't sound like a great idea. We should keep in mind the performance implications for accounts that might have a few thousand reports.
> 
> Can we do better?

@rushatgabhane Hi,
If it is necessary to modified directly from the OptionsSelector component, it must be checked whether the data arrays are empty or not. When we look at the incoming section data there is a nested json array thus we need to make search operation. So what is this search operation for, this search operation is to find each json in the section array and find the length of the data array in this json. What would happen if there was no json inside, but a direct data array? There would be no change again, because this time we would have a nested array and we would have to query the length of the data array in each index of this section array. So we would have to do a search operation again. So we know, every search operation is a o(n) notation. Considering our current conditions, we know that it is necessary to perform a search operation but we should consider which o(n) algorithm we use to perform this search operation will get the best efficiency. I've tested several o(n) algorithms (array.map - array.filter - array.foreach). According to the results, foreach will be the most correct choice.

## Test Steps
1. Login with any user (i tested with test user -> applausetester+0901abb@applause.expensifail.com)
2. Open the search drawer
3. Click the search
4. Search the "test"
5. See the results

## Test Results
![image](https://user-images.githubusercontent.com/61627150/170893109-b6d049d1-01dc-474a-83b8-166857477197.png)

## Notes
array.find algorithm was also tried but a good efficiency could not be obtained.

**Comment by rushatgabhane** [comment]
>doing additional O(n) operations on every render for an expensive component doesn't sound like a great idea

I just reread what I had said and realized that n=2 over here 🤦‍♂️ my bad.

A slightly cleaner way to solve this issue would be to wait for #7702 to merge and use `state.allOptions.length` in OptionsSelector. That PR might merge anytime soon.

What do you think @Julesssss ? 

- Hold on #7702 (almost merged)
- or go with @jayeshmangwani 's [proposal ](https://github.com/Expensify/App/issues/9088#issuecomment-1136304290) right now.

**Comment by Julesssss** [comment]
Excellent reviewing so far @rushatgabhane 👍 

Holding on the above PR sounds like the best idea IMO. Hopefully, the above proposals won't need much modification once this is done. @jayeshmangwani please feel free to update your proposal if you'd still be interested.

**Comment by Julesssss** [comment]
We're holding on [this](https://github.com/Expensify/App/pull/7702) PR.

**Comment by jliexpensify** [comment]
Assigning Kadie as I am heading OOO

**Comment by rushatgabhane** [comment]
still holding

**Comment by Julesssss** [comment]
Still still holding

**Comment by rushatgabhane** [comment]
still still still holding

**Comment by rushatgabhane** [comment]
still still still holding

**Comment by rushatgabhane** [comment]
This issue is off hold. 7702 has merged!

@jayeshmangwani's [proposal](https://github.com/Expensify/App/issues/9088#issuecomment-1136304290) is good to go!
cc: @Julesssss 

🎀 👀 🎀 C+ reviewed

**Comment by Julesssss** [comment]
Hi @jayeshmangwani, are you still available to work on this if I assign you?

**Comment by jayeshmangwani** [comment]
Yes I am available @Julesssss , Thanks

**Comment by jayeshmangwani** [comment]
[PR](https://github.com/Expensify/App/pull/9601) raised, and the job is no longer available at Upwork
@rushatgabhane @Julesssss

**Comment by jliexpensify** [comment]
Re-posted:

Internal - https://www.upwork.com/ab/applicants/1541923006968999936/job-details
External - https://www.upwork.com/jobs/~018f0b8d4da5523520

@jayeshmangwani - I can't seen to find you in Upworks, please feel free to apply for te job or send me your profile link
@rushatgabhane - have invited you

**Comment by jayeshmangwani** [comment]
@jliexpensify applied for job, Thanks

**Comment by Julesssss** [comment]
Merged, we just need to wait for prod deployment and then the 7 day countdown will begin.

**Comment by jliexpensify** [comment]
Not overdue melvin.

**Comment by jliexpensify** [comment]
Hmm odd, the GH didn't update - @Julesssss or @rushatgabhane can you confirm I'm ok to pay based off https://github.com/Expensify/App/pull/9601?

**Comment by Julesssss** [comment]
Yeah, that is odd. Please go ahead and pay out though.

**Comment by jliexpensify** [comment]
Cheers for confirming Jules, paid!
