### ISSUE TITLE
[HOLD for payment 2022-07-05] [$250] FEATURE REQUEST: When automatically including a link, default to https instead of http if not specified

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#9089]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open any chat 
2. send safe.directory/link message 

## Expected Result:
When automatically including a link, if no scheme is specified default to https 

## Actual Result:
When automatically including a link, if no scheme is specified link defaults to http

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.63-0
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 
<img width="754" alt="Screen Shot 2022-05-17 at 10 26 22 AM" src="https://user-images.githubusercontent.com/43995119/169212281-c79349b0-92a9-419f-b325-db59df6c59cb.png">
![Screen Shot 2022-05-19 at 1 05 50 AM](https://user-images.githubusercontent.com/43995119/169212289-07998589-ddde-466e-8eed-0308c8ef09e4.png)

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @rafecolton 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1652808521820459

**Job Post:** https://www.upwork.com/jobs/~010e0b78d36773ffee

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by sobitneupane** [comment]
**Proposal:**
We need to make some changes in expensify-common repo. 
https://github.com/Expensify/expensify-common/blob/237fb782678fec9542d0a2608ea18ef2302995fd/lib/ExpensiMark.js#L89
```diff
-    return `<a href="${g3 && g3.includes('http') ? '' : 'http://'}${g2}" target="_blank" rel="noreferrer noopener">${g1}</a>`; 
+   return `<a href="${g3 && g3.includes('http') ? '' : 'https://'}${g2}" target="_blank" rel="noreferrer noopener">${g1}</a>`;
```
https://github.com/Expensify/expensify-common/blob/237fb782678fec9542d0a2608ea18ef2302995fd/lib/ExpensiMark.js#L120-L122
```diff
                replacement: (match, g1, g2, g3) => (
-    `${g1}<a href="${g3 && g3.includes('http') ? '' : 'http://'}${g2}" target="_blank" rel="noreferrer noopener">${g2}</a>${g1}`
+    `${g1}<a href="${g3 && g3.includes('http') ? '' : 'https://'}${g2}" target="_blank" rel="noreferrer noopener">${g2}</a>${g1}`
                ),
```

**Comment by jayeshmangwani** [comment]
Proposal:
In ExpensiMark, For `link` and `autoLink`, we are checking if it includes http, and not then we are adding `http://`, we have to add `https://` instead `http://`at both the places in 
`expensify-common/lib/ExpensiMark.js`

https://github.com/Expensify/expensify-common/blob/237fb782678fec9542d0a2608ea18ef2302995fd/lib/ExpensiMark.js#L84-L90

https://github.com/Expensify/expensify-common/blob/237fb782678fec9542d0a2608ea18ef2302995fd/lib/ExpensiMark.js#L107-L123

**Comment by Santhosh-Sellavel** [comment]
@marcochavezf 
We have two proposals, both are the same.
So let's go with the first one,  @sobitneupane  [proposal](https://github.com/Expensify/App/issues/9089#issuecomment-1131408879) looks good here.
🎀👀🎀 C+ reviewed!

**Comment by Santhosh-Sellavel** [comment]
@kevinksullivan Wonder why there is no external label here?

**Comment by marcochavezf** [comment]
Thanks @Santhosh-Sellavel, the proposal looks good, hiring @sobitneupane

**Comment by Santhosh-Sellavel** [comment]
@sobitneupane Any update here?

**Comment by sobitneupane** [comment]
> @sobitneupane Any update here?

will create PR by tomorrow.

**Comment by Santhosh-Sellavel** [comment]
@marcochavezf Can you review PR on repo expensify-common?

**Comment by marcochavezf** [comment]
Thanks @sobitneupane @Santhosh-Sellavel! Now we'll need a PR to update `expensify-commons` in the [package.json](https://github.com/Expensify/App/blob/c41a782c8628a1f30e102186494a685df9165ef1/package.json#L65) with the latest commit hash 😀

**Comment by Santhosh-Sellavel** [comment]
@marcochavezf 

Status on the issue:
The issue is almost fixed waiting for the final PR.
Mostly C+ duties are done, here.

If a PR is submitted before I sign off I'll check that too.

I'm going on OOO, moving forward If there is anything major that needs C+ attention, feel free to un-assign me and add a new C+ here, thanks!

cc: @kevinksullivan

**Comment by marcochavezf** [comment]
> Thanks @sobitneupane @Santhosh-Sellavel! Now we'll need a PR to update `expensify-commons` in the [package.json](https://github.com/Expensify/App/blob/c41a782c8628a1f30e102186494a685df9165ef1/package.json#L65) with the latest commit hash 😀

Hi @sobitneupane, did you create a PR to update `expensify-commons`? :)

**Comment by sobitneupane** [comment]
> Hi @sobitneupane, did you create a PR to update `expensify-commons`? :)

I will create it by tomorrow.

**Comment by marcochavezf** [comment]
Forgot to add the `Reviewing` label here, but also seems this issue is still happening in QA https://github.com/Expensify/App/pull/9471#issuecomment-1164266575

**Comment by kevinksullivan** [comment]
@sobitneupane paid. @Santhosh-Sellavel hired for C+, please let me know when you accept.

**Comment by Santhosh-Sellavel** [comment]
Accepted thanks!

**Comment by kevinksullivan** [comment]
Paid @Santhosh-Sellavel . All set!
