### ISSUE TITLE
[Needs Reproduction][$250] Chat with drafted text not showing in LHN for some accounts

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#9092]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Viewed chat with user A
2. Viewed chat with "New username for Manager account Allen - eCORP" , [manager.allen@expensicorp.com](mailto:manager.allen@expensicorp.com) account and noticed draft text in compose box
3. Viewed chat with User A

## Expected Result:
Draft chat with [manager.allen@expensicorp.com](mailto:manager.allen@expensicorp.com) to show at top in LHN with :pencil2: icon

## Actual Result:
Chat doesn't show as draft

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Desktop App

**Version Number:** 1.1.60-3
**Reproducible in staging?:** Y
**Reproducible in production?:** need repro
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 
[lhn no draft.txt](https://github.com/Expensify/App/files/8725152/lhn.no.draft.txt)

https://user-images.githubusercontent.com/43995119/169214972-91df4e2f-678b-41e9-a1e9-089a7d58da67.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @mallenexpensify 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1652727178530969

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by bondydaa** [comment]
i'm guessing something on the front end isn't being updated, it could possibly be that the backend hasn't returned a response yet or something like that but 🤷 lets investigate the front end first.

**Comment by Christinadobrzyn** [comment]
Job posted in Upwork: 

Internal posting - https://www.upwork.com/ab/applicants/1527478590208892928/job-details
External posting - https://www.upwork.com/jobs/~0175ef7266cf8bfb7e

**Comment by brianmuks** [comment]
Is it fine to test this issue with [manager.allen@expensicorp.com](mailto:manager.allen@expensicorp.com)?

**Comment by parasharrajat** [comment]
Can we get generalized reproduction steps? I don't think the current steps are enough @mvtglobally

**Comment by mallenexpensify** [comment]
I think reliably reproducing is likely going to be tough.  I haven't noticed it happen _much_ either. It's possible it has something to do with the expensicorp.com  email/domain.   How about we put on [HOLD] for now?  
If someone is able to find reliable reproduction steps, and we (Expensify/QA) are able to reproduce, we can compensate $250 for documenting and sharing the steps

**Comment by mallenexpensify** [comment]
K, I added the `Needs Reproduction` label and removed `Help Wanted`.  I'll keep 👀 peeled for being able to reproduce too

**Comment by NikkiWines** [comment]
Hmm, I'm also unable to reproduce this. @mallenexpensify can you try reproducing this again on your account it see if it's still an issue?
