### ISSUE TITLE
[$250] mWeb - IOU - Cursor not moveable between digits, unable to insert numbers

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#9119]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensifail.com
2. Log in with any account
3. Tap on Plus button
4. Tap Request Money
5. Type any numbers
6. Move the cursor to the middle and put any other number

## Expected Result:
Able to inset the number between digits in the amount moving the cursor 

## Actual Result:
Unable to inset the number between digits in the amount moving the cursor 

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Mobile Web

**Version Number:**  1.1.65.3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/169621316-54cdd3e1-1e6e-4cfe-aa04-3884e76716c7.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** Applause - Internal team
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by marcochavezf** [comment]
I can reproduce it on my android phone, applying the `External` label

**Comment by stephanieelliott** [comment]
Posted to Upwork: https://www.upwork.com/jobs/~010a55eacf56ab6d45

**Comment by mountiny** [comment]
Alright! Thanks for head up @rushatgabhane 

Sorry for such a quick turnaround @stephanieelliott, can we close the upwork job and this issue?

**Comment by stephanieelliott** [comment]
All good, took the job down!
