### ISSUE TITLE
Workspace -After connecting bank account the user can still see "Connect to bank" button

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#9161]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Access staging.new.expensifail.com
2. Sign into an applause.expensifail.com account
3. Tap on "Profile" icon > "Workspace' > "Connect bank account"
4. Proceed with the flow until the very end to successfully add the bank account
5. Return to the workspace menu and tap on any option (For example: "Issue Cards", "Pay Bills", etc.)

## Expected Result:
The user expects to see the new tab options that are shown after successfully connecting a bank account

## Actual Result:
The use can momentarily see the "Connect bank account" button before being shown the correct options

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.66.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** No ( unable to check the VBA flow in Production)

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/170138775-8858ab0d-4709-4809-a7b2-1c0444da793d.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team 

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Julesssss** [comment]
It seems to me that this is expected and not a regression. Production currently [requires the API call ](https://github.com/Expensify/App/blob/aac57d37c29c0d8d8fa6261f6a50c69295e966cd/src/pages/ReimbursementAccount/ReimbursementAccountPage.js#L75-L76)when opening the page before the Onyx `achData` is created and updated and this has been true for a while now. 

CC @marcaaron, please correct me if I'm mistaken 🙇‍♂️

**Comment by Julesssss** [comment]
> Reproducible in production?: No ( unable to check the VBA flow in Production)

Hi @kbecciv, does this mean that you wern't able to test this issue against production?

**Comment by kbecciv** [comment]
@Julesssss Yes, we need to use real bank credentials to test the VBA flow in Production. Tester just signed into the same user account for checking and issue does not happen in production. But I think that wasn't the best method to check.

https://user-images.githubusercontent.com/93399543/170267519-e9393798-e9dc-493a-a795-0e9e62fa1074.MP4

**Comment by marcaaron** [comment]
Agree with the general premise of this issue and don't _think_ we should be blocking anything or showing an outdated UI if we have an opportunity to show an up-to-date one.

Seems most likely related to these changes -> https://github.com/Expensify/App/pull/8946/files

I think we could be resetting the VBA when we go to fetch a new one? Or is it that we just haven't fetched it yet? Not sure.

**Comment by marcaaron** [comment]
I think we should just close this issue for now. It's not worth sending to External contributors as the implementation around all of this data fetching is going to change.
