### ISSUE TITLE
[$250] Web - Workspace - Added VBA does not show in any of the menu options when accessing offline

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#9166]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensify.com and login with expensifail account
2. Click avatar > workspace > Connect bank account
3. Add a VBA
4. Go to workspace and click any option (Issue cards, Reimburse expenses, Pay bills etc) and observe
5. Disable internet connection and click the same options

## Expected Result:
Step 4 - There should be no flickering before all the cards appear
Step 5 - Should display all the cards

## Actual Result:
Step 4 - There's a flash for a moment before cards appear
Step 5 - Connect to bank account appears

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- Desktop App
- Android
- iOS
- mWeb
**Version Number:** 1.1.66-0

**Reproducible in staging?:** Y

**Reproducible in production?:** No

**Email or phone of affected tester (no customers):** [applausetester++2501mn@applause.expensifail.com](mailto:applausetester++2501mn@applause.expensifail.com) / Utest123

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/170159983-266ead8f-122e-4a3b-b7b3-471c19d074af.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause internal team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Julesssss** [comment]
I'm not sure I completely understand the bug, but[ this PR](https://github.com/Expensify/App/issues/9166) seems the most likely cause. Commenting there.

**Comment by Julesssss** [comment]
Actually, it could be [this PR ](https://github.com/Expensify/App/pull/9138). Again, I think this is expected behaviour. Will wait for a second opinion before I resolve though.

**Comment by kavimuru** [comment]
@Julesssss When we access the menu options in the workspace editor while offline we see the button "Connect bank account" for VBA added account. But in production this is not the case.
<img width="960" alt="Production" src="https://user-images.githubusercontent.com/43996225/170246917-66d87160-26b2-4d50-a8b5-149292381adf.png">
<img width="960" alt="Staging" src="https://user-images.githubusercontent.com/43996225/170246919-fd32a861-a9be-41d1-84d9-4535755ce06c.png">
.

**Comment by Julesssss** [comment]
Thanks for confirming @kavimuru. 

While we may desire to make further improvements (by remembering whether the user has added a card), I still think that it's more of a side effect than a regression that should be reversed.

One way to do this would be to make a similar change to [this PR](https://github.com/Expensify/App/pull/9138), so that the component doesn't show until we know for certain whether the user has a connected bank account.

**Comment by Julesssss** [comment]
Resolving the blocker as discussed here and in [Slack](https://expensify.slack.com/archives/C07J32337/p1653493672703489). Let's continue the discussion and work towards an improvement.

**Comment by adelekennedy** [comment]
[internal](https://www.upwork.com/ab/applicants/1529935302129147904/job-details)
[external](https://www.upwork.com/jobs/~01f8cfc43c5276047f)

**Comment by marcaaron** [comment]
Sorry, I'm actually going to close this. These Offline issues should stay internal for now as we are re-writing the API and how data is fetched and stored and will be deep diving into all the flows and improving the designs.
