### ISSUE TITLE
Workspace -  Offline - User can't change currency and cant see tab options in workspace

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#9197]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Pre-Condition: Disable internet THEN open the module
1. Access staging.new.expensify.com
2. Sign into a valid account
3. Enable "Airplane mode" to simulate loss of internet
4. Click "Profile" > "Workspace" > "General Settings"
5. Click to change the Currency while offline
6. While offline, click on any of the tabs like "Issue cards", "Pay bills", etc.

## Expected Result:
In step 5 :The user expects to be able to change the currency while offline and when the internet is reestablished their changes will be saved
In step 6:  The user expects to open the tabs while offline and if any options are clicked there should be an offline prompt message alerting the user to their offline status

## Actual Result:
Step 5: The "Search Currency" function is blocked while offline if the user opens the workspace menu from the start while offline. If the user is already within the tab and loses internet connection they will be able to change the currency as normal. 
Step 6:  The user cannot access any of the tab options in workspace while offline, there will just be a white screen displayed and no info will display , not even a connect to bank button. (The only tab where this does not happen is on "Reimburse expenses")

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.68-2
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Email or phone of affected tester (no customers):** 
emilio.utest@gmail.com / Emilio9806
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/170595524-b36063c4-5d40-4131-b44e-7dbe708a8886.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** Applause internal team
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by marcaaron** [comment]
Flag as skip for now. Offline behavior is getting overhauled.
