### ISSUE TITLE
Control Onyx via Storybook controls

### ISSUE THREAD

**Issue by roryabraham** [Expensify/App#9209]
### Problem
Storybook is a very useful tool to build, test and showcase our UI. While it works great with React, there's no way to interface Onyx via storybook.

### Why this is important
Where Onyx values are used to control our UI components (for example, going from offline -> online), there's no way for us to adjust those Onyx values via the Storybook controls.

### Solution
Build some solution to connect storybook controls to Onyx (probably a Storybook plugin), not sure.

**Comment by roryabraham** [comment]
This is a curiosity, but likely won't be a priority in the near-term.

**Comment by roryabraham** [comment]
Not pursuing this right now, going to unassign myself for now. cc @marcaaron since I know you're a fan of Storybook

**Comment by marcaaron** [comment]
Yes! Love Storybook. But unsure what this issue is asking? Does it need to have anything to do with Onyx? Could see an argument that a well designed component has no knowledge of Onyx at all and should always be a dumb recipient of props like `isOffline: true/false` vs. having a dependency on an Onyx key.

**Comment by marcaaron** [comment]
>We have no way to tie Onyx data to Storybook controls. For example a switch to toggle isOffline between true or false, or a picker / input to switch the locale.

Onyx data is still just props though right? Something like `props.network.isOffline` should be editable in the story when you are messing around with whatever component.
