### ISSUE TITLE
[HOLD for payment 2023-06-01] Configure NetInfo to ping Auth for its internet reachability test

### ISSUE THREAD

**Issue by roryabraham** [Expensify/App#9211]
### Problem
We use NetInfo to track whether the app can access the internet. On web/desktop, that involves regularly polling a URL to see if we get a response. We currently poll the API root, which works as a test of internet reachability. It's better than using a random URL because it verifies not only that the internet is reachable, but also that our web servers are reachable.

However, it's possible that the web servers are reachable, but Auth is down. In this case, the app won't work as expected.

### Why this is important
This is associated with the [Boolean Offline Mode](https://docs.google.com/document/d/1r9tM7zRRC12gUWPibo_O0sZgyYxoogQNvrKz14SyEds/edit#) initiative, which seeks to establish a very robust standard for offline mode where if we're online everything works as expected, and if any system which the app relies on can't be communicated with as expected, then we go into offline mode and everything works to the extent possible in offline mode.

### Solution
Configure NetInfo to use a network request that will actually communicate with Auth as an internet reachability test.

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011d42c91cf9658297</li>
        <li>Upwork Job ID: 1656885165625516032</li>
        <li>Last Price Increase: 2023-05-12</li>
    </ul>
</details>

**Comment by roryabraham** [comment]
The design doc suggests using https://expensify.com/api?command=Get with a payload of:

- `returnValueList=nameValuePairs`
- `name=private_lastModified`
- `authToken=...`

The problem with that is that we to have an `authToken` in order for that to work, which means that it can't be used when the user is not logged in. We should find or create a public API endpoint that can be used to ping auth.

**Comment by roryabraham** [comment]
So, maybe we don't need an `authToken` because any authentication error would presumably come back with a 200 status code but a non-200 JSON code, which is fine. But the problem remains that we don't seem to be able to trigger a real `command=Get` request without using a POST request and passing the `returnValueList`, etc... in the request body, and NetInfo isn't configured to use a POST request with a body for it's internet reachability test.

**Comment by roryabraham** [comment]
>  But the problem remains that we don't seem to be able to trigger a real command=Get request without using a POST request and passing the returnValueList, etc... in the request body

JK, was able to trigger an auth call with a GET request in Postman:

<img width="874" alt="image" src="https://user-images.githubusercontent.com/47436092/171045739-c57648d2-544c-426f-9d59-d9694a2657ef.png">

**Comment by roryabraham** [comment]
No update here

**Comment by roryabraham** [comment]
Actually going to HOLD this on https://github.com/Expensify/App/issues/9020

**Comment by roryabraham** [comment]
No update here, still on HOLD

**Comment by roryabraham** [comment]
HOLDing this on https://github.com/Expensify/App/issues/9020

**Comment by roryabraham** [comment]
Still on HOLD

**Comment by roryabraham** [comment]
Still on HOLD

**Comment by roryabraham** [comment]
No update

**Comment by roryabraham** [comment]
No update

**Comment by roryabraham** [comment]
Still on HOLD

**Comment by roryabraham** [comment]
No update

**Comment by roryabraham** [comment]
No update

**Comment by roryabraham** [comment]
No update

**Comment by roryabraham** [comment]
So the one this was on HOLD for is now off HOLD, so we can take this off HOLD

**Comment by michaelhaxhiu** [comment]
🪀 yoo - is this job `internal` or `external`? I am going to label it `daily` now because it's unheld!

**Comment by roryabraham** [comment]
This is done
