### ISSUE TITLE
Web - Offline - Message displayed for offline user shows code

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#9223]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Access staging.new.expensify.com
2. Sign into any valid user
3. Disable internet connection
4. Proceed to any chat and type in the chat box

## Expected Result:
The user expects to see a message stating "Your appear to be offline"

## Actual Result:
The user sees a message that appears to be in code "reportActionCompose.youAppearToBeOffline"

## Workaround:
Unknown 

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.69.1

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

![OFFLINE](https://user-images.githubusercontent.com/93399543/171044405-460213fe-e032-4ae1-a0cf-ce4095ef6654.png)

https://user-images.githubusercontent.com/93399543/171044406-ad233216-c28d-4875-a433-d174132a4e4d.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause-Internal team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by luacmartins** [comment]
I can take this one!

**Comment by luacmartins** [comment]
`youAppearToBeOffline` was moved to `common.youAppearToBeOffline`. I put up a PR with a [fix](https://github.com/Expensify/App/pull/9224).
