### ISSUE TITLE
Workspace - Currency tab appears greyed and blocked momentarily when opening settings

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#9228]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Pre-Condition: User has a workspace
1. Access staging.new.expensify.com
2. Sign into a valid account
3. Tap on "Profile" icon > "Workspace" > "General Settings"

## Expected Result:
The user expects to see the currency tab white and able to immediately be accessed

## Actual Result:
The currency tab is greyed out and blocked for a couple of seconds before the user is able to access it. It happens on all platforms, some for a longer period than others

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.69.2

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/171060146-aa84c609-3843-457b-a300-f0e9ecfbc158.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by NikkiWines** [comment]
Based on this PR (https://github.com/Expensify/App/pull/9170) it looks like this behavior is expected. cc: @amyevans

**Comment by amyevans** [comment]
Yes, it's expected (discussion [here](https://github.com/Expensify/App/pull/9170#discussion_r882188941)).
