### ISSUE TITLE
Chat layout seems broken when app is refocused after minimising on iPad - reported by @aswin-s

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#9232]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Navigate to a report with a dozen or more messages in it.
2. Minimise the app
3. Now open the app again and checkout the messages.
4. The chat messages seems to overlap and there is additional spacing between independent chat messages.

## Expected Result:
Chat layout remains unchanged on refocus

## Actual Result:
Chat layout seems broken when app is refocused after minimizing on iPad.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platform:

Where is this issue occurring?

- iOS (iPad)

**Version Number:** 
**Reproducible in staging?:** 
**Reproducible in production?:** 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 

https://user-images.githubusercontent.com/43995119/171087269-5422fa76-aaa6-4c7b-82a0-0d0f8ea7da1a.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @aswin-s
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1650867701376999

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by sakluger** [comment]
I can test this tomorrow using my iPad since I'm wfh tomorrow.

**Comment by sakluger** [comment]
I completely forgot to test this out! Will test later on today.

**Comment by sakluger** [comment]
I can't reproduce this issue on the iPad New Expensify mobile app. I tested with my own account, and used the same Concierge chat, but it always loaded correctly with no overlapping text after minimizing and reopening the app.

Could you please reopen if you still experience this consistently, and please include more contextual information including whether it's the testflight or from the App Store, plus the app version? Thanks!
