### ISSUE TITLE
Feature Request: Ability to send multiple images at once - reported by @Puneet-here

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#9237]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
 1. Go to any chat
 2. Click the :heavy_plus_sign: button
 3. Click add attachment
 4. The finder will get open now try to select multiple images

## Expected Result:
It should let you multiple images

## Actual Result:
It doesn't let you select multiple images

## Workaround:
Unknown 

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.69-0
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 
![Screen Shot 2022-05-31 at 12 04 41 AM](https://user-images.githubusercontent.com/43995119/171090607-075ec448-c0a5-4105-948b-e3f56207d989.png)

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @Puneet-here
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1651010043230409

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by flodnv** [comment]
Let's be mindful of the priority of this. I would say it's very low. Maybe it's worth a #whatsnext post or something like that.

**Comment by parasharrajat** [comment]
This is a duplicate. We already planned this a few months back. There should be an internal issue.

**Comment by conorpendergrast** [comment]
Yep, found the internal issue here - https://github.com/Expensify/Expensify/issues/167375. We're anticipating doing it at some point, but not yet! I'll close this one for now as a result
