### ISSUE TITLE
Feature Request: There is not login link on the Set Password Page - reported by @parasharrajat

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#9243]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Problem:
There is not login link on the Set Password Page. Let's say user want to login bank with different email.  He has to manually change the url from the browser. 

## Solution:
Show a link to go to Login page.

## Action Performed:
1. Navigate to app 
2. Create a brand new account 
3. Go to email and click on the verification link 

## Expected Result:
User should be able to change account if needed 

## Actual Result:
There is not login link on the Set Password Page

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.69-0
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 
![image - 2022-05-31T002730 976](https://user-images.githubusercontent.com/43995119/171092782-9e941bee-a94b-4164-a471-4fa34decadaf.png)

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @parasharrajat
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1651157311177759

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by aldo-expensify** [comment]
@parasharrajat how did you get to this state? did you take too long to click on the link from the email so it expired? or is it something else?

**Comment by aldo-expensify** [comment]
Setting this as monthly as it looks like an edge case.

**Comment by parasharrajat** [comment]
I think you may be getting confused with the error on the screenshot. But it is not about that. 

There is simply no button or link which allows the user to go to login page.

**Comment by aldo-expensify** [comment]
I'll close this as I don't think this is a normal flow, and I think it may even cause to go back by mistake.

**Comment by aldo-expensify** [comment]
Asked for some opinions here: https://expensify.slack.com/archives/C01SKUP7QR0/p1654133653822269

Feel free to reopen if you disagree...
