### ISSUE TITLE
[HOLD for payment 2022-07-15] [$250] Password Field should not Autofill with the old password on the Set Password page - reported by @parasharrajat

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#9244]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go the login page.
2. Enter an email. Press Enter.
3. Click forget on the password page.
4. Check the mailbox and Copy the link.
5. open the link on the browser

## Expected Result:
Check that if you had saved the password earlier for the email, password field is autofilled.

## Actual Result:
It should not autofill with old password as user is expected to enter new password.

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Web

**Version Number:** 1.1.69-0
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 
![image - 2022-05-31T002838 657](https://user-images.githubusercontent.com/43995119/171092994-00392957-e7fd-4a56-9538-3a18d6e4b7a8.png)

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @parasharrajat
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1651158076558069

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by conorpendergrast** [comment]
It looks like there's [this](https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion) `autocomplete="new-password"` we could add to the password field when they're setting a new password. Seems like that would be helpful!

**Comment by allroundexperts** [comment]
# Proposal
As suggested by @conorpendergrast, we need to set `autoComplete` to `new-password` for the specific text input.

The following changes:

https://github.com/allroundexperts/Expensify/blob/0f38b9a0107977e2b49edef1534caf1199e08b38/src/pages/settings/NewPasswordForm.js#L71

To:

```
               <TextInput
                    autoComplete="new-password"
```

**Comment by Harshdeepjoshi** [comment]
###Proposal
Problem
We're nor passing any prop to decide the behaviour of auto complete in the input field
Solution
We should pass a prop autoCompleteType="new-password" for web and autoCompleteType="password-new"
new-password does not work for native

we will pass the new value here 
https://github.com/Expensify/App/blob/dc300ee45cde0124f6223f715a526c0f50ef2dcc/src/pages/settings/NewPasswordForm.js#L74

**Comment by rushatgabhane** [comment]
@allroundexperts @Harshdeepjoshi I'm really confused here.

`autoComplete="new-password"` works on web only.
`autoComplete="password-new"` works for Android only. ([React native docs](https://reactnative.dev/docs/next/textinput#autocomplete-android))

So.. what should we do here to fix this issue for web, iOS and Android?

**Comment by Harshdeepjoshi** [comment]
@allroundexperts yes it was a typing mistake

**Comment by allroundexperts** [comment]
> @allroundexperts @Harshdeepjoshi I'm really confused here.
> 
> `autoComplete="new-password"` works on web only. `autoComplete="password-new"` works for Android only. ([React native docs](https://reactnative.dev/docs/next/textinput#autocomplete-android))
> 
> So.. what should we do here to fix this issue for web, iOS and Android?
> 
> (@Harshdeepjoshi im sure you mean `autoComplete` and not `autoCompleteType`)

@rushatgabhane We can do a quick platform check to determine that.

**Comment by allroundexperts** [comment]
@rushatgabhane Updated my proposal to handle this.

**Comment by Harshdeepjoshi** [comment]
@rushatgabhane we can pass `textContentType` to `newPassword`

**Comment by rushatgabhane** [comment]
@allroundexperts it's highly recommended to post updated proposals as a new comment.

And we use [platform specific extensions](https://github.com/expensify/app#platform-specific-file-extensions) over in-line platform code.

@Harshdeepjoshi yeah, that could work! Please post an updated proposal, thank you!

**Comment by allroundexperts** [comment]
@rushatgabhane Apologies. Mine updated proposal is same as that of @Harshdeepjoshi.

**Comment by rushatgabhane** [comment]
@allroundexperts no worries :)

**Comment by Harshdeepjoshi** [comment]
@rushatgabhane please check my updated proposal, I have added the necessary changes.

**Comment by Harshdeepjoshi** [comment]
@rushatgabhane . Do you need anything else from me? I am new so any instructions would be helpful. Thank you.

**Comment by rushatgabhane** [comment]
@Harshdeepjoshi just one question - which autofill service have you used to verify your proposal?

**Comment by parasharrajat** [comment]
I used the browser autofill on firefox (No external password managers).

**Comment by Harshdeepjoshi** [comment]
@rushatgabhane I tested it on firefox and chrome.

**Comment by adelekennedy** [comment]
@Julesssss thoughts on [this proposal](https://github.com/Expensify/App/issues/9244#issuecomment-1147823806)

**Comment by Julesssss** [comment]
Sorry, missed this one. Approving @Harshdeepjoshi's proposal 👍

**Comment by adelekennedy** [comment]
@Harshdeepjoshi have you applied? I'd like to hire you!

**Comment by Julesssss** [comment]
Whoops, I see the PR now

**Comment by Julesssss** [comment]
Nice work on your first PR @Harshdeepjoshi! It has been merged, we now need to wait for it to be deployed. 7 days after that you should be paid

**Comment by adelekennedy** [comment]
not overdue - waiting for it to be deployed

**Comment by Julesssss** [comment]
Can be paid today

**Comment by adelekennedy** [comment]
Paid! @parasharrajat I missed hiring you for the reporting bonus, will you apply [here](https://www.upwork.com/jobs/~0145cd6a8ef3513ba9)

**Comment by parasharrajat** [comment]
@adelekennedy Please check I have already applied.

**Comment by adelekennedy** [comment]
hired!

**Comment by parasharrajat** [comment]
Thanks, there is also reporting bonus for this one :smiley:

**Comment by adelekennedy** [comment]
@parasharrajat to confirm are you eligible for more than the reporting bonus? I see that @rushatgabhane was assigned as the C+ and @Harshdeepjoshi was assigned as the contributor, am I missing something? Please let me know 😄

**Comment by parasharrajat** [comment]
oh, my bad. I confused this with someone else. So just for the reporting.

**Comment by adelekennedy** [comment]
Perfect - and no worries, you're juggling a ton of issues!
