### ISSUE TITLE
[HOLD for payment 2022-07-25] [$250] At additional details page the error messages aren't correct - reported by @thesahindia

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#9247]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click on Fab icon > send money > onfido verification > Additional details page
2. Add alphabet in SSN and phone number field
3. Try to submit the form
4. Check the error message for both fields, it says xyz is a required field.

## Expected Result:
When the input is incorrect the error message should be correct like, Please enter valid last 4 digits of SSN.

## Actual Result:
The error message says xyz is a required field.

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.69-0
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 
<img width="373" alt="Screenshot 2022-05-10 at 7 36 21 PM" src="https://user-images.githubusercontent.com/43995119/171096480-fe8e7773-f1e9-4a60-82aa-6f2b145bd6b9.png">

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @thesahindia
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1652192120750229

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by arielgreen** [comment]
https://www.upwork.com/jobs/~01b9c993db847143ab

**Comment by allroundexperts** [comment]
@mananjadhav What error to show if field is empty? Should we show the `field is required` in that case?

**Comment by mananjadhav** [comment]
@allroundexperts I feel showing `Please enter valid last 4 digits of SSN` should be okay in case of an empty field as well. At the other places like Personal Information, this is what we're showing for all the fields.

@AndrewGable can share his thoughts too.

**Comment by allroundexperts** [comment]
# Proposal

## Issue
The component `AdditionalDetailsStep` needs a prop `walletAdditionalDetails` with a list of error messages for each field. In our case, we're not passing in that prop. If the prop is not passed, then the default error is shown as seen following:
https://github.com/Expensify/app/blob/51fb61808d84f4aae4c6cbb3f6875d43d355fbb5/src/pages/EnablePayments/AdditionalDetailsStep.js#L144

## Solution
Pass the `walletAdditionalDetails` to the `AdditionalDetailsStep` with the correct error for the fields. The following changes from:

https://github.com/Expensify/app/blob/c10177b9ad6c370d746f866f44cd7c6b3cb2faa1/src/pages/EnablePayments/EnablePaymentsPage.js#L78

to:

```
{currentStep === CONST.WALLET.STEP.ADDITIONAL_DETAILS && (
                    <AdditionalDetailsStep
                        walletAdditionalDetails={{
                            errorFields: {
                                ssn: this.props.translate('bankAccount.error.ssnLast4'),
                                phoneNumber: this.props.translate('bankAccount.error.phoneNumber'),
                            },
                        }}
                        walletAdditionalDetailsDraft={this.props.walletAdditionalDetailsDraft}
                    />
                )}
```

**Comment by thesahindia** [comment]
### Proposal

We can create an object errorTranslationKeys like we have for other pages -

(it's just for example so not showing all the keys)
```js
    this.errorTranslationKeys = {
            legalFirstName: 'bankAccount.error.firstName',
            legalLastName: 'bankAccount.error.lastName',
            dob: 'bankAccount.error.dob',
            age: 'bankAccount.error.age',
}
```
on line 144 we just have to replace the code with `return this.props.translate(this.errorTranslationKeys[fieldName]);` to show different errors

https://github.com/Expensify/App/blob/50da22fa41944f42b7c36ba7a91f0ab737eb6cc6/src/pages/EnablePayments/AdditionalDetailsStep.js#L139-L144

I just found we aren't showing any error if the user isn't 18 so for that we can add another check here 
https://github.com/Expensify/App/blob/50da22fa41944f42b7c36ba7a91f0ab737eb6cc6/src/pages/EnablePayments/AdditionalDetailsStep.js#L157-L165
```js
        if (!ValidationUtils.meetsAgeRequirements(this.props.walletAdditionalDetailsDraft.dob)) {
            errors.age = true;
        }
```

we also have to add a specific key for age in `errorTranslationKeys`
and at line 333 we can just use `errorText={this.getErrorText('dob') || this.getErrorText('age')}`

https://github.com/Expensify/App/blob/50da22fa41944f42b7c36ba7a91f0ab737eb6cc6/src/pages/EnablePayments/AdditionalDetailsStep.js#L327-L333


The ssn field can change because in some cases we ask user to enter full 9 digits of the ssn instead of the last 4 digits, so we can use an error message that fits on both ex: "Please enter valid SSN digits" 
or we can use two different errors: 
1. "Please enter the valid last 4 digits of SSN"
2. "Please enter the full valid 9 digits of SSN 

If we decide to show two different error message then we have to add another key at errorTranslationKeys for different error message.

and we can add this check  -
```js
if (this.props.walletAdditionalDetails.shouldAskForFullSSN) {
            if (!ValidationUtils.isValidSSNFullNine(this.props.walletAdditionalDetailsDraft.ssn)) {
                errors.ssnFull9 = true;
            }
        } else if (!ValidationUtils.isValidSSNLastFour(this.props.walletAdditionalDetailsDraft.ssn)) {
            errors.ssn = true;
        }

```
and we just have to use `errorText={this.getErrorText('ssn') || this.getErrorText('ssnFull9')}` at line 341

https://github.com/Expensify/App/blob/50da22fa41944f42b7c36ba7a91f0ab737eb6cc6/src/pages/EnablePayments/AdditionalDetailsStep.js#L336-L341

**Comment by arielgreen** [comment]
@mananjadhav Can you review the above, please?

**Comment by mananjadhav** [comment]
@arielgreen  I have one question regarding this one, which I've asked in the C+ channel. Once I get the confirmation, I'll respond here. I hope that's fine.

**Comment by mananjadhav** [comment]
Sorry for the delay here, @allroundexperts looks good here. The `AdditionalDetailsStep` looks for this property for error messages and it isn't being passed at the moment. 

Let me know what you think @AndrewGable.

> New contributors are limited to working on one job at a time, however experienced contributors may work on numerous jobs simultaneously.

Also a quick note, @allroundexperts, as per the [contributing guidelines](https://github.com/Expensify/App/blob/main/CONTRIBUTING.md), you'll find the above statement. I can see of all issues assigned to you, all PRs are merged except https://github.com/Expensify/App/issues/9090. Would recommend to close that one first and only then work on this one. 

🎀 👀 🎀 C+ reviewed

**Comment by mananjadhav** [comment]
Hi @thesahindia , thanks for the comment. Let me check and get back to you.

**Comment by mananjadhav** [comment]
Sorry for the miss from my side. You're right @thesahindia. I also checked if there's any small change or refactor that can be done with `FormHelper` to be able to reuse the props, but doesn't seem like an option. Additionally it doesn't cover `SSN4` and `SSN9` case. Good catch.

@AndrewGable Apologies for the back and forth. It seems @thesahindia's proposal is better and covers all the cases. 

@allroundexperts Please check the previous comments to check the misses in our findings. 

🎀 👀 🎀 C+ reviewed

**Comment by thesahindia** [comment]
I have raised the PR only SSN case is left right now. I just wanted to confirm one thing before asking for the translation on slack.
We ask for 4 digits of SSN at additional details page but in some cases we change that field to ask for the full SSN, so should we add two different error message or should we use an error message that will fit on both?

**Comment by thesahindia** [comment]
Found another bug. The keyboard type is wrong for the phone number field, we should be using `CONST.KEYBOARD_TYPE.PHONE_PAD`. Should I report it on slack or fix it here as we can just increase the job compensation.
![Screenshot_1655732894](https://user-images.githubusercontent.com/83179295/174616015-188110b7-19c6-4830-9eea-5c557d4d0d7e.png)

**Comment by thesahindia** [comment]
>I am not sure if that would be treated a bug. @AndrewGable can confirm. Because I remember allowing brackets and hypens in the phone number

Ohh good point, in android phone-pad we can use bracket and hyphens but it will be a problem in ios and as we are already using phone-pad at two places so we will need to do something about it.

**Comment by thesahindia** [comment]
Posted about the error message [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1655749321017699).
@AndrewGable @mananjadhav, please share your thoughts on it. 

@AndrewGable I think we should ask marketing team for the confirmation (also we need the translation after we decide the error message) so can you tag them in the [thread](https://expensify.slack.com/archives/C01GTK53T8Q/p1655749321017699).

**Comment by mananjadhav** [comment]
Thanks for the ping @thesahindia. I also feel we should show different error messages, easier for the user to know what is to be fixed.

**Comment by thesahindia** [comment]
Cool. Now we just need the translation.
Asked [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1655908173483039?thread_ts=1655749321.017699&cid=C01GTK53T8Q).

**Comment by AndrewGable** [comment]
Bumped thread for translation

**Comment by thesahindia** [comment]
@mananjadhav, the PR is ready for the review now 🚀

**Comment by mananjadhav** [comment]
@thesahindia Sorry for the delay. I'll be reviewing and testing this tomorrow.

**Comment by arielgreen** [comment]
@mananjadhav @thesahindia Please check your Upwork inboxes

**Comment by thesahindia** [comment]
@arielgreen, the offer is no longer available. 
Apologies for the delay, can you please send the offer again?

**Comment by thesahindia** [comment]
> Found another bug. The keyboard type is wrong for the phone number field, we should be using `CONST.KEYBOARD_TYPE.PHONE_PAD`.

I started a discussion about this bug [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1656954797547719) and it seems like everyone agrees with changing the keyboard.

@AndrewGable, can I just fix this in the current PR as we can just increase the compensation and it will also save us some time.

**Comment by arielgreen** [comment]
@thesahindia sent

**Comment by arielgreen** [comment]
bump @AndrewGable please see @thesahindia 's question:

> @AndrewGable, can I just fix this in the current PR as we can just increase the compensation and it will also save us some time.

**Comment by arielgreen** [comment]
Paid.
