### ISSUE TITLE
[HOLD for payment 2022-06-23] [$250] Unnecessary focus on the Add payment method button - reported by @adeel0202

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#9248]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to Settings
2. Go to Payments
3. Click on the Add payment method button
4. Click anywhere on the Payments page

## Expected Result:
There is no focus on the Add payment method button

## Actual Result:
Add payment method button is focused/highlighted

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Mobile Web (Safari)

**Version Number:** 1.1.69-0
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 

https://user-images.githubusercontent.com/43995119/171098102-3dc15edb-ba8d-49d3-819d-85f09ecc43ff.mov

**Expensify/Expensify Issue URL:**  
potentially related to https://github.com/Expensify/App/issues/8934 

**Issue reported by:** @adeel0202
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1652632605348319

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by michaelhaxhiu** [comment]
Adding Kadie back, as she is supposed to remain assigned per the `External` label

**Comment by kadiealexander** [comment]
Thanks Hax! Got this bad boy ready for proposals:

https://www.upwork.com/jobs/~01d69478401a6b35a0
https://www.upwork.com/ab/applicants/1532483667671990272/job-details

**Comment by allroundexperts** [comment]
# Proposal

## Issue
The css selector `:focus-visible` is responsible for showing up the outline. When the selector `:focus-visible` is applied to an element is largely dependent browser implementation. As always, the problematic browser is Safari. Safari restores focus on an element even if an event is a `click`. On Chrome and other browser, focus is restored if event type is `keypress` ie closing modal by keyboard.

## Solution
Whenever a button is clicked, we can trigger an `blur` on the element IF the `event` type is a `click`.

The following changes:

https://github.com/allroundexperts/Expensify/blob/3e0ba3a74cfa67c747a26e0f2547030ebd2714ad/src/components/Button.js#L231

To

```
onPress={(e) => {
                    if (e.type === 'click') {
                        e.currentTarget.blur();
                    }
```

## Result

https://user-images.githubusercontent.com/30054992/171935670-42737e6f-02f4-4fbd-860a-16ad9e8413e9.mp4

**Comment by rushatgabhane** [comment]
@allroundexperts can we also fix the blue line in the bottom of payment list?
<img width="391" alt="image" src="https://user-images.githubusercontent.com/29673073/172079927-77488a5b-7c90-4893-a312-690b93c50af6.png">

**Comment by allroundexperts** [comment]
@rushatgabhane Updated proposal.

**Comment by rushatgabhane** [comment]
@thienlnam I like @allroundexperts's [proposal](https://github.com/Expensify/App/issues/9248#issuecomment-1146290970).

 🎀 👀 🎀 C+ reviewed

**Comment by allroundexperts** [comment]
@thienlnam It doesn't effect keyboard. As mentioned in the proposal, the blur happens on mouse click only.

**Comment by thienlnam** [comment]
👍 We can move forward with this proposal, @rushatgabhane when you're testing, can you please make sure to check that the user can navigate through menus and buttons by clicking and then using keyboard shortcuts and vice versa?

**Comment by allroundexperts** [comment]
@thienlnam Applied.

**Comment by kadiealexander** [comment]
@allroundexperts Hired on Upwork!

**Comment by allroundexperts** [comment]
@rushatgabhane created PR.
https://github.com/Expensify/App/pull/9348

**Comment by kadiealexander** [comment]
Assigning to @jliexpensify to facilitate payment as the 23rd is a public holiday in NZ.

**Comment by jliexpensify** [comment]
No regressions, paying @adeel0202 , @allroundexperts and @rushatgabhane $250 each today.

**Comment by jliexpensify** [comment]
@adeel0202 - having issues finding you in Upworks, can you link your profile please?

**Comment by adeel0202** [comment]
@jliexpensify here is my Upwork profile: https://www.upwork.com/freelancers/~01d53b0b1ad52f0ef7

**Comment by jliexpensify** [comment]
@adeel0202 - invited, cheers! I'll pay once you accept.

**Comment by jliexpensify** [comment]
Everyone has been paid!
