### ISSUE TITLE
Padding seems off for the latest message with the typing indicator moved to the top

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#9251]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open any chat 
2. check padding below last chat and compose box 

## Expected Result:
We should have the metadata above and below the compose box as before and make sure it is vertically aligned. Decided in Slack [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1654097698880649?thread_ts=1653937814.767159&cid=C01GTK53T8Q).
 
## Actual Result:
Padding seems too high for the latest message with the typing indicator moved to the top

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Web

**Version Number:** 1.1.69-2
**Reproducible in staging?:** Y 
**Reproducible in production?:** N 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 

![image](https://user-images.githubusercontent.com/36083550/171138113-2b000a44-2405-4976-aa13-cda915ed227a.png)

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @AndrewGable 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1653937814767159

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mountiny** [comment]
I could find that this is related to two PRs recently 
- first this: https://github.com/Expensify/App/pull/9095 cc @tgolen was ooo for a while
- then https://github.com/Expensify/App/pull/9206 cc @amyevans 

I dont think this needs to be a deploy blocker since it is mainly a small styling problem.

**Comment by mountiny** [comment]
Making this weekly for now, we need to find some consensus on what would be the best way to render these.

**Comment by mountiny** [comment]
Asked in Slack [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1654097698880649?thread_ts=1653937814.767159&cid=C01GTK53T8Q), giving it some time.
