### ISSUE TITLE
[$4000] Android - Edit message - keyboard is dismissed after selecting an emoji @Tushu17

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#9252]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action steps: 
1. Send a message in any chat in App
2. Long press the message and tap on `Edit message` 
3. Tap on the emoji picker
4. Select an emoji and observe the keyboard is dismissed

## Expected results:
The alphabetical keyboard should not be dismissed after selecting an emoji

## Actual Result:
Keyboard doesn't open up after selecting emoji.

## Workaround:
Unknown 

## Platform:

Where is this issue occurring?

- Android

**Version Number:** 1.1.69.2

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/171174709-69b79478-f54a-4c55-b84b-114f7ec51087.mp4

**Upwork URL:** https://www.upwork.com/jobs/~01f30fad98ca9b6c69

**Issue reported by:** @Tushu17

**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1650039236885699

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

## Upwork Automation - Do Not Edit
- Upwork Job URL: https://www.upwork.com/jobs/~018e351e7d34632075
- Upwork Job ID: 1599837238530191360

**Comment by trjExpensify** [comment]
👋 @kbecciv @Tushu17, it took me a second to figure this out based on the steps provided and the issue title. Do you think it's more accurately described as:

Title: _Android - Edit message - keyboard is dismissed after selecting an emoji_

Action steps: 
1. Send a message in any chat in App
2. Long press the message and tap on `Edit message` 
3. Tap on the emoji picker
4. Select an emoji and observe the keyboard is dismissed

Expected results:
The alphabetical keyboard should not be dismissed after selecting an emoji

Let me know and we can update this for clarity.

**Comment by trjExpensify** [comment]
Cool, updated. Ready for engineering triage!

**Comment by trjExpensify** [comment]
Isn't it always open prior when editing? 🤔

**Comment by Julesssss** [comment]
Not if the user manually closes the keyboard. I do this when writing a long message so i can review the full message in a single screen. 

Though rare, I would be annoyed if I finished writing a message, closed the keyboard, added an emoji and then saw the keyboard pop up again. Especially because it's super laggy.

**Comment by Tushu17** [comment]
Hey @Julesssss, The behaviour is also inconsistent. The keyboard opens after selecting the emoji at composer.

https://user-images.githubusercontent.com/89839952/173139625-60c1c741-53b7-4d55-b610-2c93d0242f41.mov

.

**Comment by Julesssss** [comment]
Thanks, @Tushu17. 

@trjExpensify this is the case which I believe should be excluded: 

https://user-images.githubusercontent.com/10736861/173361430-d66f93e4-077c-417a-809e-a187e1795f88.mp4

**Comment by trjExpensify** [comment]
^^ Ah right yes, but that's not in edit mode is it?

**Comment by trjExpensify** [comment]
Okay cool, I see what you're saying. Let's do it. 👍

**Comment by Julesssss** [comment]
Awaiting proposals

**Comment by trjExpensify** [comment]
Upwork job here: https://www.upwork.com/jobs/~01f30fad98ca9b6c69

**Comment by parasharrajat** [comment]
This used to work.

**Comment by asfandyarsheikh** [comment]
Saw this on upwork. Is it good design practice to open a separate bottom sheet for emojis? Why not use a custom keyboard that allows emoji input via separate tab? Something like this https://wix.github.io/react-native-ui-lib/docs/components/keyboard/KeyboardAccessoryView

**Comment by yashwant-dangi** [comment]
**Proposal**

For the _EmojiPickerButton_ component, _onModalHide_ callback if we add a timeout of around 50-100 ms in the Interaction Manager then this issue can be resolved. 

https://github.com/software-mansion/react-native-screens/issues/89#issuecomment-514935753


https://user-images.githubusercontent.com/43725028/173767631-25bdc0cc-9202-47d6-b41a-81bab7fc1b3d.mp4

**Comment by Julesssss** [comment]
Still awaiting proposals. @trjExpensify can you please double the job price? (I assume we double in UpWork as well as just updating the issue title?)

**Comment by trjExpensify** [comment]
Yep, done! https://www.upwork.com/jobs/~01f30fad98ca9b6c69

**Comment by trjExpensify** [comment]
Not overdue, Melv. Awaiting proposals.

**Comment by Julesssss** [comment]
@trjExpensify please double again

**Comment by trjExpensify** [comment]
Donezo: https://www.upwork.com/jobs/~01f30fad98ca9b6c69

**Comment by mdneyazahmad** [comment]
## Proposal

There existed the same issue on composer and is fixed by a workaround with `setTimeout` by this [PR](https://github.com/Expensify/App/pull/3392).

https://github.com/Expensify/App/blob/d7dc3eea13bdb2af3e606530dc42058ca0a291ee/src/pages/home/report/ReportActionCompose.js#L334-L352

https://github.com/Expensify/App/blob/d7dc3eea13bdb2af3e606530dc42058ca0a291ee/src/pages/home/report/ReportActionCompose.js#L638-L642

---

Maybe it has been missed there. My proposal is to do the same thing on edit composer. The only reason I propose is because we already have deployed the same workaround.

https://github.com/Expensify/App/blob/d7dc3eea13bdb2af3e606530dc42058ca0a291ee/src/pages/home/report/ReportActionItemMessageEdit.js#L227-L231

**Comment by parasharrajat** [comment]
Ok, I see. Although we have adopted a workaround previously, it does not mean that we should do that always. 

> Let me know whether this proposal is accepted or I think we should also find a solution to the previously deployed workaround.

Yeah, try to find the solution to the real problem of why the keyboard is not opening? Let's see some root cause analysis.

FYI @mdneyazahmad your proposal matches with https://github.com/Expensify/App/issues/9252#issuecomment-1156088875 .

**Comment by trjExpensify** [comment]
Any further ideas here @mdneyazahmad?

**Comment by Julesssss** [comment]
Not overdue

**Comment by trjExpensify** [comment]
Doubled on upwork: https://www.upwork.com/jobs/~01f30fad98ca9b6c69

**Comment by aneequeahmad** [comment]
### Proposal

**Problem:**
- Root cause of the issue is in file https://github.com/Expensify/App/blob/c2ecea533a3805bbe547b48d61baa8c24a1f89ef/src/pages/home/report/ReportActionItemMessageEdit.js#L215-L222
- Whenever  `onBlur of Composer` in `ReportActionItemMessageEdit.js` is triggered with first argument as `true` https://github.com/Expensify/App/blob/c2ecea533a3805bbe547b48d61baa8c24a1f89ef/src/pages/home/report/ReportActionItemMessageEdit.js#L221
which causes to show `compose input` https://github.com/Expensify/App/blob/4d15590c44fe8bb3f2ab50a3f8e24c0e859e1b8b/src/libs/toggleReportActionComposeView/index.js#L3-L9

**Solution:**
Setting `false` instead of `true` here `   toggleReportActionComposeView(false, VirtualKeyboard.shouldAssumeIsOpen());` fixes the issue

- _**Attached video after the fix**_

https://user-images.githubusercontent.com/36359331/179383445-05ea0698-b56b-4cf4-b357-ba7205d3c2a5.mov

**Comment by parasharrajat** [comment]
What is the affect of this change @aneequeahmad?

**Comment by aneequeahmad** [comment]
@parasharrajat Effect of setting the first argument to `false` in `toggleReportActionComposeView(false, VirtualKeyboard.shouldAssumeIsOpen())`

- 'true' is used to show the ComposeInput and `onBlur` as on every interaction(like clicking outside the `EditComposeInput`) `onBlur` is triggered and causing the the ComposeInput to show and even focuses ComposeInput if it has draft message. 

- We don't need to show `ComposeInput onBlur` as showing it is already handled when `cancel or save changes` button are pressed. 

Also, as you mentioned above this used to work. You're right this used to work before `18th May 2022` and these changes were added by this [PR](https://github.com/Expensify/App/pull/9060/files#:~:text=onBlur%3D%7B,%7D%7D) in this [commit](https://github.com/Expensify/App/pull/9060/commits/06386dbceb2b20b91bfa38cd44ccb6dfbb7110a2)

**Comment by trjExpensify** [comment]
@parasharrajat @Julesssss are we good with this proposal, what's the next step?

**Comment by parasharrajat** [comment]
I got the update on the previous changes and we do want to enable the composer on blur on the edit box. So [proposal](https://github.com/Expensify/App/issues/9252#issuecomment-1186391894) is not valid.

**Comment by aneequeahmad** [comment]
@parasharrajat Oh alright i didn't know that [this](https://github.com/Expensify/App/issues/9252#:~:text=we%20do%20want%20to%20enable%20the%20composer%20to%20blur%20on%20the%20edit%20box) is a feature and we want to enable the composer to blur

Updated proposal### 

**Problem**

- We need to not run  `toggleReportActionComposeView(true, VirtualKeyboard.shouldAssumeIsOpen());` on blur as another button having action (`opening emojiPicker`) is clicked like `save and cancel`

Solution: 

- Define an `ID` in constructor after `line#76` in `EmojiPickerButton` as `this.emojiButtonID = 'emojiButton';`
https://github.com/Expensify/App/blob/c2ecea533a3805bbe547b48d61baa8c24a1f89ef/src/pages/home/report/ReportActionItemMessageEdit.js#L75-L77

- Pass ID as prop in `EmojiPickerButton` as `nativeID={this.emojiButtonID}` here

https://github.com/Expensify/App/blob/c2ecea533a3805bbe547b48d61baa8c24a1f89ef/src/pages/home/report/ReportActionItemMessageEdit.js#L229-L231

- Assign nativeID from props to `Pressable` in `EmojiPickerButton`
https://github.com/Expensify/App/blob/66a05aa4015f96f5bab59929698d517a616620d1/src/components/EmojiPicker/EmojiPickerButton.js#L27-L34

- Return from `onBlur` to prevent re-render when `emoji button` is pressed which cancels the onPress event by re-rendering. `if (_.contains([this.saveButtonID, this.cancelButtonID, this.emojiButtonID]...`
https://github.com/Expensify/App/blob/c2ecea533a3805bbe547b48d61baa8c24a1f89ef/src/pages/home/report/ReportActionItemMessageEdit.js#L216-L218

**Comment by trjExpensify** [comment]
@parasharrajat thoughts on the above?

**Comment by aneequeahmad** [comment]
@marcaaron This is the relevant [issue](https://github.com/Expensify/App/pull/9060#:~:text=have%20to%20a-,relevant%20issue.,-Reply...). I came to know that 
- we do want to enable the composer to blur on the edit box. Blur can be triggered via clicking on Save or Cancel buttons as well as a normal blur on the EditBox.

So i think to solve this keyboard dismiss issue on `EmojiPicker` we have to stop the method to toggle the composer (`toggleReportActionComposeView`) as it is preventing the users to take actions like we have done for `save` and `cancel` buttons. 

cc: @parasharrajat

**Comment by parasharrajat** [comment]
Testing the proposal in a few hours.

**Comment by parasharrajat** [comment]
How will this proposal solve the issue on Android @aneequeahmad?

**Comment by aneequeahmad** [comment]
@parasharrajat when i debugged the issue pressing the `emojiPicker` button wasn't doing any action. But now it is opening the emojiPicker on latest build `1.1.87-6` so The above proposal is not valid. 

### PROPOSAL

We only need to add  `InteractionManager.runAfterInteractions(() => setTimeout(() => this.textInput.focus(), 100))` here `onModalHide`.

https://github.com/Expensify/App/blob/d6417564acf9d34bad12231dcbc228fcb5c67f98/src/pages/home/report/ReportActionItemMessageEdit.js#L218-L221

**AFTER FIX**

https://user-images.githubusercontent.com/36359331/182445232-aaa5ba38-e6c8-4c52-9f09-4b2d87aeceb3.mp4

**Comment by parasharrajat** [comment]
A similar proposal exists.

**Comment by aneequeahmad** [comment]
@parasharrajat Actually the next time i test again code base has changed like previously pressing the emojiPicker wasn't doing any action and now in latest build it is opening the `emojiPicker` but setTimeout was to be added as this is a known problem discussed [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1658026341800479). 

I'll take care next time keeping in mind what you said. apologies and thanks for your valuable feedback.

**Comment by Julesssss** [comment]
@trjExpensify could we please double, given that we're still seeking proposals.

**Comment by trjExpensify** [comment]
👋 back from OoO, doubled [here](https://www.upwork.com/jobs/~01f30fad98ca9b6c69).

**Comment by mollfpr** [comment]
### Proposal

There are couples of root cause explained by other's and the issue only happen on Android. Also, we encountered the same issue on `ReportActionCompose` and fix with adding a timeout before focusing the input and that's not acceptable in this issue.

So I try replacing `InteractionManager.runAfterInteractions` when `onModalHide` is called with `requestAnimationFrame`. Turns out this `requestAnimationFrame` is called after `InteractionManager.runAfterInteractions` and makes the keyboard appear when we hide the modal. I think it's because `requestAnimationFrame` will fire after all the frames have been flushed.

I also try the changes on `ReportActionCompose` and works as expected. So probably we can eliminate the `setTimeout` implementation on focusing input.

https://github.com/Expensify/App/blob/22e39f9de1c1fbace6e7a0e4c06f364310129895/src/pages/home/report/ReportActionItemMessageEdit.js#L223
```diff
-  onModalHide={() => InteractionManager.runAfterInteractions(() => this.textInput.focus())}
+  onModalHide={() => requestAnimationFrame(() => this.textInput.focus())}
```

### Result
#### Android

https://user-images.githubusercontent.com/25520267/185793028-3e3b5ec8-73d2-47c4-8e99-8eb4054209d2.mp4

#### iOS

https://user-images.githubusercontent.com/25520267/185793127-4feb627d-0555-4df0-b5de-f2b1d420d3c3.mov

#### mWeb

https://user-images.githubusercontent.com/25520267/185793319-4bacce53-07b8-4861-b7bf-badb9231ceef.mp4

**Comment by trjExpensify** [comment]
Not overdue, awaiting proposals.

**Comment by Julesssss** [comment]
Not overdue, we're still awaiting proposals here.

**Comment by Julesssss** [comment]
Still awaiting proposals here.

**Comment by trjExpensify** [comment]
Still awaiting proposals here?

**Comment by Julesssss** [comment]
Yep

**Comment by Julesssss** [comment]
@trjExpensify please hold on any further pay increases for the moment though.

**Comment by mallenexpensify** [comment]
Per[ this internal conversation](https://expensify.slack.com/archives/C02NK2DQWUX/p1661419792053769), putting this keyboard-related issue on hold pending https://github.com/Expensify/App/issues/10273

I updated title and removed `Help Wanted`

**Comment by Julesssss** [comment]
No further proposals received.

**Comment by mallenexpensify** [comment]
It's on HOLD for now @Julesssss, pending https://github.com/Expensify/App/issues/10273
Not sure why this was a Daily, bumped to Weekly for now

**Comment by trjExpensify** [comment]
Can we put this on `Monthly` then and mark it as `Internal` if we're scoping a solution internally?

**Comment by Julesssss** [comment]
Still on hold, see [this](https://github.com/Expensify/App/issues/9252#issuecomment-1244720271) message.

**Comment by Julesssss** [comment]
No change from [the last](https://github.com/Expensify/App/issues/9252#issuecomment-1291828838) update.

**Comment by trjExpensify** [comment]
👋 Isn't #10273 largely complete now, why is this still held? Could it be even fixed on Android, perhaps?

CC: @JmillsExpensify, I don't think this one is on your radar as the BZ on the KeyboardAvoidingView initiative.

**Comment by Julesssss** [comment]
Given that the Keyboard changes now seem unlikely to resolve this, let's open it up for solutions again

**Comment by trjExpensify** [comment]
Yeah, I agree with that. 👍

**Comment by JmillsExpensify** [comment]
Thanks @trjExpensify Feel free to keep it, though I'll subscribe and participate.

**Comment by trjExpensify** [comment]
Cool, thanks for confirming. Added the `External` label afresh!

**Comment by Tushu17** [comment]
### proposal 
We can create a function to use `setTimeOut` in `ReportActionItemMessageEdit` file.

```
focus(shouldelay = false) {
        InteractionManager.runAfterInteractions(() => {
            if (!this.textInput) {
                return;
            }

            if (!shouldelay) {
                this.textInput.focus();
            } else {
                setTimeout(() => this.textInput.focus(), 100);
            }
        });
    }
```
we can pass that function to `onModalHide` prop of `EmojiPickerButton` as `true`.
https://github.com/Expensify/App/blob/98354545cc89b75a53f07cb1d694f7ab78ffbb40/src/pages/home/report/ReportActionItemMessageEdit.js#L252
`onModalHide={() => this.focus(true)}`.

**Comment by parasharrajat** [comment]
@Julesssss Are we expecting a setTimeout-based solution as a fix to this issue? 

If not, https://github.com/Expensify/App/issues/9252#issuecomment-1223036462. 

@Tushu17 being an experienced contributor, we expect our process to be followed. And the process says that a proposal should not match existing ones and contributors should go over the whole issue discussion before proposing a solution. As the proposal matches existing ones, it is rejected.

**Comment by Julesssss** [comment]
> Are we expecting a setTimeout-based solution as a fix to this issue?

Only if it can't be avoided.

**Comment by devpenzil** [comment]
jh

**Comment by trjExpensify** [comment]
Thread we're discussing next steps on this one is [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1670271699383879) for the breadcrumbs!

**Comment by JmillsExpensify** [comment]
Floated with Margelo so removed the `External` and `Help Wanted` labels for now.

**Comment by fedirjh** [comment]
@parasharrajat this is a known issue from RN from a long time https://github.com/facebook/react-native/issues/19366 , it was mentioned in their docs as well [Known issues](https://reactnative.dev/docs/textinput#isfocused)

This may explain the mystery :
>We can see then that a ShadowNode exists with a view, and a parent shadow node, but the view doesn't have a parent. This means for the <View> we try to focus in React has had a corresponding native UIElement created, but the element hasn't been connected to the app's visual tree.
>
> So we cannot focus the component, because the UIElement hasn't been attached to the window's view tree yet.

This thread https://github.com/microsoft/react-native-windows/issues/9292 can answer the mystery behind this issue , and it provide a solution https://github.com/microsoft/react-native-windows/issues/9292#issuecomment-1038218769

> I think the queue-based solution is a good one. If a focus request comes in, on something not yet connected, we buffer subsequent UIManager focus/blur requests until the next is available. That would preserve app-side focus state correctly, as well.

@Julesssss  it Looks like setTimeout-based solution can't be avoided

**Comment by hannojg** [comment]
I can imagine that my PR https://github.com/Expensify/App/pull/11684 fixes this issue. In my testing the keyboard always reopens after selecting an emoji. Maybe someone can take the time to try to reproduce the issue on the branch? 😊

**Comment by Julesssss** [comment]
Cool, thanks all. We'll hold this one briefly until the [linked PR](https://github.com/Expensify/App/pull/11684) is merged. We also have the option of the setTimeout solution as a workaround to revisit if that doesn't work.

**Comment by trjExpensify** [comment]
Well, that would be marvellous! Fortuitously @parasharrajat, you're the C+ on it as well! 🎉 

@Julesssss I'm updating to include the hold reason in the title, let's always remember to do that for ease of following.

**Comment by trjExpensify** [comment]
Still on hold for that PR. @parasharrajat are you back on that to test this week?

**Comment by JmillsExpensify** [comment]
@parasharrajat Are you still blocked from testing?

**Comment by trjExpensify** [comment]
Latest from the linked PR this is held on is that it will be tested today.

**Comment by trjExpensify** [comment]
PR this is on hold for is [still in review](https://github.com/Expensify/App/pull/11684).

**Comment by trjExpensify** [comment]
No change, Melv.

**Comment by trjExpensify** [comment]
Still in review. Awaiting a merge to main to re-test!

**Comment by trjExpensify** [comment]
Still held!

**Comment by trjExpensify** [comment]
No movement on the PR we're held on [here](https://github.com/Expensify/App/pull/11684#issuecomment-1443726606).

**Comment by Julesssss** [comment]
No change. We're still held

**Comment by trjExpensify** [comment]
No change.

**Comment by trjExpensify** [comment]
@Julesssss @parasharrajat the PR linked to has been closed, so what's the revised plan here?

**Comment by Julesssss** [comment]
Here's the issue we're holding on: https://github.com/Expensify/App/issues/18444

**Comment by Julesssss** [comment]
> Does the scope of this issue also include this? Just wanted to confirm this.

Yeah, I think so.

**Comment by trjExpensify** [comment]
Still in a holding pattern, though looks like we're getting close!

**Comment by trjExpensify** [comment]
Sounds good!

**Comment by Julesssss** [comment]
Still holding on the fork death

**Comment by Julesssss** [comment]
Gonna drop to weekly while it's held

**Comment by trjExpensify** [comment]
No change.

**Comment by trjExpensify** [comment]
Samesies!

**Comment by Julesssss** [comment]
Getting closer [here](https://github.com/Expensify/App/issues/13922), but still held

**Comment by trjExpensify** [comment]
PR is getting close!

**Comment by trjExpensify** [comment]
👋 can someone summarise the next steps here and what we're doing about that now? Thanks!

**Comment by trjExpensify** [comment]
@parasharrajat where you at on the continuation?

**Comment by trjExpensify** [comment]
Done!

**Comment by Julesssss** [comment]
Oh god, yeah we definitely shouldn't auto-focus the emoji search. It slows down the interaction time and reduces the available space by showing the soft keyboard.

**Comment by trjExpensify** [comment]
I think the emoji search is expected to be focused, as it is on web/desktop. If we want to deviate from that, I suggest that's a new issue and a discussion in Slack. 

As for this issue on the keyboard being dismissed after selecting an emoji, it seems like we're resolved here. Is that correct?

**Comment by Julesssss** [comment]
If it's expected on web/desktop (which I agree with), then this is a good example of a place in which all platforms should NOT align. 

We currently do this when opening a chat because automatically showing the soft keyboard on mobile is slow and annoying as it covers ~40% of the vertical page height. We shouldn't do this for emoji's either.

**Comment by Julesssss** [comment]
But I'm happy to raise that elsewhere. And yes, the original issue here is now resolved 🎉

**Comment by trjExpensify** [comment]
Yeah, I think that's just out of scope on this issue and needs to be taken some place else. 

So here, we just need to pay @Tushu17 $250 for the OG bug report.

**Comment by trjExpensify** [comment]
@Julesssss a good place to start: https://github.com/Expensify/App/issues/27047

**Comment by Julesssss** [comment]
> @Julesssss a good place to start: #27047

Thanks, I'm handling the revert [here](https://github.com/Expensify/App/issues/28228).

**Comment by Julesssss** [comment]
Oh of course. Good spot!

**Comment by Tushu17** [comment]
> So here, we just need to pay @Tushu17 $250 for the OG bug report.

Thank you @trjExpensify, offer accepted.

**Comment by trjExpensify** [comment]
Perfect, paid!

**Comment by trjExpensify** [comment]
So what are the next steps and who's doing those?

**Comment by Julesssss** [comment]
We're back to seeking proposals. [Latest comment](https://github.com/Expensify/App/issues/9252#issuecomment-1724214952)

**Comment by trjExpensify** [comment]
This issue is a bit of a spider web, IMO. Should we open a new issue with whatever relevant summary on where we are at, what we don't want to entertain, and then we'll add `help wanted` and `external` to that to seek proposals a fresh. At this point, I'm concerned nobody is going to catch up on 300+ comments and a bunch of linked issues to suggest a proposal here.

**Comment by trjExpensify** [comment]
Yes, we keep the assignees and bounty the same but the issue is summarised with what we will accept/not accept in the expected results and any relevant TL;DR of the history that we landed on there.

**Comment by getusha** [comment]
> Yes, we keep the assignees and bounty the same but the issue is summarised with what we will accept/not accept in the expected results and any relevant TL;DR of the history that we landed on there.

I started investigating this issue and to read and understand what's the ideal proposal and know what kind of proposals posted takes a lot of time this will be very helpful.

**Comment by trjExpensify** [comment]
So @parasharrajat is that something you will summarise for where we're at this far?
