### ISSUE TITLE
IOS/Android - Attachment - Endless spinner is displayed before uploading to the conversation instead preview

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#9290]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch App and login with HIGH TRAFFIC account
2. Go to any conversation
3. Tap plus and select 'Add attachment" > 'Choose from gallery"
4. Select any photo

## Expected Result:
Verify a preview of the image is displayed before uploading to the conversation.

## Actual Result:
Endless spinner is displayed before uploading to the conversation instead preview

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- iOS
- Android

**Version Number:** 1.1.70.2

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** applausetester+fish@applause.expensifail.com/Qwerty123

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

![IMG_80B84DB2A520-1](https://user-images.githubusercontent.com/93399543/171638186-4870105f-59e4-45c2-9c7a-8d9ed3d74152.jpeg)

https://user-images.githubusercontent.com/93399543/171638188-a1aeede0-9362-4e05-a646-e1702a862665.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by amyevans** [comment]
I logged into the affected account and attempted to reproduce but was unable:

https://user-images.githubusercontent.com/7277067/171915178-d00ff5b4-ce26-459c-be05-857efb8bb08b.mov

@kbecciv could you test again and see what outcome you get?

**Comment by kbecciv** [comment]
@amyevans Issue have been reproduced only on IOS and Android apps.  Please attach the video in Android app.

https://user-images.githubusercontent.com/93399543/172025139-add12bf9-68a0-4fa7-8254-fa9dc24d89f2.mp4

**Comment by amyevans** [comment]
Was able to reproduce when trying again today

**Comment by amyevans** [comment]
Located the root of the issue Friday and after some local emulator troubles was able to get proper screen recordings to demonstrate the fix today. PR is up for review.
