### ISSUE TITLE
When the compose box expands, it moves down

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#9305]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open chat 
2. Type multiline message

## Expected Result:
Compose box should stay bottom-anchored at its current position and grow from the top.

## Actual Result:
When the compose box expands, it moves down

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.71-1
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 
![compose](https://user-images.githubusercontent.com/43995119/171784190-6abb9cdc-4d41-49c0-a404-61e4db4b4704.gif)

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @shawnborton 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1654067502956959

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by iwiznia** [comment]
I think the actual problem is that it is not initially docked to the bottom, right @shawnborton? Like that extra space below the box should not exist, right?
<img width="1065" alt="image" src="https://user-images.githubusercontent.com/521248/171930121-e897d8d2-a842-4bb4-920f-ac6e9e646b57.png">

**Comment by shawnborton** [comment]
This might be related to the fact that we removed the "XXXX is typing..." from below the compose input. Maybe this is just a weird flexbox thing happening since that space is now dead, and it now shrinks when the content above it grows. So perhaps when we revert the whole typing indicator fiasco this will self-resolve?

**Comment by Beamanator** [comment]
@iwiznia did you mean to unassign @JmillsExpensify ? 😅

**Comment by iwiznia** [comment]
Oh no, sorry about that.. Reassigning

**Comment by JmillsExpensify** [comment]
>So perhaps when we revert the whole typing indicator fiasco this will self-resolve?

I think we've already done this, or are in the process of doing this right? cc @vitHoracek I think you were helping with the reversion. If so, I think we should just close this issue.
