### ISSUE TITLE
[$250] When requesting money, you get an error on the IOS app - reported by @Puneet-here

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#9307]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click on :green-plus-button: and choose request money
2. Add amount>Press Next> Select a user

## Expected Result:
You shouldn't be getting any error

## Actual Result:
You get an error

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- iOS

**Version Number:** 1.1.63-0
**Reproducible in staging?:** N (Repro on Dev)
**Reproducible in production?:** N 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 
<img width="338" alt="Screenshot 2022-05-18 at 10 41 13 PM" src="https://user-images.githubusercontent.com/43995119/171787806-c79e2239-dc5d-4ddb-80f2-dafbdc6b3b0e.png">

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @Puneet-here
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1652893905090579

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Gonals** [comment]
This seems to be a client issue. Marking as external

**Comment by JosueEchandiaAsto** [comment]
Hi, I'm fix it. 
In IOUConfirmationList: 357, display a OptionsList inside a ScrollView.
![Captura de Pantalla 2022-06-09 a la(s) 15 41 48](https://user-images.githubusercontent.com/16966456/172940630-6e15295a-8bc3-4377-96ef-3e601171235d.png)
I have the solution working correctly
![Simulator Screen Shot - iPhone 11 Pro - 2022-06-09 at 15 36 42](https://user-images.githubusercontent.com/16966456/172940859-397de229-9c18-4250-ad8c-61f56bd3a469.png)

**Comment by mananjadhav** [comment]
@JosueEchandiaAsto Thanks for the comment and the proposal. Yeah, it looks like it's the nested scroll view issue. Quick question, were you able to check to replace `ScrollView` with just `View` doesn't cause anything to break on other platforms?  also because we're removing some styles?

**Comment by JosueEchandiaAsto** [comment]
@mananjadhav, My mistake. Only "styles.flexRow" will be added. So that there are no visual changes.
Replacing ScrollView with View has no effect on platforms.

https://github.com/JosueEchandiaAsto/App/commit/aababd3d40952e6d85966b1a40ef6bbfc15c55a9

**Comment by mananjadhav** [comment]
@JosueEchandiaAsto  Thank you for the comment. Your proposal looks good.

cc - @neil-marcellini 

🎀 👀 🎀 
C+ reviewed

**Comment by neil-marcellini** [comment]
@JosueEchandiaAsto I think you have the right solution of simply replacing the `ScrollView` with a `View`, but I would prefer that you leave the styles as they are. If there is a good reason to change the style, please explain why and show us how it will look on all platforms with screenshots or recordings. I'll let you decide what to do in your PR.

You're hired for this issue! Please put up a PR and we will review it.

**Comment by JosueEchandiaAsto** [comment]
@neil-marcellini I'll explain.

### Simply replacing the ScrollView with a View

**Web**
<img width="1203" alt="Captura de Pantalla 2022-06-11 a la(s) 14 38 46" src="https://user-images.githubusercontent.com/16966456/173202636-83c47ebc-1e6e-41c6-8623-47a35f88edc5.png">

**Desktop**
<img width="1203" alt="Captura de Pantalla 2022-06-10 a la(s) 20 20 22" src="https://user-images.githubusercontent.com/16966456/173202644-73efd192-6b4b-4dbb-b0ab-d911b8d08590.png">

**Android**
<img height="641" alt="Screenshot_1654976468" src="https://user-images.githubusercontent.com/16966456/173202662-4c25ca8c-a74a-4e50-a58a-8d9f6d415fb8.png">

**iOS**
<img height="641" alt="Simulator Screen Shot - iPhone 13 - 2022-06-11 at 15 07 24" src="https://user-images.githubusercontent.com/16966456/173203306-ca723e9f-5066-4354-9fe1-6d716b60f55a.png">

Web and desktop look same, but in Android and iOS disappear OptionsList.
Overriding ScrollView loses auto-fit by content. So it is necessary to add a style to cover this case. After much analysis, the best option is flexRow.

### "styles.flexRow" added

**Web**
<img width="1203" alt="Captura de Pantalla 2022-06-11 a la(s) 15 13 03" src="https://user-images.githubusercontent.com/16966456/173203444-c20d78d4-0e31-497b-b345-73dc2d379385.png">

**Desktop**
<img width="1203" alt="Captura de Pantalla 2022-06-11 a la(s) 15 14 31" src="https://user-images.githubusercontent.com/16966456/173203475-7c25417f-ac2d-4a7a-9356-35d26c56a31f.png">


**Android**
<img height="641" alt="Screenshot_1654976468" src="https://user-images.githubusercontent.com/16966456/173203396-36486f05-d0bc-48ad-ab38-27dcfd382061.png">

**iOS**
<img height="641" alt="Simulator Screen Shot - iPhone 13 - 2022-06-11 at 15 10 45" src="https://user-images.githubusercontent.com/16966456/173203409-a877216e-900e-4d03-8831-e9301e3cd5b8.png">

This fixes the bug without visual change. 💯

**Comment by jliexpensify** [comment]
Hired @mananjadhav and @JosueEchandiaAsto - thanks!

**Comment by jliexpensify** [comment]
@JosueEchandiaAsto - I have a payment request from you in Upworks, but I'm going to reject it as we generally pay 7 days after deployment.

@mananjadhav @neil-marcellini - it doesn't look like this has been deployed, right? Apologies if I've misunderstood something in this issue, I'm not an engineer.

**Comment by mananjadhav** [comment]
@jliexpensify This should be eligible for payment and closure, but the title has not been updated.

**Comment by jliexpensify** [comment]
Thanks for the heads up @mananjadhav - will get these sorted today.

![image](https://user-images.githubusercontent.com/30815269/177447420-f8f55112-72c2-4181-aedd-765fd969e86e.png)

**Comment by jliexpensify** [comment]
Everyone's been paid, cheers!
