### ISSUE TITLE
[$250] Markdown file names are mistakenly confused as links

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#9329]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Send "ThisIsATest.md" in a chat message

## Expected Result:
The message ThisIsATest.md should not be transformed into a link.

## Actual Result:
The message ThisIsATest.md is transformed into a link.

## Workaround:
Unknown 

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.70-1
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation  
![Screen Shot 2022-06-06 at 11 24 45 PM](https://user-images.githubusercontent.com/43995119/172289221-7ff0258a-8464-490b-8d07-13dde8f17075.png)

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @roryabraham 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1654110557235489

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by stephanieelliott** [comment]
Posted to Upwork: https://www.upwork.com/jobs/~011bd5370e87d5f5cf

**Comment by parasharrajat** [comment]
It is bit of challenging issue. we use  https://github.com/Expensify/expensify-common/blob/main/lib/tlds.jsx to determine the domain. And MD is part of it. There are many other such file extensions that can be a TLD.

**Comment by stephanieelliott** [comment]
Good point @parasharrajat. Hm, I'm not sure that this is something we need to fix l - I would actually expect anything ending in `.XXX` to become a link. Many apps do this, all in all it's pretty harmless. 

@ctkochan22 what do you think? Personally I think we should not punt this but curious what you think?

**Comment by ctkochan22** [comment]
Thats true, I just looked it up and there are a few sites that have the domain `.md`. 

Whenever we chat about files, I usually wrap it in back-quotes, `something.md` which we offer. I think you two are right, we shouldn't classify this as a bug

**Comment by pecanoro** [comment]
I looked it up and it seems "md is the country code top-level domain (ccTLD) for Moldova.". If that is the case, let's close this then.
