### ISSUE TITLE
When you send a message on Desktop Chrome you can't edit it

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#9330]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. User is on the slow network (enable `simulate failing network requests` on staging to reproduce)
2. Send multiple messages 
3. Immediately after writing the last message, click the up arrow key to edit it
4. Observe that you skip to the penultimate message

## Expected Result:
User should be able to edit messages that are still in the send queue

## Actual Result:
When you send a message on Desktop Chrome, no longer how you wait, you can't edit it.  You need to leave the chat and return, before you can edit.

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Web

**Version Number:**  v1.1.73-0
**Reproducible in staging?:** Yes
**Reproducible in production?:** need repro
**Notes/Photos/Videos:**  ![NrHz7UiY1l](https://user-images.githubusercontent.com/16232057/172394995-864988fc-b6a6-400d-9f65-d4fbf711329b.gif)
**Issue reported by:** @quinthar 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1653025915443319
https://expensify.slack.com/archives/C01GTK53T8Q/p1644911919736809

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by trjExpensify** [comment]
@mvtglobally, if you head to staging and then enable `simulate failing network requests` this is reproducible consistently. 

![NrHz7UiY1l](https://user-images.githubusercontent.com/16232057/172394995-864988fc-b6a6-400d-9f65-d4fbf711329b.gif)

**Comment by mallenexpensify** [comment]
ooooh, I think this is part of an issue I've been pushing to get fixed for.. a year! We can very likely close this in favor of https://github.com/Expensify/Expensify/issues/169078

I think @roryabraham is going to start working on a fix soon too.  Actually, I'm going to close this, if needed, someone can reopen
