### ISSUE TITLE
Chat - Unable to scroll to the 1st message

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#9338]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch app and login with HT account
2. Go to chat with many messages e.g. [rybkina@gmail.com](mailto:rybkina@gmail.com)

3. Scroll to 1st message

## Expected Result:
User should be able to scroll to the 1st message

## Actual Result:
Unable to scroll up to 1st message.

## Workaround:
Unknown
## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** v1.1.73-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** kotkot7200@gmail.com / Qwerty123
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 
![Bug5600207_Screen_Shot_2022-06-07_at_10 32 23_AM](https://user-images.githubusercontent.com/43996225/172426212-729cb274-f4f2-49ae-b58e-7b2d41f077c3.png)

https://user-images.githubusercontent.com/43996225/172426242-722bcaea-c3fb-4331-922a-1ddf76ec9c6c.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** Applause internal team
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by tgolen** [comment]
I am not able to reproduce this. I got to the top of a chat eventually:

![image](https://user-images.githubusercontent.com/1228807/185195554-7dfe81ac-be02-45f7-aaa2-ec8b50144c34.png)
