### ISSUE TITLE
[HOLD for payment 2022-07-05] [$250] Split Bill - Selected contacts are duplicated in Recents after type/erase anything in Search

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#9339]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Select Split Bill (green plus button)
2. Enter an amount
3. Select multiple users
4. Type anything in Search field
5. Erase printed in Search field

## Expected Result:
Previously selected users are NOT duplicated in the 'Recents' section

## Actual Result:
Previously selected users are duplicated in the 'Recents' sectionDescribe what actually happened

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.73-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 
![Bug5600236_ND-Split_bill-Recents_Duplicate](https://user-images.githubusercontent.com/43996225/172427605-af080837-3b4a-4a61-9780-cdf939e6918f.png)
<img src="[image URL](https://user-images.githubusercontent.com/43996225/172427605-af080837-3b4a-4a61-9780-cdf939e6918f.png)" width="40%" height="40%">
https://user-images.githubusercontent.com/43996225/172427607-a5ecc5db-6dc9-4524-bfd3-f1a65f5fa68c.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @Tushu17 & Applause internal team
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1649520941635269

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Tushu17** [comment]
Hey, I've reported this bug before on [slack](https://expensify.slack.com/archives/C01GTK53T8Q/p1649520941635269).

**Comment by sobitneupane** [comment]
**Reason:**
We are passing empty array as `selectedOptions` onChangeText in `OptionsSelector`.
**Proposal:**
https://github.com/Expensify/App/blob/1af9250a74a22f0f34bfa983e1b1bfdf53a848b8/src/pages/iou/steps/IOUParticipantsPage/IOUParticipantsSplit.js#L208-L220

```diff
    onChangeText={(searchValue = '') => {
        const {
            recentReports,
            personalDetails,
            userToInvite,
        } = OptionsListUtils.getNewChatOptions(
            this.props.reports,
            this.props.personalDetails,
            this.props.betas,
            searchValue,
-          [],
+          this.props.participants,
            CONST.EXPENSIFY_EMAILS,
        );
```

**Comment by arielgreen** [comment]
https://www.upwork.com/jobs/~0154423cd42bcb5eef

**Comment by mananjadhav** [comment]
@iwiznia, @sobitneupane's proposal looks good.

@sobitneupane, as Rajat mentioned, please wait for the issues to get triaged before posting proposals.

🎀 👀 🎀 
C+ reviewed

**Comment by iwiznia** [comment]
> @sobitneupane, as Rajat mentioned, please wait for the issues to get triaged before posting proposals.

This is not really necessary, but you risk the issue NOT being sent to contributors and thus not getting pay for the proposal. It's all in the guidelines.

@arielgreen can you please hire @sobitneupane?

**Comment by arielgreen** [comment]
@sobitneupane @mananjadhav check your Upwork inbox please

**Comment by mananjadhav** [comment]
@sobitneupane Do you have any PR for me to look at for this one?

**Comment by sobitneupane** [comment]
> @sobitneupane Do you have any PR for me to look at for this one?

Created PR.

**Comment by arielgreen** [comment]
On staging

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (Second week)

**Comment by arielgreen** [comment]
@sobitneupane @mananjadhav payment has been issued.

@Tushu17, apologies I didn't see you reported this before, I've just sent over an offer for the reporting bonus, once you accept I'll send payment.

**Comment by Tushu17** [comment]
@arielgreen Offer accepted, Thank you.

**Comment by Tushu17** [comment]
Bump @arielgreen, payment is pending.
