### ISSUE TITLE
Android - Vivo v2027 - Workspace - When you open any menu in work space editor static loading icon appears during loading

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#9340]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
Issue was found when executing #9202
Issue reproducible only with device Vivo v2027 modal
## Action Performed:
1. Go to Settings, then click into General settings, Issue cards, Reimburse expenses, Pay bills, Send invoices, and Book travel

## Expected Result:
Verify that there's a spinner present during loading

## Actual Result:
Static loading icon appears during loading

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Android Vivo v2027 modal

**Version Number:** 1.1.73
**Reproducible in staging?:** Y
**Reproducible in production?:** N/A new feature
**Email or phone of affected tester (no customers):** andreylazutkinutest@gmail.com /w323052760We
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/172442386-250b4791-b0f5-4a16-b076-30776f372603.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** Applause internal team
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by yuwenmemon** [comment]
@amyevans since you worked on https://github.com/Expensify/App/pull/9202

**Comment by Julesssss** [comment]
I would just close this. We probably have 0 users on this device and it's common for Android manufacturers to override default loading icons.
