### ISSUE TITLE
Payments -  ''Add pay method'' button flashes when tapped on it

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#9368]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch the app
2. Log in with any account
3. Tap on Avatar - Setting - Payments
4. Tap  ''Add pay method'' button

## Expected Result:
 ''Add pay method'' button is not flash when tapped on it

## Actual Result:
 ''Add pay method'' button flashes when tapped on it

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.74.1

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/172747108-f2d6fab6-e989-476f-be12-e288d1ec7ed6.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Luke9389** [comment]
It's pretty hard to see exactly what's happening here. The transparent layer could be flashing out, or the button style could be turning dark green again. 

Definitely seems like it can go `External`.

**Comment by Luke9389** [comment]
Actually, @JmillsExpensify, do you think this issue is well-formed enough to export? We might want to clear up the expectations for the deliverables here before we start spending time on proposals.

**Comment by Luke9389** [comment]
Getting @JmillsExpensify's take before moving forward with this.

**Comment by JmillsExpensify** [comment]
I think we should probably put this one hold. We're about to redo this entire page for N7. Another alternative is to close it for now given that we don't have a use case that supports the Wallet page in the production app.
