### ISSUE TITLE
[HOLD for payment 2022-07-15] [$250] Chat - Extra space displayed when sending mixture of quoted and normal texts

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#9379]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch the app
2. Log in with any account
3. Send message to someone with: non-quoted , quoted then non-quoted text

## Expected Result:
No extra space displayed when used non-quoted and quoted than non-quoted text

## Actual Result:
Extra space displayed when used non-quoted and quoted than non-quoted text

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- iOS
- Android

**Version Number:** 1.1.75.0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/172914715-d9ffa428-383b-4512-a38c-1e96b7260d0f.mp4

**Upwork URL:** https://www.upwork.com/jobs/~0180e7f04fb799c19a
**Issue reported by:** Applause internal team
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by luacmartins** [comment]
This can be external.

**Comment by trjExpensify** [comment]
Upwork job here: https://www.upwork.com/jobs/~0124a56a97e10ed4e0

**Comment by mollfpr** [comment]
### Proposal

This is a known bug on the doc https://meliorence.github.io/react-native-render-html/docs/content/textual#line-breaks and recommends using `enableExperimentalBRCollapsing`. Unfortunately, we use the explicit composite architecture for `react-native-render-html` which is `RenderHTMLSource`.

In our case, for quoted HTML we don't need `<br />` before the `<blockquote>`. So we need to replace that `<br />` with an empty string.
<img width="568" alt="Screen Shot 2022-06-11 at 14 17 55" src="https://user-images.githubusercontent.com/25520267/173178247-48a86f99-f78d-46ce-ab2b-b7d696a29c4b.png">
https://github.com/Expensify/App/blob/6bac9af7294877114f8bf9532ff7b8c46146c90d/src/pages/home/report/ReportActionItemFragment.js#L90-L98
```js
            const lineBreaksAfterBlockquoteRegex = new RegExp(/<br\s*[/]?>(?=<blockquote>)/g);
            const hasLineBreaksAndBlockquote = lineBreaksAfterBlockquoteRegex.test(props.fragment.html);
            if (hasLineBreaksAndBlockquote) {
                const htmlWithoutLineBreaks = Str.replaceAll(props.fragment.html, lineBreaksAfterBlockquoteRegex, '');
                // eslint-disable-next-line no-param-reassign
                props.fragment = {...props.fragment, html: htmlWithoutLineBreaks};
            }
```

### Result

https://user-images.githubusercontent.com/25520267/173179405-159875a3-3bef-47c9-9710-a8e7ef5e6406.mov

**Comment by dhairyasenjaliya** [comment]
### Proposal 

- Here for this issue for HTML we are getting extra `<br />` in messages if combination of both non-quoted and quoted
- for quoted we are already using custom` < blockquote >` which by default includes `<br />`
- so here we do have 2 `<br />` when we have both combinations of both non-quoted and quoted

### Solution 

- the above solution that mollfpr provides works as expected when we replace `<br />` with empty text 
- but the thing is suppose we have a lot of messages at that time we are replacing each and every HTML text and replace` <br />` with an empty string which I think is a workaround, not a permanent fix 

**- IMO rather than replace each and every `<br />` more appropriate solution is to remove `<br />` with a logical check if we have `<br />` right before any `<blockquote>` then need to remove from the Backend only for HTML quoted text this will solve problems in the live app also, if we have any problems that we cant remove from the backend than replace solution will do the trick** 

### Result


https://user-images.githubusercontent.com/47522946/173275181-4783e391-3a46-41f1-8b81-85061c1c91d9.mp4

**Comment by mollfpr** [comment]
>@mollfpr I don't understand how the [bug](https://meliorence.github.io/react-native-render-html/docs/content/textual#line-breaks) you've linked is relevant. Because it's related to ignoring <br> when it is the last element.

I guess you're right.

>Because in our case the <br> before the quote shouldn't be ignored.

I think we don't need `<br>` before blockquote since blockquote is already creating a new line to show.

**Comment by rushatgabhane** [comment]
> I think we don't need <br> before blockquote since blockquote is already creating a new line to show.

Won't that break web? The normal text and quote will be shown on the same line.

**Comment by rushatgabhane** [comment]
@luacmartins I'll wait for your thoughts because I'm note sure what's the best approach to solve this issue.

**Comment by luacmartins** [comment]
@mollfpr proposal seems to fix the issue on mobile and web. I'm not a big fan of the regex, because it can be very slow to parse long comments. I'm not sure if we have an alternative though. @mollfpr can you think of something else?

**Comment by mollfpr** [comment]
@luacmartins @rushatgabhane  I’ll look another solution without regex!

**Comment by luacmartins** [comment]
Thank you!

**Comment by luacmartins** [comment]
@JosueEchandiaAsto thanks for the proposal. However, I think your proposal looks quite similar to @mollfpr and it also seems to be missing some details of how we would remove `<br/>`, e.g. which files would be changes, which methods or functions would be used.

**Comment by JosueEchandiaAsto** [comment]
@luacmartins 
It's a similar solution, but more optimal, It's just one line in a file, using the replaceAll method.  Here is the commit with the detail:

**Comment by rushatgabhane** [comment]
@JosueEchandiaAsto it's very similar to this [proposal ](https://github.com/Expensify/App/issues/9379#issuecomment-1152879262)

As @luacmartins suggested, can you please look for some alternative approach? https://github.com/Expensify/App/issues/9379#issuecomment-1154111492

**Comment by mollfpr** [comment]
@luacmartins @rushatgabhane 

I haven't found anything that can solve this issue without using regex, but I have another proposal that I think it's a better way.

I've checked that when we send a chat, we parse the text with `replace` from `ExpensiMark`. So I think we better add a new rule to replace the line break with an empty string. We already do this for `pre`, so just add another one for `blockquote`.

https://github.com/Expensify/expensify-common/blob/3d87e9b87c6e5ce5fa4bac05bceb3cdf3ad6ca56/lib/ExpensiMark.js#L176-L181

```diff
+            {
+                name: 'replacebrblockquote',
+                regex: /<br\s*[/]?><blockquote>\s*/gi,
+                replacement: '<blockquote>',
+            }
```

Here's the result
<img width="422" alt="Screen Shot 2022-06-16 at 13 24 39" src="https://user-images.githubusercontent.com/25520267/174005989-f11e5311-54e8-4cef-83f4-17d038d91f8e.png">

**The previous blockquote is before sending the message with new rule, and the last blockquote is after apply the new rule**

**Comment by JosueEchandiaAsto** [comment]
@luacmartins @rushatgabhane

https://github.com/Expensify/App/issues/9379#issuecomment-1155862056

My proposal doesn't contain regex, it's a simple replaceAll.

I was checking if with styles it was possible to ignore the break that blockquote has but I couldn't find anything.

**Comment by luacmartins** [comment]
I like your [revised proposal](https://github.com/Expensify/App/issues/9379#issuecomment-1157285013) @mollfpr! It's consistent with what we already have. @rushatgabhane any concerns?

**Comment by rushatgabhane** [comment]
> But it's not changed the previous message that was already sent, any thoughts on that?

That's because we run the parser only when editing or adding a new comment. So that's expected.
For old messages, there is a `<br>` before `<blockquote>`. That is how it's stored in Onyx and backend. We shouldn't modify the old messages or the way they're being read.

**Comment by rushatgabhane** [comment]
@luacmartins I agree as well! Looks good

**Comment by mollfpr** [comment]
@luacmartins @rushatgabhane PR on expensify-common is ON! 🚀

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by trjExpensify** [comment]
@mollfpr are we just waiting for a prod deploy here?

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (Second week)

**Comment by trjExpensify** [comment]
Okay, this one is due for payment, but we assigned the issue before hiring on Upwork and the original post has since expired. 

@mollfpr & @rushatgabhane I've sent you both invites for this, can you apply and then I'll settle up: https://www.upwork.com/jobs/~0180e7f04fb799c19a

**Comment by rushatgabhane** [comment]
thanks, done!

**Comment by trjExpensify** [comment]
Settled up with @mollfpr, @rushatgabhane still says it's waiting on you to accept the offer.

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (Third week)

**Comment by rushatgabhane** [comment]
@trjExpensify accepted!
