### ISSUE TITLE
mWeb / Safari- IOU - Cursor moves up and down when user holds and moves it

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#9380]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Log in with any account
3. Press on + icon and click Request money and add amount like 888.

## Expected Result:
Cursor should not move

## Actual Result:
Cursor moves up and down when I hold it

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Mobile Web Safari

**Version Number:** 1.1.75-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/172915463-54c6f7c5-1d25-4e51-96ab-840e119afea7.mp4

https://user-images.githubusercontent.com/43996225/172915476-e2dc349c-3aea-4cfb-a1ff-ce9f0d3dadfc.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** Applause internal team
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mountiny** [comment]
@kavimuru is this something you have a test case for or is this just an observation? Wondering if it was like this before on production or not. It does not seem like a bug to me as you can still select the spot to move your cursor into.

**Comment by kavimuru** [comment]
@mountiny This is not from a test case. Tester found this issue when performing IOU steps.

**Comment by mountiny** [comment]
@kavimuru is there any way to know if this has been present maybe ~4 versions of the app back?

**Comment by mountiny** [comment]
Alright, I don't think this is a bug worth fixing right now, we should focus on the Offline first refactorings, thanks for raising and in case this comes up in Slack and more people will see this as a problem feel free to reopen!
