### ISSUE TITLE
Chat - Site crashed when clicking on a new group chat created with phone account

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#9399]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open https://staging.new.expensify.com/
2. In chats, click the "New" icon
3. In the pop-up, click "New group"
4. In the pop-up, enter the new number "+380966261784"
5. Click on the number under search
6. Click on "Create group" at the bottom
7. In the chat list, click on the newly created chat

## Expected Result:
A chat room with this new group opens

## Actual Result:
The site crashes

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- Mobile Web

**Version Number:** v1.1.76-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/173104993-e06d1217-0424-4144-b669-6f222983a30c.mp4
![Bug5604110_Crash](https://user-images.githubusercontent.com/43996225/173105013-7434b4f6-94f0-4943-ab72-83d25d74c527.png)

**Expensify/Expensify Issue URL:** 
**Issue reported by:** Applause - Exploratory
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by deetergp** [comment]
@kavimuru I can't even create a group chat with that number. Are we sure this is still a bug?
<img width="1904" alt="Screen Shot 2022-06-13 at 9 59 06 AM" src="https://user-images.githubusercontent.com/766197/173370609-565ccef1-46ec-446d-89c4-f914e719d8b2.png">

**Comment by kavimuru** [comment]
@deetergp In the  phone number +380 is country code. The issue occurs with non existing phone account. I can close this, looks like same rootcause of #8641
