### ISSUE TITLE
[$250] Android/IOS -IOU-The cursor disappears after putting app in background in requesting money

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#9407]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open test app
2. Tap on a contact
3. Tap on +
4. Tap on request Money
5. Put app in background and Open app again

## Expected Result:
The cursor indicating where the next number will appear will be seen after opening app

## Actual Result:
The indicator disappears and can’t be found when entering amount for Money requested after putting app in background

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- iOS
- Android

**Version Number:** 1.1.75.2

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/173239939-f96b62ec-e4c1-40da-9a43-e11a8e7b5eb7.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause -Exploratory

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Gonals** [comment]
Sounds like a good candidate for External!

**Comment by bfitzexpensify** [comment]
Upwork job post [here](https://www.upwork.com/jobs/~0100ff4104b5292c8b)

**Comment by dhairyasenjaliya** [comment]
### Proposal

- here in IOUAmountPage in componentDidUpdate we are comparing current currency and updated currency if both are the same then we are just returning without focus, each and every time we go to request/send money this condition will remain true it will return without focus so we need to remove the conditional check from componentDidUpdate

https://github.com/Expensify/App/blob/0a33d883242c237a903cff5818c67341c7db966b/src/pages/iou/steps/IOUAmountPage.js#L75-L81

### Results

**iOS**

https://user-images.githubusercontent.com/47522946/173496326-27be2dc1-2cab-4098-aba5-5dd22e9325be.mp4


**Android**


https://user-images.githubusercontent.com/47522946/173496404-9a823799-5236-4cc6-a81a-28d97834f04e.mp4


Chrome Web


https://user-images.githubusercontent.com/47522946/173496425-e53a90d8-fe05-42e5-83e2-9a033901543a.mov

**Comment by parasharrajat** [comment]
@dhairyasenjaliya Thanks for the proposal but this is not a good solution. ComponentDidUpdate will fire many times and focus is a blocking operation which will hurt performance. More importantly, that `compoenentDidUpdate` logic was added specifically for currency change use-case.

**Comment by JosueEchandiaAsto** [comment]
@parasharrajat 

### Proposal

### Issue
The textField loses focus when the app goes to background.

### Fix
Using appstate listeners we can know exactly when it goes from background to foreground without affecting the current logic, nor creating loops.
Docs: https://reactnative.dev/docs/appstate
Commit: https://github.com/Expensify/App/commit/6f988d69e02dc3ec972a0d049cc84c0d57d16e02

### Result
https://user-images.githubusercontent.com/16966456/173705136-05866cf8-fea0-4929-8eb4-b82b697d7385.mp4

**Comment by usmanghani127** [comment]
## Proposal

### Issue

https://github.com/Expensify/App/blob/d8e4adae05abbd45ca72fe5c80298686456e9e63/src/components/TextInput/BaseTextInput.js#L48-L62

The AppState listener is unnecessary here, because there is no need to dismiss a keyboard which is already disabled:

https://github.com/Expensify/App/blob/d8e4adae05abbd45ca72fe5c80298686456e9e63/src/components/TextInput/BaseTextInput.js#L274

### Fix
By removing this listener and its relevant code (imports, listener remover), this issue can be fixed

### Result 

https://user-images.githubusercontent.com/71348149/173758429-09e38145-3912-405d-b52c-3dcaa84a5b3c.mov

**Comment by liyamahendra** [comment]
# Proposal

Since `componentDidUpdate` is called when the app returns to foreground, moving `this.focusTextInput();` to the top solves the issue:

```
componentDidUpdate(prevProps) {
        this.focusTextInput();
        
        if (this.props.iou.selectedCurrencyCode === prevProps.iou.selectedCurrencyCode) {
            return;
        }
    }
```

@parasharrajat are you aware about the reason why we have the `if` check and what problem is solves?

**Comment by marcaaron** [comment]
Hmm I feel that this is not a real bug or one that needs to be prioritized right now... but maybe I am missing why it matters.

@bfitzexpensify @Gonals thoughts on just closing this?

**Comment by Gonals** [comment]
Hmmm. I'd be ok with just closing this. I don't think I would consider it a bug as a user (and certainly not a relevant one)

**Comment by bfitzexpensify** [comment]
Yes, agreed. OK, closing it out.
