### ISSUE TITLE
[HOLD for payment 2022-07-05] [$250] On request call page keyboard type is wrong for phone number, extension field - reported by @Tushu17

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#9411]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open mobile Website/App
2. Go to workspace > Get assistance > Request a setup call.
3. Touch on Phone Number/Extension input field.

## Expected Result:
You should see a number pad.

## Actual Result:
 It shows normal alphabetical keyboard.

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- iOS
- Android
- Mobile Web

**Version Number:** 1.1.75-0
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 

https://user-images.githubusercontent.com/43995119/173278659-1b1373be-8278-4af2-a8de-9cf9b11c074b.mov

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @Tushu17
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1653329809177109

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Tushu17** [comment]
### Proposal 
We just need to add `keyboardType={CONST.KEYBOARD_TYPE.PHONE_PAD}` in `TextInput` of Phone number & Extension field. 
https://github.com/Expensify/App/blob/6bac9af7294877114f8bf9532ff7b8c46146c90d/src/pages/RequestCallPage.js#L301-L303
https://github.com/Expensify/App/blob/6bac9af7294877114f8bf9532ff7b8c46146c90d/src/pages/RequestCallPage.js#L311-L314

**Comment by danieldoglas** [comment]
Ok, this can be external

**Comment by MitchExpensify** [comment]
[Upwork job](https://www.upwork.com/ab/applicants/1537098751012495360/suggested)

**Comment by allroundexperts** [comment]
@rushatgabhane Is it allowed to make a proposal before even a job is declared external?

**Comment by rushatgabhane** [comment]
As per [CONTRIBUTING.md](https://github.com/Expensify/App/blob/main/CONTRIBUTING.md#propose-a-solution-for-the-job) you can. But Expensify has the right to use your proposal without compensation if it isn't marked `External`.
> Note: Issues that have not had the External label applied have not yet been approved for implementation. This means, if you propose a solution to an issue without the External label (which you are allowed to do) it is possible that the issue will be fixed internally. If the External label has not yet been applied, Expensify has the right to use your proposal to fix said issue, without providing compensation for your solution. This process covers the very rare instance where we need or want to fix an issue internally.

**Comment by allroundexperts** [comment]
> @allroundexperts good question! As per [CONTRIBUTING.md](https://github.com/Expensify/App/blob/main/CONTRIBUTING.md#propose-a-solution-for-the-job) you can. But Expensify has the right to use your proposal without compensation if it isn't marked `External`.
> 
> > Note: Issues that have not had the External label applied have not yet been approved for implementation. This means, if you propose a solution to an issue without the External label (which you are allowed to do) it is possible that the issue will be fixed internally. If the External label has not yet been applied, Expensify has the right to use your proposal to fix said issue, without providing compensation for your solution. This process covers the very rare instance where we need or want to fix an issue internally.

Gotcha. Thanks!

**Comment by Tushu17** [comment]
I have made the PR

**Comment by thienlnam** [comment]
PR merged, pending regression testing

**Comment by MitchExpensify** [comment]
Hired @Tushu17 & @rushatgabhane for eventual payment

**Comment by MitchExpensify** [comment]
Paying tomorrow when back from ooo!
