### ISSUE TITLE
Hovering over the avatar inside the chat doesn't show the tooltip - reported by @adeel0202

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#9412]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to any chat
2. Hover over the avatar on top of the chat

## Expected Result:
The tooltip is shown

## Actual Result:
The tooltip doesn't show

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Web
- Desktop App

**Version Number:** 1.1.75-0
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 

https://user-images.githubusercontent.com/43995119/173279285-251d4e8a-2ad6-4304-ad6f-781d93108c8a.mov

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @adeel0202
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1653411262374379

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by tylerkaraszewski** [comment]
Looks ok

**Comment by Puneet-here** [comment]
### Proposal 
We need to wrap `RoomHeaderAvatars` inside the tooltip https://github.com/Expensify/App/blob/0d6850a0929550301f63c292774872cb6f4d9008/src/pages/home/report/ReportActionItemCreated.js#L50

And we can get the tooltip text using `ReportUtils.getDisplayNamesWithTooltips(OptionsListUtils.getPersonalDetailsForLogins(participants, props.personalDetails))`
We don't wanna show tooltip for rooms, that's why I am using a variable `shouldShowTooltip`

For easy understanding we have to add the following code
```diff
const ReportActionItemCreated = (props) => {
    const isPolicyExpenseChat = ReportUtils.isPolicyExpenseChat(props.report);
+    const isChatRoom = ReportUtils.isChatRoom(props.report);
    const icons = ReportUtils.getIcons(props.report, props.personalDetails, props.policies);
+    const participants = lodashGet(props.report, 'participants', []);
+    const displayNamesWithTooltips = ReportUtils.getDisplayNamesWithTooltips(
+        OptionsListUtils.getPersonalDetailsForLogins(participants, props.personalDetails),
+    );
+    const avatarTooltip = _.pluck(displayNamesWithTooltips, 'tooltip');
+    const shouldShowTooltip = !isPolicyExpenseChat && !isChatRoom;
    return (
        <View style={[
            styles.chatContent,
            styles.pb8,
            styles.p5,
        ]}
        >
            <View style={[styles.justifyContentCenter, styles.alignItemsCenter, styles.flex1]}>
                <Pressable onPress={() => ReportUtils.navigateToDetailsPage(props.report)}>
+                    <Tooltip text={shouldShowTooltip && avatarTooltip.join(', ')}>
                        <RoomHeaderAvatars
                            icons={icons}
                            shouldShowLargeAvatars={isPolicyExpenseChat}
                        />
+                    </Tooltip>
                </Pressable>
```

**Comment by mountiny** [comment]
Thank @Puneet-here for the proposal, i am afraid though I agree with Rajat and this is not really a bug. There is the email already written below so I would say adding a tooltip there is not needed. It will be not visible after couple of messages too.

I will not close it yet and wait a day or so if anyone will feel different. Anyone feel free to leave a comment suggesting why this is bad UX or a problem we should really focus on. Thank you 🙇‍♂️

**Comment by adeel0202** [comment]
I reported this bug because I could see tooltip while hovering over the avatars everywhere (i.e. the header, on LHN, and inside the chat) except for this preview avatar. However, if this is on purpose and you guys think this is not an issue then we can close this.
