### ISSUE TITLE
Log search links are appending ?authToken= to the end, completely breaking them when navigating to them

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#9416]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Send a log search link to someone IE https://www.expensify.com/_devportal/tools/logSearch/#sort=asc&size=10000&query=blob%3A%22Expensiworks_CaptureAgentActivity%22%20AND%20blob%3A%22isDoneWorking%3A%20'true'%22%20AND%20email%3A%22monte%40expensify.com%22%20AND%20timestamp%3A%5B2022-05-25T12%3A00%20TO%202022-05-25T14%3A00%5D
2. Click the link
3. Observe ?authToken=<an authtoken>&email=<your email> at the end of the link

## Expected Result:
Log Search link should open without any issue 

## Actual Result:
Log search links are appending ?authToken= to the end, completely breaking them when navigating to them

## Workaround:
Unknown 

## Platform:

Where is this issue occurring?

- Web

**Version Number:** 1.1.75-0
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 
![Screen Shot 2022-06-13 at 12 38 57 AM](https://user-images.githubusercontent.com/43995119/173280878-d18587ad-103d-432c-aee0-12bf7e30fc14.png)

**Expensify/Expensify Issue URL:**  
**Issue reported by:** @alex-mechler 
**Slack conversation:** [
](https://expensify.slack.com/archives/C01GTK53T8Q/p1653584707566799)
[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by johnmlee101** [comment]
This is coming from 
https://github.com/Expensify/App/blob/65f20e83d074927e3cb85e56928a9f18d6e556b8/src/libs/actions/Link.js#L42
since we don't have `?` in the URL so it wants to append more just as is.
