### ISSUE TITLE
[HOLD for payment 2022-08-30] [$250] mweb - Unable to add a new line while editing a comment @thesahindia

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#9421]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Navigate to any chat
2. Long press on a message> Edit comment
3. Press enter/return on keyboard

## Expected Result:
Able to add a new line while editing a comment in mWeb

## Actual Result:
Unable to add a new line while editing a comment in mWeb

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Mobile Web

**Version Number:** 1.1.75.2

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/173348167-4e1dbd39-d263-40e7-bab5-201e2fd5adbc.mov

**Expensify/Expensify Issue URL:** 

**Issue reported by:** @thesahindia

**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1652956375146769

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment]
@sketchydroide Issue is reproduced in SG21/12 with version 1.1.76.2

https://user-images.githubusercontent.com/93399543/173369070-59c3ce05-cb81-46b7-a84e-c4a6de40ae44.mp4

**Comment by sketchydroide** [comment]
@kbecciv thanks, that is on an Android, can you please test the same version on an iPhone as well.
That is what I tested on, they should behave the same, but just want to get as much data on this as possible

**Comment by sketchydroide** [comment]
@kbecciv Bump

**Comment by sketchydroide** [comment]
Oh I no longer have a device, I might need to ask someone to test this

**Comment by thesahindia** [comment]
### Proposal 

We had this issue at composer and this is how we fixed this -

https://github.com/Expensify/App/blob/0fcc4920dbc0e0b7658e80541367acf8a2e4ff57/src/pages/home/report/ReportActionCompose.js#L404-L407

Right now pressing enter saves the draft so we have to prevent that behaviour for mobile devices adding a check like we have at `triggerHotkeyActions` for the composer -
https://github.com/Expensify/App/blob/0fcc4920dbc0e0b7658e80541367acf8a2e4ff57/src/pages/home/report/ReportActionItemMessageEdit.js#L182

**Comment by sketchydroide** [comment]
ok, I'm happy to make this an external then

**Comment by sketchydroide** [comment]
I was trying to remove you @dylanexpensify since you just came back from PL, but the bot really wants you :D

**Comment by dylanexpensify** [comment]
hahaha no problem! Gettin back into the swing of it! 😂

**Comment by mananjadhav** [comment]
I tested @thesahindia's proposal here https://github.com/Expensify/App/issues/9421#issuecomment-1179306114. It seems to be working and we're already using it in the Composer. 

🎀 👀 🎀 C+ reviewed

**Comment by mananjadhav** [comment]
@sketchydroide Got a chance to look at the above comment?

**Comment by dylanexpensify** [comment]
bump @sketchydroide

**Comment by sketchydroide** [comment]
humm, sorry this was missed completly for some reason.

**Comment by thesahindia** [comment]
PR is up.

cc: @mananjadhav

**Comment by dylanexpensify** [comment]
Any updates here?

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by dylanexpensify** [comment]
@thesahindia can you apply here for the job so I can pay you out? https://www.upwork.com/jobs/~0130dae03edefa9efb

thank you!

**Comment by mananjadhav** [comment]
@dylanexpensify Can I apply to the same job for C+? I guess I missed applying/getting hired on this one.

**Comment by dylanexpensify** [comment]
Go for it!

**Comment by thesahindia** [comment]
>@thesahindia can you apply here for the job so I can pay you out? https://www.upwork.com/jobs/~0130dae03edefa9efb

Applied. Thanks :)

**Comment by dylanexpensify** [comment]
Jobs paid out, contracts ended, posting removed!
