### ISSUE TITLE
[HOLD for payment 2022-09-01] [$250] Android - User cannot send the video in app @Puneet-here

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#9422]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open expensify app in android
2. Go to any chat > press heavy_plus_sign > add attachment > select a video> send

## Expected Result:
User can't send the video

## Actual Result:
User should be able to send the video

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Android

**Version Number:** 1.1.75.2

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/173932304-c51d592f-3353-42a6-8bdc-26f67650914f.mp4

**Expensify/Expensify Issue URL:**
 
**Issue reported by:** @Puneet-here

**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1653202853008229

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by flodnv** [comment]
To clarify, it sounds like the problem is bigger videos? Can we get an example of a video which works, and one that does not?

**Comment by flodnv** [comment]
Strange, that's not what @mvtglobally said here: https://expensify.slack.com/archives/C01GTK53T8Q/p1653974980606659?thread_ts=1653202853.008229&cid=C01GTK53T8Q

**Comment by Puneet-here** [comment]
@mvtglobally, wasn't able to repro this issue, I can repro this issue with smaller videos and I was able to repro this on different android devices and different accounts.

**Comment by mvtglobally** [comment]
@flodnv Team members were able to repro and we added the video of the same. Hope this helps. 
In the past the issue was with the bigger files only. Now it seems all videos are not loading

**Comment by flodnv** [comment]
Ok thanks. I guess I'll need to investigate to see if it's internal or external.

**Comment by flodnv** [comment]
Oh, to clarify, this issue only occurs on the Android app?? Indeed, I just uploaded a 13MB video on Desktop.

**Comment by Puneet-here** [comment]
Yes, the issue is on android only.

**Comment by NicMendonca** [comment]
Job post: https://www.upwork.com/jobs/~01a43f8db197229692

**Comment by errahsoufiane** [comment]
https://drive.google.com/file/d/1uebEUPfwL1DEFvzRg7xGfizpwEYy8VKA/view?usp=sharing
As you see video, `Choose from gallery` doesn't support .mp4 format
But `Choose document` works
This is latest codebase from `main` branch

**Comment by eVoloshchak** [comment]
**Proposal:**
This happens due to `react-native-image-picker` returning temporary file name instead of the real name of the file user has selected. This can be seen in [this](https://github.com/Expensify/App/issues/9422#issue-1269356711) screen capture too, notice how the video doesn't have an extension, it's just called `video:some_random_numbers`.
This is an open issue for both iOS and Android
https://github.com/react-native-image-picker/react-native-image-picker/issues/1569 
https://github.com/react-native-image-picker/react-native-image-picker/issues/1997 
https://github.com/react-native-image-picker/react-native-image-picker/issues/1959

And there [seems](https://github.com/react-native-image-picker/react-native-image-picker/issues/1569#issuecomment-934275128) to have been implemented a workaround at some point in [this PR](https://github.com/FireKamp/react-native-image-picker/commit/889a67c85e20984f821bcf81f82a45e7849fec42), but cherry-picking this PR or just using this version from github isn't returning real file name, so I'm guessing it was broken by an Android update.

Expensify backend somehow relies on file having an extension, a couple of times i saw an "Invalid file type" error when uploading video from gallery. We can add an extension back to the filename, since we have it in `type` property.
https://github.com/Expensify/App/blob/93647846f785bee14a6f2e12107130472cc454b1/src/components/AttachmentPicker/index.native.js#L67

```diff
+   const fileName = fileData.fileName || fileData.name || 'chat_attachment';
+   const fileExtension = _.last(fileData.type.split('/'));
    const fileResult = {
+       name: `${fileName}.${fileExtension}`,
-       name: fileData.fileName || fileData.name || 'chat_attachment',
        type: fileData.type,
        uri: fileData.fileCopyUri || fileData.uri,
        size: fileData.fileSize || fileData.size,
    };
```
Result:

https://user-images.githubusercontent.com/9059945/180597833-1f127104-0f40-4663-b342-d98c9ed88b4d.mp4

**Comment by rushatgabhane** [comment]
Hmm im not too sure about @eVoloshchak's proposal

**Comment by rushatgabhane** [comment]
@kbecciv is this bug still reproducible on staging ?

**Comment by NicMendonca** [comment]
@kbecciv bump ☝️

**Comment by kbecciv** [comment]
@NicMendonca Checking with team, will update you shortly

**Comment by kbecciv** [comment]
@NicMendonca Issue still reproducible on staging. 
Android app shows "Attachment uploading" when used a big mp4 file., attached video.
We have KI https://github.com/Expensify/App/issues/10031 for the mp4 file smaller than 3MB.
I hope it helps. 

https://user-images.githubusercontent.com/93399543/181619656-690914a9-7556-48c9-b928-3a478c23390f.mp4

**Comment by eVoloshchak** [comment]
I'm getting this error message also
![image](https://user-images.githubusercontent.com/9059945/181621429-892892f3-d027-4b35-bc61-62f2dac37cc2.png)

**Comment by rushatgabhane** [comment]
@eVoloshchak what's your version number?

**Comment by eVoloshchak** [comment]
> @eVoloshchak what's your version number? I'm on v1.1.84-13 and it isn't reproducible

Tested again on freshly installed v1.1.84-13 from Google Play, issue still exists.


https://user-images.githubusercontent.com/9059945/181687657-941e2b70-0817-4a8c-a94e-654146f82bb7.mp4

I've tried files less than 1 MB and a bigger ones.
Android 11, OnePlus 6

**Comment by rushatgabhane** [comment]
@deetergp did something break in the backend?

If not, let's go with @eVoloshchak's [proposal](https://github.com/Expensify/App/issues/9422#issuecomment-1193089176) because it deals with the file not supported error returned by the backend

**Comment by rushatgabhane** [comment]
@eVoloshchak what will happen if a file doesn't have an extension?

**Comment by eVoloshchak** [comment]
> @eVoloshchak what will happen if a file doesn't have an extension?

For me at least if file doesn't have an extension, it will not be displayed in the file picker. It probably filters them out

**Comment by eVoloshchak** [comment]
> > @eVoloshchak what will happen if a file doesn't have an extension?
> 
> For me at least if file doesn't have an extension, it will not be displayed in the file picker. It probably filters them out

And it also isn't displayed it you select "Choose Document" instead of "Choose from gallery"

**Comment by deetergp** [comment]
@rushatgabhane I don't think the API has changed or we'd be having larger issues elsewhere. I agree that @eVoloshchak's proposal looks good, so @NicMendonca let's hire him 👍.

**Comment by eVoloshchak** [comment]
> @eVoloshchak how's it looking?

With the latest version from git (v1.1.88-7) it looks like this:

https://user-images.githubusercontent.com/9059945/184105256-d161c80c-0735-42a0-b181-5820ea72cbbf.mp4

**Comment by eVoloshchak** [comment]
> Perfect, can you please raise a PR for the fix

I'm not assigned yet, but no problem, I'll submit a PR tomorrow

**Comment by deetergp** [comment]
Not overdue. Assigned in Upwork a few days again and awaiting a PR.

**Comment by eVoloshchak** [comment]
PR is up

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by NicMendonca** [comment]
paid!
