### ISSUE TITLE
[$250] Implement Three Suggested Changes from Callstack

### ISSUE THREAD

**Issue by Luke9389** [Expensify/App#9427]
### Background

Callstack is vendor that we've engaged to help with app performance. They've needed to delay our engagement until September, but in the mean time gave a few tips for us that they think would be helpful. 

### Suggested Changes

- ~~The @react-native-community/cli dep shouldn't be added directly. It's a transitive dependency of react-native.~~
`Note:` No longer adding @react-native-community/cli directly in package.json

- ~~Both underscore and lodash are used. These are big libraries with the same purpose so you can pick one instead (we suggest lodash in this case)~~

- Remove Intl polyfills (@formatjs/intl*) usage, which can add up to 6MB of unicode data into the JS bundle. The Hermes version you're using supports Intl object by default, so polyfill is an unnecessary overhead

### Game Plan

I'll bring these up for discussions with engineering to verify that we should proceed, and then implement the changes that we greenlight.

**Comment by Luke9389** [comment]
Brought this up in eng-chat [here](https://expensify.slack.com/archives/C03TQ48KC/p1655144670493729)

**Comment by Luke9389** [comment]
After discussing this in the thread linked above, we've decided to strike number 2 from the list.

**Comment by Luke9389** [comment]
Coming back to this issue this week.

**Comment by parasharrajat** [comment]
One more thing that I can think of is to prevent the use of inline prop values as much as possible. 

1. No Inline callbacks. 
2. No inline objects. 

Object literals will recreate a new object on each render and due to a change of value, the underlying component will rerender.

**Comment by Luke9389** [comment]
Thanks @parasharrajat, I'll check out the impact of those suggestions 👍

**Comment by Luke9389** [comment]
Gonna loop back around to this

**Comment by Luke9389** [comment]
gonna close this up by the end of the week.

**Comment by Luke9389** [comment]
Hoping to get to this soon.

**Comment by Luke9389** [comment]
C+ would you be willing to help test this PR for me? https://github.com/Expensify/App/pull/10750

**Comment by jboniface** [comment]
@mananjadhav  job post here: https://www.upwork.com/jobs/~0175fa858fa8779088

**Comment by mananjadhav** [comment]
Applied @jboniface

**Comment by jboniface** [comment]
any update here? @Luke9389 / @mananjadhav

**Comment by Luke9389** [comment]
Hey @jboniface & @mananjadhav, I still haven't had a cycle to come back to this. I'll be updating soon.

**Comment by Luke9389** [comment]
I'm going to close this in favor of all the performance updates we're doing with margelo. I still haven't gotten the app to run without the format/intl dependency, and that's the only outstanding task from callstack of the original three. 
@parasharrajat I think it's worth bringing[ this suggestion ](https://github.com/Expensify/App/issues/9427#issuecomment-1178410102)up in the open source room. That way we can make it a separate ticket if we decide to do it.

**Comment by Luke9389** [comment]
Thanks for helping test here @mananjadhav, 
@Expensify/contributor-management would any of you be willing to pay out this issue for @mananjadhav?

**Comment by JmillsExpensify** [comment]
I'll do it. Assigning myself now.

**Comment by Luke9389** [comment]
Thanks!

**Comment by JmillsExpensify** [comment]
@mananjadhav Send you a contract offer here: https://www.upwork.com/jobs/~01967be1fa14712bf3

**Comment by JmillsExpensify** [comment]
Paid via Upwork
