### ISSUE TITLE
Chat - JS console error appears when opening a particular chat

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#9436]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open Desktop App as login user [applausetester++115@applause.expensifail.com](mailto:applausetester++115@applause.expensifail.com)
2. Go to chat with [applausetester+0524@applause.expensifail.com](mailto:applausetester+0524@applause.expensifail.com)
3. Check the JS console

## Expected Result:
No errors appear in the JS console

## Actual Result:
The errors are appeared in the JS console.
Errors: "Report no longer exists"
"Cannot read properties of undefined"

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- Desktop App

**Version Number:** v1.1.76-5
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 
![Bug5608178_Screen_Shot_2022-06-13_at_3 42 07_PM](https://user-images.githubusercontent.com/43996225/173444777-ac1199f6-4742-4098-afe0-d498cce6d918.png)

https://user-images.githubusercontent.com/43996225/173444786-e326445a-4a16-451e-baab-485c708e2556.mp4
[Bug5608178_errors.txt](https://github.com/Expensify/App/files/8894423/Bug5608178_errors.txt)

**Expensify/Expensify Issue URL:** 
**Issue reported by:** Applause internal team
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by techievivek** [comment]
Looks like this could be related to the [discussion](https://expensify.slack.com/archives/C01GTK53T8Q/p1654013143621589) that I started in Slack being said that I don't feel like this is something that is concerning as of now.
