### ISSUE TITLE
[HOLD] [$250] Chat - "1 New message" badge does not display when user is on the older messages and a new message arrives

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#9437]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Sign into account A on the main device . Sign into account B on another device
3. In account A, scroll to older messages with account B 
4. Send some messages from account B to account A

## Expected Result:
"1new message" badge appears in account A

## Actual Result:
No badge appears even if the user A is somewhere in the top of the messages

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web

**Version Number:** v1.1.76-5
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** applausetester+ihchat4@applause.expensifail.com / Yulia1986Gerets
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:**

https://user-images.githubusercontent.com/43996225/173462881-e79332e1-0cb6-4bab-8b16-95e437a27884.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:**  Applause internal team
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by adelekennedy** [comment]
[internal](https://www.upwork.com/ab/applicants/1537529407758827520/job-details)
[external](https://www.upwork.com/jobs/~01a69040ca38e9de85)

**Comment by rushatgabhane** [comment]
@marcaaron @marcochavezf I don't remember exactly but we were closing any notification related issues right?

**Comment by marcaaron** [comment]
Yep, thanks @rushatgabhane (not closing but they are on hold for now)

**Comment by aksoo5** [comment]
@marcaaron Why was the PR closed?

**Comment by GoEagles999** [comment]
Issue is related to `FloatingMessageCounter`. Scroll distance condition in `toggleFloatingMessageCounter` in `ReportActionsView.js` needs to be updated to allow for notifications to be shown when scroll offset is gt 200px.

**Comment by marcaaron** [comment]
Please propose solutions to issues that have the `Help Wanted` label, thanks.

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)
