### ISSUE TITLE
[$500] IOS - VBA - Selected date is set incorrectly for date of birth field

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#9466]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login in App with any account
2. Create a New Workspace
3. Enable staging Web secure server in Account Preferences
4. Start entering data VBA

## Expected Result:
Selected date should be correctly displayed

## Actual Result:
Selected date is set incorrectly for date of birth field

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- iOS

**Version Number:** 1.1.76.2

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** applausetester+13061@applause.expensifail.com/Yulia1986Gerets

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/173881093-d66f121e-83bc-46a0-bb46-636899a91493.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by JmillsExpensify** [comment]
Wow that's a pretty weird one. Upwork job here: https://www.upwork.com/jobs/~01becfc15be5bddc4b

**Comment by allroundexperts** [comment]
@kbecciv @JmillsExpensify I'm not able to reproduce this.

https://user-images.githubusercontent.com/30054992/174033101-a85746c8-4e2c-4725-98ef-93a41ab226b5.mp4

**Comment by AndrewGable** [comment]
@Expensify/applauseleads - Can you verify you can still recreate this issue?

**Comment by JmillsExpensify** [comment]
Putting the issue on [Hold] until we can reproduce.

**Comment by mvtglobally** [comment]
@JmillsExpensify @AndrewGable, We had 3 testers able to repro the issue. all 3 are from GMT+2 timezone. 
We also validated that it wasn't next day for them so we believe its not  UTC <>EST timezone related. 
we are not able to repro in US

**Comment by AndrewGable** [comment]
That makes sense

**Comment by bdt2019unicorn** [comment]
**Upwork Proposal**

I think the problem is with the select datetime component. From the video, when the person select a date, the date goes back 1 day before. This happens because the app automatically convert the time to the standard US time. 
That is the reason why the people in US could not make the same error because the conversion between US time to US time would not make any differences. 

There are 2 ways to solve this: 
1. Check for the time zone different when doing the conversion, if the the date changes, we can continue with the old date.
2. Eliminate the time zone conversion of the app when entering date of birth. In that case, we take whatever the date the user enters. 

If you have any further questions, please let me know. 
Kind regards, 
Binh

**Comment by parasharrajat** [comment]
Ok, I see what is happening here. Thanks for your proposal @bdt2019unicorn.  I understood your general analysis. But you have to propose a solution that works with the codebase. In other workds, what would you do to solve this issue in our app?

**Comment by bdt2019unicorn** [comment]
@parasharrajat 

Thank you for your reply. 
Sorry as I have just seen this because I thought the Upwork proposal person ignore my proposal as I did not see any reply. 
I tried to sign up with the app using the staging environment but I can't even sign up and the only place I can sign up is in the website. 
In that place, I don't this screen so that is why I can only give a general solution based on the videos I saw from this issue. 
Would you be able to give the environment or the video showing how to sign up using the app?
I am not quite sure how to get to that screen as a user so I am not quite sure what components in the code is responsible for it.

**Comment by parasharrajat** [comment]
> > Would you be able to give the environment or the video showing how to sign up using the app?

@bdt2019unicorn I will suggest you join our open-source slack channel for such questions. But I believe that most of the information is available on `Read.me` and `contributing.md` files. 

> I am not quite sure how to get to that screen as a user so I am not quite sure what components in the code is responsible for it

Follow the action performed. Let me know otherwise.

**Comment by bdt2019unicorn** [comment]
@parasharrajat 
Thanks for the answer. From your contributing.md file, the only way to sign up is through the actual website as the image below. 



![image](https://user-images.githubusercontent.com/51917268/176566426-94ce865c-a9fb-494a-ad3f-f89d3cd98044.png)


If you want to sign up from the app in local, you will have error for not being authorized. I found this work from Upwork and I would pretty much want to keep the conversation through Upwork if possible. Talking here may go a bit outside of their Terms and Conditions already. 


For the action performed, I watched the videos and I can only see the screen, not how to get there when you open the app. 
Is there any assumption about the knowledge of the person submitting the proposal?

**Comment by bdt2019unicorn** [comment]
> But it might be a little hard for you to follow on due to being a new contributor so I suggest you take a look at other open issues.

Thank you for the nice rejection. I will look at other thing then. If you don't mind, would you be able to reply to my proposal on Upwork letting me know that so I can keep the record. Just trying to learn through different proposals so I can make the next one better than previous one.

**Comment by parasharrajat** [comment]
I am not rejecting your proposal. It's just a suggestion. You can pursue this issue if you want. 

Also, we don't accept proposals on Upwork. Please read the CONTRIBUTING.md file to understand the process.

**Comment by bdt2019unicorn** [comment]
I found this one through Upwork and I thought everything should go through that. 
I can see you hire through Upwork in the Contributions thing. 
Does it mean somebody else took this already and the Upwork post is just a way to pay the person?

**Comment by parasharrajat** [comment]
This is available. Open for propsoals...

**Comment by JmillsExpensify** [comment]
Still awaiting proposals

**Comment by JmillsExpensify** [comment]
The old job expired, so I've created a fresh one and increased the bounty to $500 as opposed to higher given that this isn't an incredible priority.

**Comment by buneme** [comment]
@JmillsExpensify I've set my timezone to GMT+2 but can't reproduce the issue, is it still reproducable?

**Comment by buneme** [comment]
Hi @JmillsExpensify, I've tried setting my timezone to GMT+2 (specifically Europe/Oslo) in the app but I can't reproduce the issue
<img width="383" alt="Screenshot 2022-07-19 at 02 41 27" src="https://user-images.githubusercontent.com/3949246/179707215-91f8bce3-5a56-4f21-b823-f5fd4c26cd46.png">.

**Comment by JmillsExpensify** [comment]
Interesting, thanks for the heads up! @kbecciv can we test this flow and confirm whether it's still an issue on the latest release?

**Comment by buneme** [comment]
@JmillsExpensify thanks! I'm running it on the iOS simulator so I also tried changing my computer's time zone, but that didn't help.

**Comment by parasharrajat** [comment]
It would great to get this info as well. 
1. timezone of the device. 
2. Current time of the device. 
3. Selected timezone of the logined user from the profile page.
4. Selected locale.

**Comment by JmillsExpensify** [comment]
Agreed. I'm going to try @applausebot to make sure we get a reply.

**Comment by mvtglobally** [comment]
Looking into it

**Comment by kbecciv** [comment]
@parasharrajat 
1. UTC + 3
2. 19:40
3. Europe/Kyiv
4. English

**Comment by JmillsExpensify** [comment]
@parasharrajat I'm going to be out the next 3 business days, so if we still have trouble re-producing the issue, let's close and we can re-open if it comes up again. Thanks!

**Comment by parasharrajat** [comment]
I will check it today.

**Comment by JmillsExpensify** [comment]
I'm coming back from vacay and it's still not clear this is an issue, so I'm going to proactively close. Please re-open if anyone is able to reproduce.
