### ISSUE TITLE
[$250] When using the app in spanish, the currency selector is not showing the currencies' symbol 

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#9494]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open app 
2. Select IUO 
3. Click on currency selector 
4. check Currencies display 

## Expected Result:
When using the app in spanish, the currency selector should show the currencies' symbol 

## Actual Result:
When using the app in spanish, the currency selector is not showing the currencies' symbol like it does in english (ie: CA$ in the screenshot)

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.77-0
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 
![image - 2022-06-20T090521 960](https://user-images.githubusercontent.com/43995119/174608190-558aa7c6-7264-44d9-a1f9-b4c9eb10117c.png)
![image - 2022-06-20T090520 657](https://user-images.githubusercontent.com/43995119/174608193-dd17021c-75a3-49d5-a791-31af359827ab.png)

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @iwiznia 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1655499458203209

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by tgolen** [comment]
@iwiznia Could you take a quick look at this one and recommend what the desired behavior should be?

**Comment by iwiznia** [comment]
Oh damn, you are right. Why the hell is CA$ in english and CAD in spanish?!?
I guess that's how the standard in spanish is defined and I don't think we should deviate from it, so we should do nothing and do not consider this a bug.
Thanks for investigating!

**Comment by parasharrajat** [comment]
I am not sure how to handle this. Brower returns `CAD` for `CAD` in the Spanish locale.
