### ISSUE TITLE
`GithubUtils.getStagingDeployCashData()` returned a deploy blocker issue in list of PRs

### ISSUE THREAD

**Issue by francoisl** [Expensify/App#9500]
## Action Performed:
1. We merged a [pull request](https://github.com/Expensify/App/pull/9496) that had the `CP staging label` 
2. The action `createOrUpdateStagingDeploy` failed
     - It recognized a deploy blocker listed in the current [deploy checklist](https://github.com/Expensify/App/issues/9480) as a pull request. See logs here: https://github.com/Expensify/App/runs/6972270023?check_suite_focus=true
     - [9487](https://github.com/Expensify/App/issues/9487) (which is an issue) is listed both in the `PRList` and the `deployBlockers` arrays <img width="617" alt="image" src="https://user-images.githubusercontent.com/2229301/174662198-61866c4c-0fa5-43d3-b570-acd25647037d.png">

<details><summary>Backup of the deploy checklist issue's markdown at the time of the error</summary>
<p>

```md
**Release Version:** `1.1.78-0`
**Compare Changes:** https://github.com/Expensify/App/compare/production...staging

**This release contains changes from the following pull requests:**

- https://github.com/Expensify/App/pull/9031
  - [ ] QA
  - [x] Accessibility

- https://github.com/Expensify/App/pull/9266
  - [ ] QA
  - [ ] Accessibility

- https://github.com/Expensify/App/pull/9347
  - [ ] QA
  - [x] Accessibility

- https://github.com/Expensify/App/pull/9401
  - [ ] QA
  - [ ] Accessibility

- https://github.com/Expensify/App/pull/9404
  - [ ] QA
  - [ ] Accessibility

- https://github.com/Expensify/App/pull/9445
  - [ ] QA
  - [ ] Accessibility

- https://github.com/Expensify/App/pull/9460
  - [ ] QA
  - [ ] Accessibility

- https://github.com/Expensify/App/pull/9462
  - [ ] QA
  - [ ] Accessibility

- https://github.com/Expensify/App/pull/9468
  - [x] QA
  - [x] Accessibility

- https://github.com/Expensify/App/pull/9473
  - [ ] QA
  - [ ] Accessibility


**Internal QA:**
- [x] https://github.com/Expensify/App/pull/9458 - @yuwenmemon @mountiny


**Deploy Blockers:**
- [ ] https://github.com/Expensify/App/issues/9487

**Deployer verifications:**
- [ ] I checked the [App Timing Dashboard](https://graphs.expensify.com/grafana/d/yj2EobAGz/app-timing?orgId=1) and verified this release does not cause a noticeable performance regression.
- [ ] I checked [Firebase Crashlytics](https://console.firebase.google.com/u/0/project/expensify-chat/crashlytics/app/android:com.expensify.chat/issues?state=open&time=last-seven-days&tag=all) and verified that this release does not introduce any new crashes.

cc @Expensify/applauseleads
```

</p>
</details>

## Expected Result:
https://github.com/Expensify/App/issues/9487 should not have been returned in `PRList` by `GithubUtils.getStagingDeployCashData()`.

## Workaround:
Fix the deploy blocker, restart the deploy action

## Platform:
Platform-independent

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by francoisl** [comment]
Note that this is an issue with our Github deploy actions, but I think it should be able to be worked on externally too.

**Comment by roryabraham** [comment]
Got a PR up to fix this.
