### ISSUE TITLE
[$250] HEIC file types disappear when trying to send 

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#9506]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Drag>dropped an HEIC file into NewDot chat and sent
2. File showed it was starting to send
3. File disappeared :rabbit::tophat: (doesn't show at all on my side or receiver's). Or... file keeps showing loading then disappears later, after going to other chats or refreshing. 

## Expected Result:
For file to either show the image or the file name so that it can be downloaded

## Actual Result:
File disappeared

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.77-0
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 

https://user-images.githubusercontent.com/43995119/174723811-2de9bc41-15cf-43dd-bc1a-bd00471d066b.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @mallenexpensify 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1654811005903419

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by bfitzexpensify** [comment]
Upwork job is [here](https://www.upwork.com/jobs/~01bfa1e5e3151717a8)

**Comment by parasharrajat** [comment]
This should be internal. I can say without checking that this file is blocked from the server but the server is not throwing the correct error. 

I am proposing again(I am seeing this similar issue for the fourth time) that we should add a check on the frontend to only allow uploading known files. I agree with the point that there will be many file extensions but it is very important. we should be aware of the files that our app allows to upload. It should be very easy to get the list of supported files from the backend.

**Comment by AndrewGable** [comment]
I'll dig into it a bit further.

**Comment by AndrewGable** [comment]
Closing in favor of an internal issue, this is a dupe https://github.com/Expensify/Expensify/issues/216891
