### ISSUE TITLE
[HOLD for payment 2022-10-20] [$1000] Web - Going from small to large screen and vice-versa clears the field for Email/Password input fields @daraksha-dk

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#9510]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to website
2. Enter your email or password
3. Go from small screen to large screen or vice-versa
4. Input field will be cleared

## Expected Result:
Input values should persist even after the transition

## Actual Result:
 Input gets cleared

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- Desktop App

**Version Number:** 1.1.78.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/174818320-f6c44ea8-851f-4b0b-82b1-0ab255131f3e.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:**  @daraksha-dk

**Slack conversation:**  https://expensify.slack.com/archives/C01GTK53T8Q/p1654874384376709

**Upwork post:** https://www.upwork.com/jobs/~014e254aff1fec823b

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kevinksullivan** [comment]
Hm I'm not able to reproduce this. @kbecciv are you?


https://user-images.githubusercontent.com/22508290/175458931-19549405-22f9-442c-b285-5afa50b7613f.mp4

**Comment by parasharrajat** [comment]
I think there is a very old similar issue somewhere. I don't remember what was decided at that but we should definitely do a lookup.

**Comment by kevinksullivan** [comment]
Bump @parasharrajat ^

**Comment by parasharrajat** [comment]
@kevinksullivan Here is the issue https://github.com/Expensify/App/issues/4226.

**Comment by kevinksullivan** [comment]
Thanks. Issue created and exported.

**Comment by Santhosh-Sellavel** [comment]
Issue Still Reproducible:

https://user-images.githubusercontent.com/85645967/182458748-ae227a4a-e148-47c3-b8e0-077225fc623d.mov

Waiting for proposals!

**Comment by Puneet-here** [comment]
### Proposal

I have checked the previous PR and found that we tried to use two solutions.
1. Moving the state to parent component ([SignInPage.js](https://github.com/Expensify/App/blob/main/src/pages/signin/SignInPage.js))
2. Using onyx, we just have to use account object we can store login, password there and call onyx.merge at onChange.

Both of them works, I prefer onyx more but can go by any of them.

**Comment by Santhosh-Sellavel** [comment]
> I have checked the previous PR and found that we tried to use two solutions.
> 
> 1. Moving the state to parent component ([SignInPage.js](https://github.com/Expensify/App/blob/main/src/pages/signin/SignInPage.js))
> 2. Using onyx, we just have to use account object we can store login, password there and call onyx.merge at onChange.

@Puneet-here which PR are you referring to?
Also, I think ONYX is a kind of over-engineering and should go with 1 instead

What do you say @sketchydroide?

**Comment by Puneet-here** [comment]
This [PR](https://github.com/Expensify/App/pull/4385). 
I am seeing it was decided to use ONYX instead of moving the state.

**Comment by Santhosh-Sellavel** [comment]
Thanks, @Puneet-here. 

Can you write a full proposal with changes in a new comment, so it will be easy to review?

**Comment by Puneet-here** [comment]
Just wanted to know for which approach I have to write the full proposal.
ONYX one as it was decided in the end previously or the first (moving state approach)

**Comment by Santhosh-Sellavel** [comment]
ONYX method @Puneet-here

**Comment by Santhosh-Sellavel** [comment]
Waiting for proposal

**Comment by Santhosh-Sellavel** [comment]
@Puneet-here any update?

**Comment by Puneet-here** [comment]
ONYX method has a drawback. If we control the input with ONYX then on changing the input in the middle takes the cursor to the end, so I will be explaining the state moving method.

### Proposal 

We need to move the states from [LoginForm](https://github.com/Expensify/App/blob/main/src/pages/signin/LoginForm.js) and [PasswordForm](https://github.com/Expensify/App/blob/main/src/pages/signin/PasswordForm.js) to [SignInPage](https://github.com/Expensify/App/blob/main/src/pages/signin/SignInPage.js)

We also have to move the validation and submit function to SignInPage and we just have to pass the value, callback, error and submit function.

Here's the example for LoginForm -
**LoginForm.js**

```diff
@@ -59,8 +51,6 @@ class LoginForm extends React.Component {
     constructor(props) {
         super(props);
         this.onTextInput = this.onTextInput.bind(this);
-        this.validateAndSubmitForm = this.validateAndSubmitForm.bind(this);
-
         this.state = {
             formError: false,
             login: '',
@@ -87,7 +77,7 @@ class LoginForm extends React.Component {
         }
         this.input.focus();

-        if (this.state.login) {
+        if (this.props.login) {
             this.clearLogin();
         }
     }
@@ -98,10 +88,7 @@ class LoginForm extends React.Component {
      * @param {String} text
      */
     onTextInput(text) {
-        this.setState({
-            login: text,
-            formError: null,
-        });
+        this.props.onLoginChange(text);

         if (this.props.account.errors) {
             Session.clearAccountMessages();
@@ -112,45 +99,12 @@ class LoginForm extends React.Component {
      * Clear Login from the state
      */
     clearLogin() {
-        this.setState({login: ''}, this.input.clear);
-    }
-
-    /**
-     * Check that all the form fields are valid, then trigger the submit callback
-     */
-    validateAndSubmitForm() {
-        if (this.props.network.isOffline) {
-            return;
-        }
-
-        const login = this.state.login.trim();
-        if (!login) {
-            this.setState({formError: 'common.pleaseEnterEmailOrPhoneNumber'});
-            return;
-        }
-
-        const phoneLogin = LoginUtils.getPhoneNumberWithoutSpecialChars(login);
-        const isValidPhoneLogin = Str.isValidPhone(phoneLogin);
-
-        if (!Str.isValidEmail(login) && !isValidPhoneLogin) {
-            if (ValidationUtils.isNumericWithSpecialChars(login)) {
-                this.setState({formError: 'common.error.phoneNumber'});
-            } else {
-                this.setState({formError: 'loginForm.error.invalidFormatEmailLogin'});
-            }
-            return;
-        }
-
-        this.setState({
-            formError: null,
-        });
-
-        // Check if this login has an account associated with it or not
-        Session.beginSignIn(isValidPhoneLogin ? phoneLogin : login);
+        this.props.onLoginChange('');
+        this.input.clear();
     }

     render() {
-        const formErrorTranslated = this.state.formError && this.props.translate(this.state.formError);
+        const formErrorTranslated = this.props.error && this.props.translate(this.props.error);
         const error = formErrorTranslated || _.chain(this.props.account.errors || [])
             .keys()
             .sortBy()
@@ -164,7 +118,7 @@ class LoginForm extends React.Component {
                     <TextInput
                         ref={el => this.input = el}
                         label={this.props.translate('loginForm.phoneOrEmail')}
-                        value={this.state.login}
+                        value={this.props.login}
                         autoCompleteType="username"
                         textContentType="username"
                         nativeID="username"
@@ -188,7 +142,7 @@ class LoginForm extends React.Component {
                             <FormAlertWithSubmitButton
                                 buttonText={this.props.translate('common.continue')}
                                 isLoading={this.props.account.isLoading}
-                                onSubmit={this.validateAndSubmitForm}
+                                onSubmit={this.clearLogin}
                                 message={error}
                                 isAlertVisible={!_.isEmpty(error)}
                                 containerStyles={[styles.mh0]}
```

**SignInPage.js**

```diff
@@ -42,12 +51,66 @@ const defaultProps = {
 };

 class SignInPage extends Component {
+    constructor(props) {
+        super(props);
+
+        this.onLoginChange = this.onLoginChange.bind(this);
+        this.validateAndSubmitLoginForm = this.validateAndSubmitLoginForm.bind(this);
+
+        // this.onSubmitPassword = this.onSubmitPassword.bind(this);
+
+        this.state = {
+            login: '',
+            password: '',
+            loginError: '',
+            passwordError: '',
+        };
+    }
+
     componentDidMount() {
         // Always reset the unread counter to zero on this page
         // NOTE: We need to wait for the next tick to ensure that the unread indicator is updated
         setTimeout(() => updateUnread(0), 0);
     }

+    onLoginChange(text) {
+        this.setState({login: text, loginError: null});
+    }
+
+    /**
+     * Check that all the form fields are valid, then trigger the submit callback
+     */
+    validateAndSubmitLoginForm() {
+        if (this.props.network.isOffline) {
+            return;
+        }
+
+        const login = this.state.login.trim();
+        if (!login) {
+            this.setState({loginError: 'common.pleaseEnterEmailOrPhoneNumber'});
+            return;
+        }
+
+        const phoneLogin = LoginUtils.getPhoneNumberWithoutSpecialChars(login);
+        const isValidPhoneLogin = Str.isValidPhone(phoneLogin);
+
+        if (!Str.isValidEmail(login) && !isValidPhoneLogin) {
+            if (ValidationUtils.isNumericWithSpecialChars(login)) {
+                this.setState({loginError: 'common.error.phoneNumber'});
+            } else {
+                this.setState({loginError: 'loginForm.error.invalidFormatEmailLogin'});
+            }
+            return;
+        }
+
+        this.setState({
+            loginError: null,
+        });
+
+        // Check if this login has an account associated with it or not
+        Session.beginSignIn(isValidPhoneLogin ? phoneLogin : login);
+    }
+
     render() {
         // Show the login form if
         // - A login has not been entered yet
@@ -81,7 +144,14 @@ class SignInPage extends Component {
                 >
                     {/* LoginForm and PasswordForm must use the isVisible prop. This keeps them mounted, but visually hidden
                     so that password managers can access the values. Conditionally rendering these components will break this feature. */}
-                    <LoginForm isVisible={showLoginForm} blurOnSubmit={shouldShowResendValidationLinkForm} />       
+                    <LoginForm
+                        isVisible={showLoginForm}
+                        blurOnSubmit={shouldShowResendValidationLinkForm}
+                        login={this.state.login}
+                        onLoginChange={this.onLoginChange}
+                        error={this.state.loginError}
+                        validateAndSubmitForm={this.validateAndSubmitLoginForm}
+                    />
                     <PasswordForm isVisible={showPasswordForm} />
                     {shouldShowResendValidationLinkForm && <ResendValidationForm />}
                 </SignInPageLayout>
```

Not showing some small changes like Proptypes and stuff.

**Comment by kevinksullivan** [comment]
@joekaufmanexpensify going OOO for a bit so want to make sure this gets attention when it moves forward.

**Comment by joekaufmanexpensify** [comment]
Sounds good! Given this has already been exported to Upwork, I think this should be assigned to the contributor management team, based on this [SO](https://stackoverflow.com/c/expensify/questions/8582/8583#8583). 

Re-assigning based on that!

**Comment by Santhosh-Sellavel** [comment]
Waiting for a better proposal, using ONYX should be an ideal choice.

**Comment by mollfpr** [comment]
@Santhosh-Sellavel If we using Onyx, should the value input still persist after refreshing the app?

**Comment by Santhosh-Sellavel** [comment]
On refreshing, we should clear the data

**Comment by mollfpr** [comment]
### Proposal

#### Root cause
The `LoginForm` and `PasswordForm` is remounted when the dimension screen is changed to use a different layout. Because of that remount, the state value is reset.

#### Solution
Saving the login and password value to Onyx and initiating the value to the state.

1. Add new Onyx keys to the constants file and create the action to set the value to Onyx
`src/ONYXKEYS.js`
```js
LOGIN_FORM_VALUE: 'loginFormValue',
PASSWORD_FORM_VALUE: 'passwordFormValue',
```

`src/libs/actions/Session/index.js`
```js
function persistLoginValue(text) {
    Onyx.set(ONYXKEYS.LOGIN_FORM_VALUE, text);
}
function persistPasswordValue(text) {
    Onyx.set(ONYXKEYS.PASSWORD_FORM_VALUE, text);
}
```

2. Updating the `LoginForm` to have the Onyx value and set it to state
```diff
        this.state = {
            formError: false,
+            login: props.loginFormValue,
        };
```
```diff
    componentDidUpdate(prevProps, prevState) {
+        if (prevState.login !== this.state.login) {
+            Session.persistLoginValue(this.state.login);
+        }
```
```diff
    withOnyx({
        account: {key: ONYXKEYS.ACCOUNT},
+        loginFormValue: {key: ONYXKEYS.LOGIN_FORM_VALUE},
```

3. Updating the `PasswordForm` to have the Onyx value and set it to state
```diff
        this.state = {
            formError: false,
+            password: props.passwordFormValue,
```
```diff
    componentDidUpdate(prevProps, prevState) {
+        if (prevState.password !== this.state.password) {
+            Session.persistPasswordValue(this.state.password);
+        }
```
```diff
    withOnyx({
        account: {key: ONYXKEYS.ACCOUNT},
+        passwordFormValue: {key: ONYXKEYS.PASSWORD_FORM_VALUE},
```

4. We also need to reset the login and password value when the user just opens the app or refreshes the app. To do that I'm calling the `persistLoginValue` and `persistPasswordValue` inside `SignInPage` when mount.
```diff
    componentDidMount() {
+        Session.persistLoginValue('');
+        Session.persistPasswordValue('');
```


#### Result

**Web**

https://user-images.githubusercontent.com/25520267/187014079-a3b164c9-a200-4cfd-ab33-07c3e07f8107.mov


**Desktop**


https://user-images.githubusercontent.com/25520267/187014088-72dbf721-380e-4683-9711-81a021499bb4.mov

**Comment by Santhosh-Sellavel** [comment]
@sketchydroide 
@mollfpr's proposal looks good to me!

Just one concern.
I think we should use one of the existing keys, ACCOUNT or CREDENTIALS to store these temp values instead of creating a new ONYXKEYS. What do you say?

C+ Reviewed
🎀 👀 🎀 

Thanks!

cc: @puneetlath

**Comment by mollfpr** [comment]
We can use the `ACCOUNT` key, and I think we can make it more simple to use only 1 key to holding the temp value for login/password.

**Comment by Santhosh-Sellavel** [comment]
Waiting for CME review

**Comment by sketchydroide** [comment]
I think we are still waiting?

**Comment by puneetlath** [comment]
@sketchydroide the proposal that @Santhosh-Sellavel recommended we go forward with is: https://github.com/Expensify/App/issues/9510#issuecomment-1230776346

**Comment by mollfpr** [comment]
Bump @sketchydroide

**Comment by Santhosh-Sellavel** [comment]
Waiting for you review @sketchydroide

**Comment by mollfpr** [comment]
Bump @sketchydroide 👀

**Comment by puneetlath** [comment]
I'm going to take this over since it seems @sketchydroide is OOO. 

Question -- why is the LoginForm re-mounting when the screen size updates? I'm not necessarily against the proposal. But is there an alternative where the form doesn't need to re-mount when re-sizing?

**Comment by mollfpr** [comment]
We have 3 different styles of layout to show the `LoginForm` / `PasswordForm`, each of the styles has a different layout structure based on device screen width.

I couldn't find a way to refactor the layout to prevent the re-render. It's wrapped with different structures and styles.
```js
    if (props.isSmallScreenWidth) {
        return content;
    }

    if (props.isMediumScreenWidth && props.windowHeight >= variables.minHeightToShowGraphics) {
        return (
            <View style={[styles.dFlex, styles.signInPageInner, styles.flexColumnReverse, styles.justifyContentBetween]}>
                {graphicLayout}
                <View style={styles.flex1}>
                    {content}
                </View>
            </View>
        );
    }

    return (
        <View style={[styles.flex1, styles.signInPageInner]}>
            <View style={[styles.flex1, styles.flexRow, styles.flexGrow1]}>
                {content}
                {graphicLayout}
            </View>
        </View>
    );
```

@puneetlath @Santhosh-Sellavel

**Comment by mollfpr** [comment]
Bump @puneetlath

**Comment by Santhosh-Sellavel** [comment]
> Saving values to Onyx means saving them to local storage.
Saving sensitive info like email, password, 2fa code in local storage has security vulnerability. Especially, storing password is not a good idea for security.

I believe there is no issue saving it temporarily, as we would clear the data once the login is successful.

@puneetlath Let me know your thoughts.

**Comment by mollfpr** [comment]
I have another proposal that will prevent the children (`LoginForm`, `PasswordForm`, and `ResendValidationForm`) from re-render.

```diff
diff --git a/src/pages/signin/SignInPageLayout/index.js b/src/pages/signin/SignInPageLayout/index.js
index ebe72e30e..a38ec6ed9 100644
--- a/src/pages/signin/SignInPageLayout/index.js
+++ b/src/pages/signin/SignInPageLayout/index.js
@@ -58,26 +58,27 @@ const SignInPageLayout = (props) => {
         </Pressable>
     );

-    if (props.isSmallScreenWidth) {
-        return content;
+    const isLongMiddleScreen = props.isMediumScreenWidth && props.windowHeight >= variables.minHeightToShowGraphics;
+
+    let containerStyles = [];
+    let contentStyles = [];
+
+    if (isLongMiddleScreen) {
+        containerStyles = [styles.dFlex, styles.signInPageInner, styles.flexColumnReverse, styles.justifyContentBetween];
+        contentStyles = [styles.flex1, styles.flexGrow1];
     }

-    if (props.isMediumScreenWidth && props.windowHeight >= variables.minHeightToShowGraphics) {
-        return (
-            <View style={[styles.dFlex, styles.signInPageInner, styles.flexColumnReverse, styles.justifyContentBetween]}>
-                {graphicLayout}
-                <View style={styles.flex1}>
-                    {content}
-                </View>
-            </View>
-        );
+    if (!props.isSmallScreenWidth && !isLongMiddleScreen) {
+        containerStyles = [styles.flex1, styles.signInPageInner];
+        contentStyles = [styles.flex1, styles.flexRow, styles.flexGrow1];
     }

     return (
-        <View style={[styles.flex1, styles.signInPageInner]}>
-            <View style={[styles.flex1, styles.flexRow, styles.flexGrow1]}>
+        <View style={containerStyles}>
+            {isLongMiddleScreen && graphicLayout}
+            <View style={contentStyles}>
                 {content}
-                {graphicLayout}
+                {!props.isSmallScreenWidth && !isLongMiddleScreen && graphicLayout}
             </View>
         </View>
     );
```

Only change the styles and re-render the `graphicLayout` when the screen size is changed.

**Result**


https://user-images.githubusercontent.com/25520267/190890817-1ecad7ed-7b37-4966-ae17-033f60f2d1fe.mov


https://user-images.githubusercontent.com/25520267/190890841-35cfca63-105a-46ac-b698-7c0f8614f28f.mov

cc @Santhosh-Sellavel @puneetlath

**Comment by puneetlath** [comment]
I like this approach a lot better. However, I don't think the CPA card image should be showing below the form for the medium size screen.

**Comment by shawnborton** [comment]
I think we should handle any of the design suggestions as a separate issue. For this particular issue at hand, I think we'd just want to fix the form itself.

**Comment by puneetlath** [comment]
Ahh, my fault, I didn't realize it's already like that. I realize now that if your screen is tall enough (yours is much taller than mine) then it is below.

**Comment by mollfpr** [comment]
@puneetlath Yes, in the video I’m zooming out my browser to present the change when on tall screen size.

**Comment by mollfpr** [comment]
@puneetlath @Santhosh-Sellavel thoughts https://github.com/Expensify/App/issues/9510#issuecomment-125109841?

**Comment by Santhosh-Sellavel** [comment]
@mollfpr which comment are you referring too?

**Comment by mollfpr** [comment]
@Santhosh-Sellavel Any proposal you guys selected?

**Comment by mollfpr** [comment]
Hi @Santhosh-Sellavel @puneetlath any thoughts on the proposals?

**Comment by Santhosh-Sellavel** [comment]
@mollfpr We are evaluating the proposals will let you know thanks!

**Comment by puneetlath** [comment]
Sounds good. I agree with that logic. Thanks for your proposal @mollfpr but in this case we will go with @aimane-chnaif.

**Comment by puneetlath** [comment]
@aimane-chnaif can you apply to the Upwork job here when you have a chance: https://www.upwork.com/jobs/~014e254aff1fec823b

**Comment by puneetlath** [comment]
@aimane-chnaif @Santhosh-Sellavel how's this going? Looks like the PR is close?

**Comment by Santhosh-Sellavel** [comment]
Yeah, mostly will be ready for your review by today!

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by puneetlath** [comment]
All paid. Thanks everyone!
