### ISSUE TITLE
Create a FullPageNotFoundView component

### ISSUE THREAD

**Issue by arosiclair** [Expensify/App#9522]
[Spun out of this slack convo](https://expensify.slack.com/archives/C02HWMSMZEC/p1655833957774829)

**Problem**
Similar to our `<FullPageOfflineView />` (https://github.com/Expensify/App/pull/9165) we need a full page "not found" view to display when a user attempts to view a resource that doesn't exist or they have lost access to.

**Solution**
Create a `<FullPageNotFoundView />` component that replaces the child view when a `show` prop is set to `true`.

**Comment by arosiclair** [comment]
I'll implement this this week.

**Comment by shawnborton** [comment]
Totally. We could do something very generic like the offline page you mentioned, something like this?
![image](https://user-images.githubusercontent.com/2319350/176546520-9dece21c-12f1-40cc-943a-caa3c40b4c26.png)


Questions:
- Would this page only be shown when navigating things in the workspace editor, etc? Or do we need to consider a full app blocking page, almost like a classic 404 page?

**Comment by arosiclair** [comment]
@shawnborton Thanks!

> Would this page only be shown when navigating things in the workspace editor, etc? Or do we need to consider a full app blocking page, almost like a classic 404 page?

Your first guess is correct though it could also be used for other non-workspace pages. This view would replace the content of the page/pane that can't be viewed in the same way that our offline blocking page would.

**Comment by shawnborton** [comment]
Sounds good! 

I think the question mark circle icon already exists in the App repo, so you should be good to just reuse it and style it like the offline page. Feel free to tag design in your PR too!

**Comment by jamesdeanexpensify** [comment]
Do we need copy for both screens? https://github.com/Expensify/App/issues/9522#issuecomment-1170502960

**Comment by shawnborton** [comment]
Just the screen on the right. Basically need a title, and then a small blurb underneath.

**Comment by jamesdeanexpensify** [comment]
What about: "Hmm...it's not here." for title and then for blurb: "The page is nowhere to be found."

**Comment by jamesdeanexpensify** [comment]
Ah, I actually suggested the opposite. How would that look?

**Comment by shawnborton** [comment]
Oh crap, my bad! Here is an updated screenie:

![image](https://user-images.githubusercontent.com/2319350/176784968-2d6d9471-db10-4f63-a976-86f187a0985e.png)

**Comment by jamesdeanexpensify** [comment]
Maybe "That page..." instead of "The page"...what do you think?

**Comment by jamesdeanexpensify** [comment]
Discussing the last bits here: https://expensify.slack.com/archives/C03SSAQG5/p1656631441234379?thread_ts=1656618417.749959&cid=C03SSAQG5

**Comment by jamesdeanexpensify** [comment]
Will have this finalized tomorrow. It's a really small tweaks, but I want to make sure I'm following the process that I'm creating!

**Comment by jamesdeanexpensify** [comment]
I think for now since it's more of a header/title, we can leave "Hmm...it's not here" it without a period. Let's ship it!

**Comment by jamesdeanexpensify** [comment]
And by ship it, I mean this: https://github.com/Expensify/App/issues/9522#issuecomment-1171722664

**Comment by arosiclair** [comment]
Thanks guys! Getting a Spanish translation for this and then this should be through very soon.
