### ISSUE TITLE
Chat - Sending links google.com and http://www.google.com/ appears as http:// instead of https://

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#9533]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
Issue was found when executing #9471 
## Action Performed:
1. Go to staging.new.expensify.com and login
2. Send links google.com and [www.google.com](http://www.google.com/)

## Expected Result:
In the chat it should appear as https://google.com/

## Actual Result:
It appears as http://google.com/

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Desktop App
- Mobile Web

**Version Number:** 1.1.78-7

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/175098353-97e757ab-8d3b-410e-bf3b-a274dae11ee1.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** 
Applause internal team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Julesssss** [comment]
The links do redirect to https, but I see that we show the URL as http. I think this issue should have been raised in the PR which introduced it though. I'll link it now.

**Comment by Santhosh-Sellavel** [comment]
> The links do redirect to https, but I see that we show the URL as http.

You may have tried with popular websites like google, they won't allow 'http://' urls.

Try 'http://google.com' in browser it would get automatically redirected to 'https://' site.

Same happens in this case too.

**Comment by Julesssss** [comment]
I agree the link works as expected, but it's not showing the correct URL in the tooltip.

**Comment by Julesssss** [comment]
I think the PR fixed one case only. Posted more info in the original PR: https://github.com/Expensify/App/pull/9471#issuecomment-1168704378

**Comment by Santhosh-Sellavel** [comment]
@Julesssss Just now verified everything looks good for me in staging.

https://user-images.githubusercontent.com/85645967/176236102-98094292-85fe-4778-b801-22eb2687fe8f.mov

**Comment by Julesssss** [comment]
Yep, I see the same thing now. Still not sure why it partially worked until now :/
