### ISSUE TITLE
[Feature Request] Allow "pending" attachments to be deleted and downloaded before they are created in the server

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#9541]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensify.com
2. Log in with any account
3. Go to any user and click on Plus button
4. Attach any jpg file
5. Click Send button
6. Hover to the other side and check the menu option

## Expected Result:
Optional menu is not changing from 3 to 5 options after sent attachment

## Actual Result:
Optional menu is changing from 3 to 5 options after sent attachment

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.78.7

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation
![image (25)](https://user-images.githubusercontent.com/93399543/175128588-4bad0ab1-a08e-4665-a9a7-7116fd5fbc93.png)
![image (24)](https://user-images.githubusercontent.com/93399543/175128593-59101fae-e99b-4da5-af8b-d40019e6e6eb.png)

https://user-images.githubusercontent.com/93399543/175128594-2e5c5da4-b328-4708-8e88-fe3c8b7c8eb3.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by marcaaron** [comment]
I'm not sure there's any bug here and the behavior is expected. The option to download or delete is only available after the attachment is uploaded. That said, I think we can consider adding the ability to download or delete a "pending" attachment. Going to make this internal so that someone with cycles can investigate.

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (Second week)

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (Third week) Closing
