### ISSUE TITLE
[$500] [Form Refactor] AddPlaidBankAccount

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#9577]
Coming from the [New Expensify Forms](https://docs.google.com/document/d/1DI4jQ0nyfi2JczhPT440orwlXsTP_O-aGvg-HLmcbwI/edit#heading=h.mnjguil21u0a) design doc, we should refactor [AddPlaidBankAccount](https://github.com/Expensify/App/blob/main/src/components/AddPlaidBankAccount.js) to use the new form component, follow the guidelines below:

Here's an example of a Form refactor: https://github.com/Expensify/App/pull/9056

## Guidelines
1. Replace the form component with Form.js.
2. Create a unique Onyx key in ONYXKEYS.FORM and pass it as the [formID](https://docs.google.com/document/d/15qBqIaRnuuOWpAz50Oc4U-873txonRqCaeBkrseN_8I/edit#heading=h.789lf03wn9l8) prop to Form.
3. Pass a [validate](https://docs.google.com/document/d/15qBqIaRnuuOWpAz50Oc4U-873txonRqCaeBkrseN_8I/edit#heading=h.vudloacn1xep) callback prop.
4. Pass an [onSubmit](https://docs.google.com/document/d/15qBqIaRnuuOWpAz50Oc4U-873txonRqCaeBkrseN_8I/edit#heading=h.a9p9e5um34c2) callback prop that calls the API via an action.
5. Update all inputs wrapped by Form, following the guidelines in [Refactor inputs](https://docs.google.com/document/d/1DI4jQ0nyfi2JczhPT440orwlXsTP_O-aGvg-HLmcbwI/edit#bookmark=kix.ao8ypttnbmcj).
6. Remove any unused code.

## Testing
Verify that:
- [ ] UI looks as it did before the refactor
- [ ] Values can be added and edited
- [ ] Errors are highlighted correctly (input border)
- [ ] Error messages show up correctly
- [ ] Draft values are saved properly
- [ ] Form alerts are displayed correctly
- [ ] Clicking the `fix the errors` link focuses the first input with error
- [ ] No duplicate submission of the form occurs (when it's already submitting)

**Comment by luacmartins** [comment]
This issue is being put on hold because of push to page discussion, as per [this comment](https://github.com/Expensify/App/issues/9579#issuecomment-1169229996).

**Comment by liyamahendra** [comment]
@luacmartins I understand this issue is on hold. Just leaving a comment expressing my interested in this task. I believe my relevant experience doing `Form` implementation in the `ProfilePage` can prove useful while doing this refactor.

This comment will share updates with me over email, but would be helpful if you can let me know when this issue is ready to work on and if I can take this up! :)

**Comment by Santhosh-Sellavel** [comment]
on hold

**Comment by Santhosh-Sellavel** [comment]
on hold

**Comment by luacmartins** [comment]
@puneetlath @Santhosh-Sellavel @liyamahendra this issue is no longer on hold

**Comment by puneetlath** [comment]
Great! @liyamahendra feel free to make a proposal if you're still interested.

**Comment by HafeezRai** [comment]
Can i resolve this issue i have experience with RN

**Comment by puneetlath** [comment]
@HafeezRai feel free to make a proposal. You can look at our [contributing guide](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md) and other issues in this repo to get a sense of how to do so.

**Comment by puneetlath** [comment]
Updated to $500.

**Comment by Santhosh-Sellavel** [comment]
Waiting for proposals

**Comment by puneetlath** [comment]
@luacmartins I think I'm going to take this on myself to get familiar with the new form component. 

I was looking at `addPlaidBankAccount` and it's not _really_ a form of its own. The component handles calling plaid getting the data and then renders a picker to select the bank accounts that plaid returned. It doesn't have a submit button or anything. 

The selection on that form is then used by a form in the `AddPersonalBankAccountPage` and `BankAccountStep` (https://github.com/Expensify/App/issues/9579) components. 

So I think the form refactor would actually happen on those two components and not on the `addPlaidBankAccount` component. Do you agree with that?

**Comment by luacmartins** [comment]
Thanks for the interest in this @puneetlath! 

What you said is correct, although we should refactor [this part](https://github.com/Expensify/App/blob/3cef13d5e1012dc99036d7f8c1693686d436ad4f/src/components/AddPlaidBankAccount.js#L180-L204) in AddPlaidBankAccount, in addition to AddPersonalBankAccountPage and BankAccountStep.

**Comment by Santhosh-Sellavel** [comment]
Not overdue, worked internally

**Comment by youssef-lr** [comment]
Hey @puneetlath! If you've got a lot on your plate I wouldn't mind working on this, I have a Form refactoring PR in review and could start working on this while review is ongoing.

**Comment by puneetlath** [comment]
Ok sounds good! Feel free to take it.
