### ISSUE TITLE
[HOLD for payment 2022-10-12] [$1000][Form Refactor] BankAccountStep

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#9579]
Coming from the [New Expensify Forms](https://docs.google.com/document/d/1DI4jQ0nyfi2JczhPT440orwlXsTP_O-aGvg-HLmcbwI/edit#heading=h.mnjguil21u0a) design doc, we should refactor [BankAccountStep](https://github.com/Expensify/App/blob/main/src/pages/ReimbursementAccount/BankAccountStep.js) to use the new form component, follow the guidelines below:

Here's an example of a Form refactor: https://github.com/Expensify/App/pull/9056

## Guidelines
1. Replace the form component with Form.js.
2. Create a unique Onyx key in ONYXKEYS.FORM and pass it as the [formID](https://docs.google.com/document/d/15qBqIaRnuuOWpAz50Oc4U-873txonRqCaeBkrseN_8I/edit#heading=h.789lf03wn9l8) prop to Form.
3. Pass a [validate](https://docs.google.com/document/d/15qBqIaRnuuOWpAz50Oc4U-873txonRqCaeBkrseN_8I/edit#heading=h.vudloacn1xep) callback prop.
4. Pass an [onSubmit](https://docs.google.com/document/d/15qBqIaRnuuOWpAz50Oc4U-873txonRqCaeBkrseN_8I/edit#heading=h.a9p9e5um34c2) callback prop that calls the API via an action.
5. Update all inputs wrapped by Form, following the guidelines in [Refactor inputs](https://docs.google.com/document/d/1DI4jQ0nyfi2JczhPT440orwlXsTP_O-aGvg-HLmcbwI/edit#bookmark=kix.ao8ypttnbmcj).
6. Remove any unused code.

## Testing
Verify that:
- [ ] UI looks as it did before the refactor
- [ ] Values can be added and edited
- [ ] Errors are highlighted correctly (input border)
- [ ] Error messages show up correctly
- [ ] Draft values are saved properly
- [ ] Form alerts are displayed correctly
- [ ] Clicking the `fix the errors` link focuses the first input with error
- [ ] No duplicate submission of the form occurs (when it's already submitting)

**Job Post:** https://www.upwork.com/jobs/~015df14d7f44106b74

**Comment by liyamahendra** [comment]
@luacmartins I did a similar work on https://github.com/Expensify/App/issues/9234 and would be happy to take this up. 

Since this isn't an usual bug, should I propose the changes required for making the `BankAccountStep` to use `Form` or you expect something else as a part of the proposal?

**Comment by kevinksullivan** [comment]
Oh... I agree. This will change as a result of the explorations we're working on. :nobodyreads: sorry @luacmartins , I agree we should hold on this.

**Comment by luacmartins** [comment]
Fair enough! When do we plan to discuss push to page?

**Comment by kevinksullivan** [comment]
>Fair enough! When do we plan to discuss push to page?

Next week. the other N7 initiatives have taken priority lately.

**Comment by neil-marcellini** [comment]
Is this still on hold or have we discussed push to page? https://github.com/Expensify/App/issues/9581 is holding for the same reason.

**Comment by kevinksullivan** [comment]
No, we have held these conversations (and essentially all others) so everyone stays focused on N7 / refactor.

**Comment by iwiznia** [comment]
On hold melvin

**Comment by marcaaron** [comment]
Can someone summarize why this is on HOLD? Could we not finish what we started and then iterate on top of that? Do we expect push to page to significantly change the design of the existing forms or to build on that system?

**Comment by marcaaron** [comment]
This is like just swapping out some existing code for a smaller new component with default behaviors right? Not exactly a major redesign (since the VBA flows already follow the best practices for forms) or refactor.

**Comment by luacmartins** [comment]
I'm down for removing the hold. I think any solutions we end up with should build on top of the current Form component. @iwiznia do you have any concerns regarding this?

**Comment by neil-marcellini** [comment]
I agree it would be good to remove the hold.

**Comment by iwiznia** [comment]
No concerns

**Comment by luacmartins** [comment]
Cool then! Removing the hold on all form refactor issues!

**Comment by luacmartins** [comment]
@kevinksullivan can you please post this job on upwork?

**Comment by kevinksullivan** [comment]
Doubled

**Comment by liyamahendra** [comment]
@kevinksullivan I would be interested in taking this up. @luacmartins [shared](https://github.com/Expensify/App/issues/9579#issuecomment-1169024445) that no proposal is required, just need to express interest. Does this still hold true or you would like me to place a proposal before beginning work on this?

**Comment by mananjadhav** [comment]
@liyamahendra Thanks for the interest. While @luacmartins mentioned proposal is not needed, I would strongly recommend having one. Two reasons: 

1. to keep the process consistent and have no surprises later on for PR rework.
2. Bank form is a little different than Debit Card page, with subStep.

We can still wait for @luacmartins to confirm if the proposal is needed.

**Comment by luacmartins** [comment]
I think what @mananjadhav said makes sense. Let's add a proposal to it beforehand to make sure that we are all on the same page.

**Comment by kevinksullivan** [comment]
Reassigning as I'm OOO for a bit. Thanks @dylanexpensify !

**Comment by dylanexpensify** [comment]
Sounds good! Have a good time off @kevinksullivan !

**Comment by liyamahendra** [comment]
@mananjadhav @luacmartins I was preparing the proposal. Seems like there are three major nodes based on conditions: 
1. [ScrollView](https://github.com/Expensify/App/blob/f39e1f215d753bfe54a964a0b4b1fd29a065d8ed/src/pages/ReimbursementAccount/BankAccountStep.js#L210)
2. [FormScrollView](https://github.com/Expensify/App/blob/f39e1f215d753bfe54a964a0b4b1fd29a065d8ed/src/pages/ReimbursementAccount/BankAccountStep.js#L277)
3. [ReimbursementAccountForm](https://github.com/Expensify/App/blob/f39e1f215d753bfe54a964a0b4b1fd29a065d8ed/src/pages/ReimbursementAccount/BankAccountStep.js#L304)

Does this issue need to only replace `ScrollView` or the other two as well?

**Comment by luacmartins** [comment]
@liyamahendra it should replace all of them!

**Comment by dylanexpensify** [comment]
Not overdue, any update @liyamahendra?

**Comment by liyamahendra** [comment]
@dylanexpensify my availability has changed (busy on other project), so I won't be able to take this up please.

**Comment by dylanexpensify** [comment]
cc @luacmartins @mananjadhav ^

**Comment by luacmartins** [comment]
Still looking for proposals

**Comment by mananjadhav** [comment]
@luacmartins @dylanexpensify Should we double this?

**Comment by luacmartins** [comment]
Yes, @dylanexpensify let's double this issue

**Comment by dylanexpensify** [comment]
Hmm, I can't see a job for this issue - do we need to create one?

**Comment by mananjadhav** [comment]
> Job Post: https://www.upwork.com/jobs/~015df14d7f44106b74

I thought the job post in the GH body is the one.

**Comment by dylanexpensify** [comment]
Ah nice one @mananjadhav - thank you! Will double now!

**Comment by jayeshmangwani** [comment]
### Proposal

Changes need to be done on the BankAccountStep page

replaced form component with Form.js
added keys to ONYXKEYS.FORM and passed to the Form.js
created 2 functions according to the latest Form.js requirements `validate` an `onSubmit`
updated input fields according to guideline that is accessible from #9056
removed unused code

https://github.com/Expensify/App/blob/11761bea9de7604febd17da05797c62caf2a2f6b/src/pages/ReimbursementAccount/BankAccountStep.js#L26-L27

```diff
src/pages/ReimbursementAccount/BankAccountStep.js


import ONYXKEYS from '../../ONYXKEYS';
import compose from '../../libs/compose';
-import * as ReimbursementAccountUtils from '../../libs/ReimbursementAccountUtils';
-import ReimbursementAccountForm from './ReimbursementAccountForm';
-import reimbursementAccountPropTypes from './reimbursementAccountPropTypes';
import Section from '../../components/Section';


import Button from '../../components/Button';
-import FormScrollView from '../../components/FormScrollView';
-import FormAlertWithSubmitButton from '../../components/FormAlertWithSubmitButton';
+import Form from '../../components/Form';

const propTypes = {
-    /** Bank account currently in setup */
-    // eslint-disable-next-line react/no-unused-prop-types
-    reimbursementAccount: reimbursementAccountPropTypes.isRequired,
-
    /** The OAuth URI + stateID needed to re-initialize the PlaidLink after the user logs into their bank */
    receivedRedirectURI: PropTypes.string,
    
    constructor(props) {
  super(props);

-  this.toggleTerms = this.toggleTerms.bind(this);
  this.addManualAccount = this.addManualAccount.bind(this);
  this.addPlaidAccount = this.addPlaidAccount.bind(this);
-  this.state = {
-      selectedPlaidBankAccount: undefined,
-      hasAcceptedTerms: ReimbursementAccountUtils.getDefaultStateForField(props, 'acceptTerms', true),
-      routingNumber: ReimbursementAccountUtils.getDefaultStateForField(props, 'routingNumber'),
-      accountNumber: ReimbursementAccountUtils.getDefaultStateForField(props, 'accountNumber'),
-  };
-
-  // Keys in this.errorTranslationKeys are associated to inputs, they are a subset of the keys found in this.state
-  this.errorTranslationKeys = {
-      routingNumber: 'bankAccount.error.routingNumber',
-      accountNumber: 'bankAccount.error.accountNumber',
-      hasAcceptedTerms: 'common.error.acceptedTerms',
-  };
-
-  this.getErrorText = inputKey => ReimbursementAccountUtils.getErrorText(this.props, this.errorTranslationKeys, inputKey);
-  this.clearError = inputKey => ReimbursementAccountUtils.clearError(this.props, inputKey);
-  this.getErrors = () => ReimbursementAccountUtils.getErrors(this.props);
-}
-
-toggleTerms() {
-  this.setState((prevState) => {
-      const hasAcceptedTerms = !prevState.hasAcceptedTerms;
-      BankAccounts.updateReimbursementAccountDraft({acceptTerms: hasAcceptedTerms});
-      return {hasAcceptedTerms};
-  });
-  this.clearError('hasAcceptedTerms');
+  this.validate = this.validate.bind(this);
+  this.validatePlaidAccount = this.validatePlaidAccount.bind(this);
}



/**
 * @returns {Boolean}
 */
-  validate() {
+  validate(values) {
      const errors = {};

-      if (!CONST.BANK_ACCOUNT.REGEX.US_ACCOUNT_NUMBER.test(this.state.accountNumber.trim())) {
-          errors.accountNumber = true;
+      if (!values.accountNumber || !CONST.BANK_ACCOUNT.REGEX.US_ACCOUNT_NUMBER.test(values.accountNumber.trim())) {
+          errors.accountNumber = this.props.translate('bankAccount.error.accountNumber');
      }
-      if (!CONST.BANK_ACCOUNT.REGEX.SWIFT_BIC.test(this.state.routingNumber.trim()) || !ValidationUtils.isValidRoutingNumber(this.state.routingNumber.trim())) {
-          errors.routingNumber = true;
+      if (!values.routingNumber || !CONST.BANK_ACCOUNT.REGEX.SWIFT_BIC.test(values.routingNumber.trim()) || !ValidationUtils.isValidRoutingNumber(values.routingNumber.trim())) {
+          errors.routingNumber = this.props.translate('bankAccount.error.routingNumber');
      }
-      if (!this.state.hasAcceptedTerms) {
-          errors.hasAcceptedTerms = true;
+      if (!values.acceptedTerms) {
+          errors.acceptedTerms = this.props.translate('common.error.acceptedTerms');
      }

-      BankAccounts.setBankAccountFormValidationErrors(errors);
-      return _.size(errors) === 0;
+      return errors;
  }
  
  -    /**
-     * Clear the error associated to inputKey if found and store the inputKey new value in the state.
-     *
-     * @param {String} inputKey
-     * @param {String} value
-     */
-     clearErrorAndSetValue(inputKey, value) {
-      const newState = {[inputKey]: value};
-      this.setState(newState);
-      BankAccounts.updateReimbursementAccountDraft(newState);
-      this.clearError(inputKey);
-  }

-  addManualAccount() {
-      if (!this.validate()) {
-          return;
+  validatePlaidAccount(values) {
+      const errors = {};
+      if (_.isUndefined(values.selectedPlaidBankAccount)) {
+          errors.selectedPlaidBankAccount = this.props.translate('bankAccount.error.noBankAccountSelected');
+      }

+      return errors;
+  }
+
+  addManualAccount(values) {
      BankAccounts.setupWithdrawalAccount({
-          acceptTerms: this.state.hasAcceptedTerms,
-          accountNumber: this.state.accountNumber,
-          routingNumber: this.state.routingNumber,
+          acceptTerms: values.acceptedTerms,
+          accountNumber: values.accountNumber,
+          routingNumber: values.routingNumber,
          setupType: CONST.BANK_ACCOUNT.SETUP_TYPE.MANUAL,

          // Note: These are hardcoded as we're not supporting AU bank accounts for the free plan
@@ -150,11 +109,9 @@ class BankAccountStep extends React.Component {
  /**
   * Add the Bank account retrieved via Plaid in db
   */
-  addPlaidAccount() {
-      const selectedPlaidBankAccount = this.state.selectedPlaidBankAccount;
-      if (!this.state.selectedPlaidBankAccount) {
-          return;
-      }
+  addPlaidAccount(values) {
+      const selectedPlaidBankAccount = values.selectedPlaidBankAccount;
+
      BankAccounts.setupWithdrawalAccount({
          acceptTerms: true,
          setupType: CONST.BANK_ACCOUNT.SETUP_TYPE.PLAID,
@@ -185,8 +142,6 @@ class BankAccountStep extends React.Component {
      const subStep = shouldReinitializePlaidLink ? CONST.BANK_ACCOUNT.SETUP_TYPE.PLAID : this.props.achData.subStep;
      const plaidDesktopMessage = getPlaidDesktopMessage();
      const bankAccountRoute = `${CONFIG.EXPENSIFY.NEW_EXPENSIFY_URL}${ROUTES.BANK_ACCOUNT}`;
-      const error = lodashGet(this.props, 'reimbursementAccount.error', '');
-      const loading = lodashGet(this.props, 'reimbursementAccount.loading', false);
      const validated = lodashGet(this.props, 'user.validated', false);
      return (
          <View style={[styles.flex1, styles.justifyContentBetween]}>
@@ -274,36 +229,30 @@ class BankAccountStep extends React.Component {
                  </ScrollView>
              )}
              {subStep === CONST.BANK_ACCOUNT.SETUP_TYPE.PLAID && (
  
  -<FormScrollView>
-<View style={[styles.mh5, styles.mb5]}>
-    <AddPlaidBankAccount
-        text={this.props.translate('bankAccount.plaidBodyCopy')}
-        onSelect={(params) => {
-            this.setState({
-                selectedPlaidBankAccount: params.selectedPlaidBankAccount,
-            });
-        }}
-        onExitPlaid={() => BankAccounts.setBankAccountSubStep(null)}
-        receivedRedirectURI={this.props.receivedRedirectURI}
-        plaidLinkOAuthToken={this.props.plaidLinkOAuthToken}
-        allowDebit
-    />
-</View>
-{!_.isUndefined(this.state.selectedPlaidBankAccount) && (
-    <FormAlertWithSubmitButton
-        isAlertVisible={Boolean(error)}
-        buttonText={this.props.translate('common.saveAndContinue')}
-        onSubmit={this.addPlaidAccount}
-        message={error}
-        isLoading={loading}
-    />
-)}
-</FormScrollView>
+<Form
+formID={ONYXKEYS.FORMS.BANK_ACCOUNT_STEP_FORM_PLAID}
+validate={this.validatePlaidAccount}
+onSubmit={this.addPlaidAccount}
+submitButtonText={this.props.translate('common.saveAndContinue')}
+style={[styles.mh5, styles.mb5, styles.flex1]}
+>
+<AddPlaidBankAccount
+    inputID="selectedPlaidBankAccount"
+    text={this.props.translate('bankAccount.plaidBodyCopy')}
+    onExitPlaid={() => BankAccounts.setBankAccountSubStep(null)}
+    receivedRedirectURI={this.props.receivedRedirectURI}
+    plaidLinkOAuthToken={this.props.plaidLinkOAuthToken}
+    allowDebit
+/>
+</Form>

)}
{subStep === CONST.BANK_ACCOUNT.SETUP_TYPE.MANUAL && (
-    <ReimbursementAccountForm
-        reimbursementAccount={this.props.reimbursementAccount}
+    <Form
+        formID={ONYXKEYS.FORMS.BANK_ACCOUNT_STEP_FORM_MANUAL}
+        validate={this.validate}
        onSubmit={this.addManualAccount}
+        submitButtonText={this.props.translate('common.saveAndContinue')}
+        style={[styles.mh5, styles.flexGrow1]}
    >
        <Text style={[styles.mb5]}>
            {this.props.translate('bankAccount.checkHelpLine')}
@@ -314,26 +263,21 @@ class BankAccountStep extends React.Component {
            source={exampleCheckImage(this.props.preferredLocale)}
        />
        <TextInput
+            inputID="routingNumber"
            label={this.props.translate('bankAccount.routingNumber')}
            keyboardType={CONST.KEYBOARD_TYPE.NUMBER_PAD}
-            value={this.state.routingNumber}
-            onChangeText={value => this.clearErrorAndSetValue('routingNumber', value)}
            disabled={shouldDisableInputs}
-            errorText={this.getErrorText('routingNumber')}
        />
        <TextInput
+            inputID="accountNumber"
            containerStyles={[styles.mt4]}
            label={this.props.translate('bankAccount.accountNumber')}
            keyboardType={CONST.KEYBOARD_TYPE.NUMBER_PAD}
-            value={this.state.accountNumber}
-            onChangeText={value => this.clearErrorAndSetValue('accountNumber', value)}
            disabled={shouldDisableInputs}
-            errorText={this.getErrorText('accountNumber')}
        />
        <CheckboxWithLabel
            style={styles.mt4}
-            isChecked={this.state.hasAcceptedTerms}
-            onInputChange={this.toggleTerms}
+            inputID="acceptedTerms"
            LabelComponent={() => (
                <View style={[styles.flexRow, styles.alignItemsCenter]}>
                    <Text>
@@ -344,9 +288,8 @@ class BankAccountStep extends React.Component {
                    </TextLink>
                </View>
            )}
-            errorText={this.getErrorText('hasAcceptedTerms')}
        />
-    </ReimbursementAccountForm>
+    </Form>
)}
</View>
);
@@ -359,12 +302,6 @@ BankAccountStep.defaultProps = defaultProps;
export default compose(
withLocalize,
withOnyx({
-reimbursementAccount: {
-key: ONYXKEYS.REIMBURSEMENT_ACCOUNT,
-},
-reimbursementAccountDraft: {
-key: ONYXKEYS.REIMBURSEMENT_ACCOUNT_DRAFT,
-},
user: {
key: ONYXKEYS.USER,
},

```

changes that have to be done in src/components/AddPlaidBankAccount.js for using plaidform in the form.js 

```diff
src/components/AddPlaidBankAccount.js


/** Are we adding a withdrawal account? */
allowDebit: PropTypes.bool,

+/** The ID used to uniquely identify the input in a Form */
+inputID: PropTypes.string,
+
...withLocalizePropTypes,
};

const defaultProps = {
+inputID: undefined,
plaidData: {
    bankName: '',
    plaidAccessToken: '',
@@ -191,6 +195,7 @@ class AddPlaidBankAccount extends React.Component {
            </View>
            <View style={[styles.mb5]}>
                <Picker
+                    inputID={this.props.inputID}
                    label={this.props.translate('addPersonalBankAccountPage.chooseAccountLabel')}
                    onInputChange={this.selectAccount}
                    items={options}
```

and we have to add 2 keys for 2 different forms here, 1. manual 2. plaid

```diff
src/ONYXKEYS.js


FORMS: {
  ADD_DEBIT_CARD_FORM: 'addDebitCardForm',
  REQUEST_CALL_FORM: 'requestCallForm',
+  BANK_ACCOUNT_STEP_FORM_MANUAL: 'bankAccountStepFormManual',
+  BANK_ACCOUNT_STEP_FORM_PLAID: 'bankAccountStepFormPlaid',        
},
};
```

code has been pushed [here](https://github.com/jayeshmangwani/App/tree/form_refactor_bankaccountstep)

**Comment by mananjadhav** [comment]
@jayeshmangwani Your proposal looks good to me. I've got some concerns with `inputID: undefined`, but I feel small kinks can be handled during the PR Review.

🎀 👀 🎀 
C+ reviewed

@luacmartins @iwiznia All yours.

**Comment by luacmartins** [comment]
@jayeshmangwani proposal looks good. I'll let @iwiznia make the final call since he's the CME assigned to the issue.

**Comment by iwiznia** [comment]
Yeah, maybe let's use `null` instead of `undefined` in both places?
Anyway, proposal looks good, @dylanexpensify can you hire @jayeshmangwani please?

**Comment by dylanexpensify** [comment]
you got it @iwiznia !

**Comment by dylanexpensify** [comment]
internal: https://www.upwork.com/ab/applicants/1567106393688772608/job-details
external: https://www.upwork.com/jobs/~0175e44edb7543d8d6

@jayeshmangwani can you apply here ^? That way I can get you hired! (Same for @mananjadhav!)

**Comment by jayeshmangwani** [comment]
@dylanexpensify Applied 🚀

**Comment by jayeshmangwani** [comment]
[PR](https://github.com/Expensify/App/pull/10900) created

cc: @mananjadhav @iwiznia

**Comment by mananjadhav** [comment]
Thanks for the PR @jayeshmangwani I'll get it to tomorrow.

**Comment by dylanexpensify** [comment]
Any updates @mananjadhav ?

**Comment by mananjadhav** [comment]
PR is under review, and I've raised 1-2 comments on the PR [here](https://github.com/Expensify/App/pull/10900#pullrequestreview-1102769292)

**Comment by dylanexpensify** [comment]
Should we move to weekly?

**Comment by luacmartins** [comment]
Moved to weekly and added the reviewing label

**Comment by dylanexpensify** [comment]
payments sent, contracts ended, job closed!
