### ISSUE TITLE
[Form Refactor] ValidationStep

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#9582]
Coming from the [New Expensify Forms](https://docs.google.com/document/d/1DI4jQ0nyfi2JczhPT440orwlXsTP_O-aGvg-HLmcbwI/edit#heading=h.mnjguil21u0a) design doc, we should refactor [ValidationStep](https://github.com/Expensify/App/blob/main/src/pages/ReimbursementAccount/ValidationStep.js) to use the new form component, follow the guidelines below:

Here's an example of a Form refactor: https://github.com/Expensify/App/pull/9056

## Guidelines
1. Replace the form component with Form.js.
2. Create a unique Onyx key in ONYXKEYS.FORM and pass it as the [formID](https://docs.google.com/document/d/15qBqIaRnuuOWpAz50Oc4U-873txonRqCaeBkrseN_8I/edit#heading=h.789lf03wn9l8) prop to Form.
3. Pass a [validate](https://docs.google.com/document/d/15qBqIaRnuuOWpAz50Oc4U-873txonRqCaeBkrseN_8I/edit#heading=h.vudloacn1xep) callback prop.
4. Pass an [onSubmit](https://docs.google.com/document/d/15qBqIaRnuuOWpAz50Oc4U-873txonRqCaeBkrseN_8I/edit#heading=h.a9p9e5um34c2) callback prop that calls the API via an action.
5. Update all inputs wrapped by Form, following the guidelines in [Refactor inputs](https://docs.google.com/document/d/1DI4jQ0nyfi2JczhPT440orwlXsTP_O-aGvg-HLmcbwI/edit#bookmark=kix.ao8ypttnbmcj).
6. Remove any unused code.

## Testing
Verify that:
- [ ] UI looks as it did before the refactor
- [ ] Values can be added and edited
- [ ] Errors are highlighted correctly (input border)
- [ ] Error messages show up correctly
- [ ] Draft values are saved properly
- [ ] Form alerts are displayed correctly
- [ ] Clicking the `fix the errors` link focuses the first input with error
- [ ] No duplicate submission of the form occurs (when it's already submitting)

**Comment by luacmartins** [comment]
This issue is being put on hold due to push to page discussions, as per [this comment](https://github.com/Expensify/App/issues/9579#issuecomment-1169229996).

**Comment by luacmartins** [comment]
On hold!

**Comment by luacmartins** [comment]
On hold

**Comment by luacmartins** [comment]
On hold

**Comment by luacmartins** [comment]
On hold

**Comment by luacmartins** [comment]
No longer on hold!

**Comment by luacmartins** [comment]
I'll try to work on it this week!

**Comment by luacmartins** [comment]
I'm focused on offline first and N7 issues this week. Gonna try to get to this next week.

**Comment by luacmartins** [comment]
Prioritizing N7 issues, I'll get to this next week.

**Comment by aldo-expensify** [comment]
Sorry @luacmartins , didn't have enough time to get to this before the end of last week. I'll assign it back to you so you can decide on doing it yourself or finding someone else :)

**Comment by aldo-expensify** [comment]
@luacmartins I asked in slack if someone wanted to give this a try [here](https://expensify.slack.com/archives/C03TQ48KC/p1662916489320259) and @youssef-lr offered to help (just letting you know)

**Comment by luacmartins** [comment]
@youssef-lr we changed to `isLoading` everywhere, so you should use that key.

**Comment by youssef-lr** [comment]
Thanks @luacmartins, I went ahead and updated the DD.
