### ISSUE TITLE
[$250] Web - IOU Participants - Nothing happens when press CMD+Enter

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#9594]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue was found when executed PR:** https://github.com/Expensify/App/pull/7702 

## Action Performed:
1. Go to NewDot
1. Click/tap on the green + icon on the home screen.
2. Click/tap on Request Money
3. Enter an amount and press Next
4. Enter a search query to get a reasonable-length list of results.
5. Use the arrow keys to highlight different result.
6. Press CMD+Enter.

## Expected Result:
After Press CMD+Enter it should take you to the next page with your new selected user.

## Actual Result:
When Press CMD+Enter nothing happens.

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.79.2

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** rybkina+061322@gmail.com/Qwerty123

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

**Expensify/Expensify Issue URL:** 

https://user-images.githubusercontent.com/93399543/176216341-24097724-3b45-460e-9cce-80958da142b8.mp4

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by rushatgabhane** [comment]
@roryabraham this is the expected UX, right?

**Comment by sketchydroide** [comment]
I'm adding a deploy blocker has this seems to block the QA of https://github.com/Expensify/App/pull/7702 and therefor blocking the deployment

**Comment by roryabraham** [comment]
> This is the expected UX for lists with untoggleable items

Agree, this is how it was designed so I wouldn't say it counts as a regression or deploy blocker. If we want to make `CMD+Enter` work just like `Enter` for lists that don't support multiple selections, that's a new feature. It seems like a good idea to me but can be treated as separate

**Comment by roryabraham** [comment]
This can also be external

**Comment by roryabraham** [comment]
> Is it something like other similar pages allow cmd+enter to go next, so we should implement that pattern here too?

Yeah, exactly

**Comment by madmax330** [comment]
Alright passing this on as external, thanks @roryabraham

**Comment by laurenreidexpensify** [comment]
https://www.upwork.com/jobs/~01a590c870e2d44999

**Comment by roryabraham** [comment]
I'm actually going to just fix this myself because it's come up a few times and it will be a really quick and easy fix

**Comment by roryabraham** [comment]
@laurenreidexpensify I took down the upwork job for this

**Comment by roryabraham** [comment]
Got a PR up
