### ISSUE TITLE
Web - Confirmation List - The participant isn't shown after press the ArrowUp key

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#9595]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue was found when executed PR:** https://github.com/Expensify/App/pull/7702

## Action Performed:
1. Go to NewDot
2. Open a 1:1 DM with another user (not Chronos or Concierge).
3. Press the + button in the compose bar and click Request Money
4. Enter an amount and press Next
5. Press the ArrowUp key to highlight your participant.

## Expected Result:
The participant should be show base on step 19 IOU Confirmation List/ Web/Desktop.

## Actual Result:
The participant isn't shown.

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.79.2

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** rybkina+061322@gmail.com/Qwerty123

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/176217787-e082336c-0587-4c8f-8832-6aa3305ac5e8.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by rushatgabhane** [comment]
@kbecciv I'm confused here. We're requesting money to `Holla Ryba` and the same user is shown on the confirm page.
Can you help me understand what's the bug here?

cc: @TomatoToaster

**Comment by rushatgabhane** [comment]
> Press the ArrowUp key to highlight your participant.

@kavimuru Ah yes, this step should be ignored / removed.

cc @roryabraham

**Comment by roryabraham** [comment]
Oh, you're correct that this is a mistake in the QA steps that are out-of-date. Let me update the steps and close this issue.

**Comment by roryabraham** [comment]
Updated the QA steps to remove the `Press the ArrowUp key to highlight your participant`. If you are coming from global create or a 1:1 DM, then you can't modify the IOU participants in the IOUConfirmationList. If you can't modify the participants, then the arrow keys shouldn't work
