### ISSUE TITLE
Update Allocations "Teams Export" script so it no longer has the startDate in the file

### ISSUE THREAD

**Issue by danielrvidal** [Expensify/App#9605]
We use the following instructions for our allocations process, which is approaching at the end of the month. We rely on the "script/exportTeams.sh" to get us the information our teams information. But the current script has extra information. We do not need the StartDate, so would like it removed. 

We just need the email and team, at the time the report is run. 

Below are the directions we input when we create an issue to pull the Teams data just for reference. Can you please the startDate from the script and let me know if you have any other questions?

> Hey Engineering, we need to get the quarterly teams for allocations. If you’re assigned please perform the following steps:
> 
> 1. Make sure your Salt and Web-Expensify repos are up to date and you are on the `main` branch in both repos
> 
> 2. Please run `script/exportTeams.sh` 
> 
> 3. This will produce a `employeeExport.csv` file in the Expensidev directory 
> 
> 4. Attach that file to this GH
> 
> 5. You’re done! Thanks! 
> 
> Because this is time sensitive please do it ASAP. Please let me know if you have any issues or have any questions.
>

**Comment by robertjchen** [comment]
[employeeExport.csv](https://github.com/Expensify/App/files/9013127/employeeExport.csv)

**Comment by robertjchen** [comment]
[employeeExport-2022-07-01.csv](https://github.com/Expensify/App/files/9032026/employeeExport-2022-07-01.csv)
