### ISSUE TITLE
Web - Line Breaks - Copying & Pasting Line breaks does not work

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#9608]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Pre- Condition: User has copied a line break previously
1. Access staging.new.expensify.com
2. Sign into any valid account
3. Click on any chat
4. Attempt to paste the line break in the chat box

## Expected Result:
The user expects the line break to show correctly

## Actual Result:
The line break does not work and text displays as:
"I'm a text withlinebreaks"

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.79.2

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

**Expensify/Expensify Issue URL:** 

https://user-images.githubusercontent.com/93399543/176269449-b13e5d4b-e963-48dd-bf6c-c17bd8fa0185.mp4

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by MariaHCD** [comment]
Unable to reproduce the issue. I tried copying over from Slack and even from a regular text area and the new lines are preserved when pasting into NewDot

Slack:
![Screen Shot 2022-06-29 at 4 34 42 PM](https://user-images.githubusercontent.com/12268372/176437546-6b6d36dc-3ef8-4288-bd4f-839664bb57aa.png)

Regular text area:
![Screen Shot 2022-06-29 at 4 34 16 PM](https://user-images.githubusercontent.com/12268372/176437624-4d8200b2-4fcd-45fa-a781-045bbde01db8.png)

NewDot:
![Screen Shot 2022-06-29 at 4 34 46 PM](https://user-images.githubusercontent.com/12268372/176437556-8603b93f-8c59-40b0-9c24-c8be5ed182c9.png)

Not sure if it's something specific to the comment box on TestRail
