### ISSUE TITLE
Crash occurred after Click on the "Get started" on the inbox task on OD

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#9630]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
Issue was found when executing #9469

## Action Performed:
1. Make sure you are signed out of NewDot on mobile web
2. Go to the OldDot mobile app and sign up for a new account with a + in it and @gmail.com. E.x [neil+test@gmail.com](mailto:neil+test@gmail.com)
3. Click on the "Get started" on the inbox task that says "Would you like to get started with our free plan?".

## Expected Result:
You should be directed to NewDot on mobile web and have a new workspace created, and the workspace settings should open.

## Actual Result:
Crash occurred.

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.79-2

**Reproducible in staging?:** Tested in Production as there is no beta build

**Reproducible in production?:**Y 

**Email or phone of affected tester (no customers):** rybkina+62822@gmail.com / Qwerty123

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** 

<img src="https://user-images.githubusercontent.com/43996225/176510881-ffb488cf-7005-4356-b65e-56d700453924.png" width="40%" height="40%">

https://user-images.githubusercontent.com/43996225/176510912-9689d30a-37d8-446d-936d-47ba3633c555.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:**
Applause internal team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by neil-marcellini** [comment]
This error is expected until https://github.com/Expensify/App/pull/9469 hits production. See my comment [here](https://github.com/Expensify/App/pull/9469).
