### ISSUE TITLE
[HOLD for payment 2022-08-30] [$250] Right clicking and “Copy Link” on a link produced https://new.expensify.com//r/0/NaN when pasted

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#9660]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
This Issue has been divided in 2 parts, as it evolved while it was being discusses, the solution to both the situations is similar, and it would be easier to keep them in one GH.

## Action Performed:
1. Send any link (e.g. Google.com) to a chat on web.
2. Right-click on the link to open the context menu.
3. Check that you see 2 option, `Copy link` and `Copy URL to clipboard`

## Expected Result:
We should only display the `Copy URL to clipboard` option

## Actual Result:
We show both options and it's confusing

## 2nd Situation
1. Add an attachement to a chat on web.
2. Right-click on the link to open the context menu.
3. Check that you see several options including `Copy link` and `Copy to clipboard`

## Expected Result:
We should only `Download`, `Mark as unread`, `Delete comment`

## Actual Result:
We show all of the above option, and it's confusing

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.79-9
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 
![2022-06-29_07-21-39](https://user-images.githubusercontent.com/43995119/176831323-065c08a9-ab90-4324-9271-f33c753f3514.png)
![Screen Shot 2022-07-01 at 1 41 25 AM](https://user-images.githubusercontent.com/43995119/176831345-bca3a477-751c-4a50-8d43-609c31fadcb8.png)

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @marcaaron 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1656523285065139

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by sketchydroide** [comment]
Oh that one is hilarious.
This one feels like it can be an external

**Comment by jayeshmangwani** [comment]
### Proposal:

https://github.com/Expensify/App/blob/f19a4d94870fdc96ea032d90217a03f9f5b46674/src/pages/home/report/ContextMenu/ContextMenuActions.js#L125-L132

Here, we have to use the same onPress function as we are using for `copyURLToClipboard` 

https://github.com/Expensify/App/blob/f19a4d94870fdc96ea032d90217a03f9f5b46674/src/pages/home/report/ContextMenu/ContextMenuActions.js#L67-L70

```diff

-        onPress: (closePopover, {reportAction, reportID}) => {
-            Environment.getEnvironmentURL()
-                .then((environmentURL) => {
-                    const reportActionID = parseInt(lodashGet(reportAction, 'reportActionID'), 10);
-                    Clipboard.setString(`${environmentURL}/r/${reportID}/${reportActionID}`);
-                });
-            hideContextMenu(true, ReportActionComposeFocusManager.focus);
-        },

+        onPress: (closePopover, {selection}) => {
+            Clipboard.setString(selection);
+            hideContextMenu(true, ReportActionComposeFocusManager.focus);
+        },
```

**Comment by sketchydroide** [comment]
also this still needs to get the `Help Wanted` label first.

**Comment by jayeshmangwani** [comment]
@sketchydroide I misunderstood this issue, and sure will comment on proposal one the issue has `Help Wanted` label

**Comment by Sans84** [comment]
> @jayeshmangwani I don't think that is what we are looking for, the `Copy link` is not the link of the url for that we have `Copy URL to clipboard`. `Copy link` is a link of the chat comment itself. the entire line. Like if you want to share that post with someone else

In the issue, `Copy Link` should return a link when pasted, and you write that it is a link to a comment. It's a contradiction! Is this an error in the description of the issue or an incomplete description?

**Comment by parasharrajat** [comment]
It seems yes, issue details are incorrect. 

@Christinadobrzyn Could you please fix the steps. 

1. Send any link (e.g. Google.com) to a chat on web.
2. Right-click on the link to open the context menu.
3. Select `Copy link` option. 


Expected Result:

The copied link should be the correct link to the comment.

Actual Result:

Right-clicking on “Copy Link” on a link produced [new.expensify.com//r/0/NaN](https://new.expensify.com//r/0/NaN) when pasted.

**Comment by eVoloshchak** [comment]
**Proposal:**
The issue occurs because to generate link we [need](https://github.com/eVoloshchak/App/blob/2c1032fc231717bc840b8939fd9edba54bfbe861/src/pages/home/report/ContextMenu/ContextMenuActions.js#L128) `reportAction` and `reportID`, none of which are passed to [showContextMenu](https://github.com/eVoloshchak/App/blob/2c1032fc231717bc840b8939fd9edba54bfbe861/src/components/AnchorForCommentsOnly/BaseAnchorForCommentsOnly/index.js#L69) method in `BaseAnchorForCommentsOnly`. Lets fix that

1. We can obtain `reportID` from navigation state using already existing [getReportID](https://github.com/eVoloshchak/App/blob/2c1032fc231717bc840b8939fd9edba54bfbe861/src/pages/home/ReportScreen.js#L102) function and pass it to `showContextMenu`
```diff
ReportActionContextMenu.showContextMenu(
    Str.isValidEmail(this.props.displayName) ? ContextMenuActions.CONTEXT_MENU_TYPES.EMAIL : ContextMenuActions.CONTEXT_MENU_TYPES.LINK,
    event,
    this.props.href,
    lodashGet(linkRef, 'current'),
+   getReportID(this.props.navigation.state),
);
```
2. Getting reportAction is a bit harder, but we don't need the whole action, only it's id (reportActionID). We pass it from `ReportActionItemMessage` to `ReportActionItemFragment` 
```diff
<ReportActionItemFragment
    key={`actionFragment-${props.action.sequenceNumber}-${index}`}
    fragment={fragment}
    isAttachment={props.action.isAttachment}
    attachmentInfo={props.action.attachmentInfo}
    loading={props.action.loading}
+   reportActionID={props.action.reportActionID}
/>
```
3. And then in ReportActionItemFragment's render method we need to check if html is anchor (if tag is a) and if it is, add reportActionID to html (the same principle we [use](https://github.com/Expensify/App/blob/2c1032fc231717bc840b8939fd9edba54bfbe861/src/pages/home/report/ReportActionItemFragment.js#L77) to add `data-expensify-preview-modal-disabled` param to images). This is not a final code, we probably will need to implement `Str.isAnchor` method, but just to illustrate:
```javascript
  if (props.fragment.html.startsWith('<a')) {
      props.fragment.html = props.fragment.html.replace('<a', `<a reportActionID=${props.reportActionID}`)
  }
```
4. Now that we've added `reportActionID` to html, we need to parse it in `AnchorRenderer` and pass it to `AnchorForCommentsOnly`. In `AnchorRenderer.js`
```diff
+ const reportActionID = htmlAttribs['reportactionid'];
return (
    <AnchorForCommentsOnly
        href={attrHref}
        isAuthTokenRequired={isAttachment}
        target={htmlAttribs.target || '_blank'}
        rel={htmlAttribs.rel || 'noopener noreferrer'}
        style={{...props.style, ...parentStyle}}
        key={props.key}
        displayName={displayName}
+       reportActionID={reportActionID}
    >
```
5. And we finally can use reportActionID in `showContextMenu` method
```diff
ReportActionContextMenu.showContextMenu(
    Str.isValidEmail(this.props.displayName) ? ContextMenuActions.CONTEXT_MENU_TYPES.EMAIL : ContextMenuActions.CONTEXT_MENU_TYPES.LINK,
    event,
    this.props.href,
    lodashGet(linkRef, 'current'),
+   getReportID(this.props.navigation.state),
+   {reportActionID: this.props.reportActionID}
);
```
**Result:**

https://user-images.githubusercontent.com/9059945/177003781-173e61ae-895d-476f-a984-6d0409994927.mp4

**Comment by Beamanator** [comment]
Thanks @parasharrajat updated the OP with clearer details as you mentioned here: https://github.com/Expensify/App/issues/9660#issuecomment-1172698634

**Comment by parasharrajat** [comment]
Discussing here https://expensify.slack.com/archives/C02NK2DQWUX/p1656925799345049

**Comment by parasharrajat** [comment]
Looking for other possible proposals that do not include HTML manipulation.

**Comment by marcaaron** [comment]
@roryabraham any thoughts? And can you advise on how we could disable the option to "Copy link" when we are right-clicking on a hyperlink? 

I'm not sure where in the code we'd be able to do that (looked for a bit, but couldn't find the logic that determines why some options show and others do not). That would be an easier solution IMO as it is pretty ambiguous what is even being copied when presented with these options:

<img width="372" alt="Screen Shot 2022-07-06 at 3 25 58 PM" src="https://user-images.githubusercontent.com/32969087/177670768-005181f0-6a1d-4f3e-bbff-a3827b2b1180.png">

**Comment by roryabraham** [comment]
I agree that `Copy link` vs `Copy URL to clipboard` is confusing. Reading up in the slack thread, I think @marcaaron made some really good arguments for why we should just display `Copy URL to clipboard` if you right-click on the link, so 👍 there. I also think that the same logic should apply if you right-click an email link, which has this same bug.

> And can you advise on how we could disable the option to "Copy link" when we are right-clicking on a hyperlink?

Yep!

- all the context menu actions are defined [here](https://github.com/Expensify/App/blob/c06dc817487e949c8859b8431d673283fa4a6240/src/pages/home/report/ContextMenu/ContextMenuActions.js#L34-L195)
- whether or not each one shows is determined by their `shouldShow` function
- The `BaseReportActionContextMenu` component has a [`type` prop](https://github.com/Expensify/App/blob/927555916255807842bfde5308ff517484d3ea7d/src/pages/home/report/ContextMenu/BaseReportActionContextMenu.js#L17-L18) that's [passed to the `shouldShow` function](https://github.com/Expensify/App/blob/927555916255807842bfde5308ff517484d3ea7d/src/pages/home/report/ContextMenu/BaseReportActionContextMenu.js#L35) for each context action.
- So if we don't want to show `Copy link` if you right-click on a link or email, then all we have to do is change [this line](https://github.com/Expensify/App/blob/c06dc817487e949c8859b8431d673283fa4a6240/src/pages/home/report/ContextMenu/ContextMenuActions.js#L124) to `shouldShow: type => type === CONTEXT_MENU_TYPES.REPORT_ACTION,`

**Comment by Christinadobrzyn** [comment]
I'm going to be ooo so assigning this to another teammate.

**Comment by parasharrajat** [comment]
@Christinadobrzyn Could you please update the Expected result section with following?

`Copy link` menu item should not be shown on ContextMenu for Attachments and links.

**Comment by parasharrajat** [comment]
@Christinadobrzyn Could you please update the Expected result section with the following?

`Copy link` menu item should not be shown on ContextMenu for Attachments and links.

**Comment by Harshdeepjoshi** [comment]
# Proposal
### Solution

- To hide the menu options from context menu for links, we need to edit [this](https://github.com/Expensify/App/blob/c06dc817487e949c8859b8431d673283fa4a6240/src/pages/home/report/ContextMenu/ContextMenuActions.js#L124) line and add `=> type === CONTEXT_MENU_TYPES.REPORT_ACTION`

- To hide the menu options from context menu for attachments, we would add `&& !ReportUtils.isReportMessageAttachment(lodashGet(reportAction, ['message', 0], {}))` to the [same line](https://github.com/Expensify/App/blob/c06dc817487e949c8859b8431d673283fa4a6240/src/pages/home/report/ContextMenu/ContextMenuActions.js#L124) and this will solve our issue.

The final code will look like this
``` js
    {
        textTranslateKey: 'reportActionContextMenu.copyLink',
        icon: Expensicons.LinkCopy,
        shouldShow: (type, reportAction) => type === CONTEXT_MENU_TYPES.REPORT_ACTION && !ReportUtils.isReportMessageAttachment(lodashGet(reportAction, ['message', 0], {})),
        onPress: (closePopover, {reportAction, reportID}) => {
            Environment.getEnvironmentURL()
                .then((environmentURL) => {
                    const reportActionID = parseInt(lodashGet(reportAction, 'reportActionID'), 10);
                    Clipboard.setString(`${environmentURL}/r/${reportID}/${reportActionID}`);
                });
            hideContextMenu(true, ReportActionComposeFocusManager.focus);
        },
        getDescription: () => {},
    },


```
### Links 
![Screenshot from 2022-07-08 03-13-02](https://user-images.githubusercontent.com/88710727/177876571-fc214959-94c4-4fa0-8808-d8106d874953.png)

### Attachments
![Screenshot from 2022-07-08 03-12-32](https://user-images.githubusercontent.com/88710727/177876640-74a4db32-27f6-466a-85be-ab8c19f03ccb.png)

**Comment by roryabraham** [comment]
Sure, sounds good

**Comment by parasharrajat** [comment]
Based on the new [requirements](https://github.com/Expensify/App/issues/9660#issuecomment-1178020405), @Harshdeepjoshi 's [proposal](https://github.com/Expensify/App/issues/9660#issuecomment-1178268724) looks good to me. 


cc: @sketchydroide Could you please also update the expected result according to https://github.com/Expensify/App/issues/9660#issuecomment-1178020405

:ribbon: :eyes: :ribbon:  C+ reviewed

**Comment by sketchydroide** [comment]
I updated the GH, @parasharrajat and @Harshdeepjoshi let me know if that makes sense as we end up having to very similar changes to do here, one for the link and another for the attachements.

**Comment by Harshdeepjoshi** [comment]
@sketchydroide I understood the changes. Replacing `&& !ReportUtils.isReportMessageAttachment(lodashGet(reportAction, ['message', 0, 'text'], ''))),` with `&& !ReportUtils.isReportMessageAttachment(lodashGet(reportAction, ['message', 0], {}))),` in [this line](https://github.com/Expensify/App/blob/c06dc817487e949c8859b8431d673283fa4a6240/src/pages/home/report/ContextMenu/ContextMenuActions.js#L92) will hide `Copy URL to clipboard` from attachments. 
when can I submit the PR?

**Comment by parasharrajat** [comment]
Looks good @Harshdeepjoshi. 

--- 

Am I eligible for reporting bonus of `2nd Situation in the OP`? I reported this a few days back  https://github.com/Expensify/App/issues/9660#issuecomment-1179119307. 

cc: @sketchydroide

**Comment by sketchydroide** [comment]
I would say that yes you are @parasharrajat

**Comment by parasharrajat** [comment]
@sketchydroide Should we show the copy Link option on the mini menu for attachments? 
![image](https://user-images.githubusercontent.com/24370807/179623946-f59ee792-1845-4cd8-a631-d903fc264d52.png)

**Comment by parasharrajat** [comment]
Any thoughts above?

**Comment by parasharrajat** [comment]
@sketchydroide I think we should do https://github.com/Expensify/App/issues/9660#issuecomment-1188359112 as an attachment is also and message and the user might want to copy the comment URL.

**Comment by arielgreen** [comment]
Hired in Upwork @Harshdeepjoshi @parasharrajat

**Comment by Harshdeepjoshi** [comment]
Sorry for being late, I was busy with my college exams,PR is ready for review.

**Comment by arielgreen** [comment]
Still in QA

**Comment by sketchydroide** [comment]
I think this has not been deployed yet?

**Comment by sketchydroide** [comment]
so it has been deployed now, and it's up for payment @arielgreen

**Comment by arielgreen** [comment]
@Harshdeepjoshi can you link me your Upwork profile please?

**Comment by Harshdeepjoshi** [comment]
@arielgreen Here is my profile link 
https://www.upwork.com/freelancers/~01e5d6057af1ee90ae

**Comment by sketchydroide** [comment]
@arielgreen can we close this?

**Comment by arielgreen** [comment]
@Harshdeepjoshi just sent over an offer, once you accept I can remit payment and we can close this

**Comment by Harshdeepjoshi** [comment]
@arielgreen I have accepted the offer.

**Comment by arielgreen** [comment]
Excellent, paid, closing.
