### ISSUE TITLE
Some messages from Chronos are not hyperlinked

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#9661]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Navigate to Chronos chat 
2. Wait for the summary to appear

## Expected Result:
www.Expensify.com links should be hyperlinked 

## Actual Result:
Expensify.com link is not hyperlinked 

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.79-0
**Reproducible in staging?:** Y 
**Reproducible in production?:** need repro 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 
<img width="801" alt="Screen Shot 2022-06-29 at 9 52 11 AM" src="https://user-images.githubusercontent.com/43995119/176831855-7140fa8a-a384-4c1d-bda6-22789707d59c.png">

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @puneetlath 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1656510775305249

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by madmax330** [comment]
I think this needs to be internal cc @deetergp to confirm. Since we're probably not using the right format when creating the chronos message

**Comment by madmax330** [comment]
Bump @deetergp

**Comment by deetergp** [comment]
This was fixed [here](https://github.com/Expensify/Web-Expensify/pull/34204/files)
