### ISSUE TITLE
Console error displayed when clicking on my profile page

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#9663]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open app and login 
2. Navigate to My Profile 

## Expected Result:
No console errors should display  

## Actual Result:
Console error displayed when clicking on my profile page 
`Animated: `useNativeDriver` is not supported because the native animated module is missing. Falling back to JS-based animation. To resolve this, add `RCTAnimation` module to this app, or remove `useNativeDriver`. Make sure to run `pod install` first. Read more about autolinking: https://github.com/react-native-community/cli/blob/master/docs/autolinking.md`

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Web
- Desktop App

**Version Number:** 1.1.79-9
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
![Screen Shot 2022-07-01 at 1 55 15 AM](https://user-images.githubusercontent.com/43995119/176832940-088ae9bc-4bc0-48f4-90fe-26ffe30dc1f8.png)

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @puneetlath 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1656437872974209

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by amyevans** [comment]
Well it's a warning, not an error, and I think it's expected on web/desktop given that they aren't native devices? It's probably possible to refactor code so that `useNativeDriver` is only used in native files but I also am not 100% sure of that without digging further.

I think I'm caught between closing this out as Not a Priority or opening it up for external contributors as a Monthly. Maybe @Julesssss you can provide a second opinion (and gutcheck on what I said above), or @puneetlath since you initially reported the issue?

**Comment by Julesssss** [comment]
I think it would be fine to keep it open as an internal Expensify/Expensify monthly issue -- but as it's on the public repo let's just close it to avoid spending too much time here.

As for what the solution would be, I think we could start using [this lib](https://github.com/Expensify/App/commit/d8c1b5f973008c18337e6c206e023cb6b702e810) which would disable the feature for web.
