### ISSUE TITLE
Notifications for new messages are broken in web on chrome for some users

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#9664]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open app in Web Chrome 
2. Receive couple messages 

## Expected Result:
Browser notifications should appear 

## Actual Result:
Notifications for new messages are broken in web on chrome

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platform:

Where is this issue occurring?

- Web / Chrome

**Version Number:** 1.1.79-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 
<img width="452" alt="image - 2022-07-01T020340 468" src="https://user-images.githubusercontent.com/43995119/176834042-761401b6-0c59-4889-89d4-9a90ab9c73dd.png">
![image - 2022-07-01T020338 232](https://user-images.githubusercontent.com/43995119/176834045-0de19aeb-6895-494d-8df4-695a18efc108.png)

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @iwiznia 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1656350035892269

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by iwiznia** [comment]
Both me and @tylerkaraszewski are experiencing this. It's apparently not a widespread issue.

**Comment by puneetlath** [comment]
Ok, I'm going to go ahead and mark as External to see if anyone has any ideas about how to reproduce.

**Comment by puneetlath** [comment]
@iwiznia @tylerkaraszewski y'all still experiencing this? Trying to think of what to do with this issue.

**Comment by iwiznia** [comment]
I think it's working now, but not 100% sure

**Comment by puneetlath** [comment]
Ok, gonna close. Reopen if you continue to see it.
