### ISSUE TITLE
[$250] Expense rules - Long comment entered in the description field overflows

### ISSUE THREAD

**Issue by bfitzexpensify** [Expensify/App#9668]
## EXPECTED RESULT:

Long comment entered should be within the field

## ACTUAL RESULT:

Long comment entered goes beyond the field

## ACTION PERFORMED:

1. Go to URL https://staging.expensify.com/
and login with any account
2. Navigate to Main/Settings/Your Account/Expense Rules
3. When the Merchant name contains: Test
4. Change Merchant to: New Test
5.Change Category to: Any category
6. Enter a long comment

## Workaround:
Visual
 
**Notes/Photos/Videos:** 
![Bug5630359_expense_rules_2906](https://user-images.githubusercontent.com/43996225/176524934-ece92b02-2d22-4ee4-bd92-2cead7ae9203.png)

Tester login credentials - Email/Phone: slazutkinautest+290614@gmail.com
Tester login credentials - Password: w323052760We

**Comment by bfitzexpensify** [comment]
This is coming from https://github.com/Expensify/Expensify/issues/216750 - it's already been triaged and marked as External, I'm just copying it over to the external repo.

**Comment by roryabraham** [comment]
Uhhh guys .... who marked this as external? It's in OldDot so definitely needs to be internal

**Comment by roryabraham** [comment]
This needs to be internal. @bfitzexpensify Please take down the upwork job and close this out. I reopened the internal issue

**Comment by bfitzexpensify** [comment]
Closed the upwork job. Closing this out.
