### ISSUE TITLE
Web - Group Chat - Using Enter key is leaded for crash 

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#9685]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in with any account
3. Click on Fab menu and Click Create Group
4.  Use Enter Key to create a Group Chat

## Expected Result:
No crash should be happen

## Actual Result:
App crashed when using Enter key for Group conversation

## Workaround:
Unknow

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.79.9

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/177007431-a698ee4b-81b5-44f6-890d-f85335c35181.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by rushatgabhane** [comment]
@roryabraham similar cause - https://github.com/Expensify/App/pull/9674#discussion_r912421955

**Comment by roryabraham** [comment]
Revert PR here: https://github.com/Expensify/App/pull/9690

**Comment by Julesssss** [comment]
Should be resolved by the revert [PR](https://github.com/Expensify/App/pull/9690) above. Marking it off the deployer [checklist](https://github.com/Expensify/App/issues/9586).
