### ISSUE TITLE
Web/Firefox - Eye emoji is broken in Firefox browser 

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#9686]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to https://staging.new.expensify.com
2. Click on emojis option
3. On search - start looking for eye

## Expected Result:
Eye emoji is broken in Firefox browser 

## Actual Result:
Eye emoji should be displayed without any issues

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web/Firefox
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.79.9

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation
![Eye is broken](https://user-images.githubusercontent.com/93399543/177007647-f541a502-899b-43fd-afe6-a41d47e6065e.png)

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Christinadobrzyn** [comment]
Related GH - other broken emojis in Firefox. https://github.com/Expensify/App/issues/9123

**Comment by flodnv** [comment]
Thanks @Christinadobrzyn , closing as duplicate then.
