### ISSUE TITLE
Search - Focus moves to the 1st line of results when the search query

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#9695]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/docs/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue was found when executing PR** https://github.com/Expensify/App/pull/7702

## Action Performed:
1. Open App
2. Open Search
3. Type search query
4. Focus somewhere in the middle of the list
5. Update the search input such that there are no results
6. Undo the change from the previous step

## Expected Result:
The focus should be where you left it

## Actual Result:
 Focus moves to the 1st line of results when the search query

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.79.13

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/177223065-c11645e0-87ab-43cf-bd12-9fff6b163d64.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment]
Added Deploy blocker label because the issue.

https://user-images.githubusercontent.com/93399543/177223286-96504c5a-c577-44c9-a2d9-140083cf3be0.mp4

is not reproduced in production

**Comment by isagoico** [comment]
When retesting https://github.com/Expensify/App/pull/7702 for https://github.com/Expensify/App/pull/9672. 
We found that the issue described in the OC fails step #8 and #10 under the scenario `Search page / Web-Desktop`

![image](https://user-images.githubusercontent.com/44479856/177227029-9303ba26-12ff-4c96-a3f9-3de03dce0c15.png)
 
I'm not sure if this needs to be a blocker or if it can be addressed later so we're leaving the deploy blocker label for review.

**Comment by rushatgabhane** [comment]
Thanks @isagoico, this is the expected result and not a blocker.

The tests are outdated. Sorry about that!

cc: @roryabraham

**Comment by roryabraham** [comment]
Thanks, @rushatgabhane is correct that this is the expected behavior. Whenever the search term changes we highlight the first option because it theoretically is the _Best Result™_ according to the latest search query. Thanks and sorry for the out-of-date QA steps.
