### ISSUE TITLE
[HOLD for payment 2022-09-27] [$250] We don't have character limit in zip code, we don't have state picker at additional details page - reported by @thesahindia 

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#9702]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/docs/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click on Fab icon > send money > onfido verification > Additional details page
2. Check zip code field and state field

## Expected Result:
 It should be consistent, we have character limit for zip code and we use state picker on other pages

## Actual Result:
We don't have char limit on zip code and we aren't using state picker

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.79-0
**Reproducible in staging?:** Y
**Reproducible in production?:** 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 

https://user-images.githubusercontent.com/43995119/177381152-26867a58-63ca-4257-9d90-b8a4cc231d4f.mov

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @thesahindia 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1654322127160669

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by thesahindia** [comment]
### Proposal

We just have to use [AddressForm](https://github.com/Expensify/App/blob/main/src/pages/ReimbursementAccount/AddressForm.js) component here 
https://github.com/Expensify/App/blob/95d831d67e5d44a0b1fec5b6e1ad560242d4b914/src/pages/EnablePayments/AdditionalDetailsStep.js#L272

We use `AddressForm` at all other pages where we have these fields and in additional details page we are using the same code that `AddressForm` contains, so we can just use `AddressForm`, it will dry the code and it will solve the current issues.

**Comment by MonilBhavsar** [comment]
Agree, with [slack discussion](https://expensify.slack.com/archives/C01GTK53T8Q/p1654322127160669), we should limit the zip code and use state picker in this form.

**Comment by laurenreidexpensify** [comment]
https://www.upwork.com/jobs/~014bc782e8d4ebf4f8

**Comment by laurenreidexpensify** [comment]
bump ^^ @MonilBhavsar

**Comment by MonilBhavsar** [comment]
Apologies for delay here 🙏 
Looks good to me too

**Comment by laurenreidexpensify** [comment]
@thesahindia and @rushatgabhane are hired in upwork 👍🏽 let us know when you have a PR up @thesahindia

**Comment by laurenreidexpensify** [comment]
@kevinksullivan 👋 am OOO til 12 August so reassigning. Thanks!

**Comment by thesahindia** [comment]
> @thesahindia and @rushatgabhane are hired in upwork 👍🏽 let us know when you have a PR up @thesahindia

Cool, will raise the PR today.

**Comment by thesahindia** [comment]
PR is up.

cc: @rushatgabhane

**Comment by kevinksullivan** [comment]
PR in review, @MonilBhavsar still waiting on a response regarding testing steps [here](https://github.com/Expensify/App/pull/10234#issuecomment-1213465070)

**Comment by kevinksullivan** [comment]
Waiting on @MonilBhavsar review.

**Comment by kevinksullivan** [comment]
Reassigning as I'm OOO for a bit. Thanks @kadiealexander !

**Comment by kadiealexander** [comment]
Just adding a note that I'll be OOO for the next 9 days, until September 21st. If you need a CM in that time, please re-add the external label.

**Comment by MonilBhavsar** [comment]
^  Deployed

**Comment by kadiealexander** [comment]
Everyone is paid! Thanks team :)
