### ISSUE TITLE
[$250] Editing a comment containing both RTL and LTR characters breaks the (edited) text - Reported by @adeel0202

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#9709]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/docs/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to any chat
2. Type something containing RTL characters
3. Send the comment
4. Edit the comment and add LTR characters
5. Press Save changes

## Expected Result:
The (edited) text doesn't break

## Actual Result:
The (edited) text breaks

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.79-0
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 

https://user-images.githubusercontent.com/43995119/177388061-9e475f00-495b-4fa3-90d1-029b98ccb233.mov

**Upwork URL:** https://www.upwork.com/jobs/~01c6ba7a40ecceeb34
**Issue reported by:** @adeel0202
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1655138110274269

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by trjExpensify** [comment]
Passing on to engineering triage. Will remain assigned for CM if it can go external.

**Comment by sketchydroide** [comment]
I think this can be external.

**Comment by trjExpensify** [comment]
Oops, someone missed this. On upwork here: https://www.upwork.com/jobs/~01c6ba7a40ecceeb34

**Comment by Karim-30** [comment]
### Proposal

wrap the comment and edit Texts inside a `<View>`. So change these [lines](https://github.com/Expensify/App/blob/0fcc4920dbc0e0b7658e80541367acf8a2e4ff57/src/pages/home/report/ReportActionItemFragment.js#L107-L120)  inside `ReportActionItemFragment.js` to these :
```
<View style={{flexDirection:'row',alignItems:'center'}}>

    <Text
        selectable={!canUseTouchScreen() || !props.isSmallScreenWidth}
        style={EmojiUtils.containsOnlyEmojis(props.fragment.text) ? styles.onlyEmojisText : undefined}
    >
        {Str.htmlDecode(props.fragment.text)}
    </Text>

    <Text
        fontSize={variables.fontSizeSmall}
        color={themeColors.textSupporting}
    >
        {` ${props.translate('reportActionCompose.edited')}`}
    </Text>

</View>
```

Result : 
![RTL](https://user-images.githubusercontent.com/108357004/178068511-9266030c-638c-4eee-9490-5eebe29a50fa.png)

**Comment by sketchydroide** [comment]
@Karim-30 can you show me an example with just edited RTL text?
And add a before and after example.

thanks

**Comment by Karim-30** [comment]
@sketchydroide  I updated my Proposal, here is how it looks like

before : 


https://user-images.githubusercontent.com/108357004/178076116-6058f285-871e-4ea3-9b7c-41b743b8392e.mov



after : 

https://user-images.githubusercontent.com/108357004/178075095-46a30f08-d074-462f-990d-388ef3a7e4dd.mov

**Comment by rushatgabhane** [comment]
@Karim-30 I don't think we should vertically center `(edited)`
<img width="176" alt="image" src="https://user-images.githubusercontent.com/29673073/178140712-20e97d6a-d044-463e-95c2-0cacacee8f9b.png">

**Comment by jeet-dhandha** [comment]
Just a question does Expensify provide with payments for the solutions provided by freelance developers, as they can just fix the code from the provided proposal without giving out the payments.

**Comment by rushatgabhane** [comment]
@jeet-dhandha good question. If an issue is labeled `Exported` and your proposal is accepted, you'll be paid.

I'd strongly recommend that you read https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#payment-for-contributions

**Comment by Karim-30** [comment]
>I don't think we should vertically center (edited)

@rushatgabhane You are right, using `alignItems: 'baseline'` instead of `alignItems: 'center'` fixed it.

Result : 

![fix alignment](https://user-images.githubusercontent.com/108357004/178292193-3b7697f4-3bc8-413f-b18c-a2d0a118f940.png)

**Comment by rushatgabhane** [comment]
🎀 👀 🎀 C+ reviewed
@sketchydroide I like @Karim-30's [proposal](https://github.com/Expensify/App/issues/9709#issuecomment-1179351547).

**Comment by sketchydroide** [comment]
Yeah, I'm happy with it as well

**Comment by trjExpensify** [comment]
@Karim-30 can you apply to the job on upwork when you get a chance?

**Comment by trjExpensify** [comment]
PR is in review. @sketchydroide looks like it's awaiting your approval and we can merge this?

**Comment by rushatgabhane** [comment]
@trjExpensify just FYI, we had a regression  #10123 
(so half pay for C+)

**Comment by trjExpensify** [comment]
Ah, why didn't the labels get added? 🤔 Processing payments now.

**Comment by trjExpensify** [comment]
Cool, done!
