### ISSUE TITLE
[HOLD for payment 2022-07-25] [$250] Statement does not load in NewDot Desktop App

### ISSUE THREAD

**Issue by thienlnam** [Expensify/App#9713]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/docs/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Break down in numbered steps
1. Click on the statement from Concierge on NewDot Desktop
<img width="520" alt="Screen Shot 2022-07-05 at 12 09 00 PM" src="https://user-images.githubusercontent.com/30609178/177398410-ea7c4cf1-16bb-4d04-80bb-f7a4b8f12012.png">

## Expected Result:
Describe what you think should've happened
Should show the statement

## Actual Result:
Describe what actually happened
Shows a blank screen
<img width="898" alt="Screen Shot 2022-07-05 at 12 07 13 PM" src="https://user-images.githubusercontent.com/30609178/177398753-fad5fa7c-888f-40b7-927e-32177d01c97a.png">

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?
Will have to view the statement on a non desktop application

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App x
- Mobile Web

**Version Number:** 
**Reproducible in staging?:** 
**Reproducible in production?:** 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Upwork job link:** https://www.upwork.com/jobs/~01993059e1414b86b4

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by thienlnam** [comment]
cc @justinpersaud since you've helped us on previous configuration issues - do we just need to include https://www.expensify.com/ in the frame-ancestors list?

**Comment by justinpersaud** [comment]
`www.expensify.com` is in the list already. Is it not valid without the protocol? Maybe that was a typo?

**Comment by thienlnam** [comment]
I assume it's not valid without the protocol, www.expensify.com is put there from the hostname [here](https://github.com/Expensify/Salt/blob/main/shared_pkgs/nginx/files/conf.d/www.conf.template#L50-L50).  We explicity imply it in these other configs https://github.com/Expensify/Salt/blob/3c6ac677d3a3e6d0dd7ee57b04fab523957525b6/shared_pkgs/nginx/files/conf.d/integrations.conf.template#L20-L20 so I'm guessing we can just start by adding it?

**Comment by justinpersaud** [comment]
yeah let's try that and see? according to the spec it should work though: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/frame-ancestors

>Warning: If no URL scheme is specified for a host-source and the iframe is loaded from an https URL, the URL for the page loading the iframe must also be https, per the [Does URL match expression in origin with redirect count?](https://w3c.github.io/webappsec-csp/#match-url-to-source-expression) section of the CSP spec.

**Comment by justinpersaud** [comment]
wait, are you using the staging server on newdot? could it be because the request is coming from https://staging.new.expensify.com --> www.expensify.com

**Comment by thienlnam** [comment]
Not on the staging server on newDot, unless it's something that's automatically added to my expensify account.  Good point on the staging though, we'd also want this to work on staging so I will also add `https://staging.expensify.com/` as well

**Comment by parasharrajat** [comment]
@thienlnam This one needs to be done on front end. Doing this change will fix it. 

1. Add the following line after https://github.com/Expensify/App/blob/35a41d99fe751d9952fa5401bd38c87d6bf3d5ba/desktop/main.js#L166.
```
if(details.responseHeaders['content-security-policy']){
                        details.responseHeaders['content-security-policy']  = details.responseHeaders['content-security-policy'].map(v => v.startsWith('frame-ancestors') ? v + ` app://*` : v);
                    }
```

2.  Add the following line after https://github.com/Expensify/App/blob/35a41d99fe751d9952fa5401bd38c87d6bf3d5ba/desktop/main.js#L170.                    
```
  if(details.responseHeaders['content-security-policy']){
                        details.responseHeaders['content-security-policy']  = details.responseHeaders['content-security-policy'].map(v => v.startsWith('frame-ancestors') ? v + ` http://localhost:${process.env.PORT}` : v);
                    }
```


Option solution could be remove the CSP response headers all along. I am not sure of the security implications so I won't suggest.

**Comment by thienlnam** [comment]
> Add the following line after

What's the reasoning behind this, how come it isn't being recognized currently?

> Other solution could be to remove the CSP response headers all along. I am not sure of the security implications so I won't suggest it.

Yeah this is unlikely what we'd want to do

**Comment by parasharrajat** [comment]
On the desktop app, the app is loading with localhost URL on dev and with `app://` on production. CSP policy will fail if URLs do not match what is specified in ` frame-ancestors`. 

Previously we never used frames anywhere AFAIK so `frame-ancestors` CSP was never applicable to any API calls.
As we are using electron, we can do anything with the API calls, either disable the policy completely before building the app(very bad) Or intercept the requests calls.

**Comment by thienlnam** [comment]
Interesting, thanks for the context.  I agree this actually seems to be an issue we can fix on the front-end.  Seems like we've already been running into this with access-control-allow-origin.

We could just update our config to allow app://expensify... but I think the solution you provided makes more sense.  Do you want to take this issue?

**Comment by parasharrajat** [comment]
Yup, I can do that.

**Comment by mvtglobally** [comment]
@thienlnam not sure if this is related https://github.com/Expensify/App/issues/9670

**Comment by thienlnam** [comment]
@mvtglobally Yup, good catch - this is the same issue so I'm closing the other one

**Comment by thienlnam** [comment]
We've been aware of the blank page - we don't return anything in various scenarios and we've talked about adding some kind of error message so it doesn't look like a bug.  The way you mentioned is one way we could handle it, we've also thought about just returning an error dialog but we haven't really fleshed out the design of what this would look like yet so it's something that we need to do first

**Comment by michaelhaxhiu** [comment]
Job posted here - https://www.upwork.com/jobs/~01993059e1414b86b4, and invited Rajat :)

**Comment by michaelhaxhiu** [comment]
paid
