### ISSUE TITLE
FEATURE REQUEST: Real-time translate markdown in the chat box - reported by @ahmdshrif

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#9733]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/docs/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
## Problem :

When pasting stylized text (e.g. a word like "Bold") into the New Expensify chat box it shows the markdown style before it is actually applied (i.e. "*" on either side of "Bold") rather then after the markdown style is applied (i.e. exactly how it was copied "Bold"). This can be confusing to users without knowledge of markdown styles making them less confident in what the output of their chat box text will look like.

## Solution :

Translate markdown styles in realtime (i.e. before a message is actually sent) when typing in the New Expensify chat box. This shows the user exactly how the text will look before they send it.

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.79-0
**Reproducible in staging?:** 
**Reproducible in production?:** 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 

https://user-images.githubusercontent.com/43995119/177471091-1c638e61-6ddd-4465-a3ae-f0ef200d1743.mov

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @ahmdshrif
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1656504234548779

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by parasharrajat** [comment]
I thought this was already rejected on Slack. Even if we want to rethink it. A better Problem statement is needed to think it through.

**Comment by MitchExpensify** [comment]
Cool, I found the problem hard to understand at first glance but on reading the thread I'd suggest something closer to:

"Problem:

When pasting stylized text (e.g. a word like "*Bold*") into the New Expensify chat box it shows the markdown style before it is actually applied (i.e. "*" on either side of "Bold") rather then after the markdown style is applied (i.e. exactly how it was copied "*Bold*"). This can be confusing to users without knowledge of markdown styles making them less confident in what the output of their chat box text will look like.

Solution:

Translate markdown styles in realtime (i.e. before a message is actually sent) when typing in the New Expensify chat box. This shows the user exactly how the text will look before they send it."

As a first step before bringing to What's Next I can update the original post here if you all agree that is clearer and accurate to the proposal

**Comment by MitchExpensify** [comment]
Checking on best next steps internally, will report back

**Comment by MitchExpensify** [comment]
Hey @ahmdshrif! Thanks for your patience. Thank you for the feature request however we're not going to move forward with it at this time. The problem is not one actively experienced by Expensify users. Thats not to say it won't be in the future and we can revisit it if that turns out to be the case
