### ISSUE TITLE
Back button doesn't work in the Chase bank screen - reported by dhairyasenjaliya

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#9736]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/docs/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to settings add payment method as bank account
2. Add bank account in "Chase bank"
3. here on chase bank login page press back

## Expected Result:
Should go back or exit plaid

## Actual Result:
not able to close webview or go back to exit webview

## Workaround:
Unknown 

## Platform:

Where is this issue occurring?

- iOS

**Version Number:** 1.1.79-0
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y (This has been an issue in the OldDot mobile app as well) 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation  

https://user-images.githubusercontent.com/43995119/177472209-82858778-2043-4b6e-ae9b-a2623e43de9d.MP4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @dhairyasenjaliya 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1655439172268599

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by cdraeger11** [comment]
I was not looking at the correct dashboard.

**Comment by pecanoro** [comment]
@cdraeger11 were you able to reproduce this on iOS? I don't have an iPhone so I haven't been able and it works fine in other platforms.

**Comment by dhairyasenjaliya** [comment]
@pecanoro this issue only exists on iOS

**Comment by pecanoro** [comment]
This issue doesn't seem to be a thing anymore in newer versions so I am going to close it! Thanks, @NikkiWines for testing it on an iPhone!!
