### ISSUE TITLE
When user logged in on few devices, messages dont arrive 

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#9743]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/docs/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login on few devices 
2. Go to a chat with someone
3. Have them send you a message

## Expected Result:
User should receive messages on all devices 

## Actual Result:
User is not receiving messages on mobile device. User needs to log out and log back in to see the messages 

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Web
- iOS
- Mobile Web

**Version Number:** 1.1.79-0
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 

https://user-images.githubusercontent.com/43995119/177590305-4f4f75d9-68bd-4db4-8bf1-fd399d1ffdc2.MOV

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @tgolen 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1655752298184599

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by luacmartins** [comment]
Slack thread https://expensify.slack.com/archives/C01GTK53T8Q/p1657119509766089. Seems like the fix is to wait for Web-E prod deploy.

**Comment by mvtglobally** [comment]
@luacmartins this is no longer repro 
https://user-images.githubusercontent.com/43995119/178092209-3c8cf998-abcb-43df-a33f-b0bd100b6812.MOV

**Comment by luacmartins** [comment]
Ok! Seems like we can close this issue then!
