### ISSUE TITLE
Web - Group Chat - Fub menu is opened after use the Enter Key for expensifail account

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#9745]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/docs/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue was found when executing PR** https://github.com/Expensify/App/pull/9626

## Action Performed:
1. Go to staging.new.expensifail.com
2. Log in with applausetester+0901abb@applause.expensifail.com/Feya87Katya
3. Click on Fub menu
4. Use the down key twice
5. Tan click Enter Key

## Expected Result:
 Fub menu is not opened after use the Enter Key for expensifail account

## Actual Result:
 Fub menu is opened after use the Enter Key for expensifail account

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.79.17

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**Email or phone of affected tester (no customers):** expensifail account

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/177598730-90f0143e-a46e-48f4-9d48-5dda516586ca.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause- Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Julesssss** [comment]
Unable to reproduce this on Web. Removing the deployBlocker label for now.

**Comment by kbecciv** [comment]
@Julesssss Can you try with specific account? I can reproduced it all the time.

https://user-images.githubusercontent.com/93399543/178119310-d5a92967-afd4-4fdf-8500-f8d5427ee51b.mp4
