### ISSUE TITLE
Line Breaks - Copying & Pasting Line breaks does not work

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#9767]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/docs/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Pre- Condition: User has copied a line break previously
1. Access staging.new.expensify.com
2. Sign into any valid account
3. Click on any chat
4. Attempt to paste the line break in the chat box

## Expected Result:
The user expects the line break to show correctly like:
"I'm a text with

line

breaks"

## Actual Result:
The line break does not work and text displays as:
"I'm a text withlinebreaks"

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:**  v1.1.79-17

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/177868729-8cbb9308-91d5-4e5c-9270-55ef314984f5.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** 
Applause internal team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment]
Duplicate https://github.com/Expensify/App/issues/9608
