### ISSUE TITLE
Send Money - "Looks like you're offline" message displayed on top of the Send button

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#9808]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/docs/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensify.com
2. Log in with expensifail account
3. Click on Fub menu and Select Send money
4. Put amount and select Continue
5. Turn off the internet connection

## Expected Result:
"Looks like you're offline" message displayed under Send button

## Actual Result:
"Looks like you're offline" message displayed on top of the Send button

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.82.5

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

![image (30)](https://user-images.githubusercontent.com/93399543/178055559-92148c1c-6d86-426b-9872-1a56b947a983.png)

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by thesahindia** [comment]
I don't think this is a bug. It is probably intentional and if we move the offline text below the button the position of the button will change.

cc: @Luke9389  @roryabraham

**Comment by parasharrajat** [comment]
This should be on hold until we touch offline functionality like other issues.

**Comment by kadiealexander** [comment]
Holding on publishing this until I get clarification on the above.
