### ISSUE TITLE
Seeing the chat without any room name or avatar, after getting removed from the workspace - reported by @thesahindia

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#9819]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/docs/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login to account A
2. Invite account B to your workspace
3. Login to account B at a different browser or tab and send some messages in the room
4. Switch browser and remove account B
5. Now go back and refresh and try to search the announce room using the workspace name

## Expected Result:
 It should switch to the previous chat as after getting removed from workspace the room disappears.

## Actual Result:
The room disappears from the LHN but the chat stays.

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.79-0
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 

https://user-images.githubusercontent.com/43995119/178180286-97648977-eca7-4447-a94f-8114e94d8015.mov

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @thesahindia
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1656187667917399?thread_ts=1656187450.584779&cid=C01GTK53T8Q

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by yuwenmemon** [comment]
Hmmm.. Probably something we need to take care of with a Pusher fix.

**Comment by yuwenmemon** [comment]
No update

**Comment by yuwenmemon** [comment]
Looking into this further this should be fixed with https://github.com/Expensify/Expensify/issues/211560 - so gonna close this out in favor of that issue
