### ISSUE TITLE
[HOLD for payment 2022-09-27][$500] Adding an asterisk * after each backtick ` hides the text inside the backticks - reported by @adeel0202

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#9822]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/docs/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open any chat
2. In the chat input, enter some text inside the backticks to quote it
3. After each backtick, append an asterisk like this: `*test`*
4. Send the message

## Expected Result:
The text doesn't hide, appears as typed 

## Actual Result:
The text hides, no text appears

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.79-0
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 

https://user-images.githubusercontent.com/43995119/178181820-ec93655e-4258-44b5-a9d7-3a1ecfd496e0.mov

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @adeel0202
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1656492429217749

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by stephanieelliott** [comment]
This confused me at first until I watched the video, updated the issue body to be more clear. This seems sort of edge case (you would probably only run into it in if you were making a typo) but feels very buggy so opting to raise for a fix- raising to eng but feel free to close if you disagree that this should be fixed.

**Comment by parasharrajat** [comment]
Please hold this until https://expensify.slack.com/archives/C02NK2DQWUX/p1657544731979729

**Comment by MariaHCD** [comment]
Looks like we're proposing to replace ExpensiMark. No updates on that [conversation](https://expensify.slack.com/archives/C02NK2DQWUX/p1657544731979729) just yet.

**Comment by flodnv** [comment]
We have discussed internally and reached the following conclusion: The handful of existing bugs in our markdown parser are solvable (we already have some proposals). Moving to a 3rd party library would come with its own set of new problems that we'd have to spend time solving. As such, Expensify engineers have decided to have contributors keep solving the Expensimark parsing bugs. Should there be problems other than parsing, these can be discussed separately.

**Comment by adelekennedy** [comment]
[internal](https://www.upwork.com/ab/applicants/1555326087021547520/job-details)
[external](https://www.upwork.com/jobs/~01215b5a906cd37bf4)

**Comment by adelekennedy** [comment]
Upped the price, still waiting for proposals!

**Comment by chiragsalian** [comment]
Demoting to monthly. It still has value but it is quite the edge case and won't currently affect people under normal scenarios.

**Comment by adelekennedy** [comment]
Will not increase the price on this

**Comment by aimane-chnaif** [comment]
**Proposal**

This happens because quote is overlapped with bold text.
Let me take example with this one:
```
`*test`*
```

According to regex replacement rules in ExpensiMark, `inlineCodeBlock` is more priority than `bold`
So `inlineCodeBlock` is applied first
```
<code>*test</code>*
```

After that, `bold` is applied:
```
<code><bold>test</code></bold>
```
this is issue. we should avoid this conversion and keep
```
<code>*test</code>*
```
which is rendered as `*test`*

**Solution**
To do this, we need to update regex to exclude the case of code block start (<code>) before bold (*) text.
We're already excluding the case of code block end (</code>) after bold text. So we can do similar way.

https://github.com/Expensify/expensify-common/blob/e0ec0b9abca4d7b417ba0b016f8725856cfeeece/lib/ExpensiMark.js#L138-L145

updated regex:
```
                name: 'bold',
                regex: /(?<!(<pre>|<code>|<a>)[^>]*)\B\*((?!\s).*?\S)\*\B(?![^<]*(<\/pre>|<\/code>|<\/a>))/g,
                replacement: '<strong>$2</strong>',
```
So if <pre> or <code> or <a> is before bold text, this isn't considered as bold and will not apply regex.

Final result: `*test`*

**Comment by chiragsalian** [comment]
Looks good to me too. Feel free to create the PR @aimane-chnaif.

**Comment by adelekennedy** [comment]
@rushatgabhane @aimane-chnaif @adeel0202 will you apply to the job [here](https://www.upwork.com/jobs/~010b675bfe11a4a9d8)? I had to repost it

**Comment by adelekennedy** [comment]
Reposted [here](https://www.upwork.com/jobs/~010b675bfe11a4a9d8)!

**Comment by adeel0202** [comment]
@adelekennedy still not able to apply.

<img width="1057" alt="Screenshot 2022-09-21 at 6 42 49 PM" src="https://user-images.githubusercontent.com/13783842/191520081-62a9eef3-5afb-4eb0-b6a4-67ac2618484e.png">

**Comment by rushatgabhane** [comment]
likewise

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by adeel0202** [comment]
> @adeel0202 bump :) https://github.com/Expensify/App/issues/9822#issuecomment-1253733240

@rushatgabhane you probably wanted to bump @adelekennedy 😄

**Comment by adelekennedy** [comment]
Hmm this seems like it could be an Upwork issue - the job is open and public. I just edited and refreshed [here](https://www.upwork.com/jobs/~010b675bfe11a4a9d8)

**Comment by adeel0202** [comment]
@adelekennedy, there is already a contract going on for this job on my Upwork, can you please pay me for that one instead of hiring for another one? I would really appreciate that. Same goes for [this issue](https://github.com/Expensify/App/issues/7436#issuecomment-1255819330).

**Comment by adelekennedy** [comment]
Hmm - it's a public job from my side:
<img width="165" alt="Screen Shot 2022-09-28 at 9 42 00 AM" src="https://user-images.githubusercontent.com/60450566/192840031-e146dc76-9867-483c-8077-3c75dfcbb5cf.png">

I just refreshed again if that works [here](https://www.upwork.com/jobs/~010b675bfe11a4a9d8)

**Comment by adelekennedy** [comment]
Hired you both!

**Comment by adeel0202** [comment]
@adelekennedy please check my [comment above](https://github.com/Expensify/App/issues/9822#issuecomment-1260458050)

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (Second week)

**Comment by adelekennedy** [comment]
paid!
