### ISSUE TITLE
[HOLD for payment 2022-07-25] [$250] IOS - Edit message border broken in iOS - Reported by Santhosh-Sellavel

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#9824]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/docs/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open new dot in iOS device
2. Open any chat report with messages sent by you
3. Edit a message by long pressing on the message & select 'Edit comment'

## Expected Result:
Message box border should not be broken

## Actual Result:
Border is broken in top & bottom corner on left side of the message box. Refer Attachment

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- iOS

**Version Number:** 1.1.82-0
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 

![Simulator Screen Shot - iPhone 13 - 2022-07-01 at 00 17 32](https://user-images.githubusercontent.com/43995119/178186649-b9eb42e2-f33e-4729-bba8-c9f89eb0012a.png)

**Upwork job URL:** https://www.upwork.com/jobs/~01469a1060686f9fd9
**Issue reported by:** @Santhosh-Sellavel 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1656615386577219

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by roryabraham** [comment]
@thesahindia's proposal looks good to me. Going to make this external and then let's get this on Upwork.

**Comment by roryabraham** [comment]
@MitchExpensify I preemptively assigned @thesahindia here so feel free to send an offer as soon as the Upwork job is created. @thesahindia feel free to submit a PR whenever you're ready.

**Comment by michaelhaxhiu** [comment]
Upwork job link - https://www.upwork.com/jobs/~01469a1060686f9fd9

I invited both @Santhosh-Sellavel & @thesahindia to the job, also.

**Comment by thesahindia** [comment]
> I invited both @Santhosh-Sellavel & @thesahindia to the job, also.

Applied and raised the PR.

**Comment by parasharrajat** [comment]
PR is reviewed and merged. 

:ribbon: :eyes: :ribbon:  C+ reviewed

**Comment by michaelhaxhiu** [comment]
All parties are paid.
