### ISSUE TITLE
[$250]  There is no way to write ~~~~ (without the code block) 

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#9826]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/docs/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open any chat 
2. Type ~~~~ inside any text (~~~~, ~~asdf~~, and even ~asdf~)
3. Send message

## Expected Result:
There is no way to write ~~~~ (without the code block) 

## Actual Result:
In slack, I can do ~~~~, ~~asdf~~, and even ~asdf~ if I hit cmd + z when it turns it into a strikethrough (otherwise it's asdf). In NewDot, I can't figure out how to do these - if I try to escape a tilde with a backslash, it just does a strike through that as well.

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.82-0
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 

![Screen Shot 2022-07-11 at 12 19 19 AM](https://user-images.githubusercontent.com/43995119/178187793-80260710-485e-40f4-9042-36f2047bb3a3.png)

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @rafecolton 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1657145525104199

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by bfitzexpensify** [comment]
Upwork job [here](https://www.upwork.com/jobs/~01d6546f63d8a63f34)

**Comment by jeet-dhandha** [comment]
Please change strikethrough regex in
Path `node_modules/expensify-common/lib/ExpensiMark.js`

`regex: /\B~~((?=\S)((?:\\[\s\S]|~(?!~)|[^\s~\\]|\s(?!~~))+?))~~\B(?![^<]*(<\/pre>|<\/code>|<\/a>))/g`

<img width="237" alt="Screenshot 2022-07-12 at 10 13 15 AM" src="https://user-images.githubusercontent.com/78416198/178410250-38cc8c3e-e50c-461b-bd0a-8fee8c53ea44.png">

------------------------------------------------------------------------------------------------------
I have already added proposal on Upwork under email id jeet.dhandha.2511@gmail.com. 
**If any changes are required then please do tell.**

**Comment by rushatgabhane** [comment]
@jeet-dhandha can you please explain the reasoning/process that led you to this regex?

**Comment by jeet-dhandha** [comment]
@rushatgabhane I checked available markdown libraries which use the official markdown regex for strikethrough and tried implementing it in our app. And it worked. 😃

**Comment by jeet-dhandha** [comment]
> @jeet-dhandha can you please explain the reasoning/process that led you to this regex?
> 
> And just to confirm, you mean to modify https://github.com/Expensify/expensify-common/blob/dfcfea347de5b458ab1b6cd6e1558c3ff2a5c525/lib/ExpensiMark.js#L148 ?
@rushatgabhane Yes i am pointing to that regex only.

**Comment by jeet-dhandha** [comment]
@rushatgabhane Tell me if anything is not working will try to improve the Regex Accordingly.

**Comment by rushatgabhane** [comment]
>  I checked available markdown libraries which use the official markdown regex for strikethrough and tried implementing it in our app

Oh that's fantastic, which library exactly? Can you please link the code

**Comment by jeet-dhandha** [comment]
@rushatgabhane Also we can refer to markdown official documentation https://www.markdownguide.org/ in future to update our apps regexes accordingly.

**Comment by rushatgabhane** [comment]
@jeet-dhandha I ran the tests for [expensify-common](https://github.com/Expensify/expensify-common/tree/main). And it looks like we're replacing the html `<del>` tag with `~`

eg: `<del>text here</del>` -> `~text here~`

I'd prefer that we rely on html's `<del>` tag instead

**Comment by jeet-dhandha** [comment]
@rushatgabhane Please try the updated regex
`regex: /\B~((?=\S)((?:\\[\s\S]|~~(?!~)|[^\s~\\]|\s(?!~~))+?))~\B(?![^<]*(<\/pre>|<\/code>|<\/a>))/g`
<img width="274" alt="Screenshot 2022-07-12 at 2 04 37 PM" src="https://user-images.githubusercontent.com/78416198/178447355-e03cf7e3-2c42-4b1d-9f03-bbb59b2304db.png">
<img width="271" alt="Screenshot 2022-07-12 at 2 04 28 PM" src="https://user-images.githubusercontent.com/78416198/178447364-6e8219e1-d6d9-4c0d-bb8b-fd3410bbfbce.png">

**Comment by jeet-dhandha** [comment]
@rushatgabhane Updated regex
`regex: /\B~((?=\S)((?:\\[\s\S]|~~(?!~)|[^\s~\\]|\s(?!~))+?))~\B(?![^<]*(<\/pre>|<\/code>|<\/a>))/g`

and tested with `npm run test`

<img width="1439" alt="Screenshot 2022-07-12 at 2 31 20 PM" src="https://user-images.githubusercontent.com/78416198/178452857-2cf4bc71-b4cc-4f53-ae1f-c13713d7ee85.png">

**Comment by jeet-dhandha** [comment]
Can you please provide me a brief info on the issue's we will face with this regex.

**Comment by rushatgabhane** [comment]
@jeet-dhandha there is no issue, I just wanna understand the code before we can ship it.

**Comment by jeet-dhandha** [comment]
We had to add more checks on string to remove unwanted matches.

**Comment by rushatgabhane** [comment]
That helps, thank you!

🎀 👀 🎀 C+ reviewed
@flodnv I like @jeet-dhandha's [proposal](https://github.com/Expensify/App/issues/9826#issuecomment-1181508387).

**Comment by parasharrajat** [comment]
I suggest we hold this issue until an internal discussion is concluded.

**Comment by jeet-dhandha** [comment]
@parasharrajat Please, keep me posted on the issue.

**Comment by parasharrajat** [comment]
Link to internal discussion https://expensify.slack.com/archives/C02NK2DQWUX/p1657544731979729

**Comment by jeet-dhandha** [comment]
@parasharrajat I m still not a part of Expensify's Slack, so please send me an invite my mail id is jeet.dhandha.2511@gmail.com

**Comment by parasharrajat** [comment]
That is supposed to be a internal discussion and we will share weekly updates on this issue about the status.

**Comment by jeet-dhandha** [comment]
Got It. Thanks for the update.

**Comment by flodnv** [comment]
@jeet-dhandha I have invited you to the public channel, however this discussion is being discussed outside of this public channel at the moment. We'll provide an update next week.

**Comment by jeet-dhandha** [comment]
@flodnv Any updates on this one ❓

**Comment by rushatgabhane** [comment]
@jeet-dhandha nothing yet

**Comment by flodnv** [comment]
I'm working part time this week, so I'll probably be taking a closer look at this next week as this isn't high priority. Thank you for your patience.

**Comment by flodnv** [comment]
We have discussed internally and reached the following conclusion: The handful of existing bugs in our markdown parser are solvable (we already have some proposals). Moving to a 3rd party library would come with its own set of new problems that we'd have to spend time solving. As such, Expensify engineers have decided to have contributors keep solving the Expensimark parsing bugs. Should there be problems other than parsing, these can be discussed separately.


@bfitzexpensify please hire @jeet-dhandha

**Comment by jeet-dhandha** [comment]
@flodnv Thanks for the update. Appreciate it. 
### 😃👍

**Comment by jeet-dhandha** [comment]
Upwork link : https://www.upwork.com/freelancers/~01921c050b587a3859

**Comment by jeet-dhandha** [comment]
@bfitzexpensify PR: https://github.com/Expensify/expensify-common/pull/461

**Comment by jeet-dhandha** [comment]
Getting this error when running web/desktop app : 

https://github.com/Expensify/expensify-common/pull/461#issuecomment-1206857251

**Comment by sketchydroide** [comment]
I will create the PRs for it

**Comment by flodnv** [comment]
Is this fixed? I don't think so? 😕 
<img width="202" alt="image" src="https://user-images.githubusercontent.com/4164921/185894966-a7ae5cbe-0170-4a4b-9708-da15e944631a.png">

**Comment by flodnv** [comment]
Thanks for linking the PR, I missed it 🤦 👍

**Comment by bfitzexpensify** [comment]
Cool - all done!
