### ISSUE TITLE
The "unread" dot in the Chrome tab icon is so small as to be almost invisible

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#9829]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/docs/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open app and login in browser
2. From another account send couple messages 
3. Check the "unread" indicator in the tab 

## Expected Result:
User should be able to see that there are unread messages 

## Actual Result:
User can see unread message indicator, but the The "unread" dot in the Chrome tab icon is so small as to be almost invisible

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Web

**Version Number:** 1.1.82-1
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 

<img src="https://user-images.githubusercontent.com/43995119/178320426-ca4440d1-eea4-4a4c-afa5-42145979a4c1.png" width="40%" height="40%">

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @quinthar 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1657511930574589

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by robertjchen** [comment]
Yep, definitely not ideal! Wanted to loop in @Expensify/design on this: could we possibly get a mockup of what a new "unread" indicator would look like? It sounds like we might be changing it to a green color in addition to making it larger?

**Comment by shawnborton** [comment]
Yup and perhaps we want to add some logic here:
- green is the default for unreads, etc
- show red when there is an error

Though I'm not sure if we have any red brick road logic just yet...

**Comment by shawnborton** [comment]
Posted an idea [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1657587998576039?thread_ts=1657511930.574589&cid=C01GTK53T8Q)

<img width="998" alt="image" src="https://user-images.githubusercontent.com/2319350/178386365-6ff405db-9592-4659-be04-034be2d441ca.png">

**Comment by robertjchen** [comment]
Looks great! We just need to swap out https://github.com/Expensify/App/blob/main/web/favicon-unread.png and we should be good to go here.

**Comment by parasharrajat** [comment]
Won't be that simple if we are looking to add two different ones based on error or non-error state.

**Comment by robertjchen** [comment]
Agreed- maybe we can just narrowly-scope this for just the unreads first. The error state would require some planning and discussion, especially since how the way we surface errors may be changing.

**Comment by shawnborton** [comment]
Let me know if these images work: [Notification Dot.zip](https://github.com/Expensify/App/files/9136347/Notification.Dot.zip)

**Comment by robertjchen** [comment]
It's beautiful, thanks!

**Comment by robertjchen** [comment]
Need to test things out before opening it up for review.

**Comment by robertjchen** [comment]
Update before going OOO: working through the test/screenshots checklist in the PR.

**Comment by shawnborton** [comment]
Not overdue
