### ISSUE TITLE
[Expensify Help] Create a "coming soon" page

### ISSUE THREAD

**Issue by roryabraham** [Expensify/App#9830]
### Problem
We hijacked https://help.expensify.com/, which used to redirect to https://community.expensify.com/ to our new help site, which is not done yet.

### Why this is important
This means that users going to https://help.expensify.com/ will see docs that are not ready yet instead of the help site they're used to seeing.

### Solution
Create a "coming soon" page for the new help site that can direct users to the old help site. The link should say:

"Looking for our old help site?" and link to https://community.expensify.com/

The new ComingSoon page should be hosted at https://help.expensify.com/index.html, which will mean it's what users going to https://help.expensify.com/ will see. The current main page will be moved to https://help.expensify.com/main.html. Once we're ready to launch the site in production, we'll just delete the ComingSoon page and rename `main.html` back to `index.html`.

**Comment by michelle-thompson** [comment]
Posted in [Slack](https://expensify.slack.com/archives/C03TQ48KC/p1657581164933869?thread_ts=1657560051.442269&cid=C03TQ48KC), and we're good to go with this design:
![image](https://user-images.githubusercontent.com/43361905/178583546-2b85965b-fe05-4e90-82d5-625f0e6ea212.png)

Adding the engineering label now!

**Comment by michelle-thompson** [comment]
Actually, assigning @marcochavezf since you're implementing the help site

**Comment by marcochavezf** [comment]
Thanks for the design @michelle-thompson! Could you post here a link for the sand clock icon?

**Comment by michelle-thompson** [comment]
Here you go!
[Circle Hourglass.svg.zip](https://github.com/Expensify/App/files/9096744/Circle.Hourglass.svg.zip)

**Comment by marcochavezf** [comment]
Created this PR to add the coming soon page https://github.com/Expensify/App/pull/9869
