### ISSUE TITLE
Inbox -Using "Enter" Key in request Call modal causing modal reopening every time, blocking main page

### ISSUE THREAD

**Issue by MitchExpensify** [Expensify/App#9835]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/docs/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
Coming from [this /Expensify repo issue](https://github.com/Expensify/Expensify/issues/216734) cc @kavimuru 

## Action Performed:
1. Go to staging.expensify.com
2. Log in with any  account
3. Go to Accounts - Accounts details
4. On Secondary Logins page enter the phone number +17076414722 and saved it
5. Go back to Inbox
6. Use Enter Key to call Concierge

## Expected Result:
Able to Request a Call by using Enter Key

## Actual Result:
Using Enter Key in request Call modal causing page opens every time, blocking main page

## Workaround:
Unknown

**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/176504177-408ef894-a2d3-4d6a-9298-9bc5e0382a77.mp4

Tester login credentials - Email/Phone: applausetester+062922abb@applause.expensifail.com
Tester login credentials - Password: Feya86Katya

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by parasharrajat** [comment]
How is this affecting NewDot?

**Comment by MitchExpensify** [comment]
Shoot, you are right @parasharrajat .. I got confused by the external label my mistake
