### ISSUE TITLE
Payment  - Add payment method button is misaligned 

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#9838]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/docs/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensify.com
2. Log in with any account
3. Go Settings -Payments

## Expected Result:
Add payment button is not misaligned 

## Actual Result:
Add payment button is misaligned 

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.82.5

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation
![AddPayment](https://user-images.githubusercontent.com/93399543/178530186-5da41965-267c-4778-9bbf-e1c55d453bf7.png)
![Prod](https://user-images.githubusercontent.com/93399543/178535239-90eb842c-a5cb-460b-9e93-afb06f9251dc.png)

**Expensify/Expensify Issue URL:** 

**Issue reported by:** @mdneyazahmad & Applause - Interna Team

**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1657623654999409

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by roryabraham** [comment]
This is a pretty subtle visual bug that doesn't affect the app's usability. I don't think we should block deploy on this.

**Comment by AndrewGable** [comment]
Agree

**Comment by parasharrajat** [comment]
Note: Do test other screens as well. I think that this issue also affects them. Regression from https://github.com/Expensify/App/pull/9665.

It would be better to list down those pages and fix them all in this issue.
For example 
1. Extra margin under the button on RequestCallPage.
![image](https://user-images.githubusercontent.com/24370807/178556914-afceba14-24a6-48bb-bf1b-822c8cb01fb1.png)

**Comment by ctkochan22** [comment]
@Justicea83 do you mind if I steal this from you? This is a result of my own PR https://github.com/Expensify/App/pull/9665
