### ISSUE TITLE
After signing in on mobile, User is signed out of desktop

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#9875]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/docs/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login on Desktop app and use the app 
2. Navigate to mobile app and login with the same account 

## Expected Result:
User should be able to log in on multiple devices

## Actual Result:
User logged out after login on the app 

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- iOS
- Android
- Desktop App

**Version Number:** 1.1.78-8
**Reproducible in staging?:** need repro
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @stitesExpensify 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1657592646473099

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by conorpendergrast** [comment]
I wasn't able to reproduce this. Here's what I did: 
1. Sign in to the Mac desktop app
2. Signed out of the iOS app
3. Signed back in to the iOS app

@stitesExpensify Are you able to consistently reproduce this?

**Comment by conorpendergrast** [comment]
Oh, hmm, actually, the web app has been signed out for me. 

Here's what happened: 
1. I was signed in to the web app on desktop
2. I signed in to the Mac desktop app
2. I signed out of the iOS app
3. I signed back in to the iOS app
4. I was signed out of the web app on desktop automatically

So that's weird

**Comment by francoisl** [comment]
I can't reproduce the issue described. I tried with a combination of the web + desktop + mobile apps all logged in to the same account at the same time. I didn't get signed out on any platform and was also able to send and receive messages from all of them.

@conorpendergrast what app version were you on? I'm on v1.1.84-11 (staging) right now.

My hunch is that we're creating a new temp secondary login somewhere, and it invalidates the previous ones? (that's pure speculation though, haven't dug too much). 

These flows are also very likely to change with the N7 refactors, so for now I think we can keep this open and see if we can reproduce after the Signin flow refactors.

**Comment by francoisl** [comment]
Still can't reproduce, with 1.1.86-5 now.

And again, these flows are likely to change with the N7 refactorings - going to demote this to Monthly for now, and let's try again in a few weeks.

**Comment by conorpendergrast** [comment]
Sounds good!

Conor Pendergrast
Success Coach, Expensify

**Comment by francoisl** [comment]
Just tried again and still can't reproduce!
