### ISSUE TITLE
[HOLD] Move No QA PRs to a separate section of the checklist

### ISSUE THREAD

**Issue by roryabraham** [Expensify/App#9905]
### Problem
Sometimes our deploy checklists get very large. When there are many documentation, helpsite, or GitHub Actions PRs in the checklist, those PRs typically don't need any QA.

As a time-saver/QOL improvement for Applause and deployers, we automatically check off any PR on the checklist if the title is prefixed with `[No QA]`.

However, in some cases such as [this one](https://github.com/Expensify/App/issues/9847), there are a ton of `[No QA]` PRs. This makes life more difficult for Applause and for the deployer, because they have to sift through many distracting checklist items to find the ones that they actually tested.

According to @isagoico:

> Since we manually export the results it would be perfect to have all the ones that we actually executed in a single section

I've also experienced this problem in a different way – as a deployer I want to quickly be able to see any PRs that aren't resolved yet and which may be blocking deploy. When normal PRs are mixed in with a large list of PRs that didn't undergo QA, it takes longer.

### Solution
Move `[No QA]` PRs to a separate section of the checklist, where they don't actually get checkboxes and instead are just listed out for audit/record-keeping/diff purposes.

**Comment by roryabraham** [comment]
Going to HOLD this on https://github.com/Expensify/App/issues/9999

**Comment by roryabraham** [comment]
Still on HOLD. @mountiny would you be interested in taking this one from me and tackling it alongside https://github.com/Expensify/App/issues/9999 ?

**Comment by mountiny** [comment]
Might be good to do alongside, although quite scared of the refactor there, definitely a stuff to work on after the Offshore 😄

**Comment by mountiny** [comment]
Working on higher level priorities still

**Comment by mountiny** [comment]
Since the PR we hodl this on was closed as low priority, do you think we should still do this? I think it is nice to have but also it is easy for QA to just check it off the first time they see the check list.

I will close this for now and if we will come back to polishing the deploy checklist experience and refactor, we should look into this. @roryabraham reopen if you disagree.
