### ISSUE TITLE
mWeb/Safari - Chat - Broken page layout for ##announce and ##admins rooms after navigate back to LHN

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#9915]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/docs/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Prerequisite: Create a new gmail account 
1. Login with the creds on the mWeb Safari
2. Create new Workspace (##announce and ##admins rooms should be generated)
4. Open newly created rooms ( ##announce and ##admins channels) and go back to LHN

## Expected Result:
Broken page layout for ##announce and ##admins rooms after navigate back to LHN

## Actual Result:
The user should be able to open newly created rooms without any issues

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Mobile Web/safari

**Version Number:** 1.1.84.11

**Reproducible in staging?:** Yes

**Reproducible in production?:**  Yes

**Email or phone of affected tester (no customers):** yuriy.turbo+ch3@gmail.com/Aa111111

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/179031711-d7b128e9-5b9a-42fe-9f61-6cf89580c683.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by robertjchen** [comment]
@parasharrajat Great catch, thanks! Looks like it's a dupe- will close this for now 👍  Thanks for the bug report @kbecciv
