### ISSUE TITLE
[$250] mWeb - Infinite loading displayed after navigate to links https://staging.new.expensify.com/new/chat or https://staging.new.expensify.com/search

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#9921]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue found during executing PR**https://github.com/Expensify/App/pull/9718

## Action Performed:
1. Open a incognito window and navigate to New Expensify.
2. Log in any account
3. Completely close that tab.
4. Open new tab again ad open one of these links:
a) https://staging.new.expensify.com/new/chat
b) https://staging.new.expensify.com/search

## Expected Result:
Log in page should be display

## Actual Result:
Infinite loading displayed after navigate to https://staging.new.expensify.com/new/chat or https://staging.new.expensify.com/search

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.84.11

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/179063156-b3ddc9e8-57fe-43c0-9957-54753b51ce27.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kevinksullivan** [comment]
https://www.upwork.com/jobs/~018397c33a924383ca

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by stitesExpensify** [comment]
Not overdue, not reproducible

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (Second week)

**Comment by kevinksullivan** [comment]
Assuming we close this out if we have 2 weeks of it not being reproducible?
