### ISSUE TITLE
Web - IOU - No onyxData with key country Code appeared in the call

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#9922]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found during executing PR** https://github.com/Expensify/App/pull/9801

## Action Performed:
1. Open App and login
2. Open the Network Tab
3. Click on FAB and select the option Request Money
4. Enter the amount now
5. Enter the phone number

## Expected Result:
onyxData with key country Code appeared in the call

## Actual Result:
No onyxData with key country Code appeared in the call

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.84.11

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** applausetester+31622@applause.expensifail.com/Qwerty123

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/179069823-562d92ac-16fa-4fee-8ad2-ea676f82301c.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by ctkochan22** [comment]
@kbecciv can you tell me which api command its supposed to be?

**Comment by kavimuru** [comment]
@ctkochan22, we don't see api command `OpenApp` in network activity.

**Comment by kavimuru** [comment]
@ctkochan22 Closing this issue, we have to open the console before logging in to account. It fixed this issue.

https://user-images.githubusercontent.com/43996225/179357867-6b8eea87-5e82-489d-a6fc-165d14a40c29.mp4
