### ISSUE TITLE
mweb - Split Bill - If users with long names are invited to split bill, the name will cut off

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#9927]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Access staging.new.expensify.com
2. Sign into any account
3. Tap "+" > "Split Bill" > Select any amount > "Next"
4. Select several users and pick some with longer names (Ex "Applausetester" user accounts)
5. Send the bill to create a new group

## Expected Result:
The user expects all names to fit on their device screen

## Actual Result:
The longer names are cut off by device margin

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.84.11

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** applausetester+031722emilio@applause.expensifail.com/Utest123

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

![overlap](https://user-images.githubusercontent.com/93399543/179082203-9f8bf213-771f-4c5c-8d44-aa5c43740c62.jpg)

https://user-images.githubusercontent.com/93399543/179076820-b94b70b5-7d33-42bb-a226-1fe25d1180a0.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment]
Similar issue https://github.com/Expensify/App/issues/9287

**Comment by chiragsalian** [comment]
Yup looks like this [issue](https://github.com/Expensify/App/issues/9287) fixed the problem reported here. Closing this. Feel free to reopen if i missed something.
