### ISSUE TITLE
Web - New group - The blue frame in the search bar disappears when you select a new member

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#9929]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Click on the green + button
3. Click on the "New group" option
4. Start selecting participants using the mouse

## Expected Result:
The blue frame in the search bar should not disappear when you select a new member

## Actual Result:
The blue frame in the search bar disappears when you select a new member

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.84.11

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/179084987-150fb297-e770-4866-bdce-1a62b401c4d4.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Julesssss** [comment]
Minor, but seems valid.

**Comment by parasharrajat** [comment]
I don't think we can fix it or if this is a bug. When you click somewhere on the web, the focus is removed from the inputbox. This is normal. 

For example, 
1. just go to google.com.
2. Click on the search bar and search for something. 
3. After search is loaded, click again on the search bar. 
4. Now click anywhere on the page. 
5. Cursor is removed from search input.

**Comment by JmillsExpensify** [comment]
I agree with @parasharrajat and think we should close this issue. @Julesssss what do you think?
