### ISSUE TITLE
[HOLD]Android - Notification - Notifications leads to the wrong chat while online/offline, killed app

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#9930]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login to the app, open different chat
2. Kill the app
3. Tap on the received notification
4. Repeat while offline

## Expected Result:
It should open NewDot to the correct chat, and the new message should be available.

## Actual Result:
Wrong chat window is opened
The same behavior for offline/online scenario

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Android

**Version Number:** 1.1.84.11

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/179085984-1306a501-7924-4448-865f-0229fcfceaeb.mp4

https://user-images.githubusercontent.com/93399543/179086094-2cc278e2-be10-4fa2-a6ef-6d0959c5f91b.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment]
Two issues had been closed  https://github.com/Expensify/App/issues/9179  and https://github.com/Expensify/App/issues/6079

**Comment by alex-mechler** [comment]
cc @neil-marcellini @AndrewGable since both of you have worked on notifications in the past

**Comment by AndrewGable** [comment]
As mentioned in previous issues, if this is related to offline mode, I think we should wait until after the offline API refactoring is completed.
