### ISSUE TITLE
[$500] Update the package "jest" to the latest version 

### ISSUE THREAD

**Issue by adelekennedy** [Expensify/App#9941]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
coming from this issue https://github.com/Expensify/Expensify/issues/218314

> Snyk reported a HIGH severity vulnerability in Expensify/App:package.json.
> 
> More information about this issue can be found [here](http://security.snyk.io/vuln/SNYK-JS-JSONSCHEMA-1920922).
> 
> Snyk ID: SNYK-JS-JSONSCHEMA-1920922
> Package: json-schema
> Version: 0.2.3
> Language: js
> Date Introduced: 2022-07-04

from @flodnv:

```
$ npm list jest-cli [12:26:37]
new.expensify@1.1.84-11 /Users/flo/Expensidev/App
├─┬ jest@26.6.0
│ └── jest-cli@26.6.0 deduped
└── jest-cli@26.6.0
```

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by adelekennedy** [comment]
Posted to Upwork!
[Internal](https://www.upwork.com/ab/applicants/1547975231044284416/job-details)
[External](https://www.upwork.com/jobs/~010054e881404aca14)

**Comment by greg-schroeder** [comment]
Ah yes, we should update the package "jest" to the latest version, of course

**Comment by jeet-dhandha-lio** [comment]
https://github.com/Expensify/Expensify/issues/218314

Getting a 404 not found page on this link.

**Comment by sketchydroide** [comment]
Not sure if this is supposed to be an `internal` or `extenal` issue, asking on slack

**Comment by sibelius** [comment]
what is hard about it ?

just upgrade, fix the breaking changes and make the tests pass ?

**Comment by jboniface** [comment]
@adelekennedy this needs an upwork job when you get a chance (i unassigned myself since you were assigned to manage this in the E/E repo)

**Comment by flodnv** [comment]
@sibelius nothing hard per se (hopefully), indeed it's just about:
- Reading the changelog, figuring out problems
- Upgrading, fixing problems
- Testing everything
- Shipping it

**Comment by adelekennedy** [comment]
[internal](https://www.upwork.com/ab/applicants/1551584319245205504/job-details)
[external](https://www.upwork.com/jobs/~01d4dc67c36922b74d)

**Comment by adelekennedy** [comment]
no proposals just waiting!

**Comment by parasharrajat** [comment]
### Proposal. 

There are a couple of challenges to this. Out of all the biggest one is that setImmediate is removed from jest https://github.com/facebook/jest/pull/11222 and but react-native still uses that. So far, I think upgrading RN will fix that. 

For now, we can do the following to upgrade the version. I have done a combined upgrade as a lot of things are interconnected. 

Here is the diff. 
```diff
diff --git a/jest/assetFileTransformer.js b/jest/assetFileTransformer.js
new file mode 100644
index 000000000..a4b1692fc
--- /dev/null
+++ b/jest/assetFileTransformer.js
@@ -0,0 +1,23 @@
+/**
+ * Overide the facebook's assetTransformer
+ */
+
+/* eslint-env node */
+
+const path = require('path');
+const createCacheKeyFunction = require('@jest/create-cache-key-function')
+    .default;
+
+module.exports = {
+    // Mocks asset requires to return the filename. Makes it possible to test that
+    // the correct images are loaded for components. Essentially
+    // require('img1.png') becomes `Object { "testUri": 'path/to/img1.png' }` in
+    // the Jest snapshot.
+    process: (_, filename) => ({
+        code: `module.exports = {
+      testUri:
+        ${JSON.stringify(path.relative(__dirname, filename).replace(/\\/g, '/'))}
+    };`,
+    }),
+    getCacheKey: createCacheKeyFunction([__filename]),
+};
diff --git a/jest/setup.env.js b/jest/setup.env.js
new file mode 100644
index 000000000..9ca29055a
--- /dev/null
+++ b/jest/setup.env.js
@@ -0,0 +1 @@
+global.setImmediate = jest.useRealTimers;
diff --git a/package.json b/package.json
index c78f96b3c..1d8d72bad 100644
--- a/package.json
+++ b/package.json
@@ -134,8 +134,8 @@
     "@storybook/react": "^6.5.9",
     "@storybook/theming": "^6.5.9",
     "@svgr/webpack": "^5.5.0",
-    "@testing-library/jest-native": "^3.4.2",
-    "@testing-library/react-native": "^7.0.2",
+    "@testing-library/jest-native": "^4.0.5",
+    "@testing-library/react-native": "^11.0.0",
     "@vercel/ncc": "^0.27.0",
     "@welldone-software/why-did-you-render": "^6.2.0",
     "ajv-cli": "^5.0.0",
@@ -162,9 +162,10 @@
     "eslint-plugin-storybook": "^0.5.13",
     "flipper-plugin-bridgespy-client": "^0.1.9",
     "html-webpack-plugin": "^4.3.0",
-    "jest": "^26.5.2",
-    "jest-circus": "^26.5.2",
-    "jest-cli": "^26.5.2",
+    "jest": "^28.1.3",
+    "jest-circus": "^28.1.3",
+    "jest-cli": "^28.1.3",
+    "jest-environment-jsdom": "^28.1.3",
     "metro-react-native-babel-preset": "^0.66.2",
     "mock-fs": "^4.13.0",
     "portfinder": "^1.0.28",
@@ -188,7 +189,8 @@
   "jest": {
     "preset": "react-native",
     "transform": {
-      "^.+\\.jsx?$": "babel-jest"
+      "^.+\\.jsx?$": "babel-jest",
+      "^.+\\.(bmp|gif|jpg|jpeg|mp4|png|psd|svg|webp)$": "<rootDir>jest/assetFileTransformer.js"
     },
     "transformIgnorePatterns": [
       "node_modules/(?!react-native)/"
@@ -205,13 +207,17 @@
       "__DEV__": true,
       "WebSocket": {}
     },
-    "timers": "fake",
+    "fakeTimers": {
+      "enableGlobally": true,
+      "legacyFakeTimers": true
+    },
     "testEnvironment": "jsdom",
     "setupFiles": [
       "<rootDir>/jest/setup.js"
     ],
     "setupFilesAfterEnv": [
-      "@testing-library/jest-native/extend-expect"
+      "@testing-library/jest-native/extend-expect",
+      "<rootDir>/jest/setup.env.js"
     ]
   },
   "prettier": {
diff --git a/tests/utils/waitForPromisesToResolve.js b/tests/utils/waitForPromisesToResolve.js
index 97146e6a8..c7be34b67 100644
--- a/tests/utils/waitForPromisesToResolve.js
+++ b/tests/utils/waitForPromisesToResolve.js
@@ -1,3 +1,5 @@
+import {setImmediate} from 'timers';
+
 /**
  * Method which waits for all asynchronous JS to stop executing before proceeding. This helps test things like actions
  * that expect some Onyx value to be available. This way we do not have to explicitly wait for an action to finish
```
1. First upgrade or install the following packages: 
```json
   "jest": "^28.1.3",
    "jest-circus": "^28.1.3",
    "jest-cli": "^28.1.3",
    "jest-environment-jsdom": "^28.1.3",
```
2. Change jest config 
```json
"jest": {
    "preset": "react-native",
    "transform": {
      "^.+\\.jsx?$": "babel-jest",
      "^.+\\.(bmp|gif|jpg|jpeg|mp4|png|psd|svg|webp)$": "<rootDir>jest/assetFileTransformer.js"
    },
    "transformIgnorePatterns": [
      "node_modules/(?!react-native)/"
    ],
    "testPathIgnorePatterns": [
      "<rootDir>/node_modules/"
    ],
    "testMatch": [
      "**/tests/unit/**/*.[jt]s?(x)",
      "**/tests/actions/**/*.[jt]s?(x)",
      "**/?(*.)+(spec|test).[jt]s?(x)"
    ],
    "globals": {
      "__DEV__": true,
      "WebSocket": {}
    },
    "fakeTimers": {
      "enableGlobally": true,
      "legacyFakeTimers": true
    },
    "testEnvironment": "jsdom",
    "setupFiles": [
      "<rootDir>/jest/setup.js"
    ],
    "setupFilesAfterEnv": [
      "@testing-library/jest-native/extend-expect",
      "<rootDir>/jest/setup.env.js"
    ]
  },
```
3. react-native preset of jest is still using the old transformer. As I said to fix this RN version needs to upgrade. But that can't be done in this issue so on a temporary basis we can override that until RN is upgraded. 
We have to replace the `assetFileTransformer` transformer with our version. 
```js
/**
 * Overide the facebook's assetTransformer
 */

/* eslint-env node */

const path = require('path');
const createCacheKeyFunction = require('@jest/create-cache-key-function')
    .default;

module.exports = {
    // Mocks asset requires to return the filename. Makes it possible to test that
    // the correct images are loaded for components. Essentially
    // require('img1.png') becomes `Object { "testUri": 'path/to/img1.png' }` in
    // the Jest snapshot.
    process: (_, filename) => ({
        code: `module.exports = {
      testUri:
        ${JSON.stringify(path.relative(__dirname, filename).replace(/\\/g, '/'))}
    };`,
    }),
    getCacheKey: createCacheKeyFunction([__filename]),
};
```
which will be added as 
```js
  "transform": {
      ...
      "^.+\\.(bmp|gif|jpg|jpeg|mp4|png|psd|svg|webp)$": "<rootDir>jest/assetFileTransformer.js"
    },
``` 
3. To fix the `setImmediate not defined` we need to polyfill it. The person who removed it from jsdom has suggested it https://github.com/facebook/jest/issues/11511#issuecomment-855946609. I don't want to switch to node for now.

```js
// file setup.env.js
global.setImmediate = jest.useRealTimers;
``` 
this will be passed to `setupFilesAfterEnv` jest config.

4. Now, I have optionally upgraded because There might be compatibility issues. For now, I don't know the application of these packages in our app. 
```js
 "@testing-library/jest-native": "^4.0.5",
 "@testing-library/react-native": "^11.0.0",
```

**Comment by parasharrajat** [comment]
Proposal above will also fix https://github.com/Expensify/App/issues/10227.

**Comment by bfitzexpensify** [comment]
@sketchydroide if you can confirm it will fix https://github.com/Expensify/App/issues/10227 too, I'll close that issue out

**Comment by adelekennedy** [comment]
Not overdue

**Comment by sketchydroide** [comment]
Let's go with your change @parasharrajat

**Comment by adelekennedy** [comment]
Do we want to put this issue on Hold? @parasharrajat if we're waiting

**Comment by sketchydroide** [comment]
Any update @parasharrajat, no pressure, just removing Overdue and keeping the issue up to date

**Comment by adelekennedy** [comment]
not overdue

**Comment by adelekennedy** [comment]
@parasharrajat @sketchydroide it looks like [this](https://github.com/Expensify/App/issues/9941#issuecomment-1222798333) question hasn't been resolved yet?

**Comment by sketchydroide** [comment]
@parasharrajat to be honest I don't really know, maybe we can ask on slack?
also CC @flodnv

**Comment by flodnv** [comment]
Somehow the original vulnerability reported does not exist anymore. It looks like we updated the `json-schema` dependency through somewhere else. Given this doesn't provide much value anymore, and it's hard to do, I say let's do nothing.

**Comment by flodnv** [comment]
Do you think we should "cut our losses" and compensate you $500, or that you should continue investigating this for a while and we'll see later?

**Comment by flodnv** [comment]
Ah, ok. I guess we can keep tracking for a little while and see what happens

**Comment by sketchydroide** [comment]
@parasharrajat any update on this?

**Comment by parasharrajat** [comment]
The new PR is not yet merged https://github.com/software-mansion/react-native-reanimated/pull/3559.

**Comment by adelekennedy** [comment]
@parasharrajat @sketchydroide I see the above PR is merged - from the above I think you're [due for compensation](https://github.com/Expensify/App/issues/9941#issuecomment-1239329085) from the work you've done - does this need to be stay open or can we pay and close?

**Comment by parasharrajat** [comment]
Thanks for the bump. Let me check the latest state of the PR and I will update you.

**Comment by adelekennedy** [comment]
@parasharrajat going through my issues before ooo, what are next steps?

**Comment by parasharrajat** [comment]
Tried the new version. There are a few errors. I will try to fix those. PR is updated to the latest.

**Comment by kevinksullivan** [comment]
👋 just want to confirm what next steps look like here. @parasharrajat there are errors with the new version, which you will fix in your existing PR? Is that accurate?

**Comment by parasharrajat** [comment]
Yes, I will try to fix those and share an update as soon as possible.

**Comment by parasharrajat** [comment]
Tried a few things but had no luck. Will look more into this later.

**Comment by parasharrajat** [comment]
This is not blocking anything ATM. I will share an update asap. Working on some priorities.

**Comment by sketchydroide** [comment]
any update @parasharrajat, just trying to keep this updated.

**Comment by sketchydroide** [comment]
That seems ok, we might as well upgrade to the next one, and it seems everything is still working, if we need we can open it againSent from my iPhoneOn 12 Dec 2022, at 19:15, Rajat Parashar ***@***.***> wrote:﻿
I tried to solve the issue but unfortunately, I have no solution to the following error.
  ● Test suite failed to run

    TypeError: setImmediate is not a function

      22 | }
      23 |
    > 24 | LogBox.ignoreLogs([
         |        ^
setImmediate is directly used in RN and jsdom does not contain setImmediate. It is supported in node testEnvironment. But Tests will fail in node testEnvironment so we can't switch.
The latest changes can be seen here #10300.
Now, the jest 29 version is available which has many changes so I think there is no advantage of upgrading to jest 28.
For now, I think jest 26 is working great with the project and we don't need to upgrade as there are breaking changes.
I suggest we drop this upgrade.

**Comment by sketchydroide** [comment]
That seems ok, we might as well upgrade to the next one, and it seems everything is still working, if we need we can open it again
