### ISSUE TITLE
List Issues that are available to be worked on by contributors in product

### ISSUE THREAD

**Issue by puneetlath** [Expensify/App#9957]
# Problem
As Jeet mentioned here in Slack, it's not super easy to know which issues are currently available to work on. You can search via the Help Wanted label, but it's not that easy to get a list sorted by price and the `help wanted` list often contains issues that are currently on hold and thus aren't actually available. 

# Solution 
List the issues available directly in product in settings. Instead of having `view open jobs` link to the GH issues list, we can instead list the jobs directly. And ideally we would sort them by price (highest first) and filter out issues on hold. That way it would be a list of issues that are actually available to work on at that moment and prioritized by those that pay the most. 

<img width="351" alt="image (1)" src="https://user-images.githubusercontent.com/1371996/179571497-5313a900-66c3-41ab-a056-a3340eef55b2.png">

**Comment by puneetlath** [comment]
>This is something that an app should never have.

Mind expanding on this? Why not?

**Comment by parasharrajat** [comment]
IMO, listing the issues or technical stuff on a prod app won't be very useful for End-users. . At last, it is just my opinion.

**Comment by JmillsExpensify** [comment]
I agree with Puneet. In fact, I'd even go further and build this flow directly into the Global Create flow, like so:

 - `Earn Money`
    - 1Receive SNAP Assistance` - Links to https://www.expensify.org/snap-vax
    - `Report a bug`- Links to https://github.com/Expensify/App/issues/new/choose
    - `Fix a bug` - Links to https://github.com/Expensify/App/issues?q=is%3Aissue+is%3Aopen+no%3Aassignee
    - `Join Expensify` - links to https://we.are.expensify.com/#workwithus

**Comment by marcaaron** [comment]
I took a crack at whipping up an API endpoint for this. It should be relatively simple Github query and we can just sort them by price (most expensive first).

**Comment by marcaaron** [comment]
What information should these have? I'm thinking something like...

- price
- title
- url

Should be enough to get us going with something

**Comment by marcaaron** [comment]
Made a draft [here](https://github.com/Expensify/Web-Expensify/pull/34404)

**Comment by puneetlath** [comment]
Closing this issue in favor of https://github.com/Expensify/Expensify/issues/223645. Posted your draft PR there @marcaaron!
