### ISSUE TITLE
On Edit comment, after selecting emoji composer is visible for a second - Reported by @jayeshmangwani

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#9972]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open report
2. Edit any message
3. Select emoji in Edit comment
4. For a second or less Composer will be visible and then it will be hidden

## Expected Result:
Composer should not be displayed after selecting the emoji

## Actual Result:
Composer will be displayed for a second after selecting the emoji

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Android

**Version Number:** 1.1.82-0
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 

https://user-images.githubusercontent.com/43995119/179663750-d028528f-86a1-48a1-a5f7-dbfa4d793d78.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @jayeshmangwani
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1656618517573919

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lschurr** [comment]
I couldn't reproduce this on iPhone, so maybe it's just an Android issue.

**Comment by Justicea83** [comment]
I also couldn't reproduce this on iPhone.

**Comment by Christinadobrzyn** [comment]
Testing this on an Android, I'm not able to reproduce this, the keyboard stays hidden when tapping Edit Comment and the emoji icon. Can you confirm if you still see this issue @jayeshmangwani 

<img src="https://user-images.githubusercontent.com/51066321/180325014-23c5b516-aa11-4885-9234-f20692d596c4.gif" width=" 200" height="400" />

**Comment by jayeshmangwani** [comment]
> Testing this on an Android, I'm not able to reproduce this, the keyboard stays hidden after tapping Edit Comment and the emoji icon. Can you confirm if you still see this issue @jayeshmangwani. Closing for now.
> 
> <img alt="" height="400" src="https://user-images.githubusercontent.com/51066321/180325014-23c5b516-aa11-4885-9234-f20692d596c4.gif"> [ <img alt="180325014-23c5b516-aa11-4885-9234-f20692d596c4.gif" height="400" src="https://user-images.githubusercontent.com/51066321/180325014-23c5b516-aa11-4885-9234-f20692d596c4.gif"> ](https://user-images.githubusercontent.com/51066321/180325014-23c5b516-aa11-4885-9234-f20692d596c4.gif) [ ](https://user-images.githubusercontent.com/51066321/180325014-23c5b516-aa11-4885-9234-f20692d596c4.gif)

@Christinadobrzyn  Yes, this issue is still happening and this issue is happening in this gif too,
please check in this attached gif you will see after selecting the emoji there is a flicker happening when the composer is visible for a few seconds and then gone hidden

**Comment by jayeshmangwani** [comment]
@Christinadobrzyn this issue is still happening, and issue is not about keyboard, issue is that we can see chat input for a second and then it will disappear, ![Screenshot_20220802-222757_Chrome.jpg](https://user-images.githubusercontent.com/35371050/182432399-5b78fb10-6c80-457c-8219-4b2b438aa128.jpg)
