### ISSUE TITLE
Copy to clipboard context-menu is enabled on attachments - reported by @parasharrajat

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#9974]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to any chat on web.
2. Send an attachment.
3. Right click on the attachment or hover over it to see the context menu

## Expected Result:
No copy to clipboard option should be shown as this is not yet implemented correctly for attachments.

## Actual Result:
Copy to clipboard option is shown on images that copies HTML which is not useful at all for the user.

## Workaround:
Unknown 

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.85-0
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 
![Screen Shot 2022-07-19 at 12 11 56 AM](https://user-images.githubusercontent.com/43995119/179663019-6ee2998f-62b1-4934-80fa-0e739f679765.png)

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @parasharrajat
**Slack conversation:** [
](https://expensify.slack.com/archives/C01GTK53T8Q/p1656707539152899)
[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by parasharrajat** [comment]
This is already being fixed in https://github.com/Expensify/App/issues/9660

**Comment by ntrepanier** [comment]
Closing for https://github.com/Expensify/App/issues/9660
