### ISSUE TITLE
[$250] Phone number given at the example isn't a valid number it has 9 digits - reported by @Puneet-here

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#9979]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to concierge chat
2. Click phone icon
3. Enter an alphabet
4. Press Call me

## Expected Result:
The number at error message example should be a valid number

## Actual Result:
The number isn't a valid number

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.85-0
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
<img width="360" alt="Screenshot 2022-07-07 at 2 33 28 AM" src="https://user-images.githubusercontent.com/43995119/179665764-d50211e0-8096-4492-8396-4c60c39e9ab6.png">

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @Puneet-here
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1657142374202149

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Puneet-here** [comment]
### Proposal

Need to change the number to `+15005550006`  or `+447782339811` (we are already using these numbers on some other places) at:-
https://github.com/Expensify/App/blob/03a2422207ceecaf8ed6a8c24b77558df8f2a848/src/languages/en.js#L84
https://github.com/Expensify/App/blob/03a2422207ceecaf8ed6a8c24b77558df8f2a848/src/languages/es.js#L84

also shouldn't we use one same number here too?
https://github.com/Expensify/App/blob/03a2422207ceecaf8ed6a8c24b77558df8f2a848/src/languages/en.js#L583
https://github.com/Expensify/App/blob/03a2422207ceecaf8ed6a8c24b77558df8f2a848/src/languages/en.js#L860

**Comment by kevinksullivan** [comment]
Heh, nice catch!

**Comment by kevinksullivan** [comment]
https://www.upwork.com/jobs/~0187f2a7b5616f036e

**Comment by hamzashakeel348** [comment]
Hi there, I read the bug and I already started working on it. I submitted a proposal on Upwork Job post as well. You can check there.

**Comment by hamzashakeel348** [comment]
Can I get credentials to login and to check the updates, as I am stuck on login.
<img width="1440" alt="Screenshot 2022-07-28 at 1 08 41 AM" src="https://user-images.githubusercontent.com/55921857/181362816-76db432b-bc3e-4d80-9cc4-6f4853b61751.png">
?

**Comment by Puneet-here** [comment]
@hamzashakeel348, you need to create your own account to login.

**Comment by hamzashakeel348** [comment]
@Puneet-here  I am trying to create it, but it is giving "Looks like you're offline. Please check your connection and try again." error.

**Comment by Puneet-here** [comment]
Are you on localhost:8080 ?
Also try reading [this](https://github.com/Expensify/App/blob/main/README.md#local-development), it might help.

**Comment by hamzashakeel348** [comment]
Yes, I am on Localhost:8080.

**Comment by hamzashakeel348** [comment]
@Puneet-here  Here you can see the results of my update, phone no mentioned above in the comments is no rendering, I think so this is what was required, you can guide me further.
<img width="340" alt="Screenshot 2022-07-28 at 1 28 59 AM" src="https://user-images.githubusercontent.com/55921857/181366137-89a2f443-c7cf-43fd-a235-9c90fc37d300.png">

**Comment by Puneet-here** [comment]
@hamzashakeel348, you have to post a proposal here about what changes you will make and you have to mention where you will be making them (link of specific code)

You can check the closed issues (fixed ones) in the repo to find how things work.
Also, I will suggest you to check other issues with the help wanted label on it and propose solution there as this is simple issue and I have already added the solution [here](https://github.com/Expensify/App/issues/9979#issuecomment-1188615172).

**Comment by hamzashakeel348** [comment]
@Puneet-here  I already post the proposal above in the comments, as you said that this issue already got resolved, but recently an hour ago your team posted an upwork job for it, so I was supposed to do so by following that post.

Let me know what to do for it now, in the meanwhile I am looking for other issues.

**Comment by Puneet-here** [comment]
I meant I have already commented the solution, also you have to post a proposal like [this](https://github.com/Expensify/App/issues/9979#issuecomment-1188615172). You have to link the code, where you will be making the changes.

**Comment by rushatgabhane** [comment]
> also shouldn't we use one same number here too

@Puneet-here I think they look fine

**Comment by rushatgabhane** [comment]
@tgolen I like @Puneet-here's [proposal](https://github.com/Expensify/App/issues/9979#issuecomment-1188615172)

🎀 👀 🎀 C+ reviewed

**Comment by tgolen** [comment]
Thanks for looking at that proposal. Since it's referenced in several different places, could we move that number to the CONST file and have everything reference it from there?

**Comment by Puneet-here** [comment]
Yeah, we can do that.

**Comment by tgolen** [comment]
Great, thanks! I'll approve the proposal on that assumption then.

**Comment by Puneet-here** [comment]
Just a question which number are we planning to use? 
`+15005550006` or `+447782339811`

**Comment by hamzashakeel348** [comment]
@tgolen  I also proposed the same idea, but in a different way :).

**Comment by rushatgabhane** [comment]
@Puneet-here +1 is fine given that majority of the users are US based

**Comment by rushatgabhane** [comment]
@hamzashakeel348 sorry, but I don't see your proposal

**Comment by Puneet-here** [comment]
Can I raise the PR now?

**Comment by Puneet-here** [comment]
> Can I raise the PR now? Or wait to get assigned?

**Comment by rushatgabhane** [comment]
@Puneet-here feel free to raise a PR
you'll get assigned eventually

**Comment by kevinksullivan** [comment]
Hired @rushatgabhane @Puneet-here

**Comment by Puneet-here** [comment]
I have raised the PR.
@kevinksullivan, I think there was some mistake can you send me the offer again. It's not available anymore.

**Comment by kevinksullivan** [comment]
Weird, sorry @Puneet-here . Looks like the offer went through this time. Let me know if you're able to accept it!

**Comment by Puneet-here** [comment]
> Weird, sorry @Puneet-here . Looks like the offer went through this time. Let me know if you're able to accept it!

Thanks, I have accepted the offer now. Just a note that contract was set on hourly rate.

**Comment by tgolen** [comment]
not overdue

**Comment by tgolen** [comment]
Not overdue

**Comment by Puneet-here** [comment]
@kevinksullivan is OOO ( getting married 💍 🥂 ).
@tgolen please re-apply external label so that someone else can be assigned here.

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by adelekennedy** [comment]
checking on this, @rushatgabhane from the comment above it sounds like payment is due! Is that correct?

**Comment by adelekennedy** [comment]
reopened the job - just sent you an offer @rushatgabhane

**Comment by Puneet-here** [comment]
Hey @adelekennedy, the reporting and fixing compensation is also pending.

**Comment by anasdeyra** [comment]
**PROPOSAL**
If I understood the issue right there is a constant called EXAMPLE_PHONE_NUMBER in src/CONST.js that needs to be changed to a valid number

**Comment by tgolen** [comment]
@anasdeyra thanks for the proposal, but this has already been worked on and fixed. I think we're just trying to settle it up.

**Comment by kevinksullivan** [comment]
Sorry for the delay everyone, and thanks for stepping in @adelekennedy . Paid @Puneet-here for reporting + solving, and @rushatgabhane for C+.
