### ISSUE TITLE
Dev only - Console warning on Android

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#9982]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Run the app

## Expected Result:
No warning should display 

## Actual Result:
Console warning on Android is displayed 

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Android

**Version Number:** 1.1.79-0
**Reproducible in staging?:** N
**Reproducible in production?:** N 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 
<img width="415" alt="image - 2022-07-19T004915 955" src="https://user-images.githubusercontent.com/43995119/179667110-def7192d-6efd-42a0-b4ea-f17f7f351595.png">
<img width="419" alt="image - 2022-07-19T005001 801" src="https://user-images.githubusercontent.com/43995119/179667231-50b63165-e379-4d5f-a3c7-df06c79604e8.png">

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @roryabraham 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1657318646461389

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by amyevans** [comment]
It's low hanging fruit to clean up, so makes sense to open up to External contributors.

**Comment by parasharrajat** [comment]
First, one can't be solved ATM due to a third-party package and the second one is resolved.

**Comment by amyevans** [comment]
Ah good call, thanks for adding some color there! Closing.
