### ISSUE TITLE
[$500]  Link gets focused/outlined when visiting if keyboard was open - reported by @thesahindia

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#9983]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open :expensify: at mobile browser
2. Navigate to a chat
3. Send a link
4. Open keyboard and tap on the link
5. Come back to the chat

## Expected Result:
The behaviour should be consistent and the link shouldn't get focused

## Actual Result:
The link gets focused

## Workaround:
Unknown 

## Platform:

Where is this issue occurring?

- Mobile Web

**Version Number:** 1.1.84-0
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 

https://user-images.githubusercontent.com/43995119/179667414-19bb126d-2b47-4cd6-b2fa-2144ddb4e8c5.mov

**Upwork job URL:** https://www.upwork.com/jobs/~01021d4613b10840b0
**Issue reported by:** @thesahindia
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1657392259039819

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by michaelhaxhiu** [comment]
Upwork job link - https://www.upwork.com/jobs/~01021d4613b10840b0

Let's get this party started

**Comment by roryabraham** [comment]
Is it clear to us that this is an actual bug? I don't see any problem with the link getting focused. My vote would be to just close this.

**Comment by parasharrajat** [comment]
I also vote to close it. It is not really a but. Links are a focusable target on the web. They also support tab navigation. This outline is just indicating that they are focused. Clicking anywhere on the app should hide the border.

**Comment by mananjadhav** [comment]
I too agree, if clicking anywhere else doesn't remove the border then its a bug, else I don't think there's anything to do here.

**Comment by michaelhaxhiu** [comment]
Hm I'm in agreement with @thesahindia personally. I feel like it's not expected for that link to be highlighted or focused in this situation.

Would we want to follow this pattern across the board? Additionally, when I access a link in other chat platforms or software, this isn't the behavior that I've personally witnessed (and so it feels unexpected to me). 

Shall we post this in #expensify-open-source for some 👍 / 👎 input?

**Comment by roryabraham** [comment]
I mean, I agree that ideally we wouldn't see the outline here ... I was just wondering if it's a case where we should pick our battles a bit.

We can move forward with fixing this, but I'm going to make it a monthly and let's also cap its value kind of low (i.e: don't double indefinitely).

**Comment by michaelhaxhiu** [comment]
@roryabraham I'm super down with that approach of `monthly`, great call! Do you think we should cap it at $250 or $500?

(ps - I find myself doing the same approach of "pick our battles" sometimes too, and definitely get it. This is a small battle. But it feels like one worth winning for the sake of consistency -- esp if we control the pricing/priority like you suggested).

**Comment by roryabraham** [comment]
We can cap it at $500

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by michaelhaxhiu** [comment]
Oh wow, not reproducible anymore. @thesahindia are you still able to reproduce on your end? I can try again today too if you like.

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (Second week)
