### ISSUE TITLE
[HOLD for payment 2022-08-08] [$250] Upgrade the package babel-jest to the latest version

### ISSUE THREAD

**Issue by dylanexpensify** [Expensify/App#9990]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email [contributors@expensify.com](mailto:contributors@expensify.com) to request to join our Slack channel!
___

Coming from this issue: https://github.com/Expensify/Expensify/issues/218328

```
Snyk reported a HIGH severity vulnerability in Expensify/App:package.json.

More information about this issue can be found [here](http://security.snyk.io/vuln/SNYK-JS-TMPL-1583443).

Snyk ID: SNYK-JS-TMPL-1583443
Package: tmpl
Version: 1.0.4
Language: js
Date Introduced: 2022-07-04
```

Upwork job link - https://www.upwork.com/jobs/~0166a49f3c92894698

**Comment by dylanexpensify** [comment]
cc @flodnv coming from [this](https://github.com/Expensify/Expensify/issues/218328#issuecomment-1184653415)! Let me know if this is what you meant!

**Comment by parasharrajat** [comment]
I can do that...

**Comment by dylanexpensify** [comment]
Note: please do regression testing in case upgrading the version of the package breaks something else.

**Comment by parasharrajat** [comment]
can we merge https://github.com/Expensify/App/issues/9941 into this issue? Upgrading babel-jest will also require upgrading jest and necessary changes.

**Comment by neil-marcellini** [comment]
Sounds good to me.

**Comment by flodnv** [comment]
@parasharrajat sure! I did not realize that upgrading babel-jest will also require upgrading jest.

**Comment by parasharrajat** [comment]
I am not sure about that too but I feel like both can be combined after all both need to be upgraded.

**Comment by flodnv** [comment]
Right, but we prefer 1 PR per upgraded package (in package.json) please

**Comment by parasharrajat** [comment]
Got it. Can I submit the PR?

**Comment by parasharrajat** [comment]
But I don't think this affects the app in any way. let me know if I am wrong. This is dev dependency and only used by jest to babel transpile the code.

**Comment by flodnv** [comment]
Oh! I forgot this was a dev dependency. You are totally right 👍

**Comment by neil-marcellini** [comment]
What's the status on this?

**Comment by michaelhaxhiu** [comment]
Hm why is there no CM assigned to this?

**Comment by parasharrajat** [comment]
> What's the status on this?

I guess you merged the PR 8 days back.

**Comment by neil-marcellini** [comment]
Ok so after reading our [contributor process SO](https://stackoverflow.com/c/expensify/questions/8582) the `Exported` label was added meaning that an Upwork job was created. It should be linked here and @parasharrajat should be hired and paid on the correct date.

I think since `Exported` was added before `External` our normal process didn't trigger, but that' fine since @dylanexpensify is a contributor manager. Could you please link the Upwork job and take care of the next steps?

**Comment by michaelhaxhiu** [comment]
ah ha, looks like dylan [un-assigned me](https://github.com/Expensify/App/issues/9990#event-7020232693) as the CM after he asked his question about reproducibility

**Comment by michaelhaxhiu** [comment]
I'll just re-assign myself and get it back on track 🚂

**Comment by michaelhaxhiu** [comment]
Upwork job - https://www.upwork.com/jobs/~0166a49f3c92894698

**Comment by michaelhaxhiu** [comment]
@parasharrajat invited you to the job just now

**Comment by michaelhaxhiu** [comment]
Paid
