### ISSUE TITLE
Search - Not able to select a user while offline

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#9998]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Turn off the internet connection
3. Сlick on the magnifying glass to search for a new user
4. Try to select the user for chat

## Expected Result:
The user is selected and you go to chat with that user

## Actual Result:
Unable to select the user

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web

**Version Number:** v1.1.85-3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** applausetester+ihchat4@applause.expensifail.com  / Yulia1986Gerets
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/179805291-7d334afd-197f-440f-8230-04f0db82097d.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** Applause internal team
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by danieldoglas** [comment]
I'm discussing this on slack before giving my opinion but this will probably be blocked for now

**Comment by danieldoglas** [comment]
Ok this is blocked for now on this project https://github.com/Expensify/Expensify/issues/215566

**Comment by danieldoglas** [comment]
I'll close this since once that project is done this will be done as well
